### ISSUE TITLE
error during nfq_unbind_pf()

### ISSUE THREAD

**Issue by fedya** [bol-van/zapret#1]
Linux OpenWrt 3.18.44 #2 Wed Dec 14 18:26:07 UTC 2016 mips GNU/Linux

root@OpenWrt:/opt# /opt/zapret/nfq/nfqws --qnum=200 --hostspell=HOST
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
error during nfq_unbind_pf()

Такие же результаты и для бинарников из гита и если сам собираю.

**Comment by bol-van** [comment]
модул ядра xt_NFQEUE загруен ?
другие процессов nfq на этой очереди нет ?
изменяется ли что-то при смене qnum ?
если закоментировать // exit(1);  какие ошибки появляются ?
```
	printf("unbinding existing nf_queue handler for AF_INET (if any)\n");
	if (nfq_unbind_pf(h, AF_INET) < 0) {
		fprintf(stderr, "error during nfq_unbind_pf()\n");
		exit(1);
	}

```

**Comment by bol-van** [comment]
Проверил на системе без NFQUEUE. Результат именно такой
```
./nfqws  --qnum=3
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
error during nfq_unbind_pf()
```

**Comment by bol-van** [comment]
Решение 

opkg update
opkg install iptables-mod-nfqueue

зависимости подтянутся автоматом

**Comment by s6d** [comment]
этот модуль нужен nfnetlink_queue по крайней мере у меня так
