### ISSUE TITLE
English Wiki

### ISSUE THREAD

**Issue by ilkkaya** [bol-van/zapret#10]
English wiki please

**Comment by oguska** [comment]
That will be good for starting to use with openwrt.

**Comment by sgeto** [comment]
:+1

**Comment by bol-van** [comment]
Use google translate.  From russian to whatever you want

**Comment by sgeto** [comment]
Would you accept pull requests related to translation?

**Comment by bol-van** [comment]
Why not. Name files as https.eng.txt and readme.eng.txt
