### ISSUE TITLE
Вопрос о логике работы install_easy.sh

### ISSUE THREAD

**Issue by electrifying** [bol-van/zapret#1009]
Вопрос собственно в чем на одном из этапов когда даётся выбор, какой режим использовать при выборе хостлистов следующим этапом будет предложено скачивание  списка доменов и вот по умолчанию вместо подтверждающего ответа Y, стоит по дефолту не скачивать.  То есть получается, что даже при правильно сконфигурированой стратегии у нас ничего дурится не будет, так как gz архив с листом не скачан. Режим не скачивания листа по умолчанию в скрипте был сделан специально из-за того, что он весит почти 2 мб и на роутерах с маленьким объемом памяти это будет критично или по другим причинам? Можно ли сделать в скрипте по умолчанию положительный ответ на скачивания доменов при режиме hostlist?

**Comment by bol-van** [comment]
Он сделан для того, чтобы не жали йес йес йес некст некст некст ок ок ок.
Чтобы так не работало, и чтобы все действия были осмыслены

Без скачивания используются ipset/zapret-hosts-user.txt и ipset/zapret-hosts-user-exclude.txt
