### ISSUE TITLE
НЕ КАЧАЙТЕ

### ISSUE THREAD

**Issue by HEM1TY** [bol-van/zapret#1010]
![image](https://github.com/user-attachments/assets/d1d2e1a1-090d-4c99-82e2-65446289eb49)

Какого хера... или вы хотите сказать virustotal пиздит?

**Comment by bol-van** [comment]
Так. Первый пошел в бан

**Comment by Sk7Str1p3** [comment]
Почитал бы хоть принцип работы, ебанатик. Zapret перенаправляет траффик, поэтому антивирус паникует. Это описано в документации.
