### ISSUE TITLE
nfqws зависает

### ISSUE THREAD

**Issue by toxa70x4** [bol-van/zapret#102]
Проблема на Keenetic Ultra (KN-1011) c nfqws mips32r1-lsb, зависает. 

--dpi-desync=fake,split2 --dpi-desync-ttl=3

**Comment by bol-van** [comment]
Зависает что ? nfqws перестает обрабатывать пакеты
или не работает обход, вызывая зависания соединения ?

**Comment by toxa70x4** [comment]
Не работает обход, до перезапуска.

**Comment by bol-van** [comment]
--debug что выводит ?
если tcpdump-нуть внешний интерфейс провайдера, пакеты уходят с измененым IP на провайдерский (работает ли SNAT/MASQUERADE) ?

**Comment by toxa70x4** [comment]
Как получить --debug, если я запускаю через /opt/zapret/init.d/sysv/zapret ?

**Comment by toxa70x4** [comment]
![image](https://user-images.githubusercontent.com/79611111/164057902-162f7c9b-4aa5-4b24-9780-1990ec252b80.png)
debug просто зависло

**Comment by bol-van** [comment]
Имелось в виду
tcpdump -ni <внешний_интерфейс> tcp port 443

имеющаяся картинка не информативна

> debug просто зависло

Я вынужден догадываться что под этим имеется в виду

**Comment by toxa70x4** [comment]
![image](https://user-images.githubusercontent.com/79611111/164060190-2f753b26-fd43-4c88-a10e-eb18b0cd13b9.png)

/opt/zapret/nfq/nfqws --debug --user=nobody --dpi-desync-fwmark=0x40000000 --qnum=200 --dpi-desync=fake,split2 --dpi-desync-ttl=3
Когда престает работать, данные не бегут, могу только остановить процесс CTRL+C

**Comment by toxa70x4** [comment]
Это последние на чем остановился вывод debug
![image](https://user-images.githubusercontent.com/79611111/164061002-d38da960-27ba-46dd-a64d-8da21e692ae2.png)

В этот момент в tcpdump
![image](https://user-images.githubusercontent.com/79611111/164061048-62fc27fb-7f86-4b9c-b5af-46aa54baba54.png)

**Comment by toxa70x4** [comment]
Ускорение выключено.
kill -HUP $(pidof nfqws) проверю.

Если остановить  и запустить заново, работать начинает только после перезапуска правил iptables

**Comment by bol-van** [comment]
> Если остановить и запустить заново, работать начинает только после перезапуска правил iptables

тогда дело думаю не в nfqws, нет редиректа
проверьте не слетает ли правило NFQUEUE

**Comment by toxa70x4** [comment]
Кажется разобрался в чем дело. Убрал скрипт запуска из init.d и сделал /opt/etc/ndm/netfilter.d/000-zapret.sh

`#!/opt/bin/sh
/opt/zapret/init.d/sysv/zapret restart`

**Comment by toxa70x4** [comment]
Кажется разобрался в чем дело. Убрал скрипт запуска из init.d и сделал /opt/etc/ndm/netfilter.d/000-zapret.sh

```
#!/opt/bin/sh
/opt/zapret/init.d/sysv/zapret restart
```

**Comment by toxa70x4** [comment]
/opt/zapret/init.d/sysv/zapret тоже поправил, добавил:

```
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WS_USER=nobody
```
получилось:
```
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WS_USER=nobody

SCRIPT=$(readlink -f "$0")
EXEDIR=$(dirname "$SCRIPT")
```

**Comment by toxa70x4** [comment]
Возможно запуск в init.d стоит и оставить, а в netfilter.d сделать только restart-fw

**Comment by bol-van** [comment]
Эти скрипты и схема запуска создавались не мною, меня об этом спрашивать бесполезно
Надо чтобы был nfqws и было правило. Как вы его туда положите - это сами решайте

**Comment by bol-van** [comment]
В смысле если используются запускалки с топика с форума по кинетику

Моя запускалка sysv в принципе достаточно универсальна, но имеет ряд требований по наличию утилит и фич типа ipset
Если чего-то нет - может не срабатывать
У меня кинетика нет, проверять не на чем

**Comment by ops244** [comment]
привет, могли-бы вы скинуть файлы которые исправляли, как не пытался, все равно зависает на кинетике?

**Comment by toxa70x4** [comment]
Приветствую. Напиши в телеге. @kamchaA5706.
Я видно немного не понимаю о чем речь.

вс, 25 февр. 2024 г., 16:54 ops244 ***@***.***>:
