### ISSUE TITLE
какие опции запуска нужны чтобы повторить определённый функционал goodbyedpi?

### ISSUE THREAD

**Issue by kotsmotritnastul** [bol-van/zapret#104]
я запускаю goodbyedpi на винде с дефолтными опциями то есть
`-f 2 -e 2 --auto-ttl --reverse-frag --max-payload`
где 
```
-f <value>  set HTTP fragmentation to value
-e <value>  set HTTPS fragmentation to value
--auto-ttl    [a1-a2-m]  activate Fake Request Mode, automatically detect TTL and decrease
                          it based on a distance. If the distance is shorter than a2, TTL is decreased
                          by a2. If it's longer, (a1; a2) scale is used with the distance as a weight.
                          If the resulting TTL is more than m(ax), set it to m.
                          Default (if set): --auto-ttl 1-4-10. Also sets --min-ttl 3.
--reverse-frag           fragment (split) the packets just as --native-frag, but send them in the
                          reversed order. Works with the websites which could not handle segmented
                          HTTPS TLS ClientHello (because they receive the TCP flow "combined").
--max-payload [value]    packets with TCP payload data more than [value] won't be processed.
                          Use this option to reduce CPU usage by skipping huge amount of data
                          (like file transfers) in already established sessions.
                          May skip some huge HTTP requests from being processed.
                          Default (if set): --max-payload 1200.
```
какие опции zapret повторяют этот функционал? я понимаю что вопрос возможно тупой но я обычный гречневый васян и я запутался в простыне на главной странице проекта, да и честно говоря никогда в этом не разбирался, мне просто надо чтобы сайты открывались без костылей типа впн.

**Comment by bol-van** [comment]
Для определения стратегии обхода имеется скрипт blockcheck.sh
на него и надо ориентироваться

**Comment by kotsmotritnastul** [comment]
я запустил, скрипт вернул

```
curl_test_https_tls12: nfqws strategy for ipv4 rutracker.org not found

clearing nfqws redirection

* SUMMARY
ipv4 rutracker.org curl_test_http : tpws not working
ipv4 rutracker.org curl_test_http : nfqws not working
ipv4 rutracker.org curl_test_https_tls12 : tpws not working
ipv4 rutracker.org curl_test_https_tls12 : nfqws not working

```
на винде всё работало в goodbyedpi - как можно на линуксе достичь того же результата?

**Comment by bol-van** [comment]
Linux  в виртуалке ? Если так, то обязателен режим bridge. nat работать не будет
Если нет, то нужно прикрепить полный лог

**Comment by kotsmotritnastul** [comment]
программа запущена на реальном железе. fedora 35, провайдер телеком сервис, серый айпи, мне провайдер выдаёт айпи с 10.х.х.х

как сделать логи? сделал crtl+f "логи" по простыне на главной странице но не нашёл, среди скриптов тоже не нашёл того который делает логи.

**Comment by kotsmotritnastul** [comment]
кроме того я заметил что когда включён zapret соединение отображается в кде как ограниченное а дискавер не может ни загрузить программы ни загрузить обновления.

но через консоль можно сделать и то и другое.

**Comment by bol-van** [comment]
Цитата из простыни :
> Чтобы записать вывод blockcheck.sh в файл, выполните : ./blockcheck.sh | tee /tmp/blockcheck.txt

> кроме того я заметил что когда включён zapret соединение отображается в кде как ограниченное а дискавер не может ни загрузить программы ни загрузить обновления.

Боюсь, что я долго буду гадать над возможными причинами, если вы не в состоянии самостоятельно выполнить диагностику и разобраться

**Comment by kotsmotritnastul** [comment]
извините, это была моя вина и я неверно подошёл к программе, очевидно что я сначала запустил её а потом блокчек.

сейчас когда я выполнил sudo systemctl stop zapret и sudo systemctl disable zapret блокчек написал мне

```
!!!!! curl_test_https_tls12: working strategy found for ipv4 rutracker.org : nfqws --dpi-desync=fake,split2 --dpi-desync-ttl=3 !!!!!

clearing nfqws redirection

* SUMMARY
ipv4 rutracker.org curl_test_http : tpws --methodeol
ipv4 rutracker.org curl_test_http : nfqws --dpi-desync=disorder --dpi-desync-ttl=3
ipv4 rutracker.org curl_test_https_tls12 : tpws not working
ipv4 rutracker.org curl_test_https_tls12 : nfqws --dpi-desync=fake,split2 --dpi-desync-ttl=3

```
как мне добавить эти параметры к запуску программы? это как-то через команды системд делается?
на всякий случай вот полный вывод блокчека https://rentry.co/heou8

и ещё, вы не будете против если я как-нибудь попробую разбить простыню и добавить её к проекту в виде коротких викистатей? ну типа "как запустить и остановить службу, как включить и отключить автозагрузку", "как приложить дамп для багрепорта", "как запускать программу с разными параметрами" и т.п.

**Comment by bol-van** [comment]
> sudo systemctl disable zapret

Это было лишним. Достаточно было сделать stop
disable относится к автозапуску при старте системы

> как мне добавить эти параметры к запуску программы? это как-то через команды системд делается?

в install_easy выбрать режим nfqws и согласиться на редактирование параметров
в редакторе их поменять в соответствии с обнаруженной стратегией

> и ещё, вы не будете против если я как-нибудь попробую разбить простыню и добавить её к проекту в виде коротких викистатей?

думаю не стоит. Если это делать, то надо переделывать всю документацию.

**Comment by kotsmotritnastul** [comment]
спасибо огромное, всё вроде начало открываться. 

я не предлагал убирать простыню, я имел в виду добавить в вики-раздел проекта такие статьи. я уверен что 90% ищут именно их, а разбираться в технических особенностях того как работает программа не всем охота, её как правило ставят просто чтобы сайты начали открываться.

**Comment by kotsmotritnastul** [comment]
кстати сейчас запустил sudo systemctl status zapret и оно мне написало

`мая 02 10:05:51 localhost-live.Dlink systemd[1]: /etc/systemd/system/zapret.service:10: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your ser>`

это не создаст мне в будущем проблемы с системой?

**Comment by bol-van** [comment]
> это не создаст мне в будущем проблемы с системой?

не создаст

**Comment by bol-van** [comment]
> я не предлагал убирать простыню, я имел в виду добавить в вики-раздел проекта такие статьи. я уверен что 90% ищут именно их, а разбираться в технических особенностях того как работает программа не всем охота, её как правило ставят просто чтобы сайты начали открываться.

Возможно, имеет смысл сделать некий "quick start", где описано примерно то, что описал в этом issue
Но мне не нравится другое. Чем ниже будет "порог входа", тем больше меня будут долбать тупыми вопросами. А сейчас кто с низкой квалификацией видят простыню и сразу отсюда убегают

Я много раз везде писал, что целевая аудитория "чайники" меня не интересует

**Comment by kotsmotritnastul** [comment]
ну, я вполне себе чайник и не убежал от простыни - бежать-то всё равно некуда.

опять же, использовать эту программу или нет - это не вопрос желания. никто сюда не приходит с мыслью "чёт мне без всякой веской причины захотелось использовать обход дпи, ай какая простыня страшная, всё мне расхотелось". это вопрос необходимости. если человеку **необходимо** чтобы сайт открывался не через впн, не через тор, не через прокси а нативно то он будет долбиться в issuies, пытаться что-то выкопать из стены текста и т.п. а так хоть с этими вопросами долбиться не будет тратя своё и ваше время.

впрочем настаивать не буду, решать всё равно только вам.

**Comment by bol-van** [comment]
Написал краткую инструкцию для самых типичных случаев 

https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt

**Comment by kotsmotritnastul** [comment]
спасибо. я тоже просуммировал то что тут узнал, это больше напоминалка для себя но если кто-то будет гуглить и наткнётся на эту issuie то может ему пригодится https://rentry.co/dhnda

**Comment by bol-van** [comment]
> https://rentry.co/dhnda

Для себя - неплохая памятка, но рассчитана на конкретный случай
Linux - достаточно разношерстная система. Разные системы запуска и разные менеджеры пакетов
openwrt - вообще отдельный случай
Про BSD системы вообще не говорю

Потому написал свой quick_guide  без конкретных copy-paste действий, а по понятиям
Иначе это будет новая простыня в стиле "если-то", и при таком копи пастном подходе будет уж точно бесконечное количество вопросов, если люди не понимают и просто вставляют

**Comment by kotsmotritnastul** [comment]
ну, я думаю человек который сидит на арче уже морально готов тратить 90% своего времени не на использование компа а на чтение документации, а человек который понимает что такое openwrt и не боится окирпичить свой роутер тем более не будет читать эти гайды для гречневых неосиляторов и сразу нырнёт в простыню.

**Comment by bol-van** [comment]
Вот и мне так подумалось
linux - все таки не винда, если уж нырнул - будь готов
Но, согласен, какой-то quick start не помешает
