### ISSUE TITLE
Adding a license to a repository

### ISSUE THREAD

**Issue by ataniazov** [bol-van/zapret#107]
You can include a license in your repository to make it easier for other people to contribute. You’re under no obligation to choose a license and it’s your right not to include one with your code or project. But generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

**Comment by bol-van** [comment]
You are wrong. license is present in docs folder

**Comment by ataniazov** [comment]
I'm sorry I didn't notice license. If you include a detectable license in your repository, people who visit your repository will see it at the top of the repository page.
[Adding a license to a repository
](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

BTW Thanks for awesome project.
