### ISSUE TITLE
Как использовать QUIC bypass?

### ISSUE THREAD

**Issue by rockenren** [bol-van/zapret#111]
Довольно глупый вопрос, но все же.
Что необходимо сделать, для того чтобы использовать QUIC bypass?

Пробовал добавить в config параметры из комментариев кастомного скрипта, эффекта не вижу, проверял на https://cloudflare-quic.com.

OpenWRT, iptables, nfqws, РФ.

Параметры nfq: --dpi-desync=fake,split2 --dpi-desync-ttl=2

**Comment by bol-van** [comment]
Автоматически магия не сработает. Стандартные режимы никак не работают с quic
Необходимо использовать вариант custom со скриптом  custom-nfqws-quic4all
То есть :
cp /opt/zapret/init.d/openwrt/custom-nfqws-quic4all /opt/zapret/init.d/openwrt/custom
В config :
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake"
MODE=custom

**Comment by rockenren** [comment]
Заработало, спасибо.
Логику custom режима понял теперь.
