### ISSUE TITLE
QUIC

### ISSUE THREAD

**Issue by toxa70x4** [bol-van/zapret#115]
Никак не могу заставить работать QUIC в сетях Дом.Ру

На ipv6 адреса все без проблем, на ipv4 не хочет. Хотя затык с Google пропал.

Подскажите, что делать или браузер сам считает, что по http/2 быстрее?

**Comment by bol-van** [comment]
`Никак не могу заставить работать QUIC в сетях Дом.Ру`

каким образом заставляли ?

` браузер сам считает, что по http/2 быстрее?`

такое тоже бывает. он сам решает что ему лучше

**Comment by toxa70x4** [comment]
Через custom скрипт, пробовал 3 варианта.
--dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_short_header.bin
--dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-fake-unknown-udp=/opt/zapret/files/fake/quic_short_header.bin --dpi-desync-cutoff=n2
--dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-fake-unknown-udp=/opt/zapret/files/fake/quic_short_header.bin --dpi-desync-cutoff=d2

**Comment by bol-van** [comment]
Все правильно, только в последней версии nfqws фейк пейлоад уже начинается с 0x40, вместо всех нулей, так что файл не обязателен. У меня в таком варианте все нормально пробивается, но в самом деле броузер не всегда все запросы делает по quic.
Например, в самом начале соединения он сначала должен долбануться по h2, и только получив ответ о поддержке h3, он следующие сессии может начать с h3. Но поскольку h2 уже по факту есть, зачем ее дропать, заново выполняя пусть и быстрый, но все же handshake h3 ?  Потому там часть запросов продолжает проходить по h2

**Comment by bol-van** [comment]
Лучший тест - через curl, собранный с quiche.  Сейчас это все пока еще highly experimental. Дистрибутивы не шипят curl с поддержкой http3. Потому придется самому собрать.
Им и подергать разные ресурсы с ключом --http3. Тогда он даже и пытаться не будет лезть по tcp

**Comment by toxa70x4** [comment]
![image](https://user-images.githubusercontent.com/79611111/174691775-adb9d415-3e1d-49fb-b73d-ed12b493909d.png)
vk работать не хочет.
Через VPN нет проблем.

**Comment by toxa70x4** [comment]
А если вообще выключить запрет, все работает.
![image](https://user-images.githubusercontent.com/79611111/174693744-73c0cb3b-949e-43f5-af3b-9779380aa5e0.png)

**Comment by bol-van** [comment]
Вк что-то ремонтирует с QUIC. Он снял апгрейд на h3. Броузеры лезут только по h2

**Comment by toxa70x4** [comment]
Через warp проблем нет, вк нормально работает в браузере через h3, вижу по network

**Comment by bol-van** [comment]
В любом случае, есть универсальные лекарства против такой проблемы, если она возникает

1) Включить vk.com в zapret-hosts-user-exclude.txt . Заресолвить через /opt/zapret/ipset/get_exclude.sh
2) Добавить ограничитель для пакететов, чтобы они не воспринимались процессом сервера.
TTL использовать нельзя, потому что это сломает хром. Можно бэдсум, если обход прямо на роутере. С клиента - роутер может обрезать

**Comment by bol-van** [comment]
> Через warp проблем нет, вк нормально работает в браузере через h3, вижу по network

на клиенте в шарке нет даже попыток посылать что-либо по udp:443

**Comment by bol-van** [comment]
На моем прове с ТСПУ   curl --http3  https://vk.com   проходит нормально что с nfqws, что без

**Comment by toxa70x4** [comment]
Ну сейчас так и делаю. Юзаю ttl=3 и badsum, но использую поперу.

Через Warp
![image](https://user-images.githubusercontent.com/79611111/174719945-1f96bf4c-b4f6-458e-990f-3919fd962b18.png)

**Comment by bol-van** [comment]
> Юзаю ttl=3 и badsum

ttl=3 - может навредить любому броузеру на движке chrome. я не проверял на опере, но вероятно это так.
возможно, даже дело не в chrome, а в движке (вроде там тоже quiche), который что-то запрашивает у ОС, которая выставляет какой-то статус у сокета, если вдруг заметит TTL expired in transit.
Это первое, что следует убрать

**Comment by toxa70x4** [comment]
ttl=3 и badsum не вредит, работает h3 и в опере и chrome c google. Я проблем не замечал. 

Хм.
Если даже и опускаю zapret, браузер не юзает h3 в vk, а включаешь warp или другой vpn проблем нет. Мистика.

**Comment by bol-van** [comment]
ttl=3 и badsum  вместе - это явный перебор
потому что пакет все равно до сервера не дойдет.
если оставить только badsum, то он дойдет, но будет отброшен на уровне ОС
если не оставить ограничителя, то пакет дойдет до веб сервера, будет  им обработан, но будет отброшен как инвалидный на уровне протокола QUIC
так что для QUIC по сути любые ограничения не нужны. badsum может не сработать из-за роутера, ttl может навредить

`Если даже и опускаю zapret, браузер не юзает h3 в vk, а включаешь warp или другой vpn проблем нет. Мистика.`

Может они отключили только для RU. Тестят что-то

**Comment by toxa70x4** [comment]
![image](https://user-images.githubusercontent.com/79611111/174721594-4e91c015-807b-42b9-860c-f734bc689093.png)
А почему не проходит контакт по h3, если использовать запрет?

**Comment by bol-van** [comment]
Не знаю, без дампа с роутера udp 443 сложно что-то сказать

**Comment by toxa70x4** [comment]
Раздал wifi с Yota и h3 заработал в браузере и в vk. Что там дом.ру намутил...

Как снять dump?

**Comment by toxa70x4** [comment]
Обратил внимание только с vk, что не один запрос по h3 не отходит и стал дальше копать. При каких условиях снять дамп? С включенным запретом, когда вк по h3 не отвечает в curl?

**Comment by bol-van** [comment]
> При каких условиях снять дамп?

лучше всего 2 дампа
1. curl на vk.com с nfqws , без TTL
2. curl на vk.com без nfqws

**Comment by toxa70x4** [comment]
[dump.zip](https://github.com/bol-van/zapret/files/8946109/dump.zip)
Сделано

**Comment by bol-van** [comment]
Дамп без nfqws был с роутера
Дамп с nfqws, похоже, с клиента или снят на роутере с интерфейса локалки.
Это не есть хорошо

Но в целом видно, что пробивка не осуществляется. Ответа от сервера нет вообще. Поток заблокирован.
Скорее всего это вызвано дополнительным DPI от домру, который имеет иные алгоритмы, чем ТСПУ.

Как бы я стал пытаться это пробить. Очевидно, первый пакет нужно слать quic initial безобидный.
--dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin

Если таким способом удается пробить поток, и curl срабатывает, то дальше все равно будет ТСПУ, который без отсылки fake short header обеспечит хаотичными зависаниями потока. Потому может сработать custom скрипт custom-nfqws-quic4all-complex.

```
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin"
NFQWS_OPT_DESYNC_QUIC_SHORT_HEADER="--dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-fake-unknown-udp=/opt/zapret/files/fake/quic_short_header.bin --dpi-desync-cutoff=n2"

```

**Comment by toxa70x4** [comment]
Оба дампа с роутера.
Попробую ваши рекомендации. Отпишусь.

**Comment by bol-van** [comment]
Хотя, может я и не прав. Я же забыл, что ТСПУ сейчас блочит ВЕСЬ quic, кроме white list ip на vk.com
Если даже удастся пробить DPI от дома, то ТСПУ все равно заблокирует initial. Все опять зависнет.
Вк, конечно, может и сработать, но пробивать vk.com вообще смысла нет, он не запрещен

Выходит, чтобы пробить quic на ТСПУ, нужен не QUIC, а чтобы пробить quic у дома, нужен quic. Дилемма

**Comment by toxa70x4** [comment]
И что делать? Всегда вносить исключения? Сейчас вк, потом другие разрешенные ресурсы с quic?

**Comment by bol-van** [comment]
> Всегда вносить исключения?

не поможет. дамп говорит, что блочится на гугол тоже, а значит скорее всего на любые адреса




> И что делать?

искать пробивку порта udp:443 для дома.  по udp:443 ходит не только quic, но часто и другие протоколы. Если дом их отказывается пропускать, он может сломать много чего.

**Comment by toxa70x4** [comment]
Но почему google работает?

**Comment by bol-van** [comment]
У меня нет доступа к домру
Если дадите доступ, могу посмотреть

**Comment by toxa70x4** [comment]
В телегам @toxa70x4
