### ISSUE TITLE
[Feature Request] Docker image possible?

### ISSUE THREAD

**Issue by jckefan** [bol-van/zapret#116]
MikroTik has recently added Docker containers support on their RouterOS. I'm wondering if there's now a possibility of bringing Zapret support on MikroTik devices? Thanks

Edit: Link for some more info, https://help.mikrotik.com/docs/display/ROS/Container

**Comment by bol-van** [comment]
Support of third party devices is out of scope of this project.
I intentionally will not go into this area.
I leave it to specific device fans

**Comment by bol-van** [comment]
Technically as long as linux kernel supports iptables or nftables, has proper modules and the main software does not interfere with custom firewall rules its possible to use zapret

**Comment by jckefan** [comment]
> Support of third party devices is out of scope of this project. I intentionally will not go into this area. I leave it to specific device fans

That's unfortunate.😅 Thanks for the clarification anyways. Perhaps keep the issue open for now? Perhaps someone who knows the ins & outs of Docker would be able to bring the project to Docker. Although, I would only be making speculation here, getting Zapret working Alpine Linux or some other distro doesn't seem like a hard task.

**Comment by bol-van** [comment]
> I would only be making speculation here, getting Zapret working Alpine Linux or some other distro doesn't seem like a hard task

Zapret supports traditional linux distributions. You can just install it as you would on a real linux system.
What is in question - linux kernel used by microtik. Does it have enough modules ?
Is it possible to use ipset and nfqueue from the container ? Can container auto run ?
If yes installing zapret is not a big deal

**Comment by jckefan** [comment]
> > I would only be making speculation here, getting Zapret working Alpine Linux or some other distro doesn't seem like a hard task
> 
> Zapret supports traditional linux distributions. You can just install it as you would on a real linux system. What is in question - linux kernel used by microtik. Does it have enough modules ? Is it possible to use ipset and nfqueue from the container ? Can container auto run ? If yes installing zapret is not a big deal

Sorry for the late reply. After the above comment, I decided to learn about Docker and build my own image. The project initially failed with Zapret because it seems like MikroTik's kernel indeed lacks required modules to allowing proper functioning of iptables/ipset/nftables in the container. 

The error I got when trying to run iptables was something like Kernel module `xt_set` is missing. After lots of troubleshooting, I was able to make the error go away and add and run iptables rules, but they ended up doing absolutely nothing. Nftables was the same story.

However, thankfully, I came across [SpoofDPI](https://github.com/xvzc/SpoofDPI), the project doesn't require anything extra to run in a Linux container. With SpoofDPI, I was able to get the functioning container up and running in no time. SpoofDPI runs a HTTP proxy server, and it has been working on my MikroTik router for four or five days now, just fine. The solution isn't as elegant, sophisticated and or as fast as Zapret, but it gets the job done really well.

Here's the `Dockerfile` I used:
```
FROM golang:alpine3.16 AS build

RUN \
apk add --no-cache git && \
git clone https://github.com/xvzc/SpoofDPI.git && \
cd SpoofDPI && \
go build ./cmd/...

FROM alpine:latest

COPY --from=build /go/SpoofDPI/spoof-dpi /opt/spoof-dpi
```
**Note:** I specifically haven't baked `ENTRYPOINT` or `CMD` in the `Dockerfile` because you would be able to manipulate these options for your needs, directly from the WinBox: https://i.imgur.com/xeYssKN.png the container won't run without these two commands.

The output ARM image is no more than 11 MB, so it would likely be able to fit in MikroTik's tiny ARM routers that don't have any storage expansion option.

**Comment by bol-van** [comment]
absence of ipset only breaks my startup scripts if used with iptables. nftables do not use ipset . 
to run tpws without my startup scripts nothing special is required.
nfqws require only nfqueue support in kernel

**Comment by jckefan** [comment]
> absence of ipset only breaks my startup scripts if used with iptables. nftables do not use ipset . to run tpws without my startup scripts nothing special is required. nfqws require only nfqueue support in kernel

Okay, I feel stupid.😅 I was trying to setup Zapret in Docker through `install_easy.sh` script. Now I tried directly putting `tpws` in the container, placed it on the MikroTik router, and it **WORKED!** It was sooo simple. Here's a simple Dockerfile I used:
```
FROM alpine:latest AS build

RUN \
apk update && \
apk upgrade && \
apk add git && \
git clone https://github.com/bol-van/zapret.git

FROM alpine:latest

COPY --from=build /zapret/binaries/arm/tpws  /opt/tpws
```
The image size has been further reduced to only 4 MB. A reference command that can be used to run `tpws` on MikroTik router is `/opt/tpws --uid=0:0 --no-resolve --socks --bind-addr=0.0.0.0 --port=1080 --split-pos=1`

I wonder if the image size can be reduced by using [Distroless Container Image](https://github.com/GoogleContainerTools/distroless)? However, I leave that to one's personal taste, for me personally, 4 MB is already small enough. 

The issue can be closed now.

**Comment by bol-van** [comment]
prebuilt binaries are static. they can be run without base linux distribution. chroot fs must have /sys /proc /dev and tpws in the root. thats all

**Comment by maxpain** [comment]
> --socks --bind-addr=0.0.0.0 --port=1080

@jckefan Is it possible to run it as a transparent proxy without using socks?

**Comment by maxpain** [comment]
> I wonder if the image size can be reduced by using [Distroless Container Image](https://github.com/GoogleContainerTools/distroless)?

Yes, you can just use `FROM scratch`

**Comment by rerime** [comment]
@jckefan  could tpws work in transparent mode on mikrotik?

**Comment by jckefan** [comment]
> > I wonder if the image size can be reduced by using [Distroless Container Image](https://github.com/GoogleContainerTools/distroless)?
> 
> Yes, you can just use `FROM scratch`

Later, I had tried `FROM scratch` as well, but the container didn't come online.
