### ISSUE TITLE
Подскажите как использовать custom scripts

### ISSUE THREAD

**Issue by killkong** [bol-van/zapret#117]
Привет. Увидел сервисник, в обычном режиме стартует так
ExecStart=/opt/zapret/init.d/sysv/zapret start

как правильно использовать с custom-nfqws-quic4all или любым другим кастом скриптом? В /opt/zapret/init.d/sysv/zapret связи по методам не увидел.

**Comment by bol-van** [comment]
Скопировать custom-nfqws-quic4all в custom в той же директории и в config MODE=custom

**Comment by bol-van** [comment]
И еще добавить опции в config , которые указаны в комментах в скрипте custom-nfqws-quic4all

**Comment by killkong** [comment]
спасибо
