### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by Alexey71** [bol-van/zapret#118]
Привет. Если включать поддержку ipv6 то пакета нет в openwrt - kmod-nft-nat6. Но есть пакет kmod-nf-nat6. Ошибка?
https://github.com/bol-van/zapret/blob/master/install_easy.sh#L783

**Comment by Alexey71** [comment]
https://github.com/openwrt/openwrt/commit/b75425370d8de747457c137463bc4d15f6f44d00

**Comment by bol-van** [comment]
Да, факт, он пустой был еще в snapshot.
Убрал установку
