### ISSUE TITLE
Простое проксирование

### ISSUE THREAD

**Issue by sergeevabc** [bol-van/zapret#12]
Подскажите, пожалуйста, как упростить всю схему до проксирования заблокированных ресурсов на простеньком же роутере. Скажем, с аннонсерами Рутрекера (вроде ```bt2.t-ru.org```) получается так:
```
iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -d 195.82.146.120/30 -j DNAT --to-destination proxy.antizapret.prostovpn.org:3128
```
Если теперь вложить в память роутера файл со [списком доменов][1] (менее 1 Мбайта), то что дальше прописать в dnsmasq и iptables? Вероятно, решение как-то связано с инструкцией ```match-set```?

[1]: https://antizapret.prostovpn.org/domains-export.txt

**Comment by bol-van** [comment]
делать DNAT на прокси можно только тогда, когда этот прокси является прозрачным (transparent). в противоном случае нужен соксификатор типа редсокс, который является прозрачной прослойкой и заворачивает запросы в proxy или socks.
iptables с доменными именами не работает. доменное имя это высокоуровневая абстракция, которая не существует в рамках сетевых протоклов tcp/ip.
решение тут может быть либо ipset как у меня, либо транспарент прокси, которые разбирает http запросы, смотрит поле host и по нему принимает решение что с этим делать.

**Comment by sergeevabc** [comment]
Вроде оба пишем по-русски, а словно на разных языках. Попробую переформулировать вопрос.

- есть простой роутер с dnsmasq и iptables
- есть прозрачная прокся ```proxy.antizapret.prostovpn.org:3128```
- есть текстовый файл со списком заблокированных доменов

Какие команды надо дать роутеру, чтобы, например, ```rutracker.org``` открылся через проксю?

**Comment by bol-van** [comment]
Вы обратилист не по адресу
