### ISSUE TITLE
systemd warning: Unit configured to use KillMode=none

### ISSUE THREAD

**Issue by darkblaze69** [bol-van/zapret#120]
systemd warning, so probably should be changed?
`/etc/systemd/system/zapret.service:10: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.`

**Comment by bol-van** [comment]
its not a bug. ignore this

**Comment by icynstant** [comment]
https://github.com/bol-van/zapret2/pull/35

можно тут также?

**Comment by bol-van** [comment]
https://github.com/bol-van/zapret/releases/tag/v72.13

**Comment by icynstant** [comment]
возможно у меня что-то не так, но я на v72.13 получаю то же предупреждение
