### ISSUE TITLE
Measure roud trip time and use it as exclusion criteria

### ISSUE THREAD

**Issue by ccaapton** [bol-van/zapret#121]
Currently conntrack is tracking connection start time, but not first response time. Would you mind also keep record of the first received synack packet, so users can use the time gap between syn and synack to exclude servers that is very near to us?

**Comment by bol-van** [comment]
I don't quite understand what you mean by "conntrack". Is it linux conntrack or nfqws conntrack ?
Timing is not too reliable criteria to make fooling-or-not decisions.
Its not universal, requires fine tuning for specific ISP. Too short delay may be reliable but too long is not. Target server may be overloaded and do not respond immediately.
This approach also requires redirection of at least part of incoming traffic to nfqws. Currently it does not need any of this.

It all looks unfairly complex and not very reliable. Better to determine ISP local ranges (lookup as prefixes from bgp.he.net) and put them to nozapret ipset. It also can be easily done with a script that calls whois.

**Comment by ccaapton** [comment]
> Is it linux conntrack or nfqws conntrack ?
I mean nfqws conntrack.

> Better to determine ISP local ranges
Local  country ranges are too fragmented to be put into ipset, and need constant maintenance, the delay approach may be not reliable, but even it is wrong ,it will not cause too much disruption.

**Comment by bol-van** [comment]
`Local country ranges are too fragmented to be put into ipset, and need constant maintenance, the delay approach may be not reliable, but even it is wrong ,it will not cause too much disruption`

So you are going to exclude the whole country range based on timings ? Its even more unreliable than local ISP range.
Internet links may be overloaded even within your country and pings may be high.
What country are you talking about ? Is it China ?
Are all sites outside your country blocked ? If not you can use hostlist or ipset to filter.

There's xt_geoip module that implements iptables geoip match. I haven't used it myself. It may work.
Google for instructions.

Today ipv4 has 635,000 prefixes worldwide.
100K records in ipset is not a problem if your device has at least 128M ram. nfset require much more ram (320+)
You can write a script to download and parse a free geoip list
