### ISSUE TITLE
how to use on mikrotik

### ISSUE THREAD

**Issue by 66696e656c696665** [bol-van/zapret#122]
Hello, how to use this configuration on mikrotik (RouterOS)

**Comment by bol-van** [comment]
mikrotik do not allow direct access to linux.
likely its possible but only after hacking access. its not easy. firmware resists

**Comment by bol-van** [comment]
but at least some mikrotiks can be reflashed to openwrt

**Comment by bol-van** [comment]
I also heard recent routeros allow docker containers.
https://help.mikrotik.com/docs/display/ROS/Container
this can be the best way to gain linux access

**Comment by maxpain** [comment]
@bol-van Any ideas how to use zapret in a container?
