### ISSUE TITLE
Добавление bind-addr/bind-iface для dvtws под FreeBSD

### ISSUE THREAD

**Issue by ramdaron** [bol-van/zapret#124]
Здравствуйте.

Настроил совместную работу dvtws и ipfw под FreeBSD через divert socket. Все отлично работает, но среди опций запуска я могу задать только порт, а вот указать IP-адрес или интерфейс (127.0.0.1 или lo0) возможности нет.
У tpws можно задать эти опции, не могли бы вы добавить их и в dvtws?

Спасибо.
И отдельно спасибо за проделанную работу!

**Comment by bol-van** [comment]
dvtws/nfqws никак не связаны с интерфейсами.
они связаны с очередями. divert queue и NFQUEUE  соответственно
порт dvtws это как номер очереди nfqueue

**Comment by ramdaron** [comment]
dvtws биндит порт, который задается аргументом --port, куда ipfw отправляет пакеты на обработку.
Я надеялся увидеть возможность биндить не только порт, но и адрес/интерфейс, чтобы порт не был открыт на всех IP-адресах хоста, а ограничился, например, 127.0.0.1

**Comment by bol-van** [comment]
Почитайте docs/bsd.txt.

> divert сокет - внутренний тип сокета ядра BSD. Он не привязывается ни к какому сетевому адресу, не участвует
> в обмене данными через сеть и идентифицируется по номеру порта 1..65535. Аналогия с номером очереди NFQUEUE.
> На divert сокеты заворачивается трафик посредством правил ipfw или PF.
>

**Comment by bol-van** [comment]
Можете считать, это как Unix сокетс, только привилегированные

**Comment by ramdaron** [comment]
Прочитал man 4 divert:
> The IP address in the bind is ignored; only the port number is significant.

Вы совершенно правы, и заморачиваться с указанием интерфейса или IP-адреса нет смысла.
Спасибо!

**Comment by DeAlexPesh** [comment]
возможно, глупый вопрос, но как можно завернуть трафик на divert порт?
стандартными средствами pfctl это реально ну или скриптом при запуске dvtws?
у кого-то получилось на pfsense?

**Comment by bol-van** [comment]
прямо с  pf можно через divert-to
но это сломано во freebsd
см docs/bsd.txt
