### ISSUE TITLE
Допустимо ли убрать --dports и слать в NFQUEUE вообще все исходящие соединения?

### ISSUE THREAD

**Issue by disappointed72** [bol-van/zapret#125]
Конечно по списку в ipset. Чтобы обрабатывать трафик для всех портов назначения а не только 80 и 443.

**Comment by bol-van** [comment]
А смысл в этом какой ?

Если не указано --dpi-desync-any-protocol,  то все, кроме http request и TLS Client Hello  , будет игнорироваться
Если указано, то в чем смысл насиловать непонятно какие протоколы с непонятно каким эффектом ?

**Comment by disappointed72** [comment]
Для того  чтобы был доступ к TLS или http, которые запущен не на 80 и 443 порту.

**Comment by bol-van** [comment]
nfqws все равно на каком порту что находится. Если DPI действительно что-то делают с трафиком на других портах, то можно и на другие порты повесить nfqws
