### ISSUE TITLE
Add runit services

### ISSUE THREAD

**Issue by fahimscirex** [bol-van/zapret#126]
title.

**Comment by lepz0r** [comment]
I added runit & s6 service to my fork (https://github.com/lepz0r/zapret), copy `init.d/runit/zapret` to either `/etc/runit/sv` for Artix or `/etc/sv` for Void.

**Comment by bol-van** [comment]
This looks very exotic. Only few distributions support is as alternative startup scheme.
I doubt it's worth supporting in install_easy.sh
Few folks who are smart enough to use it surely smart enough to manually attach zapret sysv scripts

**Comment by fahimscirex** [comment]
@bol-van surely I'm smart enough to add a service, and as a matter of fact that's what I did. I was just wondering why not runit when OpenRC is available.

**Comment by bol-van** [comment]
OpenRC is present as default in some distros. Alpine, gentoo, nitrux, some others
From what I googled it looks like runit is default only on some extremely outdated or abandoned distros

**Comment by bol-van** [comment]
runit is available in ubuntu and debian but only as secondary launcher. Installing runit does not uninstall systemd

**Comment by lepz0r** [comment]
runit is also default init system for Void and also one of the init system choice for Artix (Arch based distro without systemd)

**Comment by fahimscirex** [comment]
You'd get some names on the official page of [runit](http://smarden.org/runit/)
