### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by f0xeri** [bol-van/zapret#128]
При включении zapret на роутере под openwrt в режиме NFQWS --dpi-desync-fooling=badsum --dpi-desync=split (с другими комбинациями результат тот же), на iOS при попытке открыть многие сайты возникает ERR_SSL_PROTOCOL_ERROR - сайт * отправил недействительный ответ. 
Так, например, ломаются youtube.com, facebook.com и многие другие, а apple.com работает нормально.
Проблема возникает именно на iOS, на остальных устройствах всё в порядке. Есть какие-то идеи о причинах и способах решения подобной проблемы?

**Comment by f0xeri** [comment]
Падает при включении флага --dpi-desync с любым значением

**Comment by bol-van** [comment]
Соображения такие
dpi desync не влияет никак на ответ сервера, пожалуй, за исключением опции --wssize
однако, при использовании фейк пакетов (их нет только на split2 и disorder2), обычно приходит ICMP ttl expired in transit, который доставляется клиенту
обнаружено, что это влияет на броузеры на базе chrome, но только на QUIC. На TCP никак не влияет.

Сказать что-то большее можно только имея tpcdump

**Comment by bol-van** [comment]
В любом случае вам поможет ограничение либо по хост, либо по ipset листу
Можно использовать и исключение, но в случае с ютубе это не будет работать стабильно, поскольку там прыгающий ip адрес. Если выберете этот путь, можно использовать ipset hook, который заполнит ipset nozapret ip адресами автономных систем google. Если интересно, могу свое решение накидать сюда

**Comment by f0xeri** [comment]
Если я правильно вас понял, то да, я могу применять обход только к заблокированным сайтам, но проблема в том, что они тоже не открываются с телефона из-за SSL error (а хотелось бы, чтобы открывалось). 
Да, ваше решение было бы интересно. 
По поводу дампа - на каких интерфейсах делать? br-lan?

**Comment by f0xeri** [comment]
Не получается запустить nfqws, как вы сказали:
`binding this socket to queue '200'
nfq_create_queue(): Operation not permitted`

**Comment by bol-van** [comment]
Потому что на этой очереди уже другой nfqws висит.
Сначала надо остановить , запущенный из /etc/init.d/zapret
Если не получается, можно сделать killall nfqws

**Comment by bol-van** [comment]
В дампах отсутствуют входящие пакеты. Есть только исходящие.
Какой фильтр вы использовали ? Чтобы отсечь адрес назначения или источника, надо писать "host 1.2.3.4"
Не включено ли аппаратное ускорение (offloading) ? Если да - выключить. В том числе и в /opt/zapret/config.

Судя по имеющейся инфе, все работает точно так, как должно в режиме fake,disorder2. Но стратегия обхода не работает.
И это было бы нормально и в порядке вещей, если бы оно не работало со всех устройств.
Мне нужно сравнить в дампах одинаковые запросы с работающего устройства и неработающего на внешнем интерфейсе, чтобы туда попали и входящие, и исходящие пакеты.

**Comment by f0xeri** [comment]
Добавил, к сожалению, SSL error продолжает сыпаться:(

**Comment by bol-van** [comment]
Надо перезапустить /etc/init.d/zapret restart
Если не работает, то, увы, наверно ничего не выйдет.

**Comment by f0xeri** [comment]
Да, я перезапустил. 
Что ж, жаль

**Comment by bol-van** [comment]
У МТС вроде есть ipv6. Не пробовали его включать ? Возможно, на нем что-то изменится

**Comment by f0xeri** [comment]
К сожалению, у нас есть только ipv4

**Comment by bol-van** [comment]
На android можно установить новый firefox. Он точно использует свою крипто библиотеку libnss. Там точно есть поддержка TLS 1.3. Конечно, это не спасет другие приложения

На ios, насколько я знаю, требование яблока использовать системное крипто. Оно поддерживает TLS 1.3 начиная с ios 12.2. Теоретически можно попробовать обновиться. Я с ios никогда не имел дело.

Еще есть вариант присвоить компу выделенный адрес в локалке и фильтровать обход по IP адресу, чтобы он не портил жизнь другим устройствам. Это делается через custom скрипт

**Comment by f0xeri** [comment]
Стоит iOS 16.0, понятия не имею, почему оно иногда до сих пор использует TLS 1.0 - как я и сказал, в одном из пары десятков случаев страницы открываются без ошибки, а некоторые и вовсе работают без проблем.
Андроид ТВ - там приложение ютуба отказывается работать, тут уж точно не исправить.

Да, можно просто не портить жизнь другим устройствам, но всё же, получить ожидаемый результат видимо не выйдет.

**Comment by bol-van** [comment]
Странно, что DPI реагирует даже на незаблокированные сайты.
С одной стороны , можно было бы предположить, что он не понимает исходящий посыл и ждет входящего. Видит там ServerHello, и понимает, что его дурят, затем рвет конект через RST.
Но ведь TLS 1.3 проходит, значит он еще и сечет оттуда сертификат. Но там же yandex. Зачем его дропать.

Можно попробовать такой вариант.
В виртуалке запустить любой linux.   Ubuntu live-dvd 22.04 вполне подойдет.
На роутере остановить zapret. Установить его на linux, погонять блокчек оттуда
там будет curl, линкованный с openssl . он проверит все как надо для tls 1.2
Возможно, какие-то варианты мы упускаем

**Comment by f0xeri** [comment]
WSL для этой задачи не подойдёт?
И ещё, blockcheck предлагал tpws --methodeol, но он не срабатывает в принципе

**Comment by bol-van** [comment]
tpws --methodeol работает только для http и ломает некоторые сайты
Это обычное поведение DPI от rdp.ru

WSL мог бы подойти, но только 2-й версии с полноценным ядром
и чтобы не было NAT от гипервизора

**Comment by f0xeri** [comment]
![image](https://user-images.githubusercontent.com/25245692/206252029-ec7aacc7-023f-4ac4-a6c9-fd48b5524d2b.png)
Что ж

**Comment by bol-van** [comment]
Может еще быть антивирус, проверяющий все инет соединения
он может работать как прозрачный прокси. нет такого ?

**Comment by bol-van** [comment]
Какие ошибки выводятся при проверке ? Куда-нибудь можно весь лог запостить ?

**Comment by f0xeri** [comment]
https://hastebin.com/raw/cejobixacu

**Comment by f0xeri** [comment]
Хотя опять же, многие вариации из тех, что указаны unavailable в 1.3, в хромиуме работают нормально

**Comment by f0xeri** [comment]
![image](https://user-images.githubusercontent.com/25245692/206266856-653a8ab1-5072-43ad-be3e-ac1f45f8fe17.png)
Тест на роутере даёт такой результат.
При выключенном zapret на роутере и включенном в убунту настройки -dpi-desync-fooling=badsum --dpi-desync=fake, disorder2 не работают - ERR_CONNECTION_RESET не только у заблокированных, но и у яндекса с ютубом (всё то же самое, что и на iOS)
При включенном zapret на роутере С ТЕМИ ЖЕ САМЫМИ настройками (-dpi-desync-fooling=badsum --dpi-desync=fake, disorder2), на винде всё работает так, как и предполагается, на невинде - ломается.
Какая-то магия.

P.S.: под виндой и goodbyedpi работает со стандартными настройками

**Comment by bol-van** [comment]
Если роутер на базе mediatek, то он режет пакеты с badsum на входе.  Все режимы обхода с badsum и фейк-пакетами перестают работать из-за роутера в этом случае, но с него работают.
Остальное - принципиальное значение имеет версия TLS.
Все современные броузеры лезут с TLS 1.3. Для экспериментов нужен курл, в котором указывать --tls-max 1.2. Курл нормальный, с openssl, а не виндовый предустановленный с schannel.
Думаю goodbyedpi тоже не сработает на TLS 1.2

Еще может быть балансировака у провайдера на разные DPI. Можно попробовать задать 3 попытки, чтобы посмотреть на стабильность.

**Comment by f0xeri** [comment]
Да, роутер на базе MT7620. Я пробовал и варианты с badseq и что-то ещё, результат тот же

**Comment by bol-van** [comment]
Можете проверить работает ли с goodbyedpi -5   (--auto-ttl --reverse-frag)
curl --tls-max 1.2 https://www.facebook.com
curl --tls-max 1.3 https://www.facebook.com
curl с openssl

**Comment by bol-van** [comment]
Здесь требуется более глубокое исследование, и оно будет малоэффективным в таком режиме запрос-ответ
Если готовы предоставить доступ для тестирования вашего соединения, могу дать образ виртуалки
Ее надо будет поднять в режиме bridge. К основной системе, естественно, доступа не будет
