### ISSUE TITLE
на каких роутерах тестируется zapret?

### ISSUE THREAD

**Issue by kotsmotritnastul** [bol-van/zapret#132]
хочу купить роутер с openwrt специально чтобы установить туда запрет, и чтобы лишний раз не бегать возвращать деньги или менять хочется знать какой вариант гарантированно будет рабочим.

да, я читал про требования к оперативке и флешке роутеров, но мало ли, вдруг у некоторых моделей внезапно вылезут какие-то железячные проблемы, так что хочется знать на каком именно роутере точно не будет проблем с запретом.

**Comment by bol-van** [comment]
Единственные требования zapret касаются места на диске и RAM. Все остальное - отдельный вопрос как выбрать роутер под openwrt, и это надо не здесь обсуждать

**Comment by Diman3012** [comment]
Если хотите выбрать роутер под OpenWrt, то вот сайт для этого https://openwrt.org/toh/start
