### ISSUE TITLE
NFQWS and tpws

### ISSUE THREAD

**Issue by mids33** [bol-van/zapret#133]
hi bol-van  you software is the only one that bypassed my ISP .. 
the seting in linux is NFQWS_OPT_DESYNC="--dpi-desync=split2 --wssize 1:6"
how to do that in tpws in windows ..
tpws --split-pos=2 worked like other dpi but does not bypass my ISP.

thanks for any help..

**Comment by bol-van** [comment]
not possible

**Comment by bol-van** [comment]
There's software **GoodbyeDPI** for windows.
But if bypass only workis with **wssize** option I doubt it will help

**Comment by mids33** [comment]
Thanks
