### ISSUE TITLE
После настройки wireguard и перезагрузки, устройство становиться не доступным из локальной сети и сервера wireguard

### ISSUE THREAD

**Issue by morsDeiGH** [bol-van/zapret#135]
Настроил wireguard следуя информаций из wireguard_iproute_openwrt.txt
В конфигах поменял ключи и ip, все работает, но следует только перезагрузить openwrt, то он становиться не доступным из локальной сети и сервера wireguard. Пинги, веб интерфейс, ssh все не доступно.
Из-за чего такое происходит?

**Comment by bol-van** [comment]
Откуда я знаю почему ? Если нет возможности получить доступ к консоли без сети (на роутерах домашних обычно через разборку корпуса и подключение к serial port), то я бы закоментировал rule с lookup 100. Изменится ли что-то после перезагрузки ?
Может быть маркировку сделал плохо, что все туда заруливается, включая локалку, игнорируя сет nozapret

**Comment by morsDeiGH** [comment]
Подключиться к устройству возможности нет. Ставлю чистую OpenWRT и настраиваю только соединение с wireguard, zapret ещё не ставил, и такая проблема

**Comment by bol-van** [comment]
Здесь не место для обучения настройке openwrt или изучения linux и его сетевой части.
Если вы берете мой manual, то там ясно написано, что он в помощь юзерам, которые уже разбираются.
Если вы даже ему не следуете, а просто что-то пытаетесь, то к чему меня спрашивать почему у вас не работает. Я знаю что вы делаете ?
