### ISSUE TITLE
скрипты ipset: замена curl на wget

### ISSUE THREAD

**Issue by spvkgn** [bol-van/zapret#14]
Возможно ли использовать wget из busybox если нет curl? Ведь не во всех роутерах есть curl или возможность развертывания entware.

**Comment by bol-van** [comment]
Почему нет. Замените соотв команды в скриптах.
Там, где используется вывод curl в stdout, можно заменить на "wget -O - <url>"
Конечно, не будут работать ограничители  на размер файла и на макс время скачивания

**Comment by spvkgn** [comment]
ОК, попробую. У меня альт. прошивка от Padavan
