### ISSUE TITLE
modprobe lists that used by zapret and all depedencies

### ISSUE THREAD

**Issue by rapdodge** [bol-van/zapret#140]
Greetings,
Lately my ISP are implementing DPI, and it's shit.

In short, I'm using OpenWrt behind LXC, but, i don't want to making it privilege LXC, wanted to staying it unprivilege...

I've adding modprobe nfnetlink_queue, but still didn't work when running the blockcheck.

![image](https://user-images.githubusercontent.com/33513626/232202841-e576f9ec-ef5d-4221-b463-39b942231ef3.png)

May you share modprobe list that should be turned on for zapret and all the depedencies?

![image](https://user-images.githubusercontent.com/33513626/232205343-cf091ae0-73bb-436a-a28f-9e434577b811.png)

nft / nftables are installed default on openwrt 22.03... i dont have any ideas...

**Comment by bol-van** [comment]
nfqws requires cap_net_admin and cap_net_raw, otherwise it can't function.
If it also has cap_setuid,cap_setgid,cap_setpcap , it changes uid and removes unnecessary privileges. But this is not required.
For example, if you setcap  cap_net_admin,cap_net_raw+ep  to nfqws, it will work skipping privilege drop logic.

**Comment by rapdodge** [comment]
> nfqws requires cap_net_admin and cap_net_raw, otherwise it can't function. If it also has cap_setuid,cap_setgid,cap_setpcap , it changes uid and removes unnecessary privileges. But this is not required. For example, if you setcap cap_net_admin,cap_net_raw+ep to nfqws, it will work without root skipping privilege drop logic.
> 
> According to your log it does not skip privilege drop logic, so it believes it has required caps. I dont know what causes setgid to fail with invalid argument. May be it does not like default GID 0x7FFFFFFF. In recent commit I changed blockcheck to run nfqws with uid:gid 1:3003, like tpws
> 
> If LXC limits syscalls with selinux/apparmor/seccomp/... causing to behave them abnormally - its completely unsupported case.
> 
> Likely "command not found" is not related to absence of nft and you can ignore it

![image](https://user-images.githubusercontent.com/33513626/232235563-0220b641-0595-4d68-bae8-91337d832154.png)

Running as UID=1 GID=1 is likely works...
But, on the blockcheck are still has invalid argument things

![image](https://user-images.githubusercontent.com/33513626/232235591-cac3e22c-8671-40a3-8ec0-873a7853c085.png)

I've changing https://github.com/bol-van/zapret/blob/master/blockcheck.sh#L17 to GID 1, but, idk why it's doesn't working...

**Comment by rapdodge** [comment]
Okay... After enabling FUSE, Nesting, all things that connected to nftables, and changing the mode, it's running well

OpenWrt on PVE using [this wrapper](https://github.com/DazzyWalkman/oplxc4pve). And there is hookscript, I'm adding all things that connected to nftables

```
#needed by zapret
system("modprobe nf_conntrack");
system("modprobe nf_defrag_ipv4");
system("modprobe nf_defrag_ipv6");
system("modprobe nf_flow_table");
system("modprobe nf_flow_table_inet");
system("modprobe nf_log_ipv4");
system("modprobe nf_log_ipv6");
system("modprobe nf_nat");
system("modprobe nf_reject_ipv4");
system("modprobe nf_reject_ipv6");
system("modprobe nf_tables");
system("modprobe nft_objref");
system("modprobe nfnetlink");
system("modprobe nfnetlink_queue");
system("modprobe nft_chain_nat");
system("modprobe nft_ct");
system("modprobe nft_fib");
system("modprobe nft_fib_inet");
system("modprobe nft_fib_ipv4");
system("modprobe nft_fib_ipv6");
system("modprobe nft_flow_offload");
system("modprobe nft_hash");
system("modprobe nft_limit");
system("modprobe nft_log");
system("modprobe nft_masq");
system("modprobe nft_nat");
system("modprobe nft_numgen");
system("modprobe nft_objref");
system("modprobe nft_queue");
system("modprobe nft_quota");
system("modprobe nft_redir");
system("modprobe nft_reject");
system("modprobe nft_reject_inet");
system("modprobe nft_reject_ipv4");
system("modprobe nft_reject_ipv6");
```

I'm adding that because I'm running lsmod command on KVM OpenWrt...

**Comment by rapdodge** [comment]
![image](https://user-images.githubusercontent.com/33513626/232315705-2f5071b5-2f0b-4887-b3cb-fd8cf229f03d.png)

![image](https://user-images.githubusercontent.com/33513626/232315708-100f094e-0274-47a8-b734-3b53c70bfda3.png)

Hmmm... After enabling FUSE and Nesting, there is error, just disabling it, and it's fixed... But, the modprobe are still the same...

**Comment by rapdodge** [comment]
Okay, after like maybe almost 1 week, so far so good...

Just adding `nfnetlink_queue` on the hookscript

![image](https://user-images.githubusercontent.com/33513626/234163240-23316f91-6ace-4927-8a47-12e54d745ed3.png)

PVE options for LXC are like this

![image](https://user-images.githubusercontent.com/33513626/234163542-61f4bff3-e33f-464d-b739-1d1a3bb0f57e.png)

No FUSE, no nesting, etc... Just adding the https://github.com/DazzyWalkman/oplxc4pve hookscript

![image](https://user-images.githubusercontent.com/33513626/234163733-3eabf791-8a8e-42cc-96d1-7629a625cc73.png)

tpws and nfqws are working as expected.

*Notes: I'm using official OpenWrt rootfs https://downloads.openwrt.org/releases/22.03.4/targets/x86/64/openwrt-22.03.4-x86-64-rootfs.tar.gz
