### ISSUE TITLE
Unable to access router admin panel / Не могу зайти в админку роутера

### ISSUE THREAD

**Issue by oifj34f34f** [bol-van/zapret#143]
Добрый день.

После запуска сервиса zapret всё работает, но я не могу зайти в админку своего роутера, всё что я вижу, это белый экран и ошибки в инструментах для разработчиков:

```
Uncaught SyntaxError: Unexpected token '<'      vendor-4b49ccd866.js:1
Uncaught SyntaxError: Unexpected token '<'         app-3aae9887ea.js:1
Uncaught SyntaxError: Unexpected token '<'           ndmConstants.js:1
Uncaught SyntaxError: Unexpected token '<'          ndmComponents.js:1
Uncaught SyntaxError: Unexpected token '<'                version.js:1
```

После остановки сервиса страница открывается. [Вот мой конфиг](https://pastebin.com/raw/2hXYZMvA) (использую NFQWS, изменял опцию NFQWS_OPT_DESYNC).

Помогите пожалуйста.

**Comment by oifj34f34f** [comment]
Решил проблему, изменив опции в конфиге:

```
NFQWS_OPT_DESYNC="--dpi-desync=fake,split --dpi-desync-ttl=4"
NFQWS_OPT_DESYNC_HTTP="--dpi-desync=split --dpi-desync-fooling=badsum"
NFQWS_OPT_DESYNC_HTTPS="--dpi-desync=fake,split --dpi-desync-ttl=4"
```

Теперь всё работает. Спасибо за замечательную программу

**Comment by bol-van** [comment]
ndm - должно быть стоковая от kinetic ?
Это полностью неподдерживаемая конфигурация, на страх и риск и разбор самого юзера
zapret нацелен прежде всего на openwrt

**Comment by oifj34f34f** [comment]
@bol-van Я немного неправильно выразился, я использую zapret на Arch Linux (как альтернатива GoodbyeDPI на Windows)

**Comment by bol-van** [comment]
zapret никак не связан с "админкой" какого-то Linux
и тем более config вряд ли мог на это повлиять
синтаксических ошибок не вижу
скорее всего какая-то другая сопутствующая проблема
