### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by hufrea** [bol-van/zapret#145]
Предкомпилированный бинарник tpws завершается сразу после accept, однако скомпилированный вручную работает нормально
```
accept(3, {sa_family=0x1af8 /* AF_??? */, sa_data="..."}, [128]) = 3
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x416fe8, si_syscall=__NR_accept, si_arch=AUDIT_ARCH_AARCH64} ---
+++ killed by SIGSYS +++
Bad system call
```

**Comment by bol-van** [comment]
Какая архитектура и ядро ?

**Comment by hufrea** [comment]
Linux 4.19.157, Android, aarch64

вот вызов работающего бинарника:
`accept4(3, {sa_family=AF_INET6, sin6_port=htons(39054), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_scope_id=0}, [128 => 28], 0) = 5`

**Comment by bol-van** [comment]
Подозреваю, что проставлен еще какой-то сторонний seccomp filter.
Встроенный от tpws не блокирует никаких accept-ов и работает по принципу черного списка, не белого.
cat /proc/$(pidof tpws)/status | grep Seccomp
Seccomp_filters: 1  - означает есть только встроенный фильтр от tpws
Если больше, то это сторонние фильтры от android

Чем вы собирали свой вариант tpws ?
У меня собрано openwrt sdk годичной давности с компилятором gcc. Он компилит вызов syscall accept
ваш же, похоже, заменяет на accept4, либо это сделано через #define или libc, что реально превращает вызов в accept4

**Comment by hufrea** [comment]
clang version 16.0.3
Target: aarch64-unknown-linux-android24
Фильра 2

**Comment by bol-van** [comment]
В Android  любят блокировать syscall-ы, которые не применяются в их системе компиляции и libc. Для сокращения attack surface. 

Перевел код на accept4. Так даже лучше. Экономится вызов fcntl()
