### ISSUE TITLE
twitter.com custom hosts problem solving

### ISSUE THREAD

**Issue by Parakovsky** [bol-van/zapret#146]
пацаны всем привет прежде всего спасибо большое прога действительно классная все сайты открываются шикарно и главное работает без затыков зачем я раньше делал тридцать три прокси сервера я не знаю. единственное что я не смог настроить это твитер я думаю это потому что там какие то свои cdn типа twimg или еще какой то фигни если кто раньше делал именно твитор напишите мне пожалуйста свой ценный опыт спасибо

**Comment by bol-van** [comment]
В броузере F12, вкладка "сеть", и смотрим какие там домены. Где затык

**Comment by rockenren** [comment]
В режиме hostlist со списком get_reestr_resolvable_domains.sh Твиттер работал вполне нормально до ввода недавних ограничений на просмотр твитов для незарегистрированных пользователей.

Были еще проблемы с *.twimg.com (иногда медиа не грузилось), но сейчас даже проверить нормально возможности нет.

**Comment by wigeance** [comment]
*.twimg.com проверяется даже с новыми ограничениями твиттера на количество твитов. Я проверяю этой ссылкой (https://abs-0.twimg.com/emoji/va), но только https tls 1.2, на tls 1.3 сайт не работает (походу на стороне твиттера просто не прикрутили)

**Comment by bol-van** [comment]
цензор видит только домены. он не видит как работает сайт
количество твитов относится к сайту

**Comment by Parakovsky** [comment]
всем спасибо за коменты надо вернутся к этой проблеме и попробовать
прикрутить советы мне лично а то я отстаю от общего велопробега

**Comment by megumintyan** [comment]
У меня тоже не открывает пару доменов (www.instagram.com, mail.cock.li).
Если запустить для них blockcheck.sh, то он не может найти обход.
Что можно сделать? hostlist не использую.

**Comment by bol-van** [comment]
для начала проверьте есть ли вообще ответ с порта. блокировку по  ip не обойти

**Comment by rockenren** [comment]
> У меня тоже не открывает пару доменов ([www.instagram.com](http://www.instagram.com), mail.cock.li). Если запустить для них blockcheck.sh, то он не может найти обход. Что можно сделать? hostlist не использую.

Как минимум Instagram блокирует доступ из РФ со своей стороны, это не связано с DPI.
Тут поможет только доступ через прокси/VPN с зарубежных IP.

**Comment by megumintyan** [comment]
> Как минимум Instagram блокирует доступ из РФ со своей стороны, это не связано с DPI.

Обычно в таких случаях выдает "Access denied". А тут просто "time out".

К тому же  с гудбайдпи инстаграм открывается, хоть и долго думает при первом открытии.

А вот mail.cock.li действительно без прокси не работает.

**Comment by rockenren** [comment]
> Обычно в таких случаях выдает "Access denied".
Это не является обязательным условием. Могут блокировать как угодно, это лишь означает что блокировка осуществляется не средствами "веб-сервера" который эту ошибку показывает, а где-то раньше. Собственно пример с mail.cock.li это доказывает.

На Instagram в итоге микс из заблокированных РКН хостов (в т.ч. CDN), и ограничений со стороны Meta.

99.9% заблокиорованных РКН хостов есть в списках типа hostlist. Списки типа iplist не дадут 100% точности, т.к. отрабатывают по IP на момент резолва имени хоста, а IP там могут меняться (обычно такое с CDN).

Поэтому могут возникать ситуации, когда вроде в списках на дурение сайт есть, а оно не работает, потому что резолвится в уже другой IP, который в лист на дурение не попал.

Это я все к чему: используйте дурение через hostlist, а не по IP. Если сайт в hostlist есть, но все равно не открывается - проверяем через зарубежный прокси. Стал открываться? Значит блокировка на той стороне и доступ будет только "с зарубежа". zapret не помогает обходить блокировки со стороны хостов, это не его задача.
