### ISSUE TITLE
Более чем один интерфейс для интерент с разными способами запрета

### ISSUE THREAD

**Issue by nabiev-sergey** [bol-van/zapret#147]
Здрваствуйте
Скажите, пожалуйста, можно ли запустить два (три и т.д.) экземпляра nfqws, если имеется несколько интерфейсов, подключенных к разным провайдерам?
Вообще эта штука работает поверх существующих правил nftables, просто поключаясь к указаной очереди, или сама активно создаёт правила под себя?

**Comment by nabiev-sergey** [comment]
Ясно.
Есть какой-нибудь шаблон правил nftables. Или того, что в docs (nftables.txt там...) должно быть достаточно?

**Comment by bol-van** [comment]
самый базис в docs/nftables.txt
но рекомендую просмотреть создаваемое скриптами

**Comment by nabiev-sergey** [comment]
Вроде разобрался.
Большое спасибо.
