### ISSUE TITLE
Установка на FreeBSD

### ISSUE THREAD

**Issue by xpaco** [bol-van/zapret#15]
Здравствуйте! Очень прошу, расскажите, как (если это возможно) установить ваше чудо на FreeBSD (10.1)? Если конкретней, интересует установка на дистрибутив "pfSense".

**Comment by bol-van** [comment]
BSD ни разу в жизни не устанавливал, потому практического опыта никакого нет.
Могу предположить, что с небольшими модификациями можно завести tpws
Так же придется чуток переписать скрипты ipset и, разумеется, iptables на ipfw

**Comment by bol-van** [comment]
Если еще актуально, то tpws портирован на BSD. Проверена версия 12.2
