### ISSUE TITLE
Патч wg-mod для актуальной версии?

### ISSUE THREAD

**Issue by spvkgn** [bol-van/zapret#150]
Возможно ли обновить [docs/wireguard/010-wg-mod.patch](https://github.com/bol-van/zapret/blob/master/docs/wireguard/010-wg-mod.patch) для актуальной версии WG? (Если еще имеет смысл как решение для обхода dpi)
Насколько понял, этот патч для модуля dkms, когда WG еще не был принят в kernel source tree.

**Comment by bol-van** [comment]
да, все верно. цель чтобы дать идею, а не готовый патч
следить за версиями иначе придется
вообще лучше пользовать ipobfs.
