### ISSUE TITLE
Как указать свой фейковый хост для nfqws?

### ISSUE THREAD

**Issue by buggyman** [bol-van/zapret#156]
w3.org кажется заблокирован. По крайней мере через MTS.
dpi-desync-fake-tls какой-то слишком сложный, можно ли сделать опцию чтоб просто свой хостнейм указывать?

Или добавьте инструкцию как готовить этот файлик для --dpi-desync-fake-tls.

**Comment by bol-van** [comment]
Для начала докажите, что MTS блокирует именно w3.org по SNI

**Comment by bol-van** [comment]
Инструкция простая. Берем shark, ловим tcp port 443, идем куда надо, находим clienthello, записываем оттуда данные пакета без заголовков ip и tcp

**Comment by bol-van** [comment]
Добавил несколько готовых TLS фейков в files/fake

**Comment by buggyman** [comment]
Доказать не могу, потому и написал "кажется". И вообще не уверен что дело было в блокировке (сейчас всё заработало без параметры --dpi-desync-fake-tls)...

Инструкция немного невнятная, но вроде всё получилось. Смутило, что размер файла получился 529 байт вместо 517 в ваших готовых, но заблокированные сайты открываются. Спасибо.

**Comment by bol-van** [comment]
TLS ClientHello должен начинаться с 16 03. Если это не так, то либо это не hello, либо какие-то хедеры в начале

**Comment by buggyman** [comment]
Да, первые два байта именно такие. Файл получил таким образом (можно использовать как черновик для добавления в readme.txt):

> В wireshark фильтр для захвата указал такой:
> `tcp port 443 and host example.com`
> 
> Потом в браузере зашёл на сайт.
> 
> После чего в wireshark нашёл пакет с описанием `Client Hello`, в пакете нашёл блок:
> -> `Transport Layer Security`
>       ----> `TLSv1.3 Record Layer: Handshake Protocol: Client Hello`
> 
> Далее ПКМ по этой строчке и выбрал `Экспортировать Байты Пакета...  (Ctrl+Shift+X)`

По крайней мере _у меня_ не возникло бы сложностей при наличии подобной инструкции.
Ещё раз спасибо за ответ и за проект.

**Comment by bol-van** [comment]
На практике она и не нужна.
Очень сомневаюсь, что кто-то будет блокировать w3.org. Это одна из организаций, разрабатывающих общие для инета стандарты
