### ISSUE TITLE
blockcheck.sh on openwrt 23.05

### ISSUE THREAD

**Issue by AlexeiGHub** [bol-van/zapret#157]
Не работает проверка tls1.3 на openwrt 23.05

curl --tlsv13 hostname запрос обрабатывает.

**Comment by bol-van** [comment]
они перешли на мбедтлс. он не поджерживает 1.3
можно взять статический курл из соседнего репозитория   bins

**Comment by AlexeiGHub** [comment]
Приношу извинения. Глупо получилось.
Увидел в списке изменений проекта zapret эту особенность, начал проверять, и как  мне показалось что мой штатный curl в openwrt 25.03 с libmbedtls  обрабатывает ключ --tlsv1.3 понять не могу.

Вам спасибо за оперативный ответ.
