### ISSUE TITLE
Trojan found

### ISSUE THREAD

**Issue by denissovav** [bol-van/zapret#158]
Обнаружен троян в восьми бинариках.

> Trojan:Script/Wacatac.B!ml
> Affected items:
> zapret-master\binaries\aarch64\nfqws
> zapret-master\binaries\mips32r1-lsb\nfqws
> zapret-master\binaries\mips32r1-msb\nfqws
> zapret-master\binaries\x86_64\nfqws
> 
> Trojan:Script/Wacatac.H!ml
> Affected items: file:
> zapret-master\binaries\aarch64\tpws
> zapret-master\binaries\ppc\ip2net
> zapret-master\binaries\ppc\mdig
> zapret-master\binaries\x86\tpws

**Comment by bol-van** [comment]
Там UPX. Распакуйте через upx -d и проверьте заново
А потом выкините ваш антивирус на помойку

**Comment by denissovav** [comment]
Спасибо, попробую при первой возможности.
Если я правильно понимаю, у Вас все бинарики сжаты upx. Почему же тогда false detect только на этих восьми?
Антивирус - MS Defender, не выкинешь: часть ОС.

**Comment by bol-van** [comment]
Не выкинешь ? Зато можно отключить. Соседний репозиторий, win10_antishit.  eradicate defender
Или просто ГУГЛ

Я не могу обьяснить что взбрело в голову искусственному интеллекту. Это эвристика
