### ISSUE TITLE
Не работает запрет на сайтах вообще и не находит стратегий обхода.

### ISSUE THREAD

**Issue by Nuncio105** [bol-van/zapret#159]
Установил запрет на на свежеустановленную систему:
```
Kernel: 6.5.9-arch2-1 arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
Desktop: KDE Plasma v: 5.27.9 tk: Qt v: 5.15.11 wm: kwin_x11 dm: SDDM
Distro: EndeavourOS base: Arch Linux
```

Перенёс в /opt/zapret, выполнил `sudo install_bin.sh`, далее сперва выполнил `install_easy.sh`, но поскольку со стандартными настройками не заработало, я выполнил `uninstall_easy.sh` и перешёл к `blockcheck.sh`.
Попробовал несколько наиболее очевидных для меня сайтов: twitter.com rutracker.org gelbooru.com pixiv.net Однако блокчек изначально выдаёт что есть доступ (но сайты не открываются), а после, проверив всякие стратегии обхода, не находит ни одного метода обхода.
На всякий случай проверил journalctl, но там никаких ошибок или проблем связанных с чем-либо нет.

Приложил логи блокчека на примере gelbooru.com

Провайдер - МГТС
На этом же компьютере, но на винде, goodbyedpi работает, хоть и не совсем идеально.

Какие есть варианты, может какие-то ещё настройки покрутить?

[zapret-blockcheck-gelbooru.txt](https://github.com/bol-van/zapret/files/13199072/zapret-blockcheck-gelbooru.txt)
[zapret-blockcheck-gelbooru2.txt](https://github.com/bol-van/zapret/files/13199073/zapret-blockcheck-gelbooru2.txt)

**Comment by bol-van** [comment]
Могу предложить только заснять шарком успешный сеанс атаки с goodbye DPI и выложить cap.
Далее я переведу это в стратегию для nfqws.
И потом заснять сеанс неуспешной атаки с nfqws с этой же стратегией

**Comment by Nuncio105** [comment]
ipv6 нет, заголовки аутпута curl прилагаю:

[curl-output.txt](https://github.com/bol-van/zapret/files/13220547/curl-output.txt)

Wireshark раньше не пользовался, под cap имеете в виду файл захвата?

**Comment by bol-van** [comment]
В curl-output только заголовки запроса. из ответа ничего нет. это не информативно
Да, имею в виду cap файл с фильтром на tcp port 443, где осуществляется попытка дернуть заблокированный сайт с примененным лекарством

**Comment by wigeance** [comment]
Для мтс/мгтс ipv4 в Москве рабочая стратегия: --dpi-desync=fake,split2 -dpi-desync-split-pos=1 --dpi-desync-fooling=badseq,md5sig и пропишите статические ip адреса отсюда для Facebook, Instagram и т.д. https://ntc.party/t/%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8-facebookinstagramtwitter-%D1%81-goodbyedpi/1741/40
