### ISSUE TITLE
nfqws QUIC ipfrag2 

### ISSUE THREAD

**Issue by AlexeiGHub** [bol-van/zapret#160]
openwrt 23.05 
Отправляемые c wan порта фрагменты, имеют исходящий адрес локального узла.
--bind-fix4 не помогает.
fake пакет уходит с  корректным адресом.

```
unbinding existing nf_queue handler for AF_INET (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding this socket to queue '210'
setting copy_packet mode
initializing raw sockets bind-fix4=1 bind-fix6=0

```

**Comment by bol-van** [comment]
Фрагменты имеется в виду что ? ipfrag или split ?

**Comment by bol-van** [comment]
Скрипты zapret хватают пакеты еще до srcnat
```
 chain postrouting {
                type filter hook postrouting priority srcnat - 1; policy accept;
......
}

```

nfqws получает пакеты с локальным IP и отправляет их так же. это нормально.
masquerade работает уже после , как с пропущенными через очередь оригиналами, так и с отправленными nfqws пакетами через raw socket

если адрес после masquerade сохранился, значит пакеты не были обработаны, возможно по какой-то причине свалились в состояние conntrack INVALID.  но правила fw4 такое должны отсекать и не пропускать

по поводу ipfrag там вообще отдельная песня. скрипты zapret не поддерживают его использование. только ручками

**Comment by bol-van** [comment]
По этой же причине , что обработка идет до masquerade, использование bind-fix в составе скриптов zapret в текущем варианте так же не поддерживается

sending fake request : 47 45 54 20 2F 20 48 54 54 50 2F 31 2E 31 0D 0A 48 6F 73 74 3A 20 77 77 77 2E 77 33 2E 6F 72 67 ... : GET / HTTP/1.1..Host: www.w3.org ...
rawsend: bind (ignoring): Address not available

**Comment by AlexeiGHub** [comment]
> ipfrag

ipfrag2

**Comment by AlexeiGHub** [comment]
> если адрес после masquerade сохранился, значит пакеты не были обработаны, возможно по какой-то причине свалились в состояние conntrack INVALID. но правила fw4 такое должны отсекать и не пропускать

Так и есть, я отключил прибивание conntrack INVALID, иначе `rawsend: sendto: Operation not permitted`

**Comment by AlexeiGHub** [comment]
И в коде 
`
					if (!ip_frag(pkt_orig, pkt_orig_len, ipfrag_pos, ident, pkt1, &pkt1_len, pkt2, &pkt2_len))
						return res;

					DLOG("sending 1st ip fragment 0-%zu len=%zu : ", ipfrag_pos-1, ipfrag_pos)
					hexdump_limited_dlog(pkt1,pkt1_len,IP_MAXDUMP); DLOG("\n")
					if (!rawsend((struct sockaddr *)&dst, desync_fwmark, ifout , pkt2, pkt2_len))
						return res;

					DLOG("sending 2nd ip fragment %zu-%zu len=%zu : ", ipfrag_pos, len_transport-1, len_transport-ipfrag_pos)
					hexdump_limited_dlog(pkt2,pkt2_len,IP_MAXDUMP); DLOG("\n")
					if (!rawsend((struct sockaddr *)&dst, desync_fwmark, ifout , pkt1, pkt1_len))`

порядок отправки перепутан специально?

**Comment by bol-van** [comment]
ipfrag вообще большая боль. фактически он работает только для конкретных целей типа wireguard на своей VPSке, если по пути не порежут. для общего обхода не годится, поскольку сеть враждебна к ip фрагментам. не любит она их.

еще есть проблема с атакой ipfrag на проходящий пакет (forward) , когда используется masquerade.
по идее надо делать так. хватаемся с очень низким приоритетом (predefrag) на output, чтобы до conntrack пометить генеренные в nfqws пакеты как notrack. тогда их conntrack трогать не будет.
НО поскольку генеренный пакет - первый в сеансе, то в conntrack таблице еще нет информации о сеансе.
окей, сгенеренный пакет уходит. в ответ что-то приходит. и создается запись conntrack на основании вошедшего пакета. получается ломается NAT
этой проблемы нет, когда NAT не задействуется. например, в случае исходящего трафика с самой системы

в последней версии добавил переменную POSTNAT_ALL. если ее установить в 1, например в config, то схема nftables переключается на вариант обработки после nat, но в этом случае могут ломаться проходящие атаки на udp

**Comment by AlexeiGHub** [comment]
Проверьте корректность работы при `POSTNAT_ALL=0`

**Comment by bol-van** [comment]
ipfrag не будет работать при POSTNAT_ALL=0, потому что NAT не сможет заменить source address на инетовский
