### ISSUE TITLE
nfqws support for desync dns over tcp

### ISSUE THREAD

**Issue by ccaapton** [bol-van/zapret#162]
In my country dns over udp is usually polluted with early fake reply, but due to tcp handshake mechanism, dns over tcp would be reset if certain domain is detected.

Currently nfqws supports TLS/HTTP hostname extraction and desync, would you mind adding dns over tcp to the supported protocol?

**Comment by bol-van** [comment]
Consider using --desync-any-protocol with  cutoff or  connbytes limiter
