### ISSUE TITLE
tpws начинает потреблять 100% cpu

### ISSUE THREAD

**Issue by its0ka** [bol-van/zapret#164]
Запускаю так:
tpws --bind-addr=127.0.0.1 --port=65535

ip route add local default dev lo table 10
ip rule add fwmark 10 table 10

iptables -t mangle -A PREROUTING -s 10.0.0.0/8 -p tcp --dport 443 -j TPROXY --tproxy-mark 10 --on-ip 127.0.0.1 --on-port 65535

Через несколько дней после запуска процесс tpws начинает потреблять 100% цп, но работать продолжает, перезапуск tpws помогает с нагрузкой цп. Запускаю не так как описано в доках, проблема в этом? или возможно связано с https://github.com/bol-van/zapret/issues/56?

**Comment by bol-van** [comment]
та проблема давно исправлена
с тпрокси особо не тестировал
нужен оутпут с --дебаг
и стрейс

**Comment by its0ka** [comment]
поменял iptables правило на redirect и больше данной проблемы не возникало

**Comment by bol-van** [comment]
Погонял минут 10-15 с кучей вкладок броузера и скачиванием нескольких дебиан ISO.
У меня ничего не сглючилось.

```
ip -f inet rule add fwmark 1 lookup 100
ip -f inet route add local default dev lo table 100
iptables  -t mangle -I OUTPUT -p tcp --dport 443 -m owner ! --uid-owner tpws -j MARK --set-mark 1
iptables -t mangle -I PREROUTING -p tcp --dport 443 -j TPROXY --tproxy-mark 0x1/0x1 --on-ip=127.0.0.1 --on-port=988
ip -f inet6 rule add fwmark 1 lookup 100
ip -f inet6 route add local default dev lo table 100
ip6tables  -t mangle -I OUTPUT -p tcp --dport 443 -m owner ! --uid-owner tpws -j MARK --set-mark 1
ip6tables -t mangle -I PREROUTING -p tcp --dport 443 -j TPROXY --tproxy-mark 0x1/0x1 --on-ip=::1 --on-port=988
tpws --debug --port 988 --user tpws --tlsrec=sni

```
