### ISSUE TITLE
TLS inspection bypass

### ISSUE THREAD

**Issue by Hhk78** [bol-van/zapret#165]
The program runs smoothly under normal conditions. Thank you to the producers.
However, my school internet has TLS inspection. It is not possible to access the internet directly without the CA certificate issued by my school. Dns is extremely poisoned but I can solve it with dns over https. When I run zapret service, I can access http sites, but I cannot access https sites because of the "secure connection could not be established" error.
Is there a way to bypass TLS inspection?
(note:I am experiencing the same problem with the Goodbye DPI program for Windows.)
Sorry for the English, I used google translate.

**Comment by bol-van** [comment]
not possible if the tls expector is a proxy running on a full OS with tcp/ip layer
zapret is antiDPI tool

**Comment by bol-van** [comment]
if you can connect to an arbitrary http you can setup something like GOST on your server and use it as tunnel

**Comment by bol-van** [comment]
https://gost.run/en/
https://gost.run/en/tutorials/http-tunnel/

**Comment by vladns** [comment]
I also use tls inspection on the local network by a higher-level proxy (on the same system), this proxy also issues certificates, because filters https completely. Everything works as intended.
