### ISSUE TITLE
[Question] adding another port than 80/443

### ISSUE THREAD

**Issue by rapdodge** [bol-van/zapret#166]
Is there any ways to adding other port than 80 and 443?

<details>
	<summary>Why I'm asking this</summary>
	I've heard that ID govt are blocking hypixel, and there is one of my colleague that tell me the port 25565 (Minecraft Port) got DPI by the service provider

	
![image](https://github.com/bol-van/zapret/assets/33513626/0a5c32f1-003d-4f66-9f32-810eaa0c1400)

</details>

**Comment by rapdodge** [comment]
> use custom mode with zapret scripts or manual configuration without zapret scripts

How to use that inside the config file? I mean, is that possible to make it works? And could you please give the example the custom zapret scripts?

**Comment by bol-van** [comment]
Look in init.d/sysv (linux) or init.d/openwrt (openwrt)  for custom file
Look also examples in the same dir.
You can write your code to custom based on examples.
Then in config file  or install_easy select MODE=custom

**Comment by rapdodge** [comment]
> Look in init.d/sysv (linux) or init.d/openwrt (openwrt) for custom file Look also examples in the same dir. You can write your code to custom based on examples. Then in config file or install_easy select MODE=custom
> 
> There're 3 functions :
> 
> 1. daemon launch
> 2. iptables firewall setup
> 3. nftables firewall setup
> 
> The most useful example for you is probably custom-tpws4http-nfqws4https

Is that possible to make the configuration are on the config file in the future? To make it easier?

**Comment by bol-van** [comment]
i don't think so.
its very bad idea to redirect all the traffic.
will be misused

**Comment by rapdodge** [comment]
> i don't think so. its very bad idea to redirect all the traffic. will be misused

I mean, not redirect all, maybe giving like configuration like

OtherPort = [25565, 8080, 853]

So, besides 80 and 443, zapret will work on port 25565, 8080, 853

**Comment by bol-van** [comment]
this is why custom scripts exist.
you can highly customize logic there even for more complex needs
i can write a script for you if you provide os type and mode tpws or nfqws

**Comment by rapdodge** [comment]
> this is why custom scripts exist. you can highly customize logic there even for more complex needs i can write a script for you if you provide os type and mode tpws or nfqws

I'm using OpenWrt and using nfqws

**Comment by bol-van** [comment]
Finally did as you desired

update and see config :

# override ports
#HTTP_PORTS=80-81,85
#HTTPS_PORTS=443,500-501
#QUIC_PORTS=443,444

**Comment by rapdodge** [comment]
> Finally did as you desired
> 
> update and see config :
> 
> # override ports
> #HTTP_PORTS=80-81,85 #HTTPS_PORTS=443,500-501 #QUIC_PORTS=443,444

Thanks, I've already forwarding it to my colleagues :)
