### ISSUE TITLE
nfq_unbind_pf(): Invalid argument

### ISSUE THREAD

**Issue by loss-and-quick** [bol-van/zapret#167]
Вот такая ошибка возникает при использовании `blockcheck.sh`
Коммит: 3f80ae2

```checking nfqws --dpi-desync=fake,disorder --dpi-desync-fooling=badsum```
```nfq_unbind_pf(): Invalid argument```

**Comment by bol-van** [comment]
Этот код не менялся годы.

ОС, версия, ядро, архитектура, нет ли запуска из контейнера ?

**Comment by loss-and-quick** [comment]
> Этот код не менялся годы.
> 
> ОС, версия, ядро, архитектура, нет ли запуска из контейнера ? Воспроизводится устойчиво, при каждой проверке стратегии ? Или иногда, хаотично
> 
> Если в ядре нет NFQUEUE, то происходит именно как у вас
1. 
OS: OpenWRT 23.05 
Arch: mips32r1-lsb
Чисто бинарники
2.
OS: Arch
Arch: x64
Также бинарники

**Comment by bol-van** [comment]
6) На чистой openwrt потребуются дополнительные пакеты. 
opkg update
opkg install curl
Требуемые пакеты для iptables :
opkg install iptables-mod-extra iptables-mod-nfqueue iptables-mod-filter iptables-mod-ipopt iptables-mod-conntrack-extra
Требуемые пакеты для iptables ipv6 :
opkg install ip6tables-mod-nat ip6tables-extra
Требуемые пакеты для nftables (с версии 22.03 openwrt перешел на nftables по умолчанию) :
opkg install nftables kmod-nft-nat kmod-nft-queue

Это было установлено ? Как вариант прогнать install_easy до установки пакетов, потом прервать

lsmod | grep nfnetlink_queue

выдает загруженный модуль ?

**Comment by bol-van** [comment]
> OS: Arch

На традиционных linux никогда такого у меня не было, никто никогда вообще на эту проблему не жаловался за многие годы. У меня соответственно тоже не воспроизводится. Мне только удалось это воспроизвести, если принудительно заблокировать загрузку модуля ядра nfnetlink_queue.
Попробуйте на чистой системе. Загрузитесь с livecd. Все это очень странно
