### ISSUE TITLE
tpws request_sock_TCP: Possible SYN flooding on port 65530

### ISSUE THREAD

**Issue by its0ka** [bol-van/zapret#168]
раз в пару дней вижу в логе ядра
`[Sat Dec 23 18:54:18 2023] TCP: request_sock_TCP: Possible SYN flooding on port 65530. Dropping request.  Check SNMP counters.`
уже увеличивал net.ipv4.tcp_max_syn_backlog до 163840, чего в теории достигнуть не могу из-за ограничений conntrack, somaxconn,... Но сообщение в логе все равно появляется. tpws запускаю командой 
`/opt/zapret/tpws/tpws --port=65530 --bind-addr=10.50.1.2 --skip-nodelay` и далее добавляю правило iptables REDIRECT --to-port 65530
вообще tpws использую для ускорения tcp трафика wireguard клиентов, может есть какой-то другой способ? спасибо

**Comment by bol-van** [comment]
> раз в пару дней вижу в логе ядра

Если раз только в пару дней, то это вряд ли можно считать проблемой
Это сообщение может возникнуть, когда tpws не успевает принимать входящие подключения через accept()
Слишком огромное количество попыток куда-то приконектиться идет. Может тупо процессор не успевать, особенно если девайс слабенький.
В этом случае можно использовать средства iptables или nftables для load balancing на разные tpws. Каждый tpws однопоточный, но если их несколько, то нагрузка распределится. В iptables можно воспользоваться -m statistic.

> tpws использую для ускорения tcp трафика wireguard клиентов, может есть какой-то другой способ? спасибо

В чем же состоит ускорение ? Мне кажется наоборот, если избавиться от проксирования, будет лучше. Нет ?

**Comment by its0ka** [comment]
"В чем же состоит ускорение ? Мне кажется наоборот, если избавиться от проксирования, будет лучше. Нет ?"Забыл написать, что Wireguard сервер используется для выхода в интернет на клиентах, но скорость скачивания при этом низкая из-за потери пакетов (плохой инет провайдер на клиентах). Когда клиент wg скачивает что-то с серверов в инете с TCP cubic, то скорость не поднимается выше 100кб/сек, а если включить tpws и tcp bbr на wg сервере, то скорость скачивания у клиентов возрастает до 2мб/сек, тестил на speedtest.selectel.ru. Вот нашёл тсп прокси который делали специально для ускорения тсп https://github.com/cyyself/TCPTP-booster, пока не пробовал его25.12.2023, 10:10, "bol-van" ***@***.***>:

раз в пару дней вижу в логе ядра

Если раз только в пару дней, то это вряд ли можно считать проблемой
Это сообщение может возникнуть, когда tpws не успевает принимать входящие подключения через accept()
Слишком огромное количество попыток куда-то приконектиться идет. Может тупо процессор не успевать, особенно если девайс слабенький.
В этом случае можно использовать средства iptables или nftables для load balancing на разные tpws. Каждый tpws однопоточный, но если их несколько, то нагрузка распределится. В iptables можно воспользоваться -m statistic.

tpws использую для ускорения tcp трафика wireguard клиентов, может есть какой-то другой способ? спасибо

В чем же состоит ускорение ? Мне кажется наоборот, если избавиться от проксирования, будет лучше. Нет ?

**Comment by bol-van** [comment]
> https://github.com/cyyself/TCPTP-booster,

Очень простая прога. Использует блокирующие сокеты, значит может и обязательно будет виснуть.
Если какой-то клиент тупит, то на recv подвиснет, остальные будут ждать. Если много tcp, то вообще будет смерть
