### ISSUE TITLE
Обход замедления твиттера/Twitter

### ISSUE THREAD

**Issue by oifj34f34f** [bol-van/zapret#169]
Добрый день. Может оффтоп, но может ли кто-нибудь поделиться стратегией обхода замедления твиттера?

Сейчас есть это (обходит блокировку сайтов, но не замедление twitter):

```
NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder --dpi-desync-ttl=4 --dpi-desync-ttl6=0 --dpi-desync-fooling=badsum"
```
(zapret запущен на домашнем компьютере под управлением GNU/Linux)

/etc/hosts:
```
104.244.42.13 twitter.com www.twitter.com api.twitter.com
104.244.43.131 pbs.twimg.com video.twimg.com
```

Трюки с split2 не работают, провайдер: Beeline, Home

**Comment by bol-van** [comment]
На чем тестируем ? Конкретно, URL. Или визуально по броузеру ?

Вот это на 3 провайдерах быстро, даже без zapret :
curl -O https://video.twimg.com/ext_tw_video/1034694646478397440/pu/vid/6000/10000/1280x720/VFKufcmUdCH2WGeK.ts

На другом подключении провайдера твиттер вообще блокируется полностью

**Comment by oifj34f34f** [comment]
@bol-van Извиняюсь, забыл упомянуть, что через браузер скорость нормальная. Но когда локально запускаю nitter (легковесный фронтенд твиттера), скорость загрузки ИЗОБРАЖЕНИЙ и ВИДЕО (именно их) очень медленная, возможно это связано с https://github.com/zedeus/nitter/issues/477 [**1**]. Для примера, страница https://nitter.net/elonmusk (чужой инстанс) загружается быстро. Сейчас выполнил команду которую вы предоставили, не сразу загрузилось (как будто пинг 20 секунд был, а потом сразу загрузилось) [**2**].

Так что я наблюдаю замедление скорости только при кейсах [**_1_**] и [**_2_**] (думаю их объединяет общая проблема), но не при использовании в браузере

**Comment by oifj34f34f** [comment]
Кажется нашёл проблему. Надо было удалить

```
104.244.43.131 pbs.twimg.com video.twimg.com
```
из /etc/hosts

Спасибо за помощь
