### ISSUE TITLE
Offtopic: а можно ли подобными техниками починить другие протоколы?

### ISSUE THREAD

**Issue by Nekotekina** [bol-van/zapret#173]
Вкратце, мой провайдер уничтожил DHT в торрентах.
К узлам подключается, а вот количество сидов/пиров всегда 0.
Переносить полностью трафик на слабенький VPS желания нет.
Выборочно — что-то клиенты из доступных слишком убогие в этом плане.
Я очень извиняюсь, спасибо вам за вашу работу, просто не знаю даже где спросить.

**Comment by bol-van** [comment]
Можно, но вне рамок стандартных скриптов запуска
Либо руками, либо custom script. Примеры для DHT там есть
nfqws распознает DHT, так что --dpi-desync-any-protocol не нужен

из методов дурения либо fake, либо tamper
