### ISSUE TITLE
zapret along with jool

### ISSUE THREAD

**Issue by maxpain** [bol-van/zapret#174]
Я пытаюсь заставить работать zapret вместе с Jool (NAT64 gateway) в kernel mode, но не понимаю как нужно настраивать tpws.
IPv6 пакеты от wireguard клиентов приходят на VM, которая трансформирует эти пакеты в IPv4, и после этого должен отрабатывать tpws.

Мне нужно включать поддержку IPv6 в tpws или нет?
Что лучше использовать, nftables или iptables?

**Comment by bol-van** [comment]
tpws цепляется на prerouting, поэтому он перехватывает поток на этапе вхождения на систему
он не может перехватывать на этапе ухода из системы
если на вход идет ipv6, значит и перехватывать тоже надо ipv6. tpws не меняет адрес назначения, потому он будет эманировать аналогичный tcp поток от себя. следовательно, нужно сделать так, чтобы ваш jool корректно работал не только на входящий, но и на генерируемый на этой же системе трафик. может он это или нет - я не знаю.
если с этим будут проблемы, лучше использовать nfqws. он цепляется как раз на уходящий трафик

**Comment by maxpain** [comment]
Jool делает NAT64 трансляцию только если пакет форвардится.

https://nicmx.github.io/Jool/en/faq.html#why-is-my-ping-not-working
```
Why is my ping not working?
Probably because you started the ping on the same machine (or rather, network namespace) your translator instance is attached to.

At present, Netfilter Jool only hooks itself to [PRE_ROUTING](https://netfilter.org/documentation/HOWTO/netfilter-hacking-HOWTO-3.html). It does not attach itself to LOCAL_OUT. This means it can only translate traffic that inbounds from some interface (physical or otherwise). It does not intercept packets sourced from its own network namespace.

Because iptables provides matching functionality, it makes more sense to attach iptables Jool instances to LOCAL_OUT. And AFAIK, there’s nothing stopping you from doing so. But don’t quote me; I haven’t tested it.
```

**Comment by bol-van** [comment]
Тогда смотрите в сторону построения роутера на базе виртуальных интерфейсов.
Их великой множество. Выбирайте, используйте ip rule, таблицы маршрутизации.
Суть такая, что

IPV6 -> ETH0 -> NAT64 -> VETH -> ETH1
Перехват ipv4 на этапе veth

**Comment by maxpain** [comment]
Хм, было бы идеально обойтись без отдельного netspace.
Настроил по вашему совету `nfqws`, который вешается на `POSTROUTING`, а Jool настроил в iptables режиме (до этого работал в netfilter режиме, и, кстати, nftables не поддерживает) 

```
iptables -t mangle -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A PREROUTING -j JOOL --instance dns64
-A POSTROUTING -o ens3 -p tcp -m multiport --dports 443 -m connbytes --connbytes 1:6 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -m set ! --match-set nozapret dst -j NFQUEUE --queue-num 201 --queue-bypass
-A POSTROUTING -o ens3 -p tcp -m multiport --dports 80 -m connbytes --connbytes 1:6 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -m set ! --match-set nozapret dst -j NFQUEUE --queue-num 200 --queue-bypass
```

(в ip6tables всё аналогично)

По логике всё должно работать, но приходящие из wg пакеты обрабатываются только Jool'ом, а `nfqws` их не трогает, странно.

**Comment by maxpain** [comment]
Решил добавить лог после `Jool` и до `nfqws`, обнаружил что логирование срабатывает пока не добавлю к нему фильтр `-m connbytes --connbytes 1:6 --connbytes-mode packets --connbytes-dir original`

**Comment by bol-van** [comment]
Это может говорить о том, что пакет не проходит conntrack вообще
Может там в -t raw написано NOTRACK ?

virtual router только кажется чем-то сложным. на само деле все довольно легко

**Comment by maxpain** [comment]
> Может там в -t raw написано NOTRACK ?

```shell
iptables -t raw -S
-P PREROUTING ACCEPT
-P OUTPUT ACCEPT
```

> virtual router только кажется чем-то сложным. на само деле все довольно легко
Да, попробую посмотреть в эту сторону тоже)

**Comment by bol-van** [comment]
Вот так у меня работает
Вклинивание промежуточного виртуального узла между маршрутизацией подсети 192.168.1.0/24 в сеть 192.168.4.0/24 со шлюзом 192.168.4.1

```
ip netns add virt
ip link add veth0 type veth peer name veth1
ip link set netns virt veth1
ip addr add 172.31.255.253/30 dev veth0
ip -n virt addr add 172.31.255.254/30 dev veth1
ip link set dev veth0 up
ip -n virt link set dev veth1 up
ip r del default
ip r add default via 172.31.255.254 dev veth0

ip link add mvl1 link eth0 type macvlan mode bridge
ip link set mvl1 netns virt
ip -n virt link set dev mvl1 up
ip -n virt addr add 192.168.4.254/24 dev mvl1
ip -n virt r add default via 192.168.4.1 dev mvl1
ip -n virt r add 192.168.1.0/24 via 172.31.255.253  dev veth1

ip netns exec virt nft -n create table ip virt
ip netns exec virt nft -n create chain ip virt postrouting "{ type nat hook postrouting priority srcnat; policy accept; }"
ip netns exec virt nft -n add rule ip virt postrouting oifname mvl1 iifname veth1 masquerade

```

**Comment by bol-van** [comment]
Что характерно, так это обработка на tpws в том числе и локальных соединений, рожденных из корневого неймспейса самого роутера. tpws их хватает в своем неймспейсе как prerouting входящие с интерфейса
Получается, что я обрабатываю как входящие 192.168.1.1, так и рожденные на роутере, но все они становятся проходящими для неймспейса virt

В случае nat64 надо разобраться чем будут являться создаваемые им пакеты между адресами ipv4.
Если он их сам генерит, то это получается OUTPUT. Или же он еще как-то хитро что-то делает, я в нем не разбирался

**Comment by maxpain** [comment]
https://nicmx.github.io/Jool/en/node-based-translation.html

Кажется проще будет запихать Jool в отдельный netns, а zapret оставить в глобальном.

**Comment by maxpain** [comment]
Сделал вот так в общем, работает!
```
ip netns add jool
ip link add name to_jool type veth peer name to_world
ip link set up dev to_jool
ip link set dev to_world netns jool
ip netns exec jool ip link set up dev to_world
ip -6 address show scope link dev to_jool
ip netns exec jool ip -6 address show scope link dev to_world
ip netns exec jool ip -6 route add default via fe80::bc10:ecff:fe0f:277 dev to_world
ip netns exec jool ip -4 address add 192.0.2.2/24 dev to_world
ip netns exec jool ip -4 route add default via 192.0.2.1 dev to_world

ip -6 route add 64:ff9b::/96 via fe80::24fc:24ff:fe9c:3f9a dev to_jool
ip -4 address add 192.0.2.1/24 dev to_jool

ip netns exec jool jool instance add --netfilter --pool6 64:ff9b::/96 nat64
```

**Comment by maxpain** [comment]
@bol-van осталось понять что не так с MTU.
Если делать запросы непосредственно с самой VM без Jool то полёт нормальный:
```bash
wget https://abs.twimg.com/responsive-web/client-web/main.a2166cda.js
--2024-02-24 14:21:54--  https://abs.twimg.com/responsive-web/client-web/main.a2166cda.js
Resolving abs.twimg.com (abs.twimg.com)... 152.199.21.141, 2606:2800:233:8173:898f:63b3:95c3:79d2
Connecting to abs.twimg.com (abs.twimg.com)|152.199.21.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2748467 (2.6M) [application/javascript]
Saving to: ‘main.a2166cda.js’

main.a2166cda.js                           100%[======================================================================================>]   2.62M  --.-KB/s    in 0.1s

2024-02-24 14:21:55 (19.9 MB/s) - ‘main.a2166cda.js’ saved [2748467/2748467]
```

А если через Jool, то скорость мизерная:
```bash
wget --no-check-certificate --header='Host: abs.twimg.com' https://[64:ff9b::98c7:18b9]/responsive-web/client-web/main.a2166cda.js
--2024-02-24 14:24:53--  https://[64:ff9b::98c7:18b9]/responsive-web/client-web/main.a2166cda.js
Connecting to [64:ff9b::98c7:18b9]:443... connected.
    WARNING: certificate common name ‘*.twimg.com’ doesn't match requested host name ‘64:ff9b::98c7:18b9’.
HTTP request sent, awaiting response... 200 OK
Length: 2748467 (2.6M) [application/javascript]
Saving to: ‘main.a2166cda.js.1’

main.a2166cda.js.1                           1%[>                                                                                      ]  32.00K  3.70KB/s    eta 10m 38s
```

**Comment by maxpain** [comment]
Пофиксил вот так:
```bash
ip link set dev to_jool mtu 1412
ip netns exec jool ip link set dev to_world mtu 1412
```
