### ISSUE TITLE
ya-browser

### ISSUE THREAD

**Issue by ops244** [bol-van/zapret#175]
привет, вопрос такой, я установил на кинетик запрет, но проблема появилась:
при попытке открыть некоторые сайты в яндекс браузере - они не открываются, при этом в хроме и мозилле работают, и так сайты вразнобой, может открываться в яндексе, а через 15мин не открываться (но зато в других браузерах работает)
это какая-то блокировка со стороны браузера дополнительная или что?
например https://kinozal.tv/ в яндексе нивкакую не открывает, в других работает

**Comment by bol-van** [comment]
Провайдер DNS не подменяет ? Некоторые броузеры по умолчанию используют DoH

**Comment by ops244** [comment]
так если-бы провайдер подменял, он разве в других браузерах открывал-бы?
так и я использую doh в связке с zapret

**Comment by ops244** [comment]
еще заметил, если перезапустить zapret? то и в яндексе начинает работать минут 5, потом отвал, при этом в других браузерах продолжает работать

**Comment by bol-van** [comment]
В таком случае нужно проводить технический анализ. От пользовательских наблюдений толку мало для выяснения ситуации

**Comment by ops244** [comment]
может подскажите каким образом сделать? я-то в этом ничего не понимаю, чтобы вам понятно было))
еще заметил, если из браузера яндекса не выходить, а постоянно в нем сидеть, то он работает, стоит его на 5мин оставить, сразу отвал (но другие работают при этом) особенно хорошо заметно, если браузер свернуть и зайти в игру, сразу отваливается

**Comment by bol-van** [comment]
Пробуйте гонять блокчек с 5 попытками и смотрите на всех ли попытках одно и то же
Если не получится, тогда забейте и найдите вариант попроще

**Comment by ops244** [comment]
20 гоняю вот, не одно и тоже, иногда не проходит
![Снимок экрана 2024-02-26 170815](https://github.com/bol-van/zapret/assets/19797600/9c6e4b4a-713e-4b8f-8898-88de8d83e13c)

**Comment by bol-van** [comment]
Есть ли стратегии, в которых полностью все available ? Если есть, такие и надо использовать
и еще надо прогнать на парочке других блоченых сайтов, чтобы убедиться, что эти ресеты вызваны DPI, а не защитой сайта от долбежки

**Comment by ops244** [comment]
вот 3 браузера одновременно запущенных, не работает только на яндексе
![Снимок экрана 2024-02-26 171821](https://github.com/bol-van/zapret/assets/19797600/2e18f204-c74d-4eda-a342-466a48a5a7e0)

**Comment by bol-van** [comment]
Может быть какие-то броузеры пытаются лезть по QUIC, и их там заворачивает
В любом случае, пока не удастся добиться устойчивых результатов на curl, броузеры даже рассматривать не стоит
Это может быть лотерея с кэшами. Где-то подгрузился, где-то нет, и случайные хаотичные ресеты

**Comment by ops244** [comment]
ну нашел он стратегии после 20, все та-же ситуация, яндекс не работает, другие работают и это не кэш, я хожу по сайтам и скачиваю что нужно
![Снимок экрана 2024-02-26 193135](https://github.com/bol-van/zapret/assets/19797600/c661fabf-b514-44c2-91c2-c26e617cf0e3)

**Comment by bol-van** [comment]
hopbyhop - это только для ipv6
Если есть ipv6, то для него стратегия может отличаться, и нужно либо составлять комбинированную, либо прописывать отдельно
В этом и может быть причина. Броузеры могут сами выбирать как им лезть по 4 или 6. Их цель - чтобы страница открылась быстрее. Но другие броузеры могут следовать стандартному порядку выбора 4/6, как настроено в ОС. По умолчанию ipv6.

**Comment by bol-van** [comment]
И что вписал в конфиг ?

**Comment by ops244** [comment]
все 
![Снимок экрана 2024-02-26 204703](https://github.com/bol-van/zapret/assets/19797600/a79cedd3-47ad-473a-834c-4d453fc21224)

**Comment by bol-van** [comment]
И как , curl с компа успешно дергает рутрекер ?
curl -4I https://rutracker.org
curl -6I https://rutracker.org
curl -4kI https://rutracker.org
curl -6kI https://rutracker.org

**Comment by ops244** [comment]
успешно firefox и chrome, яндекс не работает

**Comment by bol-van** [comment]
Я написал про curl. Если вы не можете его запустить, то смысла продолжать дальше нет
берите VPN и пользуйтесь

**Comment by ops244** [comment]
так чтоле?
![Снимок экрана 2024-02-26 205908](https://github.com/bol-van/zapret/assets/19797600/5d80b39d-e471-4541-91d4-338c48a2a029)

**Comment by bol-van** [comment]
Так.  http работает
а с https что ?

**Comment by ops244** [comment]
![Uploading Снимок экрана 2024-02-26 205908.png…]()

**Comment by ops244** [comment]
![Снимок экрана 2024-02-26 205908](https://github.com/bol-van/zapret/assets/19797600/d25a43a5-0e83-400f-b059-613b2b7e2c01)

**Comment by bol-van** [comment]
Немного подкорректируем curl для http. По ходу ТСПУ не реагирует на метод HEAD (-I)
Для https все равно (зашифровано), а http он сечет

curl -4v http://rutracker.org
curl -6v http://rutracker.org

**Comment by ops244** [comment]
секунду, жду когда отвалится, меня вдруг озарило, что пробел в конфиге не нужен)))
![2024-02-26_21-11-36](https://github.com/bol-van/zapret/assets/19797600/95c1b2a4-5ada-4872-92b8-d43aa4397eed)

**Comment by bol-van** [comment]
Однозначно, это ошибка синтаксиса. Удивительно как это вообще работало
Тогда исправляем и делаем все курл тесты заново

curl -4v http://rutracker.org/
curl -6v http://rutracker.org/
curl -4v https://rutracker.org/
curl -6v https://rutracker.org/

**Comment by ops244** [comment]
один хрен отвалился, еще заметил, на телефоне все сайты ломает, а другие не открывает (тоже яндекс браузер)
![Снимок экрана 2024-02-26 211712](https://github.com/bol-van/zapret/assets/19797600/24f6a4c4-1e9c-47dd-9ee0-dd0f15c24a08)

![Снимок экрана 2024-02-26 211712](https://github.com/bol-van/zapret/assets/19797600/d6e3cef5-6417-4f45-9edb-47151bc591c0)

**Comment by bol-van** [comment]
Это только http, и видно, что на ipv6 обход не сработал

**Comment by ops244** [comment]
C:\Users\ops24>curl -4v https://rutracker.org/
*   Trying 172.67.182.196:443...
* Connected to rutracker.org (172.67.182.196) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET / HTTP/1.1
> Host: rutracker.org
> User-Agent: curl/8.4.0
> Accept: */*
>
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 26 Feb 2024 18:20:27 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: https://rutracker.org/forum/index.php
< CF-Cache-Status: DYNAMIC
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=csV6BeduTY4Ahx0kp7nr41Qp%2Fk%2B2y7gE7%2BoBo9rZysS%2BOROAqFTpOxlcMPC0ZELSihCPUwjfQ8gcqEYUTIo8IZY2vUQo7FZPR%2FI2%2BHkkPME3iyEC7Qg3qddpZXMDMDd1"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 85ba33bf4a5e5bb8-VIE
< alt-svc: h3=":443"; ma=86400
<
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"85ba33bf4a5e5bb8","version":"2024.2.1","r":1,"token":"644a095bdbc6472da3072c1512cdb737","b":1}' crossorigin="anonymous"></script>
</body>
</html>
* Connection #0 to host rutracker.org left intact

C:\Users\ops24>curl -6v https://rutracker.org/
*   Trying [2606:4700:3034::ac43:b6c4]:443...
* Connected to rutracker.org (2606:4700:3034::ac43:b6c4) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* Recv failure: Connection was reset
* schannel: failed to receive handshake, SSL/TLS connection failed
* Closing connection
* schannel: shutting down SSL/TLS connection with rutracker.org port 443
* Send failure: Connection was reset
* schannel: failed to send close msg: Failed sending data to the peer (bytes written: -1)
curl: (35) Recv failure: Connection was reset

**Comment by ops244** [comment]
lблин в скрин не убиралось, вот
![Снимок экрана 2024-02-26 212157](https://github.com/bol-van/zapret/assets/19797600/3ec08206-3d8c-49d4-92f9-1376eb920851)

**Comment by bol-van** [comment]
Видно, что на ipv6 обход вообще не сработал
Надо снимать zapret
killall nfqws (на всякий случай)
blockcheck.sh | tee /tmp/bl.txt
прогоняем только ipv6
лог /tmp/bl.txt сюда

**Comment by ops244** [comment]
пока выполняется, пара вопросов)
может это быть из-за того, что в роутере в DOH 3 разных сервера прописаны? типа те 2 браузера работают через google dns, яндекс тоже на нем начинает, потом видит в списке свой-же днс яндекс и переключается на него, а там стратегия не работает?

**Comment by bol-van** [comment]
Нет, дело тут не в DNS.
броузеры имеет смысл проверять только после curl

**Comment by ops244** [comment]
лог почему-то не сохранил он, вот результат
!!!!! curl_test_https_tls12: working strategy found for ipv6 rutracker.org : nfq                                                                                                        ws --dpi-desync=fake,split2 --dpi-desync-ttl=2 !!!!!

clearing nfqws redirection

* SUMMARY
ipv6 rutracker.org curl_test_http : tpws not working
ipv6 rutracker.org curl_test_http : nfqws --dpi-desync=fake --dpi-desync-ttl=2
ipv6 rutracker.org curl_test_https_tls12 : tpws not working
ipv6 rutracker.org curl_test_https_tls12 : nfqws --dpi-desync=fake,split2 --dpi-                                                                                                        desync-ttl=2

**Comment by bol-van** [comment]
В логе как раз и был смысл
Команда tee присутствует ?
/tmp доступен на запись ? echo test >/tmp/test

в конфиге /opt/zapret/config случаем не отключен обход ipv6 ? DISABLE_IPV6
Если запустить zapret с тем, что найдено, то curl с роутера на рутрекер срабатывает ?

**Comment by ops244** [comment]
я вообще уже ничего не понимаю, если я запустил zapret (uninstall) и выполнил, он почему его запустил после перезагрузки?!

**Comment by bol-van** [comment]
Потому что это кинетик, который официально я не поддерживаю
Автозапуск там ручками прикручен согласно инструкции со стороннего сайта

**Comment by ops244** [comment]
при echo test >/tmp/test ничего не происходит вобщем...
вообще мне только одна папка доступна по ftp - ьте какая-то, она пустая, если смотреть в проводнике встроенном в роутер, то папка tmp пустая, но как она может быть защищена, если я туда скачивал запрет с репозитория, вероятно не видит через этот проводник
с момента перезапуска прошло вот полчаса, досих пор яндекс работает, настройки не менял, я хз что это такое...

**Comment by ops244** [comment]
дело в том, что во внутренней памяти все установлено, если-бы на флешке было, я бы мог увидеть лог я так понимаю

**Comment by bol-van** [comment]
/tmp - обычно это tmpfs, файловая система в RAM
если на роутере ssh, то возможно файлы можно передать через sftp
в противном случае можно перекинуть обычным неткатом
на компе netcat -l -p 10000 >bl.txt      снять фаервол винды, netcat найти бинарики под винду
на роутере nc <IP_OF_COMP> 10000 </tmp/bl.txt

**Comment by ops244** [comment]
только эта папка доступна по sftp, даже в саму tmp не пускает
но дело-то в том, что у меня сейчас все работает и я ничего не менял... вот уже 40мин
![Снимок экрана 2024-02-26 232829](https://github.com/bol-van/zapret/assets/19797600/15905eb7-9002-4456-9e8f-5dbdd5cceb66)

**Comment by ops244** [comment]
только он мне все сайты сломал и половину не открывает (короче теперь как на мобиле до этого было...) но зато не отваливается))) ладно, на сегодня хватит, завтра запущу еще раз и попробую логи снять все-таки (вероятнее всего все нужно на флешку со внутренней памяти будет перенести)
![2024-02-26_23-32-13](https://github.com/bol-van/zapret/assets/19797600/139a85f3-890d-46f6-bdb7-4e35076cb2ce)

**Comment by bol-van** [comment]
Можно использовать фильтр по hostlist  и вести список , возможно даже сработает autohostlist (не проверял на кинтетиках, могут быть проблемки)
Если делать логи, то лучше на все. 4+6
Стратегия с wssize не очень желательна

**Comment by ops244** [comment]
за ночь обнаружился интересный факт, если выключить ipv6 у провайдера, все работает идеально, и сайты открывает и не ломает... посмотрев форумы, увидел такая проблема у многих на кинетиках (именно работает минут 10 и отрубается) и все ipv6 пытались использовать...

**Comment by bol-van** [comment]
О таких вещах надо не гадать, а проверять конкретными измерительными инструментами, броузер к которым не относится.
Для проверки ipv6 есть команда ping

**Comment by ops244** [comment]
ладно, мне ipv4 достаточно, по поводу ipv6 вы-же сами сверху писали, что обход вообще для него не сработал, тут впринципе все и понятно, яндекс по ipv6 лезет, а другие по ipv4...

**Comment by bol-van** [comment]
Я сказал, что он не сработал по факту, а не то, что он не может в принципе сработать
И почему - можно разобраться. А можно в топку и отключить ipv6

**Comment by bol-van** [comment]
У меня есть во дворе SPB free wifi. Это ДОМРУшный халявный городской wifi.
На нем нет ipv6, но по результатам анализа прекрасно работает стратегия http+https
--dpi-desync=fake,split2 --dpi-desync-split-pos=1 --dpi-desync-ttl=9 --dpi-desync-fooling=md5sig
(для непосредственного подключения к провайдеру TTL скорее всего следует уменьшить до 8)
Вероятно ipv6 тоже с этим будет работать.

Но насколько я знаю этот обдолбаный домсру, они выдают динамическую подсеть /64. каждый раз она разная при переподключении pppoe или ребуте роутера.
У многих роутеров с этим могут быть проблемы в силу особенностей конфигурации IPv6 адресов. Может получиться так, что комп будет использовать уже неактуальный префикс, пока не передернешь кабель, перезапустишь сетевуху через диспетчер устройств или ребутнешь комп.

PPoE: Выделяется динамический IPv6 префикс /64 (из диапазона 2a02:2698::/32)
PPPoE: Доступен статический IPv6 префикс /64 (из подсети 2a03:1ac0::/32) при включении услуги «Постоянный IP» / «Статический IP» (с мая 2020 года)

если нужен норм ipv6, очень рекомендую обзавестись вариантом 2

**Comment by ops244** [comment]
да, вы правы, у многих роутеров с ним проблема, например тп-линк года полтора не могли сделать нормальный ipv6 к нему))
а как вы поняли, что домру? я вроде не говорил вам?))

**Comment by bol-van** [comment]
Редирект заглушкой на ertelecom

**Comment by bol-van** [comment]
Какой бы хороший ни был роутер, если он выдает неограниченный lease на ipv6, префикс динамический, и внезапно роутер ресетают передергом питания, то уже некому будет отдать сообщение "префикс протух". Префиксы на компе будут копиться, будут использоваться старые нерабочий, будут виснуть все запросы

**Comment by ops244** [comment]
я тогда пока ipv4 оставляю да и можно считать проблему решенной, а покупать у них постоянный адрес за 200р в мес - того не стоит, я в 2 раза дешевле vds могу взять и vpn настроить, весь смысл теряется, да и хотелось-бы бесплатное решение, тут у нас другие провайдеры тянут, может у них нормальный ipv6 будет, посмотрим
в любом случае вам спасибо за потраченное время и поиск проблемы)
