### ISSUE TITLE
tpws randomly crashes

### ISSUE THREAD

**Issue by AronEquip** [bol-van/zapret#177]
`/opt/zapret/tpws/tpws --user=daemon --bind-addr=127.0.0.127 --port=11991 --tlsrec=sni --split-pos=10 --hostspell=hosT --hostcase --debug`

https://github.com/bol-van/zapret/assets/108195508/961fb6f8-14c7-4ad5-9d4e-cdd161d8c54d

Sorry my english is very bad.

**Comment by AronEquip** [comment]
ISP: Smartfren (AS18004)
Live in Lampung, Indonesia

https://github.com/bol-van/zapret/assets/108195508/dc31603c-c40a-4c3f-9bba-a04f6e156248

**Comment by bol-van** [comment]
You run this on windows WSL, yes ?
Is this WSL1 or WSL2 ?
only socks mode is supported on WSL1
Compile yourself with debug info (remove -s in Makefile)
then run in gdb and do 'bt' (backtrace)

**Comment by bol-van** [comment]
I believe I fixed this. It could happen if :

1) client sends request
2) remote end does not connect (blackhole, timeout)
3) client breaks connection (ctrl+C)
4) --tlsrec tampering enabled

**Comment by AronEquip** [comment]
> You run this on windows WSL, yes ? Is this WSL1 or WSL2 ? only socks mode is supported on WSL1 Compile yourself with debug info (remove -s in Makefile) then run in gdb and do 'bt' (backtrace)

No I'm not using WSL

> I believe I fixed this. It could happen if :
> 
>     1. client sends request
> 
>     2. remote end does not connect (blackhole, timeout)
> 
>     3. client breaks connection (ctrl+C)
> 
>     4. --tlsrec tampering enabled

Tested, No crashes, Thanks you!

**Comment by AronEquip** [comment]
https://github.com/bol-van/zapret/assets/108195508/93fbaae5-edaf-4eab-8ad4-7a1bb7dc8f5e
