### ISSUE TITLE
POSTNAT=1, UDP, nfqws FAKE, ответ не доходит до узла отправившего запрос из локалки

### ISSUE THREAD

**Issue by AlexeiGHub** [bol-van/zapret#179]
OWRT 23.05.3 
При POSTNAT==1  и отправке fake пакета nfqws-ом ответ доходит до роутера, но не до узла отправившего запрос(первоначальный пакет).
Если сессия была установлена до  установки POSTNAT==1  и еще жива(не вышел таймаут) ответный пакет проходит.
QUIC прекрасно работает. Попытка добавить целевой udp порт в порты QUIC  проблему не решает.

Чего я не понимаю?

**Comment by bol-van** [comment]
Да, правда, недосмотрел. Не сработала корректно схема postnat для udp
Если дропаешь в NFQUEUE первый пакет, то из коннтрак сеанс тоже вылетает
Я делал фикс этой проблемы для syndata, придется и для udp сделать

**Comment by AlexeiGHub** [comment]
Почему для QUIC работает?
Там несколько пакетов которые создают сессию?

**Comment by bol-van** [comment]
Там задержка длительная вначале возникает, потому что пакеты в начале дропаются правилом
state INVALID drop
потом прочухивается

**Comment by bol-van** [comment]
Сейчас работает ?
По дампу все уходит как надо
Время реакции curl значительно снизилось

**Comment by AlexeiGHub** [comment]
> Сейчас работает ?

1) FAKE
2) Original
3) **Original with wrong CRC**

Так и должно быть?

**Comment by bol-van** [comment]
да, это средство обхода проблемы сброса коннтрак
я не могу дропнуть первый пакет в NFQUEUE
потому для удп я порчу ipv4 checksum, для tcp - меняю TTL на 1

**Comment by AlexeiGHub** [comment]
Все заработало.
Спасибо!

**Comment by AlexeiGHub** [comment]
И в догонку я ранее намекал на то, что 
params.fake_tls[1460]  а некоторые *.bin которые с KYBER явно более чем 1460?!

**Comment by bol-van** [comment]
Многопакетные фейки пока не поддерживаются. Не вижу в этом смысла
