### ISSUE TITLE
x86?

### ISSUE THREAD

**Issue by anoduck** [bol-van/zapret#18]
I might be showing either how far behind the times I am or my never ending quest to be a cheap skate, but is there going to be an x86 release? My routers are running x86 linux, and it would be nice to get zapret running.

**Comment by bol-van** [comment]
Its very easy to 'make' if you run traditional linux.
If not - install traditional x86 linux in VM  , add "-static" to CFLAGS in makefile  and make.
This binary will run on any linux kernel that support IA32

**Comment by bol-van** [comment]
Added x86 binaries
