### ISSUE TITLE
udp, ipv4, ipfrag2 - теряется фрагмент

### ISSUE THREAD

**Issue by AlexeiGHub** [bol-van/zapret#180]
POSTNAT==0 || 1 - Не отправляет вторую часть оригинального пакета и в первом не правит размер(udp.length). 

Ранее при  POSTNAT==0 не требовался badsum. Может удастся восстановить механику? Мне кажется это может ломать работу протоколов!?

**Comment by bol-van** [comment]
ipfrag будет работать только в postnat режиме или без маскарада
с маскарадом и iptables он не может в принципе работать

при фрагментации на уровне IP  все что дальше , начиная с транспортного уровня, не трогается
если бы это было сделано неправильно, то ipfrag2 вообще бы ни на чем не срабатывал, а он срабатывает на каких-то ресурсах на QUIC

в шарке видны оба фрагмента. но шарк любит их реассемблировать. там надо внимательней смотреть

badsum не относится к ipfrag никак. badsum - это fooling, а fooling относится только к фейк пакетам. фрагментированные куски относятся к оригиналу

**Comment by AlexeiGHub** [comment]
> ipfrag будет работать только в postnat режиме или без маскарада
ОК postnat =1, понятно
> с маскарадом и iptables он не может в принципе работать
а nftables?




> каких-то ресурсах на QUIC
Посмотрите не мешает ли пакет с badsum при постнат=0 рабoте QUIC?

> в шарке видны оба фрагмента. но шарк любит их реассемблировать. там надо внимательней смотреть
Да, вроде смотрю внимательно. По крайней мере стараюсь :)
 


> badsum не относится к ipfrag никак. badsum - это fooling, а fooling относится только к фейк пакетам. фрагментированные куски относятся к оригиналу

Я имел ввиду пакет с неверным ipv4.crc отправка которого сегодня была внедрена

**Comment by bol-van** [comment]
Содержимого пакета с неверной чексуммой или TTL=1 не принципиально.
Оно все равно никуда не доходит. Это просто обманка для проверки в ядре linux на предмет conntrack teardown.
Чтобы он его не делал

**Comment by AlexeiGHub** [comment]
> с неверной чексуммой ... Оно все равно никуда не доходит

Мне кажется что доходит, например WG все равно на него :)

**Comment by bol-van** [comment]
> Посмотрите не мешает ли пакет с badsum(ipv4.crc отправка которого сегодня была внедрена) при постнат=0 рабoте QUIC?

Есть роутер удаленный со старым openwrt на iptables. С самого роутера по крайней мере без проблем работает.

> Мне кажется что доходит, например WG все равно на него :)

Теоретически может срабатывать какой-то оффлоад на сетевой карточке, который фиксит сумму. Я проверял на роутерах mediatek, atheros и на PCке с realtek GBE. Все норм
Но вы можете проверить на своем сервере. Если доходит - будем разбираться

**Comment by bol-van** [comment]
Вот как в шарке выглядит desync ipfrag2 на QUIC
Там 2 IP фрагмента. Оригинал не дропается в случае ipv4, но уродуется ip чексуммой
![ggggggggg](https://github.com/bol-van/zapret/assets/9076680/2e0c0c4b-e049-47bd-864e-553578b1f073)

**Comment by AlexeiGHub** [comment]
> Но вы можете проверить на своем сервере. Если доходит - будем разбираться

Это непринципиально, но с вашей логикой я согласен.

Так может или нет работать ipfrag2 для транзитный пакетов на роутере OWRT?

**Comment by bol-van** [comment]
> Так может или нет работать ipfrag2 для транзитных пакетов на роутере OWRT?

Да, но только на версиях с nftables

**Comment by AlexeiGHub** [comment]
> > Так может или нет работать ipfrag2 для транзитных пакетов на роутере OWRT?
> 
> Да, но только на версиях с nftables

Вот об этом мы(я) сейчас и говорим.  --dpi-desync=fake,ipfrag2 должно приводить к отправке fake и разбитого на две части оригинального пакета?

**Comment by bol-van** [comment]
> С маскарадом --dpi-desync=fake,ipfrag2 должно приводить к отправке fake и разбитого на две части оригинального пакета?

Совершенно верно. Снял дамп с проходного запроса

![ggggggggg](https://github.com/bol-van/zapret/assets/9076680/024eca14-5636-4ba3-b5bf-cc98cc494eb3)

**Comment by AlexeiGHub** [comment]
![изображение](https://github.com/bol-van/zapret/assets/122487966/2110cc69-3e56-4855-a1cb-05da771e1aa9)

**Comment by AlexeiGHub** [comment]
1) Fake
2) 1st frag
3) заглушка с bad crc

**Comment by bol-van** [comment]
Дурение ipfrag2 возможно только с девайса с внешним IP адресом
Любые нат слепят фрагменты или вовсе порежут

Шарк у вас старинный ? Не распознает протокол wireguard, не показывает fragmented пакеты никак
из картинки мне непонятно содержимое этих пакетов, так что я ничего не могу по ней сказать

**Comment by AlexeiGHub** [comment]
> QUIC вообще не чувствителен к мусорным пакетам, потому разницы особой нет есть ли badsum к фейку или нет

Но и смысла серверу отдавать на обработку данные с неправильным crc ipv4 я тоже не вижу.

**Comment by AlexeiGHub** [comment]
> Шарк у вас старинный ?

Нет из последних. Фильтрация стоит udp.port==xxxx

**Comment by bol-van** [comment]
> Но и смысла серверу отдавать на обработку данные с неправильным crc ipv4 я тоже не вижу.

Чексуммы L3 проверяют все без исключения роутеры на пути. С неверной суммой пакет будет обрезан самым первым роутером провайдера. Прежде чем говорить, что он доходит до сервера, реально возьмите свой сервер и посмотрите на нем

**Comment by AlexeiGHub** [comment]
> Чексуммы L3 проверяют все без исключения роутеры на пути

Вряд ли,  иначе badsum fooling не имел бы смысла

**Comment by bol-van** [comment]
> Вряд ли, иначе badsum fooling не имел бы смысла

badsum относится к L4. tcp или udp. и охватывает все тело пакета + адреса src,dst из ip header
L3 сумма ipv4 относится только к L3 хедеру и ни к чему больше
роутеры проверяют только L3 чексумму, а транспортную сумму нет

**Comment by AlexeiGHub** [comment]
![изображение](https://github.com/bol-van/zapret/assets/122487966/2cedaa3f-cb22-45a4-b3ff-28a4b7740082)
Это 2-й пакет 1-й фрагмент

**Comment by AlexeiGHub** [comment]
> badsum относится к L4. tcp или udp.

Да. я снова путаю.  Вы портите L3 CRC в заголовке IPV4

**Comment by bol-van** [comment]
> Да. я снова путаю. Вы портите L3 CRC в заголовке IPV4

да, потому что мне надо по хорошему вообще дропать этот пакет, что я и делаю на ipv6
но если так поступить, то ломается коннтрак. ставить TTL=1 на udp нельзя, поскольку будут приходить ICMP, которые распознаются ОС и шлются нотификации в сокет. хром их распознает
но и патчить пакет тоже нехорошо, ведь тогда он будет принят DPI и тот может его проглотить, разглядев там RUTRACKER

**Comment by AlexeiGHub** [comment]
![изображение](https://github.com/bol-van/zapret/assets/122487966/64c20565-f324-4eb4-854a-09c7c5465e1f)
Это 3-пакет, после него прилетает ответ сервера

**Comment by bol-van** [comment]
> Это 2-й пакет 1-й фрагмент

Что выдает nfqws в debug в это время ?

**Comment by AlexeiGHub** [comment]
> > Да. я снова путаю. Вы портите L3 CRC в заголовке IPV4
> 
> да, потому что мне надо по хорошему вообще дропать этот пакет, что я и делаю на ipv6 но если так поступить, то ломается коннтрак. ставить TTL=1 на udp нельзя, поскольку будут приходить ICMP, которые распознаются ОС и шлются нотификации в сокет. хром их распознает но и патчить пакет тоже нехорошо, ведь тогда он будет принят DPI и тот может его проглотить, разглядев там RUTRACKER

Да, этот аспект я понял. 

осталось на  повестке :)

1) Где 2-й фрагмент
2) Почему сервер отвечает после пакета с неправильным IPV4.crc. Это не принципиально, просто интересная фича или непонимание нюансов
3) Нужен ли для postnan==0  пакета с неправильным L3.CRC

**Comment by bol-van** [comment]
Возможно виноват фильтр udp.port в шарке. кусок он может не распознать как удп. может отключены какие-то опции в настройках шарка собирать фрагменты
я думаю все же фрагмент есть, но он не показывается шарком.  с плохой суммой никуда не уходит, а сервер отвечает на полный пакет, собранный нат провайдера
попробуйте фильтр на ip адрес назначения

**Comment by bol-van** [comment]
> 3\. Нужен ли для postnan==0  пакета с неправильным L3.CRC

Не нужен, но и не мешает. nfqws вообще не знает из какой цепочки его дернули

**Comment by AlexeiGHub** [comment]
> Что выдает nfqws в debug в это время ?

:) А ничего не выдает с --debug=2  странно????!!!!

**Comment by AlexeiGHub** [comment]
> Возможно виноват фильтр udp.port в шарке. кусок он может не распознать как удп. может отключены какие-то опции в настройках шарка собирать фрагменты
> я думаю все же фрагмент есть, но он не показывается шарком. с плохой суммой никуда не уходит, а сервер отвечает на полный пакет, собранный нат провайдера
> попробуйте фильтр на ip адрес назначения

Да надо капнуть глубже.  Там все сложнее  это ssh->tcpdump  cфильтром

**Comment by bol-van** [comment]
> :) А ничего не выдает с --debug=2 странно????!!!!

значит на него ничего не идет. не та очередь или неправильно сделан редирект в таблес
debug level только один в nfqws, можно 2 не писать

**Comment by bol-van** [comment]
> tcpdump cфильтром

tcpdump точно не умеет собирать фрагменты, потому он выбросить кусок без L4 хедера

**Comment by AlexeiGHub** [comment]
> tcpdump точно не умеет собирать фрагменты, потому он выбросить кусок без L4 хедера

А мне и не надо чтоб он собирал. Я рассчитывал на то, что он все с нужным портом отправит в шарк
![изображение](https://github.com/bol-van/zapret/assets/122487966/f8250ac2-51b0-4836-bb65-d5161fc9112e)

**Comment by bol-van** [comment]
> Я рассчитывал на то, что он все с нужным портом отправит в шарк

Порт - это понятие L4 протоколов. Находится он в L4 хедере. Если прога не может собрать пакет на уровне L3, то как она узнает порт во 2-м куске без L4 header  ?

**Comment by AlexeiGHub** [comment]
просто не хочется гнать весь трафик с WAN порта роутера по WiFi на шарк

**Comment by AlexeiGHub** [comment]
> > Я рассчитывал на то, что он все с нужным портом отправит в шарк
> 
> Порт - это понятие L4 протоколов. Находится он в L4 хедере. Если прога не может собрать пакет на уровне L3, то как она узнает порт во 2-м куске без L4 header ?

Очень логично

**Comment by bol-van** [comment]
> просто не хочется гнать весь трафик с WAN порта роутера по WiFi на шарк

фильтр на адрес назначения достаточен
или гуглите как проверять fragment offset на ненулевое значение
фильтр будет : udp.port==443 or <оффсет не 0>

**Comment by AlexeiGHub** [comment]
Изменил правило на host.  Все увидел.

Спасибо огромное за ликбез. я еще по изучаю. 
И если через пару часов не останется вопросов, закрою тикет.

Еще большое спасибо.
