### ISSUE TITLE
Wireguard server with zapret on openwrt

### ISSUE THREAD

**Issue by LoneWolff7** [bol-van/zapret#182]
I have zapret setup on openwrt with tpws, this router also acts as a wireguard server. When my peers like phone, laptop connect to this Wireguard server DPI bypassing does not work. 

Please guide me.

**Comment by bol-van** [comment]
It's not an 'install and it just works' program.
Its quite complex and requires studiying. If you don't want or can't then do not use it

**Comment by LoneWolff7** [comment]
I understand, but I have dpi bypassing already working with tpws on openwrt not through Wireguard tunnel. The guides here talk about Wireguard with a VPS setup but what to do when openwrt is itself a Wireguard server?

**Comment by LoneWolff7** [comment]
Thanks it’s working now over Wireguard. 

I just have one more question, Blockcheck.sh tells me `nfqws --dpi-desync=split2` works against my provider’s DPI so I have set it up this way 

`DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC=--dpi-desync=split2
NFQWS_OPT_DESYNC_HTTP=--dpi-desync=split2
NFQWS_OPT_DESYNC_HTTPS=--dpi-desync=split2
NFQWS_OPT_DESYNC_HTTP6=--dpi-desync=split2
NFQWS_OPT_DESYNC_HTTPS6=--dpi-desync=split2
NFQWS_OPT_DESYNC_QUIC=--dpi-desync=split2
NFQWS_OPT_DESYNC_QUIC6=--dpi-desync=split2`

I still need to activate the `MODE_HTTP_KEEPALIVE=1` for it to work successfully. 

Have I done it the right way here? It is working for me just wanted to confirm though.

**Comment by bol-van** [comment]
It can work but its bad

this is enough
NFQWS_OPT_DESYNC="--dpi-desync=split2"
NFQWS_OPT_DESYNC_HTTP* should be commented

split is useless for UDP (QUIC)

**Comment by LoneWolff7** [comment]
Thanks I will make the necessary changes. Just one last question, can zapret also block ISP’s attempt to block Wireguard? In case in future they start blocking Wireguard handshakes.

**Comment by bol-van** [comment]
May help but requires either custom scripting or manual launch (ip/nf tables + nfqws) without installer and standard script system

**Comment by bol-van** [comment]
In Russia they tried to block wg some time ago.  'fake' method with 6 fakes helped here.
also ipfrag2 works on some servers but it requires external inet IP on the device (NATed won't work) and  nftables for manipulating forwarded traffic

**Comment by LoneWolff7** [comment]
Thanks for thoroughly answering all the questions. I will keep this points in mind about wg blocking if it ever comes to that.

**Comment by Wippito** [comment]
> You have to alter OPENWRT_LAN variable in config file.

Спасибо за ответ. По какой причине трафик все равно может не проходить с такой строкой OPENWRT_LAN="lan WG_0"?
Проблема такая же, как у автора - запрет работает внутри локальной сети, но не через ВПН. К ВПН подключаюсь откуда угодно, но трафик проходит не через запрет

**Comment by bol-van** [comment]
LAN важен для tpws, а для nfqws важен WAN.
Если WAN один, его можно не прописывать. На openwrt найдется сам.
На nfqws должно приходить все, что уходит через WAN.
Так можно проверить какие linux интерфейсы считаются lan и wan.
/etc/init.d/zapret list_ifsets

Если все там в порядке, надо запускать nfqws/tpws с --debug в консоли или --debug=syslog  --debug=@file через скрипты и смотреть лог
