### ISSUE TITLE
nfqws connbytes range 1:6

### ISSUE THREAD

**Issue by disappointed72** [bol-van/zapret#183]
Возникла проблема с nfqws 1,5 недели назад, перестало работать дурение. 
Изучение дампов показало, что при установке TLS соединения, на актуальном версии Chrome, Client Hello пакет стал не 4-ым а 5-ым от начала соединения, четвёртым же начал вставать некий жирный пакет, который я опознал, как возможно ALPN.

После обновления до текущей верcии zapret проблема ушла,  и я вижу, что вы как раз правили connbytes range с 1:4 до 1:6.
При этом нигде не увидел обсуждения, почему хром начал вставлять этот пакет перед хендшейком.

Можно узнать больше информации, что произошло?

**Comment by bol-van** [comment]
Хром стал использовать постквантовую криптографию kyber.
TLS ClientHello раздулся до такого размера, который не вписывается в 1 TCP сегмент со стандартным MTU 1500.
Потому происходит сплит на 2 пакета.
Принимать решение о дурении нужно на основании всего сообщения. В последних версиях nfqws сделана приостановка отправки пакетов в сеть до полной реконструкции сообщения и дурение на первый пакет TLS ClientHello. Остальные части идут как есть.
Замена на 1:6 как раз и призвана перенаправить все части hello на nfqws, а не только первый кусок.

Каких-то других жирных пакетов там я не замечаю.
Шарк показывает, что это hello только на последнем пакете. Если раскрыть TCP header, то там увидите reassembled fragments

**Comment by disappointed72** [comment]
Точно, пишет про него, reassebled segment. Спасибо за объяснение.
