### ISSUE TITLE
SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by MercurialPony** [bol-van/zapret#184]
Запрет не работает при попытке открыть твиттер: `curl -L twitter.com`
```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to twitter.com:443
```
<details>
<summary>(полный лог)</summary>
<pre><code>curl -vL twitter.com
* IPv6: (none)
* IPv4: 104.244.42.193, 104.244.42.1, 104.244.42.129, 104.244.42.65
*   Trying 104.244.42.193:80...
* Connected to twitter.com (104.244.42.193) port 80
> GET / HTTP/1.1
> Host: twitter.com
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< perf: 7402827104
< location: https://twitter.com/
< cache-control: no-cache, no-store, max-age=0
< content-length: 0
< x-transaction-id: daaeb26c04e96e1e
< x-response-time: 98
< x-connection-hash: c55f7bc7fd7905689365de2e8936c32cf782aac986648c3105d37e2389d7b125
< date: Thu, 02 May 2024 18:10:43 GMT
< server: tsa_o
<
* Connection #0 to host twitter.com left intact
* Clear auth, redirects to port from 80 to 443
* Issue another request to this URL: 'https://twitter.com/'
* Host twitter.com:443 was resolved.
* IPv6: (none)
* IPv4: 104.244.42.65, 104.244.42.193, 104.244.42.1, 104.244.42.129
*   Trying 104.244.42.65:443...
* Connected to twitter.com (104.244.42.65) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to twitter.com:443
</code></pre>
</details>

Но при этом такие сайты как rutracker.org работают нормально. В чем может быть проблема?

Устанавливал на Ubuntu 23.10, также пробовал на docker контейнере alpine с установленным iptables (результат такой же). Во время установки через `install_easy.sh` указывал `iptables`, `tpws`, остальное по умолчанию.

При этом twitter без проблем открывается через тот же GoodbyeDPI на винде.

**Comment by bol-van** [comment]
А вы блокчек на твиттер прогоняли на TLS ?
использование zapret без поиска рабочей под конкретного провайдера не имеет смысла
раз два запустил батник и готово - такого нет

**Comment by MercurialPony** [comment]
Да, извиняюсь, действительно с правильными настройками заработало. Возможно стоит получше это описать в readme. В любом случае, спасибо👍

**Comment by bol-van** [comment]
readme - это техническое описание полное
но там в начале есть ссылка на quick start
