### ISSUE TITLE
.

### ISSUE THREAD

**Issue by xboxones1** [bol-van/zapret#187]

**Comment by bol-van** [comment]
запустить с дебаг и tee в файл
и ждать отвала
либо стрейс когда отвал случился
так же убедиться, что он не зациклился по cpu usage

**Comment by xboxones1** [comment]
Потребление я смотрел, не зацикливается.  Запущу с debug и буду смотреть.

**Comment by xboxones1** [comment]
Чуть изменил опции для nfqws и проблемы ушли. Думаю, пока можно закрыть, если повторится то переоткрою уже с логами.

**Comment by xboxones1** [comment]
Вновь столкнулся с этой проблемой и думаю мне удалось выявить из-за чего. После включения обхода для QUICK это начинает происходить, если отключить то работает без проблем. Вот [strace.log](https://github.com/user-attachments/files/16333079/strace.log), если ничего полезного, запущу с debug.

**Comment by bol-van** [comment]
да, нужен дебаг
его можно сделать под screen чтобы не падал при отключении ssh
когда упадет снова переключиться на screen 
если не умеете сначала научитесь пользоваться им

**Comment by xboxones1** [comment]
В целом причину я выяснил, как оказалось ничего не зависает. Я внимательно все проверил и увидел, что процесс не корретно перезапускается. А точнее nfqws может после перезапуска не использовать мои опции, а работает с какими-то дефолтными, иногда может висеть несколько процессов nfqws с разными опциями. Пока решил проблему добавив в функцию перезапуска принудительное закрытие nfqws (killall -q nfqws). Почему так происходит я понять не могу, скрипт использую /init.d/sysv/zapret.

**Comment by bol-van** [comment]
nfqws не может сам запуститься с произвольными опциями
разберитесь кто его запускает
прошивка ничего о нем знать не может
значит это ваше творчество
