### ISSUE TITLE
Ошибка в скрипте get_reestr_hostlist.sh?

### ISSUE THREAD

**Issue by disappointed72** [bol-van/zapret#188]
Почему-то скачивает файл в csv формате, но передаёт его в конвеере в gunzip.
В итоге: 
gzip: stdin: not in gzip format
  0 77.9M    0  281k    0     0   545k      0  0:02:26 --:--:--  0:02:26  546k
curl: (23) Failure writing output to destination

**Comment by bol-van** [comment]
Это не ошибка, а github выключил поддержку gzip.
К сожалению, курлы на обрезанных девайсах часто идут без zlib , потому --compressed, определяющий сам encoding, использовать не выходит. Расчет был на то, что гитхаб точно поддерживает, но они непонятно почему внезапно отключили

**Comment by bol-van** [comment]
Поправлено
