### ISSUE TITLE
Вопрос по QUIC

### ISSUE THREAD

**Issue by disappointed72** [bol-van/zapret#194]
В базовом конфиге приведён пример для quic в nfqws как --dpi-desync=fake --dpi-desync-repeats=6

1. Число 6 повторений fake пакета указано как пример или это некое рабочее значение которое можно использовать?
2. Нужно ли для QUIC в режиме fake устанавливать --dpi-desync-ttl ?

**Comment by disappointed72** [comment]
По ttl вопрос снят. Изучил. Остался про --dpi-desync-repeats=6

**Comment by bol-van** [comment]
На моем провайдере иногда не срабатывало с 1 повторением
DPI ищут искомое в первых N пакетах. Опытным путем определил, что 5 достаточно. 6 - на всякий случай
