### ISSUE TITLE
Не помогает обходить ограничение скорост на googlevideo.com

### ISSUE THREAD

**Issue by userosos** [bol-van/zapret#199]
Приветствую.
После сканирования получаю:
* SUMMARY
ipv4 googlevideo.com curl_test_http : tpws --hostdot
ipv4 googlevideo.com curl_test_http : nfqws not working
ipv4 googlevideo.com curl_test_https_tls12 : tpws not working
ipv4 googlevideo.com curl_test_https_tls12 : nfqws not working

Выставляю необходимые параметры в конфиге, но скорость все-равно крайне низкая.
![изображение](https://github.com/user-attachments/assets/d03d14f2-d43a-46f9-abd1-067aeb3bb895)
Запускал даже глубокое сканирование - результаты не поменялись.

**Comment by userosos** [comment]
> Блокчек не проверяет на скорость ресурса. Проверяется тоько обход блокировок. Домен googlevideo.com не предназначен для прямого обращения (домен 2 уровня). Обращение идет только в поддоменам. На домене 2 уровня неверный сертификат, а plain http выдает редирект на другой гугл домен, что воспринимается блокчеком как редирект на заглушку
> 
> Блокчек в данном случае неприменим Правильная стратегия обхода замедления --dpi-desync=split2

Скорость стала повыше, но все равно что-то не то.
![изображение](https://github.com/user-attachments/assets/6434d956-e020-4be1-8182-f07e98e5307e)

**Comment by bol-van** [comment]
Еще надо делать --dpi-desync=fake на QUIC
Проверить надо по F12 какой протокол идет на googlevideo

**Comment by alexzzd** [comment]
Скиньте, пожалуйста, как должен выглядеть файл конфига

**Comment by userosos** [comment]
> Еще надо делать --dpi-desync=fake на QUIC
> Проверить надо по F12 какой протокол идет на googlevideo

![изображение](https://github.com/user-attachments/assets/fb4b80c6-3a6b-489a-88f7-bef97ab0035e)
Стало 70к скорость соединения, хотя иногда бывает просадка до 670.
![изображение](https://github.com/user-attachments/assets/0b6bd4cb-e34a-4d48-93cf-eff7828e40d2)

**Comment by AllenfrankX** [comment]
> Скиньте, пожалуйста, как должен выглядеть файл конфига
Читайте внимательно инструкцию пожалуйста перед тем спрашивать что либо, автору проекта надо работать а не отвечать всем на одну и туже вопросы одну и туже ответы. Скорость конечно не будет как прежде но будет стабильно чем раньше

**Comment by bol-van** [comment]
По F12 надо добавить поле "протокол". Правой кнопкой
по умолчанию его может не быть

**Comment by userosos** [comment]
> @userosos Скиньте, пожалуйста, как должен выглядеть файл конфига

У меня сейчас так выглядит

```
selected : nfqws

NFQWS_OPT_DESYNC="--dpi-desync=split2"
NFQWS_OPT_DESYNC_HTTP=""
NFQWS_OPT_DESYNC_HTTPS="--dpi-desync=fake --dpi-desync-fooling=datanoack"
NFQWS_OPT_DESYNC_HTTP6=""
NFQWS_OPT_DESYNC_HTTPS6=""
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=split2 --dpi-desync=fake"
NFQWS_OPT_DESYNC_QUIC6=""
```

**Comment by bol-van** [comment]
Да, там смесь quic и tls.
Вообщем тут для всех, чтобы одно и то же не мусолить, написал FAQ
https://github.com/bol-van/zapret/discussions/200

**Comment by RomzesRover** [comment]
Работает если отключить quic. 
К сожалению в офф клиентах (приложениях) отключить нельзя это так просто, как в браузере. 
Пытаюсь вырубить в роутере. Я не очень шарю, как это сделать, по вашему FAQ увидел, что нужно заблокировать порт udp 443.
Создал следующий скрипт 
`#!/opt/bin/sh
[ "$type" == "ip6tables" ] && exit 0
[ "$table" != "mangle" ] && exit 0   # check the table name
iptables -A INPUT -p udp -m state --state NEW -m udp --dport 443 -j DROP
iptables -A OUTPUT -p udp -m state --state NEW -m udp --dport 443 -j DROP`

**iptables -L -v -n** выдаёт следующее, после перезагрузки 
[iptables response.txt](https://github.com/user-attachments/files/16466623/iptables.response.txt)

Но в приложениях, и в браузере (если поставить quic в default), всё-равно остаётся рабочим quic, замедление в действии. 
По приложениям скачал, revanced, там можно отключить quic. Но для iphone или android tv нет такого.
Подскажите как правильно выключить 443 (quic) на самом роутере через iptables.

**Comment by bol-van** [comment]
1. --state NEW здесь не нужно
2. OUTPUT касается только запросов с самого роутера и не касается проходящего (с клиентов) трафик
3. У вас плодятся дубли правил
надо проверять есть ли правило, и только тогда добавлять
Можно использовать такую функцию
```
ipta()
{
	iptables -C "$@" >/dev/null 2>/dev/null || iptables -A "$@"
}
```
Например так : ipta FORWARD -p udp --dport 443 -j DROP

**Comment by bol-van** [comment]
Судя по счетчиком по правила drop дело не доходит. Раньше в цепочках выполняется ACCEPT, что является финальным таргетом.

Надо -I делать вместо -A
```
ipt()
{
iptables -C "$@" >/dev/null 2>/dev/null || iptables -I "$@"
}
ipt FORWARD -p udp --dport 443 -j DROP```
.........

**Comment by RomzesRover** [comment]
Отлично, всё получилось на этот раз! Счетчики тикают.
_Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  824 1007K DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:443_
  
 На всех устройствах, даже с официальным клиентом, всё работает.

**Comment by Baydana** [comment]
Если кому поможет, но если заменить домен 3 уровня на ipv6  этого домена  то скачивание идёт.

**Comment by bol-van** [comment]
не у всез естб ипв6

**Comment by Seamas73** [comment]
Настроил на роутерах Keenetic Giga AX (KN-1011) и Viva (KN-1912). Тесты [отсюда](https://github.com/bol-van/zapret/issues/199), запущенные в консоли роутеров, показывают скорость в диапазоне от 43 до 50 Мбит/с. В браузерах на винде и андроиде (смартфон и тв-приставка на Android TV) интерфейс ютуба загружается мгновенно, ролики запускаются с задержкой в пределах 10-15 секунд, но проигрываются без тормозов и буферизации, в том числе в 2k (4k не искал для тестов), а также на скорости х2. Однако приложения-клиенты для ютуба (ATube для винды, оф.клиент на смартфоне и оф. и неоф. (SmartTube) клиенты для Android TV наотрез отказываются воспроизводить ролики с Ютуба: постоянная буферизация, а потом чёрный экран. Хотя, насчёт смартфона я поспешил - он проигрывает ролики, но с более чем 30 секундной задержкой.

**Comment by fnceba** [comment]
> --dpi-desync=split2

Привет!
А можем добавить эту инфу в какой-нибудь файл со справкой, типа "обход блокировки youtube на ubuntu"? У меня эта стратегия сработала. Наверное, заодно сказать условия, при которых эта стратегия должна будет работать.

А в целом -- очень полезна была бы инструкция отдельно для конкретных ресурсов, в данный момент для youtube. Потому что я не понял, как правильно искать подходящую стратегию для googlevideo.com.
