### ISSUE TITLE
Trojan:Win32/Mirai!ml

### ISSUE THREAD

**Issue by starcom89** [bol-van/zapret#201]
Скачал zip архив. 
При проверке архива антивирус обнаружил Trojan:Win32/Mirai!ml.
Только у меня так?

**Comment by bol-van** [comment]
На какие файлы ругается ?
Если на binaries, то они упакованы upx. И у некоторых AV сносит крышу у их искусственного интеллекта

**Comment by starcom89** [comment]
![image](https://github.com/user-attachments/assets/806ea370-28de-4281-bb22-daf83d534dc9)
Если так, то все ок?
