### ISSUE TITLE
Zapret ломает PBR и замедляет скорость всего

### ISSUE THREAD

**Issue by Spp595** [bol-van/zapret#203]
При установке zapret на устройстве с openwrt на котором уже настроен PBR (Policy based routing), ломается как pbr так и вся сеть в целом)
Скорость подключения к сайтам очень медленная да и будто бы сам zapret тоже не работает
Даже после удаления его при помощи sh скрипта проблема не устраняется, как понимаю может только hard reset)

**Comment by bol-van** [comment]
Если уж вы смогли настроить PBR, то думаю разберетесь в чем проблема

**Comment by Spp595** [comment]
Уже настроил, немного в конфигах тупанул)

**Comment by eldash666** [comment]
> Уже настроил, немного в конфигах тупанул)

Что мне делать, как скорость интернета вернуть, я  не разбираюсь. Zapret просто скачал от flowseal. Потом у меня инет стал замедляться. Что надо сделать чтобы вернуть? Винду аж переустановил.
Сбросил до заводских настроек роутер, не помогло

**Comment by eldash666** [comment]
> > Уже настроил, немного в конфигах тупанул)
> 
> Что мне делать, как скорость интернета вернуть, я не разбираюсь. Zapret просто скачал от flowseal. Потом у меня инет стал замедляться. Что надо сделать чтобы вернуть? Винду аж переустановил. Снова запрет не скачивал. Сбросил до заводских настроек роутер, не помогло. Итнернет какой то мега медденный через wifi. А если кабель подключить, норм становится
