### ISSUE TITLE
Не работает(?)

### ISSUE THREAD

**Issue by DADA30000** [bol-van/zapret#204]
Я прописываю sudo zapret start, и... ничего не происходит? Как понять что утилита уже запущена?
Я использую NixOS

**Comment by DADA30000** [comment]
А и утилита мне нужна просто для обхода замедления Youtube

**Comment by bol-van** [comment]
Этот вопрос не касается zapret, и тут не курсы обучения Linux
читайте документацию и гуглите как работать со службами в вашей ОС

**Comment by Nishimara** [comment]
@DADA30000 Запрет был опакечен в прошлом месяце, и сейчас висит пулл реквест на сервис. Пока он не мержнут, можно воспользоваться следующей конфигурацией

```nix
users.users.tpws = {
  isSystemUser = true;
  group = "tpws";
};

users.groups.tpws = {};

systemd.services.zapret = {
  after = [ "network-online.target" ];
  wants = [ "network-online.target" ];
  wantedBy = [ "multi-user.target" ];
  
  path = with pkgs; [
    iptables
    nftables
    gawk
  ];
  
  serviceConfig = {
    Type = "forking";
    Restart = "no";
    TimeoutSec = "30sec";
    IgnoreSIGPIPE = "no";
    KillMode = "none";
    GuessMainPID = "no";
    ExecStart = "${pkgs.zapret}/bin/zapret start";
    ExecStop = "${pkgs.zapret}/bin/zapret stop";
    
    EnvironmentFile = pkgs.writeText "zapret-environment" ''
      MODE="tpws"
      # и прочая конфигурация которую можно получить с помощью nix-shell -p zapret --run blockcheck
    '';
  };
};
```

**Comment by RendeR66** [comment]
> @DADA30000 Запрет был опакечен в прошлом месяце, и сейчас висит пулл реквест на сервис. Пока он не мержнут, можно воспользоваться следующей конфигурацией
> 
> ```nix
> users.users.tpws = {
>   isSystemUser = true;
>   group = "tpws";
> };
> 
> users.groups.tpws = {};
> 
> systemd.services.zapret = {
>   after = [ "network-online.target" ];
>   wants = [ "network-online.target" ];
>   wantedBy = [ "multi-user.target" ];
>   
>   path = with pkgs; [
>     iptables
>     nftables
>     gawk
>   ];
>   
>   serviceConfig = {
>     Type = "forking";
>     Restart = "no";
>     TimeoutSec = "30sec";
>     IgnoreSIGPIPE = "no";
>     KillMode = "none";
>     GuessMainPID = "no";
>     ExecStart = "${pkgs.zapret}/bin/zapret start";
>     ExecStop = "${pkgs.zapret}/bin/zapret stop";
>     
>     EnvironmentFile = pkgs.writeText "zapret-environment" ''
>       MODE="tpws"
>       # и прочая конфигурация которую можно получить с помощью nix-shell -p zapret --run blockcheck
>     '';
>   };
> };
> ```

а что за файл где это надо поменять?

**Comment by DADA30000** [comment]
> > @DADA30000 Запрет был опакечен в прошлом месяце, и сейчас висит пулл реквест на сервис. Пока он не мержнут, можно воспользоваться следующей конфигурацией
> > ```nix
> > users.users.tpws = {
> >   isSystemUser = true;
> >   group = "tpws";
> > };
> > 
> > users.groups.tpws = {};
> > 
> > systemd.services.zapret = {
> >   after = [ "network-online.target" ];
> >   wants = [ "network-online.target" ];
> >   wantedBy = [ "multi-user.target" ];
> >   
> >   path = with pkgs; [
> >     iptables
> >     nftables
> >     gawk
> >   ];
> >   
> >   serviceConfig = {
> >     Type = "forking";
> >     Restart = "no";
> >     TimeoutSec = "30sec";
> >     IgnoreSIGPIPE = "no";
> >     KillMode = "none";
> >     GuessMainPID = "no";
> >     ExecStart = "${pkgs.zapret}/bin/zapret start";
> >     ExecStop = "${pkgs.zapret}/bin/zapret stop";
> >     
> >     EnvironmentFile = pkgs.writeText "zapret-environment" ''
> >       MODE="tpws"
> >       # и прочая конфигурация которую можно получить с помощью nix-shell -p zapret --run blockcheck
> >     '';
> >   };
> > };
> > ```
> 
> а что за файл где это надо поменять?

это только для NixOS (Дистрибутив линукса основанный на пакетном менеджере Nix)

**Comment by RendeR66** [comment]
> > > @DADA30000 Запрет был опакечен в прошлом месяце, и сейчас висит пулл реквест на сервис. Пока он не мержнут, можно воспользоваться следующей конфигурацией
> > > ```nix
> > > users.users.tpws = {
> > >   isSystemUser = true;
> > >   group = "tpws";
> > > };
> > > 
> > > users.groups.tpws = {};
> > > 
> > > systemd.services.zapret = {
> > >   after = [ "network-online.target" ];
> > >   wants = [ "network-online.target" ];
> > >   wantedBy = [ "multi-user.target" ];
> > >   
> > >   path = with pkgs; [
> > >     iptables
> > >     nftables
> > >     gawk
> > >   ];
> > >   
> > >   serviceConfig = {
> > >     Type = "forking";
> > >     Restart = "no";
> > >     TimeoutSec = "30sec";
> > >     IgnoreSIGPIPE = "no";
> > >     KillMode = "none";
> > >     GuessMainPID = "no";
> > >     ExecStart = "${pkgs.zapret}/bin/zapret start";
> > >     ExecStop = "${pkgs.zapret}/bin/zapret stop";
> > >     
> > >     EnvironmentFile = pkgs.writeText "zapret-environment" ''
> > >       MODE="tpws"
> > >       # и прочая конфигурация которую можно получить с помощью nix-shell -p zapret --run blockcheck
> > >     '';
> > >   };
> > > };
> > > ```
> > 
> > 
> > а что за файл где это надо поменять?
> 
> это только для NixOS (Дистрибутив линукса основанный на пакетном менеджере Nix)

а для arch есть решение? я не знаю почему у меня ютуб перестал работать

**Comment by DADA30000** [comment]
> > > > @DADA30000 Запрет был опакечен в прошлом месяце, и сейчас висит пулл реквест на сервис. Пока он не мержнут, можно воспользоваться следующей конфигурацией
> > > > ```nix
> > > > users.users.tpws = {
> > > >   isSystemUser = true;
> > > >   group = "tpws";
> > > > };
> > > > 
> > > > users.groups.tpws = {};
> > > > 
> > > > systemd.services.zapret = {
> > > >   after = [ "network-online.target" ];
> > > >   wants = [ "network-online.target" ];
> > > >   wantedBy = [ "multi-user.target" ];
> > > >   
> > > >   path = with pkgs; [
> > > >     iptables
> > > >     nftables
> > > >     gawk
> > > >   ];
> > > >   
> > > >   serviceConfig = {
> > > >     Type = "forking";
> > > >     Restart = "no";
> > > >     TimeoutSec = "30sec";
> > > >     IgnoreSIGPIPE = "no";
> > > >     KillMode = "none";
> > > >     GuessMainPID = "no";
> > > >     ExecStart = "${pkgs.zapret}/bin/zapret start";
> > > >     ExecStop = "${pkgs.zapret}/bin/zapret stop";
> > > >     
> > > >     EnvironmentFile = pkgs.writeText "zapret-environment" ''
> > > >       MODE="tpws"
> > > >       # и прочая конфигурация которую можно получить с помощью nix-shell -p zapret --run blockcheck
> > > >     '';
> > > >   };
> > > > };
> > > > ```
> > > 
> > > 
> > > а что за файл где это надо поменять?
> > 
> > это только для NixOS (Дистрибутив линукса основанный на пакетном менеджере Nix)
> 
> а для arch есть решение? я не знаю почему у меня ютуб перестал работать

Есть другие issue закрытые и открытые где уже написали возможные решения
