### ISSUE TITLE
Флаги для оператора мтс

### ISSUE THREAD

**Issue by electrifying** [bol-van/zapret#206]
Хотелось бы узнать, кто уже ставил zapret с оператором мтс/мгтс какие флаги вы указывали для работы заблокированных сайтов типо rutracker.org,rutor и прочего? Спасибо за ответ.

**Comment by almirus** [comment]
мск, работают эти параметры https://github.com/bol-van/zapret/discussions/200

**Comment by electrifying** [comment]
> мск, работают эти параметры #200

Там параметры указаны только для ютуба, а я за остальные ресурсы спрашиваю

**Comment by Alluseri** [comment]
`-5` в GoodbyeDPI на МТС работает исправно, ему, вроде как, здесь соответствует `disorder` либо `disorder2`(если прописывать кастом фраг без фейков).

**Comment by bol-van** [comment]
народ, идите в дискуссии или на форумы
здесь только проблемы в самом запрете

**Comment by electrifying** [comment]
> народ, идите в дискуссии или на форумы здесь только проблемы в самом запрете

На какие форумы? Нигде zapret особо не обсуждается.Я не понимаю почему вы как автор все тикеты закрываете без какой-либо помощи, ладно бы если что-то не по делу спрашивали но все же в рамках проекта.Создайте тогда тут отдельный топик для обсуждений в данный момент его нету.

**Comment by bol-van** [comment]
zapret это средство борьбы с дпи а не таблетка
это инструмент. я не могу бегать за каждым покупателем перфоратора и разбирать с ним какие сверла подходят для его стены
тут есть дискуссии. создайте топ если хотите помощи зала
