### ISSUE TITLE
Drop UDP-connection  on stop service

### ISSUE THREAD

**Issue by aglu** [bol-van/zapret#207]
Можно ли добавить в контиг параметр закрытия UDP-соединений при остановке сервиса.
Очень долго подбирал параметры обходы по QUIC, но ничего не помогало, пока не догадался рвать соединения.
Ну, или в README прописать.
PS. Использую Ubuntu 24.04 LTS

**Comment by bol-van** [comment]
nfqws ничего не может останавливать
он обрабатывает лишь отдельные пакеты
в удп вообще нет соединений как таковых

**Comment by aglu** [comment]
Ok. Будет более точное определение проблемы и решение - переоткрою
