### ISSUE TITLE
Need help with compiling iOS binary of tpws

### ISSUE THREAD

**Issue by Leeksov** [bol-van/zapret#212]
Уже пару дней пытаюсь скомпилировать tpws для iOS наткнулся на osxcross.
 Но у меня не особо получается написать Makefile, чтоб собрать часть проекта
 
 I've been trying to compile tpws for iOS for a couple of days now and came across osxcross. 
 But I can't really write a Makefile to compile part of the project

**Comment by Leeksov** [comment]
Ура, теперь я дошёл до этапа компиляции и теперь получил уже такую ошибку

Как я понял из информации из сети, в macOS & iOS не используется epoll, а используется kqueue, предположу, что если я даже и перепишу это, то получу ещё больше ошибок

> macOS & iOS не используется epoll
Но.. почему тогда бинарный файл спокойно собирается для macOS?

**Comment by bol-van** [comment]
для бсд используется еполл-шим
я не в курсе насколько он совместим с иос
я не яблочник так что сами изучайте

**Comment by dx4321** [comment]
Получилась разобраться?

> Ура, теперь я дошёл до этапа компиляции и теперь получил уже такую ошибку <img alt="image" width="697" src="https://private-user-images.githubusercontent.com/78694696/354858065-2fb351fe-bbe4-42a5-ab45-b071929ec6cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDc5MTIsIm5iZiI6MTczNDU0NzYxMiwicGF0aCI6Ii83ODY5NDY5Ni8zNTQ4NTgwNjUtMmZiMzUxZmUtYmJlNC00MmE1LWFiNDUtYjA3MTkyOWVjNmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE4NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTc2MTAyMThkOTk0ODFlNzdlZjIwMjYwMDlmOWE4Y2QzZDg3OGJiMmM0N2ExMTc0YjhiMDc0NDBjNDZiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NVYnCjPZQgzC8ESYkckf7xfXDS-iZqi5l4GX0FgQADs">
> 
> Как я понял из информации из сети, в macOS & iOS не используется epoll, а используется kqueue, предположу, что если я даже и перепишу это, то получу ещё больше ошибок
> 
> > В macOS & iOS не используется epoll
> 
> Но.. почему тогда бинарный файл спокойно собирается для macOS?
