### ISSUE TITLE
NFQUEUE iptables or ip6tables target is missing (Keenetic Ultra + OPKG Entware 1.36.1)

### ISSUE THREAD

**Issue by zhuk83** [bol-van/zapret#215]
Привет!
ставлю запрос на сабж, при запуске проверки имеем ошибку. Куда копнуть?
`BusyBox v1.36.1 (2024-03-19 14:07:09 UTC) built-in shell (ash)

~ # cd /opt/tmp/zapret/
/opt/tmp/zapret # ./blockcheck.sh
* checking system
Linux detected
firewall type is iptables
* checking privileges
* checking prerequisites
NFQUEUE iptables or ip6tables target is missing. pls install modules.
`

**Comment by bol-van** [comment]
это не проблема запрета
кинетик официально не поддерживается
вопросы по нему только в дискуссиях
у вас не установлены модули ядра

**Comment by danbka33** [comment]
Установить протокол ipv6 в компонентах кинетика, после этого появляется пакет с netfilter в opkg. Почему кинетики так сделали непонятно, тоже долго боролся с этим...

**Comment by vasilky3** [comment]
> Установить протокол ipv6 в компонентах кинетика, после этого появляется пакет с netfilter в opkg. Почему кинетики так сделали непонятно, тоже долго боролся с этим...

Спасибо за подсказку, подскажи еще один момент. 
Что-то не пойму как после установки netfilter в админке, установить ip6tables?

**Comment by danbka33** [comment]
@vasilky3 
Тут больше ругается на NFQUEUE iptables, необходимо отключить аппаратное ускорение.
<img width="567" alt="image" src="https://github.com/user-attachments/assets/de22ebd2-7da0-42a8-aac1-25ad68452d72">
Активировать в настройках компонент
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/a6ef4245-eb99-4ee5-af5c-4aa6d1937a0f">
После этого появится netfilter, где включен модуль NFQUEUE

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/8d700ce1-7b6f-4caa-a4c7-d5550a9684b7">

**Comment by vasilky3** [comment]
@danbka33, спасибо за информацию.

Отключать HW акселерацию (замедлять работы сети?), для обхода  DPI что-то не хочется :_(

Вчера настроил используя этот гайд 
 https://habr.com/ru/articles/834826/
Полет нормальный. Как-то без отключения HW справляется.
Похоже это помогает:

> Добавляем в функцию do_start() код загрузки модулей ядра linux (xt_multiport.ko, xt_connbytes.ko, xt_NFQUEUE.ko), так как они по умолчанию не загружаются, а без них iptables будет выдавать ошибки при попытке применить необходимые правила.

**Comment by ValentinoRossi007** [comment]
<img width="639" height="198" alt="Image" src="https://github.com/user-attachments/assets/ed23887a-15be-407a-b183-4ff0138ad973" />
У меня не хочет стартовать, хотя модули все установлены. Роутер smartbox flash keenetic 4.3.2

**Comment by danbka33** [comment]
Мало установить, нужно активировать его в ядре.
[Смотри эту статью](https://habr.com/ru/articles/834826/), здесь 9 пункт как раз про это
