### ISSUE TITLE
Ubiquiti

### ISSUE THREAD

**Issue by Slona** [bol-van/zapret#216]
Добрый день, уважаемый автор. А будут решения для Ubiquiti роутеров? В частности ERX. Видел папочку mips32r1-lsb, но она уже не обновлялась 2 года, да и readme нет (
Буду очень благодарен.

**Comment by bol-van** [comment]
бинарики обновляются, вы ошибаетесь
простых готовых прикруток к разным стокам нет и не будет
вы сами будете воевать с производителем

**Comment by Slona** [comment]
Понял, сами так сами. Все равно спасибо!
