### ISSUE TITLE
Заставить работать и обход блокировок и обход замедления на Youtube вместе

### ISSUE THREAD

**Issue by DADA30000** [bol-van/zapret#221]
С такими аргументами убирается замедление на youtube, но на заблокированные сайты не получается зайти: --dpi-desync=split2
С такими всё наоборот, получается зайти на заблокированные сайты, но на Youtube перестают абсолютно грузиться видео, просто бесконечная загрузка видео: --dpi-desync=fake --dpi-desync-ttl=9 --dpi-desync-fooling=md5sig либо --dpi-desync=fake --dpi-desync-ttl=9
Можно ли сделать так, что бы работали сразу и обход замедления, и обход блокировок?

**Comment by DADA30000** [comment]
QUIC в браузере отключён
Браузер Firefox

**Comment by NMi-ru** [comment]
+ дополнительный вопрос: можно ли иметь wildcard в файле zapret-hosts-user.txt?
Если поставить туда конкретное имя типа rr1---sn-4g5edndz.googlevideo.com — всё работает, замедления нет.

**Comment by bol-van** [comment]
--dpi-desync=fake,split2    остальное оставить

вайлдкарды не нужны
субдомены автоматом учитываются

**Comment by exicc** [comment]
На ПК при отключённых QUIC и Kyber всё работает прекрасно, на андроиде же, на WiFi сети с zapret'ом в entware, в стоковом/рутованном клиенте YouTube жуткие тормоза. Можно ли как-то заставить zapret работать и для телефонов-клиентов?

**Comment by DADA30000** [comment]
> --dpi-desync=fake,split2 остальное оставить
> 
> вайлдкарды не нужны субдомены автоматом учитываются

да, работает, спасибо огромное!
