### ISSUE TITLE
Обход блокировки IP

### ISSUE THREAD

**Issue by asgardxf** [bol-van/zapret#222]
Пока не смог запустить у себя скрипт проверки, но есть смысл этим заниматься, если адреса не пингуются? идёт 100% потеря данных, например для адреса bbc.com - 151.101.0.81. Если смысла нет пытаться что-то сделать, возможно нужно в скрипт установки добавить проверку такого рода. Могу реквест сделать, если идея хорошая

**Comment by asgardxf** [comment]
почитал другие issue, понял что наверное не сюда вопрос

**Comment by bol-van** [comment]
в блокчеке есть проверка на конект порта и частичный ип блок
проверка порта требует неткат. в опенврт нет по умолчанию

полные ип блоки обходятся когда порт не конектит  только через сторонний хост
в запрете есть для этого система   ipban
для настройки полиси роутинга
но это непросто и все равно нужен впн или прокси

**Comment by micle7** [comment]
Получается если сайт внесен в zapret-ip-ipban.txt , тот же инстаграм, то просто так это не обойти?
