### ISSUE TITLE
Перестал работать VPN Split Tunneling

### ISSUE THREAD

**Issue by thenicholas** [bol-van/zapret#225]
Роутер с OpenWRT. У меня установлен пакет pbr, добавлен интерфейс Wireguard. Согласно правилам pbr траффик на определенные в списке домены идет через интерфейс Wireguard, остальной траффик - напрямую через Wan. После установки zapret ютуб престал тормозить и открываются заблокированные сайты, но теперь весь траффик идет через Wan. Как мне сделать так, чтобы как и прежде, трафик подпадающий под правила pbr шел через интерфейс Wireguard?

**Comment by bol-van** [comment]
я не изучал этот пакет, так что точно сказать не могу
могу предположить, что его настройки не работают на трафике, исходящем с самого роутера
можете курлом это проверить?
