### ISSUE TITLE
Написал мануал для Arch Linux и ТТК и нужна помощь!

### ISSUE THREAD

**Issue by sxiii** [bol-van/zapret#23]
У ТТК согласно софту "blockcheck" заблокировано всё, кроме двух вариантов:
* перенос строки перед GET
* перенос строки в заголовках в UNIX-стиле

Я не знаю, как адаптировать данные скрипты под эти два варианта обхода, однако я добился некоторых успехов в портировании процесса установки в ArchLinux (Manjaro).

Вот мой мануал:

sudo pacman -S libnetfilter_queue ipset curl lsb-release
git clone https://github.com/bol-van/zapret
sudo cp -r zapret/ /opt
sudo chmod -R 777 /opt/zapret
cd /opt/zapret/nfq
make
cd /opt/zapret/tpws
make
sudo cp /opt/zapret/init.d/debian7/zapret /etc/init.d/

#### Откроем скрипт текстовым редактором и исправим 2 переменные под нас:

sudo mousepad /etc/init.d/zapret

#### Теперь необходимо создать systemd unit для работы демона zapret, откроем файл SYSTEM.D unit: /etc/systemd/system/zapret.service и напишем в него:
```
Description=Zapret
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=simple
WorkingDirectory=/opt/zapret
ExecStart=/etc/init.d/zapret start
ExecStop=/etc/init.d/zapret stop
Restart=on-failure
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
```
#### В ArchLinux / Manjaro нету проги "start-stop-daemon", ставим из AUR:

yaourt -A start-stop-daemon

sudo systemctl enable zapret
sudo systemctl start zapret
sudo systemctl status zapret

В результате всех вышеописанных действий, systemd запускает демон, он успешно выполняет нужные скрипты, а затем повисает в "inactive/dead" состоянии (в случае с mns / rt точно):
```
● zapret.service
   Loaded: loaded (/etc/systemd/system/zapret.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2018-11-27 20:30:04 MSK; 306ms ago
  Process: 31505 ExecStop=/etc/init.d/zapret stop (code=exited, status=0/SUCCESS)
  Process: 31478 ExecStart=/etc/init.d/zapret start (code=exited, status=0/SUCCESS)
 Main PID: 31478 (code=exited, status=0/SUCCESS)

ноя 27 20:30:00 sx-pc systemd[1]: Started zapret.service.
ноя 27 20:30:00 sx-pc zapret[31478]: Creating ipset
ноя 27 20:30:00 sx-pc zapret[31478]: Adding to ipset zapret (hash:net) : /opt/zapret/ipset/zapret-ip.txt
ноя 27 20:30:04 sx-pc zapret[31478]: Adding to ipset zapret (hash:net) : /opt/zapret/ipset/zapret-ip-user.txt
ноя 27 20:30:04 sx-pc zapret[31478]: Adding to ipset ipban (hash:net) : /opt/zapret/ipset/zapret-ip-user-ipban.txt
ноя 27 20:30:04 sx-pc zapret[31478]: Adding iptables rule
ноя 27 20:30:04 sx-pc zapret[31478]: Starting anti-zapret: zapret.
ноя 27 20:30:04 sx-pc zapret[31505]: Deleting iptables rule
ноя 27 20:30:04 sx-pc zapret[31505]: Stopping anti-zapret: zapret.
```

Если кто-то сможет помочь (@bol-van ? @ValdikSS ?) с редактированием скрипта под перенос строки перед GET или перенос строки в заголовках в UNIX-стиле, буду очень признателен.

**Comment by ValdikSS** [comment]
Перенос строки перед GET или перенос заголовков в UNIX-стиле сломает большинство HTTP-сайтов, поэтому они не реализованы в zapret.

**Comment by bol-van** [comment]
"--unixeol" реализован. Но как сказал valdik, не все сервера поддерживают.
Правда, если они все равно заблокированы, то лучше пусть работает часть , чем ничего.
Я бы в таких условиях плюнул на dpi и сделал прозрачное проксирование

**Comment by sxiii** [comment]
Ого, спасибо за быструю реакцию, друзья. Я нашёл кроме --unixeol ещё и --methodeol. @bol-van прозрачное проксирование через TPWS или в смысле просто так, через внешний прокси? Я вот через TPWS пытаюсь, демон вроде бы поднимается (ещё после того как установил yaourt -A adduser-deb чтобы пользователей добавлять), но потом сразу после выполнения скриптов останавливается. Буду разбираться дальше.

**Comment by bol-van** [comment]
В смысле через внешний прокси. Tpws не делает никакой другой магии, которой не было бы в блокчек и других дурилках. Это лишь решение для прозрачного применения техники под linux .
Если это работает плохо, то проще отказаться и сделать проксирование

**Comment by MakaiHanta** [comment]
```
sudo git clone https://github.com/bol-van/zapret             128 ✘ 
Клонирование в «zapret»...
remote: Enumerating objects: 8906, done.
remote: Counting objects: 100% (499/499), done.
remote: Compressing objects: 100% (317/317), done.
remote: Total 8906 (delta 219), reused 394 (delta 182), pack-reused 8407 (from 1)
Получение объектов: 100% (8906/8906), 112.97 МиБ | 10.00 МиБ/с, готово.
Определение изменений: 100% (4903/4903), готово.
    ~  sudo cp -r zapret/ /opt                                  ✔  12s  
    ~  sudo chmod -R 777 /opt/zapret                                    ✔ 
    ~  cd /opt/zapret/nfq                                               ✔ 
    /opt/zapret/nfq    master !217  make                             ✔ 
cc -s -std=gnu99 -O3 -o nfqws *.c crypto/*.c  -lnetfilter_queue -lnfnetlink -lz
    /opt/zapret/nfq    master !217  cd /opt/zapret/tpws              ✔ 
    /opt/zapret/tpws    master !217  make                            ✔ 
cc -s -std=gnu99 -O3 -o tpws *.c  -lz -lpthread
    /opt/zapret/tpws    master !217  sudo cp /opt/zapret/init.d/debian7/zapret /etc/init.d/
cp: не удалось выполнить stat для '/opt/zapret/init.d/debian7/zapret': Нет такого файла или каталога
```

И действительно, папки /opt/zapret/init.d/debian7 нет.

ОС - manjaro

**Comment by bol-van** [comment]
Этому уже 6 лет, все поменялось !

**Comment by MakaiHanta** [comment]
> Этому уже 6 лет, все поменялось !

Прекрасно, а как теперь ставить? У меня ошибка на ошибке. Официальный установщик вообще жалуется на отсутствие пакета ip6tables, которого не существует. Более того, скрипт вообще утверждает, что у меня не установлен фаерволл iptables, хотя он стоит

**Comment by Goosegit11** [comment]
что за start-stop-daemon? если есть systemd, то команды systemctl должны работать

**Comment by bol-van** [comment]
Система запуска zapret очень сложна, и для нее написаны скрипты в init.d/sysv.
systemd по отношению к ним является вторичным. юнит представляет собой лишь адаптер под шелл скрипт
