### ISSUE TITLE
rockstar socialclub & gta online not works

### ISSUE THREAD

**Issue by DIvan2K** [bol-van/zapret#230]
> root@OpenWrt:~# cat /opt/zapret/ipset/zapret-hosts-user-exclude.txt.default 
> 10.0.0.0/8
> 172.16.0.0/12
> 192.168.0.0/16
> 169.254.0.0/16
> fc00::/7
> fe80::/10
> socialclub.rockstargames.com
> s.rsg.sc
> scapi.rockstargames.com
> prod.cloud.rockstargames.com
> media-rockstargames-com.akamaized.net

Есть ли способ узнать, какие ещё адреса используются игрой? (Запускаю из под linux arch 6.10.3 proton, есть возможность запустить из под Windows 10)

**Comment by bol-van** [comment]
с некоторых пор из репы убраны изменяемые файлы
вписывать что-то в .default не сработает
инсталятор копирует .default если не находит рабочий файл
его и надо изменять

насчет игры брать шарк и смотреть куда лезет
от днс до разбора протокола
если там тлс то смотреть  sni
