### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by zhenyolka** [bol-van/zapret#24]
Как такую штуку можно под андроид переделать? У меня при командах к iptables требует модуль ядра xt_set. Что тут можно придумать? Отдельно модуль собрать, или что-то всё-таки по проще(с iptables).

**Comment by bol-van** [comment]
Модуль ядра будет собрать очень тяжко скорее всего.
Особенно под заводское ядро.

Так что вариант только отказываться от ipset.
Можно использовать tpws со списком доменов (анализ хедера Host: и пробив по списку)

**Comment by islamdjamalov** [comment]
есть ли возможность скомпилировать nfqws под arm64 (armv8)? дело в том, что я обнаружил что в кастомных ядрах все нужные модули включены, мне не хватает только бинарников nfqws. тоже пытаюсь прикрутить эту штуку под анроид...

**Comment by islamdjamalov** [comment]
не понимаю почему в прошлый раз бинарник не запускался, сейчас пробовал запустить чтобы скопировать логи, а бинарник запустился как ни в чем не бывало :) пойду писать скриптик для автозапуска. спасибо вам за ваши труды!
