### ISSUE TITLE
Нет подключения к YouTube

### ISSUE THREAD

**Issue by NSbasyon** [bol-van/zapret#242]
8 и 9 числа на юге РФ площадка Ютюб не работает совсем. Сайт прогружается, но видео совсем не воспроизводится. Пытался запустить на линукс Минт - Запрет. Не получается настроить. Но что интересного заметил, пока идет тест blockcheck.sh - Ютюб работает! Как только тест завершиться, снова Ютруп. Может пригодится это замечание Вам для работы.

**Comment by bol-van** [comment]
мне пригодится лог блокчека
что в нем ? есть блок ? и на какой домен тест ?

**Comment by Kashemir001** [comment]
Были аналогичные симптомы, помогло переключение режима фильтрации с ipset на hostlist. Похоже, что у меня с ipset подключения к ютубу не попадают в список маскируемых, хотя домены прописаны в zapret-hosts-user.txt, get_user.sh прожимал. @NSbasyon а у вас какой режим фильтрации выставлен?

**Comment by bol-van** [comment]
ипсет не будет работать нормально с прыгающими ип
