### ISSUE TITLE
Работает только в браузере на хромиум

### ISSUE THREAD

**Issue by hy1lite** [bol-van/zapret#244]
У меня возникла проблема установил все идеально работает в хроме ,но не работает в firefox , в чем может быть проблема?

в firefox при использовании use system proxy settings на всех веб-страницах The proxy server is refusing An error occurred during a connection to Check the proxy settings to make sure that they are Contact your network administrator to make sure the proxy server is working.'

**Comment by bol-van** [comment]
у вас нет никакой конкретной информации
что не работает
как все настроено
в каких режимах
я не гадаю

**Comment by hy1lite** [comment]
в firefox не работает в network settings в режиме use system proxy settings появляеться ошибка The proxy server is refusing An error occurred during a connection to Check the proxy settings to make sure that they are Contact your network administrator to make sure the proxy server is working.' 

в дургих режимах нету смысла  так как они не будут использовать прокси системы

**Comment by bol-van** [comment]
вообще тут про проект zapret а не помощь в настройке броузеров
какой прокси ?  у запрета есть режим  tpws-socks
о нем идет речь?
у вас стоит какая-то настройка прокси, и там прокси нет
