### ISSUE TITLE
Слетают настройки после перезагрузки роутера.

### ISSUE THREAD

**Issue by dmistr** [bol-van/zapret#245]
Приветствую! Целью установки было заставить работать youtube на телевизорах LG. Сразу после установки ничего не изменилось, но после того как прописал вручную в /opt/zapret/ipset/zapret-hosts-user.txt все возможные блокируемые домены -всё заработало. Но вот незадача, на следующий день все настройки слетели и пришлось проделывать всё заново, возможна причина была в отключении питания, но тем не менее... 
Скажу честно, у меня знания linux на самом примитивном базовом уровне, так что если есть возможность напишите пошагово, как прописать всё в автозапуск или какие-либо другие способы решения проблемы. 
Роутер TP-Link Archer C2600, OpenWrt 23.05.2.
Заранее благодарен!

**Comment by bol-van** [comment]
пошагово это в дискуссии за помощью зала
у меня требования - знание линух хотя бы базовое

слетают настройки какие именно ?  в openwrt или в запрете ?
файл /opt/zapret/config или ipset/zapret-hosts-user.txt меняются, откатываются сами по себе на какое то старое состояние ?
места на диске сколько осталось ?

**Comment by dmistr** [comment]
/opt/zapret/config и zapret-hosts-user.txt - не изменяются, но приходится по новой переустанавливать сам скрипт каждый раз, иначе не работает.

**Comment by bol-van** [comment]
запуск идет через
/etc/init.d/zapret start
автозапуск через линк в /etc/rc.d
есть ли линк там ?
и работает ли старт как описано выше вместо заново install_easy ?

**Comment by dmistr** [comment]
линк в /etc/rc.d есть, 
после ребута не пропадает, как и сам /etc/init.d/zapret, 
все конфиги на месте, но вот ТВ стабильно перестает грузить.
Ручной запуск/перезапуск, как через консоль, так и из интерфейса роутера - ни к чему не ведут.
И снова помогает только переустановка.
Завтра буду копать дальше, но пока никаких мыслей нет

**Comment by bol-van** [comment]
тв это плохой тестер
курлом проверять надо есть ли замедление
а так же на роутере есть ли процессы tpws nfqws

с тв много кто писал о проблемах
но мне не на чем проверять

**Comment by dmistr** [comment]
Сегодня снова продолжил экспериментировать, т.к. youtube опять отвалился от SmartTV и на этот раз роутер не перезагружался! Грубо говоря вчера вечером, после очередной переустановки, всё летало, а вот утром - черный экран.
По вашему совету, курлом (пробовал и ранее) проверить так и не вышло - может висеть очень долго без каких либо  признаков жизни. Не исключаю свою тупость в этом вопросе, но увы пришлось отложить этот инструмент.
Не буду описывать всё разнообразие вариантов и способов запуска и редактирования конфига, но в итоге помогло включение IPv6, изменение параметра MODE_FILTER=autohostlist, подбор параметра NFQWS_OPT_DESYNC с помощью blockcheck.sh -  в итоге всё заработало с "--dpi-desync=disorder2 --dpi-desync-fooling=md5sig" даже после многократного ребута!
