### ISSUE TITLE
странное поведение с сайтом youtube.com

### ISSUE THREAD

**Issue by yudai-patronai** [bol-van/zapret#246]
Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
bash install_easy.sh сработал на ура, но выдал 2 ошибки :
`
* installing zapret-list-update timer
Failed to disable unit: Unit file zapret-list-update.timer does not exist.
Failed to stop zapret-list-update.timer: Unit zapret-list-update.timer not loaded.
Created symlink /etc/systemd/system/zapret-list-update.timer → /opt/zapret/init.d/systemd/zapret-list-update.timer.
Created symlink /etc/systemd/system/timers.target.wants/zapret-list-update.timer → /opt/zapret/init.d/systemd/zapret-list-update.timer.
* starting zapret service

press enter to continue
`

После этого во всех браузерах youtube.com работает весьма странно : сама заглавная страница с рекомендациями прогружается быстро и качественно, но при попытке запустить проигрыватель видео - проигрыватель виснет. при этом рекомендации справа продолжает показывать и в целом всю страницу тоже. Такое ощущение, что какой-то косяк с flash.

2 вопроса
1) нормально ли прошла установка, если выданы такие ошибки?
2) что с flash ?

**Comment by bol-van** [comment]
думаю эти ошибки можно игнорировать
вообще zapret это не однокнопочное решение
и может потребоваться испробовать разные стратегии, смотреть за трафиком
f12 в броузере, wireshark
как-то так

**Comment by pvrt** [comment]
> Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux bash install_easy.sh сработал на ура, но выдал 2 ошибки : `
> 
> * installing zapret-list-update timer
>   Failed to disable unit: Unit file zapret-list-update.timer does not exist.
>   Failed to stop zapret-list-update.timer: Unit zapret-list-update.timer not loaded.
>   Created symlink /etc/systemd/system/zapret-list-update.timer → /opt/zapret/init.d/systemd/zapret-list-update.timer.
>   Created symlink /etc/systemd/system/timers.target.wants/zapret-list-update.timer → /opt/zapret/init.d/systemd/zapret-list-update.timer.
> * starting zapret service
> 
> press enter to continue `
> 
> После этого во всех браузерах youtube.com работает весьма странно : сама заглавная страница с рекомендациями прогружается быстро и качественно, но при попытке запустить проигрыватель видео - проигрыватель виснет. при этом рекомендации справа продолжает показывать и в целом всю страницу тоже. Такое ощущение, что какой-то косяк с flash.
> 
> 2 вопроса
> 
> 1. нормально ли прошла установка, если выданы такие ошибки?
> 2. что с flash ?

Поддержка adobe flash закончилась в 20 году. Ютуб не работает на флеше

**Comment by Neural-network-N** [comment]
Привет всем. Такая же ситуация.
При чем 1ый раз все поставил по быстрой инструкции: сделал конфиг с nfqws, iptables, скрипт на проверку работал по дефолтному доменному имени (Рутрекер?). Фишка в том, что после настройки я смог открыть Ютуб, посмотрел одно видео и ушел довольный. Спустя время повторил попытку - видеопоток с разных ссылок не грузится, сам сайт youtube.com и поиск на нем работают.

Запустил проверку повторно, конкретно на googlevideo.com, результат:
```
curl_test_http3: nfqws strategy for ipv4 googlevideo.com not found

clearing nfqws redirection

* SUMMARY
ipv4 googlevideo.com curl_test_http : tpws --hostdot
ipv4 googlevideo.com curl_test_http : nfqws not working
ipv4 googlevideo.com curl_test_https_tls12 : tpws not working
ipv4 googlevideo.com curl_test_https_tls12 : nfqws not working
ipv4 googlevideo.com curl_test_http3 : nfqws not working
```
При проверке где-то еще мелькали ошибки, что был редирект на video.google.com при обращении googlevideo.com .

Выставил такие опции через скрипт автонастройки:
nftables
TPWS_OPT="--hostspell=HOST --split-http-req=method --split-pos=3 --oob --hostdot"

Сейчас youtube.com открывается, поиск работает, видеопоток не воспроизводит.
Get-запросы на домен вида https://rr14---sn-n8v7znsd.googlevideo.com/videoplayback?***" возвращаются с 403ей ошибкой.
Есть POST-запросы без кода ошибки, в колонке "Transferred" ошибка "NS_BINDING_ABORTED" и "CORS Failed".

@bol-van , в чем может быть проблема? Предоставлю дополнительную информацию, если необходимо.

**Comment by Neural-network-N** [comment]
Привет всем. Такая же ситуация.
При чем 1ый раз все поставил по быстрой инструкции: сделал конфиг с nfqws, iptables, скрипт на проверку работал по дефолтному доменному имени (Рутрекер?). Фишка в том, что после настройки я смог открыть Ютуб, посмотрел одно видео и ушел довольный. Спустя время повторил попытку - видеопоток с разных ссылок не грузится, сам сайт youtube.com и поиск на нем работают.

Запустил проверку повторно, конкретно на googlevideo.com, результат:
```
curl_test_http3: nfqws strategy for ipv4 googlevideo.com not found

clearing nfqws redirection

* SUMMARY
ipv4 googlevideo.com curl_test_http : tpws --hostdot
ipv4 googlevideo.com curl_test_http : nfqws not working
ipv4 googlevideo.com curl_test_https_tls12 : tpws not working
ipv4 googlevideo.com curl_test_https_tls12 : nfqws not working
ipv4 googlevideo.com curl_test_http3 : nfqws not working
```
При проверке где-то еще мелькали ошибки, что был редирект на video.google.com при обращении googlevideo.com .

Выставил такие опции через скрипт автонастройки:
nftables
TPWS_OPT="--hostspell=HOST --split-http-req=method --split-pos=3 --oob --hostdot"

Сейчас youtube.com открывается, поиск работает, видеопоток не воспроизводит.
Get-запросы на домен вида https://rr14---sn-n8v7znsd.googlevideo.com/videoplayback?***" возвращаются с 403ей ошибкой.
Есть POST-запросы без кода ошибки, в колонке "Transferred" ошибка "NS_BINDING_ABORTED" и "CORS Failed".

@bol-van , в чем может быть проблема? Предоставлю дополнительную информацию, если необходимо.

**Comment by bol-van** [comment]
сам googlevideo.com не предназначен для обращения
только субдомены
и блокчек не проверяет скорость

см дискуссии тема про тубе

**Comment by val7000** [comment]
> Привет всем. Такая же ситуация. У меня Ростелеком. При чем 1ый раз все поставил по быстрой инструкции: сделал конфиг с nfqws, iptables, скрипт на проверку работал по дефолтному доменному имени (Рутрекер?). Фишка в том, что после настройки я смог открыть Ютуб, посмотрел одно видео и ушел довольный. Спустя время повторил попытку - видеопоток с разных ссылок не грузится, сам сайт youtube.com и поиск на нем работают.
> 
> Запустил проверку повторно, конкретно на googlevideo.com, результат:
> 
> ```
> curl_test_http3: nfqws strategy for ipv4 googlevideo.com not found
> 
> clearing nfqws redirection
> 
> * SUMMARY
> ipv4 googlevideo.com curl_test_http : tpws --hostdot
> ipv4 googlevideo.com curl_test_http : nfqws not working
> ipv4 googlevideo.com curl_test_https_tls12 : tpws not working
> ipv4 googlevideo.com curl_test_https_tls12 : nfqws not working
> ipv4 googlevideo.com curl_test_http3 : nfqws not working
> ```
> 
> При проверке где-то еще мелькали ошибки, что был редирект на video.google.com при обращении googlevideo.com .
> 
> Выставил такие опции через скрипт автонастройки: nftables TPWS_OPT="--hostspell=HOST --split-http-req=method --split-pos=3 --oob --hostdot"
> 
> Сейчас youtube.com открывается, поиск работает, видеопоток не воспроизводит. Get-запросы на домен вида https://rr14---sn-n8v7znsd.googlevideo.com/videoplayback?***" возвращаются с 403ей ошибкой. Есть POST-запросы без кода ошибки, в колонке "Transferred" ошибка "NS_BINDING_ABORTED" и "CORS Failed".
> 
> @bol-van , в чем может быть проблема? Предоставлю дополнительную информацию, если необходимо.

Такая же проблема с "NS_BINDING_ABORTED". Открыавется всё, кроме googlevideo.com.

Получилось как-нибудь решить?

**Comment by Neural-network-N** [comment]
@bol-van 
Спасибо, не знал про дискуссии. И спасибо за эту сборку!

> Хреновую вы всем оказываете услугу. Вас все равно заставят это убрать. А РКН может сделать так, чтобы метод не работал. И обломаете и себя, и своих клиентов, и всех остальных.
> Я считаю, что человек каждый должен сам что-то сделать, если он хочет обойти цензуру. Коллективная ответственность здесь недопустима. Если что-то запрещают, то на это тоже есть причины, и некоторым НАДО через это проходить. Им надо чтобы им убирали порно, экстремизм и прочее, даже если внешне они не хотят, чтобы были запреты

Пробежался по комментариям и наткнулся на этот. А можно уточнить в чем заключается ваша позиция вкратце? Вы не даете готового решения, потому что не хотите облегчать работу тем, кто лазейки эти закрывает, или вы просто считаете что ничего легко даваться не должно, нужно каждому самому думать, читать, прикладывать усилия? Или какая-то еще у вас причина?

@val7000 
Да, получилось. Дискуссии читали?

**Comment by bol-van** [comment]
всего понемногу

во-первых, эта методика в принципе не может гарантировать результат
только техническая грамотность может его дать. a zapret - лишь инструмент, которому нужен мастер

во-вторых, попытки сделать все проще приведут к экспоненциальному росту необходимых усилий

в-третьих, если даже сделать чудо кнопку, государство будет вынуждено закрывать дыру
и методы у него есть разные. и это вопрос что будет для него дешевле : покупать еще вычислительные мощности тспу или устроить порку

ну и в 4-х, мне интереснее заставить кого-то чему-то научиться. 
нас реально отупляют этой удобной простотой из смартфона
человек должен приложить какие-то усилия.

**Comment by Neural-network-N** [comment]
@bol-van 
Спасибо за ответ. Позволю себе напомнить вам, что в мире пока еще существует множество прекрасных и полезных профессий вне информационных технологий. И эта удобная простота из смартфона нужна не для того, чтобы кого-то отупить, а чтобы дать возможность людям других профессий использовать сложные технические изобретения как интернет и компьютеры, не отвлекаясь от своей основной профессии (врача, учителя, ветеринара, музыканта, каменщика, водителя комбайна и др.). Пусть каждый прилагает усилия и совершенствуется в своем ремесле, не нужно всем погружаться в ИТ.
P.S.
Мы для них всего лишь ресурс для удержания власти, который они будут крутить как хотят и выжимать до последней капли. Поэтому надеяться можно только друг на друга. А в данной ситуации именно на инженеров, которые могут помочь людям других профессий не потерять доступ к полезным ресурсам.

**Comment by bol-van** [comment]
не стоит идеализировать
нет плохих и хороших, все размазано
правда и неправда перемешаны
у государства свои резоны, у меня свои
я лишь помогаю балансировать интересы сторон
есть практика. и она говорит, что если приложить титанические усилия для повышения доступности, они будут обнулены другой стороной
оригинальный пост был от прова, который сделал всем  dvtws
и я ему так ответил. что вас все равно заставят
нельзя просто так пойти сделать революцию, чтобы всем стало хорошо
потому каждый, кто берет в руку лопату, должен потрудиться и взять на себя ответственность за свой выбор. труд по изучению и настройке
 как плата за входной билет
ситуация будет меняться, технологии обхода тоже
няньки бегать следом не будут
потому учись, либо плати кому-то за помощь
не обязательно деньгами
хорошего врача найти большая проблема
если бы нашел, сам бы ему лично все настроил и обслуживал

**Comment by bol-van** [comment]
вообщем все, что я хочу сказать, что доступное для всех средство это утопия
как с технической, так и с практико-социальной стороны
в китае это тоже недоступно всем подряд
и требует знаний, ресурсов или чьей-то помощи
система иного не потерпит
там уже приходили к авторам v2ray

**Comment by val7000** [comment]
> @bol-van Спасибо, не знал про дискуссии. И спасибо за эту сборку!
> 
> > Хреновую вы всем оказываете услугу. Вас все равно заставят это убрать. А РКН может сделать так, чтобы метод не работал. И обломаете и себя, и своих клиентов, и всех остальных.
> > Я считаю, что человек каждый должен сам что-то сделать, если он хочет обойти цензуру. Коллективная ответственность здесь недопустима. Если что-то запрещают, то на это тоже есть причины, и некоторым НАДО через это проходить. Им надо чтобы им убирали порно, экстремизм и прочее, даже если внешне они не хотят, чтобы были запреты
> 
> Пробежался по комментариям и наткнулся на этот. А можно уточнить в чем заключается ваша позиция вкратце? Вы не даете готового решения, потому что не хотите облегчать работу тем, кто лазейки эти закрывает, или вы просто считаете что ничего легко даваться не должно, нужно каждому самому думать, читать, прикладывать усилия? Или какая-то еще у вас причина?
> 
> @val7000 Да, получилось. Но сейчас снова отвалилось, не работает. Дискуссии читали?

Читал дискуссии, пробовал разные стратегии. Уже чувствую, что времени трачу на это больше, чем оно того стоит) Уже больше ради технического интереса.

**Comment by zverxy** [comment]
привет, можете  помочь разобраться как вообще сказать запрет на линукс... ?? у меня мозгов нет. или хотябы дать подсказку

**Comment by Frestein** [comment]
> привет, можете помочь разобраться как вообще сказать запрет на линукс... ?? у меня мозгов нет. или хотябы дать подсказку

RTFM
