### ISSUE TITLE
[QUESTION] An analogue of the flags from GoodbyeDPI

### ISSUE THREAD

**Issue by SNR93** [bol-van/zapret#249]
Какие аналоги флагов у zapret для дефолтных флагов запуска goodbyeDPI?
Это goodbyeDPi:
-f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q

как я только на openwrt с флагами не играл, ничего не обходит. Стоит только запустить goodbyeDPI сразу все обходит.
И как сделать так, чтобы эта система и обходила запрет ютуба, и в то же время обходила блокировку других ресурсов?

**Comment by bol-van** [comment]
прямого отображения нет. gdpi шлет сразу 2 фейка badsum  и badseq
zapret так не умеет. но реально хватит и одного правильного
только на http badseq обычно ломает тспу
nfqws --dpi-desync=fake,disorder2 --dpi-desync-fooling=badseq
-q делается средствами фаервола.  ip/nf tables

 подбирать стратегии с пляской от результата блокчека

**Comment by SNR93** [comment]
Понял. И почему блокчек, после прогона определенного сайта, не хочет прогонять его еще раз после перезапуска скрипта?

**Comment by bol-van** [comment]
подробности. у меня и других он хочет

**Comment by ToxicEKB** [comment]
> прямого отображения нет. gdpi шлет сразу 2 фейка badsum и badseq zapret так не умеет. но реально хватит и одного правильного только на http badseq обычно ломает тспу nfqws --dpi-desync=fake,disorder2 --dpi-desync-fooling=badseq -q делается средствами фаервола. ip/nf tables
> 
> подбирать стратегии с пляской от результата блокчека

В GoodbyeDPI хватает настройки (и YT летает, и прочие сайты открываются):
-f 2 -e 2 --wrong-seq --reverse-frag --max-payload

На OpenWRT в zapret по аналогии прописываю в config:
NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-fooling=badseq"
Сайты открываются, YT не грузит. Из blockcheck пробовал вариации, максимум помогало открывать сайты которые уж совсем старались сделать недоступными, но YT так и стоит мертвым.

Что же такое есть в GoodbyeDPI, что не удается мне повторить на zapret?

**Comment by bol-van** [comment]
на чем работает  zapret ?
нет ли фильтрации по зостлисту?
включены ли http,https,quic ?
что выдают тесты курла на скорость из темы про замедление?

**Comment by ToxicEKB** [comment]
> на чем работает zapret ? нет ли фильтрации по зостлисту? включены ли http,https,quic ? что выдают тесты курла на скорость из темы про замедление? работает ли гудбай без -q ?

zapret на ASUS TUF AX4200
фильтрацию по хостлисту стоит в none
http, https, quic включены
тест на скорость могу провернуть только один (не умеет curl на openwrt в http3): 5027870
GDPI работает без -q

**Comment by bol-van** [comment]
судя по курлу замедление обходится
раз речь шла про винду, полагаю на ютуб лезет броузер
гляньте по ф12 на каком запросе затык
к какому домену и по какому  протоколу

**Comment by ToxicEKB** [comment]
ну винда не винда, yt не работает и на винде, и на тв, и на мобиле, те все что подключено к этой сети, на всем и нет yt.
в браузере глянул, стучится к поддоменам googlevideo.com, протокол https.
в zapret-hosts-user.txt прописан этот домен и множество других относящихся к yt.

**Comment by bol-van** [comment]
стучаться он будет это понятно и так
но есть ли затыки на googlevideo
или на других запросах затыки ?

**Comment by ToxicEKB** [comment]
Прошу прощения, не верно выразился. Именно на запросах к googlevideo и наблюдаются затыки

**Comment by bol-van** [comment]
тогда остается снимать дебаг лог nfqws  с роутера и смотреть все ли работает как надо
nfqws надо снять и перезапустить в консоли с теми же параметрами и --debug
/etc/init.d/zapret restart_daemons
тут можно срисовать параметры
/etc/init.d/zapret stop_daemons
и тут ручной запуск с debug
можно добавить | tee /tmp/log.txt
надо смотреть что он делает на проблемных запросах от броузера
отрабатывает ли как задумано

**Comment by ptipti23** [comment]
> прямого отображения нет. gdpi шлет сразу 2 фейка badsum и badseq zapret так не умеет. но реально хватит и одного правильного только на http badseq обычно ломает тспу nfqws --dpi-desync=fake,disorder2 --dpi-desync-fooling=badseq -q делается средствами фаервола. ip/nf tables
> 
> подбирать стратегии с пляской от результата блокчека

Господи, неужели.... Заработало
