### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by Setaran** [bol-van/zapret#25]
It's so hard to understand the google translate, I don't know how to install this on ubuntu 16, I've tried everything, can someone translate this properly please?

Thanks a lot :-)

**Comment by bol-van** [comment]
You can treat this software as transparent proxy for tampering with http traffic. Such as splitting request into parts, changing host: header spelling, many other features. Also generic startup files are provided. But this does not mean its one-button magic. You have to understand what it does , must find if it works with your ISP and if yes - which options work.

**Comment by baerbock** [comment]
@Setaran Real men speak Russian.
