### ISSUE TITLE
Доступность ресурсов с локалхоста

### ISSUE THREAD

**Issue by Episcop** [bol-van/zapret#250]
Для начала хотел поблагодарить автора, проект супер, спасибо.
А теперь вопрос ламера - как вернуть доступность ресурсов по wget и тп c хоста где стоит zapret?
А то даже банальный wget ya.ru или opkg update видимо дропаются.

**Comment by bol-van** [comment]
что-то с правилами *таблес намудрено
скрипты запрета делают редирект и для самого хоста
у вас с ними или самопал ? что за система и какие настройки

**Comment by Episcop** [comment]
> что-то с правилами *таблес намудрено скрипты запрета делают редирект и для самого хоста у вас с ними или самопал ? что за система и какие настройки

Keenetic Giga KN-1010
KeeneticOS 4.2 beta

Специально для zapret ставил opkg и до установки zapret все работало.
Zapret ставил по инструкции https://github.com/AlexFBG/zapret
По сути ничего страшного не случилось, я думал что вы знаете этот прикол и может есть какое то быстрое решение.

**Comment by bol-van** [comment]
кинетик я не поддерживаю и за левые инструкции не отвечаю
к автору

**Comment by Episcop** [comment]
Благодарен за ответ
