### ISSUE TITLE
Перезапуск сервиса с другим движком не убивает старый?

### ISSUE THREAD

**Issue by almirus** [bol-van/zapret#251]
ДД. в config была строчка
`MODE=nfqws`
, потом решил изменить на 
`MODE=tpws-socks` после перезапуска `systemctl restart zapret`
в top вижу, что теперь работают оба, это ошибка или норма?
![image](https://github.com/user-attachments/assets/77dfdd5a-63cf-4c64-9684-ebd5cc86af8a)

**Comment by bol-van** [comment]
да. надо было сначала остановить сервис
стоп идет по конфигу
