### ISSUE TITLE
Странное поведение, после подключения требует "залогиниться" в сеть

### ISSUE THREAD

**Issue by fruitbang** [bol-van/zapret#254]
после включения сервиса, в браузере появляется всплывашка, сигнализирующая что я должен залогиниться в сеть, а-ля публичная сеть в аэропорту
![Screenshot from 2024-08-11 15-44-00](https://github.com/user-attachments/assets/66b75e25-d550-41ef-8854-e08c511c25ad)

если нажать "подключиться" редиректит на url detectprortal.firefox.com/canonical.html
![Screenshot from 2024-08-11 15-45-39](https://github.com/user-attachments/assets/82edb3d4-751c-45c0-b46e-4d3ca7c2a90e)

скачивается html'ка с надписью SUCCESS
![Screenshot from 2024-08-11 15-46-03](https://github.com/user-attachments/assets/1e1114c5-e144-4c82-9a91-e67ec002c1ba)

**Comment by bol-van** [comment]
не хочу проходить через наводящие вопросы
описывайте на чем выполняется запрет
в каком режиме
как настраивалось
что за система клиентская

**Comment by fruitbang** [comment]
Пардон, тупанул.
Ставлю на ноутбук.
Система archlinux, gnome, network manager
Настраивал по видео на ютубе, которое пересказывает мануал quickstart.txt
Стратегия nfqws

**Comment by bol-van** [comment]
Firefox tests if the connection is a captive portal by regularly connecting to http://detectportal.firefox.com/canonical.html. Firefox will also make connections to this URL to check if your current network supports certain technologies such as IPv6

исходя из изложенного я бы попробовал дернуть
курлом этот урл. проверить не ломает ли стратегия их сервер
если курл проходит тогда смотреть в шарке куда лезет фокс при запуске
и не завершается ли тлс сессия к детектпорталу как-то ненормально

**Comment by fruitbang** [comment]
в общем, поменял стратегию и начало работать, спасибо
