### ISSUE TITLE
Не могу подобрать нужный конфиг

### ISSUE THREAD

**Issue by corerole** [bol-van/zapret#255]
OpenWRT 23.05, TP-Link Archer C7v5
поставил через install_easy.sh.
рекомендуемые настройки блокчека не работают вообще.
начал смотреть Available остановился на desync=syndata для tls1.3
это помогло обойти блоки нужных мне сайтов, но с ютубом проблему не решило.
Долго грузится сайт, иногда не с первого раза. Телик в сети не вывозит 4Kp60 hdr, хотя до блока нормально работал.
ещё стоит dnscrypt-proxy v2
[config.txt](https://github.com/user-attachments/files/16573859/config.txt)
[block.txt](https://github.com/user-attachments/files/16573812/block.txt)
Не знал куда написать, поэтому пишу тут.

**Comment by bol-van** [comment]
идите в дискуссии по теме замедления ютуба в Росии

**Comment by bol-van** [comment]
в блокчеке полно рабочих стратегий и без синдата
это потенциально ломающая стратегия и не работает с хостлистами

**Comment by corerole** [comment]
как выбирать?

**Comment by bol-van** [comment]
nfqws --dpi-desync=fake,split2 --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig

с хорошей вероятностью пробьет и замедление

**Comment by corerole** [comment]
> nfqws --dpi-desync=fake,split2 --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig

нет, это не работает. Буду тогда проверять всё ли я правильно сделал, но вроде как да.

**Comment by bol-van** [comment]
не работает что именно ?
блокчек не проверяет скорость
на теликах может понадобиться отключать  quic или затыкать порт udp 443

**Comment by corerole** [comment]
> не работает что именно ?
> оно работает, только не заходит на ютуб вообще

________

> блокчек не проверяет скорость
Ну это понятно.
________

> на теликах может понадобиться отключать quic или затыкать порт udp 443
![Снимок экрана 2024-08-13 203848](https://github.com/user-attachments/assets/da0cd051-0d1e-46af-9d1f-6d3624e3a9fe)

Заблокировал.
ситуация такая:
ПК
![Снимок экрана 2024-08-13 203615](https://github.com/user-attachments/assets/9d7671d9-c4a2-415c-a9ba-8cfcf4daf3cb)
Телик
![Снимок экрана 2024-08-13 204340](https://github.com/user-attachments/assets/c9fe115d-0b60-415b-8539-6bb69a815324)
