### ISSUE TITLE
MSS работает на macOS

### ISSUE THREAD

**Issue by Yarik0urWorld** [bol-van/zapret#258]
На macOS MSS отключен, в исходниках написано, что на маке вызовы не дадут никакого результата, хотя если закомментить ifdef'ы и пересобрать tpws, почему-то все заработало и DPI обходится.
Версия macOS: 11.7.0 (Big Sur)

**Comment by bol-van** [comment]
в шарке смотрите тцп опшинс в хэндшейке
что там ?
