### ISSUE TITLE
Не работает официальное приложение youtube на телевизорах lg

### ISSUE THREAD

**Issue by nobody7356** [bol-van/zapret#259]
На маршрутизаторе с openwrt запущено tpws

``` bash 
tpws --daemon --bind-addr 192.168.1.1 --port 999 --disorder --tlsrec=sni --split-pos=2 --pidfile $PIDFILE
iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 80 -j REDIRECT --to-port 999
iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 443 -j REDIRECT --to-port 999
```
- На подключенных клиентах macos в хроме youtube `работает`
- На подключенных клиентах ios в официальное приложение youtube `работает`
- На подключенных клиентах тв lg в браузере youtube  `работает`
- На подключенных клиентах тв lg официальное приложение youtube  `не работает`, даже не открывает превью

Подскажите, может какой параметр для tpws дополнительно включить? Есть идеи?

Пробовал заблокировать udp 443  как здесь советуют https://github.com/bol-van/zapret/issues/233 - не помогло

**Comment by maximwarner** [comment]
Доброго времени суток! У меня точно та же ситуация на Android TV. 443 порт тоже не помог. Интересно то, что ютуб не может только стартовать под zapret, а после старта, отлично с ним работает. Я делаю так: подключаюсь к Wi-Fi без запрета. Ютуб, долго, но загружается, включается без ошибок сети. Затем снова переключаюсь на Wi-Fi с активным zapret и можно спокойно смотреть видео без каких-либо зависаний. До того, как закроете ютуб. Потом придется все жто повторять.
Пока что, пока не нашел как побороть проблему с запуском, приходится использовать такой костыль. Попробуйте, может хоть так сможете смотреть.

**Comment by bol-van** [comment]
у меня нет ничего из вышеописанного. не на чем смотреть
если найдете приложение андроид где тоже самое - проверю

**Comment by nobody7356** [comment]
> Доброго времени суток! У меня точно та же ситуация на Android TV. 443 порт тоже не помог. Интересно то, что ютуб не может только стартовать под zapret, а после старта, отлично с ним работает. Я делаю так: подключаюсь к Wi-Fi без запрета. Ютуб, долго, но загружается, включается без ошибок сети. Затем снова переключаюсь на Wi-Fi с активным zapret и можно спокойно смотреть видео без каких-либо зависаний. До того, как закроете ютуб. Потом придется все это повторять. Пока что, пока не нашел как побороть проблему с запуском, приходится использовать такой костыль. Попробуйте, может хоть так сможете смотреть.

Увы, не помогло. Спасибо за отклик.

**Comment by nobody7356** [comment]
Вот что нашел на просторах интернета.

> Указанная утилита предлагает два основных режима работы – это TPWS или NFQWS. При использовании в режиме TPWS есть недостатки, заключающиеся в том, что в этом режиме не модифицируется протокол QUIC (HTTP/3), а также приложение YouTube на смарт телевизорах с WebOS или Android TV перестает вообще запускаться.

Похоже что утилитой TPWS не обойтись и для тв нужно кроме tcp 80 443 модифицировать udp 443 (QUIC), как видим в некоторых случая для Android TV достаточно просто заблокировать udp 443 и он сам начинает использовать tcp 443 вместо udp 443, для lg WebOS это увы не работает.

**Comment by maximwarner** [comment]
@nobody7356 попробуй этот конфиг https://github.com/bol-van/zapret/discussions/200#discussioncomment-10230793 ! У меня ютуб на Android TV после него наконец-то завелся!

**Comment by nobody7356** [comment]
Я не устанавливал весь пакет, я запускал отдельный бинарник tpws

На этот раз я запустил инсталятор, выбрал режим nfqws все заработало из коробки.
