### ISSUE TITLE
Установка на Ubuntu 18.04

### ISSUE THREAD

**Issue by golosoff** [bol-van/zapret#26]
Спасибо за подробную инструкцию
Остановился на двух непонятных мне вещах.
"Включить автостарт : chkconfig zapret on" - Где это необходимо сделать? в Ubuntu

И вот этим

"Процесс аналогичен debian 7, однако требуется зарегистрировать init скрипты в systemd после их копирования в /etc/init.d.
По умолчанию lsb-core может быть не установлен.
apt-get update
apt-get --no-install-recommends install lsb-core

install : /usr/lib/lsb/install_initd zapret
remove : /usr/lib/lsb/remove_initd zapret
start : sytemctl start zapret
stop : systemctl stop zapret
status, output messages : systemctl status zapret"

так же не пойму где это сделать в Ubuntu

Остановился я на "Там же выбрать параметр SLAVE_ETH, соответствующий названию внутреннего сетевого интерфейса."
cron тоже прописал

Заранее спасибо за ответ
Евгений

**Comment by bol-van** [comment]
chkconfig не относится к системам с systemd. Там используется systemctl.
Вопрос "где" мне непонятен. В терминале, конечно. От рута

**Comment by loordy** [comment]
Пожалуйста распишите процесс установки на ubuntu 18
Где запускается нормально

**Comment by bol-van** [comment]
ubuntu 18 я не проверял, однако эта система так же построена на systemd, значит для нее должно быть применимо все, что и для 16, возможно за исключением небольших нюансов типа названия пакетов, это можно додумать самостоятельно

**Comment by loordy** [comment]
падает с ошибками не могу понять где именно проблема
чуть позже выложу ошибки
