### ISSUE TITLE
Не работает google chrome, но работает на других барузерах

### ISSUE THREAD

**Issue by luckydevilru** [bol-van/zapret#260]
dnscrypt-proxy используется через  dnscrypt-proxy.socket портом 53000
а dnscrypt-proxy.service запускается dnscrypt-proxy.socket-ом при необходимости 

firefox, opera:
  открывают все

chrome открывает:
  https://x.com/
  https://rutracker.org/

chrome не открываются: 
  https://rutor.org/
  https://www.instagram.com/
  https://www.facebook.com/
  https://www.linkedin.com/

**Comment by bol-van** [comment]
такие issue практически бесполезны
потому что везде все по разному на провайдерах и стратегиях
без cap  файлов удачной и неудачной попыток можно закрывать
а так же нужен конфиг запрета

**Comment by bol-van** [comment]
некоторые сайты частично блочатся по ип адресам
броузеры могут использовать doh  от разных поставщиков
и некоторые ип блочены

**Comment by luckydevilru** [comment]
> такие issue практически бесполезны потому что везде все по разному на провайдерах и стратегиях без cap файлов удачной и неудачной попыток можно закрывать а так же нужен конфиг запрета

сделал все таки 53 порт в /lib/systemd/system/**dnscrypt-proxy.socket** несмотря из документацию у них: dnscrypt-proxy.socket 53000 а dnscrypt-proxy.service 53 порт

утро начинается с приятного. открываются все кроме linkedin - ну и ладно.

вот har если надо 
[hars.zip](https://github.com/user-attachments/files/16578483/hars.zip)


СПАСИБО ВАМ ЗА ТРУДЫ!

**Comment by luckydevilru** [comment]
**для ubuntu 24 автопереключатель VPN/DPI** 
была у меня проблема, что из-за того что /etc/resolv.conf постоянно перезаписывался. а если только чтение, не работал впн. написал скрипт для переключатель  resolv.conf при вкл/выкл впн:
выключаешь впн - настраивается под dpi и блочит редактирование.
включаешь впн - использует стандартный от systmd
