### ISSUE TITLE
Отвалились некоторые сайты

### ISSUE THREAD

**Issue by alexb0** [bol-van/zapret#269]
Пока разбираюсь, тут накидаю данных
openwrt, config по-умолчанию

Пока непонятно как чексумма ломается:

tcpdump: listening on wan, link-type EN10MB (Ethernet), snapshot length 262144 bytes
IP (tos 0x0, ttl 64, id 40536, offset 0, flags [DF], proto TCP (6), length 60)
    10.2.35.12.48564 > 185.65.151.100.80: Flags [S], cksum 0x7de2 (incorrect -> 0x9f50), seq 386111193, win 64240, optio
ns [mss 1460,sackOK,TS val 503096879 ecr 0,nop,wscale 5], length 0
        0x0000:  4500 003c 9e58 4000 4006 1eb0 0a02 230c
        0x0010:  b941 9764 bdb4 0050 1703 96d9 0000 0000
        0x0020:  a002 faf0 7de2 0000 0204 05b4 0402 080a
        0x0030:  1dfc a62f 0000 0000 0103 0305

/opt/zapret/config:
FWTYPE=nftables
SET_MAXELEM=522288
IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
AUTOHOSTLIST_RETRANS_THRESHOLD=3
AUTOHOSTLIST_FAIL_THRESHOLD=3
AUTOHOSTLIST_FAIL_TIME=60
AUTOHOSTLIST_DEBUGLOG=0
MDIG_THREADS=30
GZIP_LISTS=1
MODE=tpws
MODE_HTTP=1
MODE_HTTP_KEEPALIVE=0
MODE_HTTPS=1
MODE_QUIC=0
MODE_FILTER=none
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-ttl=0 --dpi-desync-ttl6=0 --dpi-desync-fooling=badsum"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6"
TPWS_OPT="--hostspell=HOST --split-http-req=method --split-pos=3 --oob"
FLOWOFFLOAD=donttouch
INIT_APPLY_FW=1
DISABLE_IPV6=1

**Comment by bol-van** [comment]
в дискуссии
ооб может ломать сайты
