### ISSUE TITLE
Translate it

### ISSUE THREAD

**Issue by KebabLord** [bol-van/zapret#27]
Just translate this repo to English so we can understand.

**Comment by baerbock** [comment]
@KebabLord Real real speak Russian.

**Comment by assasinfil** [comment]
это нужно только России)

**Comment by bol-van** [comment]
Translated short version of readme

**Comment by bol-van** [comment]
Не только у нас гнобят инет, но там своя специфика. Все, кроме гет_лист_фром_РКН, может пригодиться
