### ISSUE TITLE
Не могу собрать бинарники под свою платформу

### ISSUE THREAD

**Issue by dkim7bk** [bol-van/zapret#271]
Мой роутер asus rt-n11p, прошивка padavan. По инструкции скачал исходники openwrt и собрал пакеты для него. Собралось без проблем, но оказалось что бинарники от openwrt не подходят на padavan, т.к. openwrt на musl, а padavan на uclibc. Прописал в makefile пути на тулчейн и инклуды, но не компилируется, 

PATH=$PATH:(/home/dkim/padavan/padavan-ng/toolchain/out/bin)
export PATH
STAGING_DIR=(/home/dkim/padavan/padavan-ng/toolchain/out)
export STAGING_DIR
CC = /home/dkim/padavan/padavan-ng/toolchain/out/bin/mipsel-linux-uclibc-gcc
LDFLAGS = /home/dkim/padavan/padavan-ng/toolchain/out/bin/mipsel-linux-uclibc-ld
CFLAGS += -mips32r2 -march=mips32r2 -mtune=24kec -std=gnu99 -O3
CFLAGS += -I/home/dkim/padavan/padavan-ng/trunk/libs/libz/zlib-1.3.1
CFLAGS += -I/home/dkim/padavan/padavan-ng/toolchain/.build/mipsel-linux-uclibc/src/linux/include
CFLAGS += -I/home/dkim/padavan/padavan-ng/trunk/linux-3.4.x/include/linux
LIBS = -lz -lpthread -L/home/dkim/padavan/padavan-ng/trunk/stage/lib
SRC_FILES = *.c

all: tpws

tpws: $(SRC_FILES)
	$(CC) -s $(CFLAGS) -o $@ $(SRC_FILES) $(LDFLAGS) $(LIBS)

clean:
	rm -f tpws *.o

Помогите пожалуйста собрать

**Comment by bol-van** [comment]
-static
