### ISSUE TITLE
C Windows ходит на сайты, а с Android не ходит (OpenWRT)

### ISSUE THREAD

**Issue by fantrokr** [bol-van/zapret#273]
Приветствую.
OpenWRT 22, zapret, nftables, nfqws dns yandex на нестандартном порту

Много-много раз прогонял блокчек, менял настройки конфига, чаще всего получал результат: 
- работают rutracker, ntc, zona.media, tvrain 
- facebook, instagram страницы открываются, но контент не прогружается

Потом подобрал такой конфиг для https
NFQWS_OPT_DESYNC="--dpi-desync=syndata   --dpi-desync-fake-syndata=/opt/zapret/files/fake/tls_clienthello_iana_org.bin"

c Windows заработало, все что ни пробовал. Разве что твиттер слегка медленно подгружает контент.
а с Android не работает ничего из заблокированного, либо вечная загрузка, либо заглушка провайдера

Может упустил что-то?

**Comment by bol-van** [comment]
face и инста частично блокируются по ip
можно поиграться разными публичными днс
и разными doh в броузере. или вовсе отключить doh
лучше всего смотреть в tcpdump и лог --debug от nfqws
чтобы иметь обратную связь
иначе не понять что там с андроидом

syndata обязательно сломает часть сайтов,и ограничить по хостам невозможно
только по ip
