### ISSUE TITLE
nfq_open(): Protocol not supported

### ISSUE THREAD

**Issue by elmnn** [bol-van/zapret#276]
Zyxel keenetic III
im try : 
  /opt/zapret/nfq/nfqws --pidfile=/tmp/.nfqws.pid --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --qnum 200
and get :
  Loading hostlist /opt/zapret/ipset/zapret-hosts-user.txt
  loading plain text list
  Loaded 17 hosts from /opt/zapret/ipset/zapret-hosts-user.txt
  opening library handle
  nfq_open(): Protocol not supported

**Comment by bol-van** [comment]
you haven't loaded required kernel modules for nfqueue
i dont officially support stock firmwares
so cant tell you how. still i know its possible
there's russian discussion topic about  keenetic

**Comment by elmnn** [comment]
Thanks. My old core not fullsupport nfqws( 
I found my old keenetic start 2 and installed openwrt+zapret. It's working.
