### ISSUE TITLE
Перевести на английский, сделать релизы и залить на Gitlab

### ISSUE THREAD

**Issue by rezchikov** [bol-van/zapret#28]
@bol-van, это к тебе.

Могу сделать перевод на английский и литературно отредактировать оригинал **readme.md**.
Сделаю форк репозитария и залью его на Гитлаб под опенсоус-лицензий (GPLv3) с указанием оригинального авторства.

Постараюсь компилировать deb пакет, и упростить процесс установки на Ubuntu 18.xx.

**Comment by bol-van** [comment]
Я только приветствую. Можно даже авторства не указывать. Это ПО под лицензией "вне копирайта"

**Comment by bol-van** [comment]
Тем более что там половина кода скопипастена откуда-то еще :)

**Comment by heat-wave** [comment]
@rezchikov Буду рад поучаствовать в переводе и/или вычитке, если еще актуально и помощь принимается.

@bol-van Спасибо за гайд, это кладезь полезной информации!

**Comment by bol-van** [comment]
Проект в основном нацелен на русскоязычную аудиторию с учетом местных реалий.
Гугл переводчик довольно неплохо переводит текст на английский, кому надо - тот скопипастит
