### ISSUE TITLE
Обход замедления YouTube в РФ

### ISSUE THREAD

**Issue by Razdolbay-dev** [bol-van/zapret#281]
Подскажите , есть рабочий конфиг под NFQWS для обхода замедления YouTube ? 
Сервер Debian 11 
Firewall iptables 
использовал для проксирования через Mozilla [BeyDPI](https://github.com/hufrea/byedpi) , труба открывалась. 
Запускал с флагами 
`ciadpi --disorder 1 --auto=torst --tlsrec 1+s`
Есть какие то решения? Знаю точно у меня провайдер использует для блокировки запрещенки [Extfilter](https://github.com/max197616/extfilter)

**Comment by nikrays** [comment]
Может тут что-то найдете
https://github.com/nikrays/Zapret-on-Keenetic

**Comment by Razdolbay-dev** [comment]
> Может тут что-то найдете https://github.com/nikrays/Zapret-on-Keenetic

Открывается только в браузере. В приложении не хочет

**Comment by nikrays** [comment]
> > Может тут что-то найдете https://github.com/nikrays/Zapret-on-Keenetic
> 
> Открывается только в браузере. В приложении не хочет

Точно все по инструкции делали? Какой провайдер?

**Comment by Razdolbay-dev** [comment]
> > > Может тут что-то найдете https://github.com/nikrays/Zapret-on-Keenetic
> > 
> > Открывается только в браузере. В приложении не хочет
> 
> Точно все по инструкции делали? Какой провайдер?

Вышестоящий ТрансТелеКом

**Comment by nikrays** [comment]
> > > > Может тут что-то найдете https://github.com/nikrays/Zapret-on-Keenetic
> > > 
> > > 
> > > Открывается только в браузере. В приложении не хочет
> > 
> > 
> > Точно все по инструкции делали? Какой провайдер?
> 
> Вышестоящий ТрансТелеКом

Напишите в ТГ

**Comment by w3k5** [comment]
> > > > > Может тут что-то найдете https://github.com/nikrays/Zapret-on-Keenetic
> > > > 
> > > > 
> > > > Открывается только в браузере. В приложении не хочет
> > > 
> > > 
> > > Точно все по инструкции делали? Какой провайдер?
> > 
> > 
> > Вышестоящий ТрансТелеКом
> 
> Напишите в ТГ

Что произошло с репозиторием? Кто-то повлиял?
