### ISSUE TITLE
Не загружается контент на провайдере "Интегрированные сети связи (ИСС)" Краснодарский край в мобильных приложениях Facebook и Instagram

### ISSUE THREAD

**Issue by nikrays** [bol-van/zapret#283]
Здравствуйте, пытаюсь сделать универсальный конфиг на базе роутеров Keenetic, для Ростелеком - успех, на всех типах устройств работает стабильно Ютуб, и прочая запрещенка, включая fb, inst, x и ТД, контент в них тоже грузится молниеносно, тест был в разных регионах. Используется hostlist-user.

В планах ещё для МТС сделать..

Но есть такой провайдер "Интегрированные сети связи (ИСС)" Краснодарский край.
Тут ситуация аналогичная, за исключением контента в fb и inst, при том что именно на мобильных устройствах, на десктопе по прежнему ок. Если подробнее, то когда на мобиле в приложении fb заходим и обновляем, все обновляется, вижу новый текст и посты, но тупо нет картинок и видео, какого чёрта..

Что пробовал:
1. Игрался с параметрами обмана транспорта, безрезультатно, может какую идею дадите, реально долго стараюсь
2. QUIC тоже игрался
3. Нашел максимальное колличество доменов и субдоменов Facebook и Instagram, внёс в хостлист, в надежде обмануть стартовый запрос на image или что-то в этом вроде
4. Есствественно менял режим на none, чисто так, безысходность
5. Менял менял на разные паблик резолверы, делал это заменой первых двух строк в пунктах dns1 и 2 в настройках провайдера
6. Делал get_user, ip искал долго, но мимо 

Что возможно стоит попробовать:
1. Настроить DOT и DOH
2. Использовать маскарад
3. Помогите

**Comment by dzhumshoot** [comment]
@nikrays привет! У меня похожая проблема, только у меня как раз-таки Ростелеком. Можешь показать свой конфиг и хостлист? Может натолкнет на какие-то мысли. У меня сейчас так настроено (ютуб - ок, inst - не все прогружает, ресеты в консоли вижу):
```
MODE=nfqws
MODE_HTTP=0
MODE_HTTPS=1
MODE_QUIC=1
MODE_FILTER=hostlist
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-ttl=4 --dpi-desync-ttl6=2 --dpi-desync-split-pos=1 --wssize 1:6 --dpi-desync-fooling=md5sig"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6"
```

/opt/zapret/ipset/zapret-hosts-user.txt
```
googleapis.com
googlevideo.com
i.ytimg.com
i9.ytimg.com
wide-youtube.l.google.com
youtu.be
youtube.com
youtube.googleapis.com
yt3.ggpht.com
yt3.googleusercontent.com
instagram.com
cdninstagram.com
```

**Comment by nikrays** [comment]
> @nikrays привет! У меня похожая проблема, только у меня как раз-таки Ростелеком. Можешь показать свой конфиг и хостлист? Может натолкнет на какие-то мысли. У меня сейчас так настроено (ютуб - ок, inst - не все прогружает, ресеты в консоли вижу от *.cdninstagram.com):
> 
> ```
> MODE=nfqws
> MODE_HTTP=0
> MODE_HTTPS=1
> MODE_QUIC=1
> MODE_FILTER=hostlist
> NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-ttl=4 --dpi-desync-ttl6=2 --dpi-desync-split-pos=1 --wssize 1:6 --dpi-desync-fooling=md5sig"
> NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6"
> ```
> 
> /opt/zapret/ipset/zapret-hosts-user.txt
> 
> ```
> googleapis.com
> googlevideo.com
> i.ytimg.com
> i9.ytimg.com
> wide-youtube.l.google.com
> youtu.be
> youtube.com
> youtube.googleapis.com
> yt3.ggpht.com
> yt3.googleusercontent.com
> instagram.com
> cdninstagram.com
> ```

Здравствуйте, тут все есть

https://github.com/nikrays/Zapret-on-Keenetic

**Comment by nikrays** [comment]
@bol-van У вас может быть есть какие-нибудь предположения? По ip блочат?

**Comment by bol-van** [comment]
гадать смысла нет. надо дампы смотреть на конкретной проблеме
фб и инсту частично блочат по ип

**Comment by bol-van** [comment]
а еще очень много частных аномалий
где-то могут блочить что-то по ип
ggc некоторые ростелек блочит
это все живет, изменяется
черти экспериментируют на каких-то каналах
только исследование позволит выяснить

**Comment by nikrays** [comment]
> гадать смысла нет. надо дампы смотреть на конкретной проблеме фб и инсту частично блочат по ип

Хорошо, скажите пожалуйста, где их посмотреть? Могу ли я сюда их приложить?

**Comment by nikrays** [comment]
> гадать смысла нет. надо дампы смотреть на конкретной проблеме фб и инсту частично блочат по ип

![image](https://github.com/user-attachments/assets/2b5343fb-f896-410d-83ed-7b38cc3e312e)

Где этот параметр разместить?

**Comment by nikrays** [comment]
@bol-van 

--hostlist-auto-debug=/opt/zapret/AutoHostsDebug.log

Или так?

**Comment by nikrays** [comment]
> ресеты в консоли вижу от *.cdninstagram.com

Где вы их видите? В какой консоли? У вас получилось дебаг включить? Где вообще смотреть это все

**Comment by nikrays** [comment]
> а еще очень много частных аномалий где-то могут блочить что-то по ип ggc некоторые ростелек блочит это все живет, изменяется черти экспериментируют на каких-то каналах только исследование позволит выяснить

Выяснилось что на десктопах тоже контент в иннст и фейс не грузит, значит по ip? Или с ттл продолжить играться, но если по ip то какой режим выбрать?

**Comment by bol-van** [comment]
протестируйте конектит ли порт 443 неткатом
блокчек это делает в начале
если порт не конектит то либо менять днс, либо вписывать рабочий ип в хостс, либо проксировать
обойти полный ип или порт блок автономно невозможно

**Comment by nikrays** [comment]
@bol-van 
В общем прогнать facebook.com и Instagram.com этим

/opt/zapret/blockcheck.sh | tee /opt/zapret/blockcheck.txt

Что касается рабочего ip это надо специально найти список ip этих ресурсов, и добавить их в zapret-hosts-user.txt, верно я вас понял?

Что касается днс, я уже не знаю какие прописывать..

**Comment by bol-van** [comment]
их бессмысленно добавлять в лист обхода dpi
важно чтобы система ресолвила домены в незаблокированные адреса
научитесь проверять доступность порта неткатом
и ресолвить домены через произвольные dns (nslookup, dig)

**Comment by nikrays** [comment]
@bol-van Был бы признателен, если бы чуть больше инфы дали, чтобы сделать инструкцию по вашему депо ещё лучше, для людей с разными операторами.

Можно ли через ssh в entware прописать команды для резолва доменов через произвольные днс (nslookup, dig) и как это сделать?

**Comment by nikrays** [comment]
> протестируйте конектит ли порт 443 неткатом блокчек это делает в начале если порт не конектит то либо менять днс, либо вписывать рабочий ип в хостс, либо проксировать обойти полный ип или порт блок автономно невозможно

[blockcheck.txt](https://github.com/user-attachments/files/16648399/blockcheck.txt)

Посмотрите пожалуйста, что вы тут увидите?

**Comment by bol-van** [comment]
ситуация меняется, инструкции писать бесполезно
они устареют очень быстро
надо уметь самому разбираться

в блокчеке порт блока нет, ип блока нет, zapret легко пробивает DPI

**Comment by nikrays** [comment]
> ситуация меняется, инструкции писать бесполезно они устареют очень быстро надо уметь самому разбираться
> 
> в блокчеке порт блока нет, ип блока нет, zapret легко пробивает DPI

Тогда почему же на этом горе провайдере не получается отобразить контент, то есть фото и видео содержимое в инстаграмм и Фейсбук? 
Что могли бы посоветовать? Поиграться ещё с --dpi-desync?

**Comment by bol-van** [comment]
надо смотреть в броузере на каких доменах затык идет
F12. вкладка "сеть"
заодно там добавить поле "протокол" в контекстном меню
чтобы смотреть на каком протоколе (h3, https) застревает

**Comment by nikrays** [comment]
> надо смотреть в броузере на каких доменах затык идет F12. вкладка "сеть" заодно там добавить поле "протокол" в контекстном меню чтобы смотреть на каком протоколе (h3, https) застревает в дебаггере так же есть инфа на какой ип он лезет вот его то и надо пробить неткатом, если конекта не идет совсем

Я примерно понял, попробую позже, надеюсь что в конце концов все получится

**Comment by nikrays** [comment]
> надо смотреть в броузере на каких доменах затык идет F12. вкладка "сеть" заодно там добавить поле "протокол" в контекстном меню чтобы смотреть на каком протоколе (h3, https) застревает в дебаггере так же есть инфа на какой ип он лезет вот его то и надо пробить неткатом, если конекта не идет совсем

![image](https://github.com/user-attachments/assets/96b4dfb8-bfe0-443a-8db3-ad633fc72c70)


Протокол не хочет показывать, эти домены в хост листе все присутствуют...
Вот что заметил, когда переключаю user agent например айфон, то грузится мобильная версия, ну картинки всмысле, но в тоже время на самом айфоне в приложении не грузится.. 

![image](https://github.com/user-attachments/assets/e927a5c7-173e-4ac5-9230-61aac4476dfb)

Что касается дебаггера и нетката, мне не хватает информации и знаний, подскажите как это все выполнить?

**Comment by bol-van** [comment]
видно что фейс конектит
но не конектит  static.xx.fbcdn.net
там надо покопаться и найти конкретный ип адрес куда лез броузер
его и надо проверить этот ип на порт tcp 443. есть конект или нет
если нет это блокировка ип и надо плясать со сменой днс/doh или вносить в хостс неблоченые ип

**Comment by Andy-Foxxx** [comment]
Добрый день! Извиняюсь, что не по теме.
Ответьте пожалуйста, а куда делась ваша разработка "zapret на Keentic"? Себе успел настроить, хотел коллеге, а тема сегодня пропала, не додумался скопировать...

**Comment by bol-van** [comment]
это не моя разработка
кинетик не поддерживаю

**Comment by Andy-Foxxx** [comment]
bol-van, простите, вопрос был к nikrays, просто не знаю как ему лично написать.

**Comment by zhendosina** [comment]
@Andy-Foxxx  у меня аналогичная история))))

**Comment by AndryTerry** [comment]
@nikrays Присоединяюсь к комментам выше, хотел обновить конфиг, а вы снесли инструкцию.. Отличная была.
Не вернете?

**Comment by nikrays** [comment]
@AndryTerry ваш ТГ

**Comment by AndryTerry** [comment]
> @AndryTerry ваш ТГ

https://t.me/Ilya_Teterin
