### ISSUE TITLE
а можно ещё и для arm64?

### ISSUE THREAD

**Issue by admzzz** [bol-van/zapret#29]

**Comment by admzzz** [comment]
плиз...
...dnscrypt-proxy и purple I2P именно так и выкладывают бинарники - для всех основных платформ...

**Comment by bol-van** [comment]
Уже задавали этот вопрос. У вас ядро arm64 без поддержки arm32 ? Обычно все 64-битные ядра собираются с поддержкой эмуляции 32
Что за девайс ?

**Comment by admzzz** [comment]
хочется не для конкретного девайса, а как модуль для вот такого [комбайна ](https://4pda.ru/forum/index.php?showtopic=940927)
без эмуляции 32 ведь, теоретически, быстрее должно фурычить? или я неправ? (разработчик не я, если чё ;-) )

**Comment by bol-van** [comment]
Основная нагрузка не приходится на код этих бинариков, без разницы 32 или 64.
Может ip2net будет шустрее чуток. Не 2.5 секунды, а 2.2 секунды.

**Comment by bol-van** [comment]
Добавил aarch64. На openwrt aarch64 нечасто встречается, но на всякий случай пусть будет
