### ISSUE TITLE
Skip testing with the first fail

### ISSUE THREAD

**Issue by AntonSamokat** [bol-van/zapret#294]
Sorry if this is already described in readme.

Есть ли опция в blockcheck.sh для пропуска тестов после первого провала?

Т.е. например при задании 10 тестов
```
sometimes ISPs use multiple DPIs or load balancing. bypass strategies may work unstable.
how many times to repeat each test (default: 1) : 10
```

Для того чтобы тестирование выполнялось быстрее. Чтобы вместо:
```
* curl_test_http3 ipv4 www.youtube.com
- checking without DPI bypass
[attempt 1] curl: (28) Connection timed out after 2003 milliseconds
[attempt 2] curl: (28) Connection timed out after 2003 milliseconds
[attempt 3] AVAILABLE
[attempt 4] AVAILABLE
[attempt 5] AVAILABLE
[attempt 6] AVAILABLE
[attempt 7] curl: (28) Connection timed out after 2002 milliseconds
[attempt 8] AVAILABLE
[attempt 9] curl: (28) Connection timed out after 2002 milliseconds
[attempt 10] AVAILABLE
UNAVAILABLE code=28
```

Стало:
```
* curl_test_http3 ipv4 www.youtube.com
- checking without DPI bypass
[attempt 1] curl: (28) Connection timed out after 2003 milliseconds
UNAVAILABLE code=28
```
Т.е. если происходит хотя бы один провал, чтобы остальные попытки для текущего теста пропускались? Если один тест проваливается, то уже понятно что текущая стратегия не очень хорошая. Весь процесс тестирования при этом значительно бы ускорился.

**Comment by bol-van** [comment]
Это сделано в quick режиме
quick останавливается как только находит первый рабочий вариант

но основной режим работы blockcheck - не поиск абы какой таблетки, а исследование dpi на предмет обхода

**Comment by AntonSamokat** [comment]
@bol-van Благодарю
