### ISSUE TITLE
Сбор логов nfqws в режиме --daemon

### ISSUE THREAD

**Issue by Anonym-tsk** [bol-van/zapret#295]
Не нашел как запустить nfqws одновременно в --debug режиме и --daemon, чтобы писать логи в файл.
Есть такая возможность?

**Comment by nikrays** [comment]
Присоединяюсь к вам, будет для всех полезно нормально команду написать иди алгоритм, чё делать чтобы в лог записалось

**Comment by bol-van** [comment]
пока дебаг лог реализован только в консоли
но, похоже, неплохо было бы сделать дублирование в файл ?

**Comment by Anonym-tsk** [comment]
Было бы неплохо, да. Пока запустил через nohup, но хочется легальное решение )

**Comment by bol-van** [comment]
окей, сделаем. это не сложно

**Comment by bol-van** [comment]
если надо оставлять надолго, можно screen использовать
и атачиться-детачиться к нему когда угодно

**Comment by Anonym-tsk** [comment]
> можно screen использовать

Да у нас тут проблема в том, что кинетик с запущенным nfqws периодически перезагружается, при этом в логе кинетика ничего полезного кроме "hardware watchdog reset". Собственно, поэтому нужен вывод в файл.

**Comment by nikrays** [comment]
> > можно screen использовать
> 
> Да у нас тут проблема в том, что кинетик с запущенным nfqws периодически перезагружается, при этом в логе кинетика ничего полезного кроме "hardware watchdog reset". Собственно, поэтому нужен вывод в файл.

Кстати об этой проблеме кто-то уже говорил, на оригинальном репо такой проблемы нет, может когда пересобирали, что-то упустили?

**Comment by Anonym-tsk** [comment]
Не пересобирали, бинарник оригинальный отсюда.
Есть подтверждение, что на оригинальной репе тоже есть перезагрузки. Но не у всех, конечно. У кого-то чаще, у кого-то реже.

**Comment by nikrays** [comment]
@Anonym-tsk 
Ну я вот много раз себе перенастраивал, а также родственникам и знакомым, ну и другие , пока жалоб мне не писали, все хорошо, вот я инструкцию даже сделал, можете глянуть, может что-то полезное возьмёте, хотя там все от оригинала.
https://github.com/nikrays/Zapret-on-Keenetic

**Comment by Anonym-tsk** [comment]
@nikrays включите issues в репе )
Боюсь, что у меня выборка побольше

**Comment by bol-van** [comment]
Прошивочки могут жить своей жизнью. Никто не думал про nfqws при их создании
они могут как угодно дергать правила. сносить их, не расчитывая, что там может быть какой-то NFQUEUE
так же у кинетиков патченое ядро, проприетарный софт user mode
что они  там творят это к фанатам и производителю вопрос

**Comment by Anonym-tsk** [comment]
@bol-van ну в любом случае. У части пользователей в рандомный момент роутер перезагружается и это как-то связано с nfqws. У меня пока была одна перезагрузка с аптаймом в 4 дня.
Сейчас запустил запись в лог, буду смотреть.

**Comment by nikrays** [comment]
@Anonym-tsk 
Включил, посмотрим, но у меня там ссылка на ТГ, так что со мной связываются переодически, но с другими вопросами
Могу сказать одно, что устройства с 128мб ОЗУ страдают и я не знаю какой режим самый щадящий 
"none, ipset, autohostlist, hostlist"
@bol-van кстати, не подскажете какой не сильно напрягает ОЗУ?

**Comment by Anonym-tsk** [comment]
Вот кстати, с ОЗУ проблем нет, даже на устройствах со 128Мб работает нормально. Перезагрузки явно не из-за памяти

**Comment by nikrays** [comment]
@Anonym-tsk а у вас какой там конфиг по умолчанию? И какой режим из 4 стоит?

**Comment by Anonym-tsk** [comment]
@nikrays https://github.com/Anonym-tsk/nfqws-keenetic/blob/4c52a88b8dbe4aae1ed64b3c7cea75ee7a40c6af/etc/nfqws/nfqws.conf#L7

**Comment by nikrays** [comment]
@Anonym-tsk у вас получается на базе none, обходится все что можно?

**Comment by Anonym-tsk** [comment]
> обходится все что можно?

По умолчанию, hostlist+autohostlist, но пользователь может выбрать при установке

**Comment by Anonym-tsk** [comment]
> окей, сделаем. это не сложно

Лог файл достиг размера ~1Gb, nfqws стал как-то медленно работать.
Возможно, нужна какая-то ротация логов, он забивается очень быстро

**Comment by bol-van** [comment]
В tpws и nfqws реализован логгинг в syslog и file

**Comment by Anonym-tsk** [comment]
`--debug-level=0|1|2` для nfqws я так понимаю недоступен?

**Comment by bol-van** [comment]
Да, там только 1 левел. И всегда был
а в tpws 2.  2-й уровень для отладки "кишков" tpws

**Comment by Anonym-tsk** [comment]
Было бы удобнее конечно как в tpws сделать
`--debug=syslog --debug-level=0|1`

**Comment by Anonym-tsk** [comment]
Проверил, все работает

**Comment by bol-van** [comment]
С какой целью ? --debug=syslog автоматом выставляет log level в 1
А без него он автоматом 0

**Comment by bol-van** [comment]
Если LOG_LEVEL пустой когда не надо и не пустой когда надо, то можно так сделать
${LOG_LEVEL:+--debug=syslog}
