### ISSUE TITLE
Не подходит не один из способов обхода, куда копать дальше? 

### ISSUE THREAD

**Issue by Andr3WTF** [bol-van/zapret#296]
Собственно имеется следующая ситуация: Установил zapret на роутер с openwrt, запустил blockcheck.sh, перебор всех возможных вариантов выдал:
`* SUMMARY
ipv4 mail.ru curl_test_http : tpws not working
ipv4 mail.ru curl_test_http : nfqws not working
ipv4 mail.ru curl_test_https_tls12 : tpws not working
ipv4 mail.ru curl_test_https_tls12 : nfqws not working
`
А обойти интернет цензуру то хочется,

**Comment by ZongerX** [comment]
DoH или DoT сервера на роутере прописаны?

**Comment by bol-van** [comment]
mail.ru в какой стране блокируется ?
возможно там ip блоки, и они не обходятся автономно

**Comment by Andr3WTF** [comment]
> DoH или DoT сервера на роутере прописаны?
незнаю оно или нет, но включены dnscrypt-proxy
![изображение](https://github.com/user-attachments/assets/b76d7774-8e21-4a0e-a7a3-1204f22d7c7c)

**Comment by Andr3WTF** [comment]
> mail.ru в какой стране блокируется ? возможно там ip блоки, и они не обходятся автономно в блокчеке есть порт блок тест и тест на частичный ип блок и dns чек тоже есть, правда он по умолчанию заточен на домены, блокируемые в RU

Украина, меня днс на гуловские и клаудфлавровские и на адгуадровские результата недало.

**Comment by bol-van** [comment]
до войны там блочили по целым автономным ситемам
обход дпи не поможет
нужен впн или прокси
