### ISSUE TITLE
Подскажите по настройкам для МГТС (Мск)

### ISSUE THREAD

**Issue by wowa-2017** [bol-van/zapret#299]
Исходное положение: ютуб не грузит видео ни на андроидах, ни на Вин-ПК в домашней сети.

Установил tpws на Asus RT-AC68U, запускаю с параметрами (подсмотрел на 4pda): --disorder --tlsrec=sni --split-pos=2

На андроидах ютуб работает (хотя почему-то сломался гугл-переводчик), а на ПК в Хроме и Опере стабильно и без вариантов пишет "Нет соединения с интернетом" (сообщение самого ютуба). Еще из обнаруженного: не заходит на 4pda ("Не удается получить доступ к сайту. Сайт 4pda.to неожиданно разорвал соединение."). Но вообще большинство сайтов работает.

Если включаю на ПК гудбай-dpi, то ютуб в браузерах отлично работает. Для гудбай-dpi известны параметры для случая МГТС:
goodbyedpi.exe -9 -e1 -f1 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

Почитал ридми к zapret'у, он исключительно подробный, но это конечно надо времени немало на исследования... Может быть, кто-то уже подобрал параметры для случая МГТС, просьба поделиться. Или подсказать, какие настройки tpws соответствуют этим из gb-dpi. В хелпе к нему написано:
-f <value>  set HTTP fragmentation to value
-e <value>  set HTTPS fragmentation to value
-9  =        -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q
 
Предположил, что --split-pos примерно может быть аналогом -f1 или e1, но --split-pos=1 ситуацию не изменило. Подскажите, плиз, как настроить tpws аналогично этому конфигу гудбая.

**Comment by bol-van** [comment]
если нужна помощь аудитории идите в дискуссии
здесь только проблемы софта
нерабочесть стратегиитдоя вашего случае проблемой софта не является

**Comment by wowa-2017** [comment]
Да, пардон, не посмотрел сразу в дискуссии, там как раз этот случай кто-то уже пытается побороть. Жалко, что пока вроде без особого успеха.

**Comment by eastone11** [comment]
> Да, пардон, не посмотрел сразу в дискуссии, там как раз этот случай кто-то уже пытается побороть. Жалко, что пока вроде без особого успеха.

подобрал, смотрите в дискусиях и пробуйте

**Comment by bol-van** [comment]
tpws и gdpi вообще по-разному работают
tpws на уровне потока (stream), gdpi и nfqws на уровне пакетов

nfqws --dpi-desync=fake,disorder2 --dpi-desync-fooling=badseq  (или badsum)
-q делается средствами фаервола/iptables/nftables
