### ISSUE TITLE
мелочи

### ISSUE THREAD

**Issue by admzzz** [bol-van/zapret#30]
1) в инструкции пропущено необходимое chmod +x /etc/init.d/zapret перед 
/usr/lib/lsb/install_initd zapret
2) 
```
# ./get_reestr.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.8M  100 20.8M    0     0  1907k      0  0:00:11  0:00:11 --:--:-- 2247k
preparing dig list ..
digging started ...
```
и висит так больше 2 часов на ноуте с третьим интелом и /tmp  в оперативке ;-)
т.е. хорошо б какую-нибудь индикацию происходящего...
поставил set -x, висит на
```
digging started ...
+ grep -vE ^10\.[0-9]+\.[0-9]+\.[0-9]+$
+ grep -vE ^127\.[0-9]+\.[0-9]+\.[0-9]+$
+ grep -vE ^192\.168\.[0-9]+\.[0-9]+$
+ grep -E ^[^;].*[^\.]$
+ dig A +short +time=8 +tries=2 -f /tmp/zapret-dig.txt
```
оба /tmp/zapret*.txt не изменяются, размер  /tmp/zapret-dig.txt 2.6мб.
3) при подмене сертификата провайдером (по словам blockcheck, провайдер - мгтс, dnscrypt стоит и фурычит) какой из ISP выбирать/проканает?

4) в разделе настройки ISP кстати пришлась бы ссылка(и) на обсуждения блокировок провайдеров (ведь трёп идёт не только на рутрекере и гитхабе, небось?)...
5) внятно бы прописать в инструкции настройки стандартного файерволла, а то:
```
Apr 17 06:12:52 kernel: [254872.826880] [UFW BLOCK] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=48 ID=19242 DF PROTO=TCP SPT=443 DPT=33538 WINDOW=0 RES=0x00 RST URGP=0 
Apr 17 06:12:52 kernel: [254872.867854] [UFW AUDIT INVALID] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=52 ID=63166 DF PROTO=TCP SPT=443 DPT=33540 WINDOW=0 RES=0x00 RST URGP=0 
Apr 17 06:12:52 kernel: [254872.867868] [UFW BLOCK] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=52 ID=63166 DF PROTO=TCP SPT=443 DPT=33540 WINDOW=0 RES=0x00 RST URGP=0 
Apr 17 06:12:52 kernel: [254872.869096] [UFW AUDIT INVALID] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=52 ID=63167 DF PROTO=TCP SPT=443 DPT=33540 WINDOW=0 RES=0x00 RST URGP=0 
Apr 17 06:12:52 kernel: [254872.869108] [UFW BLOCK] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=52 ID=63167 DF PROTO=TCP SPT=443 DPT=33540 WINDOW=0 RES=0x00 RST URGP=0 
Apr 17 06:12:52 kernel: [254872.920032] [UFW AUDIT INVALID] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=52 ID=50150 DF PROTO=TCP SPT=443 DPT=33536 WINDOW=0 RES=0x00 RST URGP=0 
Apr 17 06:12:52 kernel: [254872.920043] [UFW BLOCK] IN=wlp2s0 OUT= MAC=68:17:29:4c:84:75:94:04:9c:50:8a:23:08:00 SRC=192.30.253.113 DST=192.168.1.3 LEN=40 TOS=0x00 PREC=0x20 TTL=52 ID=50150 DF PROTO=TCP SPT=443 DPT=33536 WINDOW=0 RES=0x00 RST URGP=0
```

**Comment by bol-van** [comment]
1)  chmod не нужен, достаточно поправить +x в гите. у меня без +x было
2) изменяется, только диг работает очень очень долго. может занять целую ночь. можно уменьшить таймауты time=4 tries=1.   проверка  : tail /tmp/zapret-ip.txt   через промежутки времени
этот скрипт создавался на ранних этапах, когда реестр еще не разросся до таких чудовищных размеров. потому, наверно, он уже мало актуален. должна быть централизованная ресолвилка. пока ее держит valdikss на antizapret. лучше пользовать get_antizapret или get_combined
3) На https оно не расчитано. https не обходится. В инструкции указано, что в большинстве случае https приходится проксировать, и приведены 2 метода : redsocks и wireguard+iproute
Теоретически в некоторых случаях может помочь nfqws или tpws --split-pos  на порту 443
Это стоит проверить вручную, если сработает - можно написать свои правила в custom
4) Не отслеживаю
5) ufw не включен по умолчанию. как там сказано, если вы пользуете какие-то системы управления фаером, нужно прикручивать правила туда.

**Comment by bol-van** [comment]
на счет саморесолвинга может быть напишу альтернативный собственный многопоточный ресолвер.

**Comment by bol-van** [comment]
Набросал мультитредный mdig.  У меня весь реестр заресолвило минут за 45 на 30 потоках
