### ISSUE TITLE
Не загружается мобильное приложение Госуслуги

### ISSUE THREAD

**Issue by pavloooha** [bol-van/zapret#307]
Здравствуйте. Имеется роутер Xiaomi Mi Router 4A, OpenWrt 23.05.4, провайдер Dom.ru. Zapret установлен, все работает молниеносно и как часы, все сайты, включая fb, inst, торренты открываются, ютуб работает на всех устройствах.

Однако, по какой-то причине, отказывается работать приложение Госуслуги на телефоне (iOS 17.5.1) - ругается, что нет интернета. Причем, с компьютера сайт открывается и работает нормально. Подскажите в какую сторону можно копнуть? 

/zapret/config:
```
MODE=nfqws
MODE_HTTP=1
MODE_HTTP_KEEPALIVE=0
MODE_HTTPS=1
MODE_QUIC=0
MODE_FILTER=none
NFQWS_OPT_DESYNC="--dpi-desync=fake,split --dpi-desync-ttl=3 --dpi-desync-fooling=md5sig"
```

Скажите, если нужны еще какие-то данные или логи. Заранее спасибо.

**Comment by pavloooha** [comment]
> Вероятно стратегия ломает сайт или его ддос-защиту Надо использовать лист исключений ipset/zapret-hosts-user-exclude.txt В режиме none он работает по IP. Но вроде гос услуги не прыгают по ip. Или можно включить hostlist, тогда и фильтрация исключений будет по хостлисту

Включил режим hostlist, добавил в exclude список 2 домена (gosuslugi.ru и esia.gosuslugi.ru), include список сделал пустым. Итог - Госуслуги теперь работают, а все что работало до этого - отвалилось. Возвращаю режим на none - опять все работает, кроме Госуслуг.

Забыл написать, что использую nftables, может в этом причина.

**Comment by pavloooha** [comment]
> поддомены можно не добавлять чтобы не срабатывал список включения, нужно, чтобы zapret-hosts-user.txt был пустым (файл нулевой длины) и zapret-hosts.txt/zapret-hosts.gz отсутствовал чтобы не было еще своих параметров --hostlist в стратегии и фильтрация не была autohostlist

Оставил один домен (gosuslugi.ru) и обратил внимание, что при запуске все равно подгружается include файл (хотя он и пустой). По итогу просто переименовал его и при запуске остался только параметр hotlist-exclude.

Как итог - все заработало. И сайт и приложение госуслуг работают, вместе с ютубом, фб и инст. Спасибо вам большое за помощь.

**Comment by bol-van** [comment]
Да, он подгружается, но если нет hostlist-auto, то итоговый include hostlist в памяти остается пустым, и nfqws/tpws не делают отличий этой ситуации от полного отсутствия инклуд листа (только что проверил - работает)

**Comment by vnt-83** [comment]
> поддомены можно не добавлять

Без добавления esia.gosuslugi.ru не получалось авторизоваться в сторонних сервисах типа dom.gosuslugi.ru и налоговой, где авторизация через ESIA. После добавления заработало нормально.
