### ISSUE TITLE
blockcheck.sh для youtube.com

### ISSUE THREAD

**Issue by Hanqnero** [bol-van/zapret#312]
blockcheck.sh подобрал параметры для rutracker.org . С ними большинство сайтов открыаются без проблем, кроме видео youtube.com . Загружается сам сайт и статический контент (аватарки и превью), но не видео. Как можно пофиксить, куда следует смотреть?

flags: `nqfws --dpi-desync=fake --dpi-desync-ttl=6`
OS Manjaro Linux
ISP Ростелеком

**Comment by bol-van** [comment]
добавить --dpi-desync-fooling=md5sig
если  не помогает, заменить fake на fake,split2

**Comment by Hanqnero** [comment]
Помогло, спасибо!

**Comment by herois90** [comment]
--filter-tcp=443 \
--dpi-desync=fake,multisplit \
--dpi-desync-fooling=md5sig \
<HOSLIST> --new
мне достаточного такого, иногда ютуб не открываеться, jnn-pa.googleapis.com - айпи отправил через vpn

**Comment by Sibiriak** [comment]
Аналогичная проблема, blockcheck подобрал стратегии  для rutracker, но  ютуб видео  не открываются и даже превью не отображаются.  Можете объяснить начинающему, что делать дальше? Из инструкции ничего не понятно.

!!!!! curl_test_http3: working strategy found for ipv4 rutracker.org : winws --dpi-desync=ipfrag2 --dpi-desync-ipfrag-pos-udp=8 !!!!!

clearing winws redirection

* SUMMARY
ipv4 rutracker.org curl_test_http : winws not working
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,multisplit --dpi-desync-fooling=badseq --dpi-desync-split-pos=1
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,fakedsplit --dpi-desync-fooling=badseq --dpi-desync-split-pos=1
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=badsum --dpi-desync-split-pos=midsld
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=badseq --dpi-desync-split-pos=1
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,fakeddisorder --dpi-desync-fooling=badseq --dpi-desync-split-pos=1
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=multisplit --dpi-desync-split-pos=2 --dpi-desync-split-seqovl=336 --dpi-desync-split-seqovl-pattern=/cygdrive/f/1/zapret-win-bundle-master/blockcheck/zapret/files/fake/tls_clienthello_iana_org.bin
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata --dpi-desync-fake-syndata=/cygdrive/f/1/zapret-win-bundle-master/blockcheck/zapret/files/fake/tls_clienthello_iana_org.bin
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata,multisplit --dpi-desync-fake-syndata=/cygdrive/f/1/zapret-win-bundle-master/blockcheck/zapret/files/fake/tls_clienthello_iana_org.bin --dpi-desync-split-pos=1
ipv4 rutracker.org curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata,multidisorder --dpi-desync-fake-syndata=/cygdrive/f/1/zapret-win-bundle-master/blockcheck/zapret/files/fake/tls_clienthello_iana_org.bin --dpi-desync-split-pos=1
ipv4 rutracker.org curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=ipfrag2 --dpi-desync-ipfrag-pos-udp=8
