### ISSUE TITLE
Есть ли обход блокировок dpi + vpn?

### ISSUE THREAD

**Issue by ko22009** [bol-van/zapret#313]
Интересует дурение dpi youtube, а также возможность ручного добавление списка обхода, чтобы ходить через vpn к ним.

И вопрос такой, есть ли способ принудительного vpn если dpi не отработал?

**Comment by bol-van** [comment]
> И вопрос такой, есть ли способ принудительного vpn если dpi не отработал?

автоматически нет, только если по каким-то спискам настроить
про дурение Youtube идем в дискуссии. там есть топик

> возможность ручного добавление списка обхода, чтобы ходить через vpn к ним

это делается либо через policy routing на linux по IP адресам, либо через высокоуровневые прокси-решения типа xray
настройка довольно сложна, и к запрету отношения не имеет
единственное, что есть в zapret - это автоматизированная система подготовки списка ip адресов, но настройка policy routing или прозрачного прокси ложится на юзера. дока есть

**Comment by ko22009** [comment]
@bol-van, Т.е. верно я понял, что физически не понять, получилось получить доступ к ресурсу или нет?
"автоматически нет, только если по каким-то спискам настроить" - т.е. это тот же ruantiblock со своими списками.

не подскажите, с ruantiblock, zapret нормально будет работать? или ruantiblock будет пытаться взять инициативу в свои руки, если в его списках есть ресурс, который надурили через zapret.

**Comment by bol-van** [comment]
понять относительно можно . этот алгоритм используется у меня в autohostlist.
но в tpws функции upstream proxy нет, а nfqws вообще никак не может ничего перенаправить, поскольку лишь работает с проходящими отдельными пакетами, и никаких функций TUN у него нет

ruantiblock : судя по беглому гуглу, это средство заполнения IP + policy routing  с интерфейсом пользователя
по доменам там нет рулежки. если и есть домены, то они ресолвятся в IP
я не проверял с zapret-ом, но полагаю могут быть сценарии конфликта, и нужно понимать детали, чтобы это исправить
