### ISSUE TITLE
Zapret не срабатывает с первого раза

### ISSUE THREAD

**Issue by ko22009** [bol-van/zapret#314]
**Проблема:**
С первого захода на заблокированные ресурс страница падает с ERR_TIMED_OUT, приходится ждать примерно по 2 минуты чтобы эта ошибка упала.

Но потом когда заходишь на эту вкладку с ошибкой, "то возможно браузер делает повторный запрос", страница прогружается нормально. Переходы по страницам отрабатывают как надо.

Такое же поведение происходит с youtube роликами. Тоже зависание при первом открытии. Может быть такое, что смотришь разные ролики, в процессе просмотра одного длинного ролика проблем не обнаружены. Но когда идет новое соединение на другой ролик, то есть такой прикол.

**Костыльное решение**
В конфигах zapret можно выставить меньше 60секунд ожидания и меньше кол-во попыток для понимания, что ресурс не доступен. Чтобы сократить время ожидания.

### Но хотелось бы услышать "правильное решение"

P.S. есть adguardhome на роутере openwrt, также стоит HTTPS DNS Прокси cloudflare и google 5053 и 5054 порт соответственно. В браузере только одно соединение на получение http страницы со статусом pending.
1.1min проходит и chrome роняет соединение с ошибкой ERR_TIMED_OUT

**Comment by bol-van** [comment]
F12 в броузере покажет на каких доменах затык
если на одних и тех же то да, то нет - значит стратегия не устойчива

**Comment by ko22009** [comment]
![Uploading Снимок экрана 2024-08-22 в 11.39.09.png…]()

**Comment by ko22009** [comment]
Происходит на всех заблокированных ресурсах. Браузер сам не обновляет страницу. т.е. три запроса происходит примерно по минуте и страница сама не перезагружается.

**Comment by ko22009** [comment]
Плюс еще провайдер перехватывает ресурс 
http://blocked.mts.ru/?host=?url=http%3A%2F%2Fkinozal.tv%2F&ip=188.114.96.1

**Comment by bol-van** [comment]
autottl работает только на некоторых провайдерах нормально и требует подбора параметров на базе скана множества доменов

autohostlist в принципе так устроен, что будет для нового домена срабатывать не с первого раза
плохо плохо плохо .... занеслось в лист .. пошло дурение

**Comment by bol-van** [comment]
адекватное решение это 
1) разобраться со стратегией
2) разобраться как работает autohostlist
3) для тестов пользоваться не броузером, а curl

для анализа действий autohostlist есть 
# 1 = debug autohostlist positives to ipset/zapret-hosts-auto-debug.log
AUTOHOSTLIST_DEBUGLOG=1

**Comment by ko22009** [comment]
22.08.2024 07:31:07 : bobfilm.net : tcp retrans threshold reached
22.08.2024 07:31:07 : bobfilm.net : fail counter 1/3
22.08.2024 07:31:48 : bobfilm.net : tcp retrans threshold reached
22.08.2024 07:31:48 : bobfilm.net : fail counter 2/3
22.08.2024 07:31:54 : bobfilm.net : tcp retrans threshold reached
22.08.2024 07:31:54 : bobfilm.net : fail counter 3/3
22.08.2024 07:31:54 : bobfilm.net : adding

Сам ресурс кстати отдает: Country not allowed

**Comment by bol-van** [comment]
автохостлист сработал как положено
домен должен появиться в ipset/zapret-hosts-auto.txt

zapret не помогает обойти блокировки со стороны самого ресурса, тк не меняет ip адрес клиента

**Comment by ko22009** [comment]
Еще заметил, что hosts-auto добавляет googlevideo.com с поддоменами, поэтому скорее всего эти прогрузки и возникают. Я так понимаю нужно лично добавить googlevideo.com без поддомена?

Такого вида записи:
rr16---sn-n8v7kn7e.googlevideo.com
rr2---sn-jvhnu5g-n8me.googlevideo.com
rr14---sn-n8v7kn7l.googlevideo.com
rr5---sn-jvhnu5g-n8ml.googlevideo.com
rr7---sn-n8v7znly.googlevideo.com
rr1---sn-jvhnu5g-n8me.googlevideo.com
rr13---sn-n8v7znsr.googlevideo.com

**Comment by ko22009** [comment]
Указал в конфиге GETLIST=get_reestr_preresolved_smart.sh, как понять что отработал?
service zapret restart.

также добавил в zapret-hosts-user.txt
googlevideo.com

**Comment by bol-van** [comment]
оно прыгает по разным GGC
googlevideo.com стоит засунуть в мануальный лист ipset/zapret-hosts-user.txt
потом killall -HUP nfqws

**Comment by bol-van** [comment]
HUP заставляет перечитать не-ауто листы без перезапуска

лист просто так не отрабатывает
чтобы он скачался, надо запустить ipset/get_config.sh
это делает инсталятор и cron
можно руками

**Comment by ko22009** [comment]
т.е. если я вношу новый домен в файл zapret-hosts-user.txt, достаточно killall -HUP nfqws?

**Comment by bol-van** [comment]
так точно

**Comment by ko22009** [comment]
В принципе понятно все стало. спасибо

**Comment by ko22009** [comment]
@bol-van, вопрос еще, если ресурс not_allowed сам пишет, тогда в zapret добавить его лучше в exclude? а через другой vpn проксировать его сразу же.

**Comment by bol-van** [comment]
все не-авто листы перечитываются по HUP. как include, так и exclude
они так же перечитываются по любому изменению авто-листа. не только автолист, а все
и скрипты ipset/get_*.sh , работающие с хостлистами, сами посылают hup

да, придется его проксировать каким-то образом
или из броузера через foxy proxy, или если прозрачно - придется делать полиси роутинг или какую-то схему с xray
