### ISSUE TITLE
Происходит ли в данном случае блокировка по IP для instagram.com?

### ISSUE THREAD

**Issue by NerdzzyDev** [bol-van/zapret#324]
### Описание проблемы:

Добрый день,

Столкнулся с проблемой, связанной с блокировкой доступа к Instagram. Успешно обошел блокировку для всех вебсайтов, но Instagram остается недоступным. Подозреваю, что блокировка происходит на уровне IP-адресов.

Судя по `traceroute`, идет редирект на заглушку Ростелекома:

```
traceroute instagram.com
traceroute to instagram.com (31.13.72.174), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  1.400 ms  1.343 ms  1.350 ms
 2  192.168.100.1 (192.168.100.1)  2.256 ms  2.916 ms  2.296 ms
 3  spbr-bras32.sz.ip.rostelecom.ru (212.48.195.243)  5.533 ms  5.588 ms  5.677 ms
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  *^C
```

Также привожу вывод команды `curl`, который демонстрирует попытку подключения:

```
curl -v instagram.com
* Host instagram.com:80 was resolved.
* IPv6: 2a03:2880:f20a:e5:face:b00c:0:4420
* IPv4: 31.13.72.174
*   Trying 31.13.72.174:80...
*   Trying [2a03:2880:f20a:e5:face:b00c:0:4420]:80...
* Immediate connect fail for 2a03:2880:f20a:e5:face:b00c:0:4420: Network is unreachable
^C
```

Я использовал стратегию, предложенную через `blockcheck.sh`, но, к сожалению, она не помогла разблокировать Instagram. Хотел бы узнать, как лучше справиться с этой проблемой и возможно ли каким-то образом разблокировать доступ к Instagram?

[blockcheck.txt](https://github.com/user-attachments/files/16742332/blockcheck.txt)

Заранее спасибо!

**Comment by NerdzzyDev** [comment]
Роутер: Xiaomi Redmi 4Av2
Провайдер: Ростелеком 
DoT установлен, DNS от cloudflare
Инстаграм выдает верный DNS, а не dns заглушки на сколько я понял

Summary ```
blockchech
```:


`* SUMMARY
ipv4 instagram.com curl_test_http : tpws not working
ipv4 instagram.com curl_test_http : nfqws --dpi-desync=fake --dpi-desync-ttl=5 --dpi-desync-fake-http=0x00000000
ipv4 instagram.com curl_test_https_tls12 : tpws not working
ipv4 instagram.com curl_test_https_tls12 : nfqws --dpi-desync=fake,disorder2 --dpi-desync-ttl=4
ipv4 x.com curl_test_http : working without bypass
ipv4 x.com curl_test_https_tls12 : working without bypass`

**Comment by bol-van** [comment]
FB и инста частично блокированы по IP
zapret не может обойти IP блокировку
может помочь смена DNS , чтобы другой DNS выдавал неблоченые IP
или пропись в hosts неблокированных IP

**Comment by NerdzzyDev** [comment]
Спасибо, а как можно заставить DNS выдавать конкретные - не заблокированные адресса для сайта? 
Через vpn  получаю верный адрес на DNS  8.8.8.8 или 1.1.1.1 (157.240.9.174), а без vpn заблокированный (31.13.72.174)
Если установлю netcat, то получу более правильные обходы блокировок?

**Comment by NerdzzyDev** [comment]
Спасибо, просто поместил в /etc/hosts правильный ip и теперь все работает! Спасибо!

**Comment by all504** [comment]
Приветствую.
Такая же ситуация с inst,
Подскажите, пожалуйста, развернуто что и куда прописать чтобы заработало?

**Comment by NerdzzyDev** [comment]
> Приветствую.
> Такая же ситуация с inst,
> Подскажите, пожалуйста, развернуто что и куда прописать чтобы заработало? 


---
В моём случае, выполнил следующие шаги:

### Шаги:

1. **Проверка соединения с Instagram.com через `ping`:**
   - В  терминале выполните команду:
     ```bash
     ping instagram.com
     ```
   - Если пакеты не доходят, значит доступ к IP-адресу Instagram заблокирован.

2. **Поиск IP-адреса Instagram с помощью `dig`:**
   - Используйте команду `dig`, чтобы получить IP-адреса через DNS-сервер Google:
     ```bash
     dig @8.8.8.8 instagram.com
     ```
   - Проверьте полученные IP-адреса с помощью команды `ping`:
     ```bash
     ping <IP-адрес>
     ```
   - Если пакеты не проходят, значит можно попробовать другие DNS, например 1.1.1.1 - если и это не помогло, то переходим к следующему шагу.

3. **Использование VPN для получения рабочего IP-адреса:**
   - Включите VPN на телефоне или компьютере.
   - Выполните `ping` для домена Instagram:
     ```bash
     ping instagram.com
     ```
   - Если соединение успешно, обратите внимание на IP-адрес в выводе, в моем случае это был `157.240.9.174` - стоит проверить его без подключения vpn
 ```bash
     ping 157.240.9.174
     ```

4. **Редактирование файла `hosts`:**
   - Откройте файл `hosts` для редактирования с правами суперпользователя:
     ```bash
     sudo vim /etc/hosts
     ```
   - Добавьте строки с найденным IP-адресом:
     ```
     157.240.9.174 instagram.com www.instagram.com
     ```
   - Сохраните изменения и выйдите из редактора.

5. **Проверка доступа к Instagram:**
   - Откройте браузер и попробуйте зайти на сайт Instagram.
   - Если доступ восстановлен, значит настройка успешна.

### Резюме:
В этой инструкции вы проверяете доступность Instagram через `ping`, находите рабочий IP-адрес с помощью VPN, и затем добавляете его в файл `hosts` для обхода блокировки.
Пример ping 
![IMG_20240829_134622_367.jpg](https://github.com/user-attachments/assets/c698a21c-35b4-4e27-a87e-af1995aff1b0)

**Comment by all504** [comment]
Спасибо.
Очень подробно, но у меня, как у нуба, второй раз видящего линукс все равно вопросы))
Запрет я ставил на keenetic по инструкции тут, на гитхабе. И все команды вводил в putty.
Ваши команды в путти ничего не дали, видимо, нужно что-то другое?)

**Comment by NerdzzyDev** [comment]
> Спасибо. Очень подробно, но у меня, как у нуба, второй раз видящего линукс все равно вопросы)) Запрет я ставил на keenetic по инструкции тут, на гитхабе. И все команды вводил в putty. Ваши команды в путти ничего не дали, видимо, нужно что-то другое?)

--- 
Ох, так прсото и не объяснить, но попробовать можно. 
1) Подключаемся через putty по ssh - к роутеру по 192.168.1.1 (как в инструкции по keenetic)
2) Пробуем `ping instagram.com` (если получаем ситуацию, как на фото, что все пакеты потеряны, то переходим к следующему шагу)
3) `ping 157.240.9.174` (если пакеты идут, как на скрине, то выполняем шаг 4)

Если что-то не выходит, то пример вывода или ошибки тут же

**Comment by M-A-M-B-A** [comment]
> 157.240.9.174 instagram.com www.instagram.com

Это работает! Спасибо! 
Вопрос - как найти не заблокированные ip И куда их добавить для стратегий

**Comment by NerdzzyDev** [comment]
> > 157.240.9.174 instagram.com www.instagram.com
> 
> Это работает! Спасибо! 
> Вопрос - как найти не заблокированные ip И куда их добавить для стратегий

Рад, что смог помочь - это не для стратегии, т.к. в данном случае мы не используем zapret. 

Ip ищется с помощью подключения к необходимому сайту через vpn/proxy. 

Т.е. провайдер блокирует диапазоны ip адрессов определенного сайта, в странах, где данный сайт не заблокирован выдаются другие адреса. (Актуально только для крупных сайтов)

Мы делаем запись в файле hosts на роутере, чтобы устройства подключенные к роутеру получали ip адрес не от провайдера, а указанный нами в файле hosts. В связи с чем обходим блокировку по ip адресу, а в данном случае zapret  помогает обходить блокировку по заголовкам запросов. 

P.s. Очень упрощённое и не совсем точное объяснение :)

**Comment by NerdzzyDev** [comment]
> > 157.240.9.174 instagram.com www.instagram.com
> 
> Это работает! Спасибо! 
> Вопрос - как найти не заблокированные ip И куда их добавить для стратегий

Если работает данный IP, то выполнить только пункт 4 и сбросить DNS cache

**Comment by NerdzzyDev** [comment]
> а для виндовс можно тоже самое сделать?

https://github.com/bol-van/zapret/discussions/338

Посмотрите данное обсуждение

**Comment by MrJek** [comment]
столкнулся в новой проблемой игстаграм заработал но требует авторизоваться через Сайт www.fbsbx.com (Подтвердите, что это вы), а тут походу сработала блокировка фейсбука, подскажите пожалуста рабочий айпи для фейсбука, для инстаграмма прописал это:
#instagram
157.240.9.174 instagram.com
157.240.9.174 www.instagram.com
157.240.9.174 graph.instagram.com
157.240.9.174 api.instagram.com
157.240.9.174 instagram.c10r.instagram.com
157.240.9.174 static.cdninstagram.com
157.240.9.174 scontent.cdninstagram.com
