### ISSUE TITLE
Помогите доработать скрипт под nfqws

### ISSUE THREAD

**Issue by ivdeveloper86** [bol-van/zapret#329]
Привет!

Пытаюсь сделать скрипт обхода блокировки для телека LG, который видимо работает через QUIC протокол.
До этого удалось завести его через tpws с параметром --mss=88, но есть проблемы со скоростью работы.

```
#!/bin/sh

SCRIPT=/tmp/mnt/DPI/zapret-master/nfq/nfqws
PIDFILE=/var/run/tpwsTV.pid
HOSTLISTFILE=/tmp/mnt/DPI/zapret-master/hostlist.txt
DVTWS="--daemon --qnum=200 --dpi-desync=fake,split2 --dpi-desync-any-protocol=1 --dpi-desync-repeats=6 --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service TPWS is already running' >&2
    return 1
  fi
  $SCRIPT $DVTWS
  iptables -t mangle -I POSTROUTING -s 192.168.1.82 -p tcp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
  iptables -t mangle -I POSTROUTING -s 192.168.1.82 -p udp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
  echo 'Started TPWS service'
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service TPWS is not running' >&2
    return 1
  fi
  echo 'Stopping TPWS service...'
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  iptables -t mangle -D POSTROUTING -s 192.168.1.82 -p tcp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
  iptables -t mangle -D POSTROUTING -s 192.168.1.82 -p udp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
}

status() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service TPWS is running'
  else
    echo 'Service TPWS is stopped'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
```

Из других тем понял, что нужны параметры --dpi-desync=fake,split2 --dpi-desync-repeats=6, но только с ними на телеке ничего не прогружается :( Так же не очень уверен в правильности маршрутизации iptables.
* 192.168.1.82 ИП телека прописанный статикой

**Comment by bol-van** [comment]
Вы просто копировали туда-сюда параметры без понимания их сути ?

DVTWS="--daemon --qnum=200 --dpi-desync=fake,split2 --dpi-desync-any-protocol=1 --dpi-desync-repeats=6 --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

Означает, что dvtws будет насиловать _каждый_ исходящий пакет. Причем по 6 раз.
Причем без ограничителя на fake, так что tcp фейки будут доходить до сервера и ломать _любое_ соединение с гарантией _100_ %
Действительно это то, что нужно ?

**Comment by ivdeveloper86** [comment]
Нужно сделать правильно) Вы можете написать как нужно?

**Comment by bol-van** [comment]
По стратегии это надо подбирать индивидуально
по https и quic надо 2 демона nfqws с разными параметрами и номерами очереди, поправить номера в iptables

для quic обычно "--dpi-desync=fake --dpi-desync-repeats=6"
для https "--dpi-desync=fake,split2 --dpi-desync-ttl=X --dpi-desync-fooling=md5sig"
ttl подбирать исходя из блокчека на рутракер

**Comment by ivdeveloper86** [comment]
а что за номера в iptables, имеется ввиду очередь --queue-num?

**Comment by bol-van** [comment]
да, queue-num
приоритет здесь ни при чем.
есть выбор номера ведра, в которое лить трафик исходя из фильтра iptables

**Comment by ivdeveloper86** [comment]
ок вроде разобрался
последний вопрос, в iptables обязательно указывать внешний_интерфейс?
`iptables -t mangle -I POSTROUTING -o <внешний_интерфейс>`

или с локальным ИП тоже должно работать?
`iptables -t mangle -I POSTROUTING -s 192.168.1.82`

**Comment by bol-van** [comment]
Желательно указывать
Во избежание крайне маловероятных, но теоретически возможных вариантов

**Comment by olegazyx** [comment]
Приведите свой итоговой скрипт, пожалуйста

**Comment by ivdeveloper86** [comment]
Короче так ничего и не работает через nfqws

Для HTTPS
```
#!/bin/sh

SCRIPT=/tmp/mnt/DPI/zapret-master/nfq/nfqws
PIDFILE=/var/run/nfqwsHTTPS.pid
HOSTLISTFILE=/tmp/mnt/DPI/zapret-master/hostlist.txt
DVTWS="--daemon --qnum=200 --dpi-desync=fake,split2 --dpi-desync-ttl=4 --dpi-desync-fooling=md5sig --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service NFQWS is already running' >&2
    return 1
  fi
  $SCRIPT $DVTWS
  iptables -t mangle -I POSTROUTING -o br0 -p tcp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
  echo 'Started NFQWS service'
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service NFQWS is not running' >&2
    return 1
  fi
  echo 'Stopping NFQWS service...'
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  iptables -t mangle -D POSTROUTING -o br0 -p tcp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
}

status() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service NFQWS is running'
  else
    echo 'Service NFQWS is stopped'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
```

Для QUIC
```
#!/bin/sh

SCRIPT=/tmp/mnt/DPI/zapret-master/nfq/nfqws
PIDFILE=/var/run/nfqwsQUIC.pid
HOSTLISTFILE=/tmp/mnt/DPI/zapret-master/hostlist.txt
DVTWS="--daemon --qnum=210 --dpi-desync=fake --dpi-desync-repeats=6 --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service NFQWS is already running' >&2
    return 1
  fi
  $SCRIPT $DVTWS
  iptables -t mangle -I POSTROUTING -o br0 -p udp --match multiport --dport 80,443 -j NFQUEUE --queue-num 210 --queue-bypass
  echo 'Started NFQWS service'
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service NFQWS is not running' >&2
    return 1
  fi
  echo 'Stopping NFQWS service...'
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  iptables -t mangle -D POSTROUTING -o br0 -p udp --match multiport --dport 80,443 -j NFQUEUE --queue-num 210 --queue-bypass
}

status() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service NFQWS is running'
  else
    echo 'Service NFQWS is stopped'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
```

Для HTTPS могу вернуть обратно вариант с tpws там где редирект на порт, на компе так работает.
Но главная задача починить телек и там так же ничего не пашет :(
Что не так в скриптах?

**Comment by bol-van** [comment]
Если правила создаются, демоны запускаются, значит скорее всего стратегия не работает
Проверить отрабатывает ли nfqws можно через --debug (см описание этой опции в readme)

**Comment by ivdeveloper86** [comment]
Да, наверное дело именно в TLS 1.2 т.к. через дробление пакетов TCP параметром mss=88 все работает. Значит обход замедления через QUIC тут не нужен.
Я так понимаю кроме как mss других альтернатив нет?

**Comment by ivdeveloper86** [comment]
Под альтернативой в имеете ввиду подбор конфига для nfqws?

**Comment by bol-van** [comment]
Гадать - это всегда плохо.
Вместо этого надо пробовать тестировать через curl с tls 1.2

Тут есть готовые команды, в т.ч. для 1.2
https://github.com/bol-van/zapret/discussions/200

**Comment by ivdeveloper86** [comment]
Почитал ваши рекомендации, попробовал разные варианты, метод NFQWS не работает у меня ни на компе ни на телеке, вообще глухо.

Пробовал такие варианты (хотя на самом деле больше):
--dpi-desync=fake,disorder2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig
--dpi-desync=fake,disorder2 --dpi-desync-autottl --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig --hostspell=hoSt
--dpi-desync=fake,split2 --dpi-desync-autottl --dpi-desync-split-pos=1 --wssize 1:6 --dpi-desync-fooling=md5sig
--dpi-desync=fake,disorder2 --dpi-desync-autottl --dpi-desync-split-pos=1 --wssize 1:6 --dpi-desync-fooling=md5sig
--dpi-desync=fake,split2 --dpi-desync-autottl --dpi-desync-fooling=md5sig
--dpi-desync=fake,disorder2 --dpi-desync-autottl --wssize 1:6 --dpi-desync-fooling=md5sig
--dpi-desync=fake,disorder2 --dpi-desync-autottl --dpi-desync-fooling=md5sig

Не понял что можно тестить в curl, там все по нулям на любом конфиге:
![02](https://github.com/user-attachments/assets/e55ff19f-274c-4c59-962c-58293fe9eb1d)

Ну и в браузере:
![03](https://github.com/user-attachments/assets/d4fe6c26-60bc-4f59-b9ef-34f28c46f151)

**Comment by bol-van** [comment]
Судя по скрину похоже, что происходит зависание соединения. То есть заблокировано полностью

curl  --tls-max 1.2 -v4s -o/dev/null -k --connect-to ::google.com -H Host:\ metsalehti-staging-s4uzwwd6nq-lz.a.run.app https://test.googlevideo.com/app/uploads/2021/11/2022-mediakortti.pdf -w %{speed_download}

вместо test.googlevideo.com можно вставлять другие домены, незаблокированные. на незаблокированных нормально скачивается ?

надо проверять nfqws с --debug работает ли вообще редирект

на счет мерлина я не знаю, никогда не пользовался

**Comment by ivdeveloper86** [comment]
Проверил на незаблокированном домене, скорость вроде норм
![01](https://github.com/user-attachments/assets/35629596-19d8-4114-b0dd-a143196b677c)
![02](https://github.com/user-attachments/assets/9ef40366-8dc7-40f8-91c5-e8eb6ec1ebec)

Аппаратное ускорение и QoS выключены
![05](https://github.com/user-attachments/assets/a1d79e34-fc31-4e41-9999-73df33d807dd)
![04](https://github.com/user-attachments/assets/73096274-bb93-45e4-9904-78eb14ab4ece)

ТипNAT стоял Симметричный, поменял на Fullcone, но без изменений

**Comment by ivdeveloper86** [comment]
Прописал дебаг
`DVTWS="--debug --daemon --qnum=200 --dpi-desync=fake,disorder2 --dpi-desync-autottl --dpi-desync-fooling=md5sig --pidfile $PIDFILE --hostlist $HOSTLISTFILE"`

Но что-то так и не понял как он должен выводиться?

**Comment by bol-van** [comment]
См документацию по ключу debug

**Comment by ivdeveloper86** [comment]
Похоже чего-то не хватает для работы nftables:
![01](https://github.com/user-attachments/assets/703820ce-3053-46c8-bc5b-2e27acdca7b1)

Хотя по инструкции quick_start.txt я установил компоненты:
![02](https://github.com/user-attachments/assets/ae843379-0bc6-4756-b4e4-1db1daf86f1f)

Пишет вручную установить : curl nft
Можете подсказать как это сделать?

**Comment by bol-van** [comment]
Прошивка не поддерживается
Любые изыскания - на пользователя
