### ISSUE TITLE
Socks5 на Windows

### ISSUE THREAD

**Issue by sanek184** [bol-van/zapret#330]
Приветствую. Есть ли возможность реализовать запуск на Windows в socks5 ? Чтобы не на весь трафик фрагментировать пакеты.
Спасибо.

**Comment by bol-van** [comment]
tpws под WSL работает, см в docs/windows.txt особенности

**Comment by sanek184** [comment]
> tpws под WSL работает, см в docs/windows.txt особенности

Установил, только подскажите пожалуйста в прописывании "способа дурения" что написать вместо --wf-tcp=80,443 ?

**Comment by bol-van** [comment]
такую стратегию средствами  tpws   не сделать
но можно оставить winws,  а tpws использовать как сокс без параметров дурения
или взять любой виндовый прокси сервер
это сработает, если использоваться будет с другой системы
можно виртуалку поднять с минимальным linux
