### ISSUE TITLE
zapret.service autostart is not working

### ISSUE THREAD

**Issue by AntonSamokat** [bol-van/zapret#333]
Environment: Ubuntu 20.04
After system reboot `zapret.service` automatically does not start and must be re-installed with `install_easy.sh` to start.
I have not found information about auto start in `readme`.

I've noticed related discussions in the following issues but without solutions:
- [Установка на Ubuntu 18.04 · Issue #26](https://github.com/bol-van/zapret/issues/26)
- [как программу полностью удалить? перезаписывает ли программа какие-нибудь системные или пользовательские файлы в /home? можно ли сделать flatpak чтобы можно было легко накатить на любой дистрибутив и легко удалить? · Issue #77](https://github.com/bol-van/zapret/issues/77)
- [Слетают настройки после перезагрузки роутера. · Issue #245](https://github.com/bol-van/zapret/issues/245)
- [Ломается L4 после отключения/удаления zapret · Issue #289](https://github.com/bol-van/zapret/issues/289)
---
Probably this is not supposed to be implemented. Below I will share my solution.

- Very important! Add iptables, nfqws, tpws, install_easy.sh to `sudoers` list. Otherwise, system will not log in (in standard GUI mode) under the current user after reboot (system will hang and not boot). Password prompt without user interactive mode hangs booting process. I do not know but may be this behavior is Ubuntu bug.
```shell
username ALL=NOPASSWD: /usr/sbin/iptables
username ALL=NOPASSWD: /opt/zapret/nfq/nfqws
username ALL=NOPASSWD: /opt/zapret/tpws/tpws
username ALL=NOPASSWD: /opt/zapret/install_easy.sh
```
- Very important! Check that `iptables` is working without requiring the password: `sudo iptables -L`. 
- Just in case create a second user with root rights. If there is problem with logging in under the main user, log in under the second user. Use terminal and `su main_user_name` to undo the changes.
- Add needed configuration for `iptables` and running of `install_easy.sh` in `~/.profile`. I have the following:
```shell
# !!! In case of adding sudo need to add corresponding command to sudoers list. Otherwise login to the system will not be possible by GUI!!!
# NFQUEUE iptable rule for zapret  # adds iptable rule only if it is not exist
rule="OUTPUT -o usb0 -p tcp --dport 443 -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:6 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass"
sudo iptables -C $rule >/dev/null 2>&1 || { 
    sudo iptables -I $rule
    echo "Added NFQUEUE IP table rule to OUTPUT filter table. Check it with: sudo iptables -L --line-number" 
}

systemctl status zapret >/dev/null 2>&1  # zapret service
result=$?  #  0 - enabled and started; 3 - exists; 4 - not found
echo "zapret service status exit code: $result"
if [[  $result -eq 4 ]]; then echo 'installing service...'; printf "\n" | sudo /opt/zapret/install_easy.sh >/dev/null 2>&1; echo 'zapret service installed'; else echo 'zapret service already exist'; fi
```

The first command creates specified iptable rule only if it is not exist.
The second command runs `install_easy.sh` with default settings which starts `zapret.service` only if this service is not exist (and it is not exist after system reboot).

May be it will be better to use Ubuntu's `Startup Applications` to run needed startup script, not `~/.profile` config.

Если что обсуждение можно вести на русском.

**Comment by bol-van** [comment]
Никто в здравом уме не будет делать это с sudoers. Разве что на очень домашней и никому не нужной больше системе.

На счет скрипитов - скрипты zapret сами добавляют iptables.
Если это какая-то самописка (служба zapret), то причин не-авто-запуска может быть много.
Мы рассматривает автозапуск в оригинальном варианте через скрипты zapret ? какие настройки ? nfqws/tpws, iptables/nftables ?
systemctl status zapret   после перезапуска

**Comment by AntonSamokat** [comment]
@bol-van Делал стандартную установку с помощью скрипта install_easy.sh
Ниже лог повторной переустановки с выбором дефолтных уже предзаполненных на основе первой установки параметров:

```
sudo ./install_easy.sh 
* checking system
system is based on systemd
* checking executables
found architecture "x86_64"
* checking privileges
* checking readonly system
* checking location
running from /opt/zapret
* checking DNS
system DNS is working
* checking virtualization
running on bare metal
* stopping zapret service
Removed /etc/systemd/system/z.service.
Removed /etc/systemd/system/zapret.service.
Removed /etc/systemd/system/multi-user.target.wants/zapret.service.

select firewall type :
1 : iptables
2 : nftables
your choice (default : iptables) : 
selected : iptables
* checking prerequisites
required utilities exist : curl ip6tables ipset iptables
* installing binaries
x86_64 is OK
installing binaries ...
linking : ../binaries/x86_64/ip2net => /opt/zapret/ip2net
linking : ../binaries/x86_64/mdig => /opt/zapret/mdig
linking : ../binaries/x86_64/nfqws => /opt/zapret/nfq
linking : ../binaries/x86_64/tpws => /opt/zapret/tpws

enable ipv6 support (default : N) (Y/N) ? 

select MODE :
1 : tpws
2 : tpws-socks
3 : nfqws
4 : filter
5 : custom
your choice (default : nfqws) : 
selected : nfqws

NFQWS_OPT_DESYNC="--qnum=200 --dpi-desync=disorder2 --dpi-desync-split-pos=1 --hostlist=/opt/zapret/youtube-domain.txt"
NFQWS_OPT_DESYNC_HTTP=""
NFQWS_OPT_DESYNC_HTTPS=""
NFQWS_OPT_DESYNC_HTTP6=""
NFQWS_OPT_DESYNC_HTTPS6=""
NFQWS_OPT_DESYNC_QUIC=""
NFQWS_OPT_DESYNC_QUIC6=""
do you want to edit the options (default : N) (Y/N) ? 
select WAN interface for nfqws operations. select ANY to operate on any interface.
WAN interface :
1 : ANY
2 : ap0
3 : docker0
4 : enp0s25
5 : lo
6 : usb0
7 : virbr0
8 : virbr0-nic
9 : wlp3s0
your choice (default : usb0) : 
selected : usb0

enable http support (default : Y) (Y/N) ? 

enable keep alive support only if DPI checks every outgoing packet for http signature
dont enable otherwise because it consumes more cpu resources
enable http keep alive support (default : N) (Y/N) ? 

enable https support (default : Y) (Y/N) ? 

enable quic support (default : N) (Y/N) ? 

select filtering :
1 : none
2 : ipset
3 : hostlist
4 : autohostlist
your choice (default : none) : 
selected : none
* installing zapret service
Created symlink /etc/systemd/system/multi-user.target.wants/zapret.service → /opt/zapret/init.d/systemd/zapret.service.
Created symlink /etc/systemd/system/zapret.service → /opt/zapret/init.d/systemd/zapret.service.
* downloading blocked ip/host list
setting high oom kill priority
clearing all known DNS caches
DNS is working
digging 6 ipv4 domains : /opt/zapret/ipset/zapret-hosts-user-exclude.txt
mdig stats : 00:00:00 : domains=6 success=4 error=2
digging 0 ipv4 domains : /opt/zapret/ipset/zapret-hosts-user-ipban.txt
mdig stats : 00:00:00 : domains=0 success=0 error=0
setting high oom kill priority
reloading ipset backend (forced-update)
Adding to ipset ipban : /opt/zapret/ipset/zapret-ip-user-ipban.txt
Adding to ipset nozapret : /opt/zapret/ipset/zapret-ip-exclude.txt
* installing zapret-list-update timer
Removed /etc/systemd/system/timers.target.wants/zapret-list-update.timer.
Removed /etc/systemd/system/zapret-list-update.timer.
Created symlink /etc/systemd/system/timers.target.wants/zapret-list-update.timer → /opt/zapret/init.d/systemd/zapret-list-update.timer.
Created symlink /etc/systemd/system/zapret-list-update.timer → /opt/zapret/init.d/systemd/zapret-list-update.timer.
* starting zapret service

press enter to continue
```

```
$ systemctl status zapret
● zapret.service
     Loaded: loaded (/etc/systemd/system/zapret.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-08-30 22:16:20 MSK; 1min 37s ago
    Process: 207291 ExecStart=/opt/zapret/init.d/sysv/zapret start (code=exited, status=0/SUCCESS)
      Tasks: 1 (limit: 8971)
     Memory: 436.0K
     CGroup: /system.slice/zapret.service
             └─207317 /media/user/data_system/opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --qnum=200 --dpi-desync=disorder2 --dpi-desync-split-pos=1 --hostlist=/opt/zapret/youtube-domain.txt

авг 30 22:16:20 comp systemd[1]: Starting zapret.service...
авг 30 22:16:20 comp zapret[207291]: Starting daemon 1: /media/user/data_system/opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --qnum=200 --dpi-desync=disorder2 --dpi-desync-split-pos=1 --hostlist=/opt/zapret/youtube-domain.txt
авг 30 22:16:20 comp zapret[207291]: Applying iptables
авг 30 22:16:20 comp zapret[207291]: Creating ip list table (firewall type iptables)
авг 30 22:16:20 comp zapret[207318]: setting high oom kill priority
авг 30 22:16:20 comp zapret[207318]: reloading ipset backend (no-update)
авг 30 22:16:20 comp zapret[207291]: Adding iptables rule for nfqws postrouting (qnum 200) :  -p tcp -m multiport --dports 80,443 -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:6 -m mark ! --mark 0x40000000/0x40000000
авг 30 22:16:20 comp zapret[207291]: Adding iptables rule for nfqws input+forward (qnum 200) :  -p tcp -m multiport --sports 80,443 -m connbytes --connbytes-dir=reply --connbytes-mode=packets --connbytes 1:1
авг 30 22:16:20 comp systemd[1]: Started zapret.service.
```

После ребута системы команда `systemctl status zapret` говорит, что службы zapret не существует. Поэтому приходится каждый раз запускать повторную установку. Система: Ubuntu 20.04.

**Comment by AntonSamokat** [comment]
By now work around with reinstalling zapret service (to run it) moved to `run-zapret` script and added it to `Startup Applications` list. Removed from it iptables updating since it is already done when zapret service is running.
```
cat run-zapret
#!/bin/bash
systemctl status zapret >/dev/null 2>&1  # zapret service
result=$?  #  0 - enabled and started; 3 - exists; 4 - not found
echo "zapret service status exit code: $result"
if [[ $result -eq 4 ]]; then echo 'installing service...'; printf "\n" | sudo /opt/zapret/install_easy.sh >/dev/null 2>&1; echo 'zapret service installed'; else echo 'zapret service already exist'; fi
```

**Comment by bol-van** [comment]
это костыли

см ls -la /lib/systemd/system/zapret.service

после инсталл он есть ?
после ребута ?

**Comment by makerbeleg** [comment]
Проблема иммет место быть. 

```
ls -la /lib/systemd/system/zapret.service
lrwxrwxrwx 1 root root 41 Aug 13 14:13 /lib/systemd/system/zapret.service -> /opt/zapret/init.d/systemd/zapret.service
```

```
sudo systemctl status zapret
Unit zapret.service could not be found.
```

```
sudo systemctl start zapret
Failed to start zapret.service: Unit zapret.service not found.
```

Решается sudo systemctl daemon-reload. После этого все запускается.

**Comment by bol-van** [comment]
после каждого ребута надо daemon-reload ?

**Comment by makerbeleg** [comment]
Да, все верно. После каждого ребута приходится запускать daemon-reload. Или запускать install_easy.sh

**Comment by bol-van** [comment]
на debian sid все норм
пока на других проверить не могу
можете проверить на чистой системе ?

**Comment by makerbeleg** [comment]
На свежем манжаро в вм работает без проблем.

Очевидно, проблема что opt у меня на отдельном разделе, что systemd [не любит](https://github.com/systemd/systemd/issues/8307).

Скопировал юнит файлы, у меня проблема решена.

**Comment by AntonSamokat** [comment]
@makerbeleg у меня всё тоже самое — /opt на отдельном разделе. Как вы сделали перенос? Всю папку с zapret на root раздел? Или /opt/zapret/init.d, или /opt/zapret/init.d/systemd?
В какую директорию перенесли? /usr/local/bin? /usr/local/share?

**Comment by AntonSamokat** [comment]
@bol-van перенёс zapret из /opt (который у меня на отдельном разделе) в /usr/local/share (на рут разделе), пытаюсь выполнить `install_easy.sh` оттуда:
```
$ ./install_easy.sh 
* checking system
system is based on systemd
* checking executables
found architecture "x86_64"
* checking privileges
root is required
* checking system
system is based on systemd
* checking executables
found architecture "x86_64"
* checking privileges
* checking readonly system
* checking location

easy install is supported only from default location : /opt/zapret
currently its run from /usr/local/share/zapret
do you want the installer to copy it for you (default : N) (Y/N) ?
```

Что-то порекомендуете?

**Comment by bol-van** [comment]
после инсталла надо
cp -f /opt/zapret/init.d/systemd/* /lib/systemd/system
systemctl daemon-reload
 но следующий прогон инсталл опять линки насоздает

**Comment by makerbeleg** [comment]
@AntonSamokat ничего переносить не надо. скопировать юнит файлы из /opt/zapret/init.d/systemd/ в /etc/systemd/system/, вместо существующих там линков.

**Comment by AntonSamokat** [comment]
@bol-van 
@makerbeleg 
После ребута zapret не взлетел, /opt/zapret/init.d тоже не видит:
```
sudo systemctl status zapret
● zapret.service
     Loaded: loaded (/lib/systemd/system/zapret.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-09-06 12:31:31 MSK; 1min 22s ago
    Process: 2600 ExecStart=/opt/zapret/init.d/sysv/zapret start (code=exited, status=203/EXEC)

сен 06 12:31:31 sam systemd[1]: Starting zapret.service...
сен 06 12:31:31 sam systemd[2600]: zapret.service: Failed to execute command: No such file or directory
сен 06 12:31:31 sam systemd[2600]: zapret.service: Failed at step EXEC spawning /opt/zapret/init.d/sysv/zapret: No such file or directory
сен 06 12:31:31 sam systemd[1]: zapret.service: Control process exited, code=exited, status=203/EXEC
сен 06 12:31:31 sam systemd[1]: zapret.service: Failed with result 'exit-code'.
сен 06 12:31:31 sam systemd[1]: Failed to start zapret.service.
```
После ручного выполенения `sudo systemctl restart zapret`, служба запустилась успешно. 
Позже попробую перенести ещё весь /opt/zapret/init.d например в /usr/local/etc/init.d . После ребута отпишусь.

**Comment by makerbeleg** [comment]
Оставьте весь zapret на opt как было. Перенесите только .service файлы из /opt/zapret/init.d/systemd/ в /etc/systemd/system/ или /lib/systemd/system

**Comment by AntonSamokat** [comment]
@makerbeleg у меня сейчас проблема в том, что `systemd/zapret.service` для своего старта использует `/opt/zapret/init.d/sysv/zapret`, который в свою очередь использует другие файлы в /opt/zapret`. Странно, что у вас не произолшла аналогичная проблема. По идее должна была. Нужно либо тащить весь запрет на рут раздел. Либо откладывать его старт до того как другой раздел будет готов.

**Comment by makerbeleg** [comment]
Из /lib/systemd/system у меня сейчас тоже не запустилось. Попробуйте скопировать юнит файлы в /etc/systemd/system/

**Comment by bol-van** [comment]
systemctl enable zapret
создает линки в /etc/systemd/system

**Comment by bol-van** [comment]
если /opt на другом разделе, надо чтобы unit запускался после монтирования
если монтируется через fstab, должно работать
на основной раздел копируется только юнит

**Comment by AntonSamokat** [comment]
Я понял в чём у меня проблема. /opt находится на отдельном зашфрованном разделе, который становится доступен только после логина пользователя.

Попробовал поставить зависимость старта сервиса от доступности раздела:
```
systemctl list-units --type=mount

sudo systemctl edit --full z

[Unit]
After=network-online.target media-sunkrop-data_system.mount
Requires=media-sunkrop-data_system.mount
```
Как рекомендовано здесь:
debian - Set systemd service to execute after fstab mount - Unix & Linux Stack Exchange
https://unix.stackexchange.com/questions/246935/set-systemd-service-to-execute-after-fstab-mount

Ошибка стала чуть другой, но суть осталась:
```
scs z
● zapret.service
     Loaded: loaded (/etc/systemd/system/zapret.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-09-07 10:52:40 MSK; 26s ago
    Process: 2633 ExecStart=/opt/zapret/init.d/sysv/zapret start (code=exited, status=203/EXEC)

сен 07 10:52:40 sam systemd[1]: Starting zapret.service...
сен 07 10:52:40 sam systemd[1]: zapret.service: Control process exited, code=exited, status=203/EXEC
сен 07 10:52:40 sam systemd[1]: zapret.service: Failed with result 'exit-code'.
сен 07 10:52:40 sam systemd[1]: Failed to start zapret.service.
```
Пробовать починить эту ошибку по рекомендациям ниже пока не стал:
ubuntu - Start systemctl service on user login - Unix & Linux Stack Exchange
https://unix.stackexchange.com/questions/334044/start-systemctl-service-on-user-login

linux - How to start a systemd service after user login and stop it before user logout - Super User
https://superuser.com/questions/1037466/how-to-start-a-systemd-service-after-user-login-and-stop-it-before-user-logout/1269158

raid - Start a systemd service after a device has been mounted - Super User
https://superuser.com/questions/930798/start-a-systemd-service-after-a-device-has-been-mounted

Systemd Service Failing with exit-code status=203/EXEC - Unix & Linux Stack Exchange
https://unix.stackexchange.com/questions/664811/systemd-service-failing-with-exit-code-status-203-exec

---

Смысла в этом не вижу потому что хочу, чтобы zapret сервис был доступен до того как какой-нибудь пользователь залогинится и тем самым расшифрует и смонтирует дополнительный раздел с /opt, как это происходит с другими службами.

Адекватный вариант решения проблемы у меня здесь получается только один — перенести инсталяцию с zapret на рут раздел. 

Ограничение
```
easy install is supported only from default location : /opt/zapret
currently its run from /usr/local/share/zapret
do you want the installer to copy it for you (default : N) (Y/N) ?
```
можно отменить изменив
ZAPRET_TARGET=/opt/zapret
в install_easy.sh на
ZAPRET_TARGET=/usr/local/share/zapret

Проверю что получится

**Comment by bol-van** [comment]
не выйдет без изменения юнитов, включая тот, что работает под таймером
скрипты хотят ZAPRET_BASE
его надо задавать в юнитах
и там же заменить захардкоденый /opt
так же надо будет его задавать при запуске любых скриптов из терминала

**Comment by AntonSamokat** [comment]
Теперь порядок — служба нормально запускается до логина. Теперь zapret можно использовать в связке с сервисом из [linux-wifi-hotspot](https://github.com/lakinduakash/linux-wifi-hotspot) что позволяет превратить ноут в роутер.

Что сделал. Остановил и выключил службу zapret. Скопировал /opt/zapret в /usr/local/share/zapret. Изменил во всех файлах путь с /opt/zapret на /usr/local/share/zapret. Выполнил install_easy.sh.

Описание в виде команд:
```
# copy zapret files to root partition
sudo cp -a /opt/zapret /usr/local/share/

# check /opt/zapret usages in all /opt/zapret files:
grep -r /opt/zapret /usr/local/share/ | less
config:#TMPDIR=/opt/zapret/tmp
config:NFQWS_OPT_DESYNC="--qnum=200 --dpi-desync=disorder2 --dpi-desync-split-pos=1 --hostlist=/opt/zapret/youtube-domain.txt"
config.default:#TMPDIR=/opt/zapret/tmp
docs/readme.eng.md:The file `/opt/zapret/config` is used by various components of the system and contains basic settings.
docs/readme.eng.md:TMPDIR=/opt/zapret/tmp
...

# turn off zapret service before making changes
sudo systemctl stop zapret
sudo systemctl disable zapret

# replace in all zapret files located in /usr/local/share/zapret '/opt/zapret' to '/usr/local/share/zapret':
grep -l -r /opt/zapret /usr/local/share/zapret | sudo xargs sed -i 's/\/opt\/zapret/\/usr\/local\/share\/zapret/g'

# just in case for rallback: 
# grep -l -r /usr/local/share/zapret /usr/local/share/zapret | sudo xargs sed -i 's/\/usr\/local\/share\/zapret/\/opt\/zapret/g'

#check result:
grep -r /usr/local/share/zapret /usr/local/share/zapret | less

# /opt/zapret can be removed:
sudo mv /opt/zapret /opt/zapret-bak
```

Предлагаю также почнить это в базовой версии zapret, чтобы другие не спотыкались на этой проблеме:
- По умолчанию использовать директорию, которая точно будет на руте, например, /usr/local/share/zapret, потому что /opt — это директория, в которую устанавливаются опциональные приложения, т.е. которые не критичны для основной работы системы. В связи с этим /opt может находиться на отдельном разделе. А отдельный раздел может быть зашифрован.
- Не ограничивать пользователя в какой-то одной конкретной директории, не зашиваться на неё. Если он хочет установить zapret в /opt — пусть будет такая возможность тоже.

**Comment by bol-van** [comment]
на традиционных линухах планирую так сделать
но на прошивках с r/o корнем /usr - точно не вариант
/opt предназначен для софта, который не должен интегрироваться и размазываться по системе. тк идеология в разных дистрах и прошивках может быть разной
тратить усилия не поддержку дистрибутивов желания нет

вопрос тут вот в чем
скрипты из zapret  достаточно хорошо адаптированы к смене локации
но вопрос в точке привязки к системе
система что-то вызывает. будь то автостарт или хук сетевых интерфейсов
это вызываемое нечто должно узнать где основные файлы
нет общего универсального места, куда эту инфу можно положить
придется генерить в инсталяторе куски кода автозапуска

**Comment by AntonSamokat** [comment]
Чтобы сделать универсальное решение и не заморачиваться с поддержкой разных дистрибутивов, можно:
- оставить /opt/zapret в качестве директории по умолчанию 
- дать возможность пользователю выбирать директорию для установки
- в документации пояснить нюансы связанные с выбором директории
С одной стороны — это упростит вам поддержку, а с другой — позволит пользователям более гибко кастомизировать решение под себя.
