### ISSUE TITLE
Проблемы с nfqws

### ISSUE THREAD

**Issue by HanabishiRecca** [bol-van/zapret#34]
В общем на роутере с openwrt пытаюсь поднять обход. На винде через GoodbyeDPI с опцией -e 40 все работает ок. А на роутере через nfqws --wsize=40 нет. Непонятно почему, ведь по идее механизм работы у обеих софтин одинаковый - через установку tcp window size.
Правило фильтра вроде работает верно, в iptables видно, что через него идут пакеты. И в самом приложении они тоже отображаются.
![изображение](https://user-images.githubusercontent.com/13597663/59151223-d78aff80-8a48-11e9-8264-3b253763c493.png)
Но вот смущает, что у них len не меняется (хотя хз, возможно так и должно быть). Есть идеи?

**Comment by HanabishiRecca** [comment]
Провел даже небольшое сравнение исходников
https://github.com/bol-van/zapret/blob/5da170f28ae96771e594bf6e04977c12856da20b/nfq/nfqws.c#L215
https://github.com/ValdikSS/GoodbyeDPI/blob/2b3e4a46833a3b566553192969b50ae1d3a170aa/src/goodbyedpi.c#L312

Непонятно почему в одном случае работает, а в другом нет.

**Comment by HanabishiRecca** [comment]
Все, разобрался в чем проблема.
1) Отключаем Hardware NAT Offload, иначе пакеты уже установленного соединения просто не попадают на фильтрацию
2) Правило все же слегка корявое, надо вот так:
`iptables -t mangle -A FORWARD -p tcp --sport 443 --tcp-flags SYN,ACK SYN,ACK -j NFQUEUE --queue-num 200 --queue-bypass`
В случае с роутером принципиально, чтобы правило находилось в FORWARD (так как ловим транзитный трафик). Плюс я не принял во внимание, что пакеты SYN,ACK входящие, а значит и порт нужно проверять через sport.

**Comment by bol-van** [comment]
Правило не корявое, это вы что-то недопоняли
в raw/PREROUTING попадает все входящее, неважно потом куда оно попадет - в INPUT или в FORWARD
у меня в скриптах еще применяется фильтр на входящий интерфейс
пакеты для модификации wsize нужно ловить входящими на wan интерфейс

```
    network_find_wan_all wan_iface
    for ext_iface in $wan_iface; do
       network_get_device DEVICE $ext_iface
       ipt PREROUTING -t raw -i $DEVICE -p tcp $1 -j NFQUEUE --queue-num $3 --queue-bypass
    done

```

**Comment by HanabishiRecca** [comment]
@bol-van на роутере не оказалось таблицы raw. А в других prerouting пакеты почему-то не объявлялись.
И мы же модифицируем не входящий, а **исходящий** пакет (SYN,ACK это ответ серверу).

**Comment by bol-van** [comment]
Нет, SYN это посылка серверу, SYN/ACK это ответ от сервера, в котором заодно и wsize
На счет hardware nat - да, при нем ничего не будет работать, это вариант для домохозяек, которым не надо порты пробрасывать, вообще ничего не надо, кроме nat
На заводских прошах действительно обычно не бывает raw, но я не расчитывал проект на них. К ним прикручивает народ самостоятельно

А на счет ack/syn - спасибо, кажется я забыл фильтр на них поставить в скриптах для openwrt

**Comment by HanabishiRecca** [comment]
@bol-van да, что-то сам себя переврал. SYN,ACK входящий конечно же. Выше там про sport писал.
HW NAT на самом деле штука полезная, особенно на гигабитном канале, когда в софтварном режиме нагрузка на проц становится очень существенной. Но с ним ничего не поделать разумеется.
Прошивка не заводская, openwrt же. Таблицы raw нету, видимо отдельными модулями надо ставить.

Кстати удалось поймать эти пакеты в mangle/PREROUTING. То есть действительно можно
```
iptables -t mangle -A PREROUTING -p tcp --sport 443 --tcp-flags SYN,ACK SYN,ACK -j NFQUEUE --queue-num 200 --queue-bypass
```
В принципе тогда правило становится универсальным, можно использовать и для роутера, и для просто компа с линуксом.

**Comment by bol-van** [comment]
Дык в ридми же написано какие пакеты нужны, делов то установить kmod-ipt-raw ?

**Comment by HanabishiRecca** [comment]
@bol-van да можно. Но вообще есть смысл толкать это именно в raw? В описаниях о предназначении таблиц, для модификации пакетов как раз существует mangle.

**Comment by bol-van** [comment]
Да , проверил, действительно работает. Значит уберу raw, ведь это дополнительная зависимость, которая не везде есть. Я как-то пробовал мангле у меня не работало, но значит в чем-то другом ошибся

**Comment by HanabishiRecca** [comment]
@bol-van вот я тоже так тыкался сначала, не работало. А потом заработало 🤔
Видимо хаотичным редактированием параметров сам себя в заблуждение и вводил. Разобрался только когда уже начал все движение пакетов логгировать.

**Comment by bol-van** [comment]
На счет вопроса в начале про len, мы ловим SYN,ACK пакеты, в которых данных нет, потому они все одного размера ip+tcp header

**Comment by HanabishiRecca** [comment]
А на другой прошивке не работает вообще 🙄
![изображение](https://user-images.githubusercontent.com/13597663/59454542-be5cc700-8e2b-11e9-9b08-02226c5479a5.png)

**Comment by HanabishiRecca** [comment]
Таки смог сделать желаемое через вот эту штуку https://github.com/p5n/ipt_tcpwin
Правда там то ли изначально код кривой, то ли особенности ядра на MIPS мешают, пришлось покурить документацию и руками допилить исходник.

**Comment by bol-van** [comment]
На другой прошивке - на какой ?
Версия ядра, архитектура.
Другие EXEшники из той же архитектуры не падают ?

**Comment by bol-van** [comment]
Можно попробовать распаковать через upx. Распаковать можно на любой системе, с любой арзитектурой и ОС. Без upx пашет ?

**Comment by HanabishiRecca** [comment]
@bol-van на openwrt было новое ядро 4.14. Ну и сама по себе система практически полноценная.

На другой прошивке (padavan) ядро старое 3.4. И система значительно порезанная. Однако я собираю сам и могу патчить как захочу. Модуль NFQUEUE включил, он работает, но вот именно nfqws падает. Распаковать не пробовал.

**Comment by bol-van** [comment]
Если он даже help не может вывести, то там дело не в коде, а в чем-то другом
Надо попробовать без upx

**Comment by HanabishiRecca** [comment]
@bol-van опа, распакованный сразу заработал. Вот это дела, впервые вижу, чтобы UPX ломал программу 🤔

**Comment by bol-van** [comment]
Возможно, код из upx использует какие-то функции ядра, которые были вырезаны в config от падавана
