### ISSUE TITLE
На последнем апдейте nfqws заработал Youtube на Samsung UE43NU7400

### ISSUE THREAD

**Issue by BucketBoot** [bol-van/zapret#341]
Router Xiaomi Redmi AX6 с Openwrt stable

**Comment by bol-van** [comment]
Разве это issue, если он заработал ? Вот если бы перестал работать, это другой вопрос

**Comment by bol-van** [comment]
В последнем nfqws была пофиксена проблема неинициализированных данных в поле tos заголовка IP.
tos содержит quality of service (qos).
На выход могли идти случайные мусорные данные вместо стандартного 0.
Возможно, какие-то узлы по пути режут пакеты с ненулевым qos. Хотя и вряд ли.

Еще несколько апдейтов назад сделано определение TLS CLientHello с версией SSL 3.0 в record layer. Старые телики такое могут выдавать.

**Comment by BucketBoot** [comment]
Перепутал я всё. Старый мой Samsung UE40F6400AKX не работал, в то время как более свежий UE43NU7400 вполне себе работал на старом релизе.
В общем, дети передают большое спасибо!

**Comment by bol-van** [comment]
Значит второе. С этим уже кто-то сталкивался, присылал мне дампы. Так и нашли проблему.
У него тоже вылечилось.
