### ISSUE TITLE
Вывод логов nfqws в Android в режиме --debug=syslog

### ISSUE THREAD

**Issue by nvasunin** [bol-van/zapret#342]
Попробовал в последней весрии nfqws сделать под Android вывод логов в режиме --debug=syslog (запускал nfqws как консольное приложение, не как демон). В logcat логов не нашел. На всякий случай посмотрел в dmesg - там тоже пусто. Куда под Android пишутся логи в режиме --debug=syslog?

П.С. И будут ли логи писаться в режиме демона? Вроде планировали сделать....

**Comment by bol-van** [comment]
никуда не пишутся
стандартный linux syslog и андроид лог не имеют ничего общего
в андроид лог можно писать только средствами android api
вероятно в bionic есть функции
бинарики готовые собраны под musl и нечего не знают про андроид

**Comment by nvasunin** [comment]
понятно
ну, тогда, наверное, можно, наверное, попробовать запускать процессы из-под logwrapper

```shell
root@android:/ # logwrapper
Usage: logwrapper [-d] BINARY [ARGS ...]

Forks and executes BINARY ARGS, redirecting stdout and stderr to
the Android logging system. Tag is set to BINARY, priority is
always LOG_INFO.

-d: Causes logwrapper to SIGSEGV when BINARY terminates
    fault address is set to the status of wait()
```

**Comment by nvasunin** [comment]
проверил
если запускать через logwrapper и в режиме демона - то логи в logcat выводятся, но не все, а только про загрузку хотлистов:
```shell
08-30 23:55:06.593 27657 27657 I nfqws   : Loading hostlist /storage/upgrade/zapret/ipset/russia-youtube.txt
08-30 23:55:06.593 27657 27657 I nfqws   : loading plain text list
08-30 23:55:06.593 27657 27657 I nfqws   : Loaded 5 hosts from /storage/upgrade/zapret/ipset/russia-youtube.txt
08-30 23:55:06.593 27657 27657 I nfqws   : Loading hostlist /storage/upgrade/zapret/ipset/zapret-hosts-user-exclude.txt
08-30 23:55:06.593 27657 27657 I nfqws   : loading plain text list
08-30 23:55:06.593 27657 27657 I nfqws   : Loaded 4 hosts from /storage/upgrade/zapret/ipset/zapret-hosts-user-exclude.txt
``` 

причем это не зависимо от наличия опции --debug=1

а можно ли сделать полноценную обработку параметра --debug=1 в режиме демона?

**Comment by bol-van** [comment]
daemon открывает стандартные потоки как   /dev/null
так что не вариант
но зачем daemon?

**Comment by nvasunin** [comment]
Потому что хотелось бы в логкат видеть как логи самого скрипта, который запускает nfqws, так и логи непосредственно симого nfqws.
Но тогда приходиьтся делать так:
- сам скрипт запускать через logwrapper: logwrapper zapret start
- в скрипте nfqws тоже запускать через logwrapper, асинхронно: logwrapper nfqws [....параметры...] &

К сожалению, такая конструкция не работает нормально - скрипт zapret выполняеся, но не завершается и остается "висеть" под процессом logwrapper. 
А если запускать nfqws из скрипта как демон: logwrapper nfqws --daemon [....параметры...] - то все работает как надо, кроме того что в логкате нет логов nfqws (кроме тех что он пишет про загрузку фильтров).

**Comment by bol-van** [comment]
то есть если из логвраппер запустить скрипт, а в нем любую команду, ее вывод пролетит мимо ?
если нет, то nfqws без daemon ничем не отличается

**Comment by bol-van** [comment]
и пусть себе висит, чем он мешает ?
можно сделать exec nfqws
 тогда шелл будет замещен nfqws

**Comment by nvasunin** [comment]
> то есть если из логвраппер запустить скрипт, а в нем любую команду, ее вывод пролетит мимо ? если нет, то nfqws без daemon ничем не отличается

нет, если из-под логвраппера запустить скрипт, то все, что скрипт (и запускаемые из него процессы) выводит в стдаут (насчет стдерр - не уверен, но можно попробовать) - попадает в логкат; причем не важно, запускается процесс синхронно или асинхроннно - все попадет в логкат
так что тут я ступил и перемудрил, сорри

> и пусть себе висит, чем он мешает ? можно сделать exec nfqws тогда шелл будет замещен nfqws

ну, кроме того, что скрипит запуска, если его запускать через логвраппер - по сути не завершается, хотя по логике должен был завершиться - в общем чем не мешает; в принципе логвраппер можно запускать асинхронно, не проблема
я думаю, что такое поведение связано с тем, что запускаемые асинхронно из скрипта nfqws имеют открытые дескрипторы, и пока они открыты - логвраппер не завершается
если процессы nfqws кильнуть - то и висящий логрвраппер сразу завершается

так что  принципе разобрались, спасибо
т.е. для Android, чтобы выводить в logcat отладочную информацию - надо скрипт запускать через logwrapper и асинхронно, а в самом скрипте nfqws запускать с опцией --debug=1
