### ISSUE TITLE
Влияние хостлиста на загрузку сайтов

### ISSUE THREAD

**Issue by electrifying** [bol-van/zapret#343]
Собсвенно вопрос,имеется запрет работающий в режиме hostlist сам файл zapret-hosts-user весит со всеми заблокированными доменами 2.02 мб, так как большинство записей просто взяты из реестра ркн, я на эти сайты все равно не захожу, а только на определенные поэтому имеет ли смысл удалить все не нужное и оставить только те домены, которые нужны или такой большой список все равно не будет влиять на скорость всех сайтов(не важно, заблокированные или нет) ,насколько я понял из доки то в режиме hostlist весь траффик все равно анализируется и идет обращение к zapret-hosts-user, после чего решается дурить сайт или нет, будет ли профит если уменьшить размер zapret-hosts-user  или можно оставить все как есть и на скорость это не повлияет?

**Comment by bol-van** [comment]
повлияет только на обьем занимаемой памяти
на скорость нет

**Comment by electrifying** [comment]
cпасибо за ответ
