### ISSUE TITLE
Слетает обход запретов при фильтрации hostlist

### ISSUE THREAD

**Issue by RJ-4816** [bol-van/zapret#347]
Доброго времени суток. Почитал документацию для исключения хостов из "дурения". Использую режим `NFQWS_OPT_DESYNC="--dpi-desync=split --dpi-desync-ttl=2"`. Однако при такой настройке нельзя скачать приложения с flathub. Выбрал фильтрацию hostlist и в файл zapret-hosts-user-exclude.txt добавил flathub.org. Zapret не смог "дурить" ютуб.

Как бы я не ставил фильтрацию hostlist, zapret не работал как нужно. Может, это я не так понял документацию?
[zapret-hosts-user.txt](https://github.com/user-attachments/files/16830082/zapret-hosts-user.txt)
[zapret-hosts-user-exclude.txt](https://github.com/user-attachments/files/16830083/zapret-hosts-user-exclude.txt)
[config.txt](https://github.com/user-attachments/files/16830088/config.txt)

**Comment by bol-van** [comment]
в такой конфигурации будет дуриться только youtube.com
что не даст эффекта
там нужны другие домены
см в дискуссиях обход ютубе
 
всегда можно включить --debug  и смотреть что он делает
см доку по --debug

**Comment by eastone11** [comment]
Используй для zapret-hosts-user.txt список ниже или переведи в режим autohostlist, у меня для ютуба еще пару доменов добавилось для обхода.

(Список от программы goodbyedpi):
youtube.com
youtu.be
googlevideo.com
ytimg.com
googleapis.com
i.ytimg.com
i9.ytimg.com
wide-youtube.l.google.com
youtube.googleapis.com
yt3.ggpht.com
yt3.googleusercontent.com
gvt1.com
video.google.com
youtube-nocookie.com
youtube-ui.l.google.com
youtubeeducation.com
youtubekids.com
yt.be
youtubei.googleapis.com
yt4.ggpht.com
ytimg.l.google.com
googleusercontent.com
gstatic.com
ggpht.com
