### ISSUE TITLE
OpenWRT PPPoE

### ISSUE THREAD

**Issue by gitalexch** [bol-van/zapret#349]
Есть подозрение, что провайдер начал перехватывать "странные" пакеты после nfqws  до начала PPPoE сессии  и выдавать при коннекте по PPPoE забаненную сетку без доступа к интернет вообще(даже подсеть отличается).
Предлагаю, добавить настройку которая бы не стартовала службу zapret до установки WAN-соединения, как реализовать --  не смог понять.......

**Comment by bol-van** [comment]
вряд ли причина в этом
zapret сам по себе ничего не отсылает
он реагирует на уже имеющиеся пакеты 
обычно это связано с запросами к сайтам

как правило до установления  pppoe сеанса
вообще нет никаких  ip адресоа
ip трафику некуда идти

**Comment by gitalexch** [comment]
у меня т.н. PPPoE dual access, до установки pppoe соединения на WAN прилетает по DHCP адрес и временный шлюз, соответственно, возможно от меня что-то улетает от различных приложений и т..п.

**Comment by bol-van** [comment]
надо с отключенным инет проводом и с опущенным pppoe интерфейсом начать запись дампа на wan
воткнуть провод
поднять pppoe
и еще полминуты покаптурить трафик
затем поизучать дамп на предмет http(s)
запросов до установления pppoe

так же проверить добавляется ли pppoe интерфейс в nfset wanif
/etc/init.d/zapret list_ifsets

по умолчанию в zapret исключены адреса локальных сетей

**Comment by gitalexch** [comment]
Всё, спасибо разобрался -- там у провайдера тупая защита от мультилогина.
