### ISSUE TITLE
openwrt 18.06.4 валится после перезагрузки

### ISSUE THREAD

**Issue by irifag** [bol-van/zapret#35]
Приветы. На чистой установке версии 18.06.4 после ребута роутер становится недоступен. 
Как при установке через install_easy.sh, так и при пошаговой ручной.  линксис wrt32x, если это важно.
Если подскажете что нужно отправить для дебага или дать удаленный доступ, то буду рад все предоставить

**Comment by irifag** [comment]
Таки смог зайти, если перед этим разрешить доступ с ван интерфейса. т.е подозреваю что проблема где-то в фаерволе, но вывод iptables соответствует чистой установке.

**Comment by irifag** [comment]
Устанавливал пошагово и после каждого шага ребутался. Оказалось это неадекватная реакция на установку grep.

**Comment by bol-van** [comment]
после установки grep   работает ли /usr/bin/grep ? может пакет битый ?

**Comment by irifag** [comment]
Работает.

**Comment by bol-van** [comment]
Скачал 18.06.04 для x86_64. Установил в vmware.
Все по умолчанию, только настроил сеть.
Установил zapret через install_easy с установкой grep
После ребута все ok
Уверен, что из-за grep ?
Я просто не понимаю как это возможно. Много систем на openwrt гонял с gnu grep, никогда такого не замечал

**Comment by irifag** [comment]
Да, абсолютно так, сам не очень понимаю как так. Проверял как на чистой, так и на комьюнити билде. Именно после уставновки грепа лан отпадает, хотя интерфейс поднят, дхцп работает и раздает адреса, с маршрутами, иптаблисей все нормально. Моих знаний не хватает чтобы найти в чем затык.
Если перед этим разрешить доступ в морду\ссш с вана, то после ребута можно с вана зайти, ремувнуть греп, ребутнуть и все обратно заработает. Если интересно - могу дать впн в локалку или порт пробросить и можешь поковырять, только какой-нибудь im укажи для связи.

**Comment by bol-van** [comment]
а если так : ln -s /bin/busybox /bin/grep 
?
установка grep удаляет линк на бизибокс из /bin
очевидно, чтобы брался всегда /usr/bin/grep
но может быть где-то зашит намертво  вызов /bin/grep ?
хотя у меня на 18.06 vmware работает и без этого линка

**Comment by bol-van** [comment]
если с gnu grep после ребута все-таки зайти на роутер через wan, нет ли в dmesg записей о SIGSEGV ?

**Comment by irifag** [comment]
В dmesg нет такого. Но нашел различия между вариантом до и после установки грепа. В варианте после установки и ребута есть:
nf_conntrack:   default automatic helper assignment has been turned off for security reasons   and CT-based  firewall rule not found.   Use the iptables CT target to attach helpers instead.

С симлинком все заработало нормально.

**Comment by bol-van** [comment]
А прошивка чистая ? Прям дефолтный образ, и на нем проблема ?
Ведь скрипты одинаковые что на mvebu, что на x86

**Comment by bol-van** [comment]
И это еще проверь 
ln -fs /usr/bin/grep /bin/grep
так будет работать или нет ?
Если нет, значит чему-то не нравится именно gnu grep. Если да, то где-то мертво зашито /bin/grep

**Comment by irifag** [comment]
В данный момент проверял на комьюнити билде, ибо все уже отстроил и лениво было все это делать заново, до этого пробовал и чистый с https://openwrt.org/toh/hwdata/linksys/linksys_wrt32x_v1_venom. 
Сейчас таки еще раз проверил на чистом - результат тот же.
ln -fs /usr/bin/grep /bin/grep помогает, как и симлинк который выше. Перепроверил дважды

**Comment by bol-van** [comment]
добавил костыль в install_easy

**Comment by irifag** [comment]
Спасибо, чмокаю.
