### ISSUE TITLE
Поддержка OpenRC

### ISSUE THREAD

**Issue by illialoo99** [bol-van/zapret#36]
Нашёл поддержку SystemD и OpenWRT, но уж никак не OpenRC. Не могли бы добавить?

**Comment by bol-van** [comment]
OpenRC используется где ? В gentoo ? Еще где ? Почти нигде.
Если уж осилили генту, то неужели сложно по инструкции установить в ручном режиме ? В ней есть раздел, посвященный openrc.
Дистрибутивы на базе gentoo используются очень редко
