### ISSUE TITLE
Заставить mdig резолвить домены через указанные DNS сервера

### ISSUE THREAD

**Issue by ilfat12** [bol-van/zapret#360]
Здравствуйте!
Разные DNS сервера возвращают разные IP адреса для доменов
```
ilfat@laptop ~ $ nslookup -type=A youtube.com 8.8.8.8 | grep Address | grep -v '#53'
Address: 108.177.14.190
Address: 108.177.14.93
Address: 108.177.14.91
Address: 108.177.14.136
ilfat@laptop ~ $ nslookup -type=A youtube.com 1.1.1.1 | grep Address | grep -v '#53'
Address: 173.194.221.93
Address: 173.194.221.136
Address: 173.194.221.190
Address: 173.194.221.91
ilfat@laptop ~ $ nslookup -type=A youtube.com 77.88.8.1 | grep Address | grep -v '#53'
Address: 142.250.150.93
Address: 142.250.150.91
Address: 142.250.150.136
Address: 142.250.150.190
```

Можно ли реализовать возможность задать список DNS серверов по которым будет проходиться mdig?

**Comment by bol-van** [comment]
пока это не реализовано
используется ресолвер из libc. он не умеет менять днс
хотя никто не мешает сделать простенький chroot
со статическим mdig в корне
/etc/resolv.conf
по желанию

**Comment by ilfat12** [comment]
> хотя никто не мешает сделать простенький chroot
> со статическим mdig в корне
> /etc/resolv.conf

Но ведь и в этом случае только у одного сервера будет запрашивтаь?

**Comment by bol-van** [comment]
сразу много серверов опрашивать избыточно для большинства доменов
mdig предназначен для ресолвинга больших листов
прыгающие ip могут быть у 1-2%  доменов
получается работа вхолостую

сделайте скрипт, который будет по очереди менять  resolv.conf в chroot
потом обьедините листы через cat l1 l2 l3 | sort -u

**Comment by ilfat12** [comment]
Спасибо.
Решил пойти другой дорогой. Изменю nftables правила, чтобы трафик модифицировался только от процессов с указанным владельцем и пущу ютуб через проксирующую программу запущенную от этого пользователя. Думаю должно сработать.

**Comment by bol-van** [comment]
можно делать редирект udp и tcp 53 от процессов с uid mdig

**Comment by ilfat12** [comment]
Отфильтровал исходящие запросы по владельцу.
В этом случае не страшно, что ответные пакеты для всех процессов будут через очередь nfqws проходить?

**Comment by bol-van** [comment]
не понял вопроса
какие именно входящие и зачем пропускать входящие через nfqws ?
входящие нужны для autottl, autohostlist и wsize
и то в ограниченных количествах

**Comment by ilfat12** [comment]
Я про эти правила:
```
-A INPUT -i enp3s0 -p tcp -m multiport --sports 80 -m connbytes --connbytes 1:1 --connbytes-mode packets --connbytes-dir reply -m set ! --match-set nozapret src -j NFQUEUE --queue-num 200 --queue-bypass
-A FORWARD -i enp3s0 -p tcp -m multiport --sports 80 -m connbytes --connbytes 1:1 --connbytes-mode packets --connbytes-dir reply -m set ! --match-set nozapret src -j NFQUEUE --queue-num 200 --queue-bypass
```

**Comment by ilfat12** [comment]
Для http случайно скопировал, но не суть.

**Comment by ilfat12** [comment]
Это же ответный входящий пакет, откуда там быть маркировке? Или я вас не понял)
А в POSTROUTING правиле есть проверка по mark.
Ну в общем все работает.
Я лишь беспокоился не будут ли эти правила негативно влиять на соединения, которые не модифицируются в POSTROUTING при установке соединения, так как они от другого owner и фильтруются.
Вообще, я задался вопросом отделить трафик, который надо модифицировать, потому что apt в контейнерах не мог обновить и скачать пакеты пока не отключил zapret. Не смотрел, но думаю apt качает по http, так как пакеты не секретные и подписаны и, подозреваю, из-за того, что и для http и для https действовало общее правило подобранное под https ломался http. Пока http оставил, но алгоритмы прописал раздельно и вроде все нормально. Если что выключу http.

**Comment by bol-van** [comment]
да, действительно. для входящих не надо марк
но это правило недостаточно для автолиста
так, к слову

страшного ничего не произойдет
разве что nfqws создаст запись в своем коннтрак
займет чуток памяти

если что - такие ситуации разруливаются через коннмарк

**Comment by ilfat12** [comment]
> да, действительно. для входящих не надо марк
> но это правило недостаточно для автолиста
> так, к слову

Ну это zapret такое правило создает, я только фильтр по owner добавляю в правило, которое в POSTROUTING.

> займет чуток памяти

ОЗУ навалом, так что норм.

В итоге я своей цели добился.
Еще раз благодарю за проект и за раъяснения!
За документацию отдельное спасибо)
