### ISSUE TITLE
Периодическая буферизация видео на мобильном клиенте YouTube

### ISSUE THREAD

**Issue by R0iZ** [bol-van/zapret#367]
Установил на роутер  с openwrt 23.05.4, стратегию подобрал, ютуб работает на пк, андроид приставках отлично! Только на смартфоне в приложении видео периодически останавливается и "крутится кружок" буферизации секунд 20, потом снова нормально видео идет. Скорость интернета хорошая, порядка 300 Мбит. Попробовал закрыть UDP на 443 порту, не изменилось ничего. Есть идеи?

**Comment by R0iZ** [comment]
Забыл написать, на смартфоне прописан частный DNS, тот же что и прописан в роутере (Adguard Home, на отдельной железке стоит)

**Comment by bol-van** [comment]
первым делом проверить курлом обходится ли тлс 1.2
если да, смотреть дамп где застревает

**Comment by R0iZ** [comment]
> первым делом проверить курлом обходится ли тлс 1.2 если да, смотреть дамп где застревает

`GET /app/uploads/2021/11/2022-mediakortti.pdf HTTP/2
> Host: metsalehti-staging-s4uzwwd6nq-lz.a.run.app
> User-Agent: curl/8.7.1
> Accept: */*
> 
< HTTP/2 200 
< content-type: application/pdf
< last-modified: Mon, 10 Jan 2022 15:11:19 GMT
< vary: Accept-Encoding
< etag: "61dc4c97-6d4968"
< x-frame-options: SAMEORIGIN
< accept-ranges: bytes
< x-cloud-trace-context: c4c492faa5e0ec637bb433fc713d8717;o=1
< date: Tue, 10 Sep 2024 03:32:48 GMT
< server: Google Frontend
< content-length: 7162216
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< 
{ [1370 bytes data]`
Судя по скорости, проблема присутствует.
Опции установлены такие: --dpi-desync=fake,disorder2 --dpi-desync-ttl=3
Добавил опцию: --dpi-desync=fake,disorder2 --dpi-desync-ttl=3 --dpi-desync-fooling=md5sig
Ответ curl не изменился.

**Comment by bol-van** [comment]
откуда взята команда ?
надо проверять
на тлс 1.3, 1.2 и quic

**Comment by R0iZ** [comment]
> откуда взята команда ? надо проверять на тлс 1.3, 1.2 и quic

С вашего сообщения и взята: https://github.com/bol-van/zapret/discussions/200#discussion-7001703

**Comment by R0iZ** [comment]
curl  --tls-max 1.2 -v4s -o/dev/null -k --connect-to ::google.com -H Host:\ metsalehti-staging-s4uzwwd6nq-lz.a.run.app https://test.googlevideo.com/app/uploads/2021/11/2022-mediakortti.pdf -w %{speed_download}
Вот эта команда

**Comment by bol-van** [comment]
команда не предназначена в таком виде для виндовс
символ \ в винде не работает
Host:\ metsalehti-staging-s4uzwwd6nq-lz.a.run.app
заменяется на
"Host: metsalehti-staging-s4uzwwd6nq-lz.a.run.app"

/dev/null
заменяется на
nul

тест с куик говорит об отсутствии ответа
заблокировано

**Comment by R0iZ** [comment]
Сегодня вообще YouTube перестал работать с выбранными опциями в конфиге zapret. Пришлось перебирать несколько штук, с некоторыми на пк работает, на андроиде нет и наоборот. С пятой попытки подобрал такую стратегию, что работает везде и пока на смартфоне тоже пропала буферизация. Предполагаю, что провайдер начал бороться с методами обхода, поэтому проблемы и возникают.

**Comment by alexzzd** [comment]
> С пятой попытки подобрал такую стратегию, что работает везде и пока на смартфоне тоже пропала буферизация. 

А можно сюда выложить опции текущей стратегии обхода?

**Comment by R0iZ** [comment]
> > С пятой попытки подобрал такую стратегию, что работает везде и пока на смартфоне тоже пропала буферизация.
> 
> А можно сюда выложить опции текущей стратегии обхода?

NFQWS_OPT_DESYNC="--dpi-desync=disorder2 --wssize 1:6"
