### ISSUE TITLE
Chatgpt

### ISSUE THREAD

**Issue by dubik11** [bol-van/zapret#368]
Добрый день!

Настроил, все работает, настройки следующие:

iptables
keepalive y
http y
https y
quic y
nfqws
NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder --dpi-desync-ttl=2 --dpi-desync-fooling=badsum"
none
none

Все отличное работает, единственное не заходит на chatgpt.com ругается что иду со своего IP, может кто-нибудь подсказать пожалуйста как его настроить?

Прошивка openwrt

**Comment by bol-van** [comment]
zapret не обходит блок со стороны самого сайта
нужно менять geoip

**Comment by dubik11** [comment]
подскажите пожалуйста можно ли это сделать с помощью zapret?

или может можете подсказать как это реализовывается на уровне роуетра?

**Comment by eastone11** [comment]
> > zapret не обходит блок со стороны самого сайта нужно менять geoip
> 
> подскажите пожалуйста можно ли это сделать с помощью zapret?
> 
> или может можете подсказать как это реализовывается на уровне роуетра?

ставишь https-dns-proxy
удаляешь в HTTPS DNS Proxy - Instances существующие
добавляешь в самом низу Custom данный DOH https://dns.controld.com/comss
проверить работает или нет по ссылке [www.dnsleaktest.com](http://www.dnsleaktest.com/) и [Configuration Status](https://controld.com/status)

**Comment by dubik11** [comment]
> > > zapret не обходит блок со стороны самого сайта нужно менять geoip
> > 
> > 
> > подскажите пожалуйста можно ли это сделать с помощью zapret?
> > или может можете подсказать как это реализовывается на уровне роуетра?
> 
> ставишь https-dns-proxy удаляешь в HTTPS DNS Proxy - Instances существующие добавляешь в самом низу Custom данный DOH https://dns.controld.com/comss проверить работает или нет по ссылке [www.dnsleaktest.com](http://www.dnsleaktest.com/) и [Configuration Status](https://controld.com/status)

не совсем понял, можно поподробнее пожалуйста? где это все делается?

**Comment by dubik11** [comment]
> > > zapret не обходит блок со стороны самого сайта нужно менять geoip
> > 
> > 
> > подскажите пожалуйста можно ли это сделать с помощью zapret?
> > или может можете подсказать как это реализовывается на уровне роуетра?
> 
> ставишь https-dns-proxy удаляешь в HTTPS DNS Proxy - Instances существующие добавляешь в самом низу Custom данный DOH https://dns.controld.com/comss проверить работает или нет по ссылке [www.dnsleaktest.com](http://www.dnsleaktest.com/) и [Configuration Status](https://controld.com/status)

не хватает памяти на установку https-dns-proxy к сожалению

**Comment by bol-van** [comment]
советы про днс - чушь
только прокси или впн

**Comment by WhiteAls** [comment]
> советы про днс - чушь
> только прокси или впн

не чушь кстати, магия вот в чём https://en.wikipedia.org/wiki/EDNS_Client_Subnet

**Comment by bol-van** [comment]
днс может вернуть другие адреса
но чем это поможет обойти геоип блок со стороны сайта ?

**Comment by eastone11** [comment]
> советы про днс - чушь только прокси или впн

обидно за чушь, но я юзаю чатгпт с помощью этой чуши https://www.comss.ru/page.php?id=12919
`Одной из уникальных особенностей нашего DNS-сервиса является возможность доступа к [ИИ-сервисами (Microsoft Copilot, ChatGPT, Google Gemini и другие) без VPN`

**Comment by WhiteAls** [comment]
> днс может вернуть другие адреса
> но чем это поможет обойти геоип блок со стороны сайта ?
openai использует cdn от cloudflare. сами лично они не банят нашу страну, но их сисадмины выставили соответсвующие настройки в cdn.
когда ты пытаешься открыть сайт чатагпт, то твой днс-форвардер отправляет запрос, который проходит через cloudflare, они видят откуда пришёл запрос (благодаря EDNS Client Subnet) и запрещают доступ к сайту.
comss (точнее contold) отдаёт фейковые данные в опции EDNS Client Subnet и поэтому блока нет

**Comment by WhiteAls** [comment]
окей, я сам почуствовал неладное и пошёл проверять. возможно ESN дейстивтельно тоже используется, но, похоже, что controld также проксирует запросы через себя. на скрине первый запрос через controld, второй через гугл
![image](https://github.com/user-attachments/assets/0bd30248-4eee-49a9-8680-c16a6c987099)

**Comment by bol-van** [comment]
окей, если работает, значит вы правы
но в общем случае если на сайте блокируется   страна
вы никак это не обойдете без смены ип

**Comment by bol-van** [comment]
по хуизу адрес относится к controld
значит там прокси ?
они подменяют ип на себя
и протаскивают через себя траф
