### ISSUE TITLE
Добавить в конфиг переменные для установки дополнительных условий в iptables/nftables

### ISSUE THREAD

**Issue by ilfat12** [bol-van/zapret#369]
Добрый день!
Мы с вами уже беседовали в другом issue по вопросу как пустить через zapret только нужный трафик. В итоге я остановился на том, что добавил проверку по владельцу процесса. Однако узнал, что программа sing-box, которую я использую, умеет маркировать исходящие пакеты и решил использовать эту возможность, думаю это менее затратно, чем узнавать владельца, да и проще в настройке, не нужно запускать отдельный экземпляр от нужного пользователя и так далее..
В общем, в sing-box устанавливается 28-ой бит, а в nft.sh добавляется проверка его наличия.
Все работает хорошо.
Конечно, было бы приятно иметь в конфиге пару переменных, для iptables/nftables, чтоб можно было добавлять свои условия через них, а не через правку кода. Да ту же проверку по owner например.
Если будет у вас такая возможность и желаение добавить, было бы здорово :)
Спасибо!

**Comment by bol-van** [comment]
редко используемые вещи я выношу на custom script, чтобы не перегружать основной функционал
там можно написать как угодно

**Comment by madnezzm** [comment]
> Добрый день! Мы с вами уже беседовали в другом issue по вопросу как пустить через zapret только нужный трафик. В итоге я остановился на том, что добавил проверку по владельцу процесса. Однако узнал, что программа sing-box, которую я использую, умеет маркировать исходящие пакеты и решил использовать эту возможность, думаю это менее затратно, чем узнавать владельца, да и проще в настройке, не нужно запускать отдельный экземпляр от нужного пользователя и так далее.. В общем, в sing-box устанавливается 28-ой бит, а в nft.sh добавляется проверка его наличия. Все работает хорошо. Конечно, было бы приятно иметь в конфиге пару переменных, для iptables/nftables, чтоб можно было добавлять свои условия через них, а не через правку кода. Да ту же проверку по owner например. Если будет у вас такая возможность и желаение добавить, было бы здорово :) Спасибо!

Пытаюсь организовать подобную схему с Sing-box. Можешь пожалуйста поделиться правилами nftables?

**Comment by ilfat12** [comment]
> > Добрый день! Мы с вами уже беседовали в другом issue по вопросу как пустить через zapret только нужный трафик. В итоге я остановился на том, что добавил проверку по владельцу процесса. Однако узнал, что программа sing-box, которую я использую, умеет маркировать исходящие пакеты и решил использовать эту возможность, думаю это менее затратно, чем узнавать владельца, да и проще в настройке, не нужно запускать отдельный экземпляр от нужного пользователя и так далее.. В общем, в sing-box устанавливается 28-ой бит, а в nft.sh добавляется проверка его наличия. Все работает хорошо. Конечно, было бы приятно иметь в конфиге пару переменных, для iptables/nftables, чтоб можно было добавлять свои условия через них, а не через правку кода. Да ту же проверку по owner например. Если будет у вас такая возможность и желаение добавить, было бы здорово :) Спасибо!
> 
> Пытаюсь организовать подобную схему с Sing-box. Можешь пожалуйста поделиться правилами nftables?

Добрый!
Я настроил себе init.d/sysv/custom.
Некоторые строки закомментировал, так как не использую хостлисты и айписеты.
И QUIC, хоть и добавил в конфиг, не использую.

```
# this script contain your special code to launch daemons and configure firewall
# use helpers from "functions" file
# in case of upgrade keep this file only, do not modify others

QNUM2=$(($QNUM+1))
QNUM3=$(($QNUM2+1))

zapret_custom_daemons()
{
        # $1 - 1 - run, 0 - stop

        local opt

        [ "$MODE_HTTP" = "1" ] && {
                opt="--qnum=$QNUM $NFQWS_OPT_DESYNC_HTTP"
                #filter_apply_hostlist_target opt
                do_nfqws $1 1 "$opt"
        }

        [ "$MODE_HTTPS" = "1" ] && {
                opt="--qnum=$QNUM2 $NFQWS_OPT_DESYNC_HTTPS"
                #filter_apply_hostlist_target opt
                do_nfqws $1 2 "$opt"
        }

        [ "$MODE_QUIC" = "1" ] && {
                opt="--qnum=$QMUM3 $NFQWS_OPT_BASE $NFQWS_OPT_DESYNC_QUIC"
                do_nfqws $1 3 "$opt"
        }
}
zapret_custom_firewall()
{
        # $1 - 1 - run, 0 - stop

        local f4 f6 f
        local first_packets_only="$ipt_connbytes 1:$(first_packets_for_mode)"
        local first_packets_only_quic="$ipt_connbytes 1:3"
        local desync="-m mark ! --mark $DESYNC_MARK/$DESYNC_MARK"
        local mymark="-m mark --mark 0x10000000/0x10000000"

        [ "$MODE_HTTP" = "1" ] && {
                f4="-p tcp -m multiport --dports $HTTP_PORTS_IPT $first_packets_only"
                f6=$f4
                #filter_apply_ipset_target f4 f6
                fw_nfqws_post $1 "$f4 $desync $mymark" "$f6 $desync $mymark" $QNUM
        }

        [ "$MODE_HTTPS" = "1" ] && {
                f4="-p tcp -m multiport --dports $HTTPS_PORTS_IPT $first_packets_only"
                f6=$f4
                #filter_apply_ipset_target f4 f6
                fw_nfqws_post $1 "$f4 $desync $mymark" "$f6 $desync $mymark" $QNUM2
                # for modes that require incoming traffic
                #fw_reverse_nfqws_rule $1 "$f4" "$f6" $QNUM2
        }

        [ "$MODE_QUIC" = "1" ] && {
                f="-p udp -m multiport --dports $QUIC_PORTS_IPT"
                fw_nfqws_post $1 "$f $desync $mymark $first_packets_only_quic" "$f $desync $mymark $first_packets_only_quic" $QNUM3
        }
}

zapret_custom_firewall_nft()
{
        # stop logic is not required

        local f4 f6 f
        local first_packets_only="$nft_connbytes 1-$(first_packets_for_mode)"
        local first_packets_only_quic="$nft_connbytes 1-3"
        local desync="mark and $DESYNC_MARK == 0"
        local mymark="mark and 0x10000000 == 0x10000000"

        [ "$MODE_HTTP" = "1" ] && {
                f4="tcp dport {$HTTP_PORTS} $first_packets_only"
                f6=$f4
                #nft_filter_apply_ipset_target f4 f6
                nft_fw_nfqws_post "$f4 $desync $mymark" "$f6 $desync $mymark" $QNUM
        }

        [ "$MODE_HTTPS" = "1" ] && {
                f4="tcp dport {$HTTPS_PORTS} $first_packets_only"
                f6=$f4
                #nft_filter_apply_ipset_target f4 f6
                nft_fw_nfqws_post "$f4 $desync $mymark" "$f6 $desync $mymark" $QNUM2
                # for modes that require incoming traffic
                #nft_fw_reverse_nfqws_rule "$f4" "$f6" $QNUM2
        }

        [ "$MODE_QUIC" = "1" ] && {
                f="udp dport {$QUIC_PORTS}"
                nft_fw_nfqws_post "$f $desync $mymark $first_packets_only_quic" "$f $desync $mymark $first_packets_only_quic" $QNUM3
        }

        # Удаляю лишние для меня правила
        nft delete chain inet zapret flow_offload

}
```

**Comment by madnezzm** [comment]
Спасибо, попробую поковырять. Как я понимаю в Sing-box у вас есть direct out с маркировкой пакета «1» и в этом скрипте nft настраивается на матчинг трафика с маркером  0x10000000?

**Comment by ilfat12** [comment]
> Спасибо, попробую поковырять. Как я понимаю в Sing-box у вас есть direct out с маркировкой пакета «1» и в этом скрипте nft настраивается на матчинг трафика с маркером 0x10000000?

Можешь и как 1 маркировать в sing-box, тогда в custom надо прописать 0x1
Тут главное 29 и 30 бит не трогать, то есть 0x20000000 и 0x40000000, их zapret маркирует.
Поэтому я решил 28 бит в 1 устанавливать, чтоб красиво было)

**Comment by bol-van** [comment]
Сделаны переменные FW_EXTRA_PRE и FW_EXTRA_POST
Использовать в кастомах как локальный префикс
FW_EXTRA_PRE="meta mark and 2 != 0" nft_fw_nfqws_post .........
Можно использовать и целиком в наследовании стандартного режима.
