### ISSUE TITLE
Настройка ip2net

### ISSUE THREAD

**Issue by dimqua** [bol-van/zapret#37]
Мой исходный список IP-адресов содержит 514850 строк, 1347285 IP и весит 7 мегабайт. После обработкой утилитой `ip2net`, число строк уменьшаются до 496189, а размер  до 6.7 мегабайт, число IP адресов возрастает до 1362110.

Это я все к чему. Возможно, необходимо сделать `ip2net` более агрессивной, поскольку сейчас размер списков сокращается незначительно (на ~3%). В идеале, конечно, лучше добавить опции конфигурирования, чтобы пользователи могли настраивать основные переменные.

**Comment by bol-van** [comment]
у меня сокращается с 750 до 550
список antizapret все время растет, я не знаю откуда они берут столько ip адресов и так быстро увеличивается он
если копать самому через get_reestr, то выходит в 10 раз меньше

**Comment by bol-van** [comment]
#define PCTMULT	3
#define PCTDIV	4

поставьте PCTMULT 2
будет значит 1/2 , чтобы занести всю подсетку
это что-то изменит ?

**Comment by dimqua** [comment]
> 750 до 550

Тысяч строк? Это при использовании списка антизапрета?

**Comment by dimqua** [comment]
> я не знаю откуда они берут столько ip адресов

В выгрузке куча IP-адресов (в т.ч. 39 префиксов) без указания доменов, которые провайдеры обязаны банить по IP. Если я правильно понимаю, то `get_reestr.sh` резолвит только домены.

**Comment by bol-van** [comment]
да, get_reestr не учитывает
настройки сделаю как будет время

Мой текущий antizapret (27-AUG-2019):

zcat zapret-ip.txt.gz | wc -l
714267
ipset list zapret | wc -l
556393

**Comment by bol-van** [comment]
провайдеры блочат по разному
многие вообще забивают на Ip из реестра, если указан домен и http
они его через DPI прогоняют

**Comment by dimqua** [comment]
В общем, наверное, что не стоит, наверное, менять дефолты, иначе (по крайней мере при использовании текущего алгоритма) это приводит к существенному увеличению "лишних" IP в списках, при том, что размер уменьшается не так сильно.

Кстати, я правильно понимаю, что резолвинг доменов и ipset применяются для снижения нагрузки на систему? По сравнению с использованием только tpws и списка доменов РКН.

**Comment by bol-van** [comment]
да, ipset должен быть значительно быстрее, потому что не протаскиваем весь TCP через user mode процесс. только l3 фильтр в kernel

**Comment by dimqua** [comment]
А если использовать небольшой список доменов, то все равно (при использовании tpws) нагрузка высокая получается? Я просто пока не пробовал. :-)

**Comment by bol-van** [comment]
tpws в режиме hostlist предполагает пропуск всех соединений через него
поиск host - операция быстрая, там используется hash list
вся нагрузка в протаскивании всего соединения через user mode процесс
размер списка доменов роли не играет

**Comment by dimqua** [comment]
Да, в readme об этом написано, но меня смутилио следущее:
>При использовании больших списков, в том числе списка РКН, оцените объем RAM на роутере! Если после запуска tpws RAM под завязку или случаются oom, значит нужно отказаться от таких больших списков.

Вроде как противоречие же.

**Comment by bol-van** [comment]
В чем противоречие ? tpws хранит хэшированный список в RAM. он в несколько раз больше текстового файла со списком. на скорость это не влияет. подобно как select из огромной базы данных по index

**Comment by dimqua** [comment]
Да, тупить начал. :-) Спасибо за разъяснения.

После установки вопрос возник. У меня `nfqws` работает со стандартными опциями (`--wsize=3 --hostspell=HOST`) и для HTTPS-трафика, то есть без параметра `split-pos`, которого у него вообще нет. Так и должно быть?

**Comment by bol-van** [comment]
wsize заменяет split-pos

**Comment by dimqua** [comment]
@bol-van а почему [вот тут](https://github.com/bol-van/zapret/blob/043a265f3a3ee99165b9eb4e34da5008fbd2f916/init.d/openwrt/functions#L235) указано `-m multiport --sports 80,443`, для http это правило тоже необходимо? Просто у меня и без него http-сайты открываются.

**Comment by dimqua** [comment]
Ан нет, понял, ошибся при тестировании.

**Comment by bol-van** [comment]
Хотелка реализована и добавлена поддержка ip6
