### ISSUE TITLE
Обход работает исключительно по LAN, но не работает по WiFi на других устройствах. OpenWRT

### ISSUE THREAD

**Issue by lunedzy** [bol-van/zapret#375]
после переустановки zapret на OpenWRT появилась проблема - обход работает только по LAN, остальные устройства с WiFi не работают.. пару недель работало везде благодаря "--dpi-desync=fake,split2" но сейчас это не работает.
ниже прикреплю конфиг nfqws

DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-ttl=0 --dpi-desync-ttl6=0 --dpi-desync-fooling=badseq,md5sig"
NFQWS_OPT_DESYNC_HTTP="--dpi-desync=split --dpi-desync-ttl=0 --dpi-desync-fooling=badsum"
NFQWS_OPT_DESYNC_HTTPS="--wssize=1:6 --dpi-desync=split --dpi-desync-ttl=0 --dpi-desync-fooling=badsum"
NFQWS_OPT_DESYNC_HTTP6="--dpi-desync=split --dpi-desync-ttl=5 --dpi-desync-fooling=none"
NFQWS_OPT_DESYNC_HTTPS6="--wssize=1:6 --dpi-desync=split --dpi-desync-ttl=5 --dpi-desync-fooling=none"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6"
NFQWS_OPT_DESYNC_QUIC6="--dpi-desync=hopbyhop"

**Comment by bol-van** [comment]
эта проблема не связана с zapret
 однажды у кого-то уже было
в итоге выяснили, что он включил аппаратное ускорение в веб морде

**Comment by lunedzy** [comment]
оно у меня отключено. но работало же ведь, да и конфиг не изменился прошлый.. ладно, тогда попробую сам ручками пофиксить проблему) хорошего дня!

**Comment by grigaraz** [comment]
появилась проблема - обход работает только по LAN, остальные устройства с WiFi не работают.. пару недель работало везде,тоже такая проблема ,но на роутере keenetic peak (выключателя аппаратного ускорения нет вродебы этот роутер в этом не нуждается ) подсккажите как быть,все работало,Но вот сегодня только по лан ...

**Comment by matt14509** [comment]
+

**Comment by bol-van** [comment]
На openwrt дефолтная конфигурация обьединяет LAN и WIFI в мост br-lan
Так что пакеты приходят в любом случае с br-lan и уходят на wan интерфейс.
Включайте дебаг nfqws и смотрите что он делает
Может он вообще не получает пакеты, может не все пакеты (характерно для оффлоада)

**Comment by grigaraz** [comment]
Спас этот конфиг
NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/dtls_clienthello_w3_org.bin"

**Comment by eastone11** [comment]
> Спас этот конфиг NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/dtls_clienthello_w3_org.bin"

а у вас на вай фай устройствах вообще не работали обходы на запрет сайты или только ютуб?

**Comment by grigaraz** [comment]
> а у вас на вай фай устройствах вообще не работали обходы на запрет сайты или только ютуб?

Как то я упёрся в Ютуб,а насчет сайтов даже не знаю,у меня в браузере стоит расширение "обход блокировок Рунета" поэтому как то не заметил каких-то запретов :) ,а вот Ютуб даже с этим расширением не работал.

**Comment by eastone11** [comment]
тогда ясно
ps
а зачем вам дополнение в браузере, если все эти проблемы решаются на уровне роутера?

**Comment by grigaraz** [comment]
> проблемы решаются на уровне роутера?

Теперь не зачем...

**Comment by lunedzy** [comment]
нужно покупать вообще свой сервер и поднимать на нем свой впн, к примеру vless либо же попроще ruantiblock..
работает не хуже zapret'a, и более продвинуто. но нужно иметь хотя-бы какие то навыки в настройке сервера, чтоб в случае ошибок понимать как и что делать.
но в zapret отличный вариант для обхода DPI, но есть свои изъяны.. "один сайт обошел - второй отлетел" но в РФ блокировки будут становится еще серьезнее, и не думаю что обойтись одним zapret'ом хватит в наших реалях)

**Comment by grigaraz** [comment]
> нужно покупать вообще свой сервер

Я тупо настроил свой сервер на роутере,и подключаюсь где угодно,и все вроде как работает ;)

**Comment by lunedzy** [comment]
насчет ruantiblock'a есть множество гайдов.. но и настройка довольно простая (не для всех), и по WiFi будет работать без проблем. насчет VLESS/X-Ray и т.п. разобратся я лично не смог, вроде все поставил правильно но по WiFi он не работал.
сейчас нахожусь на ruantiblock'e, и очень доволен - все сайты работают на отлично, ну и сервер не подвел достаточно хорошая скорость.

**Comment by lunedzy** [comment]
> > нужно покупать вообще свой сервер
> 
> Я тупо настроил свой сервер на роутере,и подключаюсь где угодно,и все вроде как работает ;)

по-подробнее?

**Comment by lunedzy** [comment]
РКН мудрят как могут, позавчера начал работать рутрекер без VPN )
у кого как не знаю, я лично удивился 😆

**Comment by grigaraz** [comment]
> по-подробнее?

На кинетиках это делается в два щелчка,причем почти любой из существующих ВПН серверов,и подключаюсь к "дому" как на работе с компа,так и на телефоне или планшете.

**Comment by lunedzy** [comment]
> > по-подробнее?
> 
> На кинетиках это делается в два щелчка,причем почти любой из существующих ВПН серверов,и подключаюсь к "дому" как на работе с компа,так и на телефоне или планшете.

ну это такое себе, сидеть не со своего айпи + урезанная скорость со стороны VPN'a..
на ruantiblock такого нет, все грузит на отлично ну и остаешься на своем родном айпи когда обычно серфишь.
но только на сайтах где блокировка используется айпишник сервера, но что удивительно грузит отлично 4к видео без фризов..

**Comment by grigaraz** [comment]
> ну это такое себе, сидеть не со своего айпи +

Как раз я получается везде сижу со своего домашнего ip.да и скорость отличная.

**Comment by theclutch3** [comment]
Такая же проблема, конфиг менять через изменение текстового файла? Мне не помогает

**Comment by lunedzy** [comment]
> Такая же проблема, конфиг менять через изменение текстового файла? Мне не помогает
настраивай через winscp / nano конфиги.

**Comment by lunedzy** [comment]
> Такая же проблема, конфиг менять через изменение текстового файла? Мне не помогает

настраивай через winscp / nano конфиги.

**Comment by lunedzy** [comment]
> Копировал конфиг grigiraz, через винсцп, а там блокнотом первую строчку конфига менял. Все правильно ?
> 
> > > Такая же проблема, конфиг менять через изменение текстового файла? Мне не помогает
> > 
> > 
> > настраивай через winscp / nano конфиги.

какой смысл копировать чужие конфиги? у вас разные провайдеры, следовательно стратегии для каждого индивидуальны.. ну а так правильно

**Comment by giich** [comment]
Keenetic GIGA Mipsel. Та же самая проблема, по проводу работает, по wi-fi нет. Причем неделю назад работало везде. NFQ с --debug показывает что пакеты видит. Дичь какая-то. Запрет последний, режимы пробовал none и hostlist, параметры тоже все перебрал. Аппаратное ускорение выключено. Прошивка из ветки БЕТА

**Comment by Vinyl23** [comment]
у меня на оборот на тел работает а в лан нет как решить)?

**Comment by bol-van** [comment]
Отключить аппаратное ускорение. flow offloading
