### ISSUE TITLE
Перестало грузиться видео youtube 12.09 ростелеком.

### ISSUE THREAD

**Issue by KeepeR22rus** [bol-van/zapret#378]
До сегодня все работало, сегодня перестало. Сайт и картинки грузятся, видео поток нет.
Работало с такими настройками:

NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-ttl=0 --dpi-desync-ttl6=0 --dpi-desync-fooling=badsum"
NFQWS_OPT_DESYNC_HTTP="--dpi-desync=fake,split2 --dpi-desync-ttl=3"
NFQWS_OPT_DESYNC_HTTPS="--dpi-desync=fake,split2 --dpi-desync-ttl=3"

Пробовал такие тоже не работает:
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-ttl=4 --dpi-desync-ttl6=2 --dpi-desync-split-pos=1 --wssize 1:6 --dpi-desync-fooling=md5sig"

В GoodbyeDPI  сегодня тоже были изменения -9 на -e 2 -f 1 --reverse-frag. Возможно в запрете тоже стоит что-либо добавить?

**Comment by maximwarner** [comment]
Подтверждаю. Тоже Ростелеком. Сегодня днем перестало грузить. До этого все было настроено так, что грузило на Android TV, ПК и смартфоне моментально.

**Comment by KeepeR22rus** [comment]
> В --dpi-desync попробуйте убрать fake, оставьте split2 или disorder2

Спасибо, убрал fake, оставил split2, заработало.
