### ISSUE TITLE
mdig не работает опция stats

### ISSUE THREAD

**Issue by hobit26** [bol-van/zapret#379]
Не выводиться статистика
архитектура mips32r1-lsb
`/opt/zapret/mdig # echo ya.ru | ./mdig --threads 1 --family 4 --stats 1

77.88.44.242
77.88.55.242
5.255.255.242
mdig stats : 00:00:00 : domains=0 success=0 error=0
mdig stats : 00:00:00 : domains=0 success=0 error=0
`

**Comment by bol-van** [comment]
https://github.com/bol-van/zapret/commit/d014ffe0ba753567d5a2c5a2b34e0b8e7f3aadca
