### ISSUE TITLE
Подгрузка видео

### ISSUE THREAD

**Issue by ThisIsNoTa2acc** [bol-van/zapret#384]
теперь видео работают, но грузятся большими кусками и после того как большой кусок просмотрен идёт 5-10 секунд подгрузка нового куска, есть ли какие-либо советы на этот счет? актуально для мобильного приложения, браузерную версию не тестил

**Comment by eastone11** [comment]
Я так понимаю вот человек с такой же проблемой
https://github.com/bol-van/zapret/issues/373

**Comment by ThisIsNoTa2acc** [comment]
окей я в ReX отключил QUIC и вроде перестало тупить
