### ISSUE TITLE
crontab: can't open 'root': No such file or directory

### ISSUE THREAD

**Issue by Mikami382** [bol-van/zapret#39]
I noticed this error upon executing install_easy.sh on my OpenWRT device.

```
* adding crontab entry
crontab: can't open 'root': No such file or directory
```

Here are additional info regarding my device:
```
Hostname	OpenWrt
Model	Raspberry Pi 3 Model B Plus Rev 1.3
Architecture	?
Firmware Version	OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc)
Kernel Version	4.9.184
```

**Comment by bol-van** [comment]
It happens on fresh openwrt installation. No crontabs by default, /etc/crontab/root is missing.
I checked in this situation script successfully creates crontab 
You can ignore this message
