### ISSUE TITLE
Попытка подобрать конфиги аналогичные GoodbyeDPI -7 для Keenetic + бонус

### ISSUE THREAD

**Issue by FuryOfFools** [bol-van/zapret#390]
Пытался вместе с Chat GPT подобрать настройки аналогичные настройки GoodbyeDPI -7.

Получился такой список:
`--dpi-desync-split-http-req=method --dpi-desync-split-tls=sni --dpi-desync=fake,disorder --dpi-desync-fooling=badsum`

Скинул Chat GPT конфиги из GoodbyeDPI для -7 и все настройки zapret и вот что он выдал:
```
# Включение фрагментации HTTP и HTTPS
--dpi-desync-split-http-req=method
--dpi-desync-split-tls=sni

# Использование фейковых пакетов с некорректной TCP контрольной суммой
--dpi-desync=fake
--dpi-desync-fooling=badsum

# Фрагментация пакетов в обратном порядке
--dpi-desync=disorder
```

Настраивал на роутер Keenetic Giga по [гайду](https://telegra.ph/Nastrojka-zapret-ot-bol-van-na-Keenetic-08-18). 
Разве что пришлось вместо:
```
modprob xt_multiport
modprob xt_connbytes
modprob xt_NFQUEUE
```
Использовать это:
```
insmod /lib/modules/4.9-ndm-5/xt_multiport.ko
insmod /lib/modules/4.9-ndm-5/xt_connbytes.ko
insmod /lib/modules/4.9-ndm-5/xt_NFQUEUE.ko
```
И в zapret/ipset/zapret-host-user.txt я скопировал все ip из черных списков GoodbyeDPI.

Дополнительно настраивал в самом роутер vpn'ы (специфика работы), [comss](https://www.comss.ru/page.php?id=13072) (для доступа к ChatGPT, Claude и тд) в интернет фильтрах. Все работает и ничего не конфликтует, но я особо не пытался вникать в суть из-за своей "хлебушковости" в данном вопросе. Если тут есть знатоки можете дополнить или подправить.

**Comment by eastone11** [comment]
> Все работает и ничего не конфликтует

ну если у тебя всё работает, может тогда и не надо ничего править?

**Comment by bol-van** [comment]
```
# Ограничение обработки пакетов с полезной нагрузкой больше 1200 байт
--dpi-desync-cutoff=n1200
```

вы неверно поняли назначение этой опции
написана ерунда

**Comment by FuryOfFools** [comment]
> ```
> # Ограничение обработки пакетов с полезной нагрузкой больше 1200 байт
> --dpi-desync-cutoff=n1200
> ```
> 
> вы неверно поняли назначение этой опции написана ерунда

То есть по идее если ее убрать все будет ок? Как я сказал я не вникал и просто скормил конфиги нейронке

**Comment by bol-van** [comment]
Это ограничение на номер исходящего пакета  в соединении.
Используется с опцией --dpi-desync-any-protocol, чтобы не дурить бесконечно соединение.
Тоже самое делается в ядре linux гораздо более эффективно через connbytes, но в других системах connbytes отсутствует. 
Скрипты запрета ставят connbytes на значение в пределах 10, иногда в пределах 20, так что n1200 никогда не достигается.
Можно убрать

**Comment by FuryOfFools** [comment]
> Это ограничение на номер исходящего пакета в соединении. Используется с опцией --dpi-desync-any-protocol, чтобы не дурить бесконечно соединение. Тоже самое делается в ядре linux гораздо более эффективно через connbytes, но в других системах connbytes отсутствует. Скрипты запрета ставят connbytes на значение в пределах 10, иногда в пределах 20, так что n1200 никогда не достигается. Можно убрать.
> 
> Из-за наличия connbytes вообще нет смысла ограничивать верхний размер пакета. В windows у Валдика это сделано только как попытка заменить connbytes, чтобы как-то отсекать ненужные пакеты из обработки, экономя ресурсы процессора. Аналогичного фильтра в winws нет, потому что winws иногда нужно работать с пакетами максимального размера. Поддержка kyber

Окей я тогда подредачил пост, чтобы глаза не мозолило.

**Comment by bol-van** [comment]
# Фрагментация пакетов в обратном порядке
--dpi-desync=disorder

Вот тут еще не совсем так.
Фрагментация на 2 куска это disorder2.
disorder - это с фейками, заполненными нулями, между фрагментами

**Comment by bol-van** [comment]
-f 2 -e 2 --wrong-chksum --reverse-frag --max-payload

--dpi-desync=fake,disorder2 --dpi-desync-fooling=badsum

**Comment by FuryOfFools** [comment]
Не сработало почему-то. По итогу все опять переделал. Уже по [этому гайду](https://habr.com/ru/articles/834826/) и оно заработало!

Конфиги из коммента автора взял. Разве что список адресов все так же взял из GoodbyeDPI

> NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"
> 
> NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-ttl=0  --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_google_com.bin"

**Comment by eastone11** [comment]
Любимый крокодил бол-ван`а ))
