### ISSUE TITLE
Вопрос по работе tpws на keenetic. (seccomp: Invalid argument)

### ISSUE THREAD

**Issue by gyhxrr31** [bol-van/zapret#391]
В общем, заметил, странные сообщения в логах терминала, что при использовании tpws и nfqws в контексте работы скрипта blockcheck выдает следующее:
```
!!!!! AVAILABLE !!!!!
- checking nfqws --dpi-desync=syndata,disorder2
seccomp: Invalid argument
seccomp: this can be safely ignored if kernel does not support seccomp
```
Насколько это критично? Если критично, то как пофиксить? А так же я заметил, что ютуб(а именно для этого я ставлю запрет, чтоб ускорить ютуб), вообще не грузит видео, а грузит только картинки. Из изменений, только начинает работать rutracker.
Роутер Keenetic 4g (1212)

**Comment by bol-van** [comment]
Там же написано. Игнорировать.
Ядро не поддерживает песочницу seccomp, она не включается

**Comment by gyhxrr31** [comment]
> Там же написано. Игнорировать. Ядро не поддерживает песочницу seccomp, она не включается
Отлично, один вопрос решен, а как быть с тем, что какие бы не применялись стратегии обхода, работает лишь rutracker?

**Comment by bol-van** [comment]
Очевидно, проверять блокчеком другие сайты
а для ютуба есть особое требование к фейку, которое описано в теме про ютуб

**Comment by gyhxrr31** [comment]
> Очевидно, проверять блокчеком другие сайты а для ютуба есть особое требование к фейку, которое описано в теме про ютуб

Таки я использовал проверку блока с помощью скрипта, и указал домен x.com(твиттер), в итоге он нашел стратегии обхода, но так таковых изменений после указания этой стратегии нет. Сайт просто не грузит.
Прикрепляю еще лог файл с выводом скрипта. 
[blockcheck_log.txt](https://github.com/user-attachments/files/17005219/blockcheck_log.txt)

**Comment by bol-van** [comment]
тут вырезка, непонятно особо ничего
проверять надо с остановленным zapret-ом
и еще сайты это не только головной домен. см F12 в броузере откуда что загружается

**Comment by gyhxrr31** [comment]
> тут вырезка, непонятно особо ничего проверять надо с остановленным zapret-ом и еще сайты это не только головной домен. см F12 в броузере откуда что загружается

Хорошо, скину полный лог, от проверки блокировки  до  настройки скрипта

**Comment by lunedzy** [comment]
прогони blockcheck на force режиме. и да, советую использовать nfqws он более функциональнее в отличии от tpws

**Comment by gyhxrr31** [comment]
> прогони blockcheck на force режиме. и да, советую использовать nfqws он более функциональнее в отличии от tpws

Хорошо, сейчас попробую и лог пришлю. nfqws я и стараюсь использовать.

**Comment by gyhxrr31** [comment]
Вот логи блокчека и настройки запрета:
[blockcheck_log_force.txt](https://github.com/user-attachments/files/17005424/blockcheck_log_force.txt)
[setup_zapret_log.txt](https://github.com/user-attachments/files/17005431/setup_zapret_log.txt)

**Comment by bol-van** [comment]
Сам домен x.com заблокирован простеньким DPI, вероятно даже не ТСПУ, и обходится простым сплитом на позиции SNI
nfqws --dpi-desync=split2 --dpi-desync-split-tls=sni
checking tpws --split-tls=sni
но не обходится сплитом на позициях 1 и 2.

Но дело то не в самом x.com. Там еще куча доменов. См F12

**Comment by gyhxrr31** [comment]
Ладно, но почему то мне кажется, что запрет не корректно работает на кинетике, вот бы кто-нибудь помог с настройкой правильной, чтоб Ютуб работал.

**Comment by gyhxrr31** [comment]
> Сам домен x.com заблокирован простеньким DPI, вероятно даже не ТСПУ, и обходится простым сплитом на позиции SNI nfqws --dpi-desync=split2 --dpi-desync-split-tls=sni checking tpws --split-tls=sni но не обходится сплитом на позициях 1 и 2.
> 
> Но дело то не в самом x.com. Там еще куча доменов. См F12

Слушай, поставил стратегию обхода как из другого топика про кинетик, а он только рутрекер открывает, что за фигня?

**Comment by lunedzy** [comment]
> > Сам домен x.com заблокирован простеньким DPI, вероятно даже не ТСПУ, и обходится простым сплитом на позиции SNI nfqws --dpi-desync=split2 --dpi-desync-split-tls=sni checking tpws --split-tls=sni но не обходится сплитом на позициях 1 и 2.
> > Но дело то не в самом x.com. Там еще куча доменов. См F12
> 
> Слушай, поставил стратегию обхода как из другого топика про кинетик, а он только рутрекер открывает, что за фигня?

прочитай пожалуйста мануал от bol-van'a, а копировать чужие стратегии учитывая что у них другие провайдеры - глупо. каждая стратегия - индивидуальная под твой провайдер.

**Comment by Programator63** [comment]
После обновления Zapret он перестала запускаться. Удалив файл 10-inherit-nfqws, мне удалось запустить снова, но теперь перестали открываться заблокированные сайты. Роутер кинетик
Конфиг:
[config.txt](https://github.com/user-attachments/files/18273369/config.txt)
