### ISSUE TITLE
win11 ошибочно определяет Zapret как вирус Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by almirus** [bol-van/zapret#393]
и удаляет скаченный master

![image](https://github.com/user-attachments/assets/6d17cb8d-c9e8-49a2-9d26-0701b7fd6a2f)

**Comment by bol-van** [comment]
Ну определяет и определяет. Что с этим можно сделать ?
На upx он реагирует. Убирать его не буду только из-за отдельно взятого антивируса, у которого едут мозги

**Comment by iRadioMan** [comment]
Как обычно, говорю: любой антивирус больше создает проблем, чем приносит пользы. Если вы уверенный в себе пользователь, отключайте все антивирусы (особенно Виндовый кусок гамна)

**Comment by xtcorp** [comment]
> Как обычно, говорю: любой антивирус больше создает проблем, чем приносит пользы. Если вы уверенный в себе пользователь, отключайте все антивирусы (особенно Виндовый кусок гамна)

Еще и комп спасибо скажет, дышать начнет

**Comment by lunedzy** [comment]
антивирусы вообще надо вырубать, мало того что они грузят систему так и еще реагируют чуть ли не на каждый скрипт.
в твоем случае решение только его отключить, а желательно вырезать вообще из системы)

**Comment by zhubr** [comment]
> Ну определяет и определяет. Что с этим можно сделать ? На upx он реагирует. Убирать его не буду только из-за отдельно взятого антивируса, у которого едут мозги

Нет, не на upx. Зачастую defender просто утюжит любые заранее незнакомые ему файлы любого формата и содержания, в которых ну может 1-2 байта случайно напомнили ему какой-то вирус, насколько бы абсурдно это не выглядело. Не стоит тратить время вообще.

**Comment by FrantsuzovDmitry** [comment]
> Как обычно, говорю: любой антивирус больше создает проблем, чем приносит пользы. Если вы уверенный в себе пользователь, отключайте все антивирусы (особенно Виндовый кусок гамна)

Не вводите людей в замешательство и не рекомендуйте отключать антивирусы. "Уверенный пользователь пениса и хорошей реакции презервативами не пользуется". А потом алименты платит или детей растит.

**Comment by zhubr** [comment]
> Не вводите людей в замешательство и не рекомендуйте отключать антивирусы. "Уверенный пользователь пениса и хорошей реакции презервативами не пользуется". А потом алименты платит или детей растит.

Безумие Defender'а (о котором речь в заголовке) общеизвестно и подтверждается вполне хорошо. Автору пакета нечего здесь исправлять и неоткуда удалять wacatc, т.к. это галлюцинации антивируса. Если пользователь хочет применить файлы из релиза, то ему необходимо как-то решить свою проблему. Отключить антивирус, по крайней мере временно, это вполне разумное решение, особенно если он понимает, что файлы не предназначены для запуска в windows и не будут там работать, т.к. они идут на маршрутизатор, а в нём wacatac не особо уживётся, LOL.

**Comment by NewUse** [comment]
речь вроде бы идёт о виндовой проксе, по этому достаточно поместить её в исключения антивируса.

**Comment by lunedzy** [comment]
> > Как обычно, говорю: любой антивирус больше создает проблем, чем приносит пользы. Если вы уверенный в себе пользователь, отключайте все антивирусы (особенно Виндовый кусок гамна)
> 
> Не вводите людей в замешательство и не рекомендуйте отключать антивирусы. "Уверенный пользователь пениса и хорошей реакции презервативами не пользуется". А потом алименты платит или детей растит.

антивирусы созданы для людей которые качают что попало, не понимая последствия. для продвинутых юзеров дефендеры и прочие антивирусы вообще не нужны ) в случае автора дефендер сработал ложно, и таких случаев куча

**Comment by zhubr** [comment]
> речь вроде бы идёт о виндовой проксе, по этому достаточно поместить её в исключения антивируса.

Речь идет о программах, не имеющих к винде вообще никакого отношения и не запускающихся в ней никогда. Для временного промежуточного хранения этих файлов винда может использоваться, просто как накопитель, если конечно Defender не сожрёт их тем временем, но это уж как повезёт.

**Comment by Rimuru205** [comment]
Не работает захожу в дс пишет Старт

**Comment by NewUse** [comment]
д 

> Не работает захожу в дс пишет Старт

сначала настрой обычный обход, чтоб на какой-нибудь рутрекер заходил, гайд в зубы и вперё

**Comment by atuc-7** [comment]
яндекс браузер не дает это загрузить

**Comment by djbiton** [comment]
Старый скрипт с горем попалам иногда срабатывает. На новый антивирус сильно ругаеться. Но я на столько не доверяю своему компу что что не могу позволить отключать антивирус. Нет, опечатки нет. Если ты не доверяешь компу и не может в эту минуту выкинуть системник в форточку, то ты не можешь доверять ему. Можешь доверять? Можешь отформатировать и не жалеть о потерях? Зачет
