### ISSUE TITLE
бинарники не запускаются под openwrt на процессоре Geode(TM) Integrated Processor by AMD PCS

### ISSUE THREAD

**Issue by Evgen2803** [bol-van/zapret#394]
Есть железка PC Engines ALIX на ней стоит openwrt. Пишут что проц AMD Geode совметим x86.
`# cat /proc/cpuinfo`
`processor       : 0`
`vendor_id       : AuthenticAMD`
`cpu family      : 5`
`model           : 10`
`model name      : Geode(TM) Integrated Processor by AMD PCS`
`stepping        : 2`
`cpu MHz         : 498.046`
`cache size      : 128 KB`
`fdiv_bug        : no`
`f00f_bug        : no`
`coma_bug        : no`
`fpu             : yes`
`fpu_exception   : yes`
`cpuid level     : 1`
`wp              : yes`
`flags           : fpu de pse tsc msr cx8 sep pge cmov clflush mmx mmxext 3dnowext 3dnow cpuid 3dnowprefetch vmmcall`
`bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass`
`bogomips        : 996.09`
`clflush size    : 32`
`cache_alignment : 32`
`address sizes   : 32 bits physical, 32 bits virtual`
`power management:`

`# ./install_bin.sh`
`x86_64 is NOT OK`
`x86 is NOT OK`
`aarch64 is NOT OK`
`arm is NOT OK`
`mips64r2-msb is NOT OK`
`mips32r1-lsb is NOT OK`
`mips32r1-msb is NOT OK`
`ppc is NOT OK`
`no compatible binaries found`

Architecture	Geode(TM) Integrated Processor by AMD PCS
Target Platform	x86/geode
Firmware Version	OpenWrt 23.05.4 r24012-d8dd03c46f / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38

Подскажите где раздобыть бинарники под эту железку?

**Comment by bol-van** [comment]
Что выводится на это ?
uname -a
/opt/zapret/binaries/x86/tpws -h

**Comment by Evgen2803** [comment]
uname -a
Linux nsk-w3 5.15.162 #0 Mon Jul 15 22:14:18 2024 i586 GNU/Linux
/tmp/zapret-master/binaries/x86/tpws
Illegal instruction

**Comment by bol-van** [comment]
Попробуйте распаковать бинарик через upx -d
https://upx.github.io/

**Comment by bol-van** [comment]
>  Generic is for 32-bit-only hardware (either old hardware or some Atom processors), should be i686 Linux architecture, will work on Pentium 4 and later. Use this only if your hardware can't run the 64-bit version.
> Legacy is for very old PC hardware, Pentium MMX, what is called i586 in Linux architecture support. It will miss a lot of features you want/need on modern hardware like multi-core support and support for more than 4GB of RAM, but will actually run on ancient hardware while other versions will not.
> Geode is a custom Legacy target customized for Geode SoCs, which are still in use in many (aging) networking devices, like the older Alix boards from PCEngines.
> 

У меня собрано под generic. Видимо, надо legacy

**Comment by Evgen2803** [comment]
./upx -d /tmp/zapret-master/binaries/x86/tpws
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.4       Markus Oberhumer, Laszlo Molnar & John Reiser    May 9th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    222074 <-    102312   46.07%   linux/i386    tpws

Unpacked 1 file.

/tmp/zapret-master/binaries/x86/tpws
Illegal instruction

Видимо под этот legacy проц только пересборка поможет.

**Comment by bol-van** [comment]
Пересобрал, пробуйте

**Comment by Evgen2803** [comment]
./tpws
Need port number
Красота. Спасибо большое.
