### ISSUE TITLE
Ошибка ERR_SSL_PROTOCOL_ERROR на определенном сайте

### ISSUE THREAD

**Issue by VanishGer** [bol-van/zapret#398]
Настроил на Кинетике по инструкции с Хабра https://habr.com/ru/articles/834826/

Обход для заблокированных сайтов работает, но есть проблема с одним сайтом (Веб-морда PaloAlto).
При выключенном Zapret сайт открывается и VPN подключается.
Если включишь Zapret - сайт выдает ошибку ERR_SSL_PROTOCOL_ERROR и не подключается ВПН через Global Protect.

В список исключений адреса закинул - ошибка остается.
Как можно попробовать решить это ?

![image](https://github.com/user-attachments/assets/af89054e-54be-4174-863f-ae197dac42f4)

**Comment by VanishGer** [comment]
Добавлю.
Ошибка появляется в режиме фильтрации hostlist.
В режимах ipset и none сайт долго не отвечает и спустя минуту выдает ERR_CONNECTION_RESET.

**Comment by eastone11** [comment]
конфиг бы кинули

**Comment by eastone11** [comment]
у меня кстати на этот сайт просто fairfox рёт без запрета

**Comment by VanishGer** [comment]
[config.txt](https://github.com/user-attachments/files/17024555/config.txt)
Этот сайт работает без ВПН и Zapret. Но выключать их ради одного сайта - очень неудобно

**Comment by VanishGer** [comment]
Каюсь, нашел свою же ошибку.
Не обновил списки
/opt/zapret/ipset/clear_lists.sh
/opt/zapret/ipset/get_config.sh

**Comment by wildburn** [comment]
> Каюсь, нашел свою же ошибку. Не обновил списки /opt/zapret/ipset/clear_lists.sh /opt/zapret/ipset/get_config.sh

Их просто в конфиг прописать для фикса? в getlist в самый конец?

**Comment by wildburn** [comment]
> > Каюсь, нашел свою же ошибку. Не обновил списки /opt/zapret/ipset/clear_lists.sh /opt/zapret/ipset/get_config.sh
> 
> Их просто в конфиг прописать для фикса? в getlist в самый конец?

Ровно такая же проблема как и у вас
