### ISSUE TITLE
I've Android Rooted device & so excited to test the Android release.

### ISSUE THREAD

**Issue by hamedsbt** [bol-van/zapret#40]
Hello, I'm a professional Android user and my device is Oneplus One with Android Pie, Rooted (Magisk , exposed and dnscrypt)

Magisk? https://forum.xda-developers.com/apps/magisk
Xposed? https://github.com/ElderDrivers/EdXposed
DNScrypt? https://github.com/jedisct1/dnscrypt-proxy

So I'm ready to run, test and report debug log to help for build up stable release for Android app and help to people for access to uncensored internet.

Also I've a suggestion: Please review the Fragmenting SSL ClientHello project too, it may teach you more tricks that currently working (at least in my country)

Thank you.

**Comment by bol-van** [comment]
Hi. 

At the moment there's no end-user GUI app for android.
All you can test is tpws with manual iptables. Both console, both require root (except socks mode of tpws).
tpws can fragment any TCP payload. use --split-pos option. Unfortunately its not possible to change any byte in TLS sessions without breaking it. To do so, one need to modify client software or terminate TLS , handling all certificate issues

**Comment by hamedsbt** [comment]
Thank you for your reply.
Did you see: https://github.com/prodeveloper0/FuckDPI_V2 it's working on windows and Fragmenting SSL ClientHello.

I don't test zapret binary on my Android device. does it run/work correctly on Android?

**Comment by bol-van** [comment]
Yes, I tested it and it works. With some notices, see readme

**Comment by bol-van** [comment]
I translated this notice to readme.eng.txt

**Comment by hamedsbt** [comment]
use command: 
```iptables -t mangle -I PREROUTING -p tcp --sport 80 --tcp-flags SYN,ACK SYN,ACK -j NFQUEUE --queue-num 200 --queue-bypass```
but not be able to bypass DPI, so try command:
```iptables -t mangle -I POSTROUTING -p tcp --dport 80 -m set --match-set zapret dst -j NFQUEUE --queue-num 200 --queue-bypass```
but error: 
iptables v1.6.1: Kernel module xt_set is not loaded in

**Comment by bol-van** [comment]
Android stock kernel does not include nfqueue and ipset
Theoretically you can recompile kernel or get kernel source, but practically its not always possible to get correct source code and its quite hard to recompile. Also, some android kernels are 100% monolitic with module support disabled. You're most lucky if you can run custom rom or kernel, for example from lineage os.

Without ipset everything yo can is redirect unconditionally or ips/subnets from individual rules (not too many)

**Comment by hamedsbt** [comment]
I'm on lineage, test with other custom kernel like: Argon v16.1 but get same error :'( 
Can you guide me about **redirect unconditionally or ips/subnets from individual rules** please!

**Comment by bol-van** [comment]
I doubt any default android kernel has built-in ipset or nfq.
Without recompiling and reflashing no luck on almost any rom.

Google iptables tutorial, its very basic knowledge

iptables ... -d 1.2.3.0/24

**Comment by bol-van** [comment]
Do it if you can. May be you will learn you cant
