### ISSUE TITLE
Вопрос по обновлению

### ISSUE THREAD

**Issue by araik1998** [bol-van/zapret#406]
Всем привет,извините, что пишу в issues. Подскажите, пожалуйста, чтобы обновить zapret надо просто повторно разархивировать [zapret.git](https://github.com/bol-van/zapret.git) и всё?

**Comment by bol-van** [comment]
Зависит от системы
Если linux/openwrt, то аналогично начальной установке.
Если было подтянуто через git, то git pull.
Если другая система и не git, то через замену файлов
