### ISSUE TITLE
Install on openWRT Error: build tools not found

### ISSUE THREAD

**Issue by hamedsbt** [bol-van/zapret#41]
**install_easy.sh:**
```
root@OpenWrt:/# /tmp/zapret/install_easy.sh
* checking system
system is based on openwrt
* checking executables
build tools not found
press enter to continue
```

**install_bin.sh:** 
```
root@OpenWrt:/# /tmp/zapret/install_bin.sh
x86_64 is NOT OK
x86 is NOT OK
aarch64 is NOT OK
armhf is NOT OK
mips64r2-msb is NOT OK
mips32r1-lsb is NOT OK
mips32r1-msb is NOT OK
ppc is NOT OK
```

How fix it?

**Comment by bol-van** [comment]
What's your device model ?

cat /proc/cpuinfo
cat /etc/board.json

**Comment by bol-van** [comment]
Check executable permissions on files inside binaries/<arch>
may be you lost them during archive repack or something like that

**Comment by hamedsbt** [comment]
Thank you for fast reply. I add 777 permission to all files and install_easy working.

**Comment by bol-van** [comment]
777 is bad practice, because this way you grant everyone to write files executed by root
some daemons run as non-root
755 is enough

**Comment by hamedsbt** [comment]
> 777 is bad practice, because this way you grant everyone to write files executed by root
> some daemons run as non-root
> 755 is enough

Thank you for your advice. Can I delete all source files from ``` zapret-master/* ``` ?!
