### ISSUE TITLE
предложение - программная альтернатива Google Global Cache

### ISSUE THREAD

**Issue by kotsmotritnastul** [bol-van/zapret#410]
я знаю что тут бывает достаточно много программистов и не знаю где ещё написать чтобы заметили. насколько сложно будет написать программу которая создаст на компах простых людей альтернативу GGC? велика вероятность что в конечном итоге РКН банально забанит все российские, а возможно и все мировые GGC по айпи и обойти этот блок ни гудбаем ни запретом будет нельзя.

конечно вы можете сказать что можно использовать впн но это имущественный ценз на пользование ютубом в стране где большинство получает около 200 долларов в месяц, и кроме того впн-сервера регулярно банят, впн-сервер это единая точка отказа, хозяин впн может запретить трафик к ютубу увидев нагрузку на узел, скорость впна часто ниже чем провайдерская, да и оплатить впн российской картой это тот ещё геморрой, а регистрировать зарубежную ещё больший геморрой для большинства.

как может работать программа создающая альтернативу GGC:
1) программа открывает порт на компе и служит прокси-сервером.
2) браузер запрашивает у программы видеоролик
3) программа запрашивает через DHT у кого из простых людей есть этот ролик (идентификатором можно сделать не хеш а ID видео вида `JQy2NMkg82A`)
4) программа посылает браузеру пользователя видео а сама кеширует его на диске пользователя чтобы другие могли скачать и с этого пользователя тоже.

такой принцип уже реализован здесь https://ru.wikipedia.org/wiki/Freenet но там сеть медленная из-за анонимизации и шифрования, а тут ничего шифровать не нужно, всё что требуется от пользователя - открыть порт на роутере чтобы иметь возможность раздавать кешированные ролики и много места на диске.

к сожалению я сам не программист и не смогу создать такую программу, тем более не смогу её поддерживать в плане багфиксов. но может быть кто-нибудь заметит это предложение и сделает что-то подобное.

**Comment by ThisIsNoTa2acc** [comment]
бля чел ебать ты гений, ты по сути описал торренты

**Comment by kotsmotritnastul** [comment]
в торентах нет такой автоматизации как во фринете и peertube. в торентах ты хранишь только то что тебе надо и ставишь на закачку/раздачу вручную, во фринете ты указываешь количество свободного места которое не жалко отдать под хранилище и кусочки файлов которые нужны людям автоматически скачиваются и раздаются.

сравнивать такое с торентами это всё равно что сравнивать ггц с фтп-сервером на который надо руками заливать видосы.

**Comment by ThisIsNoTa2acc** [comment]
> в торентах нет такой автоматизации как во фринете и peertube. в торентах ты хранишь только то что тебе надо и ставишь на закачку/раздачу вручную, во фринете ты указываешь количество свободного места которое не жалко отдать под хранилище и кусочки файлов которые нужны людям автоматически скачиваются и раздаются.
> 
> сравнивать такое с торентами это всё равно что сравнивать ггц с фтп-сервером на который надо руками заливать видосы.

Ты слову "по сути" увидел?

**Comment by kotsmotritnastul** [comment]
это не торенты а сеть кеширующих серверов на компах физлиц, ещё раз говорю. с тем же успехом сквид и фринет это тоже торенты.

**Comment by k0zyrev** [comment]
то, что вы описываете https://github.com/Chocobozzz/PeerTube

Если с поиском бесплатных впн у вас проблемы, всегда можно установить тор.
