### ISSUE TITLE
Running multiple instances for specific websites

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [bol-van/zapret#414]
Hello, I was wondering if it's possible to run multiple instances of zapret with different settings. My current settings work with almost every site but one or two requires completely different settings. I have to install zapret on my device just for those websites instead of relying on my router. Is there a way to counter this? Thanks in advance.

**Comment by k0zyrev** [comment]
https://github.com/bol-van/zapret/blob/master/docs/readme.eng.md#multiple-strategies

That feature was just recently added

**Comment by EmiliaTheGoddess** [comment]
That is exactly what I needed. Thank you!
