### ISSUE TITLE
Убрать rutracker из блокчека

### ISSUE THREAD

**Issue by electrifying** [bol-van/zapret#417]
по умолчанию в блокчеке идет тест рутрекера, но они похоже ушли на ECH. Портал открывается без всяких обходов сейчас на любом провайдере и мобильных тоже. Поэтому я думаю будет корректно поправить блокчек что бы тестировался какой-то другой домен по умолчанию

**Comment by bol-van** [comment]
curl ECH не поддерживает, так что нормально все

**Comment by bol-van** [comment]
Если быть точнее, у curl есть поддержка ech.
Но он должен быть собран с этой опцией, крипто-библиотека должна ее поддерживать, и даже в этом случае требуется указать специальный параметр в команде для включения и DoH сервер.

`curl --http3-only --ech hard --tlsv1.3 --doh-url https://cloudflare-dns.com/dns-query -v -4 https://rutracker.org/`

blockcheck не включает ech, поэтому запрос будет без него даже, если у курла есть поддержка ECH
