### ISSUE TITLE
Не работает blockcheck на OpenWRT 

### ISSUE THREAD

**Issue by bropines** [bol-van/zapret#419]
При проверке любого сайта такое

```bash
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
UNAVAILABLE code=60
- checking tpws --split-tls=sniext --oob
curl: (60) Cert verify failed: BADCERT_CN_MISMATCH
More details here: https://curl.se/docs/sslcerts.html
```

**Comment by bol-van** [comment]
Вероятно идет подмена сертификата от провайдера
Я бы попробовал дернуть curl с опцией игнора сертификата
curl -k https://website
и посмотреть что там возвращается. не заглушка ли

**Comment by bropines** [comment]
Такое выдало
```bash
root@OpenWrt:~/tmp# curl -k pixiv.net
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by bol-van** [comment]
Так он по http идет. Надо https.

pixiv у меня выдает нормальный сертификат. с VPS тоже

**Comment by bropines** [comment]
> Так он по http идет. Надо https.
> 
> pixiv у меня выдает нормальный сертификат. с VPS тоже

Не особо понял. Мне на блок чеке прописать не просто домен а https? или как?

**Comment by bropines** [comment]
есть идеи как мне это починить или лучше мне идти на ntc party?

**Comment by Pjatruha** [comment]
У меня тоже не работает.

`
root@OpenWrt:/mnt/ntfs/zapret# /mnt/ntfs/zapret/install_bin.sh
x86_64 is NOT OK
x86 is NOT OK
aarch64 is NOT OK
arm is NOT OK
mips64r2-msb is NOT OK
/mnt/ntfs/zapret/binaries/mips32r1-lsb/ip2net is absent
mips32r1-lsb is NOT OK
mips32r1-msb is NOT OK
/mnt/ntfs/zapret/binaries/ppc/ip2net is absent
ppc is NOT OK
no compatible binaries found
root@OpenWrt:/mnt/ntfs/zapret# make -C "/mnt/ntfs/zapret"
-ash: make: not found
root@OpenWrt:/mnt/ntfs/zapret# /mnt/ntfs/zapret/blockcheck.sh
* checking system
Linux detected
firewall type is iptables
* checking privileges
* checking prerequisites
/mnt/ntfs/zapret/nfq/nfqws or /mnt/ntfs/zapret/tpws/tpws or /mnt/ntfs/zapret/mdig/mdig is not available. run "/mnt/ntfs/zapret/install_bin.sh" or `make -C "/mnt/ntfs/zapret" `

press enter to continue

root@OpenWrt:/mnt/ntfs/zapret# cat /proc/cpuinfo
system type             : Ralink RT3352 id:1 rev:6
machine                 : Rostelecom RT-V4L1USBn
processor               : 0
cpu model               : MIPS 24KEc V4.12
BogoMIPS                : 265.98
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc perf_cntr_intr_bit perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
`
Подскажите, как решить эту проблему?

**Comment by NewUse** [comment]
тебе же написали комманду, почему ты не можешь её скопипастить и показать вывод?

**Comment by bropines** [comment]
> тебе же написали комманду, почему ты не можешь её скопипастить и показать вывод?

Если на то пошло, то он выводит тупо страницу провайдера со словами тебе тут делать нечего, 
В этом посте это описал
https://ntc.party/t/%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BD%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%81%D0%B2%D1%8F%D0%B7%D0%B8-byedpi-%D0%B8-%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%82/10664/9

**Comment by user26092024** [comment]
> Все попытки прогнать zapret кончится ошибкой описанной у самом начале. Или он тупо не проходит дальше страницы блокировки от Интерсвязи

попробуйте curl, libcurl4 обновить на последние версии, у меня блокчек не работал, правда с другой ошибкой, но попытка - не пытка.

**Comment by NewUse** [comment]
> Все попытки прогнать zapret кончится ошибкой описанной у самом начале. Или он тупо не проходит дальше страницы блокировки от Интерсвязи

не проходит, очевидно, но а разрешённый интернет то есть? пробовал ya.ru проверить блокчеком? вообще, похоже у тебя там dpi, который в разрыве ставится, его не обойти .

**Comment by bropines** [comment]
Короче решается тупо, беем и ставим doh сервера dns. Увы провайдер не умеет подменять шифрованные днски.
