### ISSUE TITLE
Подбор аргументов nfqws на Keenetic

### ISSUE THREAD

**Issue by sub-kek** [bol-van/zapret#421]
Подбирая аргументы мне удалось прийти к чему-то такому
```
NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-ttl=-1 --dpi-desync-fooling=badsum,md5sig --dpi-desync-repeats=8 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_gosuslugi_ru.bin"
```

Тестировал на сайтах (думаю этого достаточно):
```
maintracker.org // Какой-то невыкупленный домен который почему-то заблокирован :D // работает
fbk.info // Работает
prostovpn.org // Работает
rbc.ua // Работает
meta.com // Работает
youtube.com // Работает
facebook.com // Не работает
```

Вот хотелось бы спросить. Как можно заставить работать facebook и fbcdn.net, ведь они отлично работают при определенной настройке. И насколько те аргументы что я подобрал адекватны?

сейчас на QUIC у меня заглушка которая вроде как-то отрабатывает и нет:
```
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fooling=md5sig --dpi-desync-repeats=8 --dpi-desync-autottl=1:2:8"
```
Возможно с ней тоже что-то стоит сделать.

**Comment by PaladinCVM** [comment]
В последней версии добавился параметр --new, после которого можно определить дополнительные настройки к отдельному хостлисту

**Comment by lunedzy** [comment]
обойти сразу все сайты у тебя не получится, в этом и особенность обхода DPI и от TTL.
аргументы впринципе - адекватны..
--dpi-desync-fooling=badsum,md5sig (я бы заменил с badsum на badseq)

**Comment by bol-van** [comment]
> NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-ttl=-1 --dpi-desync-fooling=badsum,md5sig --dpi-desync-repeats=8 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_gosuslugi_ru.bin"

ttl=-1 означает ttl=255. совершенно не адекватно для фейка. лучше убирать этот параметр вообще, особенно учитывая мощный fooling (проверен ли он ?)

> NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fooling=md5sig --dpi-desync-repeats=8 --dpi-desync-autottl=1:2:8"

ttl для quic может сломать chrome

**Comment by gyhxrr31** [comment]
Хм, странно, а почему у меня на кинетике не работают такие аргументы, максимум что открывается это рутрекер

**Comment by sub-kek** [comment]
> Хм, странно, а почему у меня на кинетике не работают такие аргументы, максимум что открывается это рутрекер

У провайдеров может быть разное оборудование. И может быть так что ТСПУ стоят как у магистрала так и у провайдера.

**Comment by sub-kek** [comment]
> обойти сразу все сайты у тебя не получится, в этом и особенность обхода DPI и от TTL. аргументы впринципе - адекватны.. --dpi-desync-fooling=badsum,md5sig (я бы заменил с badsum на badseq)

На телевизоре сеть практически не работает в моем случае, если ставить badseq

**Comment by sub-kek** [comment]
> > NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-ttl=-1 --dpi-desync-fooling=badsum,md5sig --dpi-desync-repeats=8 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_gosuslugi_ru.bin"
> 
> ttl=-1 означает ttl=255. совершенно не адекватно для фейка. лучше убирать этот параметр вообще, особенно учитывая мощный fooling (проверен ли он ?)
> 
> > NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fooling=md5sig --dpi-desync-repeats=8 --dpi-desync-autottl=1:2:8"
> 
> ttl для quic может сломать chrome. md5sig неприменим к udp

Мне удалось сделать работу сети более стабильной снизив ttl и поменяв fooling на quic. Вопрос по поводу autohostlist нужно чтобы на устойствах стоял DNS роутера?

**Comment by bol-van** [comment]
> Мне удалось сделать работу сети более стабильной снизив ttl и поменяв fooling на quic
Вера в немыслимое тоже иногда срабатывает. md5sig - это опция TCP пакета, в udp ее просто некуда засовывать
а ttl может только породить ответный icmp, который система воспримет как ошибку
не все роутеры на всех хопах возвращают icmp, может потому и работает

> Вопрос по поводу autohostlist нужно чтобы на устройствах стоял DNS роутера?

никак не связано
