### ISSUE TITLE
Через 1-3 минуты вылетает онлайн игра, как то можно это исправить?

### ISSUE THREAD

**Issue by Denirvan** [bol-van/zapret#424]
Здравствуйте! Раньше я использовал GoodbyeDPI, ютуб работал, но меня не устраивало что не работают некоторые сайты, тогда я перешел на zapret и все стало работать (ютуб и нужные мне сайты), но когда я захожу в свою любимую онлайн игру, то через 1-3 минуты она вылетает с формулировкой разрыв соединения, в  GoodbyeDPI такого не было, как то можно в запрете исправуить этот момент?

**Comment by lunedzy** [comment]
очень глупый вопрос, переустанавливайте zapret и ставьте правильно по мануалу от bol-van'a..
никаких логов, никакой информации.. каким образом мы поймем в чем проблема? бред..

**Comment by iRadioMan** [comment]
Используйте hostlist'ы, чтобы отсеивать только нужные сайты от всего остального

**Comment by FordeD** [comment]
> очень глупый вопрос, переустанавливайте zapret и ставьте правильно по мануалу от bol-van'a.. никаких логов, никакой информации.. каким образом мы поймем в чем проблема? бред..

Такая же проблема, если подскажешь как включить логи и дать хоть какую-нибудь инфу то буду благодарен и добавлю сюда чтобы разобрать или сам понять смогу. 

Если вкратце то просто идут ошибки по таймауту, из-за этого вылетает

**Comment by eastone11** [comment]
> > очень глупый вопрос, переустанавливайте zapret и ставьте правильно по мануалу от bol-van'a.. никаких логов, никакой информации.. каким образом мы поймем в чем проблема? бред..
> 
> Такая же проблема, если подскажешь как включить логи и дать хоть какую-нибудь инфу то буду благодарен и добавлю сюда чтобы разобрать или сам понять смогу.
> 
> Если вкратце то просто идут ошибки по таймауту, из-за этого вылетает

в ридми ищите по --debug
