### ISSUE TITLE
ubuntu в качестве шлюза zapret

### ISSUE THREAD

**Issue by nobody7356** [bol-van/zapret#426]
на виртуалке убунту установлен запрет, с самой виртуалки обход блокировок работает, но использовать эту убунту с соседней машины в качестве шлюза для запрет не получается (net.ipv4.ip_forward=1 включено), просто ходить через нее в интернет получается, но запрет не срабатывает.

**Comment by nobody7356** [comment]
`sudo iptables -t nat -A POSTROUTING -o ens160 -j MASQUERADE`

**Comment by fa1ke5** [comment]
ens160 это что за интерфейс? та-же проблема домашний сервак на убунте, локально на серваке все едет, а клиентские компы нет

**Comment by nobody7356** [comment]
> ens160 это что за интерфейс? та-же проблема домашний сервак на убунте, локально на серваке все едет, а клиентские компы нет

Это сетевой интерфейс, он на машине один, туда приходит лан. 

Я делал на 16 убунте, там iptables.

чтобы заработало на других машинах этой сети через этот хост, нужно:

1. На хосте разрешить форвардинг
2. На хосте настроить NAT
3. На других машинах установить этот хост в качестве шлюза по умолчанию

**Comment by bol-van** [comment]
если сделано в режиме моста - там отдельная история
и требуются отдельные действия, в тч на основном шлюзе

если как роутер с отдельной подсетью - для начала настройте сам роутер
об этом много инструкций в инете
когда будет лан и ван интерфейсы запрет должен заработать
только правильно нужно их указать в конфиге или инсталяторе

**Comment by nobody7356** [comment]
> если сделано в режиме моста - там отдельная история и требуются отдельные действия, в тч на основном шлюзе
> 
> если как роутер с отдельной подсетью - для начала настройте сам роутер об этом много инструкций в инете когда будет лан и ван интерфейсы запрет должен заработать только правильно нужно их указать в конфиге или инсталяторе

в моем случае отдельных подсетей нет, убунту выступает в качестве шлюза и форвардит трафик на основной шлюз, другие машины просто вместо основного шлюза используют убунту эту.

**Comment by bol-van** [comment]
просто так не взлетит такой сетап
надо отключать icmp  redirect на убунте
иначе он форварднет клиента на  default gw
но проблема еще в том, что взодящий трафик приходит с  default gw
сразу на клиент, минуя убунту
и от этого будут проблемы с коннтрак и коннбайтс, используемые в  скриптах
и некоторые входящие нужны для  nfqws в некоторых режимах
надо делать отдельную подсеть, чтобы избежать этого гемора
или можно попытаться на убунту повесить тпвс для локализации всего трафа

**Comment by bol-van** [comment]
возможно вместо тпвс поможет snat/masquerade

**Comment by nobody7356** [comment]
такой сетап работает, когда хост ubuntu с запрет в одной локальной сети "потребителями", они просто используют его в качестве шлюза, а он уже форвардит на шлюз этой сети, т.к. на нем MASQUERADE, все пакеты идут обратно тоже через него.

**Comment by bol-van** [comment]
так и не понял
работает nfqws или не работает ?
если нет, что в дебаг логе ? он получает пакеты ?

**Comment by nobody7356** [comment]
да все работает, после как в включил  `MASQUERADE `, речь о том что на убунту нет никаких подсетей, дефлот после исталяляции + запрет и его iptables правила + MASQUERADE + net.ipv4.ip_forward=1, это все что нужно для такого шлюза
