### ISSUE TITLE
Bad value for "--uid-owner" option: "tpws"

### ISSUE THREAD

**Issue by hamedsbt** [bol-van/zapret#43]
Command:
```
iptables -t nat -I OUTPUT -p tcp --dport 80 -m owner ! --uid-owner tpws -j DNAT --to 127.0.0.1:1188
```
Return error:
iptables v1.6.1: owner: **Bad value** for "--uid-owner" option: "tpws"

**Comment by bol-van** [comment]
If you want me to spend time answering your questions, pls be more informative.
I dont know what device you execute command on
Its obvious user tpws does not exist
If its android then PLS READ manual

**Comment by hamedsbt** [comment]
sorry for my not informative question, I'm using android v9 and the custom kernel support the xt_set module.
I read the en doc (and review again), did you explain about "tpws user" on android ?!

**Comment by bol-van** [comment]
Quote from Android section of readme.eng.txt : 

> Android does not use /etc/passwd, tpws --user won't work. There's replacement.
> Use numeric uids in --uid option.
> Its recommended to use gid 3003 (AID_INET), otherwise tpws will not have inet access.
> Example : --uid 1:3003

**Comment by hamedsbt** [comment]
issued commands: 
iptables:
``` iptables -t nat -I OUTPUT -p tcp --dport 80 -m owner ! --uid-owner --uid 1:3003 -j DNAT --to 127.0.0.1:1188 ```

tpws: 
``` tpws --bind-addr=0.0.0.0 --port=1188 --uid 1:3003 --split-pos=3 --no-resolve --hostspell=HoSt --hostdot --hosttab --hostnospace --hostpad=5 --methodspace --methodeol ```

When I try to connect from other device to this transparent proxy, get log: 

Running as UID=1 GID=3003
Will listen to port 1188
transparent proxy mode
Original destination for socket fd=5 : 192.168.37.2:1188
Dropping connection to local address to the **same port to avoid loop, Failed to add connection**

**Comment by bol-van** [comment]
Its *transparent* proxy. Its not supposed to be connected this way.
Router intercepts connections from client and redirects them to transparent proxy
If you want connect directly to proxy, then use --socks option without iptables
