### ISSUE TITLE
не пробиться к x.com

### ISSUE THREAD

**Issue by all504** [bol-van/zapret#431]
Прошу помощи.
Запрет открыл все кроме linkedin и x.com
Пинг и traceroute оба домена проходят, а по curl ни один не проходит.

Уже голову сломал, не понимаю как обойти запрет по IP провайдера. Видимо что-то очень топорное

**Comment by MasterHome** [comment]
Использовать VPN?

**Comment by eastone11** [comment]
> Прошу помощи. Запрет открыл все кроме linkedin и x.com Пинг и traceroute оба домена проходят, а по curl ни один не проходит.
> 
> Уже голову сломал, не понимаю как обойти запрет по IP провайдера. Видимо что-то очень топорное

есть вариант с нахождение не заблокированных ip и добавления из в hosts
[подробней тут + скрипт](https://ntc.party/t/%D0%BF%D0%BE%D0%B4%D0%B1%D0%BE%D1%80-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B5%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B0-%D0%B4%D0%BB%D1%8F-ggc-%D1%8E%D1%82%D1%83%D0%B1%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-blockcheck/10060/98)

**Comment by all504** [comment]
> Использовать VPN?

Это слишком просто))

**Comment by all504** [comment]
> > Прошу помощи. Запрет открыл все кроме linkedin и x.com Пинг и traceroute оба домена проходят, а по curl ни один не проходит.
> > Уже голову сломал, не понимаю как обойти запрет по IP провайдера. Видимо что-то очень топорное
> 
> есть вариант с нахождение не заблокированных ip и добавления их в hosts [подробней тут + скрипт](https://ntc.party/t/%D0%BF%D0%BE%D0%B4%D0%B1%D0%BE%D1%80-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B5%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B0-%D0%B4%D0%BB%D1%8F-ggc-%D1%8E%D1%82%D1%83%D0%B1%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-blockcheck/10060/98)

Это работало со старым провайдером.
Сейчас новый пров, с ним не робит такая схема.
Он сам резолвит мои запросы и я не могу понять как это обойти.

**Comment by andmt1** [comment]
x.com у меня заработал с этим конфигом [https://github.com/bol-van/zapret/issues/381#issuecomment-2377422365](url)
