### ISSUE TITLE
После установки zapret пропадает коннект между локальными хостами

### ISSUE THREAD

**Issue by pANd-4** [bol-van/zapret#432]
После установки zapret пропадает коннект между локальными хостами, не проходят ни пинги, ни подключение по smb. Проверял несколько раз: до установки zapret работает, после установки перестает. Как исправить?

Роутер Xiaomi AX3600
Версия прошивки OpenWrt SNAPSHOT r27454-d97dced259 
Версия ядра 6.6.51

**Comment by bol-van** [comment]
какова схема подключения хостов, между которыми перестают ходить пинги ?
воткнуты в свитч роутера, используется wifi ?
каковы внутренние ip адреса ?

**Comment by pANd-4** [comment]
Подключены по Wi-Fi, подсеть 192.168.63.0/24.

**Comment by bol-van** [comment]
в дефолтной конфигурации openwrt wifi адаптеры и проводные адаптеры внутр сети
связаны в мост br-lan
правила таблес от nfqws садятся на инет интерфейс и никак не связаны br-lan
перехват tpws идет на lan, но там только порты 80 и 443
как это может на пинги влиять мне сложно представить
разве что выбран offload, и он не работает

остается только удалять цепочки таблес от zapret и выяснять удаление чего вызывает восстановление
если осилите сами

**Comment by pANd-4** [comment]
такое ощущение, что zapret все таблицы переписывает. даже после добавления правил в явном виде, разрешающих все внутри lan или br-lan, они существуют только до перезапуска firewall, после перезапуска пропадают.

**Comment by bol-van** [comment]
в nft  zapret ограничивается одноименной таблицей
а режим iptables  не надо выбирать
