### ISSUE TITLE
Не октрываются госуслуги: PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by trufanov-nok** [bol-van/zapret#433]
Есть ли инструкция для тупых - как добавлять исключения для zapret по url?

**Comment by eastone11** [comment]
1. \opt\zapret\ipset\zapret-hosts-user-exclude.txt - сюда
2. MODE_FILTER=autohostlist или hostlist
3. стратегия без методов десинхронизации 0-й фазы

**Comment by trufanov-nok** [comment]
Запись gosusligi.ru в файл `\opt\zapret\ipset\zapret-hosts-user-exclude.txt` с последующим рестартом службы zapret вроде помогла.

**Comment by TrueKoldun** [comment]
--hostlist-exclude=[путь до файла с исключениями], в инструкции всё есть

**Comment by trufanov-nok** [comment]
в интернете всё есть

**Comment by eastone11** [comment]
всё так

**Comment by Wippito** [comment]
> --hostlist-exclude=[путь до файла с исключениями], в инструкции всё есть

посмотрел кучу видео, прочитал доки, но так и не понял куда именно это писать. в SSH роутера?

**Comment by TrueKoldun** [comment]
> > --hostlist-exclude=[путь до файла с исключениями], в инструкции всё есть
> 
> посмотрел кучу видео, прочитал доки, но так и не понял куда именно это писать. в SSH роутера?

Не знаю, как оно работает на роутере. На Линуксе нужно банально создать где угодно текстовый файл с любым названием, допустим whitelist.txt. Туда вносится всё связаное с госуслугами. Сам портал и подсайты аутентификации, если они есть. Далее в ваш конфиг вносится путь до этого файла. Я так понимаю, что он будет отсылать куда-то на внутреннюю память роутера. В итоге получится что-то вроде --hostlist-exclude=/blahblahblah/whitelist.txt. Далее по идее нужно просто перезагрузить роутер, если не заработали исключения, то и программу нужно переустановить. Опять же, я не разбираюсь, пробуйте

**Comment by Wippito** [comment]
> > > --hostlist-exclude=[путь до файла с исключениями], в инструкции всё есть
> > 
> > 
> > посмотрел кучу видео, прочитал доки, но так и не понял куда именно это писать. в SSH роутера?
> 
> В итоге получится что-то вроде --hostlist-exclude=/blahblahblah/whitelist.txt. 
спасибо за наводку. как оформить строчку понял, как создать текстовый файл понял, а куда писать эту строчку в конфиге? вряд ли в любое место, правильно?

**Comment by TrueKoldun** [comment]
> > > > --hostlist-exclude=[путь до файла с исключениями], в инструкции всё есть
> > > 
> > > 
> > > посмотрел кучу видео, прочитал доки, но так и не понял куда именно это писать. в SSH роутера?
> > 
> > 
> > В итоге получится что-то вроде --hostlist-exclude=/blahblahblah/whitelist.txt.
> 
> спасибо за наводку. как оформить строчку понял, как создать текстовый файл понял, а куда писать эту строчку в конфиге? вряд ли в любое место, правильно?

Я не уверен, влияет ли конкретная позиция этого параметра в конфиге на хоть что-то. У меня он в самом конце глобального конфига для всего интернета, ни на что не жалуюсь, всё, что должно открываться из исключений, открывается

**Comment by bol-van** [comment]
В стандарной системе запуска уже есть exclude в /opt/zapret/ipset/zapret-hosts-user-exclude.txt.
В последней версии его задействование требует маркера <HOSTLIST> в настройках опций tpws/nfqws.
В старых версиях он добавляется к последней стратегии из NFQWS_OPT_DESYNC и TPWS_OPT.
Стандартный exclude задействуется только при MODE_FILTER=hostlist или autohostlist

**Comment by bol-van** [comment]
> Я не уверен, влияет ли конкретная позиция этого параметра в конфиге на хоть что-то. У меня он в самом конце глобального конфига для всего интернета, ни на что не жалуюсь, всё, что должно открываться из исключений, открывается

Влияет только положение между --new.
Внутри не влияет

**Comment by lopatin531** [comment]
> В стандарной системе запуска уже есть exclude в /opt/zapret/ipset/zapret-hosts-user-exclude.txt. В последней версии его задействование требует маркера `<HOSTLIST>` в настройках опций tpws/nfqws. В старых версиях он добавляется к последней стратегии из NFQWS_OPT_DESYNC и TPWS_OPT. Стандартный exclude задействуется только при MODE_FILTER=hostlist или autohostlist

то есть в последней версии достаточно добавить `<HOSTLIST> --new` в стратегиях в NFQWS_ENABLE и TPWS_ENABLE и добавить адрес госуслуг и их портал аутентификации в /opt/zapret/ipset/zapret-hosts-user-exclude.txt?
