### ISSUE TITLE
обход блокировки по IP некоторых серверов youtube

### ISSUE THREAD

**Issue by btgtdLAPTOP** [bol-van/zapret#434]
через blockcheck.sh нашел несколько рабочих способов дурения(билайн, москва). Заработал рутрекер, фейсбук, ютуб оживился(инста и твиттер не работали, да и хрен с ними), но очень странно. Если без запрета еле еле работала главная страница(а видео было в бесконечной загрузке), то с работающим zapret'ом ютуб нормально работал, но в какие то моменты и на каких то видосах замирал, как будто и без zapret'а. Причем так это работало с zapret'ом на линуксе, но в доме у меня еще есть пекарни на винде с goodbyedpi, там точно такая же история. В основном работает как по маслу, но в рандомные моменты времени может зависнуть будто и не обходили ничего. Устанавливал через install_easy.sh:
```

select firewall type :
1 : iptables

enable ipv6 support (default : Y) (Y/N) ? 

select MODE :
1 : tpws

TPWS_OPT="--hostspell=HOST tpws --split-tls=sni --oob"

LAN interface :
1 : NONE

WAN interface :
1 : ANY

enable http support (default : Y) (Y/N) ? 

enable https support (default : Y) (Y/N) ? 

select filtering :
1 : none

```
p.s. Я не являюсь каким то спецом в программах такого рода, но предполагаю, что часть серверов youtube заблокирована по ip. Тоже самое было с инстой: Даже с дурилкой она не работала, но прописав конкретный ip в /etc/hosts/ для инсты она вдруг заработала. Не подскажите, как найти заблокированные ip и подменять их на рабочие?

**Comment by eastone11** [comment]
труба не заблокирована по ip
посмотри стратегии через nfqws, а не tpws
ps
в целом узнать ip через f12 в браузере, сервера с видео называются примерно так _rr3---sn-jvhnu5g-c35k.googlevideo.com_

**Comment by btgtdLAPTOP** [comment]
> труба не заблокирована по ip посмотри стратегии через nfqws, а не tpws ps в целом узнать ip через f12 в браузере, сервера с видео называются примерно так _rr3---sn-jvhnu5g-c35k.googlevideo.com_

пробовал. Например:
> NFQWS_OPT_DESYNC="nfqws --dpi-desync=disorder2 --wssize 1:6 --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt"

Или:

NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-repeats=6 --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt"

Хотя на самом деле пробовал больше, просто эффект один: Либо все ломается, либо начинают работать некоторые заблокированные сайты, а ютуб то работает, то не работает. Точнее на одной вкладке он может спокойно работать, а на другой нещадно тормозить.

Про блокировку некоторыми провайдерами серверов взял у Валдика:
> Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.

Такое поведение началось только после переезда в МСК и наблюдалось как у мгтс, так и у билайна.

**Comment by NewUse** [comment]
кажется, достаточно поставить doh...

**Comment by btgtdLAPTOP** [comment]
> кажется, достаточно поставить doh...

Какой то конкретный? В firefox он включен по умолчанию(но для честности я поставил на максимальный уровень). Пробовал от cloudflare, quad9 и nextdns
никаких изменений.
p.s. Попробовал посмотреть через F12 как и что блокируется:
![image](https://github.com/user-attachments/assets/3a8db410-ad2b-4d16-833f-920ef8b6d311)
"the connection used to fetch this resource was not secure" - у заблокированных POST'ов.

**Comment by NewUse** [comment]
тогда, увы...

**Comment by bol-van** [comment]
> NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-repeats=6 --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt"

фейк без ограничителей ломает 100%  tcp
без понимания все подряд совать вряд ли поможет

**Comment by btgtdLAPTOP** [comment]
> фейк без ограничителей ломает 100% tcp без понимания все подряд совать вряд ли поможет
То то у меня такими настройками почти ничего не работало) Но проблема 100% не в этом была. Например от "nfqws --dpi-desync=syndata,disorder2" был тот же результат. 

> прямое указание листов из ipset нарушает задуманную логику скриптов
вместо этого надо использовать MODE_FILTER=hostlist
Ничего с MODE_FILTER просто не работало. Пока искал в доках так ничего и не нашел про работу MODE_FILTER
P.S. сейчас что то будет сложно пробовать, потому что вдруг ютуб заработал сам по себе на следующий день после перепрошивки роутера на openwrt(Билайн, Москва)
