### ISSUE TITLE
использование звонков дс в ОАЭ

### ISSUE THREAD

**Issue by Arturahmad1** [bol-van/zapret#435]
в ОАЭ заблокированы звонки VOIP по некоторым соц сетям (ватсап,тг,дс и тд) можно ли использовать программу для разблокировки звонков??

**Comment by NewUse** [comment]
попробуйте, но маловероятно, предположу, что там блокировка стоит в разрыв, хотя может тут кто-то более компетентный подскажет

**Comment by Arturahmad1** [comment]
не получилось 😔 или я как то не так настроил

**Comment by bol-van** [comment]
этот вопрос требует технического исследования
смотреть куда лезет приложение
какие порты, протоколы
если блок по ип или порту - запрет не поможет
