### ISSUE TITLE
Как завернуть nfqws на socks proxy

### ISSUE THREAD

**Issue by Sergey-nqwfs** [bol-van/zapret#436]
Есть сервер в сети с адресом 192.168.1.254, на нем zapret в режиме nfqws. Как сделать чтобы клиент с адресом 192.168.1.3 из этой же сети подключался к серверу с zapret через socks5? Через redsocks proxy можно как-то перенаправить трафик на zapret в режиме nfqws?

**Comment by Sergey-nqwfs** [comment]
А как его одновременно запускать? В конфиге /opt/zapret/config добавить MODE="nfqws,tpws"? А параметр TPWS_OPT="" пустой?

**Comment by bol-van** [comment]
Либо custom скриптом, либо отдельно
Специфические случаи не предусмотрены стандартной конфигурацией

**Comment by Sergey-nqwfs** [comment]
Спасибо, я сделал запуск строкой /opt/zapret/tpws/tpws --user=tpws --socks --bind-addr=127.0.0.1 --bind-iface4=wlxf8d1115fa4b1 --bind-wait-ifup=30 --bind-wait-ip=30 --port=988 & в /etc/rc.local 

в конфиге /opt/zapret/config параметр MODE="nfqws", а #TPWS_OPT="" закомментирован. Откуда тогда берутся настройки для tpws?

**Comment by bol-van** [comment]
tpws выступает лишь в роли прокси
его лучше всего запускать через procd из init.d
со скриптами запуска это никак не связано
tpws/nfqws ничего не знают об инсталляторе и конфигах

**Comment by nobody7356** [comment]
Коллеги, все таки, если поднять sock прокси самому, трафик на zapret в режиме nfqws можно пустить или только через tpws?

**Comment by bol-van** [comment]
если правила таблес настроены, nfqws будет работать для исходящих с самой системы конектов
tpws локализует конекты

пускать результат работы  nfqws через прокси не имеет смысла
это не будет работать

**Comment by Sergey-nqwfs** [comment]
Если добавить wifi hotspot с сетью 192.168.2.0/24
И перенаправлять на tpws на 988 порт,

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X
iptables -t nat -A PREROUTING -d 192.168.2.0/24 -j RETURN
iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 988
iptables -t nat -A PREROUTING -i wlan0 -p tcp -j ACCEPT
iptables -t nat -A POSTROUTING -o wlxf8d1115fa4b1 -j MASQUERADE

запускаемый командой /opt/zapret/tpws/tpws --user=tpws --socks --bind-addr=127.0.0.1 --bind-iface4=wlxf8d1115fa4b1 --bind-wait-ifup=30 --bind-wait-ip=30 --port=988

,то отваливается ssh у 192.168.1.254 на котором установлен tpws сервер и клиенты из сети 192.168.1.0/24 не могут подключится по ssh к 192.168.1.254, только из подсети 192.168.2.0/24 на wlan0.


Или все работает с применением дополнительно redsocks proxy с конфигом /etc/redsocks.conf:

base {
        log_debug = off;
        daemon = on;
        user = redsocks;
        group = redsocks;
        redirector = iptables;
}
redsocks {
        local_ip = 0.0.0.0;
        local_port = 12345;
        ip = 127.0.0.1;
        port = 988;
        type = socks5;
}

И в /etc/rc.local:

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X
iptables -t nat -N REDSOCKS
iptables -t nat -A REDSOCKS -d 192.168.2.0/24 -j RETURN
iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -i wlan0 -p tcp -j REDSOCKS
iptables -t nat -A POSTROUTING -o wlxf8d1115fa4b1 -j MASQUERADE
/opt/zapret/tpws/tpws --user=tpws --socks --bind-addr=127.0.0.1 --bind-iface4=wlxf8d1115fa4b1 --bind-wait-ifup=30 --bind-wait-ip=30 --port=988

Еще можно установить пароль на socks сервер в данном случае если он сдедан публичным. А в tpws можно установить логин/пароль на socks5?

**Comment by bol-van** [comment]
редирект или днат требуют прозрачный режим прокси
--socks это не прозрачный режим
редирект работать не будет

**Comment by Sergey-nqwfs** [comment]
Цель: точка доступа wifi с возможностью подключения к ней (нужен прозрачный прокси) и однновременно возможность подключатся как клиент к socks5 proxy серверу из той же локальной сети в которой сервер с zapret подключен к интернету. Tpws не может в прозрачный proxy и не прозрачный одновременно?

**Comment by bol-van** [comment]
tpws можно запустить несколько инстансов с разными параметрами
роль прозрачного прокси мне непонятна
без дурения это лишь  tcp proxy

**Comment by Sergey-nqwfs** [comment]
Прозрачный прокси что бы заворачивать весь трафик клиентов которые подключаются к точке доступа wifi, развернутой на сервере с zapret и пропускание этого трафика через nfqws методики модификации.

**Comment by Sergey-nqwfs** [comment]
Как все-таки правильно запустить две копии tpws в прозрачном и обычном режиме, какие команды для procd?

**Comment by bol-van** [comment]
> Прозрачный прокси что бы заворачивать весь трафик клиентов которые подключаются к точке доступа wifi, развернутой на сервере с zapret и пропускание этого трафика через nfqws методики модификации.

нелогичное решение
зачем заменять маршрутизацию на проксирование ?
маршрутизация намного легче

procd см уже имеющиеся скрипты в  init.d
или доку из zapret по заворачиванию на редсокс

**Comment by Sergey-nqwfs** [comment]
А можете все-таки написать правила редиректа. Это все можно сделать средствами iptables?
Сервер с zapret в nfqws режиме, и wifi hotspot на wlan0 с сетью 192.168.2.0/24. Надо травик с этой сети завернуть на zapret. Для интернета это только 80 и 443 порты?

**Comment by bol-van** [comment]
Поймите, что nfqws - это обработчик отдельных IP пакетов. На него не надо заворачивать соединения, как это делается в случае tpws. Он работает и без tpws на базе очереди NFQUEUE.
Завертывать в NFQUEUE можно не только с локальной системы, но и проходящий трафик.
Это и есть нормальный и основной режим работы nfqws.
Скрипты zapret перенаправляют пакеты на nfqws на этапе выхода во внешнюю сеть. В случае nftables - после NAT.
Максимально близко к выходу, чтобы можно было задействовать стратегии, ломающие NAT.
Так и следует поступать, если правила пишутся руками и nfqws тоже запускается руками, без скриптов zapret.
Вопрос в том, чтобы ограничить дурение только одной подсетью ?
К чему этот сокс вообще ?

**Comment by Sergey-nqwfs** [comment]
Есть роутер 192.168.1.1, к нему кабелем поделючается сервер (orange pi) на ней wifi точка 192.168.2.1 Часть устройств к ней подключается через wifi, а часть устройств к роутеру в сеть 192.168.1.0/24, и там через сокс клиент в firefoxe например используют сервер с zapret. Это достаточно лнгко, просто вписать адрес 192.168.1.254 и запустить tpws без параметров на сервере. И еще проброшен 988 порт на белый адрес в роутер, чтобы из вне можно было проки использовать.

**Comment by bol-van** [comment]
то есть проблема в стоковой прошивке, с которой ничего не сделать ?
обычным образом настраиваете zapret с  nfqws на 254
и туда вешаете tpws --socks
больше ничего не надо
никаких прозрачных прокси не нужно

еще есть вариант менять на клиентах  default gateway на 254
это требует отключения   icmp redirect и маскарада
gw в идеале менять через дхцп опшинс
но сток это не даст сделать скорее всего
и отключить дхцп тоже
так что только прописывать статику

**Comment by Sergey-nqwfs** [comment]
Да, keenetic старой версии, не поддерживает вот это вот все. Но можно повесить затычку на lan в виде orange pi.

Nfqws настроен обычным образом, запускается через  systemctl start zapret. При этом откуда он знает какой config брать, это по умолчанию из той папки где он запускается?
Какие правила дает INIT_APPLY_FW=1 в confige? Я смотрел через systemctl status zapret там есть следующие строки:

-p tcp -m multiport --dports 80,443 -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:6 -m mark ! --mark 0x40000000/0x40000000

 -p tcp -m multiport --sports 80,443 -m connbytes --connbytes-dir=reply --connbytes-mode=packets --connbytes 1:1

-p udp -m multiport --dports 443 -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:6 -m mark ! --mark 0x40000000/0x40000000

Перенаправляют с какого адреса на какой как понять?


Далее tpws как дополнительно запустить? Можно тоже через systemctl start zapret но с другим конфигом или достаточно просто командой `/opt/zapret/tpws/tpws --user=tpws --socks --bind-addr=127.0.0.1 --bind-iface4=wlxf8d1115fa4b1 --bind-wait-ifup=30 --bind-wait-ip=30 --port=988`?

Как еще добавить правила перенаправления с подсети 192.168.2.0/24 на прямую на zapret с nfqws?
Он в этом режиме просто направляет пакеты приходящие с любого адреса на 80 и 443 порты на очередь nfqws?

**Comment by bol-van** [comment]
если там дистр  системд, то несложно написать собственный юнит
примеров полно

запуск zapret состоит из 2 частей - запуск демонов и запуск фаервола (правила таблес)
init_app;y_fw  конфиге задает будет ли запускаться фаео при старте юнита
когда требуется синхронизироваться с системой управления фаером - надо фаер запускать отдельно
в реадми см прикрутка к системе управления фаерволом

стандартная конфигурация направляет на  nfqws начальные пакеты соединений
на порты 80 и 443. может быть ограничена исходящим интерфейсом IFACE_WAN
работает как с локальным, так и с проходным трафом
сабнеты ограничивать не надо
надо задать wan интерфейс

**Comment by Sergey-nqwfs** [comment]
Т.е. опции IFACE_LAN=адрес интерфейса в интернет (eth0 в данном случае) достаточно, чтобы пакеты из подсети 192.168.2.0/24 на wlan0 (точке доступа hostapd) попадали на обработчик nfqws? А правило masquarde не надо?

**Comment by bol-van** [comment]
собственный юнит это всего несколько строк в текстовом файле
и пару команд системцтл

masquerade вообще лучше без нужды не применять
лучше в кинетике прописать статический маршрут на 192.168.2.0/24 gw 192.168.1.254
masq нужен в случае смены gw на клиентах, иначе входящий с инета траф пойдет минуя 1.254 напрямую

iface_lan нужен только для тпвс

**Comment by Sergey-nqwfs** [comment]
> лучше в кинетике прописать статический маршрут на 192.168.2.0/24 gw 192.168.1.254
А как все же это сделать на самом сервере с zapret (orange pi), что бы все настройки локализованы были в самой затычке?
Так получится или это небезопасно?
iptables -t nat -A PREROUTING -d 192.168.1.254 -p tcp -j REDIRECT -s 192.168.2.0/24

**Comment by bol-van** [comment]
эти команды, кроме последней, не имеют смысла
nfqws прекрасно работает с проходным трафом
все необходимое поднимут скрипты zapret
masquerade нужен только если не хочется прописывать статический маршрут на кинетик
ip_forward включить, и этого хватит

**Comment by Sergey-nqwfs** [comment]
Как скрипты узнают о существовании сети 192.168.2.0/24 и что надо ее перенапралять на nfqws?
И еще в режиме tpws это сервис на адресе 127.0.0.1 слушает порт 988, а в режиме nfqws это просто список правил для перенаправления с 443 и 80 портов на nfqws?

**Comment by bol-van** [comment]
им не надо знать про подсети
важен исходящий интерфейс
таблицы маршрутизации знают про подсети и сами выберут направление

nfqws слушает на номере очереди
он не работает на уровне соединений, а на уровне отдельных пакетов

**Comment by Sergey-nqwfs** [comment]
Таблицы маршрутизации формируются в том числе маскардингом
`iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE` для того что бы пакеты проходили из одной сети в другую

**Comment by bol-van** [comment]
это не так
маскарадинг есть замена адреса источника (SNAT)
к маршрутизации отношения не имеет
она выполняется на базе правил (ip rule) и таблиц маршрутизации (ip route)
главный критерий выбора маршрута - адрес назначения, а не источника
хотя для   ipv6 могут применяться и маршруты с source addr

**Comment by nobody7356** [comment]
Коллеги, подскажите.
Есть е192.168.1.0/24 gw 192.168.1.1/32 Есть убунту с запрет в режиме nfqws 192.168.1.2/32, все соседние хосты просто используют запрет как gw и это прекрасно работает. Но пропустить через запрет трафик из соседней 192.168.2.0\24 никак не получается, т.к. там уже нельзя выставить этот запрет как gw. Подскажите в каком направление двигаться.  Нужен сокс на запрете или как еще перенаправить траффик хттп из 192.168.2.0\24?

**Comment by bol-van** [comment]
Смотря как организована сеть.
Обычно к таким костылям прибегают, когда роутером выступает заводская коробка, с которой не сделать ничего.
Если бы это была нормальная система, то nfqws разумно было бы поставить на inet gateway.
Даже если бы оставить текущую конфигурацию, на linux gw можно было бы создать отдельную route table и написать ip rule, чтобы заруливалось на 192.168.1.2, но тут опять вступает фактор убогой заводской железяки.
Так что да, пожалуй, со стоковым гейтвеем лучше сокс

**Comment by nobody7356** [comment]
Я запустил дополнительно на запрет tpws в режиме сокс, теперь я могу через сокс направлять туда трафик из соседних подсетей, с этим ок.

**Comment by Sergey-nqwfs** [comment]
Конфигурация все же работает. Orange pi можно подключить к роутеру по eth0 как сервер с точкой wifi и tpws на 988 порту.

`>/etc/network/interfaces:`
```
nano /etc/network/interfaces:
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto wlan0
iface wlan0 inet static
address 192.168.2.1
```
`>/etc/sysctl.conf:`
`net.ipv4.ip_forward=1`

hostapd и dnsmasq обычным образом.

правила и запуск tpws:

`/etc/rc.local:`
```
date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
iptables -t nat -A POSTROUTING -o wlxf8d1115fa4b1 -j MASQUERADE
/opt/zapret/tpws/tpws --user=tpws --socks --bind-addr=127.0.0.1 --bind-iface4=wlxf8d1115fa4b1 --bind-wait-ifup=30 --bind-wait-ip=30 --port=988 &
```

И в /opt/zapret/config надо добавить

```
FWTYPE=iptables
MODE=nfqws
MODE_QUIC=0
NFQWS_OPT_DESYNC="задать стратегии"
IFACE_WAN=eth0
INIT_APPLY_FW=1
```

Без правил FWTYPE=iptables и INIT_APPLY_FW=1 не работает
А без параметра IFACE_WAN='интерфейс в инет' со временем пропадает маршрутизация в сеть на wlan0 почему-то.

Что именно делает параметр IFACE_WAN в конфиге?
И еще, если tpws проброшен наружу, как узнать лог с каких ip к нему подключались?
Также хотелось бы рабочий юнит с systemctl для запуска в tpws с другим конфигом...

**Comment by bol-van** [comment]
> Что именно делает параметр `IFACE_WAN` в конфиге

в иптаблес добавляется -o iface
если несколько - правила дублируются
в нфт oifname @wanif
wanif set заполняется из iface_wan

> И systemd-resolved надо отключать?

он тут каким боком ?
tpws в носках может работать как с удаленным ресолвингом, так и нет
от клиента зависит что он хочет

**Comment by Sergey-nqwfs** [comment]
> он тут каким боком ?
Он конфликтует с dnsmasq, а dnsmasq нужен чтобы раздавать адреса клиентам точки доступа на wlan0.

И как лог подключение tpws посмотреть?
