### ISSUE TITLE
Сервер на ubuntu 20.04, zapret работает только локально на машине, клиенты нет. 

### ISSUE THREAD

**Issue by fa1ke5** [bol-van/zapret#438]
Собственно сабж, правила в iptables добавляются, тест на сервере даёт поток с Ютуба, но клиенты все равно не могут зайти.

**Comment by nobody7356** [comment]
Может поможет https://github.com/bol-van/zapret/issues/426

**Comment by fa1ke5** [comment]
Естественно нат и форвардинг давно включены, клиенты ходят в интернет уже давно и прочно.
В качестве расширителя интерфейсов используется умный свитч с VLAN, то есть у компа один физический интерфейс, который попилен на два VLAN интерфейса, LAN и WAN соответственно. В качестве цели для правил iptables указан виртуальный WAN. Может физический нужно указать?

**Comment by nobody7356** [comment]
В моем случае один сетевой интерфейс на машине, iptables только то что добавляет сам запрет и nat

В запрете в конфиге указали ваши интерфейсы?

```
# for routers based on desktop linux and macos. has no effect in openwrt.
# CHOOSE LAN and optinally WAN/WAN6 NETWORK INTERFACES
# or leave them commented if its not router
# it's possible to specify multiple interfaces like this : IFACE_LAN="eth0 eth1 eth2"
# if IFACE_WAN6 is not defined it take the value of IFACE_WAN
#IFACE_LAN=eth0
#IFACE_WAN=eth1
#IFACE_WAN6="ipsec0 wireguard0 he_net"
```

**Comment by fa1ke5** [comment]
Как включить дебаг? Пардон за дурацкий вопрос, но при текущей схеме стартовых скриптов это нетривиальная задача.
я использую nfqws, можно конечно от руки стартануть, но оно не пропишет правила в iptables

**Comment by fa1ke5** [comment]
с логом так и не понял, короче проще наверное выложить конфу
root@atom:~# ifconfig -a

br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.1  netmask 255.255.255.0  broadcast 192.168.10.255


enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500


enp3s0.1000: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500


enp3s0.1001: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet XX.XX.XX.XX  netmask 255.255.255.224  broadcast XX.XX.XX.XX

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.10.1.1  netmask 255.255.255.255  destination 10.10.1.2

wlx000f00528fae: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
wlxe84e068fd2ea: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500


root@atom:~# brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.5e2196b50ecc       no              enp3s0.1000
                                                        wlx000f00528fae
                                                        wlxe84e068fd2ea

соответственно 
br0 это LAN, в нем вайфай wlxXXXXXX и провод  enp3s0.1000
 enp3s0.1001 это WAN смотрит в инет.

**Comment by fa1ke5** [comment]
iptables правила после старта zapret
# Generated by iptables-save v1.8.7 on Mon Sep 30 16:48:32 2024
*mangle
:PREROUTING ACCEPT [54579:48517740]
:INPUT ACCEPT [28661:35074207]
:FORWARD ACCEPT [24401:13202375]
:OUTPUT ACCEPT [17528:1705048]
:POSTROUTING ACCEPT [42542:14880043]
-A INPUT -i enp3s0.1001 -p tcp -m multiport --sports 80,443 -m connbytes --connbytes 1:1 --connbytes-mode packets --connbytes-dir reply -m set ! --match-set nozapret src -j NFQUEUE --queue-num 200 --queue-bypass
-A INPUT -i enp3s0 -p tcp -m multiport --sports 80,443 -m connbytes --connbytes 1:1 --connbytes-mode packets --connbytes-dir reply -m set ! --match-set nozapret src -j NFQUEUE --queue-num 200 --queue-bypass
-A FORWARD -i enp3s0.1001 -p tcp -m multiport --sports 80,443 -m connbytes --connbytes 1:1 --connbytes-mode packets --connbytes-dir reply -m set ! --match-set nozapret src -j NFQUEUE --queue-num 200 --queue-bypass
-A FORWARD -i enp3s0 -p tcp -m multiport --sports 80,443 -m connbytes --connbytes 1:1 --connbytes-mode packets --connbytes-dir reply -m set ! --match-set nozapret src -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o enp3s0.1001 -p tcp -m multiport --dports 80,443 -m connbytes --connbytes 1:6 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -m set ! --match-set nozapret dst -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o enp3s0 -p tcp -m multiport --dports 80,443 -m connbytes --connbytes 1:6 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -m set ! --match-set nozapret dst -j NFQUEUE --queue-num 200 --queue-bypass
COMMIT
# Completed on Mon Sep 30 16:48:32 2024
# Generated by iptables-save v1.8.7 on Mon Sep 30 16:48:32 2024
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [17528:1705048]
:f2b-sshd - [0:0]
:fail2ban-ssh - [0:0]
-A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
-A INPUT -p tcp -m multiport --dports 22 -j fail2ban-ssh
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i enp3s0.1001 -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A INPUT -i tap0 -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A INPUT -i br0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3240 -j ACCEPT
-A INPUT -p udp -m udp --dport 9199 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9199 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9192 -j ACCEPT
-A INPUT -i br0 -p udp -m udp --dport 111 -j ACCEPT
-A INPUT -i br0 -p tcp -m tcp --dport 111 -j ACCEPT
-A INPUT -i br0 -p tcp -m tcp --dport 2049 -j ACCEPT
-A INPUT -i br0 -p udp -m udp --dport 2049 -j ACCEPT
-A INPUT -i br0 -p udp -m udp --dport 32764:32769 -j ACCEPT
-A INPUT -i br0 -p tcp -m tcp --dport 32764:32769 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -p tcp -m tcp --dport 1200 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i br0 -j ACCEPT
-A FORWARD -i tun0 -j ACCEPT
-A f2b-sshd -j RETURN
-A fail2ban-ssh -j RETURN
COMMIT
# Completed on Mon Sep 30 16:48:32 2024
# Generated by iptables-save v1.8.7 on Mon Sep 30 16:48:32 2024
*nat
:PREROUTING ACCEPT [3015:437837]
:INPUT ACCEPT [270:18897]
:OUTPUT ACCEPT [678:54556]
:POSTROUTING ACCEPT [138:10059]
-A PREROUTING -d xx.xx.xx.xx/32 -p tcp -m tcp --dport 1200 -j DNAT --to-destination xx.xx.xx.xx:1200
-A POSTROUTING -o enp3s0.1001 -j MASQUERADE
COMMIT
# Completed on Mon Sep 30 16:48:32 2024

**Comment by fa1ke5** [comment]
NAT включен постоянно, в mangle правила добавляются, тест локально ютуб проходит

**Comment by fa1ke5** [comment]
конфиг, пробовал указывать и LAN и WAN отдельно и вместе, реакция нулевая и ничего не меняется
```
root@atom:/opt/zapret# cat config
# this file is included from init scripts
# change values here

# can help in case /tmp has not enough space
#TMPDIR=/opt/zapret/tmp

# redefine user for zapret daemons. required on Keenetic
#WS_USER=nobody

# override firewall type : iptables,nftables,ipfw
FWTYPE=iptables

# options for ipsets
# maximum number of elements in sets. also used for nft sets
SET_MAXELEM=522288
# too low hashsize can cause memory allocation errors on low RAM systems , even if RAM is enough
# too large hashsize will waste lots of RAM
IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
# dynamically generate additional ip. $1 = ipset/nfset/table name
#IPSET_HOOK="/etc/zapret.ipset.hook"

# options for ip2net. "-4" or "-6" auto added by ipset create script
IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
# options for auto hostlist
AUTOHOSTLIST_RETRANS_THRESHOLD=3
AUTOHOSTLIST_FAIL_THRESHOLD=3
AUTOHOSTLIST_FAIL_TIME=60
# 1 = debug autohostlist positives to ipset/zapret-hosts-auto-debug.log
AUTOHOSTLIST_DEBUGLOG=0

# number of parallel threads for domain list resolves
MDIG_THREADS=30

# ipset/*.sh can compress large lists
GZIP_LISTS=1
# command to reload ip/host lists after update
# comment or leave empty for auto backend selection : ipset or ipfw if present
# on BSD systems with PF no auto reloading happens. you must provide your own command
# set to "-" to disable reload
#LISTS_RELOAD="pfctl -f /etc/pf.conf"

# override ports
#HTTP_PORTS=80-81,85
#HTTPS_PORTS=443,500-501
#QUIC_PORTS=443,444

# CHOOSE OPERATION MODE
# MODE : nfqws,tpws,tpws-socks,filter,custom
# nfqws : nfqws for dpi desync
# tpws : tpws transparent mode
# tpws-socks : tpws socks mode
# filter : no daemon, just create ipset or download hostlist
# custom : custom mode. should modify custom init script and add your own code
MODE=nfqws
# apply fooling to http
MODE_HTTP=1
# for nfqws only. support http keep alives. enable only if DPI checks for http request in any outgoing packet
MODE_HTTP_KEEPALIVE=0
# apply fooling to https
MODE_HTTPS=1
# apply fooling to quic
MODE_QUIC=0
# none,ipset,hostlist,autohostlist
MODE_FILTER=none

# CHOOSE NFQWS DAEMON OPTIONS for DPI desync mode. run "nfq/nfqws --help" for option list
# SUFFIX VARS define additional lower priority desync profile. it's required if MODE_FILTER=hostlist and strategy has hostlist-incompatible 0-phase desync methods (syndata,wssize)
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-ttl=0 --dpi-desync-ttl6=0 --dpi-desync-fooling=badsum"
#NFQWS_OPT_DESYNC_SUFFIX="--dpi-desync=syndata"
#NFQWS_OPT_DESYNC_HTTP="--dpi-desync=fake --dpi-desync-ttl=5"
#NFQWS_OPT_DESYNC_HTTP_SUFFIX="--dpi-desync=syndata"
#NFQWS_OPT_DESYNC_HTTPS="--dpi-desync=fake --dpi-desync-ttl=5"
#NFQWS_OPT_DESYNC_HTTPS_SUFFIX="--wssize 1:6"
#NFQWS_OPT_DESYNC_HTTP6=""
#NFQWS_OPT_DESYNC_HTTP6_SUFFIX="--dpi-desync=syndata"
#NFQWS_OPT_DESYNC_HTTPS6=""
#NFQWS_OPT_DESYNC_HTTPS6_SUFFIX="--wssize 1:6"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6"
#NFQWS_OPT_DESYNC_QUIC_SUFFIX=""
#NFQWS_OPT_DESYNC_QUIC6="--dpi-desync=hopbyhop"
#NFQWS_OPT_DESYNC_QUIC6_SUFFIX=""

# CHOOSE TPWS DAEMON OPTIONS. run "tpws/tpws --help" for option list
# SUFFIX VARS define additional lower priority desync profile. it's required if MODE_FILTER=hostlist and strategy has hostlist-incompatible 0-phase desync methods (mss)
TPWS_OPT="--hostspell=HOST --split-http-req=method --split-pos=3 --oob"
#TPWS_OPT_SUFFIX="--mss 88"

# openwrt only : donttouch,none,software,hardware
FLOWOFFLOAD=donttouch

# openwrt: specify networks to be treated as LAN. default is "lan"
#OPENWRT_LAN="lan lan2 lan3"
# openwrt: specify networks to be treated as WAN. default wans are interfaces with default route
#OPENWRT_WAN4="wan vpn"
#OPENWRT_WAN6="wan6 vpn6"

# for routers based on desktop linux and macos. has no effect in openwrt.
# CHOOSE LAN and optinally WAN/WAN6 NETWORK INTERFACES
# or leave them commented if its not router
# it's possible to specify multiple interfaces like this : IFACE_LAN="eth0 eth1 eth2"
# if IFACE_WAN6 is not defined it take the value of IFACE_WAN
#IFACE_LAN=eth0
IFACE_LAN=br0
IFACE_WAN=enp3s0.1001
#IFACE_WAN=enp3s0
#IFACE_WAN6="ipsec0 wireguard0 he_net"

# should start/stop command of init scripts apply firewall rules ?
# not applicable to openwrt with firewall3+iptables
INIT_APPLY_FW=1
# firewall apply hooks
#INIT_FW_PRE_UP_HOOK="/etc/firewall.zapret.hook.pre_up"
#INIT_FW_POST_UP_HOOK="/etc/firewall.zapret.hook.post_up"
#INIT_FW_PRE_DOWN_HOOK="/etc/firewall.zapret.hook.pre_down"
#INIT_FW_POST_DOWN_HOOK="/etc/firewall.zapret.hook.post_down"

# do not work with ipv4
#DISABLE_IPV4=1
# do not work with ipv6
DISABLE_IPV6=1

# select which init script will be used to get ip or host list
# possible values : get_user.sh get_antizapret.sh get_combined.sh get_reestr.sh get_hostlist.sh
# comment if not required
#GETLIST=

```

**Comment by fa1ke5** [comment]
```
root@atom:/opt/zapret# service zapret status
● zapret.service
     Loaded: loaded (/etc/systemd/system/zapret.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-09-30 16:55:25 MSK; 2min 1s ago
    Process: 3434 ExecStart=/opt/zapret/init.d/sysv/zapret start (code=exited, status=0/SUCCESS)
      Tasks: 1 (limit: 18706)
     Memory: 476.0K
        CPU: 78ms
     CGroup: /system.slice/zapret.service
             └─3460 /opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --dpi-desync=fake --dpi-desync-ttl=0 --dpi-desync-ttl6=0 --dpi-desync-fooling=badsum

сен 30 16:55:25 atom systemd[1]: Starting zapret.service...
сен 30 16:55:25 atom zapret[3434]: Starting daemon 1: /opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --dpi-desync=fake --dpi-desync-ttl=0 --dpi-desync-ttl6=0 --dpi-desync-fooling=badsum
сен 30 16:55:25 atom zapret[3434]: Applying iptables
сен 30 16:55:25 atom zapret[3434]: Creating ip list table (firewall type iptables)
сен 30 16:55:25 atom zapret[3461]: setting high oom kill priority
сен 30 16:55:25 atom zapret[3461]: reloading ipset backend (no-update)
сен 30 16:55:25 atom zapret[3434]: Adding iptables rule for nfqws postrouting (qnum 200) :  -p tcp -m multiport --dports 80,443 -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:6 -m mark ! --mark 0x40000000/0x40000000
сен 30 16:55:25 atom zapret[3434]: Adding iptables rule for nfqws input+forward (qnum 200) :  -p tcp -m multiport --sports 80,443 -m connbytes --connbytes-dir=reply --connbytes-mode=packets --connbytes 1:1
сен 30 16:55:25 atom systemd[1]: Started zapret.service.

```

**Comment by fa1ke5** [comment]
можно закрывать, я почему то рассчитывал что успешный тест это гарантия работы, все работает, просто ютуб не работает )))

**Comment by bol-van** [comment]
> Как включить дебаг? Пардон за дурацкий вопрос, но при текущей схеме стартовых скриптов это нетривиальная задача.

руками в консоли без системд несложно запустить
/opt/zapret/init.d/sysv/zapret start_fw
демоны - руками

или использовать --debug=@filename
