### ISSUE TITLE
Помогите подобрать настройки по настройкам из goodby dpi

### ISSUE THREAD

**Issue by rosomaha256** [bol-van/zapret#439]
Помогите подобрать настройки по настройкам из goodby dpi подошли такие настройки -p -r -s -f 2 -k 2 -n -e 2
в кинетике под антизапрет все перепробовал что нашел не взлетает

**Comment by NewUse** [comment]
а blockcheck запустить пробовали?

**Comment by rosomaha256** [comment]
> а blockcheck запустить пробовали?

да пробовал, но те схемы которые выдает не обходит блокировку ютуба, на торрент и тд заходит норм, попробовал на пк гудбай дипиай потестить он завелся. Теперь осталось расшифровать эту строку настройки.

**Comment by NewUse** [comment]
тогда имеет смысл заглянуть в соседнюю дискуссию, там описаны возможные варианты настройки именно для YouTube
