### ISSUE TITLE
TWPS both SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST failed ! error

### ISSUE THREAD

**Issue by eoksum** [bol-van/zapret#44]
Hi there

I compiled and started TWPS on my Raspberry Pi running Raspbian OS. I want to use TWPS as a transparent proxy. When I start TWPS I can see it running on the port I wanted it to run but when I attempt connecting through a remote device on the same network I keep getting **Empty response from server (ERR_EMPTY_RESPONSE) on Chrome.** When I enable debugging mode I can see this error:

root@raspberrypi:/home/pi/zapret/tpws# ./tpws --port=8080 --bind-addr=192.168.1.10 --maxconn=200 --hostcase --hostspell hoSt --hostdot --hosttab --hostnospace --hostpad=2 --methodspace --methodeol --debug=2
set_socket_buffers fd=3 rcvbuf=0 sndbuf=0
fd=3 SO_RCVBUF=87380
fd=3 SO_SNDBUF=16384
set_ulimit : fdmax=1082 fdmin_system=5178
set_ulimit : current system file-max=93750
Running as UID=0 GID=0
Will listen to port 8080
transparent proxy mode
epoll_wait

EVENT mask 00000001 conn=NULL (accept)
both SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST failed !
Original destination for socket fd=5 : 192.168.1.10:8080
Dropping connection to local address to the same port to avoid loop
Failed to add connection
epoll_wait

EVENT mask 00000001 conn=NULL (accept)
both SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST failed !
Original destination for socket fd=5 : 192.168.1.10:8080
Dropping connection to local address to the same port to avoid loop
Failed to add connection
epoll_wait

EVENT mask 00000001 conn=NULL (accept)
both SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST failed !
Original destination for socket fd=5 : 192.168.1.10:8080
Dropping connection to local address to the same port to avoid loop
Failed to add connection
epoll_wait

EVENT mask 00000001 conn=NULL (accept)
both SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST failed !
Original destination for socket fd=5 : 192.168.1.10:8080
Dropping connection to local address to the same port to avoid loop
Failed to add connection
epoll_wait

EVENT mask 00000001 conn=NULL (accept)
both SO_ORIGINAL_DST and IP6T_SO_ORIGINAL_DST failed !
Original destination for socket fd=5 : 192.168.1.10:8080
Dropping connection to local address to the same port to avoid loop
Failed to add connection
epoll_wait

I even tested via curl locally on Raspberry Pi to ensure if my router is blocking the port 8080 or not. The result was the same:

root@raspberrypi:/home/pi/zapret/tpws# curl -vv -x http://192.168.1.10:8080 -L http://google.com
* Expire in 0 ms for 6 (transfer 0x7fd880)
*   Trying 192.168.1.10...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x7fd880)
* Connected to 192.168.1.10 (192.168.1.10) port 8080 (#0)
> GET http://google.com/ HTTP/1.1
> Host: google.com
> User-Agent: curl/7.64.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Empty reply from server
* Connection #0 to host 192.168.1.10 left intact
curl: (52) Empty reply from server

What can I do to fix this issue? The country im living in is also forcing DPI on us and its pretty annoying.

Thank you

**Comment by bol-van** [comment]
You misunderstand what transparent proxy is and how it works on linux
Brief : TP works through iptables redirection (DNAT), its not supposed to connect directly

**Comment by eoksum** [comment]
Thank you for your reply. I have a MikroTik RB951 at my home running on MikroTik's RouterOS and I don't want to flash it to another OS since I already done all the required configuration on this device and I don't really want to redo everything but I still need a DPI circumvention tool at the network-wide level. I need a transparent proxy which can be connected directly. I also asked GoodbyeDPI's developer about this, he said try Zapret's TWPS module which can be configured as a transparent proxy. My country is imposing DPI on me which really sucks because I can't even access Wikipedia. I need a proxy which changes headers for circumvention purposes. Can I configure Zapret's TWPS as a transparent proxy?

Thank you

**Comment by bol-van** [comment]
transparent proxy is opposite thing to directly connectable proxy
if you want directly connectable - use --socks mode.
if transparent - use iptables commands as described in readme or (better) use mikrotik - specific firewall configuration commands. I'm not expert in mikrotik

**Comment by bol-van** [comment]
Transparent proxy does not require any configuration of software on client devices
Router intercepts connections and redirects them to transparent proxy. google for "mikrotik transparent proxy"
Directly connectable proxy require special proxy type support in client software and configuring server:port. TPWS supports only socks proxy type

**Comment by eoksum** [comment]
Thank you for your attention.

Now I considered everything you stated and I've tried starting TPWS with this command:

**root@raspberrypi:/home/pi/zapret/tpws#  ./tpws --port=8080 --bind-addr=192.168.1.10 --maxconn=200 --socks --hostcase --hostspell hoSt --hostdot --hosttab --hostnospace --hostpad=2 --methodspace --methodeol --debug=2**

However, result was still the same. I still kept getting **Empty reply from server** error.
This is the output generated upon a page load:

> set_socket_buffers fd=3 rcvbuf=0 sndbuf=0
> fd=3 SO_RCVBUF=87380
> fd=3 SO_SNDBUF=16384
> set_ulimit : fdmax=1082 fdmin_system=5178
> set_ulimit : current system file-max=93750
> Running as UID=0 GID=0
> Will listen to port 8080
> socks mode
> epoll_wait
> 
> EVENT mask 00000001 conn=NULL (accept)
> fd=5 SO_RCVBUF=87380
> fd=5 SO_SNDBUF=44800
> epoll_set fd=5 events=00002001
> Legs : local:1 remote:0
> Socket fd=5 (local) connected
> epoll_wait
> 
> EVENT mask 00000001 fd=5 remote=0 fd_partner=0
> +handle_epoll
> handle_proxy_mode rd=229
> S_WAIT_HANDSHAKE
> handle_epoll false
> epoll_del fd=5
> Socket fd=5 (partner_fd=0, remote=0) closed, connection removed. total_read=0 total_write=0 event_count=1
> Legs : local:0 remote:0
> epoll_wait
> 
> EVENT mask 00000001 conn=NULL (accept)
> fd=5 SO_RCVBUF=87380
> fd=5 SO_SNDBUF=44800
> epoll_set fd=5 events=00002001
> Legs : local:1 remote:0
> Socket fd=5 (local) connected
> epoll_wait
> 
> EVENT mask 00000001 fd=5 remote=0 fd_partner=0
> +handle_epoll
> handle_proxy_mode rd=229
> S_WAIT_HANDSHAKE
> handle_epoll false
> epoll_del fd=5
> Socket fd=5 (partner_fd=0, remote=0) closed, connection removed. total_read=0 total_write=0 event_count=1
> Legs : local:0 remote:0
> epoll_wait

Im not quite sure what I'm missing here. Can you please give me a idea?

Thank you very much again.

**Comment by bol-van** [comment]
looks like client does not talk socks protocol
test with curl : curl --socks5 192.168.1.10:1080 http://www.ru

also, hostpad is meaningless with "2" as parameter. parameter mean bytes. Its not possible to pad with only 2 bytes

**Comment by bol-van** [comment]
Also note  not all tampering parameters are compatible with most servers.
--methodeol can break losts of servers

**Comment by eoksum** [comment]
Thank you for your collaboration

I was able to get TPWS running and most of the blocked content now loads up :) thank you very very much!

I have one last question. Some websites get broken when TPWS is used (Same happens on GoodbyeDPI as well)

For example Wikipedia, Imgur, Pastebin is blocked in my country.
I can access Wikipedia and Pastebin with no issues with TPWS proxy but when I try accessing Imgur I get this error: **SSL_ERROR_RX_RECORD_TOO_LONG**

Is this error caused by TLS packets getting splitted with TCP fragmentation or something else? Is there a way to fix this?

Thank you very much.

**Comment by bol-van** [comment]
The only option that affects non-http traffic is --split-pos. Without it tpws runs as 1:1 tcp proxy for https traffic. And yes, sometimes splitting https break sites.
Its mainly because of middleboxes (or DPIs) on the way to the site
