### ISSUE TITLE
Обход не работает на PC, работая на телефонах и lg smartOs

### ISSUE THREAD

**Issue by ilya-dychkov** [bol-van/zapret#445]
Устанавливал zapret на Keenetic в начале сентября, получилось так что работало на всей технике в квартире ПК/ноуты/телевизор LG (smartOS)/телефоны
После проблем второй половины сентября поменял конфиг на
`--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/zapret/tls_clienthello_www_google_com.bin`

И сейчас работает на телефонах и телевизоре, но вот на ПК(провод от роутера) и ноутах(wifi) нет
Что можно поправить чтобы работало везде?

**Comment by NewUse** [comment]
doh на роутере настроен? Возможно, имеет смысл установить на роутере принудительный ttl=64,
проблема только с Ютуб,? quic пробовали включатт/выключать на ПК?

**Comment by ilya-dychkov** [comment]
> doh на роутере настроен? Возможно, имеет смысл установить на роутере принудительный ttl=64, проблема только с Ютуб,? quic пробовали включатт/выключать на ПК?

Doh должен быть, но перепроверю
Нет, вообще с телефона на тот же рутрекер или x заходит, с компов нет

**Comment by ilya-dychkov** [comment]
> doh на роутере настроен? Возможно, имеет смысл установить на роутере принудительный ttl=64, проблема только с Ютуб,? quic пробовали включатт/выключать на ПК?

DoH есть
принудительный ttl ничего не поменял
QUIC оказался в настройках браузера включен, без него на рутрекер заходит, но ютуб всё так же проблема, но теперь главная страница через раз прогружается

**Comment by NewUse** [comment]
doh на роутере настроен? Возможно, имеет смысл установить на роутере принудительный ttl=64,
проблема только с Ютуб,? quic пробовали включатт/выключать на ПК?

> > doh на роутере настроен? Возможно, имеет смысл установить на роутере принудительный ttl=64, проблема только с Ютуб,? quic пробовали включатт/выключать на ПК?
> 
> DoH есть принудительный ttl ничего не поменял QUIC оказался в настройках браузера включен, без него на рутрекер заходит, но ютуб всё так же проблема, но теперь главная страница через раз прогружается

попробуй опциию --dpi-desync=fake,split2 --oob для quic указать

**Comment by bol-van** [comment]
`попробуй опциию --dpi-desync=fake,split2 --oob для quic указать`

Это полный абсурд. --oob вообще к tcp и tpws относится, который udp не поддерживает
split для udp не работает

**Comment by NewUse** [comment]
упс, сорри

**Comment by zamiron** [comment]
На телевизорах LG также не работает (при корретной работе на всех остальных устройствах).
В дампах видно, что модификации не происходит и доменное имя (SNI) отправляется в неизменном виде.
С какого-то момента перестало открываться видео на ПК.
Выяснилось, что домены в зоне googlevideo.com не проходят процедуру split и отправляются в чистом виде.
Например: curl https://rr10---sn-n8v7kne6.googlevideo.com
В дампе: ->SYN<-SYN/ACK->ACK->fakeTLS->PSH/ACK->TLS rr10---sn-n8v7kne6.googlevideo.com в чистом виде.
