### ISSUE TITLE
На openwrt 23.05.5 "Command failed: not found" из вызова "procd_kill zapret" при запуске install_easy.

### ISSUE THREAD

**Issue by zhubr** [bol-van/zapret#446]
...
* checking DNS
system DNS is working
* checking virtualization
cannot detect
* stopping current firewall rules/daemons
Clearing nftables
Command failed: Not found <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-----

WARNING ! you are running a low RAM system
...

Увидел это сообщение об ошибке, подозреваю что чисто косметическая вещь, не влияющая ни на что, но на всякий случай сообщаю. Сообщения об ошибках всегда вызывают некоторые подозрения, что что-то пошло не по плану.

**Comment by bol-van** [comment]
да, это не опасно
вероятно отсутствует запущенный процесс

**Comment by zhubr** [comment]
> да, это не опасно вероятно отсутствует запущенный процесс

Я как раз так подумал. Но может тогда имеет смысл куда-нибудь добавить >/dev/null чтобы не нервировать особо дотошного пользователя? Или еще лучше сначала проверять наличие такого запущенного процесса? Я могу на досуге покопаться с этим и даже попытаться приготовить патч/PR, если это рассматривается как существенное.

**Comment by bol-van** [comment]
https://github.com/bol-van/zapret/commit/88a9f16b8ad997b8f9c6a05c16e13e343fa37dff
