### ISSUE TITLE
ip2net

### ISSUE THREAD

**Issue by avengermsoft** [bol-van/zapret#45]
Нельзя ли добавить в ip2net функционал, что бы он еще понимал такие диапазоны?

103.1.160.0-103.1.163.255
103.1.168.0-103.1.171.255

?

**Comment by bol-van** [comment]
откуда берутся такого рода листы ?
сделать то конечно можно, но в текущем виде ip2net вообще не работает с диапазонами. он их пропукает в режиме passthrough, не анализируя и не объединяя с чем-либо
получается, будет преобразование ip1-ip2 в набор prefix/subnet по минимально возможному количеству префиксов

**Comment by bol-van** [comment]
оказывается команда ipset сама умеет распознавать ip1-ip2 и преобразовывать их по оптимальному раскладу hash:net
так что задача сводится к пассивному пропуску таких диапазонов
