### ISSUE TITLE
Не удается успешно выполнить make mac на MacOS 10.14

### ISSUE THREAD

**Issue by Lachinio** [bol-van/zapret#452]
Возможно ли собрать dvtws на данной версии Mac os? В [мануале сказано](https://github.com/bol-van/zapret/blob/master/docs/bsd.txt), что поддерживаются версии от 10.12 (Sierra). 
[Лог сборки](https://github.com/user-attachments/files/17267321/make_mac_log.txt)

**Comment by bol-van** [comment]
см  docs/bsd.txt
диверт сокеты вырезаны из ядра
невозможно
