### ISSUE TITLE
Не работает обход на Arch Linux

### ISSUE THREAD

**Issue by RendeR66** [bol-van/zapret#453]
Перестал работать на arch linux. Лазил менял какие-то настройки сам не зная что всё равно не работает.
И после установки запрета перестали работать гос. услуги не могу туда попросту зайти.
В линуксе я 3 из 10. До 4 августа всё работало 100% без нариканей но повторюсь без гос услуг

У меня [dhcpcd](https://wiki.archlinux.org/title/Dhcpcd_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)) и [NetworkManager](https://wiki.archlinux.org/title/NetworkManager_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9))
[iptables](https://archlinux.org/packages/?name=iptables)
При установке месяц с лишним назад настраивал dhcpcd (настройки ip) 
При вводе команды ниже получаю это как и было при установке, но я взял готовое решение. 
> sudo ./blockcheck.sh  

```
* port block tests ipv4 rutracker.org:80
ipv4 rutracker.org does not resolve

* curl_test_http ipv4 rutracker.org
- checking without DPI bypass
[attempt 1] [attempt 2] [attempt 3] [attempt 4] [attempt 5] UNAVAILABLE code=6

* port block tests ipv4 rutracker.org:443
ipv4 rutracker.org does not resolve

* curl_test_https_tls12 ipv4 rutracker.org
- checking without DPI bypass
[attempt 1] [attempt 2] [attempt 3] [attempt 4] [attempt 5] UNAVAILABLE code=6

* curl_test_http3 ipv4 rutracker.org
- checking without DPI bypass
[attempt 1] [attempt 2] [attempt 3] [attempt 4] [attempt 5] UNAVAILABLE code=6

* SUMMARY
ipv4 rutracker.org curl_test_http : test aborted, no reason to continue. curl code 6: could not resolve host
ipv4 rutracker.org curl_test_https_tls12 : test aborted, no reason to continue. curl code 6: could not resolve host
ipv4 rutracker.org curl_test_http3 : test aborted, no reason to continue. curl code 6: could not resolve host

Please note this SUMMARY does not guarantee a magic pill for you to copy/paste and be happy.
Understanding how strategies work is very desirable.
This knowledge allows to understand better which strategies to prefer and which to avoid if possible, how to combine strategies.
Blockcheck does it's best to prioritize good strategies but it's not bullet-proof.
It was designed not as magic pill maker but as a DPI bypass test tool.

press enter to continue
```

**Comment by bol-van** [comment]
хост не ресолвится
возможно, пров использует православный днс
надо менять днс. если дом.ру - шифровать днс

**Comment by RendeR66** [comment]
> хост не ресолвится возможно, пров использует православный днс надо менять днс. если дом.ру - шифровать днс

у меня ростик, вы про это?

>  sudo nano /etc/resolv.conf  
если да то у меня тут:                                
```
# Generated by dhcpcd from enp42s0.dhcp, enp42s0.ra
# /etc/resolv.conf.head can replace this line
nameserver 192.168.31.1
nameserver (тут мой ip v6)
# /etc/resolv.conf.tail can replace this line
nameserver ::1
nameserver 127.0.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
nameserver 1.0.0.1
options edns0
```

**Comment by ferum365** [comment]
Ростик меняет алгоритм блокировки youtube  раз в 10-12 дней. У меня Rutracker  не резольвился изначально, в конце августа  чекал bbc.com проработало до 12 сентября. Потом нашёл готовый конфиг но работало тупо. Чекал по ссылке из кода страницы videoplayback. Дольше работает по  tpws  но всё равно не на всегда. Как перестаёт работать переделываю на новых настройках. Использую в качестве шлюза  tvbox rockchip rk3318 под  armbian,  форвардинг пакетов и маскарад  сети в iptables. В общем управляемся пока по роликам от доморощенных хацкеров... и да оно работает. ... а арчевский мануал так себе.
