### ISSUE TITLE
DPI Desync 

### ISSUE THREAD

**Issue by zhenyolka** [bol-van/zapret#46]
Пишу аналог goodbyedpi под андроид, который будет работать как http прокси. Уже написал консольный вариант на C++, который может обходить блокировки большинством способов, но пока не могу реализовать атаку десинхронизации(без которой, к примеру, блокировку по https на моем мобильном операторе обойти невозможно, т.к. он реконструирует tcp трафик).
Я пытался осуществить dpi desync с помощью отправки пакета с низким ttl, но после трех неудачных ретрансмиссий фейкового пакеты система закрывает соединение.
Как еще можно отправить пакет использую только возможности сокетов C++ так, чтобы он не дошел до сервера, но дошел до DPI?

**Comment by bol-van** [comment]
У меня отправка фейк-пакетов сделана через raw socket. Весь код для этого есть в nfqws, конкретно файл darkmagic.c
Чтобы правильно выполнить desync, нужно знать tcp sequence numbers и отправить пакет сразу после 3-way handshake, еще до отправки первого реального пакета.
По своей сути эта атака расчитана на работу на уровне пакетов, а не на уровне соединения .
Поэтому она у меня задействуется в рамках nfqws.
NFQUEUE есть на некоторых стоковых ядрах андроида точно, но я не имею статистики насколько  он распространен по разным производителям, моделям и версиям android.

Можно ли заменить чем-то nfqueue ? Теоретически, можно сделать свой мини-tcpdump. Ведь он же как-то работает ? Чтобы не хватать все подряд, у сокетов поддерживаются BPF фильтры. Вероятно, именно их и использует tcpdump. Я не копал глубже

**Comment by zhenyolka** [comment]
Спасибо за ответ. Видимо пока без dpi desync, раз заставить его работать на андроиде из-за рута и ядра нельзя.

**Comment by bol-van** [comment]
У меня появился доступ к подключению , где установлен с большой вероятностью именно  суверенный DPI.
Оказывается, он не проверяет sequence numbers вообще. Достаточно инжекта фейк-пакета с нулевыми сиквенсами, значит перехват пакетов не нужен.
Остается только простенький rawsend. Но требования рута никуда не уходят. Без cap_net_raw вообще невозможна прямая манипуляция с пакетами

**Comment by zhenyolka** [comment]
Спасибо, но рут никак нельзя.
На desync я плюнул и вместо него сделал возможность проксирования через socks5. Теперь есть вопрос: этот самый суверенный DPI, или вообще какой-либо DPI из используемых нашими провайдерами фильтрует трафик в прокси соединении или нет? И если да, то как часто такие у нас встречаются?
Так же интересно узнать, как вообще этот новый суверенный DPI работает, то есть есть ли возможность обойти его разделением пакетов на сегменты и изменением Host: заголовка, или на него действует только DPI desync?

**Comment by bol-van** [comment]
Да, многие DPI фильтруют http proxy. Нешифрованный http proxy протокол почти ничем не отличается от обычного http.  Важнее вопрос мониторит ли DPI нестандартные порты на предмет http.

Предположительно суверенный DPI, к которому  у меня есть доступ, ищет http только на 80 порту и tls только на 443, так что прокси даже не шифрованный должен сработать. Но на многих  других провайдерах это не работало, лучше не расчитывать.

Суверенный DPI уверенно противостоит большинству попыток его надурить.
Работает только перенос строки перед методом, но это ломает огромное количество серверов.
Так же он успешно противостоит давно применямым против китайского FW методам дурения на пакетном уровне. Видно, что он разрабатывался с учетом китайского опыта

**Comment by zhenyolka** [comment]
Не-не-не, я хотел спросить именно про socks5 прокси, с http и так понятно.

**Comment by bol-van** [comment]
socks прокси - это парочка раундтрипов, дальше идет plain tcp proxy без шифрования
суверенный DPI ищет TLS client hello сколь угодно долго на протяжении tcp соединения
