### ISSUE TITLE
при обновлении zapret удаляются мои фейки

### ISSUE THREAD

**Issue by eastone11** [bol-van/zapret#460]
Можно ли сделать чтобы при обновлении zapret через install_easy.sh оставались мои *bin в \opt\zapret\files\fake\?

Немного тупил почему старая стратегия перестала работать после обновления, думал что при таком обновлении он не трогает мои изменения, но видимо это касается только конфига.

**Comment by bol-van** [comment]
убирайте их из /opt/zapret
там не место вашим файлам

**Comment by bol-van** [comment]
нелогично. установка сносит ненужные более файлы из старых версий
вносить в установщик историю изменений это геморно и ненужно
гораздо проще создать директорию вне /opt/zapret и хранить там все свое

**Comment by eastone11** [comment]
> нелогично. установка сносит ненужные более файлы из старых версий вносить в установщик историю изменений это геморно и ненужно гораздо проще создать директорию вне /opt/zapret и хранить там все свое

понял, спасибо
