### ISSUE TITLE
Всю запретку грузит кроме ютуба XD

### ISSUE THREAD

**Issue by AlexRay2** [bol-van/zapret#464]
Грузит все кроме ютуба,  в blockcheck выдало:
ipv4 rutracker.org curl_test_http : tpws --split-http-req=method --oob
ipv4 rutracker.org curl_test_http : nfqws --dpi-desync=fake --dpi-desync-ttl=6
ipv4 rutracker.org curl_test_https_tls12 : tpws not working
ipv4 rutracker.org curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=6
ipv4 rutracker.org curl_test_http3 : nfqws --dpi-desync=fake
вот, в  install_easy.sh:
NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-ttl=6"
NFQWS_OPT_DESYNC_SUFFIX=""
NFQWS_OPT_DESYNC_HTTP=""
NFQWS_OPT_DESYNC_HTTP_SUFFIX=""
NFQWS_OPT_DESYNC_HTTPS=""
NFQWS_OPT_DESYNC_HTTPS_SUFFIX=""
NFQWS_OPT_DESYNC_HTTP6=""
NFQWS_OPT_DESYNC_HTTP6_SUFFIX=""
NFQWS_OPT_DESYNC_HTTPS6=""
NFQWS_OPT_DESYNC_HTTPS6_SUFFIX=""
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6"
NFQWS_OPT_DESYNC_QUIC_SUFFIX=""
NFQWS_OPT_DESYNC_QUIC6=""
NFQWS_OPT_DESYNC_QUIC6_SUFFIX=""
 Как починить?

**Comment by Gleb-pro-admin** [comment]
Наблюдаются внеерестровые блокировки IP адресов Google. В частности, так делает провайдер МТС по Ethernet. Тут не поможет ни GoodbyeDPI, ни Zapret, ни SpoofDPI.
Попробуй сменить браузер, использовать мобильное приложение, или несколько раз перезагрузить видео. С 10 попытки должно открыться.

**Comment by ThisIsNoTa2acc** [comment]
Да тоже ютуб перестал работать, джентельмены, какие-нибудь решения есть?

**Comment by Demo13B** [comment]
Присоединяюсь, сегодня перестал грузить. Несколько часов пробовал разные конфиги, ничего не помогает. Справедливости ради, я мало что в этом понимаю, может кто лучше меня разбирается и нашел фикс. Даже Дискорд грузит спокойно с одним ютубом траблы)

**Comment by inkcmd** [comment]
у меня не работает на openwrt уже месяц как или два. как только поставил работало, а вторая волна блокировки и не могу подобрать ничего на ютуб. ростелеком, тамбов. гудбайдпи работает обновленный. и под виндой запрет работает с дефолтными настройками. поставил конфиг еще и под дискорд от чувака с гитхаба, тоже работает все. а под линуксом не работает ничего. 
про дискорд - если добавить в custom обход по udp с портами 50000+ опять же из обсуждения + какой то обход на quic 443 в config, и включить на компе гудбайдпи или запрет стандарными cmd, то тоже работает. то есть обход udp работает, а http и https не работает у меня. такие выводы сделал. месяц назад просто плюнул подбирать стратегии, времени конечно много на это уходит. особенно если они не работают. сегодня blockcheck прогнал, на выходных попытаюсь что то подобрать себе.

**Comment by yury-sch** [comment]
Та же беда, везде перестало работать сегодня. Проверял в Safari, AppleTV, клиенте под iOS, Яндекс браузере (под macos и из под винды), Android смартфоне. Единственное место где работает нормально: браузер Microsoft Edge. Еще бывает в Yandex браузере видео все же запускается спустя минут 10

**Comment by minamoto-ru** [comment]
Не работает в Chrome и работает в Edge, т.к. в начале эпопеи с блокировками многие отключили экспериментальные фичи - "Experimental QUIC protocol" и "TLS 1.3 hybridized Kyber support". Если запущен Zapret и эти две фичи переключить обратно в состояние "Default" - Ютуб начинает работать.

**Comment by ivdeveloper86** [comment]
Только что перестал грузить Ютуб (пров Билайн), остальное работает, конфиг такой:
DVTWS="--daemon --qnum=200 --dpi-desync=fake,disorder2 --dpi-desync-autottl --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-tls=/tmp/mnt/DPI/zapret-master/files/fake/tls_clienthello_www_google_com.bin --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

где-то месяц назад так же резко перестало работать на --dpi-desync=fake,split2, тогда перешел на текущий вариант --dpi-desync=fake,disorder2

**Comment by ivdeveloper86** [comment]
у меня завелся ютуб на конфиге  --dpi-desync=fake,disorder и  --dpi-desync=fake,split, выбирайте какой больше нравится

**Comment by inkcmd** [comment]
> у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится

слишком просто. может провайдер помогает? знаю таких, у кого ютуб без плясок работает

**Comment by ThisIsNoTa2acc** [comment]
> у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится

мне лично не помогло

**Comment by ThisIsNoTa2acc** [comment]
@bol-van есть идеи?

**Comment by ivdeveloper86** [comment]
У меня работает, но есть косяк, некоторые ролики запускаются сразу, а некоторые грузятся по 20-30 секунд, иногда и по минуте может крутить... Не знаю как с этим бороться, уже и Experimental QUIC protocol отключил и TLS 1.3 hybridized Kyber support включил, никакой разницы.

**Comment by Maeglor** [comment]
Тоже самое, Ютуб часа 2 назад внезапно перестал работать.

**Comment by undefinedquest** [comment]
YT.cmd
```
start "zapret: youtube" /min "%~dp0winws.exe" ^
--wf-tcp=80,443 --wf-udp=443 ^
--filter-udp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new
```

Все вышеперечисленные флаги в дефолт поставить
Ребут браузера
Ютуб в начале прогрузки видео думает секунд 10-15, иногда придется ф5 прожать, как только начинается прогрузка все идеально в 4к идет
Работает в Chrome на Билайне

**Comment by ThisIsNoTa2acc** [comment]
> YT.cmd
> 
> ```
> start "zapret: youtube" /min "%~dp0winws.exe" ^
> --wf-tcp=80,443 --wf-udp=443 ^
> --filter-udp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
> --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
> --filter-tcp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new
> ```
> 
> Все вышеперечисленные флаги в дефолт поставить Ребут браузера Ютуб в начале прогрузки видео думает секунд 10-15, иногда придется ф5 прожать, как только начинается прогрузка все идеально в 4к идет Работает в Chrome на Билайне

А в конфиге под роутер можно это?

**Comment by yury-sch** [comment]
> у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится

Так же и у меня, заменил `--dpi-desync=fake,disorder2` на `--dpi-desync=fake,split2` худо бедно начало работать на всех устройствах. Но справедливости ради у меня еще целая простыня настроек после идет `--dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin`

**Comment by zamiron** [comment]
Попробуйте пожалуйста curl https://rr10---sn-n8v7kne6.googlevideo.com
В этом случае TLS hello у вас разбивается на части в режиме disorder или split ? (в дампе на исходящем интерфейсе)
У меня не разбивается не смотря на то что fake hello отправляется.

Пробовал с разными параметрами. Измнений нет. Пример опций:
--dpi-desync=fake,disorder --dpi-desync-fooling=badsum  --dpi-desync-fake-tls=/opt/tls_clienthello_vk_com.bin --dpi-desync-fake-unknown=/opt/tls_clienthello_vk_com.bin

**Comment by Demo13B** [comment]
> > у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится
> 
> Так же и у меня, заменил `--dpi-desync=fake,disorder2` на `--dpi-desync=fake,split2` худо бедно (иногда сразу грузит, иногда ждать надо секунд 30) начало работать на всех устройствах. Но справедливости ради у меня еще целая простыня настроек после идет `--dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin`

Вот на этом конфиге более-менее завелось. Пробовал без `--dpi-desync-fake-tls`, не работало, а с ним запахало, видимо он является важной частью. Точно так же видосы грузятся по 30 секунд в начале, но хотя бы так, большое спасибо за конфиг)

**Comment by ThisIsNoTa2acc** [comment]
split2 помогло

**Comment by ThisIsNoTa2acc** [comment]
# this file is included from init scripts
# change values here

# can help in case /tmp has not enough space
#TMPDIR=/opt/zapret/tmp

# redefine user for zapret daemons. required on Keenetic
WS_USER=nobody

# override firewall type : iptables,nftables,ipfw
FWTYPE=iptables

# options for ipsets
# maximum number of elements in sets. also used for nft sets
SET_MAXELEM=522288
# too low hashsize can cause memory allocation errors on low RAM systems , even if RAM is enough
# too large hashsize will waste lots of RAM
IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
# dynamically generate additional ip. $1 = ipset/nfset/table name
#IPSET_HOOK="/etc/zapret.ipset.hook"

# options for ip2net. "-4" or "-6" auto added by ipset create script
IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
# options for auto hostlist
AUTOHOSTLIST_RETRANS_THRESHOLD=3
AUTOHOSTLIST_FAIL_THRESHOLD=3
AUTOHOSTLIST_FAIL_TIME=60
# 1 = debug autohostlist positives to ipset/zapret-hosts-auto-debug.log
AUTOHOSTLIST_DEBUGLOG=0

# number of parallel threads for domain list resolves
MDIG_THREADS=30

# ipset/*.sh can compress large lists
GZIP_LISTS=1
# command to reload ip/host lists after update
# comment or leave empty for auto backend selection : ipset or ipfw if present
# on BSD systems with PF no auto reloading happens. you must provide your own command
# set to "-" to disable reload
#LISTS_RELOAD="pfctl -f /etc/pf.conf"

# override ports
#HTTP_PORTS=80-81,85
#HTTPS_PORTS=443,500-501
QUIC_PORTS=443-65535

# CHOOSE OPERATION MODE
# MODE : nfqws,tpws,tpws-socks,filter,custom
# nfqws : nfqws for dpi desync
# tpws : tpws transparent mode
# tpws-socks : tpws socks mode
# filter : no daemon, just create ipset or download hostlist
# custom : custom mode. should modify custom init script and add your own code
MODE=nfqws
# apply fooling to http
MODE_HTTP=1
# for nfqws only. support http keep alives. enable only if DPI checks for http request in any outgoing packet
MODE_HTTP_KEEPALIVE=0
# apply fooling to https
MODE_HTTPS=1
# apply fooling to quic
MODE_QUIC=1
# none,ipset,hostlist,autohostlist
MODE_FILTER=autohostlist

# CHOOSE NFQWS DAEMON OPTIONS for DPI desync mode. run "nfq/nfqws --help" for option list
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin" 
#NFQWS_OPT_DESYNC_HTTP=
#NFQWS_OPT_DESYNC_HTTPS=
#NFQWS_OPT_DESYNC_HTTP6=
#NFQWS_OPT_DESYNC_HTTPS6=
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,split2 --dpi-desync-repeats=6 --dpi-desync-ttl=0  --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"
#NFQWS_OPT_DESYNC_QUIC6=

# CHOOSE TPWS DAEMON OPTIONS. run "tpws/tpws --help" for option list
TPWS_OPT="--hostspell=HOST --tlsrec=sni --split-pos=1 --oob --disorder"

# openwrt only : donttouch,none,software,hardware
FLOWOFFLOAD=donttouch

# openwrt: specify networks to be treated as LAN. default is "lan"
#OPENWRT_LAN="lan lan2 lan3"
# openwrt: specify networks to be treated as WAN. default wans are interfaces with default route
#OPENWRT_WAN4="wan vpn"
#OPENWRT_WAN6="wan6 vpn6"

# for routers based on desktop linux and macos. has no effect in openwrt.
# CHOOSE LAN and optinally WAN/WAN6 NETWORK INTERFACES
# or leave them commented if its not router
# it's possible to specify multiple interfaces like this : IFACE_LAN="eth0 eth1 eth2"
# if IFACE_WAN6 is not defined it take the value of IFACE_WAN
#IFACE_LAN=eth0
IFACE_WAN=ppp0
#IFACE_WAN6="ipsec0 wireguard0 he_net"

# should start/stop command of init scripts apply firewall rules ?
# not applicable to openwrt with firewall3+iptables
INIT_APPLY_FW=1
# firewall apply hooks
#INIT_FW_PRE_UP_HOOK="/etc/firewall.zapret.hook.pre_up"
#INIT_FW_POST_UP_HOOK="/etc/firewall.zapret.hook.post_up"
#INIT_FW_PRE_DOWN_HOOK="/etc/firewall.zapret.hook.pre_down"
#INIT_FW_POST_DOWN_HOOK="/etc/firewall.zapret.hook.post_down"

# do not work with ipv4
#DISABLE_IPV4=1
# do not work with ipv6
DISABLE_IPV6=0

# select which init script will be used to get ip or host list
# possible values : get_user.sh get_antizapret.sh get_combined.sh get_reestr.sh get_hostlist.sh
# comment if not required
GETLIST=

**Comment by ivdeveloper86** [comment]
один 'гений' написал --dpi-desync-repeats=6 --dpi-desync-any-protocol, остальные дружно скопировали этот бред)

**Comment by Maeglor** [comment]
В целом отвисло само. 

Сейчас повередие такое: секунд 10 пупит на загрузке информации о видео, после того как оно подгрузилось, дальше без тормозов.

Похоже что решения указанные выше это плацебо. 

У меня конфиг предельно тупой: 

NFQWS_OPT_DESYNC=--dpi-desync=split2

**Comment by yury-sch** [comment]
> один 'гений' написал --dpi-desync-repeats=6 --dpi-desync-any-protocol, остальные дружно скопировали этот бред)

Ты бы лучше рассказал что тут не так

**Comment by AlexRay2** [comment]
> у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится

не помогло :(

**Comment by Gleb-pro-admin** [comment]
> В целом отвисло само.
Явный признак блокировки по IP. Не все сервера Google доступны в России. Иногда попадается рабочий, иногда нет. Нужен способ предопредилить выбор сервера.

**Comment by Serg-VL** [comment]
У меня так сработало
`NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-split-seqovl=1 --dpi-desync-ttl=0 --dpi-desync-repeats=7 --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"`

**Comment by AlexRay2** [comment]
У меня РОСТЕЛЕКОМ если что:)

**Comment by prOOrc** [comment]
> У меня РОСТЕЛЕКОМ если что:)
У меня только с такими настройками работает.
```
NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"
```

**Comment by Nordwise** [comment]
Москва, МГТС. Фиксы никакие не работают вообще. Похоже реально блочат айпишники сидят.

**Comment by Letton** [comment]
Подмосковье, МГТС. Аналогично никакие стратегии не помогают, работает всё, кроме ютюба.

**Comment by PalachMB** [comment]
> У меня РОСТЕЛЕКОМ если что:)
Это вообще не показатель. В моем небольшом городке, где всего один филиал с оборудованием РТ, у меня не работает ни с какими примочками, а в соседнем доме работает без всяких приблуд. 
Уже плюнул на подбор обманок, нужные ролики проще через ВПН смотреть, чем по три часа подбирать кратковременные опции ради 3-хминутного видео, которые через полчаса могут перестать работать

**Comment by GottaGOS** [comment]
Sunlink, Тула. Никакие конфиги не пашут. Будем ждать решения :/

**Comment by hukarere** [comment]
До вчерашнего дня пользовался youtubeUnblock на Линуксе, вчера перестал работать, ищу альтернативу, зашел сюда, а тут пишут, что zapret со вчерашнего же дня не работает с теми же симптомами: какие параметры ни пробуй, задержка при запуске youtube видео до минуты.

Автор youtubeUnblock объяснил это так на https://github.com/Waujito/youtubeUnblock/issues/148#issuecomment-2405713651 :
> В общем, что случилось. Предварительно, имеем простейший маппинг GGC, которые хостят только сервера googlevideo. И таким серверам просто обрубают весь TLS трафик, независимо от SNI. Видимо, синфэйк вызывает глюк у ТСПУ, и он начинает хуже анализировать трафик.

Так что по описанию похоже, что ни youtubeUnblock, ни zapret пока не пофиксили, ищу другие решения для линукса...

**Comment by yury-sch** [comment]
> > у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится
> 
> Так же и у меня, заменил `--dpi-desync=fake,disorder2` на `--dpi-desync=fake,split2` худо бедно (иногда сразу грузит, иногда ждать надо секунд 30) начало работать на всех устройствах. Но справедливости ради у меня еще целая простыня настроек после идет `--dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin`

Как объяснил автор на другом ресурсе:
"Проблема в том, что анализатор трафика не хочет сразу отставать от потока после фейковых пакетов и ловит реальные client hello и блокирует поток. Решение - увеличиваем число фейковых пакетов через параметр dpi-desync-repeats" 
Я вернул --dpi-desync=fake,disorder2 и выставил --dpi-desync-repeats=15 - все заработало идеально (Билайн)

**Comment by Demo13B** [comment]
> > > у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится
> > 
> > 
> > Так же и у меня, заменил `--dpi-desync=fake,disorder2` на `--dpi-desync=fake,split2` худо бедно (иногда сразу грузит, иногда ждать надо секунд 30) начало работать на всех устройствах. Но справедливости ради у меня еще целая простыня настроек после идет `--dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin`
> 
> Как объяснил автор на другом ресурсе: "Проблема в том, что анализатор трафика не хочет сразу отставать от потока после фейковых пакетов и ловит реальные client hello и блокирует поток. Решение - увеличиваем число фейковых пакетов через параметр dpi-desync-repeats" Я вернул --dpi-desync=fake,disorder2 и выставил --dpi-desync-repeats=15 - все заработало идеально (Билайн)

Да, действительно работает лучше. Правда у меня пока все равно на запучк видео уходит 5-10 секунд, на телефоне по прежнему 30 секунд. Надо попробовать поиграться с этим параметром.

**Comment by ED6-cmyk** [comment]
> > > > у меня завелся ютуб на конфиге --dpi-desync=fake,disorder и --dpi-desync=fake,split, выбирайте какой больше нравится
> > > 
> > > 
> > > Так же и у меня, заменил `--dpi-desync=fake,disorder2` на `--dpi-desync=fake,split2` худо бедно (иногда сразу грузит, иногда ждать надо секунд 30) начало работать на всех устройствах. Но справедливости ради у меня еще целая простыня настроек после идет `--dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin`
> > 
> > 
> > Как объяснил автор на другом ресурсе: "Проблема в том, что анализатор трафика не хочет сразу отставать от потока после фейковых пакетов и ловит реальные client hello и блокирует поток. Решение - увеличиваем число фейковых пакетов через параметр dpi-desync-repeats" Я вернул --dpi-desync=fake,disorder2 и выставил --dpi-desync-repeats=15 - все заработало идеально (Билайн)
> 
> Да, действительно работает лучше. Правда у меня пока все равно на запуск видео уходит 5-10 секунд, на телефоне по прежнему 30 секунд. Надо попробовать поиграться с этим параметром.

Подтверждаю, стало грузиться в несколько десятков раз быстрее, почти незаметно с паузой. Ростелеком.

**Comment by kast88x** [comment]
> > У меня РОСТЕЛЕКОМ если что:)
> 
> У меня только с такими настройками работает.
> 
> ```
> NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"
> ```

на Билайн заработало, спасибо!

**Comment by andyvtrende** [comment]
> > > У меня РОСТЕЛЕКОМ если что:)
> > 
> > 
> > У меня только с такими настройками работает.
> > ```
> > NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"
> > ```
> 
> на Билайн заработало, спасибо!

Москва, Ростелеком, работают видео шортсы стримы на android и windows pc

**Comment by admsergei** [comment]
На МТС главная ютуба не работает ни в какой конфигурации, стабильно выкидывает "Нет подключения". Если загрузить страницу с видео и запустить службу, то начинает грузить поток. Видимо, оператор топорно сбрасывает соединение. 

Так же не работает инстаграм, прогнал blockcheck (standart, http/https, tls1.2-1.3, verify-server-cert), получил параметры:
```
ipv4 instagram.com curl_test_http : winws not working
ipv4 instagram.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=fake,split --dpi-desync-fooling=datanoack --dpi-desync-split-pos=1
ipv4 instagram.com curl_test_https_tls13 : winws not working
ipv4 instagram.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake
```
Вписал в конфиг `--new -dpi-desync=fake,split --dpi-desync-fooling=datanoack --dpi-desync-split-pos=1 --hostlist="%~dp0list-additional.txt"` - ноль эффекта, страница не грузится. На любом другом операторе конфиг работает.

**Comment by MUKS1T1MRUS** [comment]
товарищи присоединяюсь к данному мероприятию сижу на операторе авокадо вот грузит все все поголовно даже ютуб шортс но вот сам ютуб на большие ролики не работает причем с начала 2025 года перестало все работать знающие люди давайте помогайте что можно вписать (гудбай дпи уже отвалился на все запрет работает на все кроме ютуб спуф дпи не пробовал так что пишу предварительно)
