### ISSUE TITLE
Вместе с zapret не рабоает vpn

### ISSUE THREAD

**Issue by nikofon** [bol-van/zapret#465]
Здравствуйте, стоит запрет на системе linux работает по правилу tpws --split-pos=1 --oob. 
Однако когда я пытаюсь включить vpn (Windscribe), то он не работает по любому протоколу. Vpn на 443 порте если это важно.
Нужно ли мне настроить прокси в настройках vpn или что то еще сделать? (я сам в этом не очень понимаю, извините если вопрос глупый)

**Comment by andmt1** [comment]
Надо настроить фильтр по списку:
установить отпцию: MODE_FILTER=hostlist 
и внести хосты в файл zapret-hosts-user.txt (белый список) или exclude - исключить. Это всё есть в инструкции

**Comment by mnogourona** [comment]
> Надо настроить фильтр по списку: установить отпцию: MODE_FILTER=hostlist и внести хосты в файл zapret-hosts-user.txt (белый список) или exclude - исключить. Это всё есть в инструкции

Здравствуйте, я абсолютно не разбираюсь в сетях, но столкнулся с похожей проблемой что и человек выше, раньше я просто выключал запрет и спокойно пользовался VPN'ом, но сейчас, по какой-то причине, у меня не выключается запрет полностью, он как бы не работает, но на фоне есть какие-то процессы, препятствующие запуску VPN, в случае ADGuard и ему подобных просто нет сетей, пытался подключиться без использования сторонних программ через встроенные функции винды, но просто идет бесконечное подключение, в какой-то момент начал подозревать что дело может быть в провайдере, но это не так, на телефоне vpn работает, при смене сети тоже ничего не меняется, помогите пожалуйста, не могу найти ответ на свой вопрос в интернете, даже chatgpt бессилен 😅
