### ISSUE TITLE
Не работает Запрещенограм

### ISSUE THREAD

**Issue by IGOR3K99** [bol-van/zapret#468]
Здравствуйте. У меня такая проблема. Я не могу зайти в Запрещенограм. То есть я пытаюсь в него зайти и у меня постоянно выскакивает ошибка ERROR_CONNECTION_RESET. Еще я пробовал прогнать тест запрещенограма через blockcheck, и там тоже ни ответа ни привета. И вот можно ли как-нибудь это исправить? Если да, то как?

[config.txt](https://github.com/user-attachments/files/17321223/config.txt) - мною настроенная конфига (.txt я в конце добавил, потому что без него браузер не видит этот файл)
[blockcheck.txt](https://github.com/user-attachments/files/17320399/blockcheck.txt) - выхлоп при тесте Запрещенограма через blockcheck.

P. S.: в файл с хостами Запрещенограм я тоже добавил, но это вообще никак мне не помогает.
P. P. S.: пользуюсь я сейчас МГТСом.

**Comment by Alexey71** [comment]
Прежде чем запускать blockcheck. Читайте что пишут там.
```
* checking already running zapret processes
!!! WARNING. some dpi bypass processes already running !!!
!!! WARNING. blockcheck requires all DPI bypass methods disabled !!!
!!! WARNING. pls stop all dpi bypass instances that may interfere with blockcheck !!!
```

**Comment by eastone11** [comment]
> Прежде чем запускать blockcheck. Читайте что пишут там.
> 
> ```
> * checking already running zapret processes
> !!! WARNING. some dpi bypass processes already running !!!
> !!! WARNING. blockcheck requires all DPI bypass methods disabled !!!
> !!! WARNING. pls stop all dpi bypass instances that may interfere with blockcheck !!!
> ```
> 
> @bol-van Какой нибудь ограничитель сделать, чтобы при запущеном запрете не чекала ничего

не будет это делать
![Uploading 1fcc3a96060e06bdd5d215a9e854c03d.png…]()

**Comment by IGOR3K99** [comment]
> Прежде чем запускать blockcheck. Читайте что пишут там.
> 
> ```
> * checking already running zapret processes
> !!! WARNING. some dpi bypass processes already running !!!
> !!! WARNING. blockcheck requires all DPI bypass methods disabled !!!
> !!! WARNING. pls stop all dpi bypass instances that may interfere with blockcheck !!!
> ```
> 
> @bol-van Какой нибудь ограничитель сделать, чтобы при запущеном запрете не чекала ничего

Ок. Я вырубил запрет. И все равно ничего не поменялось.

[blockcheck.txt](https://github.com/user-attachments/files/17330775/blockcheck.txt)

**Comment by Alexey71** [comment]
Тогда ищите ип адрес рабочий через [это](https://ntc.party/t/%D0%BF%D0%BE%D0%B4%D0%B1%D0%BE%D1%80-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B5%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B0-%D0%B4%D0%BB%D1%8F-ggc-%D1%8E%D1%82%D1%83%D0%B1%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-blockcheck/10060/116). Потом в hosts добавлять найденый рабочий ип с доменом инсты

**Comment by jestxfot** [comment]
У меня завёлся
```bash
--dpi-desync=fake,split2 --dpi-desync-ttl=0 --dpi-desync-autottl=6 --dpi-desync-repeats=12 --dpi-desync-split-pos=1 --dpi-desync-fooling=md5sig,badseq
```

**Comment by IGOR3K99** [comment]
> ```shell
> --dpi-desync-repeats=12
> ```

И у меня, кстати, тоже с этой конфигой Запрещенограм завелся. Правда потом мне пришлось обратно поставить значение 0 в dpi desync ttl и dpi desync fooling полностью убрать, потому что плеер в Ютубе у меня не работал. Так что, спасибо jestxfot за помощь.
