### ISSUE TITLE
При активном сервисе не работает stackoverflow.com (всё семейство сайтов)

### ISSUE THREAD

**Issue by h4tr3d** [bol-van/zapret#469]
Браузер Firefox, выдаёт:

> ## Secure Connection Failed
> 
> An error occurred during a connection to stackoverflow.com. Cannot communicate securely with peer: no common encryption > algorithm(s).
> 
> Error code: `SSL_ERROR_NO_CYPHER_OVERLAP`
> 
> - The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> - Please contact the website owners to inform them of this problem.

Добавил его в исключения в `/opt/zapret/ipset/zapret-hosts-user-exclude.txt`:
```
# SO familiy
stackoverflow.com
```

сделал рестарт сервиса, результата нет. Чую, что нужно подшаманить что-то в настройках, но не понятно.

Запускаю на Desktop x86_64, Manjaro, ядро 6.10.11

**Comment by Fenrir-0xFF** [comment]
Добавь --dpi-desync-fooling=md5sig,**badsum**

**Comment by Fenrir-0xFF** [comment]
Добавь --dpi-desync-fooling=md5sig,**badsum**
