### ISSUE TITLE
Проблемы с nfqws на старом роутере

### ISSUE THREAD

**Issue by myzmike** [bol-van/zapret#474]
Столкнулся со странным глюком, когда настраивал zapret на старом роутере под управлением OpenWRT 14.07 с iptables +fw3. Если запускать nfqws в консоли с параметром --debug, то все работает. Если запускать без этого параметра, то обход не работает, в логах конечно пусто. Если демонизировать процесс, то ничего не работает ни с параметром --debug, ни без него. То есть, единственный вариант - запускать nfqws в консоли с параметром --debug, что, мягко говоря, не очень удобно

**Comment by bol-van** [comment]
Эта та самая lexra ?
Вариант --debug=@filename
что-то меняет ?

**Comment by myzmike** [comment]
Да, она самая. Вариант --debug=@filename посмотрю и отпишусь.

**Comment by myzmike** [comment]
С вариантом

**Comment by bol-van** [comment]
Ошибки buffer space где видны ? В логе nfqws или dmesg ?
Что с памятью ?

На кинетиках была проблема с утеканием slab на nfqueue на старом ядре 4.9. Тут еще древнее. Не знаю есть ли этот баг там.
Но отсутствие работы без --debug это не обьясняет

**Comment by myzmike** [comment]
Ошибки no buffer space available падали в stderr, когда процесс был в фоновом режиме. Но сегодня повторить не удалось, нет таких ошибок. Единственное, поменял некоторые параметры дурения. Какие были вчера, уже не вспомню.
Ситуацию с --debug это, конечно, не объясняет.
 Пока придумал такой костыль --debug=@/dev/null Вроде, работает. 
С blockcheck.sh тоже странная история. Он сканирует, но никаких рабочих стратегий не находит вообще. DNS точно в норме, удалось на этой старой коробке настроить связку stubby + unbound, все это завернуто на Cloudflare. Попробую прописать в скрипте такой же костыль, и посмотрю, что получится

**Comment by myzmike** [comment]
Проблема с blockcheck решилась пересборкой curl с OpenSSL вместо PolarSSL
Костыль работает. Так что, если не времени и желания выяснять, что там с --debug, то можно, наверное, закрыть issue
Спасибо за отличный софт!

**Comment by bol-van** [comment]
Неудивительно. Криптолиба 10+ летней давности. ca-certificates тоже
