### ISSUE TITLE
Поддержка структур в хост листе.

### ISSUE THREAD

**Issue by shikulja** [bol-van/zapret#476]
пример -

[torrents]
rutracker.org
nnmclub.to

Обоснование изменений -
- структуры [host list] пригодятся для подключения и отключения блоков хост листа, без разрастания количества рандомных хост листов под определенные задачи.

**Comment by shikulja** [comment]
; в файле должен быть хост на каждой строке. - пропуск пустых строк?

**Comment by bol-van** [comment]
Комментарии уже есть.
Если первый символ на строке # ; /  или строка пустая, хост не заносится в лист

**Comment by shikulja** [comment]
@bol-van спасибо, пока этого хватит, оставим открытым на подумать о блоках?

**Comment by bol-van** [comment]
Тэги требуют отдельной опции в параметрах.
Мне кажется эта функция нужна очень редко.
Разных файлов хватит. Их можно сколько угодно насоздавать и использовать.
Возможно, имеет смысл сделать что-то типа --hostlist-dir, откуда будут загружаться все файлы.
Это сделать намного проще

**Comment by shikulja** [comment]
Лучше использовать тег и логику их работы. 
[Общий список]
[сервис1]
[сервис2]
если подгружать все, то это идея не очень тем, что
list-youtube
