### ISSUE TITLE
Пожалуйста добавляйте в репозиторий теги для каждой версии

### ISSUE THREAD

**Issue by remittor** [bol-van/zapret#477]
## Проблема:

Сейчас делаю ipk пакеты для OpenWrt:
https://github.com/remittor/zapret-openwrt/blob/a7289f779ab1a6f977349cf2b83f395eb76edf08/zapret/Makefile#L15-L18
и автосборщик OpenWrt очень долго выкачивает репозиторий zapret: `git clone <...> && git switch <commit_hash>`
Для сторонней обёртки очень важно привязываться к конкретной ветке или версии.
А так как вы очень часто коммитите в свой репозиторий бинари, то полное дерево сорцов в git очень большого размера. И `git clone` всё это дерево выкачивает.

## Решение:

Как только в в файл `changes.txt` добавляете новую версию, то сразу добавьте новый tag в репо на github.
Например для текущей версии tag может иметь название "v63" или "v1.63" (как вам нравится).
При этом github автоматом сохранит для каждого tag'a zip и tgz с сорцами.
И сторонние разработчики (для и юзеры) смогут выкачивать сорцы по имени tag'а.

**Comment by bol-van** [comment]
Там нельзя качать по commit hash ?
Тэги посмотрю. Не пользовался никогда

**Comment by remittor** [comment]
> Там нельзя качать по commit hash ?

Так сейчас так и буду делать. Но саму git'у необходимо полное дерево скачать, прежде чем переключиться на указанную через commit_hash ветку кода.
Так устроен git.

**Comment by remittor** [comment]
@bol-van 
Всё чётко! Спс!
