### ISSUE TITLE
Работающая стратегия для Discord?

### ISSUE THREAD

**Issue by nikofon** [bol-van/zapret#479]
На стратегиях которые я пробую само приложение работает, однако нет возможности подключиться к голосовым каналам (не просиходит соединение к RTC серверу, пишет что не находит маршрут).
Видел что умельцы выпустили батники для виндовса которые работают, есть инфа как их перенести в конфиг (или просто выбрать может у кого есть работающие стратегии)?

**Comment by ampilda** [comment]
У меня через QUIC заработало
```
QUIC_PORTS=50000-65535
MODE_QUIC=1
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
```

**Comment by S1lenix** [comment]
У меня на win версии запрета работает --filter-udp=50000-65535 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin"
А на роутере
QUIC_PORTS=50000-65535
MODE_QUIC=1
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"
не завелось, не понимаю почему

**Comment by bol-van** [comment]
> У меня через QUIC заработало
> 
> ```
> QUIC_PORTS=50000-65535
> MODE_QUIC=1
> NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
> ```

ОТМЕЧАЮ ТРЭШ С ЖЕСТОКИМ ФЛУДОМ

**Comment by inkcmd** [comment]
если у вас зависания на моменте "Подключение к RTC" - проблема квика. если же у вас висит "Подключение", то нет обхода Http\https. я это так понимаю

**Comment by loxdogs** [comment]
> > У меня через QUIC заработало
> > ```
> > QUIC_PORTS=50000-65535
> > MODE_QUIC=1
> > NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
> > ```
> 
> ОТМЕЧАЮ ТРЭШ С ЖЕСТОКИМ ФЛУДОМ

а что это значит? Так не делать или что?

**Comment by bol-van** [comment]
Прошу прощения, не то процитировал
Проблема есть на win версии, если не добавляется --dpi-desync-cutoff=d4, что приводит к отсылке огромного количества ненужных пакетов в сеть (ее наводнение мусором, трэшем, флудом)
Хотя такое применение QUIC параметра и непредусмотрено , флуда в данном случае не будет, потому что в скриптах запуска для linux используется ограничитель connbytes

**Comment by nikofon** [comment]
Если что вот это для меня сработало, мейтенер как всегда на шаг впереди: https://github.com/bol-van/zapret/discussions/475

**Comment by Fantazion-Git** [comment]
> > У меня через QUIC заработало
> > ```
> > QUIC_PORTS=50000-65535
> > MODE_QUIC=1
> > NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
> > ```
> 
> ОТМЕЧАЮ ТРЭШ С ЖЕСТОКИМ ФЛУДОМ

боже чел, спасибо! Кастомные скрипты не помогли.
