### ISSUE TITLE
Различия wsize и disorder2/split2

### ISSUE THREAD

**Issue by HanabishiRecca** [bol-van/zapret#48]
В общем суть: обход через простой **wsize** работает нормально. А через **disorder2** и **split2** - нет.
Вопрос, есть ли фундаментальные различия в принципе работы, которые могут по-разному на DPI влиять?

**Comment by bol-van** [comment]
Они похожи по результату, но есть различные моменты, связанные с клиентской системой. При wsize сегментацию осуществляет клиент, а не роутер. Linux и windows это делают по-разному
При disorder сегментацию выполняет роутер.
Надо дампы смотреть. Так сложно сказать.

**Comment by HanabishiRecca** [comment]
В дебаге должно что-то писаться? Как например wsize пишет "Window size change". При disorder/split видно что пакеты идут, даже весь трафик через них пускал чтоб наверняка, но никаких дополнительных надписей нет.

**Comment by bol-van** [comment]
надписи должны быть при --debug. если их нет, значит nfqws не получает те пакеты, над которыми он должен поработать
```
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding this socket to queue '200'
setting copy_packet mode
Running as UID=1 GID=1
packet: id=1 len=40
packet: id=2 len=110
packet contains HTTP request
hostname: www.ru
dpi desync src=192.168.1.2:64524 dst=217.112.35.73:80
reinjecting original packet. len=110 len_payload=70
```

**Comment by bol-van** [comment]
может быть ошибка в iptables ? например, завертывается входящий трафик вместо исходящего. не ?

**Comment by HanabishiRecca** [comment]
Ну с ридми брал. И я в курсе про отличие с wize.
Пробовал даже вообще весь трафик заворачивать на него
`iptables -t mangle -I POSTROUTING -p tcp --dport 443 -j NFQUEUE --queue-num 200 --queue-bypass`
Видно что при попытке зайти на сайт пакеты проходят, но обработки не происходит.

**Comment by bol-van** [comment]
что за девайс ? не какой-то заводской роутер ? в них часто оффлоад присутствует

проверяю на системе, где точно нет оффлоадов
с клиента curl https://lenta.com

```
iptables -t mangle -I POSTROUTING -p tcp --dport 443 -j NFQUEUE --queue-num 200 --queue-bypass
/opt/zapret/nfq/nfqws --qnum=200 --dpi-desync=split2 --debug
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding this socket to queue '200'
setting copy_packet mode
Running as UID=0 GID=0
packet: id=1 len=52
packet: id=2 len=40
packet: id=3 len=557
packet contains TLS ClientHello
hostname: lenta.com
dpi desync src=192.168.4.2:60799 dst=82.202.190.33:443
sending 1st tcp segment 0-2 len=3
sending 2nd tcp segment 3-516 len=514
packet: id=4 len=43
packet: id=5 len=554
packet: id=6 len=40
packet: id=7 len=133
packet: id=8 len=142
packet: id=9 len=40
packet: id=10 len=40
packet: id=11 len=40
packet: id=12 len=40
packet: id=13 len=40
packet: id=14 len=40
packet: id=15 len=40
packet: id=16 len=40
packet: id=17 len=40
packet: id=18 len=71
packet: id=19 len=40
packet: id=20 len=40
packet: id=21 len=68

```

**Comment by HanabishiRecca** [comment]
Разобрался в общем. Мой косяк был в том, что
1) Браузер кэширует соединение и при обновление странички не создает новую TLS сессию. Надо новое окно открывать.
2) Оффлоад все же мешает, да.
Через split2 провайдер все же не обманулся, а вот с disorder2 дело пошло.

**Comment by HanabishiRecca** [comment]
Хотя я нашел хитрый способ обойти 2 проблему. Задаю оффлоад вот таким образом:
`iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 5: -j FLOWOFFLOAD --hw`
То есть он начинает оффлоад только после 5 пакета в соединении, что позволяет отработать nfqws.

**Comment by bol-van** [comment]
Понятно. Но все же что за девайс и какая ос ?

**Comment by HanabishiRecca** [comment]
RT-AC57U на OpenWRT

**Comment by bol-van** [comment]
В openwrt offload можно отключить полностью, а частично - да, только через собственный огород с iptables. fw3 по другому не умеет

**Comment by HanabishiRecca** [comment]
Нет, инсталлятором не пользовался. Встроенный фаервол выпилен, весь конфиг у меня кастомный.
