### ISSUE TITLE
Что делать пользователям MacOs

### ISSUE THREAD

**Issue by hudeuschiy** [bol-van/zapret#481]
Подскажите, пожалуйста, пошагово, как использовать продукт обычному не разбирающемуся в кодировании пользователю MacOs. Единственное, что нужно - доступ к Дискорду

**Comment by kbrddestroyer** [comment]
Терминал MacOS поддерживает команды Linux, так что скрипты должны работать так же. Проблемы могут возникнуть с доступом, так как MacOS более закрытая система. Тем не менее попробуй выполнить quickstart гайд для Linux, должно сработать.

**Comment by hudeuschiy** [comment]
Можно ссылку для неопытного пользователя? :)

**Comment by 00enterausername00** [comment]
Попробуй spoofdpi - там парой команд все делается и даже есть приложение для запуска мышкой. Zapret больше для роутеров, чтобы вылечить всю сеть, а не один комп.

**Comment by bol-van** [comment]
На macos zapret работает только с tpws.
Ограниченная поддержка.

**Comment by EugeneYakovenko** [comment]
На сегодня у меня на Mac работает для Ютуба, рутрекера и флибусты следующий вариант  privoxy + tpws:
**privoxy** 
    listen-address  127.0.0.1:3128
    forward-socks5 .googlevideo*. 127.0.0.1:1010 .
    forward-socks5 .youtu*. 127.0.0.1:1010 .
    forward-socks5 .ytimg. 127.0.0.1:1010 .
    forward-socks5 .ggpht. 127.0.0.1:1010 .
    forward-socks5 .discord. 127.0.0.1:1010 .
    forward-socks5 .flibusta. 127.0.0.1:1010 .
    forward-socks5 .rutracker. 127.0.0.1:1010 .
 **tpws**
    . /tpws --bind-addr=127.0.0.1 --port 1010 --socks --split-tls=sni --split-tls=sniext --oob 2

**Comment by kotudemo** [comment]
> На macos zapret работает только с tpws. Ограниченная поддержка. Дискород он не вылечит, так что мимо

 мб знаешь какие-нибудь альтернативы для дискорда тогда, или тут только впн покупать в Европе?

**Comment by kotudemo** [comment]
https://github.com/by-sonic/unblock-pro
вчера вообще вот эту штуку выложили, но хз насколько она работает и насколько она безопасна вообще

**Comment by kotudemo** [comment]
> https://github.com/by-sonic/unblock-pro вчера вообще вот эту штуку выложили, но хз насколько она работает и насколько она безопасна вообще

ну оно по крайней мере работает, в том чилсе и войсы в дискорде чинит

**Comment by proxylot** [comment]
https://github.com/proxylot/zapret-macos?tab=readme-ov-file#%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-zapret-%D0%BD%D0%B0-macos - гайд по запуску запрета на макос
