### ISSUE TITLE
Не работает Ru домен по типу avito.ru dns.ru ozon.ru

### ISSUE THREAD

**Issue by amigo4562** [bol-van/zapret#483]

**Comment by amigo4562** [comment]
у меня вообще все что имеет .Ru не открывается

**Comment by bol-van** [comment]
Никакой инфы, как будто что-то нажали и оно НЕ
это НЕ однокнопочное решение
требуется настройка и поиск стратегии

**Comment by amigo4562** [comment]
Ну понятно что это не однокнопочное решение, я спросил ради того что бы узнать есть ли у кого то решение на мой вопрос
