### ISSUE TITLE
Проверка Маршрута в Дискорде на Линуксе

### ISSUE THREAD

**Issue by Aspirata** [bol-van/zapret#486]
После изменения некоторых вещей в конфигах, у меня стал чуть дальше грузится войс дс, чем было с ByeDPI, и юбуб работает отлично, но теперь войс дс зависает на проверке маршрута. Может кто-то знает решение ?

P.S Провайдер у меня Электронный Город

Вот [мой конфиг](https://pastebin.com/6bZXkmvp) и [zapret-hosts-user.txt](https://pastebin.com/RddqHygU)

**Comment by inkcmd** [comment]
закомментированный оверрайд quic портов? так то хз, я не знаю, должны ли они быть закомментированы
есть отдельный кастом для дискорда, в обсуждениях висит от bol-van, был где то еще какой то

**Comment by inkcmd** [comment]
https://github.com/bol-van/zapret/discussions/475
сделай как здесь и заработает

**Comment by Aspirata** [comment]
Всё работает из коробки с новым коммитом
