### ISSUE TITLE
uninstall_easy полностью не удаляет zapret

### ISSUE THREAD

**Issue by nikofon** [bol-van/zapret#488]
После того как скрипт "удаляет" запрет все еще каким то образом есть доступ к сайтам, к которым доступа быть не должно, хотя запретовский рулсет отсутствует в nftables. Как такое возможно?

**Comment by bol-van** [comment]
Другие способы обхода блокировок или ECH
Без рулесета и без демонов запрета нет

**Comment by truechupa** [comment]
Я осмелюсь предположить, что может быть дело в шифровании dns?

**Comment by ThinkFresh75** [comment]
Такая же проблема. Удалось победить?

**Comment by bol-van** [comment]
В uninstall внесено опциональное удаление доп пакетов.
Инструкция по удалению есть в quick-start
Без nfqws/tpws запрет не может иметь место
Думаю вопрос этот закрыт
