### ISSUE TITLE
Не удается найти файл winws.exe

### ISSUE THREAD

**Issue by lilsreda** [bol-van/zapret#489]
При запуске start_now.cmd открывается ошибка -- Не удается найти файл winws.exe --
![image](https://github.com/user-attachments/assets/795ef3e3-e4c5-43a2-b197-a8c5f4c48e5e)

**Comment by MrProstos** [comment]
Архив распаковал ?

**Comment by bol-van** [comment]
Учитесь пользоваться командной строкой
Вы находитесь в другой директории
Как и обещал, такие иссуес закрываю сразу
