### ISSUE TITLE
SC StartService FAILED 5 Acces is denied

### ISSUE THREAD

**Issue by midas888-star** [bol-van/zapret#490]
![Снимок экрана 2024-10-11 214635](https://github.com/user-attachments/assets/e0cc7ab6-cc7f-438a-b922-22a1bb9c5b51)

что делать? запускать другие батники пробовал, проблема аналогичная, порты менять пробовал

**Comment by bol-van** [comment]
Антивирус ?

**Comment by midas888-star** [comment]
> Антивирус ?

выключен. других антивирусов нету

**Comment by ltrinch** [comment]
У тебя в консоли написано, что нужно запускать от имени администратора. Если всё ещё будет ошибка - дай знать какая.

**Comment by bol-van** [comment]
У него sc create service SUCCESS. Не под админом такое бы не сделалось.
Проблема может быть с чтением файла с диска под аккаунтом SYSTEM.
Это может быть, например, если прога находится на сетевом диске или каком-то специфическом диске, доступным только под текущей юзер сессией.

**Comment by ltrinch** [comment]
> У него sc create service SUCCESS. Не под админом такое бы не сделалось. Проблема может быть с чтением файла с диска под аккаунтом SYSTEM. Это может быть, например, если прога находится на сетевом диске или каком-то специфическом диске, доступным только под текущей юзер сессией. Или поставлены NTFS права, запрещающие доступ SYSTEM и администраторс.

Да, ты прав, недоглядел этот момент, извиняюсь. В таком случае, ждём пока автор даст обратный ответ по этому поводу.
