### ISSUE TITLE
Программа пишет что не может найти nslookup или  host

### ISSUE THREAD

**Issue by ExcellentProof** [bol-van/zapret#497]
устанавливал по инструкции, на 6 шаге когда надо запуститю blockcheck.sh при запуске пишет это :

* checking system
Linux detected
firewall type is iptables
* checking already running zapret processes
* checking privileges
root is required
* checking system
Linux detected
firewall type is iptables
* checking already running zapret processes
* checking privileges
* checking prerequisites
nslookup or host does not exist. please install

press enter to continue

когда нажимаю enter ничего не происходит пытался найти пакеты nslookup и host, найти не смог.

**Comment by jacobcodev** [comment]
cvde

**Comment by ExcellentProof** [comment]
на арче надо установть пакет dnsutils
