### ISSUE TITLE
Asus AC68U Can`t Install

### ISSUE THREAD

**Issue by Aaldaff** [bol-van/zapret#51]
How i can fix this ? 
#install_bin.sh
root@OpenWrt:/opt# /opt/zapret/install_bin.sh
x86_64 is NOT OK
x86 is NOT OK
aarch64 is NOT OK
Illegal instruction
armhf is NOT OK
mips64r2-msb is NOT OK
mips32r1-lsb is NOT OK
mips32r1-msb is NOT OK
ppc is NOT OK

install_easy.sh
root@OpenWrt:/opt# /opt/zapret/install_easy.sh
* checking system
system is based on openwrt
* checking executables
Illegal instruction
build tools not found

press enter to continue

_root@OpenWrt:/opt# cat /proc/cpuinfo_
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1987.37
Features        : half thumb fastmult edsp tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0
processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1993.93
Features        : half thumb fastmult edsp tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0
Hardware        : BCM5301X
Revision        : 0000
Serial          : 0000000000000000

root@OpenWrt:/opt# cat /etc/board.json
{
        "model": {
                "id": "asus,rt-ac68u",
                "name": "Asus RT-AC68U (BCM4708)"
        },
        "switch": {
                "switch0": {
                        "enable": true,
                        "reset": true,
                        "ports": [
                                {
                                        "num": 1,
                                        "role": "lan"
                                },
                                {
                                        "num": 2,
                                        "role": "lan"
                                },
                                {
                                        "num": 3,
                                        "role": "lan"
                                },
                                {
                                        "num": 4,
                                        "role": "lan"
                                },
                                {
                                        "num": 0,
                                        "role": "wan"
                                },
                                {
                                        "num": 5,
                                        "device": "eth0",
                                        "need_tag": true
                                }
                        ],
                        "roles": [
                                {
                                        "role": "lan",
                                        "ports": "1 2 3 4 5t",
                                        "device": "eth0.1"
                                },
                                {
                                        "role": "wan",
                                        "ports": "0 5t",
                                        "device": "eth0.2"
                                }
                        ]
                }
        },
        "network": {
                "lan": {
                        "ifname": "eth0.1",
                        "protocol": "static"
                },
                "wan": {
                        "ifname": "eth0.2",
                        "protocol": "dhcp"
                }
        }
}

**Comment by bol-van** [comment]
I used to compile arm with VFP (hard float).
Now moved to cortex-A9 target with soft float. Should work, please test

**Comment by Aaldaff** [comment]
Thanks for fast repaly, im noob with this, but thank for help, this my rule for instalation
opkg update
opkg install iptables-mod-extra iptables-mod-nfqueue iptables-mod-filter iptables-mod-ipopt iptables-mod-conntrack-extra ipset curl
opkg install ip6tables-mod-nat
opkg install gzip
opkg install grep

opkg update
opkg install git-http
mkdir /opt
cd /opt
git clone --depth 1 https://github.com/bol-van/zapret
/opt/zapret/install_bin.sh

root@OpenWrt:/opt#
root@OpenWrt:/opt# /opt/zapret/install_bin.sh
x86_64 is NOT OK
x86 is NOT OK
aarch64 is NOT OK
arm is OK
installing binaries ...
linking : ../binaries/arm/ip2net => /opt/zapret/ip2net
linking : ../binaries/arm/mdig => /opt/zapret/mdig
linking : ../binaries/arm/nfqws => /opt/zapret/nfq
linking : ../binaries/arm/tpws => /opt/zapret/tpws

After that what i do ?

**Comment by bol-van** [comment]
See docs/readme.eng.txt
I'm not going to retell its content.
I can only help with a specific problem
