### ISSUE TITLE
tpws при отсутствии сетевой активности флудит в консоль "epoll_wait"

### ISSUE THREAD

**Issue by Baltazar500** [bol-van/zapret#52]
Доброго времени суток.

Тулза tpws при отсутствии сетевой активности начинает флудить в консоль "epoll_wait". Если выводить выхлоп в файл для логгирования событий, то он в свою очередь он замусориватся данными строками при неактивности. С этим можно что-то сделать ?

**Comment by bol-van** [comment]
При включенном debug и отсутствии активности должно вывести 1 раз epoll_wait и на этом остановиться. 
Если оно лезет все время, значит активность есть. Например, она может быть вызвана рекурсивным заворотом соединений на tpws от самого tpws при соединениях с самого хоста, где работает tpws.
Нужны последние ~50 строк из вывода tpws при --debug=2
и netstat -nt | grep :<порт_tpws>

**Comment by Baltazar500** [comment]
>Если оно лезет все время, значит активность есть. Например, она может быть вызвана рекурсивным заворотом соединений на tpws от самого tpws при соединениях с самого хоста, где работает tpws.

Активности нет, равно как и заворота. Ни одного запроса даже не было. Тем не менее, я выяснил в чём проблема - epoll_wait валится, как только выключается экран и смарт на андроиде переводится в "спящий" (энергосберегающий) режим.  Если это дело отключить

>echo y > /sys/power/wake_lock

то epoll_wait перестаёт сыпаться в консоль/лог. Если бы эта придурь (wakelock) не мешала работать по ssh и не вызывала лаги, то я бы о ней даже не знал. А так, когда началась такая котовасия с tpws, сразу же закрались подозрения, не она ли виновата во всём. Так в итоге и оказалось. 

Проблема только в том, что режим с wakelock'ом дефолтный и включен по крайней мере на том конкретном смарте просто так - без него враз высаживается батарея в фоне.

>Нужны последние ~50 строк из вывода tpws при --debug=2

Если всё же нужно

>set_socket_buffers fd=7 rcvbuf=0 sndbuf=0
>fd=7 SO_RCVBUF=1048576
>fd=7 SO_SNDBUF=524288
>set_ulimit : fdmax=3088 fdmin_system=7184
>set_ulimit : current system file-max=99443
>Running as UID=1 GID=3003
>Will listen to port 32000
>socks mode
>epoll_wait

>и netstat -nt | grep :<порт_tpws>

Там пусто :/

**Comment by bol-van** [comment]
Я просил лог в проблемном состоянии. В рабочем и сам могу получить
У меня есть android 5 и 7 оба на MTK. На обоих девайсах не воспроизводится

**Comment by Baltazar500** [comment]
>Я просил лог в проблемном состоянии

Это он есть. В дефолтном состоянии, в активном режиме wakelock'a (вручную назад врубается аналогично)

>echo y > /sys/power/wake_unlock

стоит только затушить экран, сразу же пачками валятся строки "epoll_wait" в консоль эмулятора терминала. Как только экран будится, или отключается wakelock

>echo y > /sys/power/wake_lock

строки в консоли/логе перестают множиться.

**Comment by bol-van** [comment]
Мне интересно было увидеть кучу этих epoll_wait. Нет ли каких-то записей между ними

**Comment by Baltazar500** [comment]
>Мне интересно было увидеть кучу этих epoll_wait. Нет ли каких-то записей между ними
Нет там ничего кроме "epoll_wait" частоколом (с каждой новой строки). За ночь тогда в лог-файл нащёлкало ~ 16К строк "epoll_wait". Сплошняком. Только их.

**Comment by bol-van** [comment]
Судя по коду это может быть только в случае, когда epoll_wait возвращается с ошибкой EINTR. Что-то регулярно прерывает вызов. Какие-то хаки андроида

мне бы вывод
strace -r tpws --debug=2 --socks --port=4444 --uid=1:3003
в проблемном режиме

если нет бинарика strace, можно взять тут : https://github.com/bol-van/bins

**Comment by bol-van** [comment]
Возможно, что-то изменит запуск с UID приложения, "не экономящего заряд"
В настройках такие выбираются

**Comment by Baltazar500** [comment]
>если нет бинарика strace, можно взять тут : https://github.com/bol-van/bins
Есть. Из entware :)

>мне бы вывод
>strace -r tpws --debug=2 --socks --port=4444 --uid=1:3003
>в проблемном режиме

Вот кусок от строк getuid32/getgid32 до первого "epoll_wait" https://pastebin.com/UCGFSfUT, а вот то,  что начало сыпаться в консоль сразу, как экран потух https://pastebin.com/hc3XEf8c

Причём такое поведение не только в ConnectBot'e, но и по ssh (который при гашении экрана лагает). Выхлоп выложил на pastebin, дабы снова не воевать со вставкой логов на github.

>в принципе это не страшно, если делается не слишком часто. 16к за ночь - не так много, раз в неск секунд. для загрузки cpu это ничто. а лог можно не писать. не включать debug

Да похоже так и поступлю, просто до этого подобных заморочек не было с tpws )))

>Возможно, что-то изменит запуск с UID приложения, "не экономящего заряд"

Попробовал UID Viber'a и AquaMail (10143:3003 /  10093:3003) - они в фоне обычно проверяют почту. Бесполезно.

>В настройках такие выбираются

Смарт с данной петрушкой на 4.2.2 (Jelly Bean). Там я такого не припомню

**Comment by bol-van** [comment]
Да, все как и предположил. EINTR
Вызвано наверняка сигналами SIGSTOP/SIGCONT.
При попытке делать kill с этими сигналами epoll_wait выходит с EINTR
Это андроид пытается дозировать экзекуцию процессе
