### ISSUE TITLE
"TLS 1.3 hybridized Kyber support" causes huge CPU spike

### ISSUE THREAD

**Issue by ODAKAB** [bol-van/zapret#522]
I use zapret on my Keenetic Carrier DSL (Keenetic-2111)

Testing on facebook.com, isn't on my list and it isn't censored, Brave browser.
**Idle:** CPU usage is around **4%**
**TLS 1.3 support disabled:** CPU usage is around **15%** until page fully loads, everything is smooth.
**TLS 1.3 support enabled:** CPU usage spikes up to **100%**, rest of the page doesn't load or load very slowly because of that and if I keep trying few more times, device eventually reboots itself due to heavy load.

zapret settings related to filter and strategy
```
MODE=nfqws
MODE_HTTP=1
MODE_HTTP_KEEPALIVE=0
MODE_HTTPS=1
MODE_QUIC=0
MODE_FILTER=hostlist
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-ttl=2"
```

Is it expected for TLS 1.3 to cause this huge load on zapret or is it a bug?
Is there a way to reduce the load or just skip checking for TLS 1.3?

**Comment by bol-van** [comment]
No, it doesnt look normal.
I cant tell you anything without recorded --debug log

**Comment by ODAKAB** [comment]
It was very consistent and easy to reproduce, but now I can't reproduce it. Reboots still happen 1 or 2 times everyday without a visible trigger. I will reopen if I catch and log it.
