### ISSUE TITLE
(TAM VIDEOYU İZLE==)) IKBAL UZUNER GÖRÜNTÜLERI SANSÜRSÜZ TELEGRAM IKBAL UZUNER OLAYI TELEGRAM.

### ISSUE THREAD

**Issue by ylannadteent** [bol-van/zapret#527]
(TAM VIDEOYU İZLE==)) IKBAL UZUNER GÖRÜNTÜLERI SANSÜRSÜZ TELEGRAM IKBAL UZUNER OLAYI TELEGRAM.
semih çelik semih çelik ikbal semih çelik video semih çelik ikbal uzuner video twitter ikbal ayşenur halil ayşenur halil video semih celik semih çelik video twitter semih çelik twitter telegram ikbal uzuner ikbal uzuner görüntüleri ikbal cesedi ikbal uzuner cesedi twitter ikbal uzuner ikbal uzuner twitter ikbal uzuner sansürsüz ikbal sansürsüz

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://anyplacecoming.com/zq5yqv0i?key=0256cc3e9f81675f46e803a0abffb9bf)

[🔴 ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://anyplacecoming.com/zq5yqv0i?key=0256cc3e9f81675f46e803a0abffb9bf)

[Watch 🟢 ➤ ➤ ➤ 🌐 Click Here To link (Full Viral Video Link)](https://anyplacecoming.com/zq5yqv0i?key=0256cc3e9f81675f46e803a0abffb9bf)

🔴[ ➤►DOWNLOAD👉👉 (Full Viral Video Link)](https://jamunatvbd.com/leakedvideo.html?Ms2)

İkbal Uzuner ve Ayşenur Halil'in öldürülmesi üniversitelerde protesto edildi
protestoKaynak,X@IstanbulEmek
5 Ekim 2024
Güncelleme 3 saat önce
İstanbul'da İkbal Uzuner ile Ayşenur Halil'in vahşice öldürülmesi üzerine kadınların şiddete karşı eylemleri devam ediyor.

Hafta sonu çeşitli kentlerde gerçekleştirilen basın açıklamaları ve gösterilerin ardından pazartesi günü de kadınlar eğitim kurumlarında ve sokaklarda tepkilerini dile getirdi.

İstanbul Üniversitesi, Boğaziçi, Yıldız Teknik ve Medipol Üniversitesi gibi birçok üniversitede öğrenciler kadın cinayetlerini protesto etti.

Ayşenur Halil'in eğitim gördüğü Medipol Üniversitesi'nde de öğrenciler Halil ve İkbal Uzuner için gösteri yaptı; üniversitedeki anmaya akademisyenler ve idari personel de katıldı.

Öğrenciler, "Sesini duyuramamış tüm kadınlar için buradayız", "Yaşamak istiyoruz", "Öfkeni diri, başını dik tut", "Sen, ben, biz, birbirimizin çaresiyiz", "Kadına değil, şiddet son", "Korkuya teslim olmayacağız" ve "Kadına ve çocuğa dokunma" yazılı pankartlar taşıdı.

**Comment by mckenkenedy** [comment]
FG

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/4f9ea6a5-72ed-4513-ad03-3257e480596f" alt="" /></a>

vf

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/b0c0ec09-34cf-4490-9160-a6d5927622f4" alt="" /></a>


FG

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/4f9ea6a5-72ed-4513-ad03-3257e480596f" alt="" /></a>

vf

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/b0c0ec09-34cf-4490-9160-a6d5927622f4" alt="" /></a>


FG

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/4f9ea6a5-72ed-4513-ad03-3257e480596f" alt="" /></a>

vf

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/b0c0ec09-34cf-4490-9160-a6d5927622f4" alt="" /></a>


xcvxvcxcvcx

**Comment by mckenkenedy** [comment]
fddfgdfg

FG

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/4f9ea6a5-72ed-4513-ad03-3257e480596f" alt="" /></a>

vf

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/b0c0ec09-34cf-4490-9160-a6d5927622f4" alt="" /></a>


FG

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/4f9ea6a5-72ed-4513-ad03-3257e480596f" alt="" /></a>

vf

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/b0c0ec09-34cf-4490-9160-a6d5927622f4" alt="" /></a>


FG

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/4f9ea6a5-72ed-4513-ad03-3257e480596f" alt="" /></a>

vf

<a href="https://bit.ly/bestleakvideo"><img src="https://github.com/user-attachments/assets/b0c0ec09-34cf-4490-9160-a6d5927622f4" alt="" /></a>
