### ISSUE TITLE
netflix working on desktop but not on smartphone

### ISSUE THREAD

**Issue by sidull** [bol-van/zapret#54]
my isp blocking netflix in my region, so i think this is the only option for me to open netflix in smart tv. i using tpws all https + dns over tls installed to my openwrt router. everything going well in desktop, i can watch the movie. but when i connect to router using ios, android and smart tv, the video not playing. i only can explore the menu and the image load very well. 
There are something that i should configure?
Thanks.

**Comment by sidull** [comment]
.

**Comment by bol-van** [comment]
You should understand how this technically works and use network monitoring tools. Its not magic pill.
giving support for specific ISPs is out of my scope
