### ISSUE TITLE
Plasma desktop crasing 

### ISSUE THREAD

**Issue by BurhanDanger** [bol-van/zapret#55]
Clean Manjaro-plasma install. (Nothing modified, packages updated only)

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel: 5.6.15-1-MANJARO x86_64 
CPU: Quad Core Intel Core i5-8300H
Memory: 7.6 GiB of RAM
GPU: Mesa Intel(R) UHD Graphics 630, GP107M [GeForce GTX 1050 Ti Mobile]

Example: 

Before: ![vlcsnap-2020-06-04-14h48m58s345](https://user-images.githubusercontent.com/25033866/83735753-9684f580-a672-11ea-9f7d-8e5e39d2c861.png)

After: ![vlcsnap-2020-06-04-14h48m14s068](https://user-images.githubusercontent.com/25033866/83735740-94229b80-a672-11ea-8ba9-7dd28de31b6e.png)

[![Video_example](https://user-images.githubusercontent.com/25033866/83736718-dac4c580-a673-11ea-99f6-ef0ecaa67c58.png)](https://streamable.com/s6myot)

Aftermath: 
All the windows miss the borders. Device becomes unresponsive. Even moving tty seems to be laggy. Using ./uninstall_easy seems to fix the issue. 

I tried with i3-wm on the same machine. Works fine.

**Comment by PHPoenX** [comment]
Same problem with openSUSE Tumbleweed

Qt version 5.14.1
Kernel 5.6.14
x86_64

After rebooting problem doesn`t disappear

**Comment by bol-van** [comment]
This software has no relation to UI. I will test however when i have time

**Comment by Iltsov** [comment]
Значит это не я что-то неправильно делаю. У меня та же самая проблема.
Могу только добавить, что это происходит с tpws, с nfqws всё ок

Operating System: Fedora 32
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.13.2
Kernel Version: 5.6.16-300.fc32.x86_64
OS Type: 64-bit
Processors: 4 × AMD Phenom(tm) II X4 955 Processor
Memory: 7,8 ГиБ

**Comment by bol-van** [comment]
Чтобы ускорить процесс найдите лив образ который под виртуалкой воспроизводит проблему

**Comment by bol-van** [comment]
Indeed it had no relation to UI. It was because of treating max open files as 32-bit value instead of correct 64-bit rlim_t
Recent kernels have default max-file 0x7FFFFFFFFFFFFFFF

fixed
