### ISSUE TITLE
Добавляйте программу в исключения Касперского и MalwareBytes!

### ISSUE THREAD

**Issue by kapustok** [bol-van/zapret#550]
WinDivert64 - обнаружение от Касперского. 
После обновления вирусных баз вчера в обычным состоянии видит программу как heur:.Multi.Misslink.a (not-a-virus) 
В случае работы программы после запуска .bat видит ее как heur:Trojan.Multi.Misslink и удаляет без возможности сохранения и выдает кучу ошибок. 
В целом отправлял файл в Eset анализ прислали что все чисто даже данный драйвер. Но только Касперский на него с ума сходит. Отправьте* им письмо чтобы успокоились
![camphoto_1932422408](https://github.com/user-attachments/assets/cfed5e3c-5886-4b4a-b1b3-27685e0a516d)
![IMG_2541](https://github.com/user-attachments/assets/95579dfe-6137-4847-a268-cceb1cbe5100)
![IMG_2542](https://github.com/user-attachments/assets/74841885-a9fd-494f-955d-cbe1839b1547)

Так или иначе, спасибо за прогу, удобная.

**Comment by bol-van** [comment]
Антивирусы обычно жалуются на upx.
windivert они более-менее научились не трогать, но видимо пошли рецидивы.
Еще возможны жалобы на cygwin

**Comment by kapustok** [comment]
> Антивирусы обычно жалуются на upx. windivert они более-менее научились не трогать, но видимо пошли рецидивы. Еще возможны жалобы на cygwin
это понятно. Просто не хочется чтобы человек сидел 30 минут ждал лечение из за срабатывания
