### ISSUE TITLE
Yotube загружается но не грузяться видео

### ISSUE THREAD

**Issue by TheDifferentGuy** [bol-van/zapret#558]
У меня в настройках стоит NFQWS_OPT_DESYNC="--dpi-desync=fake --dpi-desync-ttl=7", сам youtube грузиться, но видосы не прогружаються. Подскажите пожалуйста, какую настройку поставить, чтобы видосы начали грузиться.

**Comment by electrifying** [comment]
--dpi-desync-repeats и фейк tls гугла

**Comment by LEECH161** [comment]
> --dpi-desync-repeats и фейк tls гугла
А полностью строка (NFQWS_OPT_DESYNC=) как выглядит?

**Comment by RendeR66** [comment]
`NFQWS_OPT_DESYNC="-dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"`

`NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-ttl=0 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"`

файл конфиг поменяй должно заработать, но есть побочки, аватарки в кс не грузятся, но зато можно по гос услугам лазить

**Comment by Kerosin3** [comment]
> `NFQWS_OPT_DESYNC="-dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"`
> 
> `NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-ttl=0 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"`
> 
> файл конфиг поменяй должно заработать, но есть побочки, аватарки в кс не грузятся, но зато можно по гос услугам лазить
> 
> думаю ты догодаешься что в место чего подставлять

У меня такая настройка стоит и всё равно вечная загрузка

**Comment by RendeR66** [comment]
> > `NFQWS_OPT_DESYNC="-dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"`
> > 
> > `NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-ttl=0 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"`
> > 
> > файл конфиг поменяй должно заработать, но есть побочки, аватарки в кс не грузятся, но зато можно по гос услугам лазить
> > 
> > думаю ты догодаешься что в место чего подставлять
> 
> У меня такая настройка (исправленная) стоит и всё равно вечная загрузка

У меня медленно но грузит, главная цель что грузит выполнено. Может у тебя не в конфиге дело? Или ты как-то не так установил, на какой ты ос это делаешь?

**Comment by TheDifferentGuy** [comment]
Не хочу огорчать, но у меня на ростелекоме этот конфиг не пашет. Только сам ютуб грузит, а видосы нет.

**Comment by limpopo34** [comment]
Не знаю как у вас, а у меня после этих батников запрета теперь всё грузит без включения батников, но почему-то в хроме всё плохо, а в яндекс и майкрософт эдж ютуб хорошо грузит. Может вам поможет сменить браузер? Я пока ищу способы оживить ютуб на хроме, ведь это мой основной браузер для всего.

**Comment by maksimn** [comment]
Та же проблема – сайт работает, но видео не грузятся. Есть ли у кого-нибудь аналогичный конфиг для TPWS режима?

**Comment by limpopo34** [comment]
У меня видосы начали грузиться когда в браузере включил QUIC protocol и Kyber, наверное это было где-то в инструкции =)

**Comment by ghotam1331** [comment]
> У меня видосы начали грузиться когда в браузере включил QUIC protocol и Kyber, наверное это было где-то в инструкции =)
Спасибо, бро, мне помогло )

**Comment by Kirihi147** [comment]
> У меня видосы начали грузиться когда в браузере включил QUIC protocol и Kyber, наверное это было где-то в инструкции =)
Тоже пользуюсь firefox, и сталкиваюсь с некоторыми проблемами. Отключение quic не особо помогает, ещё и максимум буфера режет, но это не точно. Также, изменение конфига не помогает - именно с данной проблемой. Включил протокол kyber, и вроде соединение стало стабильнее, то есть пропали скачки скорости соединения в статистике ютуба. В том числе начальный затуп скорости по 200-1000 Кб/c.
Буду ещё проверять, но появляется спад скорости внезапно, так что, возможно, встречу ещё не скоро. Спасибо за совет!

**Comment by Kerosin3** [comment]
> У меня видосы начали грузиться когда в браузере включил QUIC protocol и Kyber, наверное это было где-то в инструкции =)

помогло

**Comment by Kirihi147** [comment]
> Тоже пользуюсь firefox, и сталкиваюсь с некоторыми проблемами. Отключение quic не особо помогает, ещё и максимум буфера режет, но это не точно. Также, изменение конфига не помогает - именно с данной проблемой. Включил протокол kyber, и вроде соединение стало стабильнее, то есть пропали скачки скорости соединения в статистике ютуба. В том числе начальный затуп скорости по 200-1000 Кб/c. Буду ещё проверять, но появляется спад скорости внезапно, так что, возможно, встречу ещё не скоро. Спасибо за совет!

К сожалению не помогло, так же сталкиваюсь с падениями скорости соединения. Временно помогает перезагрузка страницы, больше решений пока не нашёл.

**Comment by andmt1** [comment]
> Та же проблема – сайт работает, но видео не грузятся. Есть ли у кого-нибудь аналогичный конфиг для TPWS режима?
поменяйте режим на nfqws. Видео грузит по QUIC протоколу, tpws не работает с quic
