### ISSUE TITLE
Please make it compatible with AsusWRT-Merlin

### ISSUE THREAD

**Issue by asaddon** [bol-van/zapret#57]
Any chance you can make it compatible with Asus routers running AsusWRT-Merlin?
https://www.asuswrt-merlin.net

Thankyou!

**Comment by bol-van** [comment]
Binaries are universal. Do you have trouble running them?
Easy to use support - no chance

**Comment by asaddon** [comment]
The setup instructions and scripts are made for Linux and OpenWRT, I just need a script file to install it on AsusWRT. I know how to copy the appropriate binaries in the opt folders but the init.d file is for openwrt.

**Comment by bol-van** [comment]
Sorry, no scripts, only manual approach. I will not easy support each firmware.

**Comment by asaddon** [comment]
Alright no issues, I'll go through the script's code to find out what its doing and try to make it work for my firmware.

**Comment by bol-van** [comment]
Its work for owner of specific devices. I dont have them.
Each firmware has its own logic. You need to figure out where to place tpws or nfqws and how to hook on autorun. Then it should not be too hard. Iptables+running daemon
Also check for races. Firmware can clear or modify iptables after your script. If so then add some delay or rerun script in background, detached from main execution, and there add some delay.
tpws should work on any router, nfqws require nfqueue kernel support

**Comment by asaddon** [comment]
Finally I've made it work, thankyou again for the pointers, i just have one feature request and I didn't feel like opening a new issue just for that so I'm writing it here.

Can you also add mix Host header case (test.com -> tEsT.cOm) function is tpsw like GoodByeDPI coder implemented.

**Comment by bol-van** [comment]
Does it help ?

**Comment by asaddon** [comment]
Yes it helped bypassing the DPI on some websites. I tried that option in GoodByeDPI.

**Comment by bol-van** [comment]
Done. pls check

**Comment by asaddon** [comment]
Thank you so much! 
It worked beautifuly.

**Comment by jixermo** [comment]
> Finally I've made it work, thankyou again for the pointers.

@asaddon Is it possible to share the changes you've made to make it work on AsusWRT? I'd be really grateful.

**Comment by asaddon** [comment]
> > Finally I've made it work, thankyou again for the pointers.
> 
> @asaddon Is it possible to share the changes you've made to make it work on AsusWRT? I'd be really grateful.

@jixermo First you need to setup AsusWRT Merlin on your router and enable scripts and jffs execution.
I'm attaching the modified scripts here, please go through it.
[zapret.zip](https://github.com/bol-van/zapret/files/13992631/zapret.zip)

**Comment by jixermo** [comment]
> > > Finally I've made it work, thankyou again for the pointers.
> > 
> > 
> > @asaddon Is it possible to share the changes you've made to make it work on AsusWRT? I'd be really grateful.
> 
> @jixermo First you need to setup AsusWRT Merlin on your router and enable scripts and jffs execution. I'm attaching the modified scripts here, please go through it. [zapret.zip](https://github.com/bol-van/zapret/files/13992631/zapret.zip)

Thanks for taking the time to respond. I can confirm I got it working, cheers!

**Comment by Argentum4k** [comment]
> Binaries are universal. Do you have trouble running them? Easy to use support - no chance

Привет, у меня старый (10 лет, но довольно мощный) роутер  на asusWRT, и ни один из бинарей не запускается: "no compatible binaries found". ( chmod делал) 
cat /proc/cpuinfo выдает
Processor       : ARMv7 Processor rev 0 (v7l)
Что не так, могу ли я собрать под свою архитектуру, если да то как? нашел старый тред 2022 года про сборку, но из него уже не активны ссылки.

**Comment by bol-van** [comment]
там может быть несовместимость кода инсталл_бин с кастрированной прошивкой
пробуйте руками из binaries/arm запускать

**Comment by Argentum4k** [comment]
пробовал, код скрипта работает правильно, понимает что бинари несовместимые, там родная оболочка ash, и при запуске ip2net как у вас и написано в коментах скрипта, просто висит, никакого вывода. при запуске  sh ./binaries/arm/ip2net
выдает  ./binaries/arm/ip2net: line 1: syntax error: unexpected word (expecting ")")
других интерпретаторов не завезли

**Comment by bol-van** [comment]
это не шелл скрипты, а  elf
в инсталл_бин используется find -exec, чтобы не дать шеллу интерпретировать их как текст
я просил запустить их как exe-шник, а не скрипт
если не работает надо распаковать upx

**Comment by bol-van** [comment]
а еще надо запускать
ip2net -h
он без параметров и должен висеть и ждать stdin

скорее всего финд от бизибокс был собран без -exec

**Comment by bol-van** [comment]
на таких прошивочках я рекомендую отказ от инсталятора

**Comment by Argentum4k** [comment]
ip2net -h сработало действительно! спасибо.

**Comment by bol-van** [comment]
можно, конечно, нагородить еще костылей
но может еще не чем-то отвалиться
а на другой прошивке - на другом
эти гонки за поддержкой сильно порезанных систем не имеют особого смысла
там надо брать nfqws/tpws и писать к ним иптаблес
самому

**Comment by asaddon** [comment]
> > > > Finally I've made it work, thankyou again for the pointers.
> 
> > > 
> 
> > > 
> 
> > > @asaddon Is it possible to share the changes you've made to make it work on AsusWRT? I'd be really grateful.
> 
> > 
> 
> > @jixermo First you need to setup AsusWRT Merlin on your router and enable scripts and jffs execution. I'm attaching the modified scripts here, please go through it. [zapret.zip](https://github.com/bol-van/zapret/files/13992631/zapret.zip)
> 
> 
> 
> I don't understand this topic, and I don't know how and what scripts to install from your ZIP file. Can you make detailed instructions for MerlinWRT?

Wait for it to be integrated in amtm, I think @thelonelycoder is working on it or plans to.
