### ISSUE TITLE
[Question] nfqws fooling methods.

### ISSUE THREAD

**Issue by asaddon** [bol-van/zapret#58]
Hello, 
Any specific reason or technical limitation that nfqws doesn't have these fooling methods which tpsw have?
--hostdot
--hosttab 
--hostpad=<bytes>
--methodspace
--methodeol
--unixeol

Also I've checked my router can run both NFQUEUE mode and Proxy Mode, what do you recommend, which one is better speed wise?

**Comment by bol-van** [comment]
nfqws works in packet mode, tpws works in stream mode
nfqws cannot extend or shrink packets inside TCP session, otherwise it would break TCP sequence

nfqws is faster especially if you can not to pass the whole tcp session to it and use limiters inside iptables

**Comment by asaddon** [comment]
So nfqws cannot have these fooling methods? Specially hostdot one.

**Comment by bol-van** [comment]
theoretically its possible to add dot but have to take one byte from something
for example, from user-agent.
but its not worth doing. twps works fine

**Comment by asaddon** [comment]
Okay if I am understanding the concept correctly isn't hostspace also  add extra bytes since technically space is also a character? Just curious about it, I totally understand that I can use Proxy mode and that works well too.

**Comment by asaddon** [comment]
I mean -hostnospace and you can ignore my previous comment, I didn't looked at the code but you're probably  adding the bytes in the function to balance it out.

**Comment by bol-van** [comment]
If you read help you will notice
remove space after Host: and add it to User-Agent: to preserve packet size

Adding anything means removing something from somewhere. This can negatively impact content. For example, taking one char from user-agent can break browser recognition on some websites.

**Comment by asaddon** [comment]
Understood completely understand. Thanks for your time once again, you can close this issue now.
