### ISSUE TITLE
Общая проблема, не работает обход DPI

### ISSUE THREAD

**Issue by cRayleigh** [bol-van/zapret#581]
Проблема возникла ещё с goodbyeDPI, на тот момент можно было обойтись и VPN'ом, а сейчас стоит вопрос пинга. Дело в том, что на одном провайдере именуемом себя как ККС, который проводят в Ставрополье, напрочь не работают методы обхода DPI, различные флаги и прочие танцы с бубном не особо помогли, и вот я здесь. Если кому-то не жаль потратить часть своего времени для помощи, буду очень признателен. Также хотел узнать про внутреннюю механику работы.

**Comment by electrifying** [comment]
запускайте блокчек в 5-6 прогонов и пробуйте стратегии предложенные оттуда

**Comment by cRayleigh** [comment]
> запускайте блокчек в 5-6 прогонов и пробуйте стратегии предложенные оттуда.Вместо рутрекера по умолчанию лучше использовать какой-либо другой сайт, так как рутрекер сейчас открывается без всего

Я наверное, зря не упомянул его, с него начинал. Всё, что он предложил не работало - после многих попыток прекратил его мучать. Пробовал ещё рандомную генерацию 16-тиричного кода - тоже мимо. Шифровал DNS, не уверен, что могло помочь, но было. Ещё можно было бы попробовать goodcheck, но я так понимаю исход будет как и с blockchek'ом.

**Comment by electrifying** [comment]
> Всё, что он предложил не работало

А сколько прогонов  делали, если один вполне могло быть так что сейчас попало и все прошло, а в другой раз уже нет. Поэтому стратегия и не сработала которую по итогу предложена была

**Comment by cRayleigh** [comment]
> А сколько прогонов делали, если один вполне могло быть так что сейчас попало и все прошло, а в другой раз уже нет. Поэтому стратегия и не сработала которую по итогу предложена была

Вероятно вы правы, и может я делаю что-то не так. Какой сайт для прогона могли бы посоветовать?

**Comment by electrifying** [comment]
> Какой сайт для прогона могли бы посоветовать?

Любой который точно заблокирован,например, pornolab.net или theins.ru.Возможно у вас откроются, можно просто проверить вбив адреса в браузер отключив все способы обхода и vpn, если выдаст заглушку провайдера или просто не загрузятся, значит заблокированы и можно пробовать один из них в блокчеке

**Comment by Kerrung** [comment]
> > Какой сайт для прогона могли бы посоветовать?
> 
> Любой который точно заблокирован,например, pornolab.net или theins.ru.Возможно у вас откроются, можно просто проверить вбив адреса в браузер отключив все способы обхода и vpn, если выдаст заглушку провайдера или просто не загрузятся, значит заблокированы и можно пробовать один из них в блокчеке

Вообще-то заглушку вы видеть не должны, а должны только сообщение самого браузера о неработающем сайте. Если вы её видите, то у вас не защифрован DNS, а если так, то Zapret работать и не должен. Первым делом вам необходимо защифровать DNS. Подробности в этом видео: https://www.youtube.com/watch?v=FdDC9R7gL-Y

**Comment by Kerrung** [comment]
@cRayleigh получилось ли у вас исправить вашу проблему?

**Comment by cRayleigh** [comment]
Да, всё заработало, ютуб в том числе.
