### ISSUE TITLE
После закрытия и полного удаления программы продолжает работать Youtube и Discord

### ISSUE THREAD

**Issue by NotFooound** [bol-van/zapret#584]
Запустил батник с таким содержанием 

> @echo off
> chcp 65001 >nul
> :: 65001 - UTF-8
> 
> cd /d "%~dp0"
> 
> set BIN=%~dp0bin\
> 
> start "zapret: discord" /min "%BIN%winws.exe" --wf-tcp=80,443 --wf-udp=443,50000-65535 ^
> --filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-udplen-increment=10 --dpi-desync-repeats=6 --dpi-desync-udplen-pattern=0xDEADBEEF --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
> --filter-udp=50000-65535 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
> --filter-tcp=80 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
> --filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

Сразу напишу, что хотел, чтобы всё включалось и выключалось при запуске батника, получилось, что работает всегда(даже с закрытым батником и приложением, и службой). Качал это решение у "AikenOZ", могу дать ссылку на решение. В этой же папке был service_remove, который не помог. Полностью переустановил винду с форматированием всех дисков, а также сбрасывал роутер, всё равно всё продолжает работает. Также скачал файлы "zapret-master". Запускал и "install_easy", и "uninstall_easy". По мимо этого файла скачивал и запускал другие "запреты", их тоже могу добавить. Никакие удаления служб и т.д. не помогли. Ничего не поменялось, всё продолжает работать. И как бы это странным не казалось, хотелось бы вернуть всё на свои места, потому что боюсь за утечку данных, потому что не знаю как это работает.
И очень важную вещь забыл сказать. На телефонах и прочих устройствах подключенных к сети всё работает, что на 5гг, что на 2.4

Система: 
Ос: win 11
Провайдер: ТТК (мб они просто всё починили, а я загнался)
Роутер: Xiaomi Mi WiFi Router Pro

Почему пишу сюда? Потому что персонаж "AikenOZ", ничего дельного не смог сказать, кроме того как "запусти service_remove из папки"

**Comment by bol-van** [comment]
`И очень важную вещь забыл сказать. На телефонах и прочих устройствах подключенных к сети всё работает, что на 5гг, что на 2.4`

Если на роутер и wifi устройства ничего не ставилось, значит блокировки нет

**Comment by NotFooound** [comment]
Просто до того как я включил zapret с пресетом выше, у меня ничего не работало

**Comment by limpopo34** [comment]
У меня тоже всё стало работать даже после перезагрузки пк. Но, почему-то в хроме ютуб плохо грузит видео, а в яндексе шикарно, да даже майкросовфт эдж грузит видосы хорошо, а хром почему-то не справляется.
Помимо возможности вернуть "как было" меня ещё интересует возможность починить хром для ютуба. Есть какие-то предложения?
