### ISSUE TITLE
offtopic: donate

### ISSUE THREAD

**Issue by lux01sv** [bol-van/zapret#590]
Привет. Прости за сотни людей, которые не могут прочитать readme.txt 😅
Я очень благодарен от лица всех, кто пользуется твоим комплексом обхода DPI решений. Спасибо тебе большое, от всего сердца. Я рад что на протяжении всего этого времени ты не забил на проект, и продолжаешь дополнять его разными идеями.

Работать за "спасибо" это конечно круто, но всё же: куда можно отправить донат на развитие проекта? Предпочтительно криптовалютой (по очевидным всем причинам 🙄), было бы классно если бы это был TON или USDT

**Comment by Sergey-nqwfs** [comment]
Да, было бы неплохо, а вы в readme.txt случайно не нашли реквизитов?

**Comment by bol-van** [comment]
USDT 0x3d52Ce15B7Be734c53fc9526ECbAB8267b63d66E
BTC bc1qhqew3mrvp47uk2vevt5sctp7p2x9m7m5kkchve

**Comment by IvanMineev** [comment]
Я не криптобоярин (хотя понимаю, что разработчики достойны всяческой материальной поддержки), поэтому оценил звездой и лайкнул все, что только можно) Здоровья, успехов и дальнейшего развития в IT.

**Comment by BrainDead88** [comment]
Здоровья и успехов разработчику! Он наш Ангел-спаситель!

**Comment by Sava349** [comment]
у меня проблема с программой. Я разорхивировал файл но там нет discord.bat

**Comment by KiRitosBanditos** [comment]
Уважаемые разработчики Zapret, будет ли возможно добавить soundcloud.com в запрет для обхода?

**Comment by h1bro32** [comment]
я вот скачал запрет версии 1.5.2 и 1.6.0 и мне виндовс дефендер жалуется на троян, из-за чего он может жаловаться на него?
