### ISSUE TITLE
почему на вин 10/11 скорость падает, а на других ос нет (через роутер)

### ISSUE THREAD

**Issue by Euphoreka7** [bol-van/zapret#593]
апдейт венды вынудил ее переустановить. после чего столкнулась с проблемой того что скорость скачивания низкая. причем применимо к хттпс. перепробовала кучу вариантов исправления этого на стороне венды - результатов не дало

есть роутер. на нем опен-врт. там запрет. к роутеру через вай-фай подключены мак-бук и пк на виндовс. везде блокировка обходится успешно. на маке просадок скорости по tcp нет. на венде есть. пробовала на компе с проблемной вендой грузить убунту лайв - проблем со скоростью нет

какую отсебятину может вносить венда что скорость именно для нее режется? до переустановки проблем со скоростью не было

скорость должна быть около 300мбпс. с этим замедлением около 2-3мбпс

скорость проверялась на: https://openspeedtest.com/

конфиг:
```
FWTYPE=nftables
SET_MAXELEM=9999999 #522288
IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
AUTOHOSTLIST_RETRANS_THRESHOLD=3
AUTOHOSTLIST_FAIL_THRESHOLD=3
AUTOHOSTLIST_FAIL_TIME=60
AUTOHOSTLIST_DEBUGLOG=0
MDIG_THREADS=30
GZIP_LISTS=1
QUIC_PORTS=443,444,9993,50000-65535
MODE=nfqws
MODE_HTTP=1
MODE_HTTP_KEEPALIVE=0
MODE_HTTPS=1
MODE_QUIC=1
MODE_FILTER=autohostlist
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC_HTTPS="--dpi-desync=split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sni --wssize 1:6"
NFQWS_OPT_DESYNC_HTTP6="--dpi-desync=split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sni --wssize 1:6"
NFQWS_OPT_DESYNC_HTTPS6="--dpi-desync=split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sni --wssize 1:6"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
NFQWS_OPT_DESYNC_QUIC6="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
TPWS_OPT="tpws --split-pos=1 --oob --mss=88"
FLOWOFFLOAD=donttouch
OPENWRT_LAN="br-lan"
OPENWRT_WAN4="wan"
INIT_APPLY_FW=1
DISABLE_IPV6=1
#GETLIST=
```

**Comment by bol-van** [comment]
` --wssize 1:6`

В этом проблема.
Разные системы могут по-разному управлять window size.
Если окно после манипуляций остается достаточно малым, это снижает скорость. Особенно на большом пинге.

**Comment by Euphoreka7** [comment]
пасиб

просканила еще раз. кроме кучи вариантов с `--wssize 1:6` остались только эти (c учетом скоростей выбрала первое):
```
--dpi-desync=fake,disorder --dpi-desync-ttl=1 --dpi-desync-fake-tls=0x00000000 --dpi-desync-split-pos=1 # 325/314
--dpi-desync=split2 --dpi-desync-split-seqovl=1 --dpi-desync-split-tls=sni # 322/280
--dpi-desync=syndata,split2 # 57/60
```

**Comment by bol-van** [comment]
syndata тоже лучше не использовать, поскольку не работает с хостлистом. хотя скорость и не режет.
