### ISSUE TITLE
какие рабочие конфиги NFQWS?

### ISSUE THREAD

**Issue by render69** [bol-van/zapret#594]
И так у меня вновь перестал работать скрипт для проверки рабочих стратегий
Увы но моя стратегия(ниже) перестала работать, гурзит первые 10 секунд видео(если повезёт)
```
NFQWS_OPT_DESYNC="-dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"

NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-ttl=0  --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"
```
У кого какие стратегии наботают? У меня ростик вообще стал инет тормозить не только на пк

**Comment by lxngren** [comment]
Лично у меня на ростелекоме работает twps --split-pos=1 --oob --mss=88, но раз через раз.

**Comment by TrueKoldun** [comment]
https://github.com/bol-van/zapret/issues/464#issuecomment-2406042314
Попробуйте увеличить --dpi-desync-repeats= с 6 на что-то побольше

**Comment by render69** [comment]
Короче надо будет поменять парочку настроек у меня с моим конфигом заработало
Браузер brave brave://flags/
Хром chrome://flags/
для остальных ищите сам я хз какой у вас браузер

Так вот надо тут включить парочку настроек, хах
Experimental QUIC protocol - QUIC в поске в выше сайтах
и
TLS 1.3 hybridized Kyber support - Kyber в поске в выше сайтах
Вы должны выбрать включино или enabled
на 14 октября это работает на другие дни хзхз

**Comment by broderix** [comment]
> Лично у меня на ростелекоме работает twps --split-pos=1 --oob --mss=88, но раз через раз. NFQWS наглухо мертв лично у меня

Спасибо за настройки, у меня работаю отлично, но только в связке с  --bind-addr=127.0.0.1 --port=8081 --uid=1:3003 --socks , а к мобильные устройства я проксирую на sthp --listen-ip 127.0.0.1 -p 8080 -s 127.0.0.1:8081 через прогу https://github.com/KaranGauswami/socks-to-http-proxy

**Comment by C0u1dnt** [comment]
> Лично у меня на ростелекоме работает twps --split-pos=1 --oob --mss=88, но раз через раз. NFQWS наглухо мертв лично у меня

А где в запрете это прописать?
В какой строчке конфига?

**Comment by epicbattle1** [comment]
> > Лично у меня на ростелекоме работает twps --split-pos=1 --oob --mss=88, но раз через раз. NFQWS наглухо мертв лично у меня
> 
> А где в запрете это прописать? В какой строчке конфига?

TPWS_OPT

**Comment by WinterWind777** [comment]
у меня в основном работает с этим
```
--dpi-desync=split2 --dpi-desync-split-seqovl=336 --dpi-desync-split-seqovl-pattern=/opt/zapret/files/fake/tls_clienthello_iana_org.bin"
```
только некоторые видео не открывает

**Comment by C0u1dnt** [comment]
> > > Лично у меня на ростелекоме работает twps --split-pos=1 --oob --mss=88, но раз через раз. NFQWS наглухо мертв лично у меня
> > 
> > 
> > А где в запрете это прописать? В какой строчке конфига?
> 
> TPWS_OPT

А можешь целиком конфиг скинуть

**Comment by epicbattle1** [comment]
> > > > Лично у меня на ростелекоме работает twps --split-pos=1 --oob --mss=88, но раз через раз. NFQWS наглухо мертв лично у меня
> > > 
> > > 
> > > А где в запрете это прописать? В какой строчке конфига?
> > 
> > 
> > TPWS_OPT
> 
> А можешь целиком конфиг скинуть

я использую nfqws, тебе выше дали настройки, убери из них tpws в начале и скопипасти в свой конфиг

**Comment by C0u1dnt** [comment]
> у меня в основном работает с этим
> 
> ```
> --dpi-desync=split2 --dpi-desync-split-seqovl=336 --dpi-desync-split-seqovl-pattern=/opt/zapret/files/fake/tls_clienthello_iana_org.bin"
> ```
> 
> только некоторые видео не открывает

не работает никак, даже с тпвс

**Comment by DADA30000** [comment]
`NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"`

**Comment by render69** [comment]
> `NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"`

а гос услуги как пофиксить?
