### ISSUE TITLE
Не грузятся превью и аватарки на YouTube

### ISSUE THREAD

**Issue by TheJarinMaster** [bol-van/zapret#595]
![0000034](https://github.com/user-attachments/assets/29fbfe15-69c8-4e44-b2c4-ee0ca869f2ff)
В хроме Kyber и QUIC стоят на default, из папки запускаю только general.bat
Есть кто сталкивался с такой же проблемой?

**Comment by NewUse** [comment]
у меня такое было, когда была выбрана не корректная стратегия для quic, посмотри в Discussion примеры стратегий для YouTube.

**Comment by iRadioMan** [comment]
Либо стратегия неудачная, либо необходимо дополнительно шифровать DNS запросы
