### ISSUE TITLE
unable to find libraries netfilter_queue, nfnetlink on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [bol-van/zapret#598]
The README says that the project supports FreeBSD, but the build depends on the libraries netfilter_queue, nfnetlink that aren't currently available on FreeBSD.

Were you able to compile netfilter_queue, nfnetlink on FreeBSD?

**Comment by bol-van** [comment]
It looks like you're ignoring makefiles in the project.

**Comment by bol-van** [comment]
BSD make uses BSDmakefile first then Makefile
If you have installed GNU make it may ignore BSDmakefile. If so use "make bsd", not just "make"

**Comment by yurivict** [comment]
I see. BSD make somehow succeeds to build it, thanks.

------------------

You may want to add the 'install' target that would install binaries into ```$DESTDIR$PREFIX/bin```.

**Comment by bol-van** [comment]
makefile in mdig,ip2net,nfq,tpws leave binary in its folder.
common make in /opt/zapret copies binaries to /opt/zapret/binaries/my.

zapret is intended to live in /opt/zapret.
it does not want to copy itself to special locations that vary from distro to distro and os to os

**Comment by yurivict** [comment]
> zapret is intended to live in /opt/zapret.
> it does not want to copy itself to special locations that vary from distro to distro and os to os

The standard "install" target below would correctly install into os-specific location on all Linux/BSD systems:
```
install:
      $(CP) build/executable-file $(DESTDIR)$(PREFIX)/bin
```
```DESTDIR``` is a stage dir, ```PREFIX``` is the prefix variable that is always set during builds.

**Comment by bol-van** [comment]
For pktws executable name may be winws,dvtws,nfqws
Single install target won't work
