### ISSUE TITLE
kernel warning с ядром 4.13 и tpws

### ISSUE THREAD

**Issue by pshpsh** [bol-van/zapret#6]
https://gist.github.com/pshpsh/3244d020e9676d25c0e24bc8148b6a4a strace
https://gist.github.com/pshpsh/0ebc7a82c2fef93674c5c4a08a8ac77d сам ворнинг

До 4.14 LTS надо подождать, наверно. Пока откатился на 4.12.

**Comment by bol-van** [comment]
http://elixir.free-electrons.com/linux/latest/source/lib/iov_iter.c

ворнинг тут :

static inline bool page_copy_sane(struct page *page, size_t offset, size_t n)
{
size_t v = n + offset;
if (likely(n <= v && v <= (PAGE_SIZE << compound_order(page))))
return true;
WARN_ON(1);
return false;
}

Можно попробовать уменьшить

tpws.h
#define SPLICE_LEN 65536

**Comment by pshpsh** [comment]
Попробовал, не помогает.

**Comment by bol-van** [comment]
SPLICE_LEN  до 4096, 2048
tpws.c
#define RD_BLOCK_SIZE 8192
до 4096,2048

если это не помогает, то буду ждать до вхождения ядра в стабильное состояние, может быть это найдут и пофиксят
вообще это ошибка ядра и user mode процесс не должен мочь вызывать ерроры и варнинги в ядре

**Comment by bol-van** [comment]
https://patchwork.kernel.org/patch/9927927/

**Comment by pshpsh** [comment]
Спасибо, патч как раз то самое. Теперь остается надеяться, что примут в 4.14.

**Comment by pshpsh** [comment]
Да, прочекал гит, уже есть в мастере.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/iov_iter.c#n688

**Comment by pshpsh** [comment]
Да, пофикшено в итоге.
