### ISSUE TITLE
-methodeol in NFQWS

### ISSUE THREAD

**Issue by asaddon** [bol-van/zapret#60]
Hello, is there any way to implement "methodeol" for NFQWS? My ISP recently changed something and I really want to bypass the DPI using NFQWS instead of TPWS because of the speed it offers. 

I'm not currently familiar with the technicalities if either it is possible or not but if it is then please implement it whenever you can.

**Comment by bol-van** [comment]
Read this https://github.com/bol-van/zapret/issues/58

**Comment by asaddon** [comment]
I know about this but you said theoreticaly it's possible to add some of the things in packet mode too so I was just wondering if "methodeol" can be done.

**Comment by bol-van** [comment]
I cant reimplement tcpip stack better than os does :)

**Comment by asaddon** [comment]
Understood. Looks like I'm stuck with Proxy mode for now lol. :)
