### ISSUE TITLE
Помощь с установкой

### ISSUE THREAD

**Issue by elzikv2** [bol-van/zapret#601]
Приветствую, установил, сделал по инструкции, особо ничего не изменилось, буду благодарен если поможете как правильно установить со скриншотами
Заранее благодарю

**Comment by Nikola2222** [comment]
куда установил?

**Comment by NewUse** [comment]
в смысле не изменилось?, не похоже, что инструкцию читали, блокчек скорее всего ругнулся на днс, например...

читать заново и вдумчиво .

**Comment by elzikv2** [comment]
все прочитал, примерно понял, не понял что выбирать в инстал изи, куда вписывать комбинации и как обойти запрет дс

**Comment by F4kogLc** [comment]
> все прочитал, примерно понял, не понял что выбирать в инстал изи, куда вписывать комбинации и как обойти запрет дс

терпи
![3](https://github.com/user-attachments/assets/8179b351-f05b-4547-9d36-08e4fb81be94)

**Comment by remittor** [comment]
> буду благодарен если поможете как правильно установить со скриншотами
> куда вписывать комбинации
> что выбирать в инстал изи

Коли вы написали про install_easy.sh, то очень вероятно вы ставите на OpenWrt.
Я конечно не экстрасенс, но вы сами должны были написать эту информацию!!! Вас выше даже специально попросили уточнить!!! Но вы до сих пор думаете, что все остальные люди обладают эксрасенсорикой.

Если вы на роутер с OpenWrt пытаетесь установить, то смотрите тут скрины: https://github.com/remittor/zapret-openwrt/discussions/1
Бинари лежат тут: https://github.com/remittor/zapret-openwrt/releases
