### ISSUE TITLE
Вопрос по скорости роутера на OW с zapret

### ISSUE THREAD

**Issue by ProLiteNT** [bol-van/zapret#602]
Есть такой кейс:
Настроен zapret и в нем offloading отключен, в роутере также отключен и скорость вместо 1гб/с получается 600мб/с и ниже, если на роутере включаю offloading, то скорость возвращается в нормальное состояние.
Подскажите как подружить с запретом? знаю что у некоторых включен offloading в zapret, но возможно под iptws или как-то так, у меня nfqws со списком /opt/zapret/ipset/zapret-hosts-user.txt

**Comment by bol-van** [comment]
В инсталяторе zapret надо выбрать software и hardware. Инсталятор отключит системную установку в UCI и сделает выборочное управление offload

**Comment by ProLiteNT** [comment]
> В инсталяторе zapret надо выбрать software или hardware. Инсталятор отключит системную установку в UCI и сделает выборочное управление offload


т.е. нужно прям переустановить zapret, когда в роутере включены обе галки? или можно в config просто поменять donttouch на hardware?
![image](https://github.com/user-attachments/assets/8612beeb-55b9-4a24-b09c-b27254f0674f)

**Comment by bol-van** [comment]
В UCI не надо включать. Инсталятор сам это отключит, если оно включено, потому что с ним обход работать не будет.
Трафик пойдет мимо дурилки.
Чтобы он пошел на дурилку в нужном обьеме нужно выборочное управление, которым занимается сам zapret
