### ISSUE TITLE
Не работает Не в РФ

### ISSUE THREAD

**Issue by snglovesyou** [bol-van/zapret#606]
Привет, попыталась установить этот фикс и еще несколько разных, разных версий и все они не работают потому что я живу в Турции (здесь этот фикс тоже нужен) Я после 10 ретраев решила попробовать включить Российский впн перед запуском и все заработало, подскажите нельзя ли как то изменить программу на фикс именно в моей стране и вообще как это можно контрить...

**Comment by snglovesyou** [comment]
> It's not easy program. If you have no idea how it works probably it's better not to use it

спс за помощь

**Comment by hardw3q** [comment]
Стоит почитать docs/quick_start. Скорее всего вы пытаетесь использовать конфиги которые подходят для россии в другой стране. 
Возможно будет досточно получить конфигурацию через blockcheck.sh

**Comment by bol-van** [comment]
Я так всегда отвечаю на подобные вопросы, потому что они так заданы.
Создается впечатления, что чел скачал, нажал, и у него НЕ.
И он хочет, чтобы он еще раз нажал, и у него ДА.
Ни подробностей, ни попытки изучить как оно работает. Потому и ответ - это не простая программа. Либо изучайте, либо удаляйте

**Comment by snglovesyou** [comment]
> Я так всегда отвечаю на подобные вопросы, потому что они так заданы. Создается впечатления, что чел скачал, нажал, и у него НЕ. И он хочет, чтобы он еще раз нажал, и у него ДА. Ни подробностей, ни попытки изучить как оно работает. Потому и ответ - это не простая программа. Либо изучайте, либо удаляйте

Понятно, просто мне посоветовали эту штуку и я то что она не работает не в рф узнала методом проб и ошибок, я не программист и просто решила узнать может это как то легко пофиксить можно. Извините что я тупой, хз((

**Comment by bol-van** [comment]
Вам подойдет что-то попроще. VPN, например.
