### ISSUE TITLE
Torrents are not downloading while zapret is started?

### ISSUE THREAD

**Issue by toprak** [bol-van/zapret#61]
Ubuntu 18.04 
My settings: MODE=nfqws_all_desync
NFQWS_OPT_DESYNC="--dpi-desync --dpi-desync-ttl=9 --dpi-desync-fooling=md5sig -$
INIT_APPLY_FW=1
DISABLE_IPV6=1

**Comment by bol-van** [comment]
As always I remind that this is NOT an EASY TOOL.
Do not expect it to work automatically and everywhere.
