### ISSUE TITLE
Не стартует MacOS Sequoia 15.0

### ISSUE THREAD

**Issue by ROLL007237** [bol-van/zapret#610]
После установки через install_easy.sh (MacOS Sequoia 15.0) для обхода по tpws в конце мне выдало, на сколько я понял, команду для запуска по tpws 

```
/opt/zapret/tpws/tpws --daemon --pidfile=/var/run/tpws1.pid --user=root --port=988 --bind-addr=127.0.0.1 --hostspell=HOST --split-http-req=method --split-pos=3 --oob
```
после запуска команды оно говорит:

> we have 1 user defined desync profile(s) and default low priority profile 0

Чего делать

UPD: Вручную перезапустил процесс tpws все заработало

**Comment by ROLL007237** [comment]
> Скорее стоит ли проверить запущен ли процесс pgrep ^tpws$

Запущен, айдишник бьется
Ютуб и дискорд все также не работают

nfqws в блокчеке мне выдает что через него не доджится DPI

**Comment by bol-van** [comment]
Значит стратегия не работает. nfqws нет на macos
