### ISSUE TITLE
В новой версии видит трояны

### ISSUE THREAD

**Issue by OldSmartSoldier** [bol-van/zapret#611]
Пытаюсь обновить, поскольку перестал работать ютуб. На другом устройстве с той же версией с тем же интернетом работает. Дискорд и там, и там работает. Во-первых вопрос, почему так может быть и имеет ли смысл обновиться, во-вторых, почему в новой версии видит троян Wacatac
![image](https://github.com/user-attachments/assets/bb3e0bf8-8e6a-49ca-973d-141b390a23f4)

**Comment by bol-van** [comment]
Антивирусы бывает дружат с upx, и я не собираюсь с этим бороться.
На разных устройствах могут быть разные броузеры или разные стратегии обхода.

**Comment by Razzvik** [comment]
и как быть
![Screenshot_20](https://github.com/user-attachments/assets/eab8ffa4-dea6-4277-873c-b25d15ca5830)

**Comment by bol-van** [comment]
1) Игнорировать
2) Проверить файл на вирустотал. Увидеть, что ругаются лишь раз два три из двадцать-тридцать
3) Перестать юзать

**Comment by johnnyd-78** [comment]
> 1. Убедиться, что это не сборка от васяна. Там может быть что угодно.

Это и есть сборка от васяна. Хотя в сборке от другого васяна плюс/минус то же самое, потому что ругается именно на экзешник запрета + на виндиверт. Двойное комбо "троянов" :D
Но у того другого васяна хотя бы эти файлы побитово соответствую взятым отсюда, но предыдущей версии (сверял КС), а вот сборку этого васяна я не проверял.

**Comment by bol-van** [comment]
Всегда есть пункт 3

**Comment by Tioplaya** [comment]
скажу так: 360 total security имеет кучу ложных срабатываний, поэтому верить ему - что себе не доверять
