### ISSUE TITLE
Зависания на ютубе

### ISSUE THREAD

**Issue by DADA30000** [bol-van/zapret#612]
Проблема в том, что в любой случайный момент ютуб может просто зависнуть на секунд 15-30, и если смотреть по сетевой активности, то он просто всё так же пытается подключиться к тому же домену откуда и шло видео, но у него почему то не получается в этот период с ошибкой NS_BINDING_ABORTED, но как только проходит немного времени, всё снова работает идеально, есть идеи как исправить?
NixOS, Firefox 131, zapret из последнего коммита, http3 отключён в Firefox, вот сами настройки
```sh
          MODE="nfqws"
          FWTYPE="iptables"
          MODE_HTTP=1
          MODE_HTTP_KEEPALIVE=0
          MODE_HTTPS=1
          MODE_QUIC=1
	  QUIC_PORTS=50000-65535
          MODE_FILTER=none
          DISABLE_IPV6=1
          INIT_APPLY_FW=1
          NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"
	  NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
          TMPDIR=/tmp
```
Если нужно что то ещё дописать, напишите что именно
EDIT: с включённым http3 всё так же

**Comment by mem-u** [comment]
QUIC_PORTS лучше вернуть на 443,444
У меня следующий конфиг (тоже пользуюсь firefox):
`NFQWS_OPT_DESYNC="--dpi-desync=fake,split --dpi-desync-repeats=6 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-fooling=badseq"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --dpi-desync-repeats=6"`

**Comment by DADA30000** [comment]
> QUIC_PORTS лучше вернуть на 443,444 У меня следующий конфиг (тоже пользуюсь firefox):
> 
> `NFQWS_OPT_DESYNC="--dpi-desync=fake,split --dpi-desync-repeats=6 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-fooling=badseq"`
> 
> `NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --dpi-desync-repeats=6"` Взято из zapret-discord-youtube от Flowseal

забыл написать, даже с полностью выключенным QUIC в zapret всё абсолютно так же :)

**Comment by DADA30000** [comment]
> QUIC_PORTS лучше вернуть на 443,444 У меня следующий конфиг (тоже пользуюсь firefox):
> 
> `NFQWS_OPT_DESYNC="--dpi-desync=fake,split --dpi-desync-repeats=6 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-fooling=badseq"`
> 
> `NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --dpi-desync-repeats=6"` Взято из zapret-discord-youtube от Flowseal

и fake + split для меня к сожалению не работает

**Comment by DADA30000** [comment]
хотя не, вроде даже работает

**Comment by DADA30000** [comment]
а ещё если ставлю `QUIC_PORTS` на `443,444` или `443,444`, голосовые звонки снова перестают работать в дискорде

**Comment by mem-u** [comment]
> хотя не, вроде даже работает но теперь другие заблокированные сайты не грузит

ставьте
`MODE_FILTER=hostlist`
и в /zapret/ipset/zapret-hosts-user.txt внесите следующие домены после чего перезапустите запрет
`
googlevideo.com
youtubei.googleapis.com
ytimg.com
yt3.ggpht.com
yt4.ggpht.com
youtube.com
youtubeembeddedplayer.googleapis.com
ytimg.l.google.com
jnn-pa.googleapis.com
youtube-nocookie.com
youtube-ui.l.google.com
yt-video-upload.l.google.com
wide-youtube.l.google.com
gstatic.com
discord.gg
discord.media
discordapp.com
discordapp.net
dl.discordapp.net
discordapp.io
discord.com
discordcdn.com
discord.dev
discord.new
discord.gift
dis.gd
discordstatus.com
`
Это только для дискорда и ютуба, можно еще добавить сайты на выбор в том же формате.
Через quic_ports не стоит фиксить звонки дс. Используйте скрипты от bol-van которые были недавно добавлены. (просто перекиньте из custom.d.examples в custom.d) После этого убедитесь что нет скрипта "custom" в директории /zapret/init.d/openwrt/ (вместо openwrt может быть sysv или другое название)
![image](https://github.com/user-attachments/assets/46f28307-abdc-42a3-8d48-74d13d331537)
После всего этого нужно изменить `MODE="nfqws"` на `MODE="custom"`
Далее презапускаете и все должно заработать

**Comment by DADA30000** [comment]
> > хотя не, вроде даже работает но теперь другие заблокированные сайты не грузит
> 
> ставьте
> 
> ```shell
> MODE_FILTER=hostlist
> ```
> 
> и в /zapret/ipset/zapret-hosts-user.txt внесите следующие домены после чего перезапустите запрет
> 
> ```shell
> googlevideo.com
> youtubei.googleapis.com
> ytimg.com
> yt3.ggpht.com
> yt4.ggpht.com
> youtube.com
> youtubeembeddedplayer.googleapis.com
> ytimg.l.google.com
> jnn-pa.googleapis.com
> youtube-nocookie.com
> youtube-ui.l.google.com
> yt-video-upload.l.google.com
> wide-youtube.l.google.com
> gstatic.com
> discord.gg
> discord.media
> discordapp.com
> discordapp.net
> dl.discordapp.net
> discordapp.io
> discord.com
> discordcdn.com
> discord.dev
> discord.new
> discord.gift
> dis.gd
> discordstatus.com
> ```
> 
> Это только для дискорда и ютуба, можно еще добавить сайты на выбор в том же формате. Через QUIC_PORTS, по словам создателя, не стоит фиксить звонки дс т.к. это может привезти к багам и неисправностям. Используйте скрипты от bol-van которые были недавно добавлены. (просто перекиньте из custom.d.examples в custom.d) После этого убедитесь что нет скрипта "custom" в директории /zapret/init.d/openwrt/ (вместо openwrt может быть sysv или другое название) ![image](https://private-user-images.githubusercontent.com/54555136/377145296-46f28307-abdc-42a3-8d48-74d13d331537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjcyMTgsIm5iZiI6MTcyOTE2NjkxOCwicGF0aCI6Ii81NDU1NTEzNi8zNzcxNDUyOTYtNDZmMjgzMDctYWJkYy00MmEzLThkNDgtNzRkMTNkMzMxNTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEyMDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NjVlMjA2MjU0N2U2NzM3N2YxMDYxOGNjYjMwNzkxNmZmOTE5Y2ZlZDI2YmM3YzZiNGU1MTJlN2M2NmNkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RCryqfEZCcgBHojFFNBy8io86XSRBbbnKIufZHJHFbo) После всего этого нужно в конфиге изменить
> 
> ```shell
> MODE="nfqws"
> ```
> 
> на
> 
> ```shell
> MODE="custom"
> ```
> 
> Далее презапускаете и все должно заработать (Если у вас нет папок custom.d и custom.d.examples, то нужно обновить zapret)

1. У меня NixOS и я использую zapret как пакет, так что я не могу модифицировать что в нём находится

2. Можно просто использовать аргументы --new и --hostlist, это намного легче, но проблема в другом

3. Проблема в том что я не могу найти метод при котором нет этих зависаний, хотя в последнее время их намного меньше стало, теперь уже в основном при проматывании

**Comment by Resource-xx** [comment]
У меня похожая ситуация - или не открывается страница с видео, или с перебоями загружается видеопоток.
Решилось только разбиением  на отдельные группы правил для разных хостов:
1. googlevideo.com + *.googlevideo.com;
2. тытруба + дискорд;
3. остальное (типа рутрекеров и иже с ним);

**Comment by andmt1** [comment]
> EDIT на след день: зависания все ещё присутствуют

поднимите --dpi-desync-repeats=6 до 15-20.
так: --dpi-desync-repeats=15

**Comment by vitaldmit** [comment]
> Проблема в том, что в любой случайный момент ютуб может просто зависнуть на секунд 15-30, и если смотреть по сетевой активности, то он просто всё так же пытается подключиться к тому же домену откуда и шло видео, но у него почему то не получается в этот период с ошибкой NS_BINDING_ABORTED, но как только проходит немного времени, всё снова работает идеально, есть идеи как исправить? NixOS, Firefox 131, zapret из последнего коммита, http3 отключён в Firefox, вот сами настройки
> 
> ```shell
>           MODE="nfqws"
>           FWTYPE="iptables"
>           MODE_HTTP=1
>           MODE_HTTP_KEEPALIVE=0
>           MODE_HTTPS=1
>           MODE_QUIC=1
> 	  QUIC_PORTS=50000-65535
>           MODE_FILTER=none
>           DISABLE_IPV6=1
>           INIT_APPLY_FW=1
>           NFQWS_OPT_DESYNC="--dpi-desync=syndata,fake,split2 --dpi-desync-fooling=md5sig"
> 	  NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
>           TMPDIR=/tmp
> ```
> 
> Если нужно что то ещё дописать, напишите что именно EDIT: с включённым http3 всё так же

Конфиг рабочий. Ютуб грузится нормально. Но проблема в том что некоторые сайты перестали открываться. Например avito, habr и еще кое какие. Пробовал `QUIC_PORTS=50000-65535` менять на 443,444, но не помогает. Что может быть?

**Comment by andmt1** [comment]
D конфиге прописать MODE_FILTER=hostlist

и внести нужные домены в белый список:
zapret-hosts-user.txt

или в черный (авито хабр вк):
zapret-hosts-user-exclude.txt

**Comment by DADA30000** [comment]
> > EDIT на след день: зависания все ещё присутствуют
> 
> поднимите --dpi-desync-repeats=6 до 15-20. так: --dpi-desync-repeats=15

проблема сама исчезла спустя несколько дней, просто я уже забыл как то об этом issue здесь, а так я уже пробовал тогда это сделать, не помогло :)
