### ISSUE TITLE
Не работает на кабельном интернете (Вайфай воркает)

### ISSUE THREAD

**Issue by winnerbylife13** [bol-van/zapret#614]
Пытался пофиксить дискорд, ставил разные обновления, пробовал стратегии от других людей, никак не работают, до тех пор, пока не переключусь на вайфай. Блокчек очень долго подбирал (3100+ строк)

SUMMARY
ipv4 discord.com curl_test_http : working without bypass
ipv4 discord.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata
ipv4 discord.com curl_test_http3 : winws not working

**Comment by bol-van** [comment]
Это похоже на ситуацию, когда работает средство обхода блокировок. Например, не был остановлен zapret

**Comment by winnerbylife13** [comment]
Перед блокчеком выключил запрет, служба была остановлена. Не могу понять почему именно с кабельным происходит такое, ведь как только я переключаюсь на беспроводной интернет сразу же все запускается как надо

**Comment by winnerbylife13** [comment]
попробовал сегодня quick блокчек и выбрал ipv4 и ipv6 вместе, в summary мне выдало следующее:

ipv4 discord.com curl_test_http : working without bypass
ipv4 discord.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata
ipv4 discord.com curl_test_http3 : winws not working
ipv6 discord.com curl_test_http : test aborted, no reason to continue. curl code 6: could not resolve host
ipv6 discord.com curl_test_https_tls12 : test aborted, no reason to continue. curl code 6: could not resolve host
ipv6 discord.com curl_test_http3 : test aborted, no reason to continue. curl code 6: could not resolve host
ipv4 youtube.com curl_test_http : working without bypass
ipv4 youtube.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=split2
ipv4 youtube.com curl_test_http3 : winws --wf-l3=ipv4 --wf-udp=443 --dpi-desync=fake --dpi-desync-repeats=5
ipv6 youtube.com curl_test_http : test aborted, no reason to continue. curl code 6: could not resolve host
ipv6 youtube.com curl_test_https_tls12 : test aborted, no reason to continue. curl code 6: could not resolve host
ipv6 youtube.com curl_test_http3 : test aborted, no reason to continue. curl code 6: could not resolve host

До этого пробовал standard, только ipv4 и только discord.com (в начале темы уже было):

ipv4 discord.com curl_test_http : working without bypass
ipv4 discord.com curl_test_https_tls12 : winws --wf-l3=ipv4 --wf-tcp=443 --dpi-desync=syndata
ipv4 discord.com curl_test_http3 : winws not working

Это все было при подключении интернета к ноутбуку кабелем, на вайфае блокчек не запускал (если это как-то влияет на ситуацию..)

Возможно с этими данными можно подобрать обход или объяснить, в чем проблема заключается? Прошу помочь, если это возможно, потому что разбираюсь я в этом плохо, а пользоваться дискордом хочется :(

**Comment by artemryskal** [comment]
@winnerbylife13 как пофиксил?

**Comment by winnerbylife13** [comment]
> @winnerbylife13 как пофиксил?

точно не понял от чего именно, попробовал zapret [flowseal](https://github.com/Flowseal/zapret-discord-youtube) и подключился к самому вайфаю (до этого тоже пытался подключится одновременно с кабельным, но дискорд все так же не работал), щас попробвал и работает вроде. Просто методом тыка, потому что абсолютно не разбираюсь в этом всем

**Comment by artemryskal** [comment]
> > @winnerbylife13 как пофиксил?
> 
> точно не понял от чего именно, попробовал zapret [flowseal](https://github.com/Flowseal/zapret-discord-youtube) и подключился к самому вайфаю (до этого тоже пытался подключится одновременно с кабельным, но дискорд все так же не работал), щас попробвал и работает вроде. Просто методом тыка, потому что абсолютно не разбираюсь в этом всем

Понял. Спасибо за ответ
