### ISSUE TITLE
Youtube не грузит видео

### ISSUE THREAD

**Issue by etty80** [bol-van/zapret#615]
Добрый вечер,
На кинетике все отлично работало, но:

Как и у остальных стал плохо работать Youtube, особенно хреново грузится на iOS \ Android TV с шансом в 1\10, на изначально рабочих стратегиях с split2, билайн мск. При этом все остальные заблокированные сайты работают. Использую ipset с get_reestr_preresolved_smart.sh

1. Как понять что пров блочит ,googlevideo.com по IP (В таком случае обход вообще не возможен?)
2. Если IP заблочены, можно ли завернуть домены googlevideo.com итд на wireguard туннель который поднят до VPS. И если возможно, как это правильно сделать на кинетике? При этом оставить дурение для остальных хостов как есть.
3. Может быть есть какой - то альтернативный вариант, как можно заставить ютуб на iOS \ Android ходить только на "правильные IP", которые не блокнули?
4. iOS / Android youtube приложения используют QUIC? Может быть есть смысл завернуть только QUIC на wireguard? Можно ли так?
5. Есть ли мысли как можно поправить? Нужен ли тут --dpi-desync-cutoff=d4?
Моя стратегия для QUIC:
`--dpi-desync=fake,split2 --dpi-desync-ttl=8 --dpi-desync-any-protocol --dpi-desync-repeats=15 --dpi-desync-fooling=md5sig --dpi-desync-split-seqovl=1 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin`

Заранее сорри, если какие - то вопросы тупые или нерелевантные.

**Comment by DADA30000** [comment]
> Добрый вечер, На кинетике все отлично работало, но:
> 
> Как и у остальных стал плохо работать Youtube, особенно хреново грузится на iOS \ Android TV с шансом в 1\10, на изначально рабочих стратегиях с split2, билайн мск. При этом все остальные заблокированные сайты работают. Использую ipset с get_reestr_preresolved_smart.sh
> 
>     1. Как понять что пров блочит ,googlevideo.com по IP (В таком случае обход вообще не возможен?)
> 
>     2. Если IP заблочены, можно ли завернуть домены googlevideo.com итд на wireguard туннель который поднят до VPS. И если возможно, как это правильно сделать на кинетике? При этом оставить дурение для остальных хостов как есть.
> 
>     3. Может быть есть какой - то альтернативный вариант, как можно заставить ютуб на iOS \ Android ходить только на "правильные IP", которые не блокнули?
> 
>     4. iOS / Android youtube приложения используют QUIC? Может быть есть смысл завернуть только QUIC на wireguard? Можно ли так?
> 
>     5. Есть ли мысли как можно поправить? Нужен ли тут --dpi-desync-cutoff=d4?
>        Моя стратегия для QUIC:
>        `--dpi-desync=fake,split2 --dpi-desync-ttl=8 --dpi-desync-any-protocol --dpi-desync-repeats=15 --dpi-desync-fooling=md5sig --dpi-desync-split-seqovl=1 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin`
> 
> 
> Заранее сорри, если какие - то вопросы тупые или нерелевантные.

насчёт первого, выясни какой айпи для начала под доменом (пингани с впном например), и потом просто попробуй зайти на этот айпишник со своими обходами
ещё у тебя многовато опций, попробуй поубирать некоторые
ещё я вообще пытаюсь избегать QUIC, проблематичный он, сосредоточься на обычных общих методах обхода, не для QUIC, а QUIC отрубить попробуй

**Comment by Filentin** [comment]
У меня другая проблема, ставлю запрет на роутер, все работает отлично до момента перезагрузки роутера. После запуска просто перестает работать... Я и рестарчу fw3, fw4 и сам запрет перезапускаю, ничего. Вот тока переустановка помогает. В чем может быть косяк, понять не могу. Может кто сталкивался?

**Comment by etty80** [comment]
> У меня другая проблема, ставлю запрет на роутер, все работает отлично до момента перезагрузки роутера . а переустановка помогает. В чем может быть косяк, понять не могу. Может кто сталкивался?

Я думаю, у тебя какая то проблема со скриптами. Сделай еще раз внимательно по [гайду ](https://habr.com/ru/articles/834826/)на чистый диск

**Comment by etty80** [comment]
> > Добрый вечер, На кинетике все отлично работало, но:
> > Как и у остальных стал плохо работать Youtube, особенно хреново грузится на iOS \ Android TV с шансом в 1\10, на изначально рабочих стратегиях с split2, билайн мск. При этом все остальные заблокированные сайты работают. Использую ipset с get_reestr_preresolved_smart.sh
> > ```
> > 1. Как понять что пров блочит ,googlevideo.com по IP (В таком случае обход вообще не возможен?)
> > 
> > 2. Если IP заблочены, можно ли завернуть домены googlevideo.com итд на wireguard туннель который поднят до VPS. И если возможно, как это правильно сделать на кинетике? При этом оставить дурение для остальных хостов как есть.
> > 
> > 3. Может быть есть какой - то альтернативный вариант, как можно заставить ютуб на iOS \ Android ходить только на "правильные IP", которые не блокнули?
> > 
> > 4. iOS / Android youtube приложения используют QUIC? Может быть есть смысл завернуть только QUIC на wireguard? Можно ли так?
> > 
> > 5. Есть ли мысли как можно поправить? Нужен ли тут --dpi-desync-cutoff=d4?
> >    Моя стратегия для QUIC:
> >    `--dpi-desync=fake,split2 --dpi-desync-ttl=8 --dpi-desync-any-protocol --dpi-desync-repeats=15 --dpi-desync-fooling=md5sig --dpi-desync-split-seqovl=1 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Заранее сорри, если какие - то вопросы тупые или нерелевантные.
> 
> насчёт первого, выясни какой айпи для начала под доменом (пингани с впном например), и потом просто попробуй зайти на этот айпишник со своими обходами ещё у тебя многовато опций, попробуй поубирать некоторые ещё я вообще пытаюсь избегать QUIC, проблематичный он, сосредоточься на обычных общих методах обхода, не для QUIC, а QUIC отрубить попробуй

А как отрубить QUIC для приложений? Как можно его запретить им?

**Comment by ivdeveloper86** [comment]
> > > Добрый вечер, На кинетике все отлично работало, но:
> > > Как и у остальных стал плохо работать Youtube, особенно хреново грузится на iOS \ Android TV с шансом в 1\10, на изначально рабочих стратегиях с split2, билайн мск. При этом все остальные заблокированные сайты работают. Использую ipset с get_reestr_preresolved_smart.sh
> > > ```
> > > 1. Как понять что пров блочит ,googlevideo.com по IP (В таком случае обход вообще не возможен?)
> > > 
> > > 2. Если IP заблочены, можно ли завернуть домены googlevideo.com итд на wireguard туннель который поднят до VPS. И если возможно, как это правильно сделать на кинетике? При этом оставить дурение для остальных хостов как есть.
> > > 
> > > 3. Может быть есть какой - то альтернативный вариант, как можно заставить ютуб на iOS \ Android ходить только на "правильные IP", которые не блокнули?
> > > 
> > > 4. iOS / Android youtube приложения используют QUIC? Может быть есть смысл завернуть только QUIC на wireguard? Можно ли так?
> > > 
> > > 5. Есть ли мысли как можно поправить? Нужен ли тут --dpi-desync-cutoff=d4?
> > >    Моя стратегия для QUIC:
> > >    `--dpi-desync=fake,split2 --dpi-desync-ttl=8 --dpi-desync-any-protocol --dpi-desync-repeats=15 --dpi-desync-fooling=md5sig --dpi-desync-split-seqovl=1 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Заранее сорри, если какие - то вопросы тупые или нерелевантные.
> > 
> > 
> > насчёт первого, выясни какой айпи для начала под доменом (пингани с впном например), и потом просто попробуй зайти на этот айпишник со своими обходами ещё у тебя многовато опций, попробуй поубирать некоторые ещё я вообще пытаюсь избегать QUIC, проблематичный он, сосредоточься на обычных общих методах обхода, не для QUIC, а QUIC отрубить попробуй
> 
> А как отрубить QUIC для приложений? Как можно его запретить им?

Нужно делать блок для UDP 443 порта, хотя у меня прекрасно работает на нем, даже быстрее чем на tls

**Comment by johnnyd-78** [comment]
Как отрубить квик в приложении ютуб на андроиде (а именно про это и был вопрос) - никак. Так что там именно нужен рабочий квик и нет смысла его блочить - только хуже сделаете.

Насчет опций - да, много лишнего. Во-первых на udp не работает дурилка split2/disorder2 и их варианты без 2 - это только для TCP. TTL там тоже нет. Если дурится any-protocol то обязательно нужен connbytes или cutoff - читайте хелп. dpi-desync-split-seqovl не работает для UDP как и сам split Дурилка md5 вроде к UDP тоже непременима, но это надо уточнять в хелпе.
Остаются репитс и фейк - от них и надо плясать. Уменьшить/увеличить репитс, взять другой bin фейка... У меня репитс 2 вообще хватает для беспроблемной работы квика на ютубе.

**Comment by bol-van** [comment]
> TTL там тоже нет

TTL на udp есть, поскольку относится к уровню IP.
и fooling=badsum тоже, поскольку чексум есть и в UDP.

**Comment by bol-van** [comment]
> Я и рестарчу fw3, fw4 и сам запрет перезапускаю, ничего.

Вроде была у кого-то похожая проблема. Он тыкая на все, установил и nft, и iptables, и получился адский микс

**Comment by hlivergaing** [comment]
Неделю назад данный конфиг отрабатывал отлично и на Android и Windows и WEB OS (LGTV) - но неделю назад просто внезапно перестало работать именно на Android смартфонах и LG TV

WS_USER=nobody
FWTYPE=iptables
SET_MAXELEM=522288
IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
AUTOHOSTLIST_RETRANS_THRESHOLD=3
AUTOHOSTLIST_FAIL_THRESHOLD=3
AUTOHOSTLIST_FAIL_TIME=60
AUTOHOSTLIST_DEBUGLOG=0
MDIG_THREADS=30
GZIP_LISTS=1
MODE=nfqws
MODE_HTTP=1
MODE_HTTP_KEEPALIVE=0
MODE_HTTPS=1
MODE_QUIC=1
MODE_FILTER=none
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --wssize 1:6 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-ttl=0 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_google_com.bin --wssize 1:8"
TPWS_OPT="--hostspell=HOST --split-http-req=method --split-pos=3 --oob"
FLOWOFFLOAD=donttouch
INIT_APPLY_FW=1
DISABLE_IPV6=1
GETLIST=get_user.sh

**Comment by etty80** [comment]
@bol-van @johnnyd-78 
Благодарю господа, не знал про split и udp. Нашел рабочую стратегию.
