### ISSUE TITLE
zapret полностью зависает

### ISSUE THREAD

**Issue by ivdeveloper86** [bol-van/zapret#616]
Всем привет!
Столкнулся с проблемой полного зависания процесса вот на таком конфиге:
```
#!/bin/sh

SCRIPT=/tmp/mnt/DPI/zapret-master/nfq/nfqws
PIDFILE=/var/run/nfqwsTCP.pid
HOSTLISTFILE=/tmp/mnt/DPI/zapret-master/hostlist.txt
DVTWS="--daemon --qnum=200 --dpi-desync=fake,split --dpi-desync-fooling=md5sig --dpi-desync-repeats=5 --dpi-desync-fake-tls=/tmp/mnt/DPI/zapret-master/files/fake/tls_clienthello_www_google_com.bin --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service NFQWS is already running' >&2
    return 1
  fi
  $SCRIPT $DVTWS
  iptables -t mangle -I POSTROUTING -o eth0 -p tcp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
  echo 'Started NFQWS service'
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service NFQWS is not running' >&2
    return 1
  fi
  echo 'Stopping NFQWS service...'
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  iptables -t mangle -D POSTROUTING -o eth0 -p tcp --match multiport --dport 80,443 -j NFQUEUE --queue-num 200 --queue-bypass
}

status() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service NFQWS is running'
  else
    echo 'Service NFQWS is stopped'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
```

Вначале все отлично работает, все домены из хостлиста и Ютуб, но в течении пары минут все виснет и даже не заблокированные сайты перестают открываться. Если остановить процесс, сайты (не заблокированные) снова начинают грузиться. Использую последнюю версию запрета (сегодня обновлял).

Подскажите, это кривость моего конфига или что-то другое?

**Comment by bol-van** [comment]
Фильтра по mark не хватает. При большом количестве попыток может произойти deadlock

**Comment by ivdeveloper86** [comment]
Фильтр по mark добавлял, с ним он вообще не работает в таком конфиге.
Пока что убрал 80 порт, пока не виснет, потестирую...

**Comment by bol-van** [comment]
-m mark ! --mark 0x40000000/0x40000000

такой должен быть фильтр. если с ним что-то не работает, то без него что-то работает неправильно

**Comment by bol-van** [comment]
Еще может марк не работать, потому что стоковая прошивка использует марк для своих целей и портит бит.
Надо разобраться что там наворочено в стоке. Если какой-то бит не используется, то можно задействовать его.

Без фильтра по марк будут дедлоки. Снизит их вероятность можно уменьшив repeats
