### ISSUE TITLE
Не работает файл blockcheck.sh

### ISSUE THREAD

**Issue by temcheeter** [bol-van/zapret#620]
Всё делал по инструкции с ютубчика. На этапе, когда нужно запускать файл blockcheck.sh, в консоли я получил это:
```
* checking system
Linux detected
firewall type is iptables
* checking already running zapret processes
* checking privileges
* checking prerequisites
nslookup or host does not exist. please install

press enter to continue
```
Отвечу на все вопросы. Заранее спасибо!

**Comment by bol-van** [comment]
Что за система ?
Прошивки, кроме openwrt, официально не поддерживаются. На них только самостоятельная прикрутка

**Comment by temcheeter** [comment]
> Что за система ? Прошивки, кроме openwrt, официально не поддерживаются. На них только самостоятельная прикрутка

uname ->
```Linux archlinux 6.11.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux```
Я новичок на пингвине, если какую-то команду надо прописать для информации - скажи.

**Comment by IlyaChizhanov** [comment]
@temcheeter только что проверил на Arch. Вам нужен [пакет](https://archlinux.org/packages/extra/x86_64/bind/) `bind`.

**Comment by freedom1b2830** [comment]
Как говорил IlyaChizhanov вам нужен bind
pacman -F nslookup
```
extra/bash-completion 2.14.0-2 [установлен]
    usr/share/bash-completion/completions/nslookup
extra/bind 9.20.3-1 [установлен]
    usr/bin/nslookup
extra/zsh 5.9-5 [установлен]
    usr/share/zsh/functions/Misc/nslookup
```
