### ISSUE TITLE
настройка на nixos 

### ISSUE THREAD

**Issue by Sk7Str1pe** [bol-van/zapret#623]
снесли ютуб с диском, мириться не стал. пытался настроить но дс не помогло, сам дискорд не установился (connection refused), а vesktop не подключается к серверам. мой конфиг запрета:
```Nix
{ pkgs, ... }:

{
  users.users.tpws = {
    isSystemUser = true;
    group = "tpws";
  };

  users.groups.tpws = {};

  systemd.services.zapret = {
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];
  
    path = with pkgs; [
      iptables
      nftables
      gawk
    ];
  
    serviceConfig = {
      Type = "forking";
      Restart = "no";
      TimeoutSec = "30sec";
      IgnoreSIGPIPE = "no";
      KillMode = "none";
      GuessMainPID = "no";
      ExecStart = "${pkgs.zapret}/bin/zapret start";
      ExecStop = "${pkgs.zapret}/bin/zapret stop";
    
      EnvironmentFile = pkgs.writeText "zapret-environment" ''
        MODE="tpws"
	ipv4 discord.com curl_test_http : working without bypass
        ipv4 discord.com curl_test_https_tls12 : tpws --split-tls=sni --oob
        ipv4 discord.com curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=9
        ipv4 discord.com curl_test_https_tls13 : tpws --split-tls=sni --oob
        ipv4 discord.com curl_test_https_tls13 : nfqws --dpi-desync=fake --dpi-desync-ttl=10
      '';
    };
  };
}
```
как понимаю чтото забыл прописать, но что - не ясно. заранее спасибо

**Comment by Nishimara** [comment]
@Sk7Str1pe для дискорда этого хватит

```bash
QUIC_PORTS=50000-65535
MODE_QUIC=1
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
```

**Comment by bol-van** [comment]
Это "сова на глобусе". Для discord есть custom  50-discord

**Comment by Sk7Str1pe** [comment]
@Good1Cheese буду тебе очень признателен если покажешь конфиг никса

**Comment by Sk7Str1pe** [comment]
@Nishimara 
![image](https://github.com/user-attachments/assets/3d7c8076-fecb-4492-a0e3-dc0f6e408bbe)
взял твой конф, дс не грузит, весктоп тоже

**Comment by Sk7Str1pe** [comment]
![image](https://github.com/user-attachments/assets/700f0abc-7650-4408-b820-b7220e781153)
заметил щас что запрету дали сервис, мб чер него? только там в params опции для запуска через шелл а не конфиг

**Comment by Sk7Str1pe** [comment]
все оказалось куда прозаичней, сервис просто не был запущен

**Comment by Sk7Str1pe** [comment]
![image](https://github.com/user-attachments/assets/f889691e-353f-41d5-98ab-29e2c47b5129)
однако сервис активировать не выходит, помирает при запуске, интересно

**Comment by Nishimara** [comment]
@Sk7Str1pe лучше использовать сервис zapret'а из nixpkgs, только параметры нужные подставь. И воспользуйся custom-50-discord для whitelist.

**Comment by Wumianzhe** [comment]
@Nishimara Я пока малознаком что с Nix, что с zapret, можно инструкцию как должен выглядеть services.zapret? Я предполагаю, что должно быть в whitelist, но не в params.

**Comment by Nishimara** [comment]
@Wumianzhe в params нужно подставить значения, какие ты бы подставил в NFQWS_OPT_DESYNC_*

например
```nix
services.zapret = {
  enable = true;
  whitelist = [
    ...
  ];
  params = [
    "--dpi-desync=fake,disorder2"
    "--dpi-desync-ttl=1"
    "--dpi-desync-autottl=2"
  ];
};
```

**Comment by pokedim13** [comment]
@Good1Cheese Как настроиться в итоге? Попытался запустить с nixpkgs, но не зафурычали звонки, хотя стал пускать в чат (vesktop)

**Comment by pokedim13** [comment]
@Wumianzhe Как ты? смог настроиться? Поделись успехами

**Comment by Wumianzhe** [comment]
@pokedim13 изначально что-то получалось с параметрами 
```
"--dpi-desync=fake,tamper"
"--dpi-desync-repeats=6"
"--dpi-desync-any-protocol"
```
и whitelist-ом из 50-discord, но при этом обрубало всё остальное. Как будто через zapret шло вообще всё и только дискорд проходил whitelist.

Сейчас vesktop начинает подключаться, и если его оставить на час вроде даже подключается, без войса. Но сохраняется доступ ко всему остальному.

**Comment by ReLoneR1** [comment]
умные люди у которых работает, может кто-нибудь сподобится написать инструкцию для простолюдинов

**Comment by ReLoneR1** [comment]
а почему мы хотим отключить уже готовый сервис из никспакетов и все прописывать сами вручную? я правильно понимаю что когда zapret появится на стабильной ветке, то все должно будет вот так прозаично работать?

> ![image](https://private-user-images.githubusercontent.com/159684143/378543778-700f0abc-7650-4408-b820-b7220e781153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NzkwMjUsIm5iZiI6MTcyOTg3ODcyNSwicGF0aCI6Ii8xNTk2ODQxNDMvMzc4NTQzNzc4LTcwMGYwYWJjLTc2NTAtNDQwOC1iODIwLWI3MjIwZTc4MTE1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNzUyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWJkMDA2MjNmNWUxMjliYjEwYTg2MmYwMmRjMmI1OWZkMTc1YTNjZDM4ZDljMDk3ZTM3MDIxMmExYTM0ZDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6KK-ZJ5bvzNN45iRXDO9bsQODlvw-msezExMRz6lyfs) заметил щас что запрету дали сервис, мб через него? только там в params опции для запуска через шелл а не конфиг

**Comment by Nishimara** [comment]
@ReLoneR1 проблема в текущей реализации сервиса. Он вызывает nfqws напрямую, тоесть ExecStart там ${pkgs.zapret}/bin/nfqws и параметры передаются здесь же. Если мы хотим более глубокой настройки - надо прибегать к методу, который я скинул выше. В будущем можно будет не отключать модуль из nixpkgs и прямо так его использовать, но пока - только так, если отбросить костыли.

**Comment by Nishimara** [comment]
@Sk7Str1pe ишью решён?

**Comment by cublae** [comment]
Не очень понимаю зачем здесь создается юзер под tpws, можете пожалуйста объяснить зачем?

**Comment by bol-van** [comment]
Скрипты zapret все равно его сами создадут, если он отсутствует.
Запускать службы под отдельным юзером - это правило хорошего тона с точки зрения security.
В случае срыва уязвимости не будет доступа к другим службам

**Comment by cublae** [comment]
Понял, спасибо за ответ

**Comment by Sk7Str1pe** [comment]
@Nishimara ишью решен через кастомный сервис, нативная настройка ломала сеть

**Comment by Nishimara** [comment]
В случае, если всё работает исправно, было бы неплохо закрыть ишью 🙃

**Comment by ReLoneR1** [comment]
@Nishimara 
> лучше использовать сервис zapret'а из nixpkgs, только параметры нужные подставь. И воспользуйся custom-50-discord для whitelist.

Я правильно понимаю это лист [ip адресов](https://github.com/Flowseal/zapret-discord-youtube/blob/main/ipset-discord.txt), благодаря которым работает войс в дискорде? Их же вроде нужно подставлять в команду не через --hostlist (whitelist), а через --ipset, которого нет в nixpkgs. По крайней мере у меня через whitelist ip-адресов - войс не заработал

**Comment by bol-van** [comment]
На *nix нужно использовать кернел ипсеты. --ipset - это плохое решение, в скриптах я его запретил

**Comment by ReLoneR1** [comment]
то есть это должно быть что-то типа такого? Только с добавленным --source?
[zapret.nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/networking/zapret.nix#L149)

**Comment by ritascarlet** [comment]
Короче парни, держите одно из решений

https://github.com/ritascarlet/Anti-RKN-on-any-linux-distributions

ебать запрет сложная штука, хоть убейте. Если у кого-то есть рабочий конфиг, но скиньте пж

**Comment by lunedzy** [comment]
> Короче парни, держите одно из решений
> 
> https://github.com/ritascarlet/Anti-RKN-on-any-linux-distributions
> 
> ебать запрет сложная штука, хоть убейте. Если у кого-то есть рабочий конфиг, но скиньте пж

а доки для кого)? ну в таком случае раз вам "сложно", то сделайте свой впн сервер и используйте его.

**Comment by ritascarlet** [comment]
> > Короче парни, держите одно из решений
> > https://github.com/ritascarlet/Anti-RKN-on-any-linux-distributions
> > ебать запрет сложная штука, хоть убейте. Если у кого-то есть рабочий конфиг, но скиньте пж
> 
> а доки для кого)? ну в таком случае раз вам "сложно", то сделайте свой впн сервер и используйте его.

доки для умных, а я долбаеб)

**Comment by pokedim13** [comment]
> > Короче парни, держите одно из решений
> > https://github.com/ritascarlet/Anti-RKN-on-any-linux-distributions
> > ебать запрет сложная штука, хоть убейте. Если у кого-то есть рабочий конфиг, но скиньте пж
> 
> а доки для кого)? ну в таком случае раз вам "сложно", то сделайте свой впн сервер и используйте его.

Для особо одарённых, запрет использует уязвимости на ТСПУ оборудовании (использовать несколько пробелов, делить заголовки, делить пакеты и т.д.). Ясен красен он сложен, ибо у каждого провайдер разное оборудование и по разному настроено, а тыкать в надежде, что заработает... Кринж как по мне...

VPN в таком варианте намного удобнее, тот же vless, но у NixOS есть проблемы с tun режимом. То что чел смог поднять WARP (который более стабильный, ибо работает через CDN) на этом дистре уже говорит о +- хороших навыках, а ты позер, кури дальше свою доку.

**Comment by pokedim13** [comment]
> доки для умных, а я долбаеб)

У тебя кстати конфиг на гитхабе поплыл 
![image](https://github.com/user-attachments/assets/1aa45bd5-d30f-439a-9442-e7f4764eeba5)

**Comment by ritascarlet** [comment]
> > доки для умных, а я долбаеб)
> 
> У тебя кстати конфиг на гитхабе поплыл ![image](https://private-user-images.githubusercontent.com/72319244/400985722-1aa45bd5-d30f-439a-9442-e7f4764eeba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMzU5MzIsIm5iZiI6MTczNjMzNTYzMiwicGF0aCI6Ii83MjMxOTI0NC80MDA5ODU3MjItMWFhNDViZDUtZDMwZi00MzlhLTk0NDItZTdmNDc2NGVlYmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDExMjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYjQ0ZDBkZjI3YjMwZGVjYjE2MjQ1MjcyOTZiOGFhYzM5ZWFlM2VjZmZlNDdjZDU1MTMzNjdiNjY5ZTZhNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wl-qbG6a-0liU1xON4limkK8Hpga4wMOrrZZmPr_Cu8)

Хреново( 

Сегодня поправлю

**Comment by ritascarlet** [comment]
> > доки для умных, а я долбаеб)
> 
> У тебя кстати конфиг на гитхабе поплыл ![image](https://private-user-images.githubusercontent.com/72319244/400985722-1aa45bd5-d30f-439a-9442-e7f4764eeba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTg2NTgsIm5iZiI6MTczNjM1ODM1OCwicGF0aCI6Ii83MjMxOTI0NC80MDA5ODU3MjItMWFhNDViZDUtZDMwZi00MzlhLTk0NDItZTdmNDc2NGVlYmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDE3NDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NGZhYmVmZmY0MGFlY2FhODg5NmY5ZjdkNGE1ZTA1MmJjNWQxM2Q5NmNhMDgyNmVlOTM1YWRiNjg0ZjZmNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RgLlhoVLMbYKQP1kzpfDkbx2KO-5FR95vs0sKpE--fY)

обновил, можешь смотреть

**Comment by pokedim13** [comment]
> обновил, можешь смотреть

Ага, позже чекну как-нить. Может чот скомунизжу. warp то я настроил ещё месяц назад... Ток тоже криво работает.

**Comment by Nishimara** [comment]
@descentcare 
```nix
systemd.services.zapret.serviceConfig.ExecStart = lib.mkForce "${pkgs.zapret}/bin/tpws";
```

Но в таком случае, скорее всего, придется перелопачивать сервис что-бы он работал конкретно под тпвс. Советую все же использовать nfqws, тогда париться придется исключительно с параметрами

**Comment by Simon-The-Human** [comment]
> Забил болт на декларативный подход... Смог настроить запрет на провайдере Билайн используя стратегию https://github.com/Flowseal/zapret-discord-youtube/blob/main/discord.bat (там много стратегий)

@imsweetdogs
Там обновили стратегии, дискорд вписан в остальные, чтобы параллельно не запускать.

https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.8.0

**Comment by MagisYT** [comment]
> Запустил через https://github.com/Sergeydigl3/zapret-discord-youtube-linux, для работы нужен nfqws в пакетах системы.

Можешь пожалуйста объяснить как это сделать, я немножко новичёк в никсе

**Comment by imsweetdogs** [comment]
> > Запустил через https://github.com/Sergeydigl3/zapret-discord-youtube-linux, для работы нужен nfqws в пакетах системы.
> 
> Можешь пожалуйста объяснить как это сделать, я немножко новичёк в никсе

Там есть инструкция

**Comment by UtsuHuman** [comment]
services.zapret.enable = true;
   services.zapret.whitelist =
   [
  "youtube.com"
  "googlevideo.com"
  "ytimg.com"
  "youtu.be"
  "discord.com"
  "discord-attachmets-uploads-prd.storage.googleapis.com"
  "googleapis.com"
];
services.zapret.params =
[
  "--dpi-desync=fake,disorder2"
  "--dpi-desync-ttl=1"
  "--dpi-desync-autottl=2"
];
Реализовал вот так, ютуб работал, но только в хроме, в файрфоксе нет (браузер по умолчанию).
Параметры дефолтные, в этом ишью писали про кастом 50 хз что писать

**Comment by yaitskov** [comment]
Привет,

Положил запретный конфиг в /etc/nixos/configuration.nix.
`nixos-rebuild switch` отработал чисто.
Статус службы ок, nfqw процесс вертится, но `iptables -S`  показывает путые таблицы.

Нужно пересобирать ядро с `# CONFIG_NETFILTER_XTABLES_COMPAT is not set`? 
Смущает что никсовая обвязка хорошо валидирует и добавить следующую проверку было легко и логично, но если её нет значит може и не надо уже. Ядро еще никогда не пересобирал под никсом. Опыт конечно полезный, но не самый приятный.
```
grep -E '^CONFIG_NETFILTER_XTABLES_COMPAT=[ym]$' /proc/config.gz
```


> ● zapret.service - DPI bypass service
>      Loaded: loaded (/etc/systemd/system/zapret.service; enabled; preset: ignored)
>      Active: active (running) since Mon 2025-10-27 09:00:07 MSK; 18min ago
>       Until: Mon 2025-10-27 10:00:07 MSK; 41min left
>  Invocation: f8048098110f4fedba88b4165c67a504
>    Main PID: 345686 (nfqws)
>          IP: 0B in, 0B out
>          IO: 0B read, 0B written
>       Tasks: 1 (limit: 18988)
>      Memory: 452K (peak: 1.8M)
>         CPU: 42ms
>      CGroup: /system.slice/zapret.service
>              └─345686 /nix/store/h1cjb183cagjldv8f75qvi28n1946ack-zapret-72/bin/nfqws --pidfile=/run/nfqws.pid --dpi-desync=fakedsplit…
> 
> Oct 27 09:00:07 nixos nfqws[345686]: Loading hostlist /nix/store/x9h1cgaixzxfr1m9qivqvmd23145bjaq-zapret-whitelist
> Oct 27 09:00:07 nixos nfqws[345686]: loading plain text list
> Oct 27 09:00:07 nixos nfqws[345686]: Loaded 8 hosts from /nix/store/x9h1cgaixzxfr1m9qivqvmd23145bjaq-zapret-whitelist
> Oct 27 09:00:07 nixos nfqws[345686]: Running as UID=2147483647 GID=2147483647
> Oct 27 09:00:07 nixos nfqws[345686]: opening library handle
> Oct 27 09:00:07 nixos nfqws[345686]: unbinding existing nf_queue handler for AF_INET (if any)
> Oct 27 09:00:07 nixos nfqws[345686]: binding nfnetlink_queue as nf_queue handler for AF_INET
> Oct 27 09:00:07 nixos nfqws[345686]: binding this socket to queue '200'
> Oct 27 09:00:07 nixos nfqws[345686]: setting copy_packet mode
> Oct 27 09:00:07 nixos nfqws[345686]: initializing raw sockets bind-fix4=0 bind-fix6=0
> 
> 

> ps aux | grep nfqw
> 2147483+  183974  0.0  0.0   3108  2228 ?        Ss   22:00   0:00 /nix/store/
> h1cjb183cagjldv8f75qvi28n1946ack-zapret-72/bin/nfqws --pidfile=/run/nfqws.pid --dpi-desync=fakedsplit --dpi-desync-ttl=11 --dpi-desync-split-pos=method+2 --dpi-desync-fakedsplit-mod=altorder=1 --hostlist /nix/store/x9h1cgaixzxfr1m9qivqvmd23145bjaq-zapret-whitelist --qnum=200

**Comment by GriefNorth** [comment]
В итоге кто-то нашел рабочий конфиг ?

**Comment by imsweetdogs** [comment]
@GriefNorth Да, просто заюзай стратегии flowseal

**Comment by ApathyErr** [comment]
@GriefNorth https://github.com/kartavkun/zapret-discord-youtube
