### ISSUE TITLE
Помогите удалить папку zapret-win-bundle-master

### ISSUE THREAD

**Issue by binjof** [bol-van/zapret#628]
Помогите удалить папку zapret-win-bundle-master. Если можно с более подробной инструкцией. При удалении показывает что папка или файл открыты в другой программе

**Comment by epicbattle1** [comment]
может надо отключить сервис перед тем как удалять?

**Comment by binjof** [comment]
Напиши пожалуйста как отключить сервис

**Comment by bol-van** [comment]
Для этого надо убить все процессы winws.exe и остановить windivert.
Убиение процессов сводится к закрытию окон или к остановке службы/задачи, если таковые были созданы.
Windivert удаляется так
cmd от  имени администратора
sc stop windivert

**Comment by Yatagarasu-282** [comment]
при вводе sc stop windivert пишет что данная программа не установлена
, но программа не удаляется

**Comment by bol-van** [comment]
Можно попробовать удалять все файлы и посмотреть какие файлы не удаляются
Если это winws.exe, windivert.dll, cygwin1.dll, то запущена копия winws
Иначе может быть такой вариант, что в этой папке находится другая программа как в текущей директории, и это не дает удалить всю директорию

**Comment by Vmsk88** [comment]
> Для этого надо убить все процессы winws.exe и остановить windivert. Убиение процессов сводится к закрытию окон или к остановке службы/задачи, если таковые были созданы. Windivert удаляется так cmd от имени администратора sc stop windivert

Спасибо огромное)
