### ISSUE TITLE
Как добавить в конфиг zapret на роутер

### ISSUE THREAD

**Issue by C0u1dnt** [bol-van/zapret#629]
Запрет от флоусила работает идеально, как добавить параметр на роутер в конфиг?

start "zapret: general" /min "%BIN%winws.exe" --wf-tcp=80,443 --wf-udp=443,50000-50100 ^
--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-50100 --ipset="ipset-discord.txt" --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new ^
--filter-tcp=80 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

**Comment by boozzze** [comment]
Да, волнительный момент и для меня, искал решение, не понимаю, почему оно не находится.

**Comment by boozzze** [comment]
[идеально](https://github.com/bol-van/zapret/issues/599#issuecomment-2427173135)

**Comment by bol-van** [comment]
Это скоро перестанет работать.

> Собираюсь убирать все это хозяйство с HTTP,HTTPS,QUIC,MODE
> Оно создавалось под вариант, когда не было мультистратегий и фильтров.
> Сейчас натягивают сову на глобус, пытаясь запихнуть в QUIC незапихуемое только потому, что там udp. Это полнейший misuse и трэш.
> Будет несовместимое изменение, полностью ломающее старый конфиг.
> Конфигурация будет приближена к winws.
> Отдельно настраиваем перехват по портам и отдельно опции единственного инстанса nfqws и/или tpws.
> Стандартный autohostlist будет в виде переменной $AUTOHOSTLIST, стандартный hostlist - $HOSTLIST. Куда надо, туда и воткнете. Будете сами думать куда. Как в винде.
> Скачивание сетов/листов будет отдельно настраиваться.
> Кастомы останутся, но уже без MODE=custom. Достаточно их наличия.
> Могут быть варианты, не вписывающиеся даже в новую схему.
> Тот же дискорд требует особого ipset. Проводить в конфиг - это слишком частно, такого не будет.
> На винде ipset идет через параметр --ipset winws, а на не винде это порочная практика. Естественно, по незнанию и по упрощению будут насиловать несвойственным образом, но это ненормально. Надо использовать kernel ipsets.
> Думаю воткну в инсталятор проверку на наличие параметра --ipset и принудительный отказ продолжать.
> Иначе один кто-то напишет, а потом по сети этот копипастный трэш будет распространяться.

**Comment by boozzze** [comment]
> Проводить в конфиг - это слишком частно, такого не будет.

Почему слишком частно, считаете? Два глобальных популярных сервиса, ютуб и дискорд

Грубо говоря, какой-нить Likee если бы был локнут, ну да, нафиг не интересен, но два топа, грандмастера, гроссмейстера интернета - YT DISCORD, имхо стоят такого подхода.

**Comment by boozzze** [comment]
или я не правильно понял вас? Интересует, будет ли понятное просто решение для openwrt под дискорд + ютуб онли?)

**Comment by nanopasta** [comment]
Тоже интересует, как такой конфиг прописать, и в какой раздел? nfqws, или куда?

**Comment by bol-van** [comment]
> Грубо говоря, какой-нить Likee если бы был локнут, ну да, нафиг не интересен, но два топа, грандмастера, гроссмейстера интернета - YT DISCORD, имхо стоят такого подхода.

Эта программа технически ориентированная, а не пользовательски.
Инструмент создается для применения определенных техник по определенным критериям.
Если критерии оказываются слишком специфические, пишутся кастом-скрипты.

**Comment by bol-van** [comment]
> или я не правильно понял вас? Интересует, будет ли понятное простое решение для openwrt под дискорд + ютуб онли?)

Если кто-то напишет - будет. Но уже под адекватную платформу, и без натягивания совы на одно место.
Сейчас этот конфиг хоть и может работать, но по сути неадекватное решение.
И еще универсальных вариантов не существует. Он может работать там, не работать здесь, и не работать завтра
