### ISSUE TITLE
внешний конфигурационный файл для tpws

### ISSUE THREAD

**Issue by alexdaft** [bol-van/zapret#632]
можно ли добавить в список переменных tpws внешний config файл для простоты сборки/обновления сервиса?
пример - складирование всех рабочих конфигов где нибудь в отдельном /etc/zapret/ и pull, пересборка бинарников в /usr/local/zapret/

**Comment by bol-van** [comment]
В чем проблема запускать что-то вроде tpws $(cat config_file) ?

**Comment by NewUse** [comment]
для какой ОС это требуется?

**Comment by alexdaft** [comment]
>В чем проблема запускать что-то вроде tpws $(cat config_file) ?

Да в целом вы наверное правы, можно и так, просто хотелось в сервис проталкивать конкретными путями а не подфункциями.

>для какой ОС это требуется?

Linux

**Comment by alexdaft** [comment]
>Чтобы в systemd unit засунуть постоянную строку запуска ?

Именно так, в целом вариант описанный вами тоже можно закрутить, думаю мне этой подсказки будет достаточно. Спасибо.

**Comment by NewUse** [comment]
какая init система? вообще для systemd для этого есть отдельная папка для хранения файлов опций запуска:
/etc/sysconfig/
если не ошибаюсь

**Comment by alexdaft** [comment]
Entware там просто шелл скрипт висит, затолкаю в переменные.

**Comment by naruto522ru** [comment]
> какая init система? вообще для systemd для этого есть отдельная папка для хранения файлов опций запуска: /etc/sysconfig/ если не ошибаюсь

Вообще-то нет)

/etc/default

**Comment by naruto522ru** [comment]
> В чем проблема запускать что-то вроде tpws $(cat config_file) ?

Можно скрипт по типу init с меняющимися параметрами. Ну или в environment затолкнуть а так tpws --param1=${VALUE1} --param2=${VALUE2}

**Comment by NewUse** [comment]
а какой жистрибутив то? кинетикОС чтоль?

**Comment by alexdaft** [comment]
>а какой жистрибутив то? кинетикОС чтоль?
ага, он самый

**Comment by Fenrir-0xFF** [comment]
Писал подобное предложение для nfqws, если разраб решит это реализовать там то аналогично и в tpws несколько строк думаю добавит. 
На нормальном линуксе это не критично, у меня на OpenWrt и LineageOS всего два файла - сам бинарик и .sh скрипт с параметрами, всё работает норм, а вот на некоторых официальных урезанных прошивках помимо гемора с iptables при большом количестве передаваемых параметров бинарику иногда возникают косяки. Ощющение что сам /bin/sh чясть парамеиров отрезает, самое хреновое что и отладку нормальную со скрипта не получить ps | grep nfqws > /tmp/123.txt выдаёт ещё меньше чем то что гарантировано отправлено бинарику

**Comment by Fenrir-0xFF** [comment]
@bol-van конфиг появился но с багами. v68 

Знак # в любой строке выше параметров отрубает все параметры расположенные ниже 

К примеру если в первой строке файла добавить сообщение что это конфиг для такогото провайдера "#Config for beeline" чтобы люди знали что это за файл то весь конфиг перестаёт работать. 

А если к примеру нужно отключить чтото одно
_--filter-tcp=80 --wssize=1:6 --dpi-desync=split --dpi-desync-fooling=md5sig,badsum 
**#**--new --filter-tcp=443 --wssize=1:6 --dpi-desync=disorder2
--new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6_ 
то всё что расположено ниже тоже отключяется. 

Написано что в конфиге игнориться всё кроме параметров, но параметры не цепляется из переменной даже если писать построчно 
_var=" 
--uid=0:0 --qnum=200 --new --filter-tcp=443 --wssize=1:6 --dpi-desync=disorder2
"_ 
Просто автоматическое добавление таблиц в nfqws/tpws не реализовано а собрать порты кроме как из переменной больше неоткуда, чтобы не плодить кучю файлов в качестве конфига удобно указывать sh скрипт который добавляет таблицы. 
Но это не критично, такто ничего не мешает в скрипте собрать порты для таблиц через $(cat /configfile) но тогда уже будет три минимально необходимых файла вместо двух. 

Ещё такой вопрос: почему @ или $ вместо --config <file> как положено по госту? Тщятельно на разных девайсах это ещё не тестил но есть риск того что sh воспримет файл конфига как переменную, в результате чего весь скрипт навернётся.

**Comment by bol-van** [comment]
А кто вам сказал, что в конфиг это конфиг ? Это не конфиг, а взятие параметров запуска процесса из файла.
Там банальный парсер, превращающий файл в argc,argv. Однако, он использует функции shell. Там можно писать его конструкции, использовать переменные, кроме запуска форков : `$(cmd)`
Как такового конфига в привычном смысле нет.

$ - это только для винды, где показыватель lnk жует все после @. В шелле можно `\$`, но не нужно. @ - лучше.
@ у меня используется и в других местах, где нужно что-то взять из файла.
не --config, потому что это НЕ конфиг. и чтобы не городить двойной код с getopt

> Написано что в конфиге игнориться всё кроме параметров, но параметры не цепляется из переменной даже если писать построчно
> var="
> --uid=0:0 --qnum=200 --new --filter-tcp=443 --wssize=1:6 --dpi-desync=disorder2
> "

так нельзя писать в этом файле. Там не должно быть никаких var=. Только параметры как в командной строке и все.

Про таблицы совсем не понял. Какие таблицы ? Динамического изменения параметров действительно нет, файлы хост/ipset автоматически перегружаются при изменениии, а kernel ipsets/tables управляются своими средствами
