### ISSUE TITLE
Параметр #DESYNC_MARK=0x40000000 не работет youtube

### ISSUE THREAD

**Issue by ipsenchenko** [bol-van/zapret#634]
Обратил внимание на то, что после очередного обновления в коммандную строку запуска nfqws настырно добавляется параметр   --dpi-desync-fwmark=0x40000000 с которым ничего не работает, после его удаления всё начинает работать, причём вымарать его достаточно сложно он прописан в файле конфигурации и в стартовых скриптах. Прекрасно помню, что раньше его не было.  
Товарищ майор не спит и гадит на гитхабе?

**Comment by bol-van** [comment]
Этот параметр всегда был. Он нужен. Используется для предотвращения зацикливания на сгенеренных пакетах.
И мало того это значение по умолчанию. Даже если не указывать будет 0x40000000

**Comment by ipsenchenko** [comment]
Тогда почему с ним у меня практически ничего не работает?

**Comment by NewUse** [comment]
переустановите запрет, по всей видимости не настроено перенаправление, и проверьте что выключен оффлоадинг, если на роутере запускаете

**Comment by bol-van** [comment]
> Тогда почему с ним у меня практически ничего не работает?

Не знаю откуда была получена эта установка что причина в этом параметре.
Тыкал на все подряд, что-то вышло , а как не знаю ?
Иногда причина работы может быть в неработе того, что должно должно работать, но оно не работает
