### ISSUE TITLE
Очень сильно лагает дискорд и иногда вообще не заходит просто бесконечная загрузка. 

### ISSUE THREAD

**Issue by Lolik52** [bol-van/zapret#635]
Скачивал запрет у флоусила. Вчера было нормально сегодня уже начались лаги и только что просто перестал работать дискорд. Кто знает как можно пофиксить? Пробовал устанавиливать другие версии не помогло.

**Comment by MistikLove** [comment]
у меня тоже самое 
перезапустил пк и не работает дс но ютуб пашет

**Comment by Lolik52** [comment]
Как я понял скорее всего большая нагрузка на домены в самый пик по времени так как ночью все четко и утром до обеда. после 15 по мск уже печаль начинается. Надо в лист дискорда добавить доменов побольше, но я не знаю где их взять. Щас сижу всё окей но до 22мск вообще зайти не мог просто не грузило
