### ISSUE TITLE
Не работает discord и ютуб

### ISSUE THREAD

**Issue by Aspirata** [bol-van/zapret#637]
Начиная с 21-го октября я больше не могу смотреть ютуб и даже просто зайти в дискорд c zapret. Хотя до этого дня я спокойно заходил в войсы и смотрел ютуб.
Немного информации:
Я сижу на линуксе. Режим работы zapret стоит на custom (Свои скрипты я не добавлял, всё работало из коробки), все остальные настройки при установке стоят в значении по умолчанию

**Comment by NewUse** [comment]
режим какой?blockcheck проверяли? слишком мало диталей, отсутствует диагностика, а вот телепаты, к сожалению, ушли в отпуск, начните с настройки DoH, если не была сделана ранее.

**Comment by Aspirata** [comment]
> режим какой?blockcheck проверяли? слишком мало диталей, отсутствует диагностика, а вот телепаты, к сожалению, ушли в отпуск, начните с настройки DoH, если не была сделана ранее.

режим какой? Custom
blockcheck проверяли? -- DNS looks good
начните с настройки DoH, если не была сделана ранее. Я не смог настроить его,  так чтобы работал ютуб,может вы знаете ссылку на нужный сервер DoH ?

**Comment by NewUse** [comment]
работа ютуб тут не при чём, годится любой сервер DoH.
Если настроен, то начните с провеки YouTube через блокчек, по некоторым данным, провайдеры начали его полноценно блочить

**Comment by Kerrung** [comment]
https://youtu.be/FdDC9R7gL-Y?si=jJ_9NtiEJMmydSaf

**Comment by Aspirata** [comment]
> https://youtu.be/FdDC9R7gL-Y?si=jJ_9NtiEJMmydSaf

Не помогло, делал всё по инструкции. Результат тот же, что и при обычной установке zapret

**Comment by NewUse** [comment]
не надо пользоваться васяно-инструкциями, всё есть в редми, если не хватает знаний -- можно купить vpn и забыть о блокировках раз и навсегда.

прогоняли блокчеком ютюб?

**Comment by Aspirata** [comment]
> не надо пользоваться васяно-инструкциями, всё есть в редми, если не хватает знаний -- можно купить vpn и забыть о блокировках раз и навсегда.
> 
> прогоняли блокчеком ютюб?

прогоняли блокчеком ютюб? Нет, у меня не хватает знаний(

**Comment by bol-van** [comment]
VPN уже тоже блокируют. По известным протоколам за бугор.
При дальнейшей эскалации этого процесса VPN тоже станет областью, где нужны знания.

**Comment by Dimadin27** [comment]
Знания всегда пригодятся, и нынешняя ситуация с блокировками это хороший стимул их получить.

**Comment by YaNixTo** [comment]
Кто додумался выложить гайд об обходе блока ютуба на самом ютубе?

**Comment by Aspirata** [comment]
Крч, решение было простым. Нужно просто переместить скрипт zapret/init.d/sysv/custom.d.examples/50-discord в zapret/init.d/sysv/custom.d
