### ISSUE TITLE
Winws становится .tmp при первом запуске

### ISSUE THREAD

**Issue by 8aizenZ** [bol-van/zapret#639]
![image](https://github.com/user-attachments/assets/ce08a1ca-43eb-4f45-b592-3e6eddf230b6)
пробовал переустанавливать ,
один раз при перезагрузке перед запуском дс включил и заработал, попробовал еще раз , не получилось

**Comment by 8aizenZ** [comment]
он превратился в trz3342.tmp

**Comment by 8aizenZ** [comment]
@bol-van , вери вери извеняюсь за пинг но мне срочно нужно пофиксить

**Comment by bol-van** [comment]
Происки антивируса ?

**Comment by 8aizenZ** [comment]
антивирус вырублен давно 
+ только в службах msconfig выключил GDPI
