### ISSUE TITLE
Как насчет openrc?

### ISSUE THREAD

**Issue by delvin-fil** [bol-van/zapret#64]
Гентуха у меня без systend и я понятия не имею, как это делать, ибо не интересовался.
ЗЫЖ Менять профиль и пересобирать мир не собираюсь.

**Comment by bol-van** [comment]
Я тоже не собираюсь делать easy_setup для гентухи
Не-изи описано в readme

**Comment by delvin-fil** [comment]
"Не-изи описано в readme"
Не, не, вы не поняли! Как с этими сисктл'ами бороться, что вместо них в openrc? Они ж разные шо попец! В опенрк я все умею, системд в глаза ни разу не видел(даже на виртуалках).

**Comment by fedya** [comment]
@delvin-fil sysctl это не часть openrc и не часть systemd, вот отсюда procps-ng устанавливается.

**Comment by delvin-fil** [comment]
> sysctl это не часть openrc и не часть systemd
> но так же поддерживается и большинство классических дистрибутивов linux, использующих **systemd**.
Как то так, а "sysctl" - ну как то не довелось, ибо все ручками.

**Comment by delvin-fil** [comment]
Ладно, всем спасибо! Разберусь.

**Comment by Zorgodon** [comment]
Вот что я использую на артиксе, если кому-то нужно:
(Просто обёртка для sysvinit скриптов)
``` 
#!/sbin/openrc-run

depend() {
    need net
}

checkconfig(){
ZAPRET_BASE=/opt/zapret
. "$ZAPRET_BASE/init.d/sysv/functions"
}

start() {
checkconfig || return 1
ebegin "Starting zapret"
/opt/zapret/init.d/sysv/zapret start
eend $?
}

stop(){
ebegin "Stopping zapret"
/opt/zapret/init.d/sysv/zapret stop
eend $?
}
```
