### ISSUE TITLE
Моментально закрывается 

### ISSUE THREAD

**Issue by PerPerteck** [bol-van/zapret#640]
Моментально закрывается bat файлы при открытие, такие как general сначала разумеется предупреждение от винды - разрешил, антивирус не блокает, при открытии просит имя запуск от имени администратора, затем закрывается, также если открывать файл от имени администратора вручную.

**Comment by bol-van** [comment]
Я обещал закрывать все issue, где человек не обладает базовыми знаниями, необходимыми для пользования программой. Выполняю
