### ISSUE TITLE
dvtws udp не работает с hostlist

### ISSUE THREAD

**Issue by fr-esa** [bol-van/zapret#642]
правила для ipfw
```
    ipfw add 100 divert 989 tcp from any to any 80,443 out not diverted xmit pppoe0
    ipfw add 100 divert 989 udp from any to any 50000-50030 out not diverted xmit pppoe0
```
выборка из скрипта для дискорда
```
    --filter-udp=50000-50030 \
    --dpi-desync=fake \
    --dpi-desync-repeats=6 \
    --dpi-desync-any-protocol \
    --hostlist=/usr/local/etc/dvtws/dvtws_discord \
```
в файле лежат сети добытые руками и соответствующие консоли в дискорде
содержимое самого dvtws_discord
```
66.22.196.0/22
66.22.200.0/21
66.22.208.0/20
66.22.216.0/24
66.22.217.0/24
66.22.224.0/22
66.22.230.0/23
66.22.232.0/21
66.22.240.0/21
66.22.244.0/24
66.22.248.0/24
```
в итоге дискорд не работает. Если убрать hostlist, дискорд работает, но в диапазон портов лезут некоторые пиры от торрента. при указании hostlist-auto, он не заполняется даже при большом колличестве попыток, hostlist-debug не регает новые записи. сам dvtws  обновлен
```
ls -la /usr/local/sbin/dvtws
-rwxr-xr-x  1 root wheel 137824 Oct 25 12:58 /usr/local/sbin/dvtws
```
что я сделал неправильно? tcp правила все работают корректно

**Comment by bol-van** [comment]
hostlist  работает с доменами. Они высекаются из прикладного протокола.
Если нужна фильтрация по ip, нужно использовать ipfw tables
См docs/bsd.txt

**Comment by fr-esa** [comment]
я в курсе, это черновая конфигурация

**Comment by fr-esa** [comment]
отдельный инстанс не понадобился, попрвил правило 
`ipfw add 100 divert 989 udp from any to table\(discord\) 50000-50030 out not diverted xmit pppoe0`
и добавил в стратегию 
`    --dpi-desync-cutoff=n2 \`
сорян что повторно открываю, ошибся кнопкой

**Comment by bol-van** [comment]
Если на udp ничего нет, кроме discord voice, то и правда отдельный инстанс не нужен, и можно обойтись отдельным профилем. А если бы был quic, то нужен
