### ISSUE TITLE
Как удалить zapret полностью

### ISSUE THREAD

**Issue by Uminacay** [bol-van/zapret#643]
Возникла проблема, что не могу удалить предложенными способами zapret на ПК. Все равно продолжают грузиться сайты, которые не должны грузиться. Мешает работе  VPN Paper.

**Comment by bol-van** [comment]
Я понял. Надо вставить REM в service_create и task_create
Чтобы без редактирования нажимая все подряд нельзя было установить сервис
Сумел отредактировать значит понимаешь как убирать
А нет, так закрыл окно. 
Правда, тут еще придется windivert останавливать. Но это можно заменить на ребут компа

**Comment by kangooroohh** [comment]
ничего не понял, я тоже хочу полностью удалить всё, не могу ни одним впном пользоваться
