### ISSUE TITLE
syndata problem

### ISSUE THREAD

**Issue by ppetbox** [bol-van/zapret#644]
syndata ломает некоторые сайты, но без него не работает YouTube. --hostlist-exclude не помогает потому что syndata в режиме hostlist не работает by design.  Если нельзя сделать действие syndata избирательным,  то не понятно как решать эту дилему потому что найти способ заставить работать YouTube без syndata мне не удалось. Поэтому что бы  достучаться до поломанных сайтов приходиться гасить zapret. Пробовал VPN, но его syndata тоже ломает, можно конечно поискать устойчивый против такой атаки но это то же квест с неопределённым результатом. Вобщем куда ни кинь всюду клин.

**Comment by bol-van** [comment]
Ипсет на ASN гугла
префиксы выдергиваются по whois

**Comment by ppetbox** [comment]
Работает. Спасибо. Правда whois дает не полный список, пришлось вручную допиливать, то есть добавить 77.37.192.0/18. От туда непосредственно идёт video stream. Я искал двумя способами:

1.  `whois -h whois.radb.net -- '-i origin AS15169`
2. https://bgp.he.net/AS15169#_prefixes

Почему то оба способа эту сеть не дали. А ещё нужно и дргими сайтами заняться - готовые списки слишком большие для nfqws. Вобщем дело геморойное - hostlist конечно лучше, но увы приходится от него отказаться

**Comment by bol-van** [comment]
> готовые списки слишком большие для nfqws

в каком конкретно месте они слишком большие ? 
туда можно миллионы записей загонять. Лишь бы памяти хватило.
ipset-ы надо гнать в ядро

**Comment by ppetbox** [comment]
> !!! nftables не могут работать с ipset-ами. Собственный аналогичный механизм требует огромного количество RAM
!!! для загрузки больших листов.  Например, для загона 100K записей в nfset не хватает даже 256 Mb.
!!! Если вам нужны большие листы на домашних роутерах, откатывайтесь на iptables+ipset.

Ну вот не хочется трогать iptables - там у меня самодельный firewall + docker. Кроме того зачем мне большие списки - я предпочитаю решать проблемы по мере их поступления, то есть добавлять сайты когда с ними сталкиваешься. Я даже список сетей для YouTube собираюсь сократить - ASN даёт слишком много, а излишества обременяют мою гершную душу. Хотя надо подумать, может действительно не стоит морочить себе голову и воспользоваться готовыми списками, если памяти хватит. У меня 4G:

`
               total        used        free      shared  buff/cache   available
Mem:         3847624     1767992      298064        7452     2101460     2079632
Swap:        3858428       75008     3783420
`
В общем я на распутье

**Comment by bol-van** [comment]
Я с успехом использовал ipset размером 20K на роутере с 64 Mb.  На 4G этой проблемы нет даже близко.

**Comment by ppetbox** [comment]
Ну то есть не надо переходить на iptables?  А то я попрбовал заменить `FWTYPE=nftables` на `FWTYPE=iptables` и получил в `systemctl status zapret.service`:

`zapret[338548]: iptables v1.8.10 (nf_tables): Set zapret doesn't exist.`

Или изменения значения переменной не достаточно и надо ещё что то руками прикручивать? Я думал эта задача автоматизирована.

**Comment by bol-van** [comment]
Не надо переходить на iptables.
Все что нужно исправил бы инсталлер

**Comment by ppetbox** [comment]
Спасибо за поддрежку. Ну тогда я попробую загрузить список по максиму что дают скрипрты ipset/get_*.sh и посмотрими как железяка с этим справится, у меня же там есть и дргуие сервисы. Какой из скриптов лучше подойдёт для этой задачи?

**Comment by bol-van** [comment]
get_antifilter_ipsmart.sh - небольшой и с порно
get_refilter_ipsum.sh - небольшой и с выкинутым порнокоазино, не все порно работает
get_reestr_preresolved.sh - тупо заресолвленный реестр
get_reestr_preresolved_smart.sh - предыдущее + накиданы туда ASNки cloudflare, гугла, меты и твиттера

**Comment by ppetbox** [comment]
Если я правильно понял из 10 скриптов самый большой список даёт ipset/get_reestr_preresolved_smart.sh а все остальные дают его подмножество? Или в меньших списках може быть то чего нет в самом большом? То есть смысл вопроса в том, стоит ли заниматься комбинаторикой объединяя списки и вычищая дублированные записи? Или лучше потом добавлять что то вручную, если натолкнёшься на сайт которого нет в твоём списке?

**Comment by bol-van** [comment]
Эти списки от разных источников. Что они там намутили - это целая история.
Но на практике в основном там есть почти все. Что не хватает можно добавить самому через zapret-hosts-user.txt

**Comment by ppetbox** [comment]
Попробовал get_reestr_preresolved_smart.sh - youtube не работает, то есть мета данные получает но видео не идёт. Вернлся к старому списку и всё заработало. Значит придётся заниматься рукоделием и дальше, увы.

**Comment by bol-van** [comment]
Надо смотреть по F12 на каких GGC фейлится. Возможно, они могут и не пренадлежать ASN гугла

**Comment by ppetbox** [comment]
Я не на браузере проверяю.  Я запускаю streamlink через proxy, смотрю на какие хосты он ходит, пропускаю ip через whois и в список уже добавляю сеть - так оно работает. Но в результате работает и десктоп браузер и мобильное приложение и smart tv и даже vlc который умеет youtube воспроизводить непосредственно

**Comment by bol-van** [comment]
Я для примера. Любым доступным способом, хоть SNI из .cap файла от tcpdump в шарке (tls.handshake фильтр)
И что whois показывает ? Каким ASN принадлежат адреса blablabla.googlevideo.com ?

**Comment by bol-van** [comment]
Когда работатет только syndata, чаще всего это является включенности ускорения в настройках прошивки. Он же offload.

**Comment by ppetbox** [comment]
@ppetbox:
> Работает. Спасибо. Правда whois дает не полный список, пришлось вручную допиливать, то есть добавить 77.37.192.0/18. От туда непосредственно идёт video stream. Я искал двумя способами:

Естественно не даёт, потому что это другая авотномная система, то есть русская а не гугловая. Скорее всего это и есть тот самый GGC местоного то есть русского разлива. Поэтому то эта сесть и не попадает в генерируемые скриптами списки. Вот почему (и не только поэтому) hostlist лучше чем ipset

**Comment by ppetbox** [comment]
@ppetbox:
> Я не на браузере проверяю. Я запускаю streamlink через proxy, смотрю на какие хосты он ходит, пропускаю ip через whois и в список уже добавляю сеть - так оно 

Это самый компактный метода, который даёт самый компактный результат:

```
77.37.192.0/18
142.250.0.0/15
64.233.160.0/19
173.194.0.0/16
```

И это всё что нужно для работы YouTube: всего четрые строчки в ipset соответсвующие четрырём строчкам access.log squid:

```
27/Oct/2024:15:15:22 +0300   5049 127.0.0.1 TCP_TUNNEL/200 3273705 CONNECT rr2---sn-gvnuxaxjvh-c35d.googlevideo.com:443 - HIER_DIRECT/rr2---sn-gvnuxaxjvh-c35d.googlevideo.com -
27/Oct/2024:15:15:22 +0300   5257 127.0.0.1 TCP_TUNNEL/200 11474 CONNECT manifest.googlevideo.com:443 - HIER_DIRECT/manifest.googlevideo.com -
27/Oct/2024:15:15:22 +0300  42583 127.0.0.1 TCP_TUNNEL/200 117509 CONNECT www.youtube.com:443 - HIER_DIRECT/www.youtube.com -
27/Oct/2024:15:15:22 +0300  42722 127.0.0.1 TCP_TUNNEL/200 8887 CONNECT youtube.com:443 - HIER_DIRECT/youtube.com -
```

Правда придётся видимо следить за его актуальностью

**Comment by ppetbox** [comment]
@bol-van:
> Каким ASN принадлежат адреса blablabla.googlevideo.com ?

AS42610 
address:        National Cable Networks
address:        Nagatinskaya str., 1, bldn. 26
address:        117105 Moscow, Russia

Но там не все домены этой зоны.  manifest.googlevideo.com - это уже гугловый ASN

**Comment by bol-van** [comment]
Понятно, поэтому и лист с ходу не работает.

**Comment by ppetbox** [comment]
@bol-van:
>  Методом тыка на одном из провов дошел до следующего варианта

Из моего списка там три записи и это не GGC это как раз гугловый ASN доменов youtube.com, www.youtube.com и  manifest.googlevideo.com. А собственно видео кэш это 77.37.192.0/18 которого в этом списке и нет.

**Comment by ppetbox** [comment]
@bol-van:
> Методом тыка на одном из провов дошел до следующего варианта

А скрипты включают результаты этого метода, или там только то что приходит от внешних ресурсов?

**Comment by bol-van** [comment]
Это только частный случай, выявленный по многочисленным просмотрам видео с трубы
нигде не отражено

**Comment by ppetbox** [comment]
То есть чем дальше в лес тем больше дров - ipset это болото в котором можно утонуть посвятив ему всю свою жизнь. Гонятся  за айпишниками - это проклятие. Эта альтернатива hostlist не от хорошей жизни.

**Comment by bol-van** [comment]
В случае трубы и ситуевины с ней в России - да

**Comment by ppetbox** [comment]
И к стати этот мой супер кортокий список как оказалось работает с перебоями, пришлось вернуться к длинному, к сборной солянке: get_user.sh + AS15169 + 77.37.192.0/18 (GGC). Но видимо и это не последняя остановка и эксперименты придётся продолжить.

**Comment by ppetbox** [comment]
И ещё всё забываю спросить: у меня есть предположение что get_reestr_resolve.sh может дать более актуальный список чем get_reestr_preresolved.sh Так ли это?

**Comment by bol-van** [comment]
preresolved - это моя поделка.
Каждые 2 дня выполняется тоже самое, что в get_reestr_resolved , и выливается на github.
Так что разницы никакой. Только свою систему нагружать на час.

**Comment by bol-van** [comment]
Еще момент, который, возможно, упустили.
GGC могут требовать для пробития гугловский фейк и неоднократные repeats.
в blockcheck их можно подсунуть через переменную PKTWS_EXTRA

> У меня Ютуб заработал. Помогло изменения одной строчки. Нашёл тут, в закрытых ишью.
> 
> Было:
> --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6
> Стало:
> --filter-udp=443 --dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --dpi-desync-repeats=6

**Comment by ppetbox** [comment]
TLS не работает, quic не проверял - он мне не нужен. Не работает в смысле  не только YouTube, а и всё остальное, то есть вся сеть сломана напрочь.

**Comment by ppetbox** [comment]
`NFQWS_OPT="--filter-tcp=443 --dpi-desync=syndata,fake --dpi-desync-ttl=4 --dpi-desync-fooling=md5sig <HOSTLIST>"`

Это рабочая конфигурация при условии что я использовал предлагаемый install_easy.sh по умолчанию скрипт get_*.

**Comment by ppetbox** [comment]
Чего то git pull ругается: "You have divergent branches". С чего бы это? Я ж его не трогал.

**Comment by ppetbox** [comment]
```
commit f2f9451777197613e4b71514dd4d3ff2937d36fa (HEAD -> master)
Author: bol-van <none@none.none>
Date:   Sun Oct 27 19:14:23 2024 +0300

    blockcheck: restrict fooling only to domain's IPs
```
И после этого git не трогал, впрочем как и до этого.

**Comment by ppetbox** [comment]
Но счастье было не долгим: без объявления войны YouTube и proton перестали работать. Как и с git пока они работали я ничего не трогал. Подозрительное совпадение.

**Comment by ppetbox** [comment]
Реанимировал YouTube - причина была в списке: добавил этот свой магический список из четырёх записей и YouTube заработал.

**Comment by bol-van** [comment]
git надо перекачать заново, делал там чистку от истории

**Comment by ppetbox** [comment]
youtube постоянно мутирует. На сей раз пришлось подстраивать конфиг:

`--filter-tcp=443 --dpi-desync=syndata,fake,split --dpi-desync-ttl=2 --dpi-desync-fooling=badsum`

Весёлая жизнь. И вечный тюнинг, покой нам только снится. С hostlist было поспокойней пока тема syndata не возникла.

**Comment by bol-van** [comment]
Отдельный инстанс с перенаправлением через фаервол по ipset.
В винде параметр --ipset winws. В *nix он запрещен

**Comment by ppetbox** [comment]
То есть `--new --ipset=` работать не будет?

**Comment by bol-van** [comment]
Если руками запустить - будет. Скрипты запуска отлавливают этот параметр и запрещают его использование.
Чтобы не было копипасты с простыми, но дурными решениями

**Comment by ppetbox** [comment]
Тогда, если запускать руками, отдельный инстас не нужен? Ну если оба профиля можно объединеть в одном интсансе:

`/opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --user=tpws --dpi-desync-fwmark=0x40000000 --filter-tcp=443 --dpi-desync=fake --dpi-desync-ttl=2 --dpi-desync-fooling=badsum --new --ipset=/opt/zapter/ipset/ip-syndata.txt --dpi-desync=syndata --dpi-desync-ttl=2 --dpi-desync-fooling=badsum`

Или для второго профиля нужен ещё свой фильтр?

**Comment by ppetbox** [comment]
Или если без фильтра то просто поменять профили местами

**Comment by bol-van** [comment]
Специализация должна идти вперед, иначе до нее дело не дойдет.

**Comment by ppetbox** [comment]
Но этого не достаточно, как я понял table inet zapret тоже придётся создавать руками.

**Comment by ppetbox** [comment]
Кроме того --filter-tcp=443 заберёт весь этот трафик и до второго профиля дело не дойдёт

**Comment by ppetbox** [comment]
Ну вот попробоал:

`/opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --user=tpws --dpi-desync-fwmark=0x40000000  --filter-tcp=443 --dpi-desync=fake --dpi-desync-ttl=2 --new --ipset=/opt/zapret/ipset/ip-syndata.txt --dpi-desync=syndata`

**Comment by bol-van** [comment]
Так не будет работать. До 2 профиля дело не дойдет по 443 порту
syndata надо вперед
и туда же еще раз продублировать filter 443

**Comment by ppetbox** [comment]
А как эти два профиля поделят между собой трафик если у них фильтры одинаковы? По какому признаку? И зачем в первом профиле fake, если он для ggc не нужен?

**Comment by ppetbox** [comment]
Может добаваить --ipset для второго профиля?

**Comment by ppetbox** [comment]
запрос на youtube проходит четрые сайта - манифест это предпоследний перед видео, которое уже идёт из ggc

**Comment by ppetbox** [comment]
`/opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --filter-tcp=443 --dpi-desync=syndata,fake --dpi-desync-ttl=2 `

Это то что у меня работает через конфиг, то есть со стандартными скриптами systemd

**Comment by bol-van** [comment]
Предложенный мной вариант оставляет syndata лишь для списка IP, остальное - по-старому

**Comment by ppetbox** [comment]
Тогда не понятно почему не работает. В таблице ggc есть:

```
nft list table inet zapret | grep 77.37.192.0/18
                             77.37.192.0/18, 77.66.18.0/24,
```

**Comment by bol-van** [comment]
А причем здесь nft ?
--ipset - это USER MODE ipset, реализуемый средствами nfqws/tpws
Поэтому я и против его использования на linux, где есть поддержка iptables или nftables
С nft надо было отдельный инстанс nfqws пускать с другой очередью и писать отдельное правило queue.

**Comment by ppetbox** [comment]
Привильно ли я понимаю, что второй профиль по умолчанию подразумевает:

`--ipset=/opt/zapret/ipset/zapret-ip.txt`

И поэтому его добавлять не надо?

**Comment by bol-van** [comment]
По умолчанию никакие ipset не подразумеваются
Но поиск профиля происходит слева направо до первого совпадения и дальше не идет.
Потому если на 1 профиле ipset, то он заберет на себя все IP из списка, а остальные пойдут на следующий

**Comment by ppetbox** [comment]
Тогда тем более не понятно почему не работает. Возможно причина - в списке, но я добавил туда всё что нужно youtube (эти самые четрые сети) но и это не помогает.

**Comment by bol-van** [comment]
Откуда правила tables ? Свои или от скриптов zapret ?

**Comment by ppetbox** [comment]
от скриптов zapret.  Может быть для user mode эту таблицу вообще удалить?

**Comment by ppetbox** [comment]
Или по крайней мере убрать из неё список?

**Comment by ppetbox** [comment]
Я просто останавливал:

`systemctl stop zapret.service`

а потом запускал из коммандной строки

**Comment by bol-van** [comment]
Если делать руками, то все надо. И таблес, и запуск nfqws.
Мешать это, чтобы обойти запрет на --ipset, не вариант

**Comment by bol-van** [comment]
> Я просто останавливал:
> 
> `systemctl stop zapret.service`
> 
> а потом запускал из коммандной строки

После этого не останется правил. nfqws не будет работать просто так без правил

**Comment by ppetbox** [comment]
Вобщем надо трудится, что бы посторить коммунизм. Вот пока оно как то работает, но не всё и не стабильно. А что бы изолирать эту syndata нужно экспериментировать.

**Comment by bol-van** [comment]
Чтобы изолировать, надо взять 50-discord и немного переписать под себя

**Comment by ppetbox** [comment]
@bol-van:
> Когда работатет только syndata, чаще всего это является следствием включенности ускорения в настройках прошивки. Он же offload.

Если я правильно понял, речь идет об openwrt. Но у меня другая железка. Корме того в настройках всегда было FLOWOFFLOAD=none. Так что в любом случае этот факотр не играет роли.

**Comment by ppetbox** [comment]
В общем сделал я этот custom - вроде бы работает, но как то не стабильно.  Но и без него стабильности не было. Буду продолжать эксперименты, но это уже будет типа тюнинг. А так принципально задача решена, так что наверно можно закрывать тему. Хотя честно говоря решение не очень удобное, мяго говоря. Идельным было бы конечено hostlist с двумая профилями, каждый со своим списком, что бы без custom и без огромных ipset-ов.
