### ISSUE TITLE
Как обойти блокировку твиттер?

### ISSUE THREAD

**Issue by DownEr228** [bol-van/zapret#645]
Я буквально абсолютно не знаю как, обыскал везде, не нашел..

**Comment by HentayHentay** [comment]
> Я буквально абсолютно не знаю как, обыскал везде, не нашел..

От провайдера к провайдеру наблюдается то или иное ограничение. Искать в интернете решение своей проблемы ни к чему хорошему не приведёт. 
Решение:  Найти домены твиттера и внести их в файл/скопировать и прогнать их через блокчекер . Выявленные стратегии обхода внести в конфиг запрета, не забывая обновить у себя список доменов (добавить хосты твиттера) 

Данная программа не является однокнопочной.

**Comment by fr-esa** [comment]
--dpi-desync=fake,disorder 
    --dpi-desync-ttl=4 
пробуйте

**Comment by NewUse** [comment]
blockcheck прогоните при выключенном запрете

**Comment by BuIlDaLiBlE** [comment]
Это и правда от провайдера зависит - у меня, например, идёт блок по IP и тут кроме как использования прокси/VPN по-другому блокировку не обойти.

**Comment by Wippito** [comment]
> ```
> --dpi-desync=fake,disorder 
> --dpi-desync-ttl=4 
> ```
> 
> пробуйте

это только для твиттера работает? для chess.com сработает?

**Comment by HentayHentay** [comment]
> это только для твиттера работает? для chess.com сработает?

> blockcheck прогоните при выключенном запрете


Не предполагал, что столько любителей "копипастии".

**Comment by Wippito** [comment]
> > это только для твиттера работает? для chess.com сработает?
> 
> > blockcheck прогоните при выключенном запрете
> 
> Не предполагал, что столько любителей "копипастии". Хотим проблем , берём "не проверенную" стратегию обмана...

я ничего не понял из ответа, но даже не это меня в себе разочаровало, а то, что chess.com, оказывается, работает в другом браузере. чтож, видимо это совпадение, что в хроме он перестал работать сразу после установки запрета, но в любом случае, копаться в конфигах мне больше не нужно, спасибо)
