### ISSUE TITLE
Замедление GitHub-а и cache.nixos.org

### ISSUE THREAD

**Issue by DADA30000** [bol-van/zapret#646]
Возможно они были задеты блокировкой или замедлением чего либо другого, но факт остаётся фактом, скорость скачивание с гитхаба или при обновлении моей системы с cache.nixos.org очень низкая, вот пример
```
❯ time curl https://cache.nixos.org/nar/00gq5dxn728g6557w3jrs39mn43q709jsasd363wgy9fg8rcisgi.nar.xz > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8187k  100 8187k    0     0  82006      0  0:01:42  0:01:42 --:--:-- 32051
curl  > /dev/null  0,35s user 0,25s system 0% cpu 1:42,26 total
```
у знакомого в Краснодаре команда выполнилась за 1 секунду, так же различные файлы с гитхаба скачивает со скоростью максимум 200 кб в секунду
Кто нибудь сталкивался с подобным? И нашёл ли решение?

**Comment by bol-van** [comment]
На 2 провайдерах норм.
Может какой-то канал приуныл ? Такое бывает

**Comment by DADA30000** [comment]
> На 2 провайдерах норм. Может какой-то канал приуныл ? Такое бывает сделайте mtr. может где-то лосс или пинг по 300 мс

Я глупенький, можно поподробнее что за mtr :)

**Comment by DADA30000** [comment]
вот результаты 
![image](https://github.com/user-attachments/assets/ec35c574-b7a0-469d-8800-a2e8cb445825)
![image](https://github.com/user-attachments/assets/b3aa5860-7343-4185-9aae-a4ca221dbf76)
![image](https://github.com/user-attachments/assets/8702a2d7-257e-4c38-9989-190fa42be503)

**Comment by bol-van** [comment]
А что вы хотели с 57% потерей пакетов ? Спасибо, что хоть что-то качается

**Comment by bol-van** [comment]
ТСПУ иногда ставят прямо на первый хоп, но такое бывает достаточно редко, так что винить РКН сходу нельзя.
На первом скрине потери начинаются прямо со шлюза провайдера. Но на другим направлениях потери приемлемые
Может это временное явление или плохая связь с провайдером ?

**Comment by DADA30000** [comment]
> ТСПУ иногда ставят прямо на первый хоп, но такое бывает достаточно редко, так что винить РКН сходу нельзя. На первом скрине потери начинаются прямо со шлюза провайдера. Но на других направлениях потери приемлемые Может это временное явление или плохая связь с провайдером ?

Надеюсь что временные, но подозреваю что придётся менять провайдера, но всё равно спасибо что откликнулись :D
