### ISSUE TITLE
nfqws считает `--ipset` плохой опцией

### ISSUE THREAD

**Issue by xbt573** [bol-van/zapret#653]
Пытаюсь прикрутить следующую стратегию:
```
--filter-udp=50000-50099 --ipset=/opt/zapret/ipset/zapret-ip-user-discord.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=n2 --new
```
На что nfqws выдаёт мне `!!! REFUSING TO USE BAD OPTIONS :`, методом исключения было найдено, что проблемная опция именно `--ipset`, проваливается вне зависимости от файла

Операционная система: Linux (Fedora Linux 40)
Саму стратегию стянул с виндового батника в `binaries/win64/zapret-winws`

**Comment by bol-van** [comment]
Это специально сделано, чтобы вы так не делали. Искусственно и намеренно.
Для дискорда есть готовый custom script

**Comment by xbt573** [comment]
Скрипт видел, но хотел разобраться в чём именно проблема с `--ipset`, вдруг мне придётся делать стратегию не для дискорда а чего-то другого, даже если не мне то другим людям будет проще найти.

**Comment by bol-van** [comment]
На unix системах есть тоже самое в ядре.
Я хотел запретить упрощать себе жизнь в ущерб производительности

**Comment by xbt573** [comment]
Хорошо, а возможно ли использовать функционал тех же ядерных списков не используя custom скрипты? Или это единственный вариант? Принимая всю ту же необходимость когда-то и кому-то сделать обход для чего-то, но не имеющего возможности сделать это custom скриптом.

Я посмотрел на пример с дискордом и он выглядит довольно тяжело (может быть это я ничего не знаю), особенно из-за того что единственная документация это комментарии в коде и он сам.

**Comment by bol-van** [comment]
> Хорошо, а возможно ли использовать функционал тех же ядерных списков (в пределах конфигов zapret) не используя custom скрипты?

В них можно использовать только стандартный режим фильтрации по MODE_FILTER=ipset
Дополнительные сеты только через кастомы. См пример в 50-discord

В доке кое-что написано про кастомы. См "вариант custom"

**Comment by pspirichev** [comment]
Доброго дня @bol-van и не сочтите за дерзость, но было бы очень приятно видеть в таком случае указание в логах, на то что скрипту не нравится именно --ipset, а не только абстрактное `!!! REFUSING TO USE BAD OPTIONS :` поскольку как писал автор оригинального issue подобрать, что именно не нравиться скрипту, можно только методом тыка.

**Comment by bol-van** [comment]
Согласен. Сделано
