### ISSUE TITLE
Не создались правила firewall на openwrt 14.07

### ISSUE THREAD

**Issue by vnt-83** [bol-van/zapret#655]
Установил согласно `manual_setup.txt`

При этом автоинсталятор бинариков правильно определил архитектуру:
```
root@OpenWrt:/opt# /opt/zapret/install_bin.sh
x86_64 is NOT OK
x86 is NOT OK
aarch64 is NOT OK
arm is NOT OK
mips64r2-msb is NOT OK
mips32r1-lsb is NOT OK
mips32r1-msb is OK
installing binaries ...
linking : ../binaries/mips32r1-msb/ip2net => /opt/zapret/ip2net
linking : ../binaries/mips32r1-msb/mdig => /opt/zapret/mdig
linking : ../binaries/mips32r1-msb/nfqws => /opt/zapret/nfq
linking : ../binaries/mips32r1-msb/tpws => /opt/zapret/tpws
root@OpenWrt:/opt#
```

В файле `/opt/zapret/config` прописал:
```
FWTYPE=iptables
POSTNAT=1
TPWS_SOCKS_ENABLE=1
TPWS_ENABLE=1
NFQWS_ENABLE=1
MODE_FILTER=none          # так и было
FLOWOFFLOAD=donttouch     # так и было
```
Остальное не трогал, полный файл приложил (переименовал в txt, иначе не грузился)

На последнем этапе "Посмотреть появились ли нужные правила." обнаружил, что новые правила не появились. После перезагрузки роутера тоже не появились.

При этом есть запущенные процессы:
```
root@OpenWrt:~# ps | grep zapret
 1225 daemon     576 S    /opt/zapret/tpws/tpws --user=daemon --bind-addr=127.0.0.127 --port=988 --filter-tcp=80 --methodeol --new --filter-tcp=443 --split-tls=sni --disorder
 1226 daemon     984 S    /opt/zapret/tpws/tpws --user=daemon --socks --bind-addr=127.0.0.1 --bind-iface4=br-lan --bind-wait-ifup=30 --bind-wait-ip=30 --port=987 --filter-tcp=80 --methodeol --new --filter-tcp=443 --split-tls=sni --disorder
 1227 21474836   748 S    /opt/zapret/nfq/nfqws --qnum=200 --filter-tcp=80 --dpi-desync=fake split2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --dpi-desync=fake disorder2 --dpi-desync-fooling=md5sig --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6
 2383 root      1356 S    grep zapret
root@OpenWrt:~#
```

Железка: `MikroTik RouterBOARD 751` https://mikrotik.com/product/RB751U-2HnD
Прошивка: `OpenWrt Barrier Breaker 14.07`
Память:
```
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                  124.0M     31.3M     92.7M  25% /
/dev/root               124.0M     31.3M     92.7M  25% /
tmpfs                    14.1M    592.0K     13.5M   4% /tmp
tmpfs                   512.0K         0    512.0K   0% /dev
root@OpenWrt:~#
root@OpenWrt:~#
root@OpenWrt:~# free -m
             total         used         free       shared      buffers
Mem:         28896        25284         3612            0            0
-/+ buffers:              25284         3612
Swap:            0            0            0
root@OpenWrt:~#
```

zapret скачал последней версии v66

После всех манипуляций ютуб не заработал (страница загружается, а ролики нет). 

Подскажите куда копать, где смотреть?

[config.txt](https://github.com/user-attachments/files/17535041/config.txt)

**Comment by bol-van** [comment]
Даже разбираться не хочется в таком старье. Я понимаю если бы лексра была.
Но :
https://openwrt.org/toh/hwdata/mikrotik/mikrotik_rb751u-2hnd
Supported Current Rel:
    19.07.10

**Comment by vnt-83** [comment]
Это может быть сязано со старой версией curl?

```
root@OpenWrt:/opt# /opt/zapret/blockcheck.sh
* checking system
Linux detected
firewall type is iptables
* checking already running zapret processes
* checking privileges
* checking prerequisites
* checking DNS
system DNS is working
comparing system resolver to public DNS : 8.8.8.8
pornhub.com : OK
ntc.party : OK
rutracker.org : OK
www.torproject.org : OK
bbc.com : OK
checking resolved IP uniqueness for : pornhub.com ntc.party rutracker.org www.torproject.org bbc.com
censor's DNS can return equal result for multiple blocked domains.
all resolved IPs are unique
-- DNS looks good
-- NOTE this check is Russia targeted. In your country other domains may be blocked.
* checking virtualization
cannot detect

NOTE ! this test should be run with zapret or any other bypass software disabled, without VPN

installed curl does not support --connect-to option. pls install at least curl 7.49
current curl version:
curl 7.38.0 (mips-openwrt-linux-gnu) libcurl/7.38.0 PolarSSL/1.3.9
Protocols: file ftp ftps http https
Features: IPv6 Largefile SSL

press enter to continue

root@OpenWrt:/opt#
```

Хотя перечисленные выше сайты и правда работают.

**Comment by vnt-83** [comment]
> Даже разбираться не хочется в таком старье. Я понимаю если бы лексра была. Но : https://openwrt.org/toh/hwdata/mikrotik/mikrotik_rb751u-2hnd Supported Current Rel: 19.07.10

Понял, попробую.

**Comment by bol-van** [comment]
Версии ниже 17 вряд ли будут работать нормально. На 19 точно работает. есть железяки, которые discontinued на 19

**Comment by vnt-83** [comment]
> 32 mb ram - это уже проблема само по себе
Ого, я думал это нормально. А сколько желательно?

**Comment by bol-van** [comment]
32 - это конфа на гране вылетов. Но можно попробовать zapret без листов или только с небольшими своими листами.
Что-то удобоваримое начинается с 64, а лучше с 128

**Comment by vnt-83** [comment]
Понял, спасибо

**Comment by vnt-83** [comment]
Напишу для тех, у кого тоже OpenWrt 14.07

У меня Ютуб заработал. Помогло изменения одной строчки. Нашёл тут, в закрытых ишью.

Было:
`--filter-udp=443 --dpi-desync=fake  --dpi-desync-repeats=6`
Стало:
`--filter-udp=443 --dpi-desync=fake  --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --dpi-desync-repeats=6`

Заработало и на компе и в приложении на смартфонах.

Подумал, раз заработал рутрекер без VPN, значит система работает. Решил попробовать подобрать стратегию и всё получилось.

Кстати, ставить было напряжно. В этой версии openwrt wget не умеет в https - из-за этого не установить пакеты нормально. Пришлось руками качать пакеты с зависимостями, перекидывать на роутер и ставить из файлов. Это если кто-то столкнётся.

@bol-van выражаю огромную благодарность!

Обязательно прочту весь хелп, т.к. судя по всему zapret умеет гораздо больше, чем разблокировать ютуб.

За рутрекер без VPN отдельная благодарность!

**Comment by vnt-83** [comment]
Кстати, как я понял, 32МБ это минимум для последней версии openwrt. У меня расход памяти не изменился, остался на уровне последних 10 лет.

Вот, нагрузка системы при просмотре ролика:

![Снимок экрана 2024-10-28 023554](https://github.com/user-attachments/assets/08273c02-5629-407b-8f60-490cdc3a407d)

**Comment by bol-van** [comment]
Для последних версий реальный юзабельный минимум - 64.
https://openwrt.org/supported_devices/432_warning
