### ISSUE TITLE
Не обрабатывает трафик non direct connected

### ISSUE THREAD

**Issue by wildarp** [bol-van/zapret#656]
Пытаюсь запустить zapret на Linux
все запустил поставил vpn , все завелось работает
Но мне нужно пропустить весь трафик через zapret тот что прилетает с vlan14 (non direct connected) и сделать nat на IP (vlan15)
rp.filter=2
Все сделал трафик проходит, NAT есть, но youtube не заводиться именно для трафика который  пролетает с vlan14 на vlan15 .
Direct connected (wireguard) )работает отлично. в чем может быть проблема?

**Comment by bol-van** [comment]
tpws цепляется на IFACE_LAN, nfqws - на IFACE_WAN
Для tpws важен только входящий интерфейс, для nfqws - исходящий.
Если надо сделать, чтобы через nfqws проходили только  пакеты, переправленные с определенного входящего интерфейса, на nftables это можно сделать через маркировку и хук скрипты.
На iptables в текущей схеме это затруднено.

Но всегда можно выкинуть скрипты запуска и написать все таблес самому.

**Comment by wildarp** [comment]
Понял спасибо, попробуем
