### ISSUE TITLE
Не разблокирует Youtube

### ISSUE THREAD

**Issue by n13wolf** [bol-van/zapret#657]
Со вчерашнего дня (28.10) не разблокирует Youtube ни в одной из кнопок ( Билайн, Windows 10). Однако это  делает GDPI goodbyedpi-0.2.3rc3-2  - 1_russia_blacklist_YOUTUBE  или 1_russia_blacklist_YOUTUBE_ALT

**Comment by bol-van** [comment]
По сборкам все вопросы к сборщикам.
У оригинального zapret нет кнопок

**Comment by viktoriaLukyanova** [comment]
Друзья, выручайте. Поставил zapret на роутер с openwrt. Перепробовав 1000 стратегий для YT, нашел, которая работает (discord тоже работает с custom). Но работает на смартфонах (iphone, android), на win в браузерах кроме Яндекса (флаги одинаковые) и самое главное не работает на android TV.
Вот стратегии:
NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig <HOSTLIST> --new 
--filter-tcp=443 --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin <HOSTLIST> --new 
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin <HOSTLIST> --new 
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new --dpi-desync=fake,disorder2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig <HOSTLIST>"

blockcheck выдает: ipv4 rr5---sn-c0q7lns7.googlevideo.com curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=1
Провайдер МТС. Пробовал ttl менять, но не вышло. Что за магия, как ее победить? Я знаю, что я где то близко

**Comment by eastone11** [comment]
> Друзья, выручайте. Поставил zapret на роутер с openwrt. Перепробовав 1000 стратегий для YT, нашел, которая работает (discord тоже работает с custom). Но работает на смартфонах (iphone, android), на win в браузерах кроме Яндекса (флаги одинаковые) и самое главное не работает на android TV (пишет "Нет подключения к Интернету"). Вот стратегии: NFQWS_OPT=" --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new --dpi-desync=fake,disorder2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig "
> 
> blockcheck выдает: ipv4 rr5---sn-c0q7lns7.googlevideo.com curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=1 Провайдер МТС. Пробовал ttl менять, но не вышло. Что за магия, как ее победить? Я знаю, что я где то близко

послед строка для udp врядли работает тк ```
Для UDP действуют только режимы десинхронизации fake,hopbyhop,destopt,ipfrag1,ipfrag2,udplen,tamper.
Возможно сочетание fake,hopbyhop,destopt с ipfrag2, fake,fakeknown с udplen и tamper.
```

в целом попробуй дебаг, может что будет понятно

**Comment by viktoriaLukyanova** [comment]
> > Друзья, выручайте. Поставил zapret на роутер с openwrt. Перепробовав 1000 стратегий для YT, нашел, которая работает (discord тоже работает с custom). Но работает на смартфонах (iphone, android), на win в браузерах кроме Яндекса (флаги одинаковые) и самое главное не работает на android TV (пишет "Нет подключения к Интернету"). Вот стратегии: NFQWS_OPT=" --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new --dpi-desync=fake,disorder2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig "
> > blockcheck выдает: ipv4 rr5---sn-c0q7lns7.googlevideo.com curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=1 Провайдер МТС. Пробовал ttl менять, но не вышло. Что за магия, как ее победить? Я знаю, что я где то близко
> 
> послед строка для udp врядли работает тк ``` в целом попробуй дебаг, может что будет понятно
> 
> ```
> Для UDP действуют только режимы десинхронизации fake,hopbyhop,destopt,ipfrag1,ipfrag2,udplen,tamper.
> Возможно сочетание fake,hopbyhop,destopt с ipfrag2, fake,fakeknown с udplen и tamper.
> ```

NFQWS_OPT="
--debug --filter-tcp=80...
Так? Не могу найти syslog

**Comment by eastone11** [comment]
> NFQWS_OPT=" --debug --filter-tcp=80... Так? Не могу найти syslog

можно в файл --filter-tcp=80 --debug=@opt/zapret/log.txt --страта
по каждому фильтру свой дебаг надо либо понять\знать через что приставка работает либо делать на каждом (вроде так)

**Comment by viktoriaLukyanova** [comment]
> > NFQWS_OPT=" --debug --filter-tcp=80... Так? Не могу найти syslog
> 
> можно в файл --filter-tcp=80 --debug=@/opt/zapret/log.txt --страта по каждому фильтру свой дебаг надо либо понять\знать через что приставка работает либо делать на каждом (вроде так)

--filter-tcp=80 : Пусто
--filter-tcp=443 : read 652 bytes from /opt/zapret/files/fake/tls_clienthello_www_google_com.bin
--filter-udp=443 : read 1200 bytes from /opt/zapret/files/fake/quic_initial_www_google_com.bin
--filter-udp=443 : `adding low-priority default empty desync profile
we have 5 user defined desync profile(s) and default low priority profile 0
Loading hostlist /opt/zapret/ipset/zapret-hosts-auto.txt
loading plain text list
Loaded 0 hosts from /opt/zapret/ipset/zapret-hosts-auto.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user.txt
loading plain text list
Loaded 78 hosts from /opt/zapret/ipset/zapret-hosts-user.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-auto.txt
loading plain text list
Loaded 0 hosts from /opt/zapret/ipset/zapret-hosts-auto.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user.txt
loading plain text list
Loaded 78 hosts from /opt/zapret/ipset/zapret-hosts-user.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-auto.txt
loading plain text list
Loaded 0 hosts from /opt/zapret/ipset/zapret-hosts-auto.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user.txt
loading plain text list
Loaded 78 hosts from /opt/zapret/ipset/zapret-hosts-user.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-auto.txt
loading plain text list
Loaded 0 hosts from /opt/zapret/ipset/zapret-hosts-auto.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user.txt
loading plain text list
Loaded 78 hosts from /opt/zapret/ipset/zapret-hosts-user.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user-exclude.txt
loading plain text list
Loaded 6 hosts from /opt/zapret/ipset/zapret-hosts-user-exclude.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user-exclude.txt
loading plain text list
Loaded 6 hosts from /opt/zapret/ipset/zapret-hosts-user-exclude.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user-exclude.txt
loading plain text list
Loaded 6 hosts from /opt/zapret/ipset/zapret-hosts-user-exclude.txt
Loading hostlist /opt/zapret/ipset/zapret-hosts-user-exclude.txt
loading plain text list
Loaded 6 hosts from /opt/zapret/ipset/zapret-hosts-user-exclude.txt
initializing conntrack with timeouts tcp=60:300:60 udp=60
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding this socket to queue '200'
setting copy_packet mode
initializing raw sockets bind-fix4=0 bind-fix6=0
set_socket_buffers fd=8 rcvbuf=2048 sndbuf=32768
fd=8 SO_RCVBUF=4096
fd=8 SO_SNDBUF=65536
set_socket_buffers fd=9 rcvbuf=2048 sndbuf=32768
fd=9 SO_RCVBUF=4096
fd=9 SO_SNDBUF=65536
`
Что то понятно?

**Comment by andmt1** [comment]
DoH или DoT настроены? 
как оказалось. на нешифрованных DNS ютуб вообще не работает. А вот с настроенным DoH всё грузится и на ТВ и на андроид, т.е. где видео идет по протоколу QUIC даже с самым простым конфигом:--dpi-desync=fake --dpi-desync-repeats=15

**Comment by HentayHentay** [comment]
> -dpi-desync-repeats=15

Самый простой конфиг .. супер конфиг
