### ISSUE TITLE
Не работают звонки в дискорде. Вечный RTC Connecting.

### ISSUE THREAD

**Issue by wildburn** [bol-van/zapret#658]
Пытаюсь подключиться в дискорде к голосовому каналу, но безуспешно. Вечный RTC Connecting, потом красным показывает No Route и так по кругу. Пару-тройку дней назад все хорошо работало без нареканий. Бывает фиксится в 1 разе из 10 перезагрузкой, но это лишь иногда. Очень странно. Может кто сталкивался? Еще если впн врубить от WireGuard и потом выключить, то тоже невозможно подключиться по запрету.
![image](https://github.com/user-attachments/assets/3e78ed71-2425-4156-97f1-8adc8ba4ba0c)
![image](https://github.com/user-attachments/assets/f6f1d1f6-885e-4930-88d3-a468735cfeec)

**Comment by eastone11** [comment]
через скрипт, тут посмотри https://github.com/bol-van/zapret/issues/650

**Comment by wildburn** [comment]
На ПК стоит Adguard и после последнего обновления оказывается нельзя подключиться к войсам через запрет. Убрал Дискорд из фильтрации и заработало
