### ISSUE TITLE
Дамы и господа, нужны новые костыли на ютуб

### ISSUE THREAD

**Issue by ThisIsNoTa2acc** [bol-van/zapret#659]
Перестало работать
```
QUIC_PORTS=443-444,50000-65535
# CHOOSE NFQWS DAEMON OPTIONS for DPI desync mode. run "nfq/nfqws --help" for option list
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-split-pos=1 --dpi-desync-autottl=1:1-8 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=10 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin" 
#NFQWS_OPT_DESYNC_HTTP=
#NFQWS_OPT_DESYNC_HTTPS=
#NFQWS_OPT_DESYNC_HTTP6=
#NFQWS_OPT_DESYNC_HTTPS6=
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,split2 --dpi-desync-repeats=10 --dpi-desync-autottl=1:1-8 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"
#NFQWS_OPT_DESYNC_QUIC6=
NFQWS_OPT_DESYNC_QUIC_SUFFIX="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
```

**Comment by ThisIsNoTa2acc** [comment]
Как вернусь домой может быть попробую краказябру выше так же в suffix вставить и посмотреть что будет

**Comment by eastone11** [comment]
трешачок
используй блокчек для нахождения нормальный стратегий

**Comment by HentayHentay** [comment]
> QUIC_PORTS=443-444,50000-65535

1 - На сколько помню, данная опция существует для переназначения протокола. Если данный протокол определяется нормально, то лучше отключить это(установить перед `#`). А то мы ищем quic в диапазоне, где его нет(50000-655535). Для дискорда есть custom под названием 50-discord.
2 - Так-же для поиска стратегии нормальной нужно отловить в браузере рабочий *.googlevideo.com и после чего его пропустить через блокчек.  При работе блокчека запрет и его аналоги нужно отключить
3 - Стратегия основана на `NFQWS_OPT_DESYNC=` применяется на всех протоколах. Если не указано иного. Проще найти нормальную стратегию через блокчекер.(На HTTP/HTTPS/QUIC)

**Comment by HentayHentay** [comment]
> Кастомка дискорда

Потому что мы тут упираемся уже в фильтр, выставленный в запрете.  В зависимости от фильтра, нужно внести адреса дискорда (хосты). Дискорд использует UDP порты. Проблема в том, что протоколы там разные.



> а blockcheck трайну

~ 30 минут )

**Comment by ThisIsNoTa2acc** [comment]
> > Кастомка дискорда
> 
> Потому что мы тут упираемся уже в фильтр, выставленный в запрете. В зависимости от фильтра, нужно внести адреса дискорда (хосты). Дискорд использует UDP порты. Проблема в том, что протоколы там разные.
> 
> > а blockcheck трайну
> 
> ~ 30 минут )

кароче говоря blockcheck мне ставит ```MODE=tpws
MODE_QUIC=0
MODE_FILTER=none``` ни один из этих 3 параметров мне не нравится. Сейчас вроде старый конфиг опять заработал, видать реально по часам конфигурация меняется dpi железа, если опять перестанет работать то уже буду чесать репу

**Comment by ThisIsNoTa2acc** [comment]
кароче говоря стратегии blockcheck не работает от слова совсем

**Comment by ThisIsNoTa2acc** [comment]
> Как вернусь домой может быть попробую краказябру выше так же в suffix вставить и посмотреть что будет

сработало
```
# CHOOSE NFQWS DAEMON OPTIONS for DPI desync mode. run "nfq/nfqws --help" for option list
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-split-pos=1 --dpi-desync-autottl=1:1-8 --dpi-desync-fooling=md5sig,badsum --dpi-desync-repeats=10 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin" 
#NFQWS_OPT_DESYNC_HTTP=
#NFQWS_OPT_DESYNC_HTTPS=
#NFQWS_OPT_DESYNC_HTTP6=
#NFQWS_OPT_DESYNC_HTTPS6=
NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,split2 --dpi-desync-repeats=10 --dpi-desync-autottl=1:1-8 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"
#NFQWS_OPT_DESYNC_QUIC6=
#NFQWS_OPT_DESYNC_QUIC_SUFFIX="--dpi-desync=fake,tamper --dpi-desync-any-protocol"
NFQWS_OPT_DESYNC_QUIC_SUFFIX="--dpi-desync=fake,split2 --dpi-desync-repeats=10 --dpi-desync-autottl=1:1-8 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"
```
