### ISSUE TITLE
Лицензия проекта

### ISSUE THREAD

**Issue by etozhecyber** [bol-van/zapret#66]
Какая лицензия у проекта? Не могли бы вы добавить файл LICENSE в репозиторий?

**Comment by bol-van** [comment]
Нет никакой лицензии. Do whatever you want.
Кроме преследования проекта и иного причинения вреда

**Comment by etozhecyber** [comment]
По твоему описанию подошла бы лицензия MIT. 

Полный ассортимент можно посмотреть тут: https://choosealicense.com/licenses/

Просто без лицензии непонятно могу ли я вносить правки, могу ли я собирать себе или кому-то ещё(распространять в бинарном виде)?

**Comment by bol-van** [comment]
Я точно не против. Это надо для отчетности ? В какой-то коммерческий проект ?

**Comment by etozhecyber** [comment]
Нее, просто хотел на выходных развлечься с github action и разобраться со сборкой пакетов ipkg для openwrt. Переживаю за протраченое время :)

**Comment by bol-van** [comment]
Добавил в docs
