### ISSUE TITLE
батник запрет дискорд сразу закрывается

### ISSUE THREAD

**Issue by FluorineF9** [bol-van/zapret#660]
Здрасте,при открытии батника он мелькает и сразу закрывается.
Закидывал в кмд ничего не происходило что мне делать я не знаю,уже собираюсь сносить винду.

**Comment by FluorineF9** [comment]
кстати когда другие батники открываю то все нормально

**Comment by bol-van** [comment]
Такого батника нет в оригинале. Если это сборка, то к сборщикам

**Comment by FluorineF9** [comment]
попробовал winws врубить в zapret 66 тоже самое

**Comment by bol-van** [comment]
Читаем docs/quick_start_windows.txt
