### ISSUE TITLE
проблема с установкой пакета iptables-mod-nfqueue на роутере Xiaomi AX6000

### ISSUE THREAD

**Issue by funnyshit** [bol-van/zapret#661]
Не находит пакет iptables-mod-nfqueue. Можно ли как-то завести на этом роутере на родной прошивке (OpenWRT туда не ставится, насколько я понял)? Пишут, что родная прошивка основана на OpenWRT

root@XiaoQiang:/opt/zapret# ./install_easy.sh
* checking system
system is based on openwrt
openwrt firewall uses fw3. flow offloading unavailable.
* checking executables
found architecture "aarch64"
* checking privileges
* checking location
running from /opt/zapret
* installing binaries
x86_64 is NOT OK
x86 is NOT OK
aarch64 is OK
installing binaries ...
linking : ../binaries/aarch64/ip2net => /opt/zapret/ip2net
linking : ../binaries/aarch64/mdig => /opt/zapret/mdig
linking : ../binaries/aarch64/nfqws => /opt/zapret/nfq
linking : ../binaries/aarch64/tpws => /opt/zapret/tpws
* checking DNS
system DNS is working
* checking virtualization
cannot detect
* stopping current firewall rules/daemons
Clearing nftables
/etc/rc.common: line 154: procd_running: not found

WARNING ! you are running a low RAM system
WARNING ! nft requires lots of RAM to load huge ip sets, much more than ipsets require
WARNING ! if you need large lists it may be necessary to fall back to iptables+ipset firewall
select firewall type :
1 : iptables
2 : nftables
your choice (default : nftables) : 1
selected : iptables

enable ipv6 support (default : N) (Y/N) ? n
* checking prerequisites
* installing prerequisites
Downloading http://downloads.openwrt.org/releases/18.06.9/targets/ipq/ipq50xx_64/packages/Packages.gz
wget: server returned error: HTTP/1.1 404 Not Found
*** Failed to download the package list from http://downloads.openwrt.org/releases/18.06.9/targets/ipq/ipq50xx_64/packages/Packages.gz

Downloading http://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading http://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading http://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading http://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/routing/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/releases/18.06.9/targets/ipq/ipq50xx_64/packages/Packages.gz, wget returned 1.
Package curl (7.60.0-4) installed in root is up to date.
Package ipset (6.38-1) installed in root is up to date.
Package iptables (1.6.2-2) installed in root is up to date.
Package iptables-mod-extra (1.6.2-2) installed in root is up to date.
Unknown package 'iptables-mod-nfqueue'.
Package iptables-mod-filter (1.6.2-2) installed in root is up to date.
Package iptables-mod-ipopt (1.6.2-2) installed in root is up to date.
Package iptables-mod-conntrack-extra (1.6.2-2) installed in root is up to date.
Collected errors:
 * opkg_install_cmd: Cannot install package iptables-mod-nfqueue.
could not install prerequisites

press enter to continue

**Comment by bol-van** [comment]
Скорее всего это китаец. Нет официальной поддержки. Китаец натянул на уши перчатку, фантик выплюнул, и все довольны. Пока не начнешь что-то ставить. Репозиториев нет, модулей ядра нет

**Comment by funnyshit** [comment]
Понял... неудачно попал (( Да, это китайская версия.

А без этого модуля никак не запустить?

**Comment by bol-van** [comment]
iptables можно навернуть, но они потянут за собой зависимости kmod-*, которые любезный китаец положить не удосужился

**Comment by bol-van** [comment]
Без него не будет nfqws работать

**Comment by funnyshit** [comment]
А tpws для обхода блокировки youtube недостаточно?

**Comment by bol-van** [comment]
На части провайдеров обходит для TLS 1.3.
--split-pos=1 --oob
Для TLS 1.2 может помочь --mss 88, но это большая жесть, которую лучше не использовать.
Это вариант точечного пробития, когда другой вариант - вообще никак

**Comment by funnyshit** [comment]
спасибо большое! буду пробовать

**Comment by dlempty** [comment]
есть вариант сменить заводскую прошивку на чистый owrt избавиться от китайщины и нормально ставить все необходимые пакеты

**Comment by funnyshit** [comment]
а где такой вариант? я нашел только для redmi ax6000, а для моего xiaomi ax6000 пишут, что нет(

**Comment by dlempty** [comment]
> а где такой вариант? я нашел только для redmi ax6000, а для моего xiaomi ax6000 пишут, что нет(

Ссылку на устройство дай

**Comment by bol-van** [comment]
Это неофициалка. Китайцы на коленке адаптировали под свой чипсет, не позаботившись о дальнейшем обновлении и сопровождении.
По хорошему им надо было провести поддержку через сообщество и сделать ее официальной.
Но в стилке китайском им пофигу. Склепал кое-как, продал фантик, забыл

**Comment by dlempty** [comment]
> Это неофициалка. Китайцы на коленке адаптировали под свой чипсет, не позаботившись о дальнейшем обновлении и сопровождении. По хорошему им надо было провести поддержку через сообщество и сделать ее официальной. Но в стиле китайском им пофигу. Склепал кое-как, продал фантик, забыл. Большинство юзеров привыкло роутеры встречать по веб морде. Морда есть ? openwrt ? тык тык настроил готово. все зашибись

Сам недавно купил сяоми ах6000 китайский, отлично прошился на чистый оврт, главное что б чипсет был медиатек а не квалкомм

**Comment by funnyshit** [comment]
> > а где такой вариант? я нашел только для redmi ax6000, а для моего xiaomi ax6000 пишут, что нет(
> 
> Ссылку на устройство дай

Роутер Xiaomi Mi AX6000 Wi-Fi с Wi-Fi6
https://market.yandex.ru/product--mi-aiot-ax6000/1777242039?sku=101853800017&uniqueId=99558805

**Comment by dlempty** [comment]
> > > а где такой вариант? я нашел только для redmi ax6000, а для моего xiaomi ax6000 пишут, что нет(
> > 
> > 
> > Ссылку на устройство дай
> 
> Роутер Xiaomi Mi AX6000 Wi-Fi с Wi-Fi6 https://market.yandex.ru/product--mi-aiot-ax6000/1777242039?sku=101853800017&uniqueId=99558805

Не, тут точно не вариант шиться, чип от квалкомм, если и перешить то можно остаться без вайфаев или ещё чего-нибудь 😐

**Comment by funnyshit** [comment]
вот я тоже подумал, что лучше не рисковать. nftables там нет, как я понял, там на какой-то старой версии openwrt основывается. opkg по крайней мере использует репы от 18-й версии.

**Comment by funnyshit** [comment]
думал может как-то попробовать самостоятельно собрать этот iptables-mod-nfqueue, но тоже не факт, что заведется

**Comment by funnyshit** [comment]
на tpws пока не получилось обойти блокировки
