### ISSUE TITLE
-HUP не работает.

### ISSUE THREAD

**Issue by ppetbox** [bol-van/zapret#662]
обновляю zapret-ip-user.txt, потом

`killall -HUP nfqws`

не помогает, тогда пробую

`systemctl restart zapret.service`

то же никакого эффекта. Приходтися вопрос решать радикально:
```
systemctl stop zapret.service
nft delete table inet zapret
systemctl start zapret.service
```

**Comment by bol-van** [comment]
Если непонятно что творит nfqws, его можно запустить с --debug логом. См доку по параметру --debug.
На счет nft, pls

`nft -t list table inet zapret` до systemctl stop, после stop и после start , без delete

**Comment by bol-van** [comment]
ipset сохраняется, потому что он заполняется отдельно скриптами из ipset
Его дергать туда-сюда из-за каждого рестарта чревато на рутерах. Может память отвалиться

**Comment by ppetbox** [comment]
Ну тогда delete это единственный способ обновления списка (если HUP не работает) . Обновление я проверял по 

`nft list table inet zapret`

**Comment by bol-van** [comment]
HUP не обновляет ip листы.
они находятся не в памяти nfqws, а в памяти ядра linux

**Comment by ppetbox** [comment]
То есть так  и должно быть: после HUP в `nft list table inet zapret` ничего и не долждно изменится, так что ли?

**Comment by bol-van** [comment]
Да, HUP существует только для хостлистов и user mode ipset-ов внутри nfqws/tpws. Которые на *nix не должны использоваться

**Comment by ppetbox** [comment]
Спасибо.
