### ISSUE TITLE
Youtube "Нет сети" на android tv и Яндекс браузере

### ISSUE THREAD

**Issue by viktoriaLukyanova** [bol-van/zapret#665]
Друзья, выручайте. Поставил zapret на роутер с openwrt. Перепробовав 1000 стратегий для YT, нашел, которая работает (discord тоже работает с custom). Но работает на смартфонах (iphone, android), на win в браузерах кроме Яндекса (флаги одинаковые) и самое главное не работает на android TV (пишет "Нет подключения к Интернету").
Вот стратегии:
`NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig --new
--filter-tcp=443 --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new --dpi-desync=fake,disorder2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig "`

blockcheck выдает: ipv4 rr5---sn-c0q7lns7.googlevideo.com curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=1
Провайдер МТС. Пробовал ttl менять, но не вышло. Что за магия, как ее победить? Я знаю, что я где то близко

**Comment by eastone11** [comment]
https://github.com/bol-van/zapret/issues/657

**Comment by HentayHentay** [comment]
Здравствуйте



> nfqws --dpi-desync=fake --dpi-desync-ttl=1

Данный вывод относиться к -filter-tcp=443. 


> NFQWS_OPT=" --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new --dpi-desync=fake,disorder2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig "

Т.к не вижу ни листов, ни ипсетов , то делаю вывод что у нас стоит `MODE_FILTER=none` ?
Если что-то другое, то нужно занести в листы в зависимости от данной переменой ипы/сети  или домены

**Comment by viktoriaLukyanova** [comment]
> Здравствуйте
> 
> > nfqws --dpi-desync=fake --dpi-desync-ttl=1
> 
> Данный вывод относиться к -filter-tcp=443.
> 
> > NFQWS_OPT=" --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --new --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11 --new --dpi-desync=fake,disorder2 --dpi-desync-ttl=2 --dpi-desync-fooling=md5sig "
> 
> Т.к не вижу ни листов, ни ипсетов , то делаю вывод что у нас стоит `MODE_FILTER=none` ? Если что-то другое, то нужно занести в листы в зависимости от данной переменой ипы/сети или домены

MODE_FILTER=hostlist
В zapret-hosts-user все возможные домены, которые находил.
Поменял на: --filter-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin <HOSTLIST> --new 
Ничего не поменялось. 
На компе и в хроме если что посмотрю, мне главное на ТВ настроить. А на ноуте даже в хроме не работает. Вообще не понимаю

**Comment by HentayHentay** [comment]
> MODE_FILTER=hostlist
> --filter-tcp=443 --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new

Не вижу в предложенном варианте указание на хостлист. (см /docs/readme)
А значит у нас не происходит чтение хостлиста и применения дурения. Все правильно по сути

**Comment by eastone11** [comment]
начни с самого простого, поменяй hostlist на none

**Comment by bol-van** [comment]
> Не вижу в предложенном варианте дурения указание на хостлист. (см /docs/readme)
> В данном варианте фильтра запрет ждет список, что бы прочесть его и применить дурение. Не найдя данный список, у нас не применяется механизм.

Это не так.
MODE_FILTER нужен только для 
1. выбора способа замещения маркеров `<HOSTLIST>` и `<HOSTLIST_AUTO>` 
2. выбора в инсталяторе пути диалога какие листы скачивать.
3. в скриптах запуска MODE_FILTER=ipset меняет правила перенаправления трафика с фаервола

**Comment by andmt1** [comment]
> Что за магия, как ее победить? 
Ответил тут
https://github.com/bol-van/zapret/issues/657#issuecomment-2452914487
