### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by BlvDeLxRd** [bol-van/zapret#667]
Вобще я новый пользователь линукса, вот установил можно сказать на днях первый раз и столкнулся с проблемой дса(не робит войс), тк на винде все просто и не нужно ничего настраивать, достаточно просто нажать пару кнопок и все готово, то тут я хз че делать. В readme и quick-start написано первым делом после установки библеотек  нужно отправится в blockcheck.sh я понятное дело так и сделал, по итогу работы этого файла мне выдало вот это:
```
ipv4 rutracker.org curl_test_http : working without bypass
ipv4 rutracker.org curl_test_http : tpws --hostcase
ipv4 rutracker.org curl_test_http : nfqws --hostcase
ipv4 rutracker.org curl_test_https_tls12 : working without bypass
ipv4 rutracker.org curl_test_https_tls12 : tpws --split-tls=sni
ipv4 rutracker.org curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=5
```
Далее на сколько я понял нужно идти в install_easy.sh, все правильно протыкать и ввести туда значения, которые я получил по итогу в blockcheck.sh, вот тут у меня возник вопрос собственно, не понимаю куда конкретно и какие данные нужно вводить, нужно ли что то заменять и куда че дописывать? Вот что я вижу у себя на экране:
```
./install_easy.sh
* checking system
system is based on systemd
* checking executables
found architecture "x86_64"
* checking privileges
root is required
[sudo] пароль для blvdelxrd: 
* checking system
system is based on systemd
* checking executables
found architecture "x86_64"
* checking privileges
* checking readonly system
* checking location

easy install is supported only from default location : /opt/zapret
currently its run from /home/blvdelxrd/Загрузки/zapret-66
do you want the installer to copy it for you (default : N) (Y/N) ? y

installer found existing /opt/zapret
directory needs to be replaced. config and custom scripts can be kept or replaced with clean version
do you want to delete all files there and copy this version (default : N) (Y/N) ? y

keep config, custom scripts and user lists (default : Y) (Y/N) ? y
relaunching itself from /opt/zapret
* checking system
system is based on systemd
* checking executables
found architecture "x86_64"
* checking privileges
* checking readonly system
* checking location
running from /opt/zapret
* checking DNS
system DNS is working
* checking virtualization
running on bare metal
* stopping zapret service
Removed "/etc/systemd/system/multi-user.target.wants/zapret.service".
Removed "/etc/systemd/system/zapret.service".

select firewall type :
1 : iptables
2 : nftables
your choice (default : nftables) : 2
selected : nftables
* checking prerequisites
required utilities exist : curl nft
* installing binaries
x86_64 is OK
installing binaries ...
linking : ../binaries/x86_64/ip2net => /opt/zapret/ip2net
linking : ../binaries/x86_64/mdig => /opt/zapret/mdig
linking : ../binaries/x86_64/nfqws => /opt/zapret/nfq
linking : ../binaries/x86_64/tpws => /opt/zapret/tpws

enable ipv6 support (default : N) (Y/N) ? n

flow offloading can greatly increase speed on slow devices and high speed links (usually 150+ mbits)
offloading is applicable only to forwarded traffic. it has no effect on outgoing traffic
hardware flow offloading is available only on specific supporting hardware. most likely will not work on a generic system
offloading breaks traffic shaper
select flow offloading :
1 : none
2 : software
3 : hardware
your choice (default : none) : 1
selected : none

enable tpws socks mode on port 987 ? (default : N) (Y/N) ? n

enable tpws transparent mode ? (default : N) (Y/N) ? n

enable nfqws ? (default : Y) (Y/N) ? y

NFQWS_PORTS_TCP=80,443
NFQWS_PORTS_UDP=443
NFQWS_TCP_PKT_OUT=9
NFQWS_TCP_PKT_IN=3
NFQWS_UDP_PKT_OUT=9
NFQWS_UDP_PKT_IN=0
NFQWS_PORTS_TCP_KEEPALIVE=
NFQWS_PORTS_UDP_KEEPALIVE=
NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=fake,disorder2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 <HOSTLIST>"
do you want to edit the options (default : N) (Y/N) ? 
```
Возможно я что то где то не так указал, где то не прочитал и из-за этого щас туплю, я хз. Кто нибудь укажите на ошибки, помогите или просто проведите меня за ручку от начала до успешного обхода блокировки дс пжж<3333)

**Comment by Aspirata** [comment]
Попробуй это
https://github.com/bol-van/zapret/issues/637#issuecomment-2439937985

**Comment by BlvDeLxRd** [comment]
> Попробуй это [#637 (comment)](https://github.com/bol-van/zapret/issues/637#issuecomment-2439937985)

спс братишь реально помогло, только теперь у меня почему то тг не робит и на панели задачь показывает, что я к интернету не подключен, кто еще знает, что у меня еще не будет работать

**Comment by HentayHentay** [comment]
> спс братишь реально помогло, только теперь у меня почему то тг не робит и на панели задачь показывает, что я к интернету не подключен, кто еще знает, что у меня еще не будет работать

Потребуется накидать в блокчекер сайты, к которым ты хочешь иметь доступ. По умолчанию выбрана стратегия обхода, которая может не подойти к твоему провайдеру.

`curl_test_https_tls12` - данный вывод относиться к `--filter-tcp=443`
` curl_test_http` - данный вывод относиться к `--filter-tcp=80`

Возможно потребуется ведение множественной стратегии с листами хостов/подсетями. Но предупрежу о таком моменте, что сайты могут находиться не в прямой видимости или быть заблокированы у провайдера полностью. Тогда только vpn/прокси или любой другой способ перенаправления трафика

**Comment by BlvDeLxRd** [comment]
1
