### ISSUE TITLE
Сборка пакетов под openwrt

### ISSUE THREAD

**Issue by etozhecyber** [bol-van/zapret#67]
Привет, я работаю DevOps инженером в кровавом энтерпрайзе и мне очень хочется приложить руку к opensource, я выбрал твой проект, так как считаю его очень полезным и перспективным. Также мне очень нравится OpenWrt и хотелось разобраться в нем устроены пакеты в архитектура в целом.

На выходных поковырялся с сборкой OpenWrt пакетов, получилось так https://github.com/etozhecyber/zapret-openwrt
В целом хотелось бы получить установку и настройку zapret одной командой на роутер любой домохозяйки которая смогла установить OpenWrt, это со стороны пользователя. Со стороны разработчика хотелось бы сделать релиз новой версии приложения по установке тега в github, чтобы все процессы тестирования, сборки, выкладки проходили автоматически через Github action.

Надеюсь на сотрудничество :)

**Comment by etozhecyber** [comment]
Также интересна сборка пакетов(а возможно и образов OpenWrt) под микротиковский metarouter, это тоже для меня неизведанная область

**Comment by etozhecyber** [comment]
В readme моего проекта указан примерный пласт работы которую я планирую сделать

**Comment by bol-van** [comment]
Предлагаю делать это отдельно. По типу гуи для goodbyedpi. 
Для домохозяйки не выйдет потому что нвдо разрвбатывать стратегию обхода. Хотите сделать авто пробер?
Вести базу провайдеров?

**Comment by etozhecyber** [comment]
Я так сейчас и делаю отдельно, https://github.com/etozhecyber/zapret-openwrt/blob/master/packages/tpws/Makefile#L6-L9. 
По поводу автонастройки я пока не думал если честно. В идеале нужен минималистичный https://github.com/ValdikSS/blockcheck чтобы его поставлять с приложением

**Comment by etozhecyber** [comment]
К этой теме про автопробер. 
Я сегодня настраивал goodbyedpi на новом провайдере, и поймал себя на том что тупо перебираю опции и дергаю curl -v http://www.linkedin.com/. Почему бы для роли пробера не использовать tpws в режиме socks 5 и curl c -x socks5h://localhost:1080 ?

Правда заметил в доке "Подключения к IP того же устройства, на котором работает tpws, включая localhost, запрещены", что сильно затею усложняет :(

**Comment by etozhecyber** [comment]
Единственное curl придётся ставить, он в базовой поставке не идёт. Но после автодетекта его можно снести, и сэкономить 50 кб места

**Comment by bol-van** [comment]
Запрещены только запросы на socks соединения к тому же хосту, где работает tpws
Чтобы извне не получили доступ к localhost.
Подключиться к tpws на localhost можно, запросить tpws подключиться к localhost - нет
Подключиться к tpws на localhost и запросить соединение в инет - можно

В условиях нашествия суверенки tpws почти бесполезен. nfqws дает куда больше вариантов

Я бы 10 раз подумал (и уже давно решил) стоит ли связываться с домохозяйками. Стоит ли им упрощать жизнь.
Условия постоянно меняются. Сегодня одна проверка работает, завтра нет. Сегодня на одном провайдере одно, завтра другое. Впрягаться с головой в поддержку всех возможных случаев - оно надо ?

**Comment by bol-van** [comment]
Оценка эффективности обхода блокировок не всегда является очевидной процедурой
дернули пару заблокированных (на момент написания версии проги), чего-то там выдало, вроде норм
к сожалению это не всегда так
бывает очень много разных случаев на разных провайдерах
блокировки могут быть неполными. что-то открывается, что-то нет.
блокировки могут выполняться разными девайсами. у TELE2 такое ощущение, что там несколько блокировщиков, каждый из которых блочит разные сайты.
какие-то методы могут ломать часть серверов. работать только на http, но не https, или наоборот
там очень много всяких нюансов

ожидаемого результата ткнул - проверил - получил да/нет - такого может не быть
может быть хорошо, а может вкривь-вкось, что проще отказаться от данного метода
или может быть, что большинство работает, но некоторые очень нужные нет.
нужны списки фильтрации

я так подумал, что поддержка автоматии не стоит моих усилий, а домохозяйки не являются целевой аудиторией. домохозяйки даже openwrt прошить не смогут, не то что залить туда zapret

**Comment by Bounty780** [comment]
А можно залить на роутер Keenetic через OPKG?

**Comment by bol-van** [comment]
на форуме кинетиков есть ветка по прикрутке. я деплойментгм под другие прошивки заниматься не собираюсь

**Comment by Glazami** [comment]
А под padavan можно приладить? Готового пакета вообще нету под mipsel?

**Comment by megapro17** [comment]
@etozhecyber энтузиазм мгновенно закончился? выложите хотя бы готовые пакеты, ну!

**Comment by megapro17** [comment]
> домохозяйки даже openwrt прошить не смогут, не то что залить туда zapret

Те кто прошил Openwrt, но не хочет связываться со всей этой дрянью по типу скачивания sdk, компиляции, вы тоже отбрасываете?

**Comment by Bounty780** [comment]
> на форуме кинетиков есть ветка по прикрутке. я деплойментом под другие прошивки заниматься не собираюсь

Оно бы хорошо, но выдает `iptables: No chain/target/match by that name`
