### ISSUE TITLE
НОВЫЙ ФИКС DISCORD! 100% РАБОЧИЙ ДИСКОРД + ЮТУБ

### ISSUE THREAD

**Issue by Merk-ops** [bol-van/zapret#673]
https://www.youtube.com/watch?v=5BGcOpSjLH0&t=8s
1 минута и дс работает 
ссылка на видос -

**Comment by HentayHentay** [comment]
> а для линуха слабо сделать?

С 66 запрета логика на Win/Linux стала похожей. Ну кроме части переменных. 

> 1 минута и дс работает
> ссылка на видос -

То что работает у Вас может не работать у других.

**Comment by L2503452** [comment]
Не качайте лол, поставил троянчик, уе66ан
