### ISSUE TITLE
Хром не даёт скачать .zip, скачал .tar.gz в чем разница? Я нубас полный, просто хочу завести дискорд

### ISSUE THREAD

**Issue by dzenkys** [bol-van/zapret#674]

**Comment by Miraihi** [comment]
Кто не хочет учиться пользоваться инструментом может попробовать [эту вилку](https://github.com/Flowseal/zapret-discord-youtube)

**Comment by MineShadow7** [comment]
Тот же архив, просто разархивируй утилитой, которая это позволяет
