### ISSUE TITLE
50-discord ломает часть интернета

### ISSUE THREAD

**Issue by kjljxybr** [bol-van/zapret#675]
hse.ru ломается, с ним же ломаются еще энное количество сайтов

ERR_CONNECTION_RESET в хроме 
SSL_ERROR_RX_MALFORMED_SERVER_HELLO в фаерфоксе

версия последняя, конфиг стандартный кроме как nfqws включен

**Comment by bol-van** [comment]
Невозможно, он работает только с udp на определенных портах и определенных IP

**Comment by kjljxybr** [comment]
с дефолтным конфигом без 50-discord все работает, с включенным 50-discord но service zapret stop тоже работает, как только запрет включается сразу вылезает то что выше. Провайдер МГТС, Москва

**Comment by bol-van** [comment]
Что за система ? iptables, nftables ?

**Comment by kjljxybr** [comment]
nftables, openwrt, в custom.d оригинальный 50-discord из той же версии, версия - гит пулл, последний коммит https://github.com/bol-van/zapret/commit/f22dcb24877ec9fe6be63ce3cf64d5433a3061b3

**Comment by kjljxybr** [comment]
Нет, ошибки те же

**Comment by bol-van** [comment]
Нет, не нужно рестартать фаервол.
Значит дело не в дурении, которое инициирует 50-discord.
Может в фаерволе ?

Что там в  nft list table inet zapret ?

**Comment by kjljxybr** [comment]
https://pastebin.com/S0Uv9TBe
pastebin тоже отказался открываться, пришлось стопать запрет

**Comment by bol-van** [comment]
А если запустить без 50-discord, что в nft list table inet zapret ?

Должно лишь исчезнуть вот это правило
 
        chain postnat {
                oifname @wanif udp dport 50000-50099 ct original packets 1-3 ip daddr @discord ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 65400

**Comment by kjljxybr** [comment]
https://pastebin.com/FPhR4CsM
pastebin заработал, hse.ru все так же сломано, лечится полной переустановкой без 50-discord

**Comment by bol-van** [comment]
Так работает
```
        chain postnat {
                oifname @wanif udp dport 443 ct original packets 1-9 ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 200
                oifname @wanif tcp dport { 80, 443 } ct original packets 1-9 ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 200
        }
```
А так не работает
```
        chain postnat {
                oifname @wanif udp dport 50000-50099 ct original packets 1-3 ip daddr @discord ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 65400
                oifname @wanif udp dport 443 ct original packets 1-9 ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 200
                oifname @wanif tcp dport { 80, 443 } ct original packets 1-9 ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 200
        }
```

Я все-таки думаю дело тут не в 50-discord, а в каких-то кэш-моментах броузера.
Никак это правило, тем более с отсутствующим обработчиком очереди, не может повлиять на работоспособность обычных сайтов.
Основная стратегия ломает сайты или не обходит блокировку.

Можно попробовать сделать NFQWS_ENABLE=0 , оставить 50-discord и перезапустить.
Думаю вряд ли что-то будет ломаться , кроме заблокированных. Будет девственный провайдер как есть

**Comment by kjljxybr** [comment]
Кэш не причем, это буквально первое что я проверил

> Можно попробовать сделать NFQWS_ENABLE=0 , оставить 50-discord и перезапустить.
так работает, да, но мне нужен nfqws для обхода ютуба, хотелось бы 2в1 получить рабочее

**Comment by bol-van** [comment]
Вы хоть немного в сетях разбираетесь и в таблицах ?
Видите что здесь идет направление на очередь udp портов 50000-50099 по списку ip из сета discord ?
Как по вашему это может повлиять на доступность веб сайтов ?

Надо разбираться с основной стратегией, которая не работает.
