### ISSUE TITLE
Удаление zapret в OpenWRT?

### ISSUE THREAD

**Issue by pavelmoshik** [bol-van/zapret#676]
Здравствуйте. 
Как удалить полностью zapret  с целью его обновления из роутера работающем на OpenWRT? 
Запускаю `uninstall_easy.sh` из папки /tmp в результате выполнения скрипта просто перестает работать команда service zapret, но файлы не удаляются из папки opt, настройки и конфиги zapret по прежнему продолжают работать, даже после перезагрузки и сброса настроек роутера.
Также запускал комнату `uninstall_easy.sh`  из папки /opt/zapret, суть таже.

**Comment by DerenHolmes** [comment]
запускаешь консоль ( командная строка ) вводишь Sc Stop WinDivert

**Comment by bol-van** [comment]
После uninstall надо rm -r /opt/zapret

**Comment by pavelmoshik** [comment]
> После uninstall надо rm -r /opt/zapret Для обновления не надо его убирать. Все сделает install_easy, запущенный из /tmp

Благодарю!

**Comment by KS753KS753** [comment]
Добрый день. 
На роутер ax3000t openwrt 24.10.1 через System / Software установил Zapret 70.20250505. 
1) Подскажите, как его полностью удалить и удалить директорию /opt/zapret? Пытался вводить эти команды через putty, но ничего не происходит. 
2) А можно обновлять на версию более свежую 71.20250607 через раздел System / Software просто установив поверх старой версии?

Примечание: Если на вашем роутере уже установлен дистрибутив zapret при помощи скрипта /opt/zapret/install_easy.sh, то следует запустить скрипт /opt/zapret/uninstall_easy.sh для удаления официального дистрибутива zapret. После этого желательно полностью удалить директорию /opt/zapret (это не обязательно, но рекомендуется).
