### ISSUE TITLE
blockcheck - 0 рабочих стратегий.

### ISSUE THREAD

**Issue by rscx-r1** [bol-van/zapret#677]
всем привет, в блокчеке после трех часов метода standart, не нашлось ни одной рабочей стратегии под дискорд
провайдер - билайн, сломался буквально минут 5 назад окончательно, что можно сделать?

версия zapret-win-bundle (свежая)

**Comment by Animator2003** [comment]
тоже чет отвалился дискорд 
свежий zapret-win
провайдер сибирские сети

**Comment by rscx-r1** [comment]
> тоже чет отвалился дискорд свежий zapret-win провайдер сибирские сети

что-то мне кажется дискорд решил не мелочиться и забанил россию окончательно)

**Comment by logo6** [comment]
> > тоже чет отвалился дискорд свежий zapret-win провайдер сибирские сети
> 
> что-то мне кажется дискорд решил не мелочиться и забанил россию окончательно)

так дс ркн забанил а не наоборот

**Comment by HentayHentay** [comment]
Если у провайдера дискорд по ипу забанен, то тут имеется пара обходов
- перененаправить свой трафик в правильном направление (vpn/tor/proxy)
- найти рабочий ип и сделать якорь в локальном hosts. пропустить "подменённый" через блокчек
- Так-же рекомендуется отказаться от провайдерских днс (подмена днс)

**Comment by DivM20** [comment]
У друга та же фигня была, ни одной стратегии по udp для дискорда, помогли аргументы, которые я взял с репозитория KizilBypass.
[list-general.txt](https://github.com/user-attachments/files/17601538/list-general.txt)
[kizil_based_shit.txt](https://github.com/user-attachments/files/17601539/kizil_based_shit.txt)
Вот список для дискорда и ютуба, kizil_based_shit нужно поставить разрешение .cmd, Гитхаб его не даёт так скинуть.
Закинь файлы в папку zapret-winws, мб поможет. Удачи.

**Comment by bol-van** [comment]
ТРЭШ-ФЛУД конфиг детектед
--filter-udp=50000-50099 --dpi-desync=fake,tamper --dpi-desync-any-protocol --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^

нет cutoff

Так же не будут работать варианты типа *.youtube.com в листах
звездочки не поддерживаются

**Comment by DivM20** [comment]
Ну вообще хз, тебе то так-то явно виднее. Я свой конфиг на базе вот этого сделал.
https://github.com/bol-van/zapret-win-bundle/issues/23
Вот ещё видяшка записи экрана, что оно работает, м.б. это тебе что-то скажет. Сам я лично понятия не имею почему, но проблему с дискордом это пофиксило.
https://disk.yandex.ru/i/2o0UHiUM_PjIYA

**Comment by bol-van** [comment]
В zapret-win-bundle никогда не было варианта без cutoff.
Его распространил однажды "деятель", и теперь эта зараза ходит по сети.
А я ее отмечаю при первом обнаружении.
Работать то она работает, но гадит сеть зазря и сильно

**Comment by rscx-r1** [comment]
> В zapret-win-bundle никогда не было варианта без cutoff. Его распространил однажды "деятель", и теперь эта зараза ходит по сети. А я ее отмечаю при первом обнаружении. Работать то она работает, но гадит сеть зазря и сильно, если попадет на указанные порты. Дебилу козлу анусовичу сообщил

никогда не юзал версию без cutoff, поправил благодаря настройке запрета на уровне роутера, пока держится)

**Comment by oculomotoriusus** [comment]
> В zapret-win-bundle никогда не было варианта без cutoff. Его распространил однажды "деятель", и теперь эта зараза ходит по сети. А я ее отмечаю при первом обнаружении. Работать то она работает, но гадит сеть зазря и сильно, если попадет на указанные порты. Дебилу козлу анусовичу сообщил

Добрый дядя, я прочитал тонну толмудов, но так и не понял как эти вещи "гадят сеть зазря и сильно" объясни пожалуйста:3 
и как сделать так чтобы работало но не "гадило сеть зазря и сильно" , добрый дядя, пожалуйста сжалься, я умоляю, читал эти толмуды два дня, голова кругом

**Comment by bol-van** [comment]
В версии для винды везде где any protocol нужен cutoff. Без него будет гадить

**Comment by oculomotoriusus** [comment]
> В версии для винды везде где any protocol нужен cutoff. Без него будет гадить

а что такое гадить? мне просто интересно, просто без cutoff не лучше ли чем используя vpn, и тонны данных обводя по кругу

**Comment by bol-van** [comment]
`winws.exe --wf-tcp=443 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-repeats=20 --dpi-desync-fooling=md5sig`
дернит что-нить по https
и посмотрит в шарк tcp.port=443

на каждый исходящий будет 20 говна и так до бесконечности

**Comment by bol-van** [comment]
```
ithub version v69.8 (9c8636081c413dcc08ea6ce8eb33a36798908a8e)

WARNING !!! possible TRASH FLOOD configuration detected in profile 1
WARNING !!! it's highly recommended to use --dpi-desync-cutoff limiter or fakes will be sent on every processed packet
WARNING !!! make sure it's really what you want
WARNING !!! in most cases this is acceptable only with custom payload based windivert filter (--wf-raw)
we have 1 user defined desync profile(s) and default low priority profile 0
```
