### ISSUE TITLE
Перестал работать дис с прогой zapret, у кого так же

### ISSUE THREAD

**Issue by DerenHolmes** [bol-van/zapret#678]

**Comment by DerenHolmes** [comment]
я даже обновил программу и всё заработало, но потом через несколько часов вдруг перестал

**Comment by 999ASMODEUS666** [comment]
Есть такое, я discord.bat включал пару минут грузило и зашло

**Comment by bol-van** [comment]
Обсуждение сборок переносим к сборщикам
