### ISSUE TITLE
Как избавиться от лишней папки bin?

### ISSUE THREAD

**Issue by karbonator55** [bol-van/zapret#679]
Я собирался установить новую версию zapret discord. Установил, всё работает. Но когда я собрался удалить прошлую версию, у меня получилось удалить всё кроме папки bin. При попытке удаления высвечивается уведомление, что папка используется. Как можно от неё избавиться, если вторая bin-папка уже есть вместе с новой версией zapret discord?

![изображение_2024-10-31_140658677](https://github.com/user-attachments/assets/54123f50-895d-4401-86ee-a0df15f88016)

![изображение_2024-10-31_140724007](https://github.com/user-attachments/assets/e670e60a-9a56-482e-bf03-b3fdc29a9e20)

**Comment by karbonator55** [comment]
Или вдруг я пошёл совсем не тем путём? Подскажите, пожалуйста, как всё наладить

**Comment by logo6** [comment]
востанови из корзины прошлый запрет и там deleteservice

**Comment by karbonator55** [comment]
> востанови из корзины прошлый запрет и там deleteservice

пытался. это почему-то не помогло. Но я уже нашёл другое решение, спасибо!
