### ISSUE TITLE
Бинарники в UPX

### ISSUE THREAD

**Issue by etozhecyber** [bol-van/zapret#68]
https://github.com/bol-van/zapret/blob/dccf672d8a9f4a0ba7e671eb1eadd52f9ce7b4d3/docs/readme.txt#L993

Для OpenWrt в этом нет смысла так как файловая система SquashFS которая используется на роутерах уже со сжатием. 
Чаще всего UPX сжатые бинарники в SquashFS весят немного больше, чем без UPX сжатия. По этому в OpenWrt upx не используют

**Comment by bol-van** [comment]
В squash запакована только основная часть прошивки. 
Всунуть в нее посторонние бинарики можно только либо через свою сборку, либо через image builder
Остальные пакаджи ставятся в несжимаемую FS, которая есть overlaysfs(squashfs, jffs2/ubifs)
Они не жмутся

**Comment by etozhecyber** [comment]
Да, ты прав. Я не учёл overlayfs
