### ISSUE TITLE
50-discord отвалился

### ISSUE THREAD

**Issue by FelixBlet** [bol-van/zapret#684]
Сначала работал, без нареканий, потом в один момент просто отключил и не хочет подключать. Как будто способ дрочки мозгов другой от РКП. Пока я пытался починить подключиться всё таки удалось на какой то сервер, но в основном ругается конкретно что на russia****.discord.media
Попробовал подключиться без своих обходов - всё также. 
Идеи у меня кончились, поэтому пришёл сюда :/
Запрет стоит на пк, линух

**Comment by bol-van** [comment]
50-discord работает только по voice части.
Обход веб сайтов через основную функцию

**Comment by FelixBlet** [comment]
> 50-discord работает только по voice части. Обход веб сайтов через основную функцию
В этом то и проблема, веб сайт обходит, сообщения пишутся, все дела, а вот voice часть как раз и не работает. К голосовым каналам не подключается

**Comment by render69** [comment]
у меня такаяже фигня ток в добавок ют отвалился. дискорд вроде работает на сообщения. и то ют я починил методом тыка не понимая что куда тыкать  🥲

**Comment by bol-van** [comment]
У всех по разному на провайдерах. Нет тут единых таблеток.

**Comment by FelixBlet** [comment]
Бол-ван как всегда оказался прав, за что ему большое спасибо.
Как оказалось, несмотря на тот факт, что конкретно тот сайт запускается при подключении - отношения к войсу он имеет малое. Я попробовал другую стратегию и войс заработал.
@render69 Попробуй прогнать discord.com через блокчек и попробовать другие стратегии. Несмотря на то, что моя прошлая работала - пришлось её изменять.

**Comment by render69** [comment]
> Бол-ван как всегда оказался прав, за что ему большое спасибо. Как оказалось, несмотря на тот факт, что конкретно тот сайт запускается при подключении - отношения к войсу он имеет малое. Я попробовал другую стратегию и войс заработал. @render69 Попробуй прогнать discord.com через блокчек и попробовать другие стратегии. Несмотря на то, что моя прошлая работала - пришлось её изменять.

то что у меня плок чек выдаёт не работает, дорабатывать приходится

**Comment by FelixBlet** [comment]
> то что у меня блок чек выдаёт не работает, дорабатывать приходится

У меня тоже не сработало, если брать именно по строчкам, но я просто попробовал комбинировать предложенные методы и всё заработало. Самое главное - не забывать отключать запрет (да и вообще все приложения для обхода) во время блокчека, а то один раз понять не мог, почему дискорд работать не хочет с предложенными стратегиями...

**Comment by Netlighter** [comment]
> > то что у меня блок чек выдаёт не работает, дорабатывать приходится
> 
> У меня тоже не сработало, если брать именно по строчкам, но я просто попробовал комбинировать предложенные методы и всё заработало. Самое главное - не забывать отключать запрет (да и вообще все приложения для обхода) во время блокчека, а то один раз понять не мог, почему дискорд работать не хочет с предложенными стратегиями...

у меня во время блокчека открылся дискорд, то есть какой-то обход сработал, но когда установил сервис не заработало. можешь кинуть свой конфиг, может моя проблема с другом?

**Comment by Netlighter** [comment]
заработало, пришлось откатить конфиг до дефолтного и по очереди пробовать новые настройки

```python
# this file is included from init scripts
# change values here

# can help in case /tmp has not enough space
#TMPDIR=/opt/zapret/tmp

# redefine user for zapret daemons. required on Keenetic
#WS_USER=nobody

# override firewall type : iptables,nftables,ipfw
FWTYPE=nftables
# nftables only : set this to 0 to use pre-nat mode. default is post-nat.
# pre-nat mode disables some bypass techniques for forwarded traffic but allows to see client IP addresses in debug log
#POSTNAT=0

# options for ipsets
# maximum number of elements in sets. also used for nft sets
SET_MAXELEM=522288
# too low hashsize can cause memory allocation errors on low RAM systems , even if RAM is enough
# too large hashsize will waste lots of RAM
IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
# dynamically generate additional ip. $1 = ipset/nfset/table name
#IPSET_HOOK="/etc/zapret.ipset.hook"

# options for ip2net. "-4" or "-6" auto added by ipset create script
IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
# options for auto hostlist
AUTOHOSTLIST_RETRANS_THRESHOLD=3
AUTOHOSTLIST_FAIL_THRESHOLD=3
AUTOHOSTLIST_FAIL_TIME=60
# 1 = debug autohostlist positives to ipset/zapret-hosts-auto-debug.log
AUTOHOSTLIST_DEBUGLOG=0

# number of parallel threads for domain list resolves
MDIG_THREADS=30

# ipset/*.sh can compress large lists
GZIP_LISTS=1
# command to reload ip/host lists after update
# comment or leave empty for auto backend selection : ipset or ipfw if present
# on BSD systems with PF no auto reloading happens. you must provide your own command
# set to "-" to disable reload
#LISTS_RELOAD="pfctl -f /etc/pf.conf"

# mark bit used by nfqws to prevent loop
DESYNC_MARK=0x40000000
DESYNC_MARK_POSTNAT=0x20000000

TPWS_SOCKS_ENABLE=0
# tpws socks listens on this port on localhost and LAN interfaces
TPPORT_SOCKS=987
# use <HOSTLIST> placeholders to engage standard hostlists and autohostlist in ipset dir
# they are replaced to empty string if MODE_FILTER does not satisfy
TPWS_SOCKS_OPT="
--filter-tcp=443 --split-tls=sni --disorder --oob <HOSTLIST>
"

TPWS_ENABLE=0
TPWS_PORTS=80,443
# use <HOSTLIST> placeholders to engage standard hostlists and autohostlist in ipset dir
# they are replaced to empty string if MODE_FILTER does not satisfy
TPWS_OPT="
--filter-tcp=80 --methodeol <HOSTLIST> --new
--filter-tcp=443 --split-tls=sni --disorder <HOSTLIST>
"

NFQWS_ENABLE=1
# redirect outgoing traffic with connbytes limiter applied in both directions.
NFQWS_PORTS_TCP=80,443
NFQWS_PORTS_UDP=443
# PKT_OUT means connbytes dir original
# PKT_IN means connbytes dir reply
# this is --dpi-desync-cutoff=nX kernel mode implementation for linux. it saves a lot of CPU.
NFQWS_TCP_PKT_OUT=$((6+$AUTOHOSTLIST_RETRANS_THRESHOLD))
NFQWS_TCP_PKT_IN=3
NFQWS_UDP_PKT_OUT=$((6+$AUTOHOSTLIST_RETRANS_THRESHOLD))
NFQWS_UDP_PKT_IN=0
# redirect outgoing traffic without connbytes limiter and incoming with connbytes limiter
# normally it's needed only for stateless DPI that matches every packet in a single TCP session
# typical example are plain HTTP keep alives
# this mode can be very CPU consuming. enable with care !
#NFQWS_PORTS_TCP_KEEPALIVE=80
#NFQWS_PORTS_UDP_KEEPALIVE=
# use <HOSTLIST> placeholders to engage standard hostlists and autohostlist in ipset dir
# they are replaced to empty string if MODE_FILTER does not satisfy
NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=fake,disorder2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 <HOSTLIST>
"

# none,ipset,hostlist,autohostlist
MODE_FILTER=none

# openwrt only : donttouch,none,software,hardware
FLOWOFFLOAD=none

# openwrt: specify networks to be treated as LAN. default is "lan"
#OPENWRT_LAN="lan lan2 lan3"
# openwrt: specify networks to be treated as WAN. default wans are interfaces with default route
#OPENWRT_WAN4="wan vpn"
#OPENWRT_WAN6="wan6 vpn6"

# for routers based on desktop linux and macos. has no effect in openwrt.
# CHOOSE LAN and optinally WAN/WAN6 NETWORK INTERFACES
# or leave them commented if its not router
# it's possible to specify multiple interfaces like this : IFACE_LAN="eth0 eth1 eth2"
# if IFACE_WAN6 is not defined it take the value of IFACE_WAN
#IFACE_LAN=
#IFACE_WAN=
#IFACE_WAN6="ipsec0 wireguard0 he_net"

# should start/stop command of init scripts apply firewall rules ?
# not applicable to openwrt with firewall3+iptables
INIT_APPLY_FW=1
# firewall apply hooks
#INIT_FW_PRE_UP_HOOK="/etc/firewall.zapret.hook.pre_up"
#INIT_FW_POST_UP_HOOK="/etc/firewall.zapret.hook.post_up"
#INIT_FW_PRE_DOWN_HOOK="/etc/firewall.zapret.hook.pre_down"
#INIT_FW_POST_DOWN_HOOK="/etc/firewall.zapret.hook.post_down"

# do not work with ipv4
#DISABLE_IPV4=1
# do not work with ipv6
DISABLE_IPV6=1

# select which init script will be used to get ip or host list
# possible values : get_user.sh get_antizapret.sh get_combined.sh get_reestr.sh get_hostlist.sh
# comment if not required
#GETLIST=

**Comment by FelixBlet** [comment]
> заработало, пришлось откатить конфиг до дефолтного и по очереди пробовать новые настройки

 Я немного неуверен, но вроде если стоит MODE_FILTER=none, то хостлист не подставляется, попробуй прописать вручную путь до хостлиста, может перестанет ломаться.

**Comment by HentayHentay** [comment]
> > заработало, пришлось откатить конфиг до дефолтного и по очереди пробовать новые настройки
> 
> Я немного неуверен, но вроде если стоит MODE_FILTER=none, то хостлист не подставляется, попробуй прописать вручную путь до хостлиста, может перестанет ломаться.

Стратегия применяется на всем, что проходит фильтры.
