### ISSUE TITLE
Бесконечное подключение к RTC

### ISSUE THREAD

**Issue by Ingvarr15** [bol-van/zapret#685]
Устанавливаю на linux, вроде все делаю по инструкции, после запуска обхода начинает пускать в диск, можно отправлять сообщения, но при подключении к голосовому каналу висит какое-то время подключение к RTC, а потом пишет что не удалось установить маршрут. То есть такое ощущение что работает, но частично. Если что вот конфиг:
```
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=fake,disorder2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 <HOSTLIST>
```
Подскажите, у кого была такая проблема? Как решили?

**Comment by bol-van** [comment]
Кастом надо использовать 50-discord. Поместить в custom.d

**Comment by Ingvarr15** [comment]
> Кастом надо использовать 50-discord. Поместить в custom.d

Спасибо тебе большое! Я 4 дня пытался понять где я косячу, думал мб конфиг под свою конкретную ситуацию надо изменить. Теперь всё отлично работает)

**Comment by Wippito** [comment]
> Кастом надо использовать 50-discord. Поместить в custom.d


Привет. Пытаюсь тоже запустить кастомный скрипт, перенес 50-discord в custom.d, но дискорд так и не заработал.
Перед этим прогнал дискорд через блокчек, внес параметры в стратегию в конфиге. Прочитал ридми, поискал по темам по ключевому слову custom, но так и не нашел. Что-то нужно еще сделать, чтобы активировать его?

**Comment by bol-van** [comment]
Двойной --dpi-desync бесполезен. остается лишь последний вариант.
TPWS_OPT и NFQWS_OPT включаются лишь, если включен соответствующий ENABLE
50-discord работает только по voice части. как всегда гарантий обхода нет, не на всех провайдерах может работать.
Веб сайт и приложения могут использовать другие домены, кроме того, что виден в адресной строке

**Comment by Wippito** [comment]
> TPWS_OPT и NFQWS_OPT включаются лишь, если включен соответствующий ENABLE

вы про TPWS_ENABLE=1 и NFQWS_ENABLE=1? других не нашел, эти включены


> 50-discord работает только по voice части

что-то можно сделать, если стратегии по discord.com и 50-discord не разблокируют дискорд? больше никаких путей разблокировки нет?

**Comment by Wippito** [comment]
> Двойной --dpi-desync бесполезен. остается лишь последний вариант.

если я правильно понял, то --dpi-desync должен быть оформлен так, верно? спасибо за помощь
--filter-tcp=80 --dpi-desync=fake,split2,disorder2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=fake,disorder2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-udp=443 --dpi-desync=fake,disorder2 --dpi-desync-repeats=6 <HOSTLIST>

**Comment by bol-van** [comment]
split2 и disorder2 взаимо исключающие. либо то, либо это
В остальном годится в первом приближении.

Но вот использование одновременное tpws и nfqws с данными опциями вряд ли уместно.
Сплитать должен только один.
Если уж tpws используется в тандеме с nfqws, то он должен работать на оцпии дурения, не реализованные в nfqws. Такие, как oob, methodeol. То есть все, что вносят изменение в размер данных в пакетах. nfqws это сделать не может.

Если же tpws сделан "на всякий случай" и "чтобы было", то это плохое решение. Больше - не значит лучше.
