### ISSUE TITLE
Как включить custom в новой версии ?

### ISSUE THREAD

**Issue by Xcode24** [bol-van/zapret#687]
Исходя из документации <50-discord>  поместил  в /opt/zapret/init.d/sysv/custom.d, ибо в моём случае у меня просто Linux
Я не силён в этих делах поэтому просьба не хэйтить))
P.S. Оператор эр-телеком ни как не могу победить доступ к rutor.info 
Debian amd64, danted, squid.
Вот что менял в дефолт конфиге:
 
FWTYPE=iptables

...

NFQWS_ENABLE=1

NFQWS_PORTS_TCP=80,443
NFQWS_PORTS_UDP=443

NFQWS_TCP_PKT_OUT=$((6+$AUTOHOSTLIST_RETRANS_THRESHOLD))
NFQWS_TCP_PKT_IN=3
NFQWS_UDP_PKT_OUT=$((6+$AUTOHOSTLIST_RETRANS_THRESHOLD))
NFQWS_UDP_PKT_IN=0

NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --hostlist="/opt/zapret/ipset/zapret-hosts-user.txt" --new
--filter-tcp=443 --dpi-desync=fake,split2  --dpi-desync-ttl=8 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --hostcase --hostlist="/opt/zapret/ipset/zapret-hosts-user.txt" --dpi-desync-fake-tls="/opt/zapret/files/fake/tls_clienthel>
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 --hostlist="/opt/zapret/ipset/zapret-hosts-user.txt" --dpi-desync-fake-quic="/opt/zapret/files/fake/quic_initial_www_google_com.bin" --new
"
MODE_FILTER=hostlist

**Comment by eastone11** [comment]
> Кастомы останутся, но уже без MODE=custom. Достаточно их наличия.

а блокчек ничего не находит для rutor.info?

**Comment by bol-van** [comment]
hostlist="/opt/zapret/ipset/zapret-hosts-user.txt" 

так лучше не делать. для этого есть маркер `<HOSTLIST>` и MODE_FILTER=hostlist

на домру надо шифровать dns

**Comment by Xcode24** [comment]
> > Кастомы пришли, но уже без MODE=custom. Их достаточно.
> 
> блокчек ничего не нашёл для rutor.info?

ipv4 rutor.info curl_test_http : nfqws --hostcase
ipv4 rutor.info curl_test_https_tls12 : nfqws --dpi-desync=fake,split2 --dpi-desync-ttl=8

**Comment by Xcode24** [comment]
> hostlist="/opt/zapret/ipset/zapret-hosts-user.txt" так лучше не делать. для этого есть маркер `<HOSTLIST>` и MODE_FILTER=hostlist
> 
> на домру надо шифровать dns
> 
> в конце --new тоже лишний. хотя это и не смертельно, но вместо нулевого профиля все неподошедшее будет падать в этот последний.

поправил как сказал сенсей, рутор поднялся!) спасбо!
Но как заставить работать дискорд????

NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=fake,split2  --dpi-desync-ttl=8 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --hostcase --dpi-desync-fake-tls="/opt/zapret/files/fake/tls_clienthello_www_google_com.bin" <HOSTLIST> --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="/opt/zapret/files/fake/quic_initial_www_google_com.bin" <HOSTLIST_NOAUTO>
"

**Comment by bol-van** [comment]
В `<HOSTLIST>` не хватает закрывающего знака. Гитхаб сьел ?
discord voice через custom   50-discord

**Comment by Xcode24** [comment]
> В `<HOSTLIST>` не хватает закрывающего знака. Гитхаб сьел ? discord voice через custom 50-discord

 Гитхаб сьел )  
 Понимаю что через custom 50-discord, но не понимаю как его включить?

**Comment by bol-van** [comment]
Переписать в custom.d в init.d/{sysv,openwrt} в зависимости от типа системы

**Comment by Xcode24** [comment]
> Переписать в custom.d в init.d/{sysv,openwrt} в зависимости от типа системы

Сделано но discord voice не работает(

**Comment by bol-van** [comment]
Рестарт нужен zapret.
Если не работает, то нет никаких гарантий работоспособности стратегии
Можно чуток подкрутить параметры в переменных, которые обьявлены в начале 50-discord.
Их можно перенести в config

**Comment by Xcode24** [comment]
> Рестарт нужен zapret. Если не работает, то нет никаких гарантий работоспособности стратегии Можно чуток подкрутить параметры в переменных, которые обьявлены в начале 50-discord. Их можно перенести в config

Взял стратегию из рабочего winws 
--filter-udp=50000-50100 --ipset="ipset-discord.txt" --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new ^

Заменил в /opt/zapret/init.d/sysv/custom.d/50-discord:
NFQWS_OPT_DESYNC_DISCORD="${NFQWS_OPT_DESYNC_DISCORD:---dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol}"
на 
NFQWS_OPT_DESYNC_DISCORD="${NFQWS_OPT_DESYNC_DISCORD:---dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6"
Ничего не поменялось. 
Как проверить работу модуля 50-discord??

**Comment by NoDwen** [comment]
Проверить работу можно с помощью systemctl status zapret.service там должны быть строчка с параметрами NFQWS_OPT_DESYNC_DISCORD, либо можно в конце файла 50-discord написать `echo "Любой текст(скорее всего желательно на английском"`,и искать строчку с твоим текстом в команде systemctl status zapret.service

**Comment by bol-van** [comment]
> Ничего не поменялось.

Под linux cutoff не нужен, потому что используются connbytes. Он еще больше обрезает фейкование с 3 до 2 пакетов

**Comment by bol-van** [comment]
Проверить работу можно посмотрев параметры инстанса nfqws, обслуживающего discord, убив его и запустив в консоли с --debug.
Или добавить --debug=@filename или --debug=syslog в параметры

**Comment by Xcode24** [comment]
> > Ничего не поменялось.
> 
> Под linux cutoff не нужен, потому что используются connbytes. Он еще больше обрезает фейкование с 3 до 2 пакетов

Нашёлся процесс, но войс так и не завелся, в чом может быить ещё проблема ? Я испльзую danted мб оно теряет?


zapret[63961]: Inserting iptables rule for nfqws postrouting (qnum 65400) : -p udp -m multiport --dports 50000:50100 -m connbytes --connbytes-dir=original --connbytes-mode=packets --connbytes 1:3 -m set --match-set discord dst

**Comment by bol-van** [comment]
danted - это socks proxy. Даже если socks поддерживает udp assicate, броузеры это не используют. Лезут напрямую должно быть.
Можно считать, что через прокси удп не ходит

**Comment by bol-van** [comment]
Для обхода блокировки DHT перед выборами. Его уже 2 раза блокировали , чтобы не работало навальное приложение для умного голосования

**Comment by bol-van** [comment]
Против навальной блокировки DHT перед выборами

**Comment by Xcode24** [comment]
> danted - это socks proxy. Даже если socks поддерживает udp associate, броузеры это не используют. Лезут напрямую должно быть. Можно считать, что через прокси удп не ходит

Я не исполюзю discord в браузере, а использую proxifier для desktop

**Comment by Xcode24** [comment]
> > danted - это socks proxy. Даже если socks поддерживает udp associate, броузеры это не используют. Лезут напрямую должно быть. Можно считать, что через прокси удп не ходит
> 
> Я не исполюзю discord в браузере, а использую proxifier для desktop c rules по discord.exe

**Comment by bol-van** [comment]
Неизвестно как это все работает в связке.
Надо смотреть шарки, дампы и разглядеть там то, что должно быть. Или его отсутствие

**Comment by Xcode24** [comment]
> Неизвестно как это все работает в связке. Надо смотреть шарки, дампы и разглядеть там то, что должно быть. Или его отсутствие

Мне все равно кажется, что модуль не отрабатывает
 50-dht4all - для чего ?

**Comment by pwd491** [comment]
> > Неизвестно как это все работает в связке. Надо смотреть шарки, дампы и разглядеть там то, что должно быть. Или его отсутствие
> 
> Мне все равно кажется, что модуль не отрабатывает 50-dht4all - для чего ?

Попробуйте сделать
```
/etc/init.d/zapret stop
/etc/init.d/zapret stop_fw
/etc/init.d/zapret start_fw
/etc/init.d/zapret start
```

( Я когда настраивался заметил баг, что если делать `/etc/init.d/zapret restart` то правила для udp в firewall не прописываются, возможно у вас также)

**Comment by bol-van** [comment]
```
start_fw()
{
	zapret_apply_firewall
}
stop_fw()
{
	zapret_unapply_firewall
}
restart_fw()
{
	stop_fw
	start_fw
}

```

**Comment by Xcode24** [comment]
> Неизвестно как это все работает в связке. Надо смотреть шарки, дампы и разглядеть там то, что должно быть. Или его отсутствие

И так, мод работает всё ок 
proxifier не пробрасывает UDP 
решением проблемы с войсом было использование SOCKS5 для дискорда вот данный проект оказался заменой не рабочему proxifier 
https://github.com/runetfreedom/discord-voice-proxy/tree/v0.2.1
