### ISSUE TITLE
Улучшение: Discord, nftables, динамический адрес-лист.

### ISSUE THREAD

**Issue by janeblower** [bol-van/zapret#689]
Добрый день!

Мне очень не нравился огромный адрес лист в init.d 50-discord, поэтому я решил не использовать этот адрес лист, а динамически добавлять туда адреса, на которые идут udp коннекты по портам 50000-50099.

В nft set я добавляю адреса через dnsmasq при резолве. (только этого было недостаточно - не добавлялись адреса голосовых серверов, видимо, они не резолвятся через dnsmasq роутера)
/etc/dnsmasq.conf
```
....
nftset=/discord.gg/4#inet#zapret#discord
nftset=/discord.com/4#inet#zapret#discord
nftset=/discordapp.net/4#inet#zapret#discord
nftset=/discordapp.com/4#inet#zapret#discord
nftset=/discord.media/4#inet#zapret#discord
nftset=/discordcdn.com/4#inet#zapret#discord
nftset=/discord.co/4#inet#zapret#discord
```
Правилом я отлавливаю коннекты на нужные порты и добавляю адреса назначения в лист:
```
nft add chain inet zapret udp_filter { type filter hook prerouting priority 0\; }
nft add rule inet zapret udp_filter udp dport 50000-50099 add @discord { ip daddr }
```

Вот, как сейчас выглядит мой 50-discord:
```
# this custom script runs desync of some udp packets to discord subnets
# idea taken from community. not tested and not optimized by author.

# can override in config :
NFQWS_OPT_DESYNC_DISCORD="${NFQWS_OPT_DESYNC_DISCORD:---dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol}"
DISCORD_PORTS=${DISCORD_PORTS:-50000-50099}
DISCORD_SET_NAME=discord
alloc_dnum DNUM_DISCORD
alloc_qnum QNUM_DISCORD

zapret_custom_daemons()
{
	# $1 - 1 - run, 0 - stop

	local opt="--qnum=$QNUM_DISCORD $NFQWS_OPT_BASE $NFQWS_OPT_DESYNC_DISCORD"
	run_daemon $DNUM_DISCORD $NFQWS "$opt"
}

zapret_custom_firewall_nft()
{
	# stop logic is not required

	local f
	local first_packets_only="$nft_connbytes 1-3"
	local dest_set="ip daddr @$DISCORD_SET_NAME"
	local subnets

	local DISABLE_IPV6=1

	make_comma_list subnets $DISCORD_SUBNETS
	nft_create_set $DISCORD_SET_NAME "type ipv4_addr; timeout 1h;"
	nft_flush_set $DISCORD_SET_NAME
	nft add chain inet zapret udp_filter { type filter hook prerouting priority 0\; }
	nft add rule inet zapret udp_filter udp dport 50000-50099 add @discord { ip daddr }

	f="udp dport {$DISCORD_PORTS}"
	nft_fw_nfqws_post "$f $first_packets_only $dest_set" "" $QNUM_DISCORD
}

zapret_custom_firewall_nft_flush()
{
	# this function is called after all nft fw rules are deleted
	# however sets are not deleted. it's desired to clear sets here.

	nft_del_set $DISCORD_SET_NAME 2>/dev/null
	nft delete chain inet zapret udp_filter
}

```

P.S.: 
Я очень привык к микротикам, поэтому пользоваться nft мне было очень больно. 
Если кто-то считает, что можно реализовать как-то иначе/красивее/корректнее - делитесь идеями и примерами.

P.S.2:
Наверное, лучше перенести этот пост в дискуссии.

**Comment by bol-van** [comment]
Насолько мне известно, дискорд сервера выдают IP для коннекта без домена через свой протокол. Там ничего не ресолвится.

**Comment by bol-van** [comment]
Насолько мне известно, дискорд сервера выдают IP для коннекта без домена через свой протокол. Там ничего не ресолвится.

Если все время добавлять каждый IP из портов 50000-50099, то в чем вообще смысле сета ?

**Comment by bol-van** [comment]
Почему уродство ? Есть какие-то другие способы ?

> Или вы о том, что проще не смотреть в сет, а сразу брать всё, что стучит на нужные порты?

Важен итоговый результат. У вас все будет отправляться на дурилку. Только попутно еще куда-то заноситься.
Так зачем заносить, может проще без кастома все забить в --filter-udp в основные опции ?

**Comment by janeblower** [comment]
> Так зачем заносить, может проще без кастома все забить в --filter-udp в основные опции ?

А у меня оно так не поехало почему-то -_-

**Comment by bol-van** [comment]
Наверно не хватает перенаправления через NFQWS_PORTS_UDP

**Comment by janeblower** [comment]
> Насолько мне известно, дискорд сервера выдают IP для коннекта без домена через свой протокол. Там ничего не ресолвится.

Я последил внимательнее за поведениями, поотлавливал запросы, посмотрел акулой:
При коннете к войс-каналу летит dns запрос (условно) russiaXXXX.discord.MEDIA
russiaXXXX.discord.media отдаёт ip уже непосредственно голосового канала, который можно так же получить, зарезолвив russiaXXXX.discord.GG (xxxx совпадают).

Можно прилепить хук на dns, который будет отлавливать запрос russiaXXXX.discord.MEDIA, менять в нём домен 1го уровня и тоже его резолвить.

Имхо, оверкилл - да, не надо будет держать лист всех ip дискорда - тоже да.

**Comment by bol-van** [comment]
Можно убрать заполнение ipset и сделать через dnsmasq вот так
https://www.monotux.tech/posts/2024/08/dnsmasq-netfilter/
