### ISSUE TITLE
wssize  + hostlist

### ISSUE THREAD

**Issue by mildok** [bol-van/zapret#690]
Здравствуйте, здесь:
https://github.com/bol-van/zapret/issues/608#issuecomment-2416084267

Вы писали что:
> wssize несовместим с хостлистом

Я перепробовал разные параметры - какое-то время некоторые работали, но потом переставали работать.
Позже нашёл параметр wssize и с ним достаточно долго всё работает.

Но он применяется ко всем сайтам - и тем которые мне не нужно чтобы применялось.

А опция --hostlist= как вы и написали не работает с wssize.

Подскажите, пожалуйста, hostlist пока не реализована работа с wssize, или же wssize это невозможно впринципе из-за их природы?

**Comment by bol-van** [comment]
Второе.
Применение идет начиная прямо с SYN пакета.
Хост выцепляется  только из первых пакетов с данными

**Comment by mildok** [comment]
Спасибо
