### ISSUE TITLE
Сразу закрывается окно zapret

### ISSUE THREAD

**Issue by Bomb1na** [bol-van/zapret#692]
Пытался запустить discord.bat и все general, но все сразу закрываются, уже все антивирусники снес, антивирусник от windows выключил, но проблема остается, просто запускаешь файл, например от имени администратора, он открывается на мили секунду и закрывается сразу, честно, уже много чего пытался сделать, ни чего не помогло, у меня Win10 провайдер Планета

**Comment by bol-van** [comment]
Это сборка, не оригинал. Вопрос к сборщикам
