### ISSUE TITLE
ТГ

### ISSUE THREAD

**Issue by Scrimaging** [bol-van/zapret#693]
С запретом не грузит медиафайлы в тг и спотик, так же не работает впн

**Comment by Marvefect** [comment]
Используй (авто)хостлист в качестве метода фильтрации, готовые уже лежат в сети

**Comment by HentayHentay** [comment]
Несколько путей решения проблемы
- закинуть хосты тг в исключения запрета
- закинуть хосты тг в запрет  (будет обработка запретом)
- кустомс (будет обработка запретом)

Выбираем один пункт и реализуем

**Comment by Scrimaging** [comment]
> Несколько путей решения проблемы
> 
> * закинуть хосты тг в исключения запрета (тг не ограничен)
> * закинуть хосты тг и спотик в запрет  (будет обработка запретом)
> * кустомс (будет обработка запретом)
> 
> Выбираем один пункт и реализуем

а как это сделать, я пенёк

**Comment by HentayHentay** [comment]
> > Несколько путей решения проблемы
> > 
> > * закинуть хосты тг в исключения запрета (тг не ограничен)
> > * закинуть хосты тг и спотик в запрет  (будет обработка запретом)
> > * кустомс (будет обработка запретом)
> > 
> > Выбираем один пункт и реализуем
> 
> а как это сделать, я пенёк

1 - найти/выяснить через запросы гугла/яндекса хосты
2 - в зависимости от фильтра - занести в /ipset/zapret-hosts-auto или  /ipset/zapret-hosts-user (если хотим обработки запросов)
3 - если не хотим то в  /ipset/zapret-hosts-user-exclude
PS Те же действие, если выбран фильтр ipset, но только с содержимом ip

Кустом писать это уже сложный уровень ^^

**Comment by Scrimaging** [comment]
> > > Несколько путей решения проблемы
> > > 
> > > * закинуть хосты тг в исключения запрета (тг не ограничен)
> > > * закинуть хосты тг и спотик в запрет  (будет обработка запретом)
> > > * кустомс (будет обработка запретом)
> > > 
> > > Выбираем один пункт и реализуем
> > 
> > 
> > а как это сделать, я пенёк
> 
> 1 - найти/выяснить через запросы гугла/яндекса хосты 2 - в зависимости от фильтра - занести в /ipset/zapret-hosts-auto или /ipset/zapret-hosts-user (если хотим обработки запросов) 3 - если не хотим то в /ipset/zapret-hosts-user-exclude
> 
> Кустом писать это уже сложный уровень ^^
> 
> PS Те же действие, если выбран фильтр ipset, но только с содержимом файлов соответственно `/ipset/*-ip-*`
> 
> PS2 Но если хотим быть уверены в правильности стратегии, то нужно проверить хосты через блокчек и подобрать/выбрать стратегию обхода

спасибо, попробую, хотя и не понял ничего 💯

**Comment by HentayHentay** [comment]
> спасибо, попробую, хотя и не понял ничего 💯

Для новичков самый легий режим - автохост
Но при неоткрытые сайта нужно обновить не один раз страницу (список ведётся автоматически и вносится только то, что нужно.)

**Comment by Scrimaging** [comment]
> > спасибо, попробую, хотя и не понял ничего 💯
> 
> Для новичков самый легий режим - автохост Но при неоткрытые сайта нужно обновить не один раз страницу (список ведётся автоматически и вносится только то, что нужно.)
> 
> Работает хорошо, когда выбрана правильная стратегия обхода

либо я еблан, либо хз
хосты тг я не могу найти вообще, выдает хосты тг ботов
а если и найду, то я не знаю как кинуть исключение в запрет
(сорян за тупизм)

**Comment by HentayHentay** [comment]
> > > спасибо, попробую, хотя и не понял ничего 💯
> > 
> > 
> > Для новичков самый легий режим - автохост Но при неоткрытые сайта нужно обновить не один раз страницу (список ведётся автоматически и вносится только то, что нужно.)
> > Работает хорошо, когда выбрана правильная стратегия обхода
> 
> либо я еблан, либо хз хосты тг я не могу найти вообще, выдает хосты тг ботов а если и найду, то я не знаю как кинуть исключение в запрет (сорян за тупизм)

> 3 - если не хотим то в /ipset/zapret-hosts-user-exclude
Сюда 
t.me
telegram.org
telegram.me
telegram.space

Ищем по whois и будет счастье.
