### ISSUE TITLE
проблемы с обходом блокировки youtube (googlevideo.com)

### ISSUE THREAD

**Issue by ryazh3nka** [bol-van/zapret#695]
здравствуйте! спасибо за замечательное решение, с помощью программы открывается x.com и discord. Однако возникает проблема с заходом на ютуб: на сайт зайти получается, но проигрывание видео виснет. Распишу проблему подробнее. (прошу прощения если не понимаю чего-то очевидного)

мой nfqws конфиг, пользуюсь nftables:
> NFQWS_PORTS_TCP=80,443
> NFQWS_PORTS_UDP=443
> NFQWS_TCP_PKT_OUT=9
> NFQWS_TCP_PKT_IN=3
> NFQWS_UDP_PKT_OUT=9
> NFQWS_UDP_PKT_IN=0
> NFQWS_PORTS_TCP_KEEPALIVE=
> NFQWS_PORTS_UDP_KEEPALIVE=
> NFQWS_OPT="
> --dpi-desync=fake --dpi-desync-ttl=7"

кроме zapret пробовал альтернативные решения типа spoofdpi, powertunnel, etc, и везде одна и та же ошибка с подключением к googlevideo.com. в issues почитал ваш ответ на подобную проблему (от 1 августа), но, как я понял, формат конфигурационного файла обновился. 

система: пользуюсь системой инициализации runit, закидываю файл из /opt/zapret/init.d/runit в /var/services. все dependencies установлены. во время поиска решений через blockcheck увидел предупреждение о том, что curl собран без поддержки quic.

скажите, пожалуйста, каковы пути возможного решения?

**Comment by ryazh3nka** [comment]
P.S: запускаю ./install_easy.sh следующим образом:

> select flow offloading: none
> enable tpws socks mode on port 987? N
> enable tpws transparency mode? N
> enable nfqws? Y
> LAN interface: NONE
> WAN interface: ANY
> select filtering: none

в ./blockchech.sh:
> check http? Y
> check https tls 1.2? Y
> check https tls 1.3? Y

**Comment by HentayHentay** [comment]
> скажите, пожалуйста, каковы пути возможного решения?

Открыть ютуб, начать проигрывать видео и отловить обращение к  googlevideo.com, 
Вдруг у нас сменился местный GGC.

Далее его адрес закидываем в блокчекер (запрет в этот момент выключаем) и смотрим на результаты. 
Скорее будут обходы по TCP 443
QUIC потребует UDP 443 , но по сути там фейки идут в отличие от TCP

**Comment by ryazh3nka** [comment]
> Открыть ютуб, начать проигрывать видео и отловить обращение к googlevideo.com, Вдруг у нас сменился местный GGC.
глупый вопрос, как можно отловить это обращение? в firefox искать во вкладке network? из того что знаю, смысла вбивать googlevideos.com в blockcheck.sh нет, поэтому нужно искать поддомены? если задаю супер странный вопрос и я не понимаю самых основ, можете просто в ответе ссылку прикрепить на мануал откуда стоит продолжить изучение

> Не указан `MODE_FILTER`
не увидел этого параметра в скрипте, мне нужно отредачить конфиг?

**Comment by HentayHentay** [comment]
> глупый вопрос, как можно отловить это обращение? в firefox искать во вкладке network? из того что знаю, смысла вбивать googlevideos.com в blockcheck.sh нет, поэтому нужно искать поддомены? если задаю супер странный вопрос и я не понимаю самых основ, можете просто в ответе ссылку прикрепить на мануал откуда стоит продолжить изучение

А ещё может творить и вытворять браузер некоторые неприятности)
В инструментах разработчика - сеть


> не увидел этого параметра в скрипте, мне нужно отредачить конфиг?

Сорри , я уже увидел
В конфигурации данный параметр присутствует в текстовом виде.

**Comment by ryazh3nka** [comment]
> MODE_FILTER=none

 из zapret/config
 
 попытался поймать это обращение, но в network увидел только следующие запросы:

> GET 
> https://www.youtube.com/watch?v=SLEBIJ9DTAI
> POST
> scheme: https; Host: 443---sn-gxuog0-n8me.googlevideo.com
> filename: videoplayback

и длинная ссылка при даблклике на последний запрос.

**Comment by HentayHentay** [comment]
> и длинная ссылка при даблклике на последний запрос.

https://rr13---sn-n8v7knel.googlevideo.com/* <- нас только данная часть ссылки интересует
Далее берём rr13---sn-n8v7knel.googlevideo.com и в блокчек его вставляем и ждем вердикта.


> Host: 443---sn-gxuog0-n8me.googlevideo.com

ссылка не полная. Отсутствует некоторая часть

**Comment by eastone11** [comment]
> из zapret/config
> 
> > MODE_FILTER=none
> 
> попытался поймать обращение к googlevideo, но в network увидел только следующие запросы:
> 
> > GET
> > https://www.youtube.com/watch?v=SLEBlJ9DTAI
> > POST
> > scheme: https; Host: 443---sn-gxuog0-n8me.googlevideo.com
> > filename: videoplayback
> 
> и длинная ссылка при даблклике на последний запрос.


тут с картинками, может поможет
https://ntc.party/t/%D0%BF%D0%BE%D0%B4%D0%B1%D0%BE%D1%80-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B5%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B0-%D0%B4%D0%BB%D1%8F-ggc-%D1%8E%D1%82%D1%83%D0%B1%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-blockcheck/10060

**Comment by HentayHentay** [comment]
> POST
> scheme: https
> Host: rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com
> filename: videoplayback

А вот и хост для нахождения стратегии 


> GET
> scheme: https
> Host: rr2---sn-q4fl6n6r.googlevideo.com
> filename: videoplayback
> status: 403

Не правильный хост.  GET гуглвидео не отвечает.

**Comment by ryazh3nka** [comment]
спасибо за помощь! поставил на проверку, буду ждать. прошу прощения за ошибки в урлах, руками их перепечатывал потому что почему-то не могу копировать на dwm под x11 из f12-меню в фаерфоксе. извините за то что запутал. если возникнут проблемы, отпишусь через час, ещё раз большое спасибо!

**Comment by ryazh3nka** [comment]
попробовал новые решения, ютуб перестал загружаться.

блокчек выдал следующее:

> * SUMMARY
> ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_http : working without bypass
> ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_https_tls12 : tpws --split-pos=1 --oob
> ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_https_tls12 : nfqws --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1
> ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_https_tls13 : tpws --split-pos=2
> ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_https_tls13 : nfqws --dpi-desync=fake --dpi-desync-ttl=9 --dpi-desync-fake-tls=0x00000000

почистил /var/service от файлов программы, перезапустил dnscrypt-proxy, dhcpcd и wpa_supplicant. запустил install-easy.sh. в случае с nfqws протыкал аналогично первому сообщению в этом треде изменив конфиг поочерёдно на каждый из предложенных. youtube.com и x.com перестали открываться вообще

**Comment by HentayHentay** [comment]
> * ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_https_tls12 : nfqws --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1
`--filter-tcp=443` - данная стратегия. 

> * ipv4 rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com curl_test_https_tls13 : nfqws --dpi-desync=fake --dpi-desync-ttl=9 --dpi-desync-fake-tls=0x00000000

`--filter-tcp=443` - данная стратегия. 

Quic имеет стандартные настройки:
`--filter-udp=443 --dpi-desync=fake ` (можно взять из config.def*)

Не забываем перезапустить запрет. А то если ты ставишь так


NFQWS_OPT="
--dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1
"
То ты себе интернет ломаешь )

**Comment by ryazh3nka** [comment]
спасибо за быстый ответ! понял, что -- упс -- так и делал. теперь конфиг выглядит так:

> NFQWS_PORTS_TCP=80,443
> NFQWS_PORTS_UDP=443
> NFQWS_TCP_PKT_OUT=9
> NFQWS_TCP_PKT_IN=3
> NFQWS_UDP_PKT_OUT=9
> NFQWS_UDP_PKT_IN=0
> NFQWS_PORTS_TCP_KEEPALIVE=
> NFQWS_PORTS_UDP_KEEPALIVE=
> NFQWS_OPT="
> --filter-tcp=443"

после этого:
> $ sudo rm -rf /var/service/zapret/
> $ sudo cp -r /opt/zapret/init.d/runit/zapret/ /var/service/
> $ sudo sv restart zapret

по-прежнему не работает. единственное чего не сделал из вашей инструкции -- не настроил Quic. честно говоря, немного не разобрался, мне их ручками в конфиг в /opt/zapret записать? 

ещё есть подозрение что я пока переустанавливал программы у меня могли съехать порты. NFQWS_PORTS стоят 80, 443, а dnscrypts-proxy слушает порт 53. может быть лезу туда где мало смыслю

**Comment by HentayHentay** [comment]
*много мата*

```
NFQWS_OPT="
--filter-tcp=443  --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --new
--filter-udp=443 --dpi-desync=fake  --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 
"
```

Или

```
NFQWS_OPT="
--filter-tcp=443  --dpi-desync=split  --dpi-desync=fake --dpi-desync-ttl=9 --dpi-desync-fake-tls=0x00000000 --new
--filter-udp=443 --dpi-desync=fake  --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 
"
```

**Comment by bol-van** [comment]
Пробелов может быть сколько угодно между переменными . Это так называемый whitespace

**Comment by HentayHentay** [comment]
@bol-van 

Спасибо за информацию. Успокоили

**Comment by ryazh3nka** [comment]
спасибо за терпение.. поправил, теперь конфиг корректный. по поводу IFACE_WAN -- стоит wlp2s0, вроде как нужный интерфейс. ютуб работает, но видео по-прежнему в бесконечной загрузке. поисследовал, пинганул адреса из запросов, вроде как тоже работает.

конфиг:

> NFQWS_PORTS_TCP=80,443
> NFQWS_PORTS_UDP=443
> NFQWS_TCP_PKT_OUT=9
> NFQWS_TCP_PKT_IN=3
> NFQWS_UDP_PKT_OUT=9
> NFQWS_UDP_PKT_IN=0
> NFQWS_PORTS_TCP_KEEPALIVE=
> NFQWS_PORTS_UDP_KEEPALIVE=
> NFQWS_OPT="
> --filter-tcp=443 --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --new
> --filter-udp=443 --dpi-desync=fake --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6"

> Host: rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com
> Host: rr3---sn-gxuog0-n8me.googlevideo.com

**Comment by HentayHentay** [comment]
Пробуй на хроме
Часто мазилла или другие немного тупят 

`--filter-tcp=443 --dpi-desync=split --dpi-desync=fake --dpi-desync-ttl=9 --dpi-desync-fake-tls=0x00000000 --new`
Замени строчку если не менял. 
`--filter-udp=443 --dpi-desync=fake --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6"`

Может потребоваться докинуть фейк  `--filter-udp=443 --dpi-desync=fake --filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6`  в `--filter-udp=443 --dpi-desync=fake --filter-udp=443 --dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/(указать фейковый квик) --dpi-desync-repeats=6 --dpi-desync-cutoff=d3`

**Comment by ryazh3nka** [comment]
спасибо большое мистер хентай!! всё работает отлично (правда хром тупит. зато в мозилле всё ок хд)

мой конфиг:
> NFQWS_PORTS_TCP=80,443
> NFQWS_PORTS_UDP=443
> NFQWS_TCP_PKT_OUT=9
> NFQWS_TCP_PKT_IN=3
> NFQWS_UDP_PKT_OUT=9
> NFQWS_UDP_PKT_IN=0
> NFQWS_PORTS_TCP_KEEPALIVE=
> NFQWS_PORTS_UDP_KEEPALIVE=
> NFQWS_OPT="
> --filter-tcp=443 --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --new
> --filter-udp=443 --dpi-desync=fake --filter-udp=443 --dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin  --dpi-desync-repeats=6 --dpi-desync-cutoff=d3"

если всё окей, ишью закрою. спасибо ещё раз:))

**Comment by NewUse** [comment]
> спасибо большое мистер хентай!! всё работает отлично (правда хром тупит. зато в мозилле всё ок хд)
> 
> мой конфиг:
> 
> > NFQWS_PORTS_TCP=80,443
> > NFQWS_PORTS_UDP=443
> > NFQWS_TCP_PKT_OUT=9
> > NFQWS_TCP_PKT_IN=3
> > NFQWS_UDP_PKT_OUT=9
> > NFQWS_UDP_PKT_IN=0
> > NFQWS_PORTS_TCP_KEEPALIVE=
> > NFQWS_PORTS_UDP_KEEPALIVE=
> > NFQWS_OPT="
> > --filter-tcp=443 --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --new
> > --filter-udp=443 --dpi-desync=fake --filter-udp=443 --dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin  --dpi-desync-repeats=6 --dpi-desync-cutoff=d3"
> 
> если всё окей, ишью закрою. спасибо ещё раз:))

кажется там задублироваласт строка с udp фильтром

**Comment by dexeltod** [comment]
@ryazh3nka в какой папке ты нашел этот конфиг? Я явно вижу обычный config файл, который выглядит не так как у тебя.

**Comment by ryazh3nka** [comment]
@dexeltod да, я через install_easy заменил эти значения. наверное, не совсем корректно было это "конфигом" называть

**Comment by ryazh3nka** [comment]
> кажется там задублироваласт строка с udp фильтром

и правда, ночью уже видеть разучился

**Comment by ryazh3nka** [comment]
резюмирую если вдруг кто-то столкнётся с похожей проблемой:

Проблема: грузится ютуб, не грузятся видео, идёт бесконечная загрузка.
Решение: найти в f12-меню обращение к googlevideo.com во время загрузки видео, прогнать его через blockcheck, добавить способ обхода в конфиг через install-easy, добавить строчку с фейком из комментария выше если не помогло.

в моём случае:

> NFQWS_PORTS_TCP=80,443
> NFQWS_PORTS_UDP=443
> NFQWS_TCP_PKT_OUT=9
> NFQWS_TCP_PKT_IN=3
> NFQWS_UDP_PKT_OUT=9
> NFQWS_UDP_PKT_IN=0
> NFQWS_PORTS_TCP_KEEPALIVE=
> NFQWS_PORTS_UDP_KEEPALIVE=
> NFQWS_OPT="
> --filter-tcp=443 --dpi-desync=split --dpi-desync-ttl=3 --dpi-desync-split-pos=1 --new
> --filter-udp=443 --dpi-desync=fake --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin --dpi-desync-repeats=6 --dpi-desync-cutoff=d3"

**Comment by NewUse** [comment]
> что делать, если blockcheck на домен googlevideo.com пишет nfqws: not working в результатах теста?
> 
> а во время работы на всех запросах ошибка timed out after 2000 milliseconds

а rutracker.org?

**Comment by ryazh3nka** [comment]
насколько знаю, нет смысла в blockcheck вставлять сам домен googlevideo.com. нужно во время загрузки в f12 отловить обращение к хосту (у меня было rr2---sn-ug5onuxaxjvh-n8v6.googlevideo.com)

**Comment by bol-van** [comment]
Напрямую googlevideo.com не используется. Там выдается сертификат от www.google.com, что будет выдавать каждый раз ошибку сертификата. Попытка блокчекнуть googlevideo.com равносильна долбежке лбом о бетон
```
  subject: CN=www.google.com
*  start date: Oct 21 08:38:45 2024 GMT
*  expire date: Jan 13 08:38:44 2025 GMT
*  subjectAltName does not match hostname googlevideo.com
* SSL: no alternative certificate subject name matches target hostname 'googlevideo.com'
* closing connection #0
curl: (60) SSL: no alternative certificate subject name matches target hostname 'googlevideo.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.

```

**Comment by Goosegit11** [comment]
я не использовал googlevideo.com напрямую, смотрел какой домен используется через F12 и вставлял его. запрос шёл POST 

rr5---sn-n3toxu-axqs.googlevideo.com

**Comment by Goosegit11** [comment]
@NewUse  на рутрекер нашлась стратегия под https и quic, вставил её.
рутрекер открывается, ютуб открывается, видео не грузит.

**Comment by NewUse** [comment]
> @NewUse на рутрекер нашлась стратегия под https и quic, вставил её. рутрекер открывается, ютуб открывается, видео не грузит.

вот теперь ищи один из доменов гуглвидео (rr*)через браузер и подбирай стратегию для этого домена, для udp fake заголовок нужно взять из готовых для гугла, на сколько я помню, но тут лучше, конечно, автор подскажет.

**Comment by Goosegit11** [comment]
прочитай выше

**Comment by NewUse** [comment]
> В блокчеке есть тесты на IP и port block. Первым делом надо этот вариант подтвердит или исключить. Но это требует ручной интерпретации, автомат не скажет да или нет
> 
> Потом надо попробовать прогон с гугл фейками и повторами. PKTWS_EXTRA="--dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-repeats=11"

кажется это стоит всё объединить в один пост и подправть первый пост темы #200 в discussion
