### ISSUE TITLE
Инсталлятор

### ISSUE THREAD

**Issue by TyroSpy** [bol-van/zapret#697]
Когда запускаю install_easy.sh дохожу до пункта выбора режима MODE_FILTER и если выбрать режим autohostlist, то следующего пункта, который должен быть: "do you want to auto download ip/host list (default : N)" - его не предлагается. Роутер с OpenWrt. zapret v67

**Comment by bol-van** [comment]
Так и задумано. Зачем скачивать листы, если работает по авто листу ?

**Comment by HentayHentay** [comment]
Но всегда можно в конфиг пихнуть в самый конец лист.
Правда он будет не рабочим....

**Comment by TyroSpy** [comment]
> Но всегда можно в конфиг пихнуть в самый конец лист, если вы это хотите Правда он будет не рабочим

Так и пихаю руками, Все работает

**Comment by bol-van** [comment]
> Так было раньше, а теперь вы переделали логику, вот цитата из доки: "autohostlist - режим hostlist + распознавание блокировок и ведение автоматического листа"

В этой части ничего не переделалось. zapret-hosts-user.txt работает как дополнительный источник доменов при MODE_FILTER=autohostlist. Но если там окажется скачанный zapret-hosts.{txt|gz}, он тоже будет применен.

**Comment by TyroSpy** [comment]
Ну так я ровно про это и пишу, только при моем желании, как он там окажется если инсталлятор не предлагает его добавить

**Comment by bol-van** [comment]
А смысл его добавлять, если работает автолист ?

**Comment by TyroSpy** [comment]
Ну как я понимаю логику, в автолист должно попадать только то, чего нет в хостлистах

**Comment by bol-van** [comment]
Если включить скачивание листов, там практически все будет

**Comment by TyroSpy** [comment]
Ну я тут решил записаться в тестировщики рефильтра, там много чего нет

**Comment by bol-van** [comment]
OK, сделал возможность выбора.
Об этом еще 1 чел просил давненько
