### ISSUE TITLE
binary for 32 bit

### ISSUE THREAD

**Issue by gvsurenderreddy** [bol-van/zapret#7]
Hello is it possible for me to use for voip application to escape dpi

**Comment by bol-van** [comment]
It depends how your voip works. Which protocols its based on and what and how your dpi filters.
This software is mostly oriented to bypass http blocking. To bypass other protocol blocks you need some sort of VPN or proxy

**Comment by gvsurenderreddy** [comment]
thank you sir do you have binary for X86 please

**Comment by bol-van** [comment]
Binaries are mostly intended for routers. Its not trivial to cross-compile for them. Routers mostly use mips or arm cpu. Even if you have PC router board running openwrt  I doubt it does not support x64, just install 64 bit os.
But if you're on desktop linux then you dont need binaries.  Just install gcc and 'make'
