### ISSUE TITLE
Не собирается под OpenBSD 7.6 -stable

### ISSUE THREAD

**Issue by ssh3** [bol-van/zapret#700]
Привет. Низкий поклон за работу!

Предположительно после коммита 8b4b8c3 перестала собираться с `make bsd`

> ./params.h:17:10: fatal error: 'wordexp.h' file not found
> #include <wordexp.h>

Я понимаю, что платформа не приоритетная, но вдруг. :)

Полный лог сборки прикрепил.

[zapret-building.log](https://github.com/user-attachments/files/17610170/zapret-building.log)

**Comment by bol-van** [comment]
Действительно, в openbsd нет wordexp.
Он используется для загрузки конфига из файла

**Comment by bol-van** [comment]
Сделал условную компиляцию. Если openbsd, функция чтения конфига из файла отключается

**Comment by ssh3** [comment]
Я правильно понимаю, что при таком подходе, все необходимые параметры следует при старте демона перечислить?

**Comment by bol-van** [comment]
Именно так.
реализация wordexp не просто так убрана из openbsd. У нее есть определенные секурити косяки

**Comment by ssh3** [comment]
Теперь собирается. Спасибо.
