### ISSUE TITLE
запрет умирает после запуска, хз что делать

### ISSUE THREAD

**Issue by Snowy-Fluffy** [bol-van/zapret#702]
было дело что создавал кучу правил для инитов, по итогу у меня при запуске какой то из инитов рандомно умирал, приходилось перезапускать, с того времени, я вроде бы удалил весь тот не рабочий мусор, недавно решил поставить последний комит запрета, предыдущий прослужил мне 3 месяца. вообщем по итогу, все ставлю, устанавливаю, вроде как без ошибок, но, теперь ебаный запрет падает. 
перезагрузка сервиса, установка других правил, переустановка запрета и т.д. не помогло.

![image](https://github.com/user-attachments/assets/07322124-dfcd-4e24-99ba-b8bbe886aef7)

Дополнено: выполнил откат на предыдущую версию, и все магическим образом запустилось. Правда дискорд на текущей стратегии перестал открываться вообще, ну это уже мои проблемы. Буду благодарен если мне помогут решить ситуацию с новым запретом

**Comment by Snowy-Fluffy** [comment]
Здравствуйте, запрет прежде всего расчитан на все linux - системы, в том числе и на openwrt. Моя система иницилизации не должна влиять на работу запрета, не прямо, не косвенно. Так же я не могу понять, какой смысл в этом обсуждении будут иметь характеристики моего "пылесоса"?

**Comment by Snowy-Fluffy** [comment]
Здравствуйте, запрет прежде всего расчитан на все linux - системы, в том числе и на openwrt. Моя система иницилизации не должна влиять на работу запрета, не прямо, не косвенно. Так же я не могу понять, какой смысл в этом обсуждении будут иметь характеристики моего "пылесоса"?

**Comment by Snowy-Fluffy** [comment]
Здравствуйте, запрет прежде всего расчитан на все linux - системы, в том числе и на openwrt. Моя система иницилизации не должна влиять на работу запрета, не прямо, не косвенно. Так же я не могу понять, какой смысл в этом обсуждении будут иметь характеристики моего "пылесоса"?

**Comment by Snowy-Fluffy** [comment]
большинство пользователей запрета прежде всего используют его на персональных компьютерах, где доминирует ситемный демон

**Comment by bol-van** [comment]
Основные платформы по частоте использования - openwrt и windows.
Linux мало кто юзает.
Судя по логу тут не были включены в конфиге ни tpws, ни nfqws. Он вхолостую запускается.
