### ISSUE TITLE
Discord: "Не установлен маршрут"

### ISSUE THREAD

**Issue by insidethehearts** [bol-van/zapret#706]
Всех приветствую, очень хочу наконец перейти на Linux, но, пока что из за неработоспособности дискорда не могу.
Тестирую на ноуте.

Если кратко, и по делу: 
При подключению к голосовому чату бесконечный цикл от "Подключение к RTC" до "Не установлен маршрут"
Конфиг прилагается

Если длинно и не по делу:
Сначала пытался через TPWS, только потом узнал что он с UDP не работает, завёл на NQWFS, все работает, кроме как раз таки войса в дискорде. Пытался несколько дней сам, не получается, не хватает видимо знаний. Прошу вас, уважаемые форумные друзья помочь мне разобраться в этой ситуации и всё починить, и наконец слезть с винды. Спасибо!

Кфг без комментариев:

> 
> FWTYPE=iptables
> 
> SET_MAXELEM=522288
> IPSET_OPT="hashsize 262144 maxelem $SET_MAXELEM"
> IP2NET_OPT4="--prefix-length=22-30 --v4-threshold=3/4"
> IP2NET_OPT6="--prefix-length=56-64 --v6-threshold=5"
> AUTOHOSTLIST_RETRANS_THRESHOLD=3
> AUTOHOSTLIST_FAIL_THRESHOLD=3
> AUTOHOSTLIST_FAIL_TIME=60
> AUTOHOSTLIST_DEBUGLOG=0
> 
> MDIG_THREADS=30
> 
> GZIP_LISTS=1
> 
> DESYNC_MARK=0x40000000
> DESYNC_MARK_POSTNAT=0x20000000
> 
> TPWS_SOCKS_ENABLE=0
> TPPORT_SOCKS=987
> TPWS_SOCKS_OPT="
> --filter-tcp=80 --methodeol <HOSTLIST> --new
> --filter-tcp=443 --split-tls=sni --disorder <HOSTLIST>
> "
> 
> TPWS_ENABLE=0
> TPWS_PORTS=80,443
> TPWS_OPT="
> --filter-tcp=80 --methodeol <HOSTLIST> --new
> --filter-tcp=443 --split-tls=sni --disorder <HOSTLIST>
> "
> 
> NFQWS_ENABLE=1
> NFQWS_PORTS_TCP=80,443
> NFQWS_PORTS_UDP=443,50000-65535
> NFQWS_TCP_PKT_OUT=$((6+$AUTOHOSTLIST_RETRANS_THRESHOLD))
> NFQWS_TCP_PKT_IN=3
> NFQWS_UDP_PKT_OUT=$((6+$AUTOHOSTLIST_RETRANS_THRESHOLD))
> NFQWS_UDP_PKT_IN=0
> #NFQWS_PORTS_TCP_KEEPALIVE=80
> #NFQWS_PORTS_UDP_KEEPALIVE=
> NFQWS_OPT="
> --filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-any-protocol --dpi-desync-fooling=md5sig <HOSTLIST_NOAUTO> --new
> --filter-tcp=443 --dpi-desync=fake,disorder2 --dpi-desync-any-protocol --dpi-desync-fooling=md5sig <HOSTLIST_NOAUTO> --new
> --filter-udp=443 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-repeats=6 <HOSTLIST_NOAUTO>
> "
> 
> MODE_FILTER=none
> 
> FLOWOFFLOAD=donttouch
> 
> INIT_APPLY_FW=1
> 
> DISABLE_IPV6=1

Вероятно, проблема глупая, но никто не говорил что я умный. Еще раз спасибо.

**Comment by HentayHentay** [comment]
50-discord в init.d размещён ?

**Comment by insidethehearts** [comment]
Нет. Ни в /opt/zapret/init.d/ ни в /opt/zapret/init.d/sysv/custom.d

**Comment by HentayHentay** [comment]
> Нет. Ни в /opt/zapret/init.d/ ни в /opt/zapret/init.d/sysv/custom.d

Вот и ответ. 
Найдите в примерах данный файлик и разместите. 

Сайты обходятся стандартно

PS не раз разбиралось уже данная проблема.

**Comment by insidethehearts** [comment]
@HentayHentay спасибо, ты сделал мой день!
Нет слов чтобы отблагодарить тебя. Спасибо огромное!

### Если вдруг еще найдутся такие как я, объясню что я сделал, на всякий случай
Скопировал скрипт командой 
> sudo cp /opt/zapret/init.d/sysv/custom.d.examples/50-discord /opt/zapret/init.d/custom.d/50-discord`
Перезапустил zapret
> sudo systemctl restart zapret

@HentayHentay лучший!

**Comment by bol-van** [comment]
--desync-any-protocol непонятно накой тут написано
