### ISSUE TITLE
РКН внес в реестр zapret, хорошая работа!

### ISSUE THREAD

**Issue by dttric** [bol-van/zapret#708]
иронично что РКН запретил запрет XD
![image](https://github.com/user-attachments/assets/c73bd1d1-05fe-4c91-8bc6-20e46e5f0014)

**Comment by HentayHentay** [comment]
Вопрос только в том, что в блокировке(в листе)
Но вот на самом сайте выдает данную страницу, хотя гитхаб не в бане(какое мило противоречие)

**Comment by bol-van** [comment]
Гитхаб в бане ?

**Comment by bol-van** [comment]
Они не могут заблокировать отдельные страницы под https.
Это может сделать только сам github

**Comment by dttric** [comment]
> Они не могут заблокировать отдельные страницы под https.
> Это может сделать только сам github

тогда я не знаю но оно есть в реестре значит что-то сделают

**Comment by Storik4pro** [comment]
> Они не могут заблокировать отдельные страницы под https. Это может сделать только сам github

Мне кажется, что новости про "аналог гитхаб" были не просто так.
Хотя, может, они дают гитхабу время, чтобы он заблокировал доступ к репозиторию?..

**Comment by dttric** [comment]
> > Они не могут заблокировать отдельные страницы под https. Это может сделать только сам github
> 
> Мне кажется, что новости про "аналог гитхаб" были не просто так.
> Хотя, может, они дают гитхабу время, чтобы он заблокировал доступ к репозиторию?..

видимо пора сделать бекап всего на гитлаб

**Comment by bol-van** [comment]
Я не буду гоняться и делать репу доступную для России. И воевать с РКН тоже не собираюсь.
Заблокируют так заблокируют. Кому надо - скачает. Будет востребовано - разнесут и без меня

**Comment by DeltaOmegas** [comment]
> Не, ну вроде эффективно заблокировали 😄
> 
> yandex.eu ![image](https://private-user-images.githubusercontent.com/35381259/383253796-49a3a043-b967-421b-96db-3e92075cacd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzM0NTcsIm5iZiI6MTczMDgzMzE1NywicGF0aCI6Ii8zNTM4MTI1OS8zODMyNTM3OTYtNDlhM2EwNDMtYjk2Ny00MjFiLTk2ZGItM2U5MjA3NWNhY2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE4NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OTE0ZTM5OWYyY2ViYTAzYjFhOGFlMTVjNjRiYjliZTdjNjZlYzRkZjc3YjU3OTUwYTY1ZGNhMGIxNmQ4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWHmIM6nTYLL9ayTkakL6rWU2UDgQ5yvma5VwZyjGEE) yandex.ru ![image](https://private-user-images.githubusercontent.com/35381259/383254045-2e464cdc-cd71-46e0-9046-a373783f2b17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzM0NTcsIm5iZiI6MTczMDgzMzE1NywicGF0aCI6Ii8zNTM4MTI1OS8zODMyNTQwNDUtMmU0NjRjZGMtY2Q3MS00NmUwLTkwNDYtYTM3Mzc4M2YyYjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE4NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYjdiNWQ3MGY5YzQ4ODNjNGZlNTFjZmNhYjE1NDUxMWZmM2M4ZGI4OGYyYmFhNTM0Y2E2ZTBhYmQ4MzVjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g66B7skcjCIErNivcFNwUkDKcfusU7ViJsDvk7tpu0U)

А кто-то яндексом пользуется ещё?

**Comment by Fenrir-0xFF** [comment]
> Это может сделать только сам github
Сталкивался уже с этим на гитхабе, тем кто из рашки вылезит сообщение что заблочено, с иностранных ip откроется норм. 
На крайняк можно пересоздать репозиторий, раньше блокировка слетала исправили это сейчяс или нет ХЗ. 
Да и никто не мешает создавать клоны репозитория, только порядковый номер менять по мере блокировки раз в месяц

**Comment by electrifying** [comment]
Поясните для быдла, а может ли ркн на практике если захочет сломать работу запрет так, что бы ни одна стратегия вообще больше не работала?

**Comment by bol-van** [comment]
Они выделили 60 лярдов на развитие системы блокировок до 2030 года.
Могут, но им придется нарастить вычислительные мощности значительно

**Comment by electrifying** [comment]
> Заодно будут более продвинуто блокировать впн.

Даже связку vless+xray смогут блокнуть?

**Comment by bol-van** [comment]
> Даже связку vless+xray смогут блокнуть?

Могут и до этого дойти. Активная автоматизированная охота на VPN и автоматический блок IP.
В TM что-то такое уже давно практикуется.
Есть парочка универсальных способов.
Если от юзера 99% трафика идет через 1 хост - это VPN. Если таких юзеров несколько , то это точно VPN

**Comment by Aspirata** [comment]
Я сегодня винду переустанавливал. Когда попытался скачать zapret через Microsoft Edge с поисковиком яндекс, то не смог найти оригинальный гитхаб, с поисковиком гугла всё находится исправно

**Comment by bol-van** [comment]
РКН внес в реестр ссылку, яндекс отработал
