### ISSUE TITLE
После реинсталла сломался дискорд.

### ISSUE THREAD

**Issue by noverd** [bol-van/zapret#709]
OS: Manjaro
Конфиг: дефолтный
Устанавливал все по manual_setup
Список доменов:
```
googlevideo.com
youtu.be
youtube.com
youtubei.googleapis.com
youtubeembeddedplayer.googleapis.com
ytimg.l.google.com
ytimg.com
jnn-pa.googleapis.com
youtube-nocookie.com
youtube-ui.l.google.com
yt-video-upload.l.google.com
wide-youtube.l.google.com
youtubekids.com
ggpht.com
discord.com
gateway.discord.gg
cdn.discordapp.com
discordapp.net
discordapp.com
discord.gg
media.discordapp.net
images-ext-1.discordapp.net
discord.app
discord.media
discordcdn.com
discord.dev
discord.new
discord.gift
discordstatus.com
dis.gd
discord.co
discord-attachments-uploads-prd.storage.googleapis.com
7tv.app
7tv.io
10tv.app
```
Очень странная проблема, при переустановке сделал ./uninstall_easy и после повторил все шаги в manual_setup. Домены стояли те же самые.
Мне кажется что у меня сломан конфиг, так как одновременно с включением обхода ломались некоторые Российские сайты(habr, тинькофф), то сейчас они прекрасно работают. Я уверен что проблема не связана с изменениями у РКН.

**Comment by noverd** [comment]
Возможно кто-нибудь посоветуют лучший конфиг или какое-то другое решение для linux.

**Comment by HentayHentay** [comment]
Дискорд - 50-discord под свою систему 

Прочесть по поводу множества стратегий и покрутить блокчекер на сломанных/нужных сайтах

**Comment by noverd** [comment]
Кстати, на счет 50-discord. Я в других решениях его видел, перенес к себе в init.d/custom.d и ничего не заработало, а старый обход через хостлист отключился? Как оно вообще работает?

**Comment by HentayHentay** [comment]
> Кстати, на счет 50-discord. Я в других решениях его видел, перенес к себе в init.d/custom.d и ничего не заработало, а старый обход через хостлист отключился? Как оно вообще работает?

Нужно переносить данный лист от своего инициализационного скрипта (init.d, systemd). А то сломаешь
Работает в старых системах = customs 
Если запрет обновлен - то просто правильно кладешь и все.
Он чинит голос
Сайты работают через обычный https стратегию

**Comment by noverd** [comment]
Не совсем понимаю куда класть надо этот скрипт. Вот у меня systemd, его надо в zapret/init.d/systemd ложить или как?

**Comment by HentayHentay** [comment]
Из zapret/tree/master/init.d/sysv/custom.d.examples
/50-discord
В
 custom.d

**Comment by noverd** [comment]
Получается в zapret/custom.d/
?

**Comment by HentayHentay** [comment]
1 - я каталоги не вижу..
2 - я написал тебе папку примерную в каталоге запрета. 
3 - нужно взять данный скрипт и положить её в правильную папку под свою систему вызовов (инитов) 
Можно к слову глянуть в служебный инит и посмотреть откуда он стартует

**Comment by noverd** [comment]
Окей. Я просто хочу удостверится что я скопировал в правильное место.
Локация установки: /opt/zapret
Мой инициализатор: systemd
Куда я положил: /opt/zapret/init.d/systemd/custom.d/50-discord

**Comment by viktoriaLukyanova** [comment]
> 1 - я каталоги не вижу.. 2 - я написал тебе папку примерную в каталоге запрета. 3 - нужно взять данный скрипт и положить её в правильную папку под свою систему вызовов (инитов) Можно к слову глянуть в служебный инит и посмотреть откуда он стартует 4 - перезапустить запрет 5 - Если хочешь ещё что-то и это что-то не открывается, нужно проверять блокчеком при незапущенном запрете

а чтобы ютуб через blockcheck проверить нужно типо такого домена или какой?
rr4---sn-q4flrnl7.googlevideo.com (они постоянно меняются)

**Comment by HentayHentay** [comment]
@viktoriaLukyanova 
В выполенных иссу не один раз разбирался ютуб.
Ещё можешь в диалогах посмотреть.

**Comment by HentayHentay** [comment]
`curl_test_http` - `--filter-tcp=80`
`curl_test_https_tls12`   - `--filter-tcp=443`
`curl_test_http3`   - `--filter-udp=443`

**Comment by noverd** [comment]
Есть ли способ проверить, проходят ли через запрет пакеты вообще? У меня закрадываются смутные подозрения, что у меня криво настроено iptables/nftables

**Comment by HentayHentay** [comment]
При перезапускки запрета в консоле должны появиться строчки. Если там тишина, то значит ни один демон не активирован .

**Comment by aden16rus** [comment]
может ктото подскажет какой то механизм настройки войса в дискорде? файлик 50-discord подкинул куда надо но не помогло
