### ISSUE TITLE
[quick_start.txt] Нет файла readme.txt

### ISSUE THREAD

**Issue by Yoti** [bol-van/zapret#710]
В файле `quick_start.txt` в [последней строке](https://github.com/bol-van/zapret/blob/master/docs/quick_start.txt#L179) упоминается файл `readme.txt`, которого нет в репозитории. Возможно, имеется в виду `readme.md`? Если принимаются PR с правками "простых" ошибок вроде этой, то могу присылать их вместо issue по факту нахождения. Также хочу отметить отсутствие секции с удалением zapret в readme. Упомянуто лишь в случае с усечённой установкой на OpenWrt в условиях нехватки памяти.

**Comment by bol-van** [comment]
Еще идет работа по оMDшиванию, не все закончено
Про uninstall_easy, думаю, сами догадаются

**Comment by Yoti** [comment]
Однако полнота и всеобъемлемость readme без секции удаления страдает. Хотелось бы видеть хотя бы список частей приложения (папка такая-то, служба такая-то и т.д.) для полного ручного удаления (или контроля успеха автоматического удаления). В любом случае, раз моё пожелание прочитано, то можно и issue закрывать за ненадобностью.

**Comment by bol-van** [comment]
> Деинсталляция выполняется через `uninstall_easy.sh`

Написано все-таки

**Comment by Yoti** [comment]
Искал по странице по буквам "удал", а также просматривал оглавление.
