### ISSUE TITLE
все еще не работает, помогите

### ISSUE THREAD

**Issue by VIR4S** [bol-van/zapret#712]
сегодня делал все как обычно, но дс завис на бесконечном starting, я пытался по разному, но не получилось

**Comment by HentayHentay** [comment]
И снова не слова о пылесосе....
А какое начало

**Comment by VIR4S** [comment]
> И снова не слова о пылесосе.... А какое начало

не понял

**Comment by VIR4S** [comment]
вчера заработал, но  сегодня опять сдох, помогите пж

**Comment by HentayHentay** [comment]
Про пылесос  рассказывай , а то не телепаты

**Comment by VIR4S** [comment]
> Про пылесос рассказывай , а то не телепаты

я не очень в этом разбираюсь, объясни пожалуйста, что я должен сделать?

**Comment by VIR4S** [comment]
> Про пылесос рассказывай , а то не телепаты

ну лично у меня пылесос NORMANN AVC-212
