### ISSUE TITLE
[uninstall_easy.sh] Не удаляет /opt/zapret/

### ISSUE THREAD

**Issue by Yoti** [bol-van/zapret#713]
Собственно, файл для удаления выполняет функцию отключения, не удаляя по факту сами файлы. Тестовая система `OpenWrt 23.05.5 (r24106-10cc5fcd00)`.

**Comment by HentayHentay** [comment]
Судя по тому что там написано, происходит удаление службы и очистка ip/nf таблиц. 
Далее ручками уберись 

Скорее сделано для того, что бы ты мог свои конфиги и листы куда-то сохранить

PS и  почему все считают, что удаление - это помимо отключения функционала, ещё и уборка файлов следом....

**Comment by konstantisu** [comment]
Возможно, многие накушались Windows, где реестр загаживается не удаляющим за собой мусор софтом до переустановки системы :)? Или не хочет разбираться, проще переставить owet с нуля, или искать мешающие "хвосты". Или не у всех роутеры с гиговыми флешками? Вариантов немало. Но да, главное чтобы конфиги удавалось возвращать в состояние "как было". Про пакеты и зависимости лучше не упоминать...

**Comment by Yoti** [comment]
> PS и почему все считают, что удаление - это помимо отключения функционала, ещё и уборка файлов следом....

Install_easy разворачивает файлы в /opt. Обратное действие (uninstall_easy) должно эти файлы убирать по определению.

> PS2 Вот что делает удаление

Я прочитал, что она делает. И отписался о том, что она **не** делает.  Почему я считаю, что это баг? Смотри ответ на цитату выше.

**Comment by eastone11** [comment]
> > PS и почему все считают, что удаление - это помимо отключения функционала, ещё и уборка файлов следом....
> 
> Install_easy разворачивает файлы в /opt. Обратное действие (uninstall_easy) должно эти файлы убирать по определению.
> 
> > PS2 Вот что делает удаление
> 
> Я прочитал, что оно делает. И отписался о том, что оно **не** делает. Почему я считаю, что это баг? Смотри ответ на цитату выше.

разработчик видимо не согласен )
![image](https://github.com/user-attachments/assets/d722a5b5-0b72-4f31-b41f-1b8b2e503a91)

**Comment by HentayHentay** [comment]
@eastone11 
А я уж думал, что никто в ридми не заглянет ....

**Comment by eastone11** [comment]
> @eastone11 А я уж думал, что никто в ридми не заглянет ....

с пылу с жара кстати))
![image](https://github.com/user-attachments/assets/aad14616-b4e6-435b-94d2-2bc331362f15)

**Comment by Yoti** [comment]
> с пылу с жара кстати))

Видимо, это реакция на мой предыдущий репорт. Но да, последний коммит я не смотрел. Думаю, этого достаточно, чтобы закрыть issue.

**Comment by bol-van** [comment]
Да, сносит файлы деинсталятор не будет.
Потому что инсталлятор рассчитан в том числе и на выполнение из самого /opt для поправки конфига.
Копирует файлы в /opt он только, если запущен из другой локации. И то спрашивает в начале, по умолчанию НЕТ.

На счет зависимостей - неизвестно нужны они еще или нет. Только если спрашивать хотите/не хотите.
И то в случае openwrt это довольно проблемное действие. Потому что opkg не удаляет зависимости зависимостей. Не помнит что было автоматически установлено как зависимость, а что вручную. Как это делают более продвинутые пакетные манагеры на традиционных системах. В одной версии openwrt одни подздависимости, в другой- другие

**Comment by bol-van** [comment]
Сделано предложение удалить зависимости. По умолчанию  - нет.
Про снос /opt/zapret пишется, но не делается

**Comment by Yoti** [comment]
В контексте моей просьбы достаточно этого https://github.com/bol-van/zapret/commit/868d115c5d3e5f049d2588e905b2cfbdd105e33f#diff-2853695723668172fcde2eee778eaded1781661d07078a9700cae82dcba8bce8R77

**Comment by Akelpad** [comment]
подскажите как обновить запрет? полностью удалить все нужно?

**Comment by bol-van** [comment]
Не нужно. На linux достаточно запустить install-easy из нового комплекта не из /opt

**Comment by Akelpad** [comment]
У меня нет такого. И у меня винда. Устанавливал запрет через пакеты.

**Comment by Akelpad** [comment]
https://github.com/remittor/zapret-openwrt/wiki/Installing-zapret%E2%80%90openwrt-package
