### ISSUE TITLE
unblock localhost

### ISSUE THREAD

**Issue by TyroSpy** [bol-van/zapret#72]
Если возможно вынесите из функции fw_tpws4() правило блокировки локальных адресов: `ipt input_lan_rule_zapret -d 127.0.0.0/8 -j DROP` и далее в отдельную функцию например fw_local() и добавьте возможность ее отключения через параметр в конфиге. Блокировка создает конфликты для других правил перенаправления.

**Comment by bol-van** [comment]
это правило необходимо, чтобы исключить доступ через lan к localnet.  тк включенр route_localnet. мотивация подробно изложена в readme
в чем у вас конфликт?

**Comment by TyroSpy** [comment]
Конкретно конфликт на OpenWrt с перенаправлением на порт socks Tor `iptables -I prerouting_lan_rule -t nat -p tcp --dport 9050 -j DNAT --to 127.0.0.1:9050` естественно пакеты дропаются из-за вашего правила

**Comment by bol-van** [comment]
то есть вы тоже используете route_localnet ?
варианты решения
1) повесить ваш сервис тоже на 127.0.0.127
2) в /etc/firewall.user добавить в input_lan_rule разрешение на => 127.0.0.1:9050

**Comment by bol-van** [comment]
вообще роутить неконтролируемо в localnet это дыра в безопасности, особенно если разрешено и с внешнего интерфейса или на all

**Comment by bol-van** [comment]
а еще tor не обязан слушать на 127.0.0.1, его можно забиндить и на LAN IP, это наиболее логичное решение
выкрутасы с DNAT с LAN на 9050 это изврат

**Comment by TyroSpy** [comment]
Сам Tor предупреждает об обратном, что вешать на LAN IP это небезопасно. Ладно, решил проблему через firewall.user
Я не предлагал убрать ваше правило, мне показалось, что по крайней мере параметром в конфиге, можно дать пользователем самим определиться, блочить или нет локальные подключения. Можно закрывать тему.

**Comment by bol-van** [comment]
ваш вариант с dnat делает то же самое - делает доступным tor с LAN
только добавляет еще секурити проблему в довесок
tor всегда предупреждает о бездумных действиях. и говорит : это действительно то, что имелось в виду ?

**Comment by TyroSpy** [comment]
А как быть в случае конфигурации Tor в прозрачном режиме? Его таки придется вешать на localhost и таких примеров масса. Не вижу ничего нестандартного вешать на локал и давать доступ из LAN

**Comment by bol-van** [comment]
не придется.
route_localnet - это нестандартное поведение linux. поддерживается только для ipv4, для ipv6 - нет
в стандартном варианте требуется повесить прозрачный прокси на LAN IP, и только тогда можно делать DNAT туда или REDIRECT
я его использую только, чтобы не связываться с определением LAN IP, который может еще не быть сконфигурирован в момент запуска скрипта. но игра с route_localnet требует очень внимательного ограничения доступа
иначе можно на соседней системе убрать 127.0.0.0/8 из local, прописать маршрут на атакуемый хост и соединяться с его 127.0.0.1 удаленно. выходит вешание на 127.0.0.1 больше не является запретом от удаленного доступа

**Comment by TyroSpy** [comment]
Может в теории вы правы, но в режиме транспарент в конфиге Tor можно задать только порт (параметр TransPort), а вешается он автоматически на 127.0.0.1, вот строчка из лога: `Opening Transparent pf/netfilter listener on 127.0.0.1:9040`

**Comment by bol-van** [comment]
Да, и REDIRECT не будет работать на 127.0.0.1.
Возможно, в примерах, даже официальных, ошибка.
Товарищ напоролся именно на это : https://qna.habr.com/q/457222
правильно будет
TransPort 192.168.1.1:9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort

**Comment by bol-van** [comment]
https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TransparentProxy

тут официальная дока как это настраивать для разных вариантов
только локальный анонимизатор, анонимизирующий мидлбокс или все вместе
