### ISSUE TITLE
Не работает гс (no route, rtc conneting)

### ISSUE THREAD

**Issue by ScriptsByTheRealX** [bol-van/zapret#720]
НЕ Вкратце: зашел утром в дискорд, захотел зайти в гс а  у меня не грузит. думал интернет, но уже как 3-4 дня не могу нормально общаться, adguard'a нету, только его впн. пытался переустановить его самого и zapret тоже, но никак не хочет голосовой работать. 
Спасибо заранее за помощь если кто-то ответит.
Также раньше не работали иконки, теперь сами починились.

**Comment by eastone11** [comment]
https://github.com/bol-van/zapret/issues/685

**Comment by dnevnnoyy** [comment]
> #685

Не одно из предложеных решений не помогло. Voice так же не работает.

**Comment by HentayHentay** [comment]
Войс дискорда идет через клаудфлае
РКН щас имеет клаудфлае. Поэтому могут быть все что угодно

**Comment by ScriptsByTheRealX** [comment]
> Войс дискорда идет через клаудфлае РКН щас имеет клаудфлае. Поэтому может быть все что угодно

Понятно тогда, буду ждать новой версии zapret'a если она вообще починит гс
