### ISSUE TITLE
rawsend: sendto: Operation not permitted

### ISSUE THREAD

**Issue by pwd491** [bol-van/zapret#722]
Пытаюсь запустить инстантс в новой версии
```
/opt/zapret/nfq/nfqws --qnum=200 --user=daemon --dpi-desync-fwmark=0x40000000 --hostlist=/opt/zapret/ipset/youtube.txt --dpi-desync=fake,split2 --dpi-desync-repeats=8 --dpi-desync-fooling=datanoack --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --new
```

```
we have 2 user defined desync profile(s) and default low priority profile 0
Loading hostlist /opt/zapret/ipset/youtube.txt
loading plain text list
Loaded 12 hosts from /opt/zapret/ipset/youtube.txt
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding this socket to queue '200'
setting copy_packet mode
initializing raw sockets bind-fix4=0 bind-fix6=0
seccomp: Invalid argument
seccomp: this can be safely ignored if kernel does not support seccomp
Running as UID=1 GID=1

rawsend: sendto: Operation not permitted
rawsend: sendto: Operation not permitted
rawsend: sendto: Operation not permitted
rawsend: sendto: Operation not permitted
rawsend: sendto: Operation not permitted
rawsend: sendto: Operation not permitted
rawsend: sendto: Operation not permitted
```

В чём может быть проблема? Запускаю на Openwrt

**Comment by bol-van** [comment]
В conntrack и правиле drop invalid в цепочке output.
datanoack может работать только на nftables в режиме postnat
Скрипты zapret делают вот так, чтобы избежать дропа этим правилом :

```
        chain predefrag_nfqws {
                meta mark & 0x20000000 != 0x00000000 notrack comment "postnat traffic"
                ip frag-off != 0x0 notrack comment "ipfrag"
                exthdr frag exists notrack comment "ipfrag"
                tcp flags ! syn,rst,ack notrack comment "datanoack"
        }
```

пакеты, генерируемые nfqws, переводятся в notrack. но это работает только в режиме postnat

**Comment by pwd491** [comment]
> В conntrack и правиле drop invalid в цепочке output. datanoack может работать только на nftables в режиме postnat Скрипты zapret делают вот так, чтобы избежать дропа этим правилом :
> 
> ```
>         chain predefrag_nfqws {
>                 meta mark & 0x20000000 != 0x00000000 notrack comment "postnat traffic"
>                 ip frag-off != 0x0 notrack comment "ipfrag"
>                 exthdr frag exists notrack comment "ipfrag"
>                 tcp flags ! syn,rst,ack notrack comment "datanoack"
>         }
> ```
> 
> пакеты, генерируемые nfqws, переводятся в notrack. но это работает только в режиме postnat

Спасибо

**Comment by pwd491** [comment]
> В conntrack и правиле drop invalid в цепочке output. datanoack может работать только на nftables в режиме postnat Скрипты zapret делают вот так, чтобы избежать дропа этим правилом :
> 
> ```
>         chain predefrag_nfqws {
>                 meta mark & 0x20000000 != 0x00000000 notrack comment "postnat traffic"
>                 ip frag-off != 0x0 notrack comment "ipfrag"
>                 exthdr frag exists notrack comment "ipfrag"
>                 tcp flags ! syn,rst,ack notrack comment "datanoack"
>         }
> ```
> 
> пакеты, генерируемые nfqws, переводятся в notrack. но это работает только в режиме postnat

Спасибо!
