### ISSUE TITLE
Set connmark in nfqws

### ISSUE THREAD

**Issue by ccaapton** [bol-van/zapret#73]
Currently nfqws needs connbytes to skip the later packets. I just noticed that it is also possible to set the connmark of a packet in nfqueue, example [here](https://github.com/mpuzio/nfqueue-mnl/blob/master/nfqueue-mnl.h#L341). If nfqws adopts this method, you can skip all packets having the connmark, so later packets will not flow into nfqueue.

**Comment by bol-van** [comment]
What's advatage of your approach worth rewriting the code ?
In both cases we must write an addition filter in the iptables command.
May be this is advantageous in case of internet connection with high packet loss such as bad cellular link. Nfqws has the chance to report when it doesn't need any more packets. But the same can be accomplished just by increasing connbytes value from 4 to ~10. It's not a big problem to pass several extra packets to nfqws.
