### ISSUE TITLE
Не разблокирует Youtube, Discord

### ISSUE THREAD

**Issue by Purple52Line** [bol-van/zapret#730]
Привет. Такая проблема, недели 2 назад ставил zapret на openwrt через uninstall_easy.sh. Все завелось (Youtube, Discord, rutracker) через nftables и autohostlist, файл config никак не правил. 
После сноса роутера в 0 и установки zapret заново перестали работать Youtube и Discord, но rutracker работает. 
Провайдер сибсети. Может кто подсказать или направить куда копать?

**Comment by Purple52Line** [comment]
P.s через nftables, nfqws и autohostlist

**Comment by eastone11** [comment]
для войса дискорда скрипт, через поиск находится
для ютуба (ggc поиск) и авторизации диска блокчек юзай

**Comment by Purple52Line** [comment]
Для дискорда скрипт, это который 50-discord? Или именно в Винде обход хапрет-диакорд ютуб?
На ютубе блокчек смысла нет юзать, делал блокчек на сервера с видосами. Прогонял 3 раза 3 сервера в стандарте. Стратегии блокчека не помогли.
flow offloading - это гляну, не проверял, да и честно говоря не знаю что это пока что.

**Comment by Purple52Line** [comment]
> для войса дискорда скрипт, через поиск находится для ютуба (ggc поиск) и авторизации диска блокчек юзай почему оно тогда работало а сейчас нет, никто не скажет думаю, единственное если роутер в 0, проверь не включился ли flow offloading в фариволе


Для дискорда скрипт, это который 50-discord? Или именно в Винде обход хапрет-диакорд ютуб?
На ютубе блокчек смысла нет юзать, делал блокчек на сервера с видосами. Прогонял 3 раза 3 сервера в стандарте. Стратегии блокчека не помогли.
flow offloading - это гляну, не проверял, да и честно говоря не знаю что это пока что.

**Comment by eastone11** [comment]
скрипт
глянь
