### ISSUE TITLE
Войс чат дискорда не обходится

### ISSUE THREAD

**Issue by SalamonHaichat** [bol-van/zapret#735]
Изначально пользовался `50-discord`, включенным в zapret. Где-то дня 3-4 назад войс чат перестал работать. Всё остальное включая ютуб и весь остальной функционал дискорда обходится нормально. Проводил `blockcheck.sh` на домен по типу `warsaw10017.discord.gg`, http соединения проходят нормально даже без спутины, а вот https не идут вообще никакие, даже когда ставил force опцию.

Ищу советы, что тут можно ещё посмотреть и настроить. Читал тут, что cloudflare забанили и весь поток голосовых серверов дискорда через него проходит, но тогда намного больше сайтов были бы мне также недоступны, думаю. Кроме этого, думаю попытаться настроить `dnscrypt-proxy` на своей машине, хотя не знаю, имеет ли смысл это делать, не трогуя самой роутер (я во всём этом не шарю).

**Comment by HentayHentay** [comment]
Проблема в ограничениях провайдера
ДНС никак не поможет. ТК маршрутизация строиться серверами и алгоритмами дискорда. 
И войс дискорда имеет специфичную структуру. Так что из рекомендаций покрутить алгоритмы. (Блокчек тебе не помощник в починке голоса )
