### ISSUE TITLE
После установки нет возможности зайти на свой домашний сервер из локальной сети

### ISSUE THREAD

**Issue by Openwrtfunboy** [bol-van/zapret#74]
Привет! После установки не могу попасть на свой сайт. При переходе на сайт из локальной сети открывается страница роутера, а при переходе на сайт из интернета, непосредственно сайт. Очень неудобно, что я не могу попасть на него изнутри, т.е. из lan. Это как-то можно исправить?

**Comment by bol-van** [comment]
Много раз прочитал и мало что понял
Мне сложно комментировать что-то, когда имеется минимум технической информации, придется долго писать наводящие вопросы, а этим я заниматься не готов
Более технично, пожалуйста

**Comment by Openwrtfunboy** [comment]
> Много раз прочитал и мало что понял
> Мне сложно комментировать что-то, когда имеется минимум технической информации, придется долго писать наводящие вопросы, а этим я заниматься не готов
> Более технично, пожалуйста

Да, конечно, извините.

У меня белая статика и через опенврт прокинуты порты 80 и 443 через luci, а на этих портах сайт.

Без zapret он открываются что с моей сети (lan), что с мобильного интернета, а с zapet при вводе ip адреса или домена сайта из моей сети (lan), открывается админ-панель openwrt (luci), но с мобильного интернета (wan), открывается все же мой сайт.

Сайт, если что, не на роутере, а на домашнем сервере, роутер только прокидывает порт.

Как я поискал по issues, это как-то связано с dnat, но на большее пока что моих знаний в опневрт не хватает.

**Comment by bol-van** [comment]
Переадресация при запросе на внешний адрес самого роутера изнутри lan - это особый случай, обыгрываемый в openwrt через iptables. Он называется "reflection" (параметр в /etc/config/firewall) или "Enable NAT loopback" в luci (секция network - firewall - port forwards - edit)
Описываемое вами поведение характерно для выключенного reflection. Изнутри переадресация не производится, поэтому
на портах отвечает то, что там непосредственно висит - uhttpd + luci

zapret никак не вмешивается в механизм перенаправления портов.
я поднял 2 виртуалки - одну с openwrt, другую с клиентом, повесил веб сервер на клиент, сделал перенаправление на openwrt с порта 80 на клиент, установил zapret на openwrt в режиме по умолчанию (tpws). поведение как описал выше

**Comment by bol-van** [comment]
Мне удалось воспроизвести ваш случай
У меня проблемы не было, потому что я тестил в виртуалках на WAN адресах из диапазона 192.168.0.0/16

В режиме tpws  создается перенаправление на tpws на порты 80,443 более приоритетное, чем перенаправление через правила /etc/config/firewall   "DNAT"
Имеется система исключения IP адресов из переадресации через ipset "nozapret", который заполняется из файла /opt/zapret/ipset/zapret-hosts-user-exclude.txt
По умолчанию его содержание :
```
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
169.254.0.0/16
fc00::/7
fe80::/10
```

Нужно добавить в этот файл внешний IP адрес вашего роутера
либо переключиться на режим nfqws. nfqws не использует DNAT

**Comment by Openwrtfunboy** [comment]
Да, отлично, все теперь работает, как надо.

При том даже с хардварным натом, софтверным натом, BBR CCA и qos-ом, но у меня и опенврт китайская (репа coolsnowwolf)

Спасибо)
