### ISSUE TITLE
Автозапуск

### ISSUE THREAD

**Issue by Aspirata** [bol-van/zapret#740]
Попытался поставить автозапуск zapret через службу, но что-то ничего не работает(

P.S preset_russia.cmd работает исправно

rem set ARGS=--wf-tcp=80,443 --wf-udp=443,50000-50099 ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --hostlist-auto="%~dp0autohostlist.txt" --new ^
--filter-tcp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new ^
--filter-tcp=80,443 --dpi-desync=fake,disorder2 --dpi-desync-repeats=6 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-udp=50000-50099 --ipset="%~dp0ipset-discord.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=n4 --new ^
--filter-udp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11
rem call :srvinst winws1
rem set ARGS=--wf-l3=ipv4,ipv6 --wf-udp=443 --dpi-desync=fake 
rem call :srvinst winws2
goto :eof

:srvinst
net stop %1
sc delete %1
sc create %1 binPath= "\"%~dp0winws.exe\" %ARGS%" DisplayName= "zapret DPI bypass : %1" start= auto
sc description %1 "zapret DPI bypass software"
sc start %1

**Comment by bol-van** [comment]
REM - это комментарий
специально сделано, чтобы нубы не долбили все подряд, а потом не спрашивали как это удалить
если человек совершает осмысленное действие, он убирает REM
так же проверить пути на пробелы. пути с пробелами требуют экранирования через `\"`

**Comment by Aspirata** [comment]
Спасибо, я убрал rem и теперь всё работает

set ARGS=--wf-tcp=80,443 --wf-udp=443,50000-50099 ^
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --hostlist-auto="%~dp0autohostlist.txt" --new ^
--filter-tcp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake,split2 --dpi-desync-repeats=11 --dpi-desync-fooling=md5sig --dpi-desync-fake-tls="%~dp0tls_clienthello_www_google_com.bin" --new ^
--filter-tcp=80,443 --dpi-desync=fake,disorder2 --dpi-desync-repeats=6 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-udp=50000-50099 --ipset="%~dp0ipset-discord.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=n4 --new ^
--filter-udp=443 --hostlist="%~dp0list-youtube.txt" --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic="%~dp0quic_initial_www_google_com.bin" --new ^
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=11
call :srvinst winws1
rem set ARGS=--wf-l3=ipv4,ipv6 --wf-udp=443 --dpi-desync=fake 
rem call :srvinst winws2
goto :eof

:srvinst
net stop %1
sc delete %1
sc create %1 binPath= "\"%~dp0winws.exe\" %ARGS%" DisplayName= "zapret DPI bypass : %1" start= auto
sc description %1 "zapret DPI bypass software"
sc start %1

**Comment by vadimminekraft02072004-ui** [comment]
Как удалить автозапуск?

**Comment by bol-van** [comment]
читать

**Comment by vadimminekraft02072004-ui** [comment]
Как удалить автозапуск? Я уже удалил запрет, а автозапуск пытается открывать какой то файл и сворачивает игры

**Comment by bol-van** [comment]
оригинал так не делает
а со всем остальным го ту откуда оно было скачано

**Comment by vadimminekraft02072004-ui** [comment]
Где удалить автозапуск запрета? Дайте ссылку. Я скачивал от сюда с ГетХаба. Я удалил этот запреет, и дискорд и начал через омандную строку пытаться что-то открывать. Что надо удалить и где

**Comment by bol-van** [comment]
docs/quick_start_windows
больше мне нечего добавить
сумел поставить службой - сумеешь и удалить. защита о  дурака там есть

**Comment by vadimminekraft02072004-ui** [comment]
Так я не ставил, там был файл АВТОЗАПУСК, я его запустил и запрет запускался автоматом

**Comment by bol-van** [comment]
в моих репах такого файла нет, а всем гитхабом я не владею
к сборщикам
