### ISSUE TITLE
Потеряна возможность использования вместе с ruantiblock [openwrt]

### ISSUE THREAD

**Issue by Wiedzmin89** [bol-van/zapret#748]
До обновления формата конфигураций, zapret работал с [ruantiblock](https://github.com/gSpotx2f/ruantiblock_openwrt) без каких либо проблем.
После обновления похоже, что zapret вообще не даёт работать ruantiblock, а иногда их взаимодействие вообще полностью кладёт openwrt.
Я так понимаю, что проблема связана с тем, что оба приложения используют nftables.

Я бы хотел поставить старую версию zapret, но @bol-van потёр историю

**Comment by Fenrir-0xFF** [comment]
> а иногда их взаимодействие вообще полностью кладёт openwrt.
Глянул чисто ради интереса что за ruantiblock это ппц... Zapret тут скорей всего не причём. 
Мой тебе совет - удаляй этот ruantiblock нахрен и никогда больше его не ставь. Ладно бы он под винду или нормальный линукс писал но чисто под OpenWRT.... кроме мата и пожеланию афтору убиться об стену больше ничего пожелать не могу. 
Ладно он lua использует, там для графического интерфейса luci к примеру, но сцука использовать ещё и питон там где можно обойтись bash скриптами которые так сильно не грузят систему это идиотизм. 
Кроме того он не учитывает как работает Tor на OpenWRT а работает он отвратительно **засирая всю ОЗУ после чего зависает** и развисается только когда у него пропадает соединение с мостами и сервером изза того что он завис. Это в лучшем случяе, а в худшем **как у тебя роутер зависает целеком**, поэтому от использования Tor на OpenWRT Я давно отказался, вместо него бесплатный openvpn использую, он роутер так сильно не грузит. 
Если нужна инструкция как зделать чтобы через VPN открывались только сайты из списка сообщи - скину конфиг.

**Comment by bol-van** [comment]
Скорее всего причина в чем-то другом.
Новый конфиг ничего особо нового в результат своей работы не принес.
Просто другой способ управления включением перехвата и запуска демонов.
Функции-хелперы остались теми же, ничего не поменялось и в tables

**Comment by Wiedzmin89** [comment]
> Мой тебе совет - удаляй этот ruantiblock

Я уже и не особо против, но надо чем-то заменить, всё же дурение dpi не всегда работает: в частности, не работает, когда обладатель ресурса ограничил доступ в РФ (jetbrains привет)

> Если нужна инструкция как зделать чтобы через VPN открывались только сайты из списка сообщи - скину конфиг

Да, давай, буду рад. У меня настроен sing-box. Указал в профиле тг (сюда можно будет чистый ответ собрать)

**Comment by Wiedzmin89** [comment]
> Скорее всего причина в чем-то другом. Новый конфиг ничего особо нового в результат своей работы не принес. Просто другой способ управления включением перехвата и запуска демонов. Функции-хелперы остались теми же, ничего не поменялось и в tables

Такое ощущение, что система ложится, когда и в обоих приложениях указаны одинаковые домены, как будто происходит неразрешимый конфликт во время маршрутизации.

После обновы, как будто приоритет маршрутов от zapret стал выше.

Если нет, то нет, буду изучать другие варианты. В любом случае, спасибо всем за ответы)

**Comment by bol-van** [comment]
Надо сперва понять как работает другой софт.
Это policy routing или прозрачный заворот на TOR или еще что-то.
Через что идет выделение трафика. Через ip списки или списки доменов. Если доменов, то как это реализовано.
Без изучения проблемы с этой стороны вряд ли можно найти правильное решение

**Comment by Wiedzmin89** [comment]
Заворот на vpn туннель (sing-box) через [списки доменов](https://github.com/gSpotx2f/ruantiblock_blacklist/blob/master/blacklist-1.1/fqdn/ruantiblock.dnsmasq)

**Comment by bol-van** [comment]
Если там прозрачный заворот на прокси-менеджер (xray, singbox), то обычно это делается так.
Прозрачный заворот средствами DNAT,REDIRECT,TPROXY.
Прога решает что делать с трафиком. Напрямую пускать или куда-то еще его выдавать.
Если напрямую, то прога работает локализатором трафика. Заставляет его идти с системы, где она работает. По тому же принципу, что и tpws. Если  используется nfqws, проблемы не вижу. С tpws в прозрачном режиме будут проблемы, тк они конкурируют за заворот.
С шифрованным каналом куда-то дальше тоже не должно проблем быть, если не используется стандартный порт 443 и стандартный TLS. В последнем случае стратегия может ломать сервак, где расположена серверная часть от singbox

**Comment by Wiedzmin89** [comment]
Короче говоря, проблема на стороне ruantiblock, ребята что-то натворили в апдейте, теперь нихрена не работает

@Fenrir-0xFF жду конфиг

**Comment by Fenrir-0xFF** [comment]
> @Fenrir-0xFF жду конфиг

Сорри только щяс сообщение заметил 
Я на основе этой инструкции делал https://habr.com/ru/articles/767464/ там даже готовый скрипт есть, только в самом конце со списками не заморачивайся а добавь в конфиг dnsmasq только те сайты для которых нужен vpn, например рашкинские которые не заблокированы но на которых ограничен доступ к некоторым страницам с рашкинских IP все остальные заблокированные сайты через zapret будут идти. 

У меня суть конфига таже только добавлен гостевой вайфай с доступом только к http и https сайтам, трафик через который для всех идёт через VPN но для ютюба, интернет радио и iptv идёт напрямую чтобы не засерали VPN который итак медленный. В dnsmasq использовал два списка, в одном сайты идут через vpn с любого интерфейса, в другом сайты идут всегда напрямую с гостевого вайфая. 
Наверно на днях скрипт напишу для версии с вайфаем возможно комуто понадобиться.
