### ISSUE TITLE
system is not either systemd, openrc or openwrt based

### ISSUE THREAD

**Issue by sandgray** [bol-van/zapret#749]
Здравствуйте
у меня Keenetic, на нём openwrt

> uname -a
> Linux Keenetic-XXXX 4.9-ndm-5 #0 SMP Thu Oct 24 17:52:50 2024 aarch64 GNU/Linux

При запуске `./install_easy.sh` получаю сообщение:

> * checking system
> system is not either systemd, openrc or openwrt based
> easy installer can set up config settings but can't configure auto start
> you have to do it manually. check readme.txt for manual setup info.
> do you want to continue (default : N) (Y/N) ?

Почему так происходит? Сейчас поищу где происходит определение ос, но сразу возникает вопрос - если инсталлятор не определил мою систему как openwrt - то не вызовет ли проблем прямое указание не это?

На сколько критично в моём случае продолжать без правильного определения системы и может ли это быть правильнее, чем руками указать, что у меня openwrt?

Дополнение 1:
при установке по умолчанию (при том, что инсталлятор не определяет мою систему) программа явно работает - на пример юутб нормально показывает и видео шорты

Дополнение 2:
после копирования во время установки (из изиинстала) смущает вот этот файл
> /opt/zapret # ls -l
> -rw-r--r--    1 root     root             0 Nov  9 13:23 ?p}A@@8???@@?P
> .... cut ....

Все остальные файлы как минимум выглядят нормально
Если зайти виндой - то этот файл имеет имя "p}A@@8@@P"

**Comment by electrifying** [comment]
Автор уже отвечал на вопрос о странном файле, для того что бы он не появился при инсталяции нужно установить bash

**Comment by bol-van** [comment]
Это не openwrt.
entware и openwrt - вещи совершенно разные. Единственное, что их связывает, это opkg

**Comment by sandgray** [comment]
> Это не openwrt. entware и openwrt - вещи совершенно разные. Единственное, что их связывает, это opkg

Благодарю, вопрос закрыт
