### ISSUE TITLE
install_easy.sh не отрабатывает

### ISSUE THREAD

**Issue by dvs727** [bol-van/zapret#753]
Всем привет, помогите пожалуйста, при попытке выполнить команду ./install_easy.sh происходит ошибка

root@OpenWrt:/tmp/zapret-master# ./install_easy.sh
* checking system
system is based on openwrt
openwrt firewall uses fw4. flow offloading requires nftables.
* checking executables
find: /tmp/zapret-master/binaries: No such file or directory
build tools not found

**Comment by electrifying** [comment]
Бинарники убраны в githam actions

**Comment by dvs727** [comment]
> Бинарники убраны в githab actions.Скачивайте релиз и разворачивайте

откуда его можно скачать? Нужна ссылка на openwrt

**Comment by electrifying** [comment]
> откуда его можно скачать?
https://github.com/bol-van/zapret/releases
Кидаете tar.gz в /tmp, распаковываете,запускаете ./install_easy.sh

**Comment by TyroSpy** [comment]
Здравствуйте. Я скомпилил ipk файлы для openwrt, потом благополучно установил. Но бинарники по умолчанию ставятся в папку /opt/zapret А потом когда запускаю install_easy.sh он мне ругается:
```
find: /opt/zapret/binaries: No such file or directory
build tools not found
```
т.е. он получается ищет их в другой папке binaries. Это баг или так задумано? Я конечно могу переместить их в эту папку, но тогда 'opkg remove' их больше не найдет. Как быть не пойму?

**Comment by bol-van** [comment]
Я как бы и не расчитывал, что IPK будет кто-то использовать.
ТОлько чтобы выдрать оттуда бинарик
Но да, лучше действительно их засовывать в /opt/zapret/binaries/my, вместо /opt/zapret/nfq, /opt/zapret/tpws и тд

**Comment by TyroSpy** [comment]
Ну я вот решил использовать) а оно с инсталятором не совместимо.. Еще бы номера версий привести к нормальному виду, что-б можно отслеживать изменения
```
root@OpenWrt:/tmp# opkg info nfqws
Package: nfqws
Version: 1
Depends: libc, libnetfilter-queue1, libcap, zlib
Status: install user installed
Architecture: aarch64_generic
Installed-Time: 1731421570
```

**Comment by bol-van** [comment]
docs/compile обновил
версий пока нет

**Comment by TyroSpy** [comment]
А зачем /opt/zapret/binaries/my ? надо сразу в /opt/zapret/binaries тогда инсталлятор их увидит

**Comment by bol-van** [comment]
Нет.  в my он ищет приоритетно бинарики. туда сбрасываются результаты собственной компиляции через make

**Comment by bol-van** [comment]
```
case $UNAME in
	Linux)
		ARCHLIST="my x86_64 x86 aarch64 arm mips64r2-msb mips32r1-lsb mips32r1-msb ppc"
		PKTWS=nfqws
		;;
	Darwin)
		ARCHLIST="my mac64"
		;;
	FreeBSD)
		ARCHLIST="my freebsd-x64"
		PKTWS=dvtws
		;;
	CYGWIN*)
		UNAME=CYGWIN
		ARCHLIST="win64"
		PKTWS=winws
		;;
	*)
		ARCHLIST="my"
esac

```

**Comment by TyroSpy** [comment]
Понял, спасибо за разъяснения. Бинарники кстати рабочие получились)

**Comment by TyroSpy** [comment]
Кстати, если инсталлятор запускается из /opt/zapret то он кладет туда все, что в есть архиве, не смотря на архитектуру и платформу, что не есть хорошо. Все-равно придется перебрасывать бинарники в /temp/zapret... Завтра проверю как это сработает

**Comment by bol-van** [comment]
Из /opt/zapret инсталятор никуда не инсталирует. он видит, что таргет уже как надо, и работает только на настройку

**Comment by Invisat24** [comment]
Может есть у кого актуальная инструкция по установке или возможно актуализировать инстукцю? С ликвидацией бинарников, текущая теряет всякий смысл. Инсталлятор ругается на отсутствие файлов в opt/zapret. Как их туда вернуть? Хотелось бы более подробно, если можно. В папке tmp инсталлятор файлы не видит.  Объясните пожалуйста, если не сложно, почему "Бинарники убраны в githab actions. Скачивайте релиз и разворачивайте".

**Comment by bol-van** [comment]
какая инструкция ? в сети их много
и да, они теряют копипастную актуальность
но на то у вас и голова чтобы связать дважды два

**Comment by Invisat24** [comment]
Спасибо за оперативный ответ!

**Comment by sawest60** [comment]
Подскажите максимально понятно, что конкретно нужно скачать и в какую папку поместить?
Из диалога выше ничего не понятно.
делал всё по "Подробная обновляемая инструкция настройки репозитория" [Zapret](https://github.com/bol-van/zapret) от [bol-van](https://github.com/bol-van) на Keenetic.

**Comment by sawest60** [comment]
скачал zapret v72.6 на пк, разархивировал
папку "binaries" перенёс на флешку в папку \\192.168.1.1\usb\tmp\zapret
дальше:
 3. Загружаем репозиторий Zapret:
cd /opt/tmp
git clone --depth=1 https://github.com/bol-van/zapret.git
4. Начнинаем устновку, выполняем скрипт:
cd zapret
./install_easy.sh
Много раз спрашивает y/n, если всегда отвечать "y", то появляется какое то окно.
ругалась на нехватку оперативной памяти, спрашивала 1 или 2, нажал 1.
дальше не понятно, все пункты выполнил
16. Перезагружаем entware(openwrt) командой ниже:
/opt/etc/init.d/rc.unslung restart
не перегружается
Итог ютуб не работает!
Есть какая то нормальная рабочая инструкция???
