### ISSUE TITLE
The program or feature cannot start or run due to incompatibility with 64-bit versions of Windows

### ISSUE THREAD

**Issue by vault-thirteen** [bol-van/zapret#754]
The program or feature ...\winws.exe cannot start or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.

![1](https://github.com/user-attachments/assets/d4e85434-ba39-4a08-ad06-f3d974b28f04)

**Comment by bol-van** [comment]
YTDisBystro is not the official version. Files could be damaged or replaced with who knows what.
Original files are here in release section

**Comment by Ericg98** [comment]
hey my laptop is having the same error message when i try to open the deimos app is there any fix or possible soltuion to get this resolved?

**Comment by icynstant** [comment]
@Ericg98 use original zapret
