### ISSUE TITLE
Дискорд вообще ни в какую не хочет работать

### ISSUE THREAD

**Issue by render69** [bol-van/zapret#757]
Использую версию v68 на arch linux
Провайдер Ростик

Блок чек выдаёт для дс:
```
ipv4 discord.com curl_test_http : working without bypass
ipv4 discord.com curl_test_https_tls12 : tpws --split-tls=sni --oob
ipv4 discord.com curl_test_https_tls12 : nfqws --dpi-desync=fake --dpi-desync-ttl=4
ipv4 discord.com curl_test_https_tls13 : tpws --split-tls=sni --oob
ipv4 discord.com curl_test_https_tls13 : nfqws --dpi-desync=disorder2
ipv4 discord.com curl_test_http3 : nfqws --dpi-desync=fake --dpi-desync-repeats=5
```
Для ютуба:
```
ipv4 youtube.com curl_test_http : working without bypass
ipv4 youtube.com curl_test_https_tls12 : tpws --split-tls=sni --oob --mss=88
ipv4 youtube.com curl_test_https_tls12 : nfqws --dpi-desync=split2 --dpi-desync-split-pos=10
ipv4 youtube.com curl_test_https_tls13 : tpws --split-pos=2
ipv4 youtube.com curl_test_https_tls13 : nfqws --dpi-desync=split2
ipv4 youtube.com curl_test_http3 : nfqws --dpi-desync=fake --dpi-desync-repeats=5
```

А для того что бы ещё и ютубчик работал я конфиг сделал таким:
 TPWS:
```
 TPWS_SOCKS_OPT="
--filter-tcp=80 --methodeol <HOSTLIST> --new
--filter-tcp=443 --split-tls=sni --obb --disorder --mss=88 --split-pos=2 <HOSTLIST>
"
TPWS_OPT="
--filter-tcp=80 --methodeol <HOSTLIST> --new
--filter-tcp=443 --split-tls=sni --disorder <HOSTLIST>
"
```

NFQWS:
```
NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,split2 --dpi-desync-fooling=badseq <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=split2,fake,disorder2 --dpi-desync-split-pos=10 --dpi-desync-repeats=5 --dpi-desync=disorder2 --dpi-desync-ttl=4 --dpi-desync-split-pos=1  <HOSTLIST> --new
"
```

Протичал ридми с ног до головы. Ничего не понял, метод тыка из предложанных функций не работает.
Без TPWS ничего не работает ни дс не грузит ни ютуб
TPWS добавляю в конфиг, могу ютубчик могу смотреть но не долго, смотрю минут 10 и всё не работает больше.
В дс могу просто смотреть что происходит на серверах но в канал захожу и тут просто вечное подключение, без ошибок просто подключение ораньжевым и всё 

Если кто то может может ваши стратегии покидаете. Или способы проверки какие-то или обхода а то через браузер и впн не гуд

**Comment by HentayHentay** [comment]
Вроде не раз данная тема рассматривалась. В закрытых и открытых иссу с темой или в диалогахю
Но нет. Вместо поискать и покрутить - прозе спросить

`TPWS` не умеет с upd играть. А дис и видео ютуба иногда требует стратегии на udp портах

**Comment by Netlighter** [comment]
> Вместо поискать и покрутить - проще спросить

вроде в каждой теме отписываешь, знаешь где какие треды обсуждаются, мог бы и ссылок человеку подкинуть, но нет - проще сказать, что человек сам виноват

> проще спросить

пардон, а для чего ишус вообще тогда нужны?

**Comment by Netlighter** [comment]
@render69 для дискорда попробуй это https://github.com/bol-van/zapret/issues/688 
как объединить стратегии для ютуба и дискорда разом не подскажу, к сожалению, но хоть дис заведется, а там может и покопаться получится

**Comment by render69** [comment]
> @render69 для дискорда попробуй это #688 как объединить стратегии для ютуба и дискорда разом не подскажу, к сожалению, но хоть дис заведется, а там может и покопаться получится

спасибо, жаль что не заработало но попытался, буду дальше искать

**Comment by IndeecFOX** [comment]
@render69

У меня на keenetic отваливался дис отдельным скриптом. Вписал стратегию в основной
Удалить 50-discord из кастомов, вписать в основной скрипт порты дополнительные, итог:
NFQWS_PORTS_TCP=80,443,50000-50090
И стратегию из скрипта 50-discord допом к 3 стратегиям в
NFQWS_OPT=" --filter-udp=50000-50090 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol --new
P.S. bol-van (автор запрета ругается на использование any-protocol в тупую "desync any protocol нуждается в connbytes или cutoff ограничителе. ", но мне сойдёт)
Теперь не должно отваливаться))
