### ISSUE TITLE
Сайты все еще открываются 

### ISSUE THREAD

**Issue by Purple52Line** [bol-van/zapret#758]
Пытаюсь удалить zapret с роутера, но рутрекер и ютуб все еще открываются. 
Сделал  service zapret stop 
Прогнал ./uninstall_easy.sh
И удалить папку с запретом в /opt
Подскажите пожалуйста, это провайдер приколы ловит или я не до конца снес запрет?
Хочу снести запрет и прогнать нормально blockcheck.sh.

**Comment by Purple52Line** [comment]
upd делается на Xiaomi Mi Router 4A с OpenWrt 23.05.4

**Comment by bol-van** [comment]
Скорее всего открывается из-за ECH. Чтобы сделать чек, достаточно service zapret stop

**Comment by Purple52Line** [comment]
>достаточно service zapret stop
Я так и сделал, потом запустил uninstall_easy.sh и удалил папку. В итоге, самого сервиса нет, а ютуб(и видео в нем) с рутрекером работают, но дискорд кстати не работает. Может ли быть такое, что провайдер что-то делает или это не на их стороне.

**Comment by Fenrir-0xFF** [comment]
> В итоге, самого сервиса нет, а ютуб(и видео в нем) с рутрекером работают, но дискорд кстати не работает.

killall tpws; killall nfqws
Если у обоих сообщение no process killed
Значит за счёт кэша браузера работает. Там достаточно один раз зайти с zapret'ом на любой https сайт после чего этот сайт будет работать даже с отключеным zapret'ом пока браузер полностью не перезапустиш.

**Comment by Purple52Line** [comment]
> killall tpws; killall nfqws Если у обоих сообщение _no process killed_ значит за счёт кэша браузера работает.

Вероятнее всего кэш, спасибо большое. Закрою ишью.
