### ISSUE TITLE
Не работает обход для другой подсети

### ISSUE THREAD

**Issue by Openwrtfunboy** [bol-van/zapret#76]
Есть подсеть 192.168.1.ххх, обход работает.
Есть подсети 192.168.4.ххх и 192.168.5.ххх со своими DHCP, но в них обход не работает.

**Comment by bol-van** [comment]
Если они представлены отдельными интерфейсами в openwrt, то скрипты запуска написаны только с учетом LAN/WAN.

**Comment by bol-van** [comment]
Завязка на LAN есть только у tpws, у nfqws есть завязка на wan, так что если перейти в режим nfqws (предварительно настроив параметры), то должно работать без изменений кода

**Comment by bol-van** [comment]
Сделал параметр в конфиге
OPENWRT_LAN="lan1 lan2 lan3"
можно указать с каких сетей tpws перенаправляет трафик на себя

**Comment by Openwrtfunboy** [comment]
> Сделал параметр в конфиге OPENWRT_LAN="lan1 lan2 lan3" можно указать с каких сетей tpws перенаправляет трафик на себя

Т.е. если у меня названия интерфейсов условно zxc и vnd, то я должен вписать

 OPENWRT_LAN="lan zxc vnd"?

**Comment by bol-van** [comment]
В openwrt существует дополнительный уровень абстракции интерфейсов. Они не соответствуют именам интерфейсов linux
в OPENWRT_LAN указываются имена интерфейсов openwrt, а не имена интерфейсов Linux

Старая конфигурация. lan - интерфейс openwrt, eth1, br-lan - интерфейсы linux. имя br-lan формируется автоматически
```
config interface 'lan'
 option type 'bridge'
 option ifname 'eth1'

```
Новая конфигурация с 21.02.  lan - интерфейс openwrt, br-lan, lan1,lan2,lan3,lan4,wan - интерфейсы linux
```
config device
        option name 'br-lan'
        option type 'bridge'
        option multicast_to_unicast '1'
        option multicast_querier '0'
        list ports 'lan1'
        list ports 'lan2'
        list ports 'lan3'
        list ports 'lan4'

config interface 'lan'
        option device 'br-lan'
```
