### ISSUE TITLE
install_bin.sh не запускается

### ISSUE THREAD

**Issue by Bogmuni** [bol-van/zapret#762]
Я новичок в linux, и у меня стоит arch.
Когда я запускаю install_bin.sh то выдаёт это:
no compatible binaries found

**Comment by venterum** [comment]
В последнем обновлении v68 были удалены binaries из репозитория на гитхабе, они теперь есть только в релизах.

`Удалены binaries. Binaries теперь только в релизах, собираемых через github actions.`

Если ты просто копировал репозиторий при помощи git clone, то стоит попробовать качнуть архив из releases

**Comment by bol-van** [comment]
Или берем релиз с готовыми бинариками, или ставит компилятор и дев пакеты и собираем

**Comment by Bogmuni** [comment]
> В последнем обновлении v68 были удалены binaries из репозитория на гитхабе, они теперь есть только в релизах.
> 
> `Удалены binaries. Binaries теперь только в релизах, собираемых через github actions.`
> 
> Если ты просто копировал репозиторий при помощи git clone, то стоит попробовать качнуть архив из releases

Спасибо, помогло.

**Comment by igr-noob** [comment]
Инструкция для новичка который хотел запустить install_bin.sh на одноплатнике (действуя по инструкциям с YouTube).
Из-за того что бинарников теперь нету в репозитории У нас появился геморрой.
1. с https://github.com/bol-van/zapret/releases скачиваем архив с последним релизом. Например сейчас  zapret-v69.9.zip
2. Из этого архива копируем папку binaries в любое место ПК
3. Находим устройство с линуксом с графическим интерфейсом. Например у меня это стимдек.
4. Копируем папку на это устройство (можно было бы скачать и разархивировать сразу на стимдеке).
5. выключаем одноплатник, достаём флешку и подключаем его к этому устройству на Linux. Добавятся 2 диска boot и root
6. Копируем папку binaries в корень диска root, т.к. сразу куда надо скопировать не получится
7. вставляем sd-карту обратно в одноплатник и запускаем mc (если не устанавливали, то напишите в консоли одноплатника apt install mc ентер и после установки mc ентер - появляется аналог Нортон Commander)
8. открываем папку otp, потом zapret, жмём tab на клавиатуре и во второй половине mc идём в самый корень и выделяем папку binaries. Жмём F5, чтобы скопировать binaries в zapret

Всё, теперь install_bin.sh запустится

Вообще было бы круто, если бы папку binaries добавили в репазиторий, чтобы у нубов с одноплатниками с безинтерфейсным линуксом не было такого гемора при создании шлюза или как его назвать - я же нуб.
Либо кто нибудь пропишите, пожалуйста, более оптимальное решение, если у человека нет отдельного устройства с интерфейсным линуксом.

**Comment by Amadeus71r** [comment]
Я использовал WinSCP для передачи недостающих файлов напрямую в роутер.

**Comment by Catterpiller** [comment]
Есть штатные средства ОС  например для последнего релиза на сегодняшний день:

wget https://github.com/bol-van/zapret/releases/download/v71.3/zapret-v71.3.tar.gz
дальше распаковываем архив:
tar -xvf zapret-v71.3.tar.gz
заходим в папку zapret-v71.3  можем запускать скрипт.
