### ISSUE TITLE
как удалить?

### ISSUE THREAD

**Issue by noximilien95** [bol-van/zapret#764]
вообще невозможно удалить, это же вирус поганый, даже нет uninstall

**Comment by jk0893** [comment]
По-человечески же написали в readme: "Деинсталляция выполняется через uninstall_easy.sh. После выполнения деинсталляции можно удалить каталог /opt/zapret."

**Comment by Goga613** [comment]
> По-человечески же написали в readme: "Деинсталляция выполняется через uninstall_easy.sh. После выполнения деинсталляции можно удалить каталог /opt/zapret."

Этот файл не работает на винде.

**Comment by jk0893** [comment]
![](https://github.com/user-attachments/assets/b3f7990e-2af2-4b05-af64-fa9511ec3650)
