### ISSUE TITLE
Почему автор удаляет вопросы о том как удалить приложение?

### ISSUE THREAD

**Issue by Goga613** [bol-van/zapret#767]
Боде, какой же это скам.
Uninstall  не работает на винде, пишет тол ко линукс и макос, а автор закрывает все вопросы с удалением, норм так вирусы разносят

**Comment by bol-van** [comment]
Потому что идиотские вопросы. Вы сначала сборок понахватались в инете, и здесь потом спрашиваете как их удалять.
Я не знаю как их удалять.
Оригинальный winws достаточно закрыть окно и нажать на windivert_delete.cmd или перезагрузить комп

**Comment by Goga613** [comment]
> Потому что идиотские вопросы. Вы сначала сборок понахватались в инете, и здесь потом спрашиваете как их удалять. Я не знаю как их удалять. Оригинальный winws достаточно закрыть окно и нажать на windivert_delete.cmd или перезагрузить комп

Ты клоун что-ли? Скачано с твоего репозитория последняя версия, твоя же сборка
