### ISSUE TITLE
Общие вопросы по настройке

### ISSUE THREAD

**Issue by fa1ke5** [bol-van/zapret#769]
И снова здравствуйте!
Сразу скажу я ценю детальнейший мануал по параметрам который выложили разработчики, с ним все замечательно только он не решает главного вопроса как эту дичь настроить. Можно почитать про методы, про параметры, про тонкости но именно ответа на вопрос как это использовать в нем нет от слова совсем.
Я уже писал тут на тему как же все таки обойти блокировку ютуба, пытались разбираться, один из ответов включите лог.
Ок, есть параметр --debug=1, добавляем, в сислоге инфа только про старт сервиса.
Мало того, сервис при старте же читает конфиг, но в логах ноль внимания на это фунт презрения, правильно он там что то распарсил, неправильно, пофигу.
Как это должно работать?
Все это описание последовательности стратегий бесполезно без понимания как это построено и как работает.
Имеем вот к примеру конфиг там параметры NFQWS_OPT_DESYNC и NFQWS_OPT_DESYNC_QUIC у обоих лепят строку параметров, какая когда работать должна, как оно обрабатывается? есть еще NFQWS_OPT_DESYNC_HTTP и NFQWS_OPT_DESYNC_HTTPS это куда вообще?
Что должен cделать рядовой потребитель этого творения что бы получить результат отличный от нулевого?
Я прямо очень сильно извиняюсь, но капец наболело ковыряние в этом конфиге. Как я могу узнать что вообще эти параметры обрабатываются а не игнорируются при старте?
Скрипт теста стратегий
Офигенная вещь, но толку от него ноль, если ты не вставил туда имя домена который реально не работает
В случае с ютубом, это может быть один из сервисов стриминга, название его совсем не yutube.com. В итоге скрипт отрабатывает, находит стратегию, бодро докладывает "все пучком командир, щас поедем, юзай эту строку в параметрах", ессно это не помогает от слова совсем.

**Comment by electrifying** [comment]
> это куда вообще?

В актуальных версиях конфиг давно переделан автором

**Comment by fa1ke5** [comment]
да это все замечательно наверное, мне то что делать что бы этот конфиг работал?

**Comment by eastone11** [comment]
> Что должен cделать рядовой потребитель этого творения что бы получить результат отличный от нулевого?

у автора программы нет цели чтобы эта программа запускалась у рядового потребителя, отталкивайся от этой мысли и тогда остальное станет понятно)

**Comment by fa1ke5** [comment]
есть кстати реализация этого запрета под винду и там прям из коробки все летит по дефолтным конфигам
https://github.com/Flowseal/zapret-discord-youtube/releases
есть даже эти конфиги, но что бы их вкрутить в наш хрен сломаешь пока осмыслишь

start "zapret: general" /min "%BIN%winws.exe" --wf-tcp=80,443 --wf-udp=443,50000-50100 ^
--filter-udp=443 --hostlist="list-general.txt" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin" --new ^
--filter-udp=50000-50100 --ipset="ipset-discord.txt" --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=d3 --dpi-desync-repeats=6 --new ^
--filter-tcp=80 --hostlist="list-general.txt" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new ^
--filter-tcp=443 --hostlist="list-general.txt" --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"

**Comment by fa1ke5** [comment]
> а покажи строку куда ты настройку с дебагом добавил

NFQWS_OPT_DESYNC="--debug=1 --debug_level=2 --dpi-desync=disorder2 --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin"
NFQWS_OPT_DESYNC_QUIC="--debug=1 --debug_level=2 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-autottl=5 --dpi-desync-ttl=2 --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_www_google_com.bin"

**Comment by eastone11** [comment]
> --debug_level=2

попробуй без левела, например в файл --debug=@/tmp/log_zapret.txt ну или в сислог если так удобней

**Comment by fa1ke5** [comment]
то есть ежели по уму, то должно быть что то вроде
NFQWS_OPT= тут общие параметры и тут надо указать дебаг
NFQWS_OPT_DESYNC = тут необщие ;)
NFQWS_OPT_DESYNC_QUIC = тут QUIC

**Comment by eastone11** [comment]
а ты принципиально старую версию используешь?

**Comment by fa1ke5** [comment]
> попробуй без левела, например в файл --debug=@/tmp/log_zapret.txt ну или в сислог если так удобней

именно это я и попробовал, файл не появляется, полез в мануал, там подобного не обнаружил и поставил так как там написано пробовал и debug и в связке с debug level, ноль на выходе

**Comment by eastone11** [comment]
ясно, не подскажу тогда почему он у тебя не работает
попробуй обновись до последней версии и там тесть

**Comment by eastone11** [comment]
запрета
начиная с 66ой версии параметры по типу NFQWS_OPT_DESYNC, NFQWS_OPT_DESYNC_QUIC выглядят как --filter-tcp, --filter-udp


> забрал правила со старого конфига

c 66ой версии совместимость со старыми конфигами потеряна.

**Comment by fa1ke5** [comment]
> запрета начиная с 66ой версии параметры по типу NFQWS_OPT_DESYNC, NFQWS_OPT_DESYNC_QUIC выглядят как --filter-tcp, --filter-udp
> 
> > забрал правила со старого конфига
> 
> c 66ой версии совместимость со старыми конфигами потеряна.

кабыздец, слов нет, спасибо большое за инфу, тогда сразу становится понятно отличие с виндовой версией

**Comment by fa1ke5** [comment]
тогда получается такой набор правил
NFQWS_OPT="
--debug=1
--filter-udp=443 --hostlist=list-general.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=/files/fake/quic_initial_www_google_com.bin --new
--filter-tcp=80 --hostlist=list-general.txt --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new
--filter-tcp=443 --hostlist=list-general.txt --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=/files/fake/tls_clienthello_www_google_com.bin
"

**Comment by fa1ke5** [comment]
пути к файлам без кавычек указывать?

**Comment by fa1ke5** [comment]
мде, не взлетает

**Comment by bol-van** [comment]
--hostlist=list-general.txt

Откуда он знает где этот файл лежит ?

**Comment by fa1ke5** [comment]
Всем спасибо за советы.
Для тех кто такие же проблемы получит пишу рецепт
1. в папке zapret запускаем скрипт uninstall_easy.sh и сносим нафиг эту дрянь
2. включаем DNSOverTLS (у меня сервер на UBUNTU 22.04 ниже инструкция для нее) https://docs.quad9.net/Setup_Guides/Linux_and_BSD/Ubuntu_22.04_%28Encrypted%29/ и ставим DNS сервера 9.9.9.9 и 149.112.112.112 в настройках сети
3. И все работает, ютуб, рутрэкер и тп. вообще без танцев

**Comment by fa1ke5** [comment]
> --hostlist=list-general.txt
> 
> Откуда он знает где этот файл лежит ? В винде он берет при запуске через батник из текущей. А тут где он найдет ?

ну очевидно я я его забрал из винды

**Comment by electrifying** [comment]
> ну очевидно я я его забрал из винды

Ну так вам автор и пишет, зачем вы это сделали если используете запрет не на винде

**Comment by fa1ke5** [comment]
> > ну очевидно я я его забрал из винды
> 
> Ну так вам автор и пишет, зачем вы это сделали если используете запрет не на винде и в флаге указали использовать лист которого у вас нет, а даже если бы и был путь бы пришлось прописывать полностью

я же написал, я его забрал, про путь полностью верно, стоило бы прописать, но увы, с запретом я попрощался, надоело этот кактус кушать

**Comment by ivdeveloper86** [comment]
> Всем спасибо за советы. Для тех кто такие же проблемы получит пишу рецепт
> 
> 1. в папке zapret запускаем скрипт uninstall_easy.sh и сносим нафиг эту дрянь
> 2. включаем DNSOverTLS (у меня сервер на UBUNTU 22.04 ниже инструкция для нее) https://docs.quad9.net/Setup_Guides/Linux_and_BSD/Ubuntu_22.04_%28Encrypted%29/ и ставим DNS сервера 9.9.9.9 и 149.112.112.112 в настройках сети
> 3. И все работает, ютуб, рутрэкер и тп. вообще без танцев

Только что проверил, отключил zapret, установил DNSOverTLS с указанными серверами DNS, бутнул роутер -> нифига не работает. Ни Ютуб, ни заблокированные сайты.
Да и с чего бы DNS мог чем-то помочь, если DPI анализирует пакеты данных?

**Comment by fa1ke5** [comment]
Я не знаю что там и кто анализирует, на старых DNS 8.8.х.х и провайдерских у меня ютуб работал только через запрет, потом перестал, дальше я попытался опять его привести в чувство, безуспешно. В итоге сейчас я его снес вообще, поставил DNSOverTLS и работает ютуб и рутрэкер, правда сейчас вот смотрю ютуб работает странно, тормозит видео, но открывается быстро, прям после запрета моментально.

**Comment by fa1ke5** [comment]
нашел причину, в браузере остался включен впн плагин, увы чуда не случилось, опять придется бодаться с этим

**Comment by UberHelmsman** [comment]
ставлю себе на linux mint cinnamon. Такой вопрос: в каком формате писать параметры в NFQWS_OPT? Вывод blockcheck слегка модифицировал и получилось такое:
```
NFQWS_OPT="
--filter-tcp=80 --dpi-desync=fake,multisplit --dpi-desync-split-pos=method+2 --dpi-desync-fooling=md5sig <HOSTLIST> --new
--filter-tcp=443 --dpi-desync=fake,multidisorder --dpi-desync-split-pos=1,midsld --dpi-desync-fooling=badseq,md5sig <HOSTLIST> --new
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=6 <HOSTLIST_NOAUTO>
--methodeol
--dpi-desync=fake --dpi-desync-ttl=5
--dpi-desync=fake --dpi-desync-fooling=md5sig
--dpi-desync=fakedsplit --dpi-desync-ttl=5 --dpi-desync-split-pos=method+2
--dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=method+2
--dpi-desync=fakeddisorder --dpi-desync-ttl=3 --dpi-desync-split-pos=method+2
--dpi-desync=fakeddisorder --dpi-desync-fooling=md5sig --dpi-desync-split-pos=method+2
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=2
--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=midsld
--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=midsld
--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=method+2
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=method+2
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=method+2
--dpi-desync=syndata
--dpi-desync=syndata --dpi-desync-fake-syndata=/tmp/zapret-v70.4/files/fake/http_iana_org.bin
--dpi-desync=syndata,multisplit --dpi-desync-split-pos=method+2
--dpi-desync=syndata,multisplit --dpi-desync-fake-syndata=/tmp/zapret-v70.4/files/fake/http_iana_org.bin --dpi-desync-split-pos=method+2
--dpi-desync=syndata,multidisorder --dpi-desync-split-pos=method+2
--dpi-desync=syndata,multidisorder --dpi-desync-fake-syndata=/tmp/zapret-v70.4/files/fake/http_iana_org.bin --dpi-desync-split-pos=method+2
--dpi-desync=fake --dpi-desync-ttl=5
--dpi-desync=fake --dpi-desync-fooling=badseq
--dpi-desync=fake --dpi-desync-fooling=md5sig
--dpi-desync=fakedsplit --dpi-desync-ttl=5 --dpi-desync-split-pos=midsld
--dpi-desync=fakedsplit --dpi-desync-fooling=badseq --dpi-desync-split-pos=midsld
--dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-ttl=3 --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-fooling=badseq --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-fooling=md5sig --dpi-desync-split-pos=midsld
--dpi-desync=multisplit --dpi-desync-split-pos=2 --dpi-desync-split-seqovl=336 --dpi-desync-split-seqovl-pattern=/tmp/zapret-v70.4/files/fake/tls_clienthello_iana_org.bin
--dpi-desync=fake,multisplit --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1
--dpi-desync=fake,fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=1
--dpi-desync=fake,fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1
--dpi-desync=fake,fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=midsld --dpi-desync-fake-tls=0x00000000
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=midsld
--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=midsld
--dpi-desync=fake,multidisorder --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=midsld
--dpi-desync=fake,multidisorder --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1
--dpi-desync=fake,multidisorder --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=1
--dpi-desync=fake,multidisorder --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=1
--dpi-desync=fake,multidisorder --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=midsld
--dpi-desync=syndata --dpi-desync-fake-syndata=/tmp/zapret-v70.4/files/fake/tls_clienthello_iana_org.bin
--dpi-desync=syndata,multisplit --dpi-desync-fake-syndata=/tmp/zapret-v70.4/files/fake/tls_clienthello_iana_org.bin --dpi-desync-split-pos=1
--dpi-desync=syndata,multidisorder --dpi-desync-fake-syndata=/tmp/zapret-v70.4/files/fake/tls_clienthello_iana_org.bin --dpi-desync-split-pos=1
"
```

Так вообще правильно или нужно писать как то по другому?

**Comment by UberHelmsman** [comment]
Просто вроде все по мануалу поставил, все настроил, но на ютубе ролики не грузит

**Comment by bol-van** [comment]
Это все неправильно. Читайте quick_start

**Comment by UberHelmsman** [comment]
я плохо в этом разбираюсь. Как определить, что относится к tcp=80, что к tcp=443, и что к udp=443?

**Comment by UberHelmsman** [comment]
?

**Comment by UberHelmsman** [comment]
Так и не понял, что с этим делать. Просто смотреть на то, что вышло в саммари и какое то из них подключать к tcp, какое то к udp?

**Comment by bol-van** [comment]
В начале quick start написано, что если вы совсем не ориентируетесь, лучше найти более простой метод
Поставить VPN и забыть
Или задавайте вопросы в дискуссиях в рассчете на помощь зала. Здесь issue, тем более закрытый

**Comment by UberHelmsman** [comment]
почитал дискуссии, сам еще чуть чуть помучился, все настроил, заработало)

**Comment by Cartsist** [comment]
Помогите пожалуйста. 
Пытался с помощью запрета 1.9 и 2 подключиться в такие игры как dead by daylight и foxhole. Однако запрет не помогает, манипуляция с файлами запрета тоже не дала результатов. При этом у других людей такой проблемы нет. Возможно ли что я что-то поменя в настройках пк? При этом с помощью некоторых впн подключиться все же удаётся
