### ISSUE TITLE
запрет

### ISSUE THREAD

**Issue by h1bro32** [bol-van/zapret#770]
хочу спросить, вот жалуется мне виндовс дефендер на троян, и вирус тотал тоже, от чего это может быть? пробовал скачать верси 1.5.2 и 1.6.0 все так же

**Comment by MayanKoyote** [comment]
А ты где тут в релизах такие версии видишь?

**Comment by bol-van** [comment]
Это репаки и сборки. Там может быть что угодно. Волна хайпа, есть скаммеры.
На оригинал жалуется немного антивирусов. В основном на windivert и upx. И если пробить по вирус тоталу, то жалуются в основном аутсайдеры, максимум - дефендер, а каспер  и 90% остальных молчат. Среди жалующихся в основном NOT-A-VIRUS, или хак -тул какой нибудь. потенциальный риск

**Comment by Fenrir-0xFF** [comment]
@bol-van написал сюда чтоб кучю issue не создавать 
69я версия, andriod-arm при запуске бинариков вот такое сообщение в самом начяле: 
**WARNING: linker: /system/bin/nfqws: unsupported flags DT_FLAGS_1=0x8000001** 
На дальнейшую работоспособность не влияет, протестировал несколько минут - вроде всё робит. 

Кстати а зачем вобще специально под андроид компилировать если там обычные arm бинарики прекрасно работают?

**Comment by Fenrir-0xFF** [comment]
>На 8-м уже точно без ругани.
>нормально работают с DNS без /etc/resolv.conf, 
>Да и меньше они по размеру. Без upx

Я на 7 тестил 
А что нетак с DNS? У меня /etc/resolv.conf нету, при этом всё норм работает, хосты в список добавляются и обрабатываются
Ну насчёт размера на андроиде точно можно не экономить, места там всегда с запасом, лишние 100кб роли не играют. 

Насчёт всего остального посути это не критично, лог на постоянку включять и мониторить врятли кто будет, а вместо --user с помощью пары команд вытащить цифры для --uid= не проблема

**Comment by bol-van** [comment]
nfqws не работает с DNS.
с ним работает tpws в режиме socks и mdig

что такое программная обработка я не понимаю. она и так программная. никаких спец железок не требуется

**Comment by Fenrir-0xFF** [comment]
> что такое программная обработка я не понимаю. она и так программная. никаких спец железок не требуется

В tpws пакеты можно же програмно как угодно переделать и отправить в интернет что угодно, но это не реализовано, подозреваю чтоб проц сильно не грузить конвертацией для прокси. 
Щяс там реализовано только разделение пакетов и отправка их чястей в обратном порядке, а всех остальных методов десинхронизации DPI нету. 

Nfqws не везде есть возможность использовать изза отсутствия NFQUEUE в iptables на некоторых прошивках, а прокси в нём нету. В tpws прокси есть но функционал ограничен.

**Comment by bol-van** [comment]
Вы плохо разбираетесь в вопросе.
tpws работает на уровне tcp сокетов, nfqws на уровне raw сокетов.
Это 2 разных подхода, у каждого из которых есть свои ограничения и преимущества.

**Comment by Fenrir-0xFF** [comment]
> Вы плохо разбираетесь в вопросе.
> tpws работает на уровне tcp сокетов, nfqws на уровне raw сокетов.
> Это 2 разных подхода, у каждого из которых есть свои ограничения и преимущества.

Согласен, не эксперт но общюю суть представляю
Можно же tpws на raw сокет wan пустить или в nfqws добавить tcp сокет на lan для работы в режиме прокси 

Насчёт tpws - можно сделать чтоб опция --maxfiles=0 использовала системные настройки поумолчянию? Не лезла их изменять. 
А то если без рута запускаю то вылазит **setrlimit: Operation not permitted** но несмотря на это всёравно работает.
