### ISSUE TITLE
Отсутствует каталог binaries

### ISSUE THREAD

**Issue by FaieksLH** [bol-van/zapret#772]
Привет, после запуска `install_bin.sh` терминал выводит:
```bash
/opt/zapret/binaries/my/ip2net is absent
my is NOT OK
no compatible binaries found
```
Скачивал с помощью `git clone` и браузера, но  каталога `binaries` всё равно нет

**Comment by FaieksLH** [comment]
Понял принял, спасибо

**Comment by eokarm** [comment]
Где и как скачать релиз?

**Comment by FaieksLH** [comment]
Тут всё написано: https://github.com/bol-van/zapret/blob/master/docs/quick_start.md

**Comment by eokarm** [comment]
Скачал скопировал,а толку chmod +x те помогает  is not executable. set proper chmod.
