### ISSUE TITLE
Discord перестал работать после 5 ноября

### ISSUE THREAD

**Issue by DRedGuia** [bol-van/zapret#773]

**Comment by bol-van** [comment]
`</home/dredguia/zapret/list-ultimate.txt> 
`

Здесь ерунда написана. Будет вываливаться по ошибке нет файла.

**Comment by DRedGuia** [comment]
> `</home/dredguia/zapret/list-ultimate.txt> `
> 
> Здесь ерунда написана. Будет вываливаться по ошибке нет файла.

Надо кавычки?

**Comment by DRedGuia** [comment]
Поставил кавычки, заработало
