### ISSUE TITLE
Asus Merlin #include <sys/capability.h> fatal error

### ISSUE THREAD

**Issue by romanlex** [bol-van/zapret#776]
В новых версиях перестал работать zapret
![image](https://github.com/user-attachments/assets/8c721fb8-b68f-4db0-b7ec-ab8cd9de3358)

где взять заголовки не понятно( 
предыдущие версии работали

**Comment by romanlex** [comment]
сам создал, сам отвечу, простите
бинарники теперь только в релизах

**Comment by TABURELTER** [comment]
> сам создал, сам отвечу, простите бинарники теперь только в релизах

Если ты смог установить то ты можешь помочь с установкой? я пытался мне писало херню что система не подходит ну и тут всё

**Comment by AJMC2002** [comment]
> > сам создал, сам отвечу, простите бинарники теперь только в релизах
> 
> Если ты смог установить то ты можешь помочь с установкой? я пытался мне писало херню что система не подходит ну и тут всё

https://man7.org/tlpi/code/faq.html#sys-capability.h-missing
