### ISSUE TITLE
No packet info in a log with custom script

### ISSUE THREAD

**Issue by mikeS7** [bol-van/zapret#777]
Log for custom script doesn't contain packet processing info. There are only startup info.
Daemon is started with following:
```
local opt="--debug=@/root/rt-gv.log --qnum=$QNUM_RT_GV $NFQWS_OPT_BASE $NFQWS_OPT_DESYNC_RT_GV"
run_daemon $DNUM_RT_GV $NFQWS "$opt"
```
Log contains only:
```
adding low-priority default empty desync profile
we have 3 user defined desync profile(s) and default low priority profile 0
[profile 1] autottl ipv4 1:3-20
[profile 1] autottl ipv6 1:3-20
Loading hostlist /opt/zapret-misc/googlevideo.txt
loading plain text list
Loaded 1 hosts from /opt/zapret-misc/googlevideo.txt

lists summary:
hostlist file /opt/zapret-misc/googlevideo.txt
profile 1 include hostlist /opt/zapret-misc/googlevideo.txt
profile 2 include hostlist /opt/zapret-misc/googlevideo.txt

initializing conntrack with timeouts tcp=60:300:60 udp=60
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding this socket to queue '65400'
setting copy_packet mode
initializing raw sockets bind-fix4=0 bind-fix6=0
set_socket_buffers fd=5 rcvbuf=2048 sndbuf=32768
fd=5 SO_RCVBUF=4096
fd=5 SO_SNDBUF=65536
set_socket_buffers fd=6 rcvbuf=2048 sndbuf=32768
fd=6 SO_RCVBUF=4096
fd=6 SO_SNDBUF=65536
```

System is OpenWrt 23.05.5
Log for main process works without issue.

**Comment by bol-van** [comment]
It means no traffic is redirected to your queue

**Comment by mikeS7** [comment]
> It means no traffic is redirected to your queue

I'm not sure that you right )

--debug can't be the first parameter. If I move it after $NFQWS_OPT_BASE it works.
local opt="--qnum=$QNUM_RT_GV $NFQWS_OPT_BASE --debug=@/root/rt-gv.log  $NFQWS_OPT_DESYNC_RT_GV"

Please close the issue if you think that is not a bug.

Thank you for your hard work!

**Comment by bol-van** [comment]
This happens because `$NFQWS_OPT_BASE` has `--user=`  parameter.
During opening of debug log nfqws chowns it to this user.
If `--debug` is before `--user` no chown is done.
Then nfqws drop privs but `/root` is not accessible
