### ISSUE TITLE
Допилите скрипты для FreeBSD

### ISSUE THREAD

**Issue by serfcity** [bol-van/zapret#779]
Здравствуйте, допилите пожалуйста install_prereq.sh, uninstall_easy.sh для FreeBSD.

**Comment by bol-van** [comment]
prereq там не нужен. все уже есть из коробки.
Если у кого-то BSD, то он разберется как и куда это прикрутить.
А играть с pfsense - дело неблагодарное

**Comment by bol-van** [comment]
Никак.
> Не пишите в issue вопросы типа "как скопировать файл", "как скачать", "как
> запустить", ... То есть все , что касается базовых навыков обращения с ОС
> linux. Эти вопросы будут закрывать сразу. Если у вас подобные вопросы
> возникают, рекомендую не использовать данный софт или искать помощь где-то в
> другом месте. То же самое могу сказать тем, кто хочет нажать 1 кнопку, чтобы
> все заработало, и совсем не хочет читать и изучать. Увы, такое не подвезли и
> не подвезут. Ищите другие более простые методы обхода. Этот метод **не для
> рядового пользователя**.
