### ISSUE TITLE
Опакечивание

### ISSUE THREAD

**Issue by begss** [bol-van/zapret#78]
Написал пакет для Alpine Linux, положил в репу testing. Может, кому пригодится, в том числе как образец, в арче и генте довольно схожие форматы рецептов сборки.

Самым сложным был инит-скрипт, пришлось немного переработать под OpenRC. Я бы вообще вынес большую часть его функционала во вспомогательный шелл-скрипт.

Так вот, по теме, что я могу посоветовать как мейнтейнер:

* Делать теги, чтобы тарболл можно было выкачивать не по коммиту, а по ним
* Бинарники класть в релизы, а не в репу
* Хотя-бы частично отойти от концепции пихания всего в /opt. Например, мейкфайл с переменной PREFIX, по дефолту - /usr/local (бинарники в /usr/local/bin, скрипты ipset - в /usr/local/share/zapret/ipset и т.п.)

А так, большое спасибо за проект. Действительно выручает.

**Comment by bol-van** [comment]
Проверил на alpine linux последней версии
Единственная проблема, потребовавшая изменения кода, связана с отсутствием useradd
Поскольку useradd, похоже, отсутствует в стандартном репозитории, сделал совместимое добавление юзера. Поддерживается useradd, adduser от busybox и adduser не от busybox

В остальном все как в gentoo, только требуется установить несколько стандартных пакетов
apk add iptables ip6tables ipset git curl

**Comment by begss** [comment]
> это сделано давно. init.d/sysv/zapret очень простой, он всего лишь дергает процедуры из functions в readme есть раздел про gentoo. на livecd от gentoo не возникло особых сложностей с openrc, все описано в readme какие конкретно проблемы возникли в alpine ? так же см. "Прикручивание к системе управления фаерволом или своей системе запуска"

Возможно, я сделал неоптимально, но иной возможности, кроме как вынести все глобальные переменные из functions в /etc/conf.d/zapret и руками поправить все, где было ZAPRET_BASE, я не видел.

Если бы не было такой жесткой привязки к определенному положению бинарников, можно было бы просто дергать functions из OpenRC-скрипта.

В принципе, масштаб проблемы не такой серьезный, ведь по сути ZAPRET_BASE у меня это /usr/share/zapret, только бинарники в другом месте лежат. Достаточно сделать такие проверки:
```
[ -n "$NFQWS" ] || NFQWS="$ZAPRET_BASE/nfq/nfqws"
[ -n "$TPWS" ] || TPWS="$ZAPRET_BASE/tpws/tpws"
```
А еще лучше такие:
```
[ -n "$NFQWS" ] || NFQWS="$(which nfqws)" || NFQWS="$ZAPRET_BASE/nfq/nfqws"
[ -n "$TPWS" ] || TPWS="$(which tpws)" || TPWS="$ZAPRET_BASE/tpws/tpws"
```
Могу позже кинуть pull request.

**Comment by bol-van** [comment]
> [ -n "$NFQWS" ] || NFQWS="$ZAPRET_BASE/nfq/nfqws"
> [ -n "$TPWS" ] || TPWS="$ZAPRET_BASE/tpws/tpws"

OK, так и сделал. И еще учитываются $MDIG, $IP2NET  в ipset, об этом тоже не стоит забывать

> [ -n "$NFQWS" ] || NFQWS="$(which nfqws)" || NFQWS="$ZAPRET_BASE/nfq/nfqws"
> [ -n "$TPWS" ] || TPWS="$(which tpws)" || TPWS="$ZAPRET_BASE/tpws/tpws"

Так не есть хорошо, потому что приоритет в бинариках не из директории установки. Мало ли затеряется старье в /usr/bin, потом будешь гадать чего не работает

**Comment by begss** [comment]
Готово, теперь обычный sysv-шный functions просто подтягивается из OpenRC-скрипта. Расположение бинарников и ZAPRET_BASE задается соответственно в /etc/conf.d/zapret.

Теперь эквивалент ручной установки из репозитория - apk add zapret, соответствнно исходники лежат в aports на гитлабе альпайна.

Имеется ли смысл контрибьютить сюда скрипты для OpenRC?

**Comment by bol-van** [comment]
не имеет смысла,   special deployment is out of scope

**Comment by begss** [comment]
> не имеет смысла, special deployment is out of scope

Но ведь для systemd есть. По сути то же самое, что у меня для OpenRC.

**Comment by bol-van** [comment]
я не знаю зачем делать специально для openrc, когда он полностью совместим с sysv init
и у меня описано как это прикрутить
буквально 2 командами

**Comment by Glazami** [comment]
Под padavan встаёт также через файлик? или требуется глубокое изучение вопроса? нельзя отделавшись одним файликом спровоцировать автоустановку, чтобы те самые файлики с тогоже гитхаба подгружались?

**Comment by bol-van** [comment]
Все прошивки, кроме openwrt, на ручном режиме

**Comment by bol-van** [comment]
Сделал некоторые модификации sysv init скриптов, чтобы сделать их максимально совместимыми с обрезанными системами, где много чего отсутствует. В частности, с прошивками с readonly root и mounted rw partition.
Fallback на user=daemon при отсутствии возможности добавить юзера
Совместимость со start-stop-daemon от busybox

**Comment by bol-van** [comment]
Добавил поддержку openrc в install_easy.sh
проверено на nitrux и alpine.
alpine - сильно обрезанная система, отсутствуют по умолчанию ip(6)tables
делать автоустановку не стал, чтобы не привязываться к специфической для обрезанной системы пакетной базе
apk add iptables ip6tables

**Comment by TheSaintDiratof** [comment]
Карасик, не заебывай человека.

**Comment by dan4ik605743** [comment]
карасик, купи масло
