### ISSUE TITLE
Ребят, где то на просторах гитхаба видел репо со списком всех заблокированных ркн доменов, тогда забил, но сейчас понадобилось.

### ISSUE THREAD

**Issue by Snowy-Fluffy** [bol-van/zapret#781]
Кто может, скиньте пожалуйста ссылку на этот репо, а если таковой репо найти не вышло, то хотя бы файл.

**Comment by bol-van** [comment]
Таких много.
Мой вот здесь : https://github.com/bol-van/rulist

**Comment by Snowy-Fluffy** [comment]
> Таких много. Мой вот здесь : https://github.com/bol-van/rulist

Спасибо!

**Comment by rekryt** [comment]
https://github.com/rekryt/iplist
