### ISSUE TITLE
Nfqws не запускается на android

### ISSUE THREAD

**Issue by VaIeroK** [bol-van/zapret#786]
После запуска скрипта вижу такое сообщение
/system/bin/nfqws: not executable: 32-bit ELF file

Пробовал разные бинарники подсовывать от unix систем, не помогало
Устройство xiaomi 14, snap 8 gen 3
Есть какое либо решение?

**Comment by electrifying** [comment]
А запрет тут при чем?
На андроиде вроде как используется byedpi https://github.com/dovecoteescapee/ByeDPIAndroid

**Comment by VaIeroK** [comment]
> А так вот собрал в Android NDK (minSdk 21) - https://github.com/spvkgn/nfqws-android/releases

Работает! Благодарю!
