### ISSUE TITLE
С Zapret-ом в дискорде не грузятся сообщения в лс/серверах

### ISSUE THREAD

**Issue by 2lJuggerl22** [bol-van/zapret#798]
![image](https://github.com/user-attachments/assets/addeb561-64b3-4686-b2f0-17839e80d47a)

**Comment by ThisIsNoTa2acc** [comment]
Да тоже самое прям ток щас началось

**Comment by Fenixsle** [comment]
Тоже самое

**Comment by Kofel** [comment]
Тоже самое

**Comment by Aragnir** [comment]
пришел за решением, но смотрю это что-то новое, не грузятся сообщения

**Comment by eastone11** [comment]
прям если кому то писать сообщение то сразу ошибка будет или когда ответ должен придти?
по крайней мере у меня ЛС открывается и пишется без ошибок

**Comment by eastone11** [comment]
Видимо проблема есть но на стороне диска
![image](https://github.com/user-attachments/assets/f3e379c4-618f-426b-b593-793fad88e6c5)

**Comment by limpopo34** [comment]
У меня починилось само собой

**Comment by Heldenraider** [comment]
Проблема была на стороне дискорда, на сайте статуса писали про API Errors.
