### ISSUE TITLE
error: dereferencing pointer to incomplete type

### ISSUE THREAD

**Issue by s6d** [bol-van/zapret#8]
gcc  -o tpws tpws.c tpws_conn.c 
tpws_conn.c: In function ‘check_local_ip’:
tpws_conn.c:54:1: error: ‘getifaddrs’ undeclared (first use in this function)
 getifaddrs
 ^
tpws_conn.c:54:1: note: each undeclared identifier is reported only once for each function it appears in
tpws_conn.c:56:5: error: expected ‘;’ before ‘if’
     if (getifaddrs(&addrs)<0) return -1;
     ^
tpws_conn.c:61:7: error: dereferencing pointer to incomplete type ‘struct ifaddrs’
  if (a->ifa_addr && sacmp(a->ifa_addr,saddr))
       ^
tpws_conn.c:63:6: warning: implicit declaration of function ‘freeifaddrs’ [-Wimplicit-function-declaration]
      freeifaddrs(addrs);
      ^
Makefile:9: recipe for target 'tpws' failed
make: *** [tpws] Error 1

**Comment by bol-van** [comment]
Что-то с заголовками не то на вашей системе.

http://man7.org/linux/man-pages/man3/getifaddrs.3.html

#include <ifaddrs.h>
есть в начале tpws_conn.c
