### ISSUE TITLE
malformed Server Hello handshake

### ISSUE THREAD

**Issue by mikhajilo** [bol-van/zapret#817]
I get the Error code: SSL_ERROR_RX_MALFORMED_SERVER_HELLO when I try to visit certain websites whenever zapret is enabled. When I disable handshakes I just can't connect to the websites at all.

**Comment by bol-van** [comment]
If you expected zapret to be ON/OFF software, you are completely wrong.
It's not easy and requires complex tuning

**Comment by mikhajilo** [comment]
![image](https://github.com/user-attachments/assets/d6c53036-4f72-4bb1-8a38-13a073012214)
I am trying to tune but it's not changing it

**Comment by bol-van** [comment]
If you can't even edit a file this software is not for you.

**Comment by mikhajilo** [comment]
I'm telling you it doesn't recognize my edits, are you dense or what

**Comment by bol-van** [comment]
In russian docs I told everyone I will close any issue concerning base computer/linux skills.

**Comment by mikhajilo** [comment]
This is why I hate russians, if it were a White person he'd just say what's wrong instead of egoing
