### ISSUE TITLE
HTTPS протокол не работает

### ISSUE THREAD

**Issue by Romiro27** [bol-van/zapret#82]
При попытке открыть любой заблокированный сайт по https:// вылезает ошибка ERR_CONNECTION_CLOSED. Я использую tpws, опция "дурение HTTPS" в конфиге не меняет ситуацию в любом виде. Очень прошу помочь, потому что относительно недавно соединение по HTTPS работало, а сейчас нет. Я не сильно углублялся в сетевую сферу, поэтому не могу понять, что именно у меня поломалось.

**Comment by bol-van** [comment]
Возможно, провайдер изменил схему блокировки
Для выяснения что же там случилось существует скрипт blockcheck.sh. Его следует запускать при полностью отключенных средствах обхода блокировок, включая сам zapret. Если на роутере был tpws, то следует сделать uninstall_easy.sh перез запуском blockcheck

**Comment by Romiro27** [comment]
Судя по выхлопу скрипта, для работы https нужно переходить на nfqws. Но, судя по тому же выхлопу, TLS v1.3 вообще не работает, если я не ошибаюсь. После перехода на nfqws всё заработало, спасибо

**Comment by bol-van** [comment]
TLS 1.3 может не работать, потому что сайт не поддерживает
рутракер, который внесен по умолчанию, не поддерживает

**Comment by Glazami** [comment]
TLS 1.3 может не работать если разсинхрон времени, У меня такое было. при том интернет в принципе не работал, то есть доступа не было никуда. просто ставишь на роутере синхронизацию времени по серверу например google.
