### ISSUE TITLE
Использование NFQWS Android

### ISSUE THREAD

**Issue by frappy21** [bol-van/zapret#824]
Добрый день! Добавил nfqws в прошивку на Android и подобрал рабочий способ обхода, но в Android отсутствует поддержка connbytes в iptables, поэтому весь трафик до указанных доменов обрабатывается nfqws.

В [этом](https://ntc.party/t/zapret-whats-new/61/119) сообщении говорится, что некий аналог есть в самом nfqws. 

Верно ли я понимаю, что для дублирования [этой](https://github.com/bol-van/zapret?tab=readme-ov-file#iptables-%D0%B4%D0%BB%D1%8F-nfqws) рекомендации можно использовать опцию --dpi-desync-cutoff=n7 ?

**Comment by bol-van** [comment]
Это не поможет. Он по-прежнему будет весь обрабатываться.
В BSD тоже нет коннбайтс, там та же хрень. Приходится пускать весь исходняк

**Comment by frappy21** [comment]
Спасибо, вопрос исчерпан
