### ISSUE TITLE
Размер релиза 69.2

### ISSUE THREAD

**Issue by NewUse** [bol-van/zapret#833]
Слишком большой размер релиза для OpenWRT Snapshot (8/64) не хватает ОЗУ для временной ФС, пришлось руками из архива удалять все бинарники кроме опенВРТ-шных, чтоб хватила в /tmp места на кэш апдейта пакетов + разархивированный zapret.  Предлагаю генерить несколько архивов: zapret_vX.X-win.zip; zapret_vX.X-android.tar.gz; zapret_vX.X-linux.tar.gz и zapret_vX.X-linux_embadded.tar.gz

**Comment by bol-van** [comment]
Имеет смысл только одна альтернатива. Для embedded/openwrt.
С удаленными не Linux бинарями, исходниками доками

**Comment by Fenrir-0xFF** [comment]
> В след релизе будет отдельный tar gz openwrt-embedded 3-3.5 mb

Кстати добавь в бинарики номер версии чтобы в справочной информации отображался

**Comment by bol-van** [comment]
Неправда. Они немного весят. Около 100-110 kb tpws и nfqws
Сейчас они собираются с `-Os -flto`

**Comment by Fenrir-0xFF** [comment]
> Неправда. Они немного весят. Около 100-110 kb tpws и nfqws с upx.
> Сейчас они собираются с `-Os -flto`

Там вроде меньше 100кб были, примерно 70-90кб, но это было год назад или ещё раньше. Такто это не критично, обычно в единичных случяях такая жосткая нехватка памяти бывает.

**Comment by bol-van** [comment]
Год ? За год столько функций добавили. Еще бы оно не росло.

**Comment by NewUse** [comment]
x86 и x86_64 кажется тоже лишним в эмбеддит

**Comment by NewUse** [comment]
и почему на мипс64р2 так радикально отличается размер бинарников, нет ли там ошибки?

**Comment by bol-van** [comment]
Не лишние. openwrt полностью должен быть покрыт.
Для этого мипса не работает upx

**Comment by bol-van** [comment]
Есть еще вот такая магия. Распаковка прямо из сети без сохранения архива на диск. Экономит место размером с архив.
`curl -Lo - https://github.com/bol-van/zapret/releases/download/v69.3/zapret-v69.3-openwrt-embedded.tar.gz | tar -zxvf -`

**Comment by NewUse** [comment]
на сколько я помню, не должно работать фишка совместимости 32 и 64 есть только у amd64--i386, хотя могу и ошибаться, к тому же потребуется тянуть зависимые 32битные библиотеки, что приведёт к многократному росту потребления места вместо экономии, кмк, а вот посмотреть иные варианты упаковки исполняемого файла наверняка можно

**Comment by bol-van** [comment]
Архитектуры проца обычно сохраняют обратную совместимость с 32 битами своей архитектуры, хотя и не всегда.
PPC вроде нет. Но PPC64 только мейнфреймы. Вряд ли ктото будет там zapret гонять.
mips, arm, x86 точно имеют совместимость.
Но ядра openwrt собираются без ее поддержки

**Comment by EugeniiSh** [comment]
Прошу прощения за офф топ, не смог найти почты автора. Ребят, подскажите пожалуйста, какое у вас образование. Если точнее, то какой путь надо пройти, что бы научиться создавать подобные вещи, ну или хотя бы научиться их понимать. У меня гуманитарное образование. Есть познания в фронтенде на уровне пол-джуна. Прочитав инструкцию понял чуть больше чем ничего. Блокировки ютуба уже замучали. Но и пользоваться программой, которая делает не понятно что с твоим трафиком тоже не хочется. Есть желание, как говорит автор, держать ситуацию под контролем. Спасибо за понимание.

**Comment by NewUse** [comment]
начни с СДСМ это серия статей от linkedmeup или как-то так, копия на харбре

**Comment by EugeniiSh** [comment]
> начни с СДСМ это серия статей от linkedmeup или как-то так, копия на харбре

Большое спасибо! Надеюсь я правильно понял о чём разговор? https://habr.com/ru/articles/134892/

**Comment by NewUse** [comment]
@bol-van  наверное можно закрывать?

**Comment by NewUse** [comment]
Исправлено, добавлен -openwrt-embedded.tar.gz
