### ISSUE TITLE
install_easy при обновлении удаляет созданный ранее хост-файл

### ISSUE THREAD

**Issue by Euphoreka7** [bol-van/zapret#839]
у меня в ipset был discord.txt. после обновления на v69 файл удалился. сделала предварительно бэкап всей директории запрета и восстановила уже как обнаружила что перестало работать. но, кмк, не ок чистить созданные пользователем файлы. было бы неплохо поправить это в будущем

**Comment by bol-van** [comment]
Все верно. Инсталятор сносит всю директорию /opt/zapret, чтобы не оставалось мусора, кроме особых стандартных файлов.
все свое нужно выносить из /opt/zapret

**Comment by Euphoreka7** [comment]
хез... в теории можно хранить подобное в /etc/zapret/... и ссылаться на это в конфиге. только не слишком очевидно. юзер хост лист сохраняется, авто - тоже. я не углублялась во внутреннюю логику бэкапа-восстановления. но мб стоит изменить хардкод с имен айписетов на *.txt если он есть.

хотя... понимаю что в зависимости от размера может зааффектить тех у кого жесткие ограничения по месту

лично мне не критично подобное. но озвучила как возможный фича реквест

**Comment by bol-van** [comment]
В новых версиях иногда удаляются какие-то старые файлы.
Чтобы корректно оставить юзерские и снести старые инсталлятор должен помнить всю историю изменений.
Что является дополнительным головняком программировать и проверять. Поэтому и не реализовано.
Проще все старое снести. А юзерам не надо там хранить свои файлы. /opt/zapret только для файлов zapret.
Тогда юзер несет ответственность за свою часть, а zapret - за свою.

**Comment by Euphoreka7** [comment]
👌🏻 
доп вопрос чтобы не плодить треды - можно ли на уровне блокчека сделать выбор между tpws и nfqws (или обе)? сейчас проверка tpws уже не занимает так много времени как раньше. но, полагаю, что мне и не только один из этих типов проверок совершенно не нужен

**Comment by Euphoreka7** [comment]
да и в принципе. у меня на уровне существующего конфига tpws отключен, но проверки всеравно происходят

**Comment by eastone11** [comment]
> 👌🏻 доп вопрос чтобы не плодить треды - можно ли на уровне блокчека сделать выбор между tpws и nfqws (или обе)? сейчас проверка tpws уже не занимает так много времени как раньше. но, полагаю, что мне и не только один из этих типов проверок совершенно не нужен

SKIP_TPWS=1 /opt/zapret/blockcheck.sh | tee /opt/zapret/blockcheck.txt

**Comment by Euphoreka7** [comment]
> > 👌🏻 доп вопрос чтобы не плодить треды - можно ли на уровне блокчека сделать выбор между tpws и nfqws (или обе)? сейчас проверка tpws уже не занимает так много времени как раньше. но, полагаю, что мне и не только один из этих типов проверок совершенно не нужен
> 
> SKIP_TPWS=1 /opt/zapret/blockcheck.sh | tee /opt/zapret/blockcheck.txt

сип (не на правах сарказма). сделаю себе заметку насчет энв переменной
но всё же речь о более юзер-фрэндли подходе
т.к. тот же выбор между ipv4 и ipv6 есть и прочее

**Comment by eastone11** [comment]
> > > 👌🏻 доп вопрос чтобы не плодить треды - можно ли на уровне блокчека сделать выбор между tpws и nfqws (или обе)? сейчас проверка tpws уже не занимает так много времени как раньше. но, полагаю, что мне и не только один из этих типов проверок совершенно не нужен
> > 
> > 
> > SKIP_TPWS=1 /opt/zapret/blockcheck.sh | tee /opt/zapret/blockcheck.txt
> 
> сип (не на правах сарказма). сделаю себе заметку насчет энв переменной но всё же речь о более юзер-фрэндли подходе т.к. тот же выбор между ipv4 и ipv6 есть и прочее

тут программа не про юзер френдли, так что такого нет

**Comment by bol-van** [comment]
Простыня вопросов напрягает.
Потому не очень часто востребованные вынесены в env

**Comment by eastone11** [comment]
хотя я бы наверно назвал команды в строке это юзер френдли), не юзер это копаться в параметрах скрипта блокчека
