### ISSUE TITLE
blockcheck.sh ошибка при сканировании

### ISSUE THREAD

**Issue by lockuser** [bol-van/zapret#849]
При выполнении blockcheck.sh возникает следующая ошибка: 
- checking tpws --split-pos=method+2 --oob
!!!!! AVAILABLE !!!!!
./blockcheck.sh: 1018: local: --oob: bad variable name

**Comment by bol-van** [comment]
какая система и версия ?
чем является /bin/sh ?

**Comment by lockuser** [comment]
> какая система и версия ? чем является /bin/sh ?

Пробовал на ubuntu 22.04 и Armbian 21.02.3. /bin/sh стандартный, системный в обоих случаях

**Comment by bol-van** [comment]
На ubuntu 16 проблема есть, на 24 - нет.
Проблема в совместимости с не очень новым dash.
Исправлено, правда не в релизе пока.

**Comment by lockuser** [comment]
Супер! Спасибо вам, буду ждать такого релиза

**Comment by bol-van** [comment]
Ждать не нужно. Достаточно заменить файл blockcheck.sh. Или использовать git clone и собирать самому
Благо на ubuntu  с этим проблем чуть больше чем ноль
