### ISSUE TITLE
Использование на EdgeRouter

### ISSUE THREAD

**Issue by CherMet90** [bol-van/zapret#86]
Добрый день. Подскажите пожалуйста относительно использования на **EdgeRouter**

Установку выполнил согласно "Пример ручной установки на debian-подобную систему"
По результатам _blockcheck_ выбрал в конфиге 
MODE=nfqws 
NFQWS_OPT_DESYNC="--dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fooling=none"
По выводу _systemctl status zapret_ служба запущена с заданными ключами
Успешного результата работы службы не наблюдаю, тестовый домен не доступен.

Предположу, что нужно создать правила для firewall. Но из мануала я не могу понять какие именно правила я должен создать

MODE_FILTER=none
IFACE_LAN="eth1 eth2"
IFACE_WAN=eth0

**Comment by CherMet90** [comment]
UPD

Выключил оффлоад
выполнил iptables -t mangle -I POSTROUTING -o eth0 -p tcp --dport 443 -j NFQUEUE --queue-num 200 --queue-bypass
Без изменений

**Comment by bol-van** [comment]
Скрипты запуска сами все делают - и фаервол, и запуск демонов
Никаких дополнительных ручных телодвижений не нужно
Надо взглянуть на результаты команд в состоянии запущенной службы zapret
```
ps xau | grep nfqws
iptables-save
```
Есть ли ipv6 ? Проверялось ли действительно на ipv4 ?

**Comment by CherMet90** [comment]
`ps xau | grep nfqws`
`tpws      4959  0.0  0.0    412   284 ?        S    16:51   0:00 /opt/zapret/nfq/nfqws --user=tpws --dpi-desync-fwmark=0x40000000 --qnum=200 --dpi-desync=fake split2 --dpi-desync-ttl=2 --dpi-desy          nc-ttl6=0 --dpi-desync-fooling=none`
`root      4963  0.0  0.3   3004  1492 ttyS0    S+   16:51   0:00 grep nfqws`

`iptables-save`
*mangle
:PREROUTING ACCEPT [785406:551705206]
:INPUT ACCEPT [95687:53190045]
:FORWARD ACCEPT [743803:505807199]
:OUTPUT ACCEPT [83788:12240124]
:POSTROUTING ACCEPT [827590:518047271]
:UBNT_FW_MSS_CLAMP - [0:0]
:UBNT_FW_MSS_CLAMP_I - [0:0]
:UBNT_PBR_1 - [0:0]
:UBNT_QOS_FW_OUT_HOOK - [0:0]
:VYATTA_FW_IN_HOOK - [0:0]
:VYATTA_FW_OUT_HOOK - [0:0]
:vpn_route - [0:0]
-A PREROUTING -j VYATTA_FW_IN_HOOK
-A PREROUTING -j UBNT_FW_MSS_CLAMP_I
-A POSTROUTING -o eth0 -p tcp -m tcp --dport 443 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -j VYATTA_FW_OUT_HOOK
-A POSTROUTING -j UBNT_FW_MSS_CLAMP
-A POSTROUTING -j UBNT_QOS_FW_OUT_HOOK
-A UBNT_FW_MSS_CLAMP -o pppoe+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP -o pptp+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP -o tun+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP -o vti+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP -o l2tpc+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP_I -i pppoe+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP_I -i pptp+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP_I -i tun+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP_I -i vti+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_FW_MSS_CLAMP_I -i l2tpc+ -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1412
-A UBNT_PBR_1 -j MARK --set-xmark 0x800000/0x7f800000
-A UBNT_PBR_1 -j ACCEPT
-A VYATTA_FW_IN_HOOK -i eth1 -j vpn_route
-A VYATTA_FW_IN_HOOK -i eth2 -j vpn_route
-A vpn_route -m comment --comment vpn_route-1 -m set --match-set rkn-blocked-ips dst -j UBNT_PBR_1
-A vpn_route -m comment --comment "vpn_route-10000 default-action accept" -j RETURN
COMMIT

*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:FW_CONNTRACK - [0:0]
:NAT_CONNTRACK - [0:0]
:PFOR_CONNTRACK - [0:0]
:VYATTA_CT_OUTPUT_HOOK - [0:0]
:VYATTA_CT_PREROUTING_HOOK - [0:0]
-A PREROUTING -j VYATTA_CT_PREROUTING_HOOK
-A PREROUTING -j NAT_CONNTRACK
-A PREROUTING -j PFOR_CONNTRACK
-A PREROUTING -j FW_CONNTRACK
-A PREROUTING -j NOTRACK
-A OUTPUT -j VYATTA_CT_OUTPUT_HOOK
-A OUTPUT -j NAT_CONNTRACK
-A OUTPUT -j PFOR_CONNTRACK
-A OUTPUT -j FW_CONNTRACK
-A OUTPUT -j NOTRACK
-A FW_CONNTRACK -j ACCEPT
-A NAT_CONNTRACK -j ACCEPT
-A PFOR_CONNTRACK -j ACCEPT
-A VYATTA_CT_OUTPUT_HOOK -j RETURN
-A VYATTA_CT_PREROUTING_HOOK -j RETURN
COMMIT

*nat
:PREROUTING ACCEPT [173:29090]
:INPUT ACCEPT [7:417]
:OUTPUT ACCEPT [15:903]
:POSTROUTING ACCEPT [56:3802]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:UBNT_PFOR_DNAT_HOOK - [0:0]
:UBNT_PFOR_DNAT_RULES - [0:0]
:UBNT_PFOR_SNAT_HOOK - [0:0]
:UBNT_PFOR_SNAT_RULES - [0:0]
:UBNT_SUSPEND_DNAT_HOOK - [0:0]
:UBNT_VPN_IPSEC_SNAT_HOOK - [0:0]
:VYATTA_DNAT - [0:0]
:VYATTA_PRE_DNAT_HOOK - [0:0]
:VYATTA_PRE_SNAT_HOOK - [0:0]
:VYATTA_SNAT - [0:0]
-A PREROUTING -j MINIUPNPD
-A PREROUTING -j UBNT_PFOR_DNAT_HOOK
-A PREROUTING -j VYATTA_PRE_DNAT_HOOK
-A PREROUTING -j UBNT_SUSPEND_DNAT_HOOK
-A PREROUTING -j VYATTA_DNAT
-A POSTROUTING -j UBNT_VPN_IPSEC_SNAT_HOOK
-A POSTROUTING -j MINIUPNPD-POSTROUTING
-A POSTROUTING -j UBNT_PFOR_SNAT_HOOK
-A POSTROUTING -j VYATTA_PRE_SNAT_HOOK
-A POSTROUTING -j VYATTA_SNAT
-A UBNT_PFOR_DNAT_HOOK -i pppoe0 -m set --match-set ADDRv4_pppoe0 dst -j UBNT_PFOR_DNAT_RULES
-A UBNT_PFOR_DNAT_HOOK -i eth1 -m set --match-set ADDRv4_pppoe0 dst -j UBNT_PFOR_DNAT_RULES
-A UBNT_PFOR_DNAT_HOOK -i eth2 -m set --match-set ADDRv4_pppoe0 dst -j UBNT_PFOR_DNAT_RULES
-A UBNT_PFOR_SNAT_HOOK -o eth1 -j UBNT_PFOR_SNAT_RULES
-A UBNT_PFOR_SNAT_HOOK -o eth2 -j UBNT_PFOR_SNAT_RULES
-A VYATTA_PRE_SNAT_HOOK -j RETURN
-A VYATTA_SNAT -o pptpc0 -m set --match-set rkn-blocked-ips dst -m comment --comment NAT-5000 -j MASQUERADE
-A VYATTA_SNAT -o pppoe0 -m comment --comment NAT-5001 -j MASQUERADE
COMMIT

*filter
:INPUT ACCEPT [368:105943]
:FORWARD ACCEPT [996:160271]
:OUTPUT ACCEPT [306:35685]
:UBNT_PFOR_FW_HOOK - [0:0]
:UBNT_PFOR_FW_RULES - [0:0]
:VYATTA_FW_IN_HOOK - [0:0]
:VYATTA_FW_LOCAL_HOOK - [0:0]
:VYATTA_FW_OUT_HOOK - [0:0]
:WAN_IN - [0:0]
:WAN_LOCAL - [0:0]
-A INPUT -j VYATTA_FW_LOCAL_HOOK
-A FORWARD -j UBNT_PFOR_FW_HOOK
-A FORWARD -j VYATTA_FW_IN_HOOK
-A FORWARD -j VYATTA_FW_OUT_HOOK
-A UBNT_PFOR_FW_HOOK -i pppoe0 -j UBNT_PFOR_FW_RULES
-A VYATTA_FW_IN_HOOK -i pppoe0 -j WAN_IN
-A VYATTA_FW_LOCAL_HOOK -i pppoe0 -j WAN_LOCAL
-A WAN_IN -m comment --comment WAN_IN-10 -m state --state RELATED,ESTABLISHED -j RETURN
-A WAN_IN -m comment --comment WAN_IN-20 -m state --state INVALID -j DROP
-A WAN_IN -m comment --comment "WAN_IN-10000 default-action drop" -j DROP
-A WAN_LOCAL -m comment --comment WAN_LOCAL-10 -m state --state RELATED,ESTABLISHED -j RETURN
-A WAN_LOCAL -m comment --comment WAN_LOCAL-20 -m state --state INVALID -j DROP
-A WAN_LOCAL -m comment --comment "WAN_LOCAL-10000 default-action drop" -j DROP
COMMIT

ipv6 не используется, выключен в настройках адаптера хоста
blockcheck запускал на роутере

**Comment by bol-van** [comment]
Возможно, есть какой-то конфликт с вашими правилами iptables
Попробуйте их всех вычистить под ноль и потом запустить сервис

-A POSTROUTING -o eth0 -p tcp -m tcp --dport 443 -j NFQUEUE --queue-num 200 --queue-bypass

Вот это руками добавлялось , да ? Мои скрипты вставили бы connbytes, чтобы не бросать весь исходящий трафик в очередь
nfqws использует mark по умолчанию 0x40000000/0x40000000. Это вступает в конфликт с вашим использованием mark 0x800000/0x7f800000

**Comment by CherMet90** [comment]
По дебагу вижу, что работает:
`packet: id=102 len=52
IP4: 192.168.1.50 => 188.65.124.92 proto=tcp sport=41042 dport=443 flags=S seq=830452366 ack_seq=0
packet: id=102 pass unmodified
packet: id=103 len=40
IP4: 192.168.1.50 => 188.65.124.92 proto=tcp sport=41042 dport=443 flags=A seq=830452367 ack_seq=3920904886
packet: id=103 pass unmodified
packet: id=104 len=557
IP4: 192.168.1.50 => 188.65.124.92 proto=tcp sport=41042 dport=443 flags=AP seq=830452367 ack_seq=3920904886
TCP: 16 03 01 02 00 01 00 01 FC 03 03 A6 9E 81 EE A5 D2 7E 23 5F F6 3B 5C 3A 0F 44 71 D2 58 2F 82 FB ... : .................~#_.;\:.Dq.X/.. ...
packet contains TLS ClientHello
hostname: www.dailymotion.com
dpi desync src=192.168.1.50:41042 dst=188.65.124.92:443
sending fake request : 16 03 01 02 00 01 00 01 FC 03 03 9A 8F A7 6A 5D 57 F3 62 19 BE 46 82 45 E2 59 5C B4 48 31 12 15 ... : ..............j]W.b..F.E.Y\.H1.. ...
sending 1st tcp segment 0-1 len=2 : 16 03 : ..
sending 2nd tcp segment 2-516 len=515 : 01 02 00 01 00 01 FC 03 03 A6 9E 81 EE A5 D2 7E 23 5F F6 3B 5C 3A 0F 44 71 D2 58 2F 82 FB 94 56 ... : ...............~#_.;\:.Dq.X/...V ...
packet: id=104 drop
`
Но сайт недоступен (проверяю www.dailymotion.com)
Также вижу, что Ip назначения отличается от Ip, который отображается по nslookup
Может в этом дело?
Кстати, goodbyeDPI успешно открывает, именно если включен dns-redirect

**Comment by bol-van** [comment]
Если DNS неправильный, например подмененный провайдером, то nfqws не будет решать эту проблему, ни о каком обходе речи не идет.
Но здесь это не так. Крупные сервисы по DNS часто выдают разные IP в зависимости от географического положения клиента. По whois ip 188.65.124.92 принадлежит сети dailymotion, так что DNS не подменяется

Вот это срабатывает :
`curl -v --resolve dailymotion.com:443:188.65.124.92 https://www.dailymotion.com`

В твоем варианте обходится только по https. потому и надо проверять только https
если в броузере ввести строку www.dailymotion.com, то броузер может дернуть сначала http, и там блокировка
через curl надо проверять для начала

**Comment by CherMet90** [comment]
Ок, спасибо. С доступностью конкретного ресурса я разберусь
Другой вопрос: Есть ли какой-то режим, типа байпасс?
Поясню. Начали наблюдаться неполадки с доступностью различных ресурсов и приложений в локалке и в целом ухудшение отклика по всем ресурсам.
Проблему решил удалением твоего правила из iptables. Хотя процесс nfqws от пользователя tpws не запущен, запущен только от рута:
```
vbash-4.1# ps xau | grep nfqws
root     26311  0.0  0.3   3004  1576 ttyS0    R+   08:42   0:00 grep nfqws
```
Это само правило вызывает проблемы, даже с неактивным nfqws?
Проверял утилизацию памяти и ЦП роутера, вроде все ок
