### ISSUE TITLE
можно ли изменить логику работы блокчека в режиме normal

### ISSUE THREAD

**Issue by kotsmotritnastul** [bol-van/zapret#884]
сейчас блокчек в режиме fast прекращает тестирование способа обхода в случае первой же неудачи и переходит к следующему способу, однако прекращает работу при нахождении первого способы обхода, который проходит успешно все повторения теста.
в режиме normal блокчек не прекращает тесты после нахождения способы который успешно проходит все повторения теста, но делает все повторения теста даже если первое было неудачным.

при этом рабочим способ обхода считается только если все повторения теста прошли успешно, то есть в режиме normal после первого же неудачного повторения теста способа обхода можно его прекращать и переходить к тесту следующего способа обхода, это могло бы сэкономить кучу времени, особенно в ситуациях когда способы блокировки часто меняются.

можно ли сделать так чтобы в режиме normal блокчек переходил к тестированию следующего способа обхода сразу после первой же неудачи? ведь если хоть одна неудача была то способ всё равно не будет считаться работающим, а значит нет смысла делает ещё несколько повторений, которые занимают суммарно по 40-50 минут при 4-6 повторениях каждого теста.

если так сделать нельзя по каким-то причинам то какие строчки в блокчеке мне надо поменять чтобы в режиме normal блокчек тестировал все способы обхода после нахождения первого полностью рабочего но прекращал тестировать каждый конкретный способ и переходил к следующему если хотя бы в одном повторении теста была неудача? в режиме fast такое уже есть, может быть оттуда можно что-то скопипастить в строки которые отвечают за работу режиме normal.

я к сожалению не смог разобраться в сложных башскриптах, поэтому не понял как это сделать самостоятельно.

**Comment by bol-van** [comment]
Много раз отвечал на этот вопрос.
blockcheck сделан не столько для копипастеров, сколько для исследователь DPI, а там важно видеть общую картину.
Характер ошибок, их частота - тоже часть полезной информации.
Я понимаю, что юзеру это как до лампочки, но это делалось не для юзеров.
В будущем планируется делать тесты разных доменов и попытки параллельно. Если эта идея выгорит, не будет нужды в прекращении тестирования после первой неудачи

**Comment by bol-van** [comment]
```
curl_test()
{
	# $1 - test function
	# $2 - domain
	# $3 - subst ip
	# $4 - param of test function
	local code=0 n=0

	while [ $n -lt $REPEATS ]; do
		n=$(($n+1))
		[ $REPEATS -gt 1 ] && printf "[attempt $n] "
		if $1 "$IPV" $2 $3 "$4" ; then
			[ $REPEATS -gt 1 ] && echo 'AVAILABLE'
		else
			code=$?
			[ "$SCANLEVEL" = quick ] && break
		fi
	done
	[ "$4" = detail ] || {
		if [ $code = 254 ]; then
			echo "UNAVAILABLE"
		elif [ $code = 0 ]; then
			echo '!!!!! AVAILABLE !!!!!'
		else
			echo "UNAVAILABLE code=$code"
		fi
	}
	return $code
}

```

			[ "$SCANLEVEL" = quick ] && break
=>
			break

**Comment by kotsmotritnastul** [comment]
а, ну раз это для исследования dpi то тогда было бы полезно выводить хотя бы процентное соотношение удач/неудач в режиме normal, потому что сейчас единственный известный мне способ исследования это `script -q -c "./blockcheck.sh" log.txt` и потом читать простыню на много экранов. возможно есть способ парсить вывод на лету но я не понимаю по каким ключевым словам его нагуглить.

в любом случае сейчас на программу бешеный спрос и скрипт в 99% используют для того чтобы по-быстрому понять после работы что там опять сломали.

за указание конкретных строчек большое спасибо, сейчас попробую.

**Comment by kotsmotritnastul** [comment]
да, вроде работает как должно, насколько я понял надо менять строку https://github.com/bol-van/zapret/blob/35a28f4efe05ededa92f435359018bfef130009d/blockcheck.sh#L976
