### ISSUE TITLE
Ошибки sysctl на Keentic при выполнении команды stop

### ISSUE THREAD

**Issue by MAD-BUG** [bol-van/zapret#889]
Версия zapret: 69.3
Платформа KeeneticOS 4.2.3

Если в конфиге указаны локальные интерфейсы, то при выполнении команды "zapret stop" в конце вывода наблюдаются данные сообщения:
sysctl: error: 'net.ipv4.conf.br0' must be of the form name=value
sysctl: error: 'nwg0/route_localnet' is an unknown key

bro основной мост объединяющий LAN порты и домашюю(основную) сеть Wi-Fi
nwg0 интерфейс подключения WireGuard 

При использовании команды "zapret start" аналогичных сообщений нету.

**Comment by bol-van** [comment]
кинетик не поддерживается
если хотите фикса разберитесь до деталей
и мы подумаем как это лучше сделать совместимым

**Comment by bol-van** [comment]
найдено, исправлено
проблема к кинетику не относится
