### ISSUE TITLE
Openwrt исключение локального IP адреса (src)

### ISSUE THREAD

**Issue by plimut** [bol-van/zapret#89]
Firewall - Custom Rules

##################### ZAPRET BYPASS ##################
iptables -t mangle -I POSTROUTING -s 192.168.1.5 -j RETURN
######################################################

Приоритет правила в таблице mangle переопределяется после инициализации zapret, невозможно создать исключение для подключенного к роутеру устройства.

MODE_FILTER=none

**Comment by bol-van** [comment]
СИСТЕМА ИСКЛЮЧЕНИЯ IP. Все скрипты ресолвят файл zapret-hosts-user-exclude.txt, создавая zapret-ip-exclude.txt и zapret-ip-exclude6.txt.
Они загоняются в ipset-ы nozapret и nozapret6. Все правила, создаваемые init скриптами, создаются с учетом этих ipset.
Помещенные в них IP не участвуют в процессе.
zapret-hosts-user-exclude.txt может содержать домены, ipv4 и ipv6 адреса или подсети.

**Comment by bol-van** [comment]
```
-A POSTROUTING -o eth0 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:4 --connbytes-mode packets --connbytes-dir original -m set --match-set zapret dst -m mark ! --mark 0x40000000/0x40000000 -m set ! --match-set nozapret dst -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth0 -p tcp -m tcp --dport 80 -m set --match-set zapret dst -m mark ! --mark 0x40000000/0x40000000 -m set ! --match-set nozapret dst -j NFQUEUE --queue-num 200 --queue-bypass

ipset list nozapret
Members:
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
169.254.0.0/16

cat /opt/zapret/ipset/zapret-hosts-user-exclude.txt 
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
169.254.0.0/16
fc00::/7
fe80::/10
```

**Comment by plimut** [comment]
Там получается вот что, при включенном MODE_FILTER=ipset, если не заполнять сам set zapret IP адресами списка РКН то условие --match-set zapret dst не выполняется т.к. он пуст, соответственно ни чего не работает, и добавление в ipset list nozapret не имеет смысла.
Можно ли как то включить обход для всего кроме локального 192.168.1.5 не загружая список РКН ?
И на сколько я понимаю --match-set nozapret dst нужен для указания интернет-адресов (назначения) котрые необходимо исключить из работы, а не локальных src, если не затруднит, внесите пожалуйста ясность.

**Comment by bol-van** [comment]
Видимо нет гарантии в каком порядке применяются firewall includes.

Но есть еще вариант. В новых версиях zapret в конфиге есть

```
#INIT_FW_PRE_UP_HOOK="/etc/firewall.zapret.hook.pre_up"
#INIT_FW_POST_UP_HOOK="/etc/firewall.zapret.hook.post_up"
#INIT_FW_PRE_DOWN_HOOK="/etc/firewall.zapret.hook.pre_down"
#INIT_FW_POST_DOWN_HOOK="/etc/firewall.zapret.hook.post_down"

```
Эти хуки специально созданы для синхронизации с применением фаервола со стороны zapret

**Comment by plimut** [comment]
OpenWrt 21.02.1 r16325-88151b8303 патч подтверждаю.

config include
<------>option path '/etc/firewall.zapret'
<------>option reload '1'

config include
<------>option path '/etc/firewall.user'

Правило после хардресета сохраняется стабильно, вот оно:

-A POSTROUTING -s 192.168.1.5/32 -j MARK --set-xmark 0x40000000/0x40000000
-A POSTROUTING -o pppoe-wan -p tcp -m multiport --dports 80,443 -m connbytes --connbytes 1:4 --connbytes-mode packets --connbytes-dir original -m mark ! -- etc...

Хуки не использовал, достаточно было git pull, спасибо Вам за то что вы есть.

**Comment by bol-van** [comment]
Я в этом патче только убрал пересоздание инклуда /etc/firewall.zapret в install_easy.sh
Если его не дергать лишний раз, то и раньше все было бы точно так же

**Comment by plimut** [comment]
С патчем все ок, но iptables -t mangle -I POSTROUTING -s 192.168.1.5 -j MARK --set-xmark 0x40000000/0x40000000 не рабочий вариант, на "устройстве" работает только iptables -t mangle -I POSTROUTING -s 192.168.1.5 -j RETURN

**Comment by bol-van** [comment]
У меня именно такая команда вполне себе работает
При ее применении обход перестает работать, вылезают заглушки провайдера
работать это будет только в режиме nfqws

**Comment by plimut** [comment]
Я Вас понял, совсем неясно почему хардресет после последнего гитпула стал сохранять правило -I именно ДО запрета а не после, я вчера боролся с этим целый вечер, после перезагрузки мое правило оказывалось полсе. Сейчас проблем не вижу, стабильно ДО, и конечно nfqws. Я не могу и не хочу Вас подставлять что это за устройство.

**Comment by plimut** [comment]
Единственное что я сделал это удалил полностью папку zapren перекачал клон и сейчас стабильно работает, правило на месте, меня беспокоит только fw3

**Comment by bol-van** [comment]
> совсем неясно почему хардресет после последнего гитпула стал сохранять правило -I именно ДО запрета а не после

Я же не знаю с какой версии обновление было
Могу подозревать, что связано это с корректировкой скрипта /etc/hotplug.d/iface/90-zapret

По умолчанию firewall include не вызывается по событию reload. В частности, /etc/firewall.user.
zapret всегда выставляет вызов по reload
Скрипт из hotplug раньше перегружал правила zapret по любому чиху, а сейчас это существенно оптимизировано

**Comment by plimut** [comment]
Последнее чем я Вас попытаю, если конечно не сильно затруднит, внесите ясность (просьба для понимания) каким именно образом правило iptables -t mangle -I POSTROUTING -s (локальный IP) -j RETURN в firewall.user может выбить портфорвардинг fw3, и на сколько это критично для безопасности.
