### ISSUE TITLE
new dns lawfilter dom.ru

### ISSUE THREAD

**Issue by phant** [bol-van/zapret#9]
Addresses:  2a02:2698:a002:1::3:17
          5.3.3.17

**Comment by bol-van** [comment]
обновил, но проверять не на чем

**Comment by phant** [comment]
я сделал на [микротике аналогичные правила,](https://gist.github.com/phant/8f4c9be244195cf161233bbeb7567b72) основываясь на чужих разработках 
у меня всё отрабатывает.

полагаю, что правила iptables заработают тоже
