### ISSUE TITLE
OpenWrt обновление прошивки

### ISSUE THREAD

**Issue by Alexey71** [bol-van/zapret#90]
Приветствую. Собираю прошивку с уже встроенными нужными пакетами. После обновления прошивки OpenWrt через `sysupgrade.bin`, приходится запускать `/opt/zapret/install_easy.sh` для восстановления работы.  В конфигурацию сохранения добавил всю папку `/opt` при обновлении прошивки она сохраняется. Можете подсказать, какие еще файлы нужны для сохранения работы после обновления прошивки?

**Comment by bol-van** [comment]
там не столько файлы, сколько линки

```
adm@router:~$ ll /etc/hotplug.d/iface/90-zapret 
lrwxrwxrwx 1 root root 36 Feb 15 20:55 /etc/hotplug.d/iface/90-zapret -> /opt/zapret/init.d/openwrt/90-zapret
adm@router:~$ ll /etc/init.d/zapret 
lrwxrwxrwx 1 root root 33 Feb 15 20:54 /etc/init.d/zapret -> /opt/zapret/init.d/openwrt/zapret
adm@router:~$ ll /etc/rc.d/*zapret*
lrwxrwxrwx 1 root root 16 Feb 15 20:54 /etc/rc.d/S21zapret -> ../init.d/zapret
adm@router:~$ ll /etc/firewall.zapret 
lrwxrwxrwx 1 root root 42 Feb 15 20:55 /etc/firewall.zapret -> /opt/zapret/init.d/openwrt/firewall.zapret
adm@router:~$ 
```

**Comment by Alexey71** [comment]
А как их можно сохранить при обновлении?

**Comment by bol-van** [comment]
Я не задавался вопросом совместимости с sysupgrade
Полагаю, что этот вопрос не слишком актуален.
Не так часто делается, прогнать install лишний раз после апгрейда - минутное дело

**Comment by Alexey71** [comment]
Спасибо
