### ISSUE TITLE
Багует софт от razer, когда открыт zapret

### ISSUE THREAD

**Issue by AmandaYang679** [bol-van/zapret#901]
Когда запускаю запрет (естественно от админа), практически каждый раз слетает конфиг мыши от razer. И пока запрет открыт, сама программа не откроется, хотя запущена фоном и отображается на панели задач, просит войти в razer, чтобы открыть razer synapse, хотя вход выполненен и сам synapse также показывается работающим в диспетчере задач. 
Переустановка софта не помогла. Считаю, что проблема именно в запрете, потому что раньше такой беды не было, и решается проблема после закрытия запрета:
Единственный вариант снова "активировать" пользовательский конфиг, это закрывать запрет, в диспетчере снимать задачу с winws.exe, закрывать razer и заходить снова. Потом это какое-то время работает.

Возможно кто-то знает как это починить?
Заранее спасибо

**Comment by bol-van** [comment]
zapret не работает по принципу акл выкл
стратегии могут ломать ресурсы
универсальных нет
а если это сборка то тему закрываю

**Comment by AmandaYang679** [comment]
не знаю сборка это или нет, я просто 1,5 месяца назад скачал весь код через сам гитхаб, а не релиз (еще до 67 релиза), там еще куча батников с альтернативными сборками, и оно работало и работает, только вот стала появляться такая проблема.
Если сборка, то закрывайте, вопросов не имею, спасибо, что обратили внимание

**Comment by bol-van** [comment]
куча каких батников ?
все что здесь есть - в этом репозитории и в win bundle
советую прочитать docs/quick_start_windows.md
может быть вопросы сами отпадут

**Comment by AmandaYang679** [comment]
![image](https://github.com/user-attachments/assets/3b7698e5-4917-4f61-ade6-d1974e5947d5)
вот эти батники с разными конфигами

**Comment by bol-van** [comment]
сборка
вопросы к авторам
