### ISSUE TITLE
Здраствуйте, а где мне запускать файлы чтобы работало всё? 

### ISSUE THREAD

**Issue by dsijdshaij** [bol-van/zapret#912]
![392673890-cd0b2f51-2751-456d-90a2-e969851436ad](https://github.com/user-attachments/assets/3b4647d1-277f-46be-a8cb-647f5bbf07e9)

**Comment by ry0shi** [comment]
хороший вопрос, ибо туториала нормального нет и остаётся только гадать что делать со всем этим добром

**Comment by dsijdshaij** [comment]
> хороший вопрос, ибо туториала нормального нет и остаётся только гадать что делать со всем этим добром

это для линукса
