### ISSUE TITLE
Падает процесс nfqws

### ISSUE THREAD

**Issue by nikrays** [bol-van/zapret#916]
Падает процесс nfqws на кинетике. Проблема появляется на многих роутерах, но не на всех. Перед тем как процесс падает в логе появляется:
```
recv: errno 132 
recv: Broken pipe 
unbinding from queue 200
```

Лог прикладываю. Тестировалось как с листами, так и без, результат одинаковый. Опытным путем выяснили, что проблема появляется, если воспроизвести следующие шаги:

1. Перезагрузил Keenetic
2. Зашел в epic games
3. 5 минут тыкал инстаграм ютуб, параллельно тыкал вкладки лаунчера - все ок
4. Запустил загрузку игры
5. +-5 минут тыкал YouTube инстаграм на компе - все ок
6. Пошел тыкать инстаграм YouTube на телефоне
7. Zapret перестал работать
8. Достал свежий лог, для отправки в issue
9. Запустил Zapret командой, снова все поднялось, лог соответственно очистился, после чего повторил все шаги, проблема повторилась

PS. Аналогичный баг был замечен на 4 разных Keenetic на разных операторах в разных городах.

PPS. Используется оригинальный репозиторий zapret с zapret-udp-fix в custom.d

PPPS. Наличие epicgames в листах или его отсутствие не влияет на падение процесса, баг по прежнему есть.

Лог:
[debug.log](https://github.com/user-attachments/files/18028845/debug.log)

**Comment by electrifying** [comment]
Скрипт на netfilter установлен?

**Comment by nikrays** [comment]
@electrifying 
Шутите?
Падает процесс, а не правила

**Comment by bol-van** [comment]
Процесс завершается, потому что идет ошибка работы с nfqueue.
Это что-то с ядром

**Comment by nikrays** [comment]
> Процесс завершается, потому что идет ошибка работы с nfqueue. Это что-то с ядром
> 
> Вот поэтому я и не поддерживаю стоковые прошивки, включая кинетик.

Возникла проблема после того ка были добавлены multidisorder и ТП, после этих сборок началось

**Comment by bol-van** [comment]
Там не менялось ничего в коде работы с nfqueue. Совсем.
На других системах нигде еще не встречал.
Может еще какой-то баг триггерится ядра.
В любом случае я делать ничего не буду , чтобы выяснить что там в кинетике не так.
Будет на других системах - разберемся

**Comment by bol-van** [comment]
Первым делом следует отсечь такую проблему, когда нет в iptables правилах проверки на desync mark.
Если там какие-то свои скрипты запуска без mark, то это проблема

**Comment by bol-van** [comment]
А еще может быть проблема, что прошивка портит desync mark

**Comment by electrifying** [comment]
А на каких именно моделях проблема, есть список? Попробую воспроизвести тоже проблему

**Comment by nikrays** [comment]
@bol-van 
Использую только:
Правило: netfilter.d
С автозапуском: ln -fs /opt/zapret/init.d/sysv/zapret /opt/etc/init.d/S99zapret
По пути: /opt/etc/ndm/netfilter.d/zapret.sh
```bash
#!/opt/bin/sh
[ "$type" == "ip6tables" ] && exit 0
[ "$table" == "filter" ] && exit 0
[ "$table" == "raw" ] && exit 0
/opt/etc/init.d/S99zapret restart-fw > /dev/null
```
С правами: chmod +x /opt/etc/ndm/netfilter.d/zapret.sh

А также ваш кастомный скрипт: 10-keenetic-udp-fix
По пути: /opt/zapret/init.d/sysv/custom.d/

**Comment by nikrays** [comment]
@bol-van 
Думаете, что все-таки в маркировке может быть дело? Вот я эту проблему воспроизвести не смог, у меня лично Keenetic Hopper SE на arm

**Comment by bol-van** [comment]
Если  сбивается  маркировка возникают повторные забросы пакетов в очередь, что приводит к рекурсии и дедлокам.
Это факт.
А что здесь я не знаю. Только предполагаю

**Comment by nikrays** [comment]
> Если сбивается маркировка возникают повторные забросы пакетов в очередь, что приводит к рекурсии и дедлокам. Это факт. А что здесь я не знаю. Только предполагаю

В общем потестил без udp-fix, а также вообще без udp, отключив порты и стратегии соответственно. Падает также, и при чем не важно что включаешь, есть много дебаг логов, но где там искать причину и как из расшифровать, знаний нет, но могу сказать что до сборки где были добавлены мультисплиты и тд жалоб не было, я попробую установить старые ваши версии и скажу на какой все ок..

**Comment by bol-van** [comment]
Я бы посмотрел какой-нибудь подлиннее. Важно выяснить нет ли повторных инжектов из-за сбитого mark

**Comment by nikrays** [comment]
> Я бы посмотрел какой-нибудь подлиннее. Важно выяснить нет ли повторных инжектов из-за сбитого mark

На 162мб, норм?)

**Comment by nikrays** [comment]
> Я бы посмотрел какой-нибудь подлиннее. Важно выяснить нет ли повторных инжектов из-за сбитого mark

[Debug_logs.zip](https://github.com/user-attachments/files/18049174/Debug_logs.zip)

**Comment by bol-van** [comment]
Реинжектов нет.
Подозреваю это какой-то баг ядра. Где был один, может быть и другой.
Возможно, поможет workaround. Переинциализировать очередь в случае ошибки EPIPE.
Но проверять мне не на чем

**Comment by nikrays** [comment]
> Реинжектов нет. Подозреваю это какой-то баг ядра. Где был один, может быть и другой. Возможно, поможет workaround. Переинциализировать очередь в случае ошибки EPIPE. Но проверять мне не на чем

Вы скажите что нужно сделать, я сделаю и могу проверить что нужно

**Comment by bol-van** [comment]
Собрать с исходников сможете ?

**Comment by nikrays** [comment]
> Собрать с исходников сможете ?

В гит же? Ну да, что там собирать, релиз сдалал и actions пошел собирать

**Comment by bol-van** [comment]
Я не буду делать релиз, только залью потенциальное лечилово для этой ситуевины
нужно будет самому собрать

**Comment by bol-van** [comment]
По ходу там еще ошибка с выводом сообщения об ошибке.
errno выводит правильно. 132. а broken pipe - неверно.
там портится errno, не сохраняется

#define ERFKILL		132	/* Operation not possible due to RF-kill */

Не знаю каким образом в кинетике задействуется механизм rf-kill

**Comment by bol-van** [comment]
Вылил исходники, которые позволят более детально рассмотреть что же там происходит.
Пока это еще не фикс, тк не ясны детали

**Comment by wigeance** [comment]
На том же девайсе где nfqws падает, поднимал tpws, он не падает, но сыпет ошибки. Вот лог, при этом сайты открывает заблокированные, несмотря на ошибки
[log.txt](https://github.com/user-attachments/files/18049567/log.txt)

**Comment by nikrays** [comment]
> Вылил исходники, которые позволят более детально рассмотреть что же там происходит. Пока это еще не фикс, тк не ясны детали. Нужен дебаг лог с этим вариантом

Собрал, почти час теста.. жду отвала

**Comment by bol-van** [comment]
про segmentation failed очень пространно написано в readme
тут ничего не сделаешь нормальным способом, но можно использовать --fix-seg

**Comment by bol-van** [comment]
> Собрал, почти час теста.. жду отвала

особо надо обратить внимание на сообщения
"recv from nfq returned 0 !"

**Comment by nikrays** [comment]
> > Собрал, почти час теста.. жду отвала
> 
> особо надо обратить внимание на сообщения "recv from nfq returned 0 !"

[Uploading debug.log…]()

**Comment by bol-van** [comment]
Уже не первый раз присылают лог, в котором не появляются сообщения

recv: errno XXX
recv: XXX
unbinding from queue 200

так что информативности 0

почему они появляются я не знаю. какая-то проблема с записью в файл, возможно.
в консоли надо дебажить, запустив процесс руками
--debug=@file почему-то не срабатывает

**Comment by nikrays** [comment]
> Уже не первый раз присылают лог с кинетика, в котором не появляются сообщения
> 
> recv: errno XXX recv: XXX unbinding from queue 200
> 
> так что информативности 0
> 
> почему они не появляются я не знаю. какая-то проблема с записью в файл, возможно. если сэмулировать ошибку recv, у меня все как надо в файл записывает. возможно, это признак какого-то системного сбоя, который в том числе и вызывает исходную проблему
> 
> а сейчас в консоли надо дебажить, запустив процесс руками --debug=@file почему-то не срабатывает

Но что самое интересное если не выходить из консоли а продолжать там находиться то выходят такие сообщения 
![IMG_20241208_090816_672](https://github.com/user-attachments/assets/8272254d-6723-4548-a20a-05c5744d6f73)

**Comment by nikrays** [comment]
recv: recv=-1 errno 132
recv: No buffer space available

Когда падёт выдает такие сообщения, может быть проблема в http?

**Comment by bol-van** [comment]
Эта ошибка означает, что процесс не успевает получать данные из очереди.
Что-то где-то застревает

**Comment by bol-van** [comment]
Сделал установку setsockopt NETLINK_NO_ENOBUFS.
Попробуйте текущий вариант

**Comment by nikrays** [comment]
> Сделал установку setsockopt NETLINK_NO_ENOBUFS. Попробуйте текущий вариант

Спасибо, хорошо

**Comment by bol-van** [comment]
Когда оно заглючит надо еще смотреть что с памятью.
Может опять ядро все сожрало из-за очередного бага

**Comment by nikrays** [comment]
> Когда оно заглючит надо еще смотреть что с памятью. Может опять ядро все сожрало из-за очередного бага

Не, с памятью все ок, я наблюдал за этим в этот период, щас идёт сборка, на другой локации отключил полностью http, попробую и без него

**Comment by bol-van** [comment]
http не может быть причиной. NFQUEUE никак не связан с этим уровнем.

сама по себе ошибка 132 совсем непонятна. Это ERFKILL, который вряд ли может иметь отношение к nfqueue.
И текст ошибки не соответствует коду 132.
132 выдала последняя версия ? В старой могло  показываться неверное сообщение

**Comment by nikrays** [comment]
132 в любой показывалось версии, между прочим такой баг отсутствовал ранее, я хочу как нибудь проверить на какой версии впервые возникла

**Comment by bol-van** [comment]
Я же говорю, ничего не менялось в этом коде уже очень давно.
Если оно как-то и началось из-за чего-то, то лишь косвенным образом

**Comment by nikrays** [comment]
Ну пока ровно час прошел, пока не падает процесс, ждём до вечера, скорее всего если не упадет то проблема решена

**Comment by nikrays** [comment]
Могу вам на текущем этапе скинуть лог, скинуть?

**Comment by bol-van** [comment]
Если не падает и нет сообщений "recv......", то не надо

**Comment by wigeance** [comment]
поймал и на своем кинетике похожий прикол, процесс не упал, но наспамил в консольку. Я не собирал бинарники, это на релизной 69.5. Воспроизвести пока не смог
Но похоже на косяк ядра какой-то мб? Потому что рядом крутится openwrt и на нем все идеально

```
rawsend: sendto: Message too large
rawsend: sendto: Message too large
rawsend: sendto: Message too large
```

**Comment by bol-van** [comment]
К кинетику не имеет отношения.
Идет отсылка пакета больше MTU.
Может случиться по разным причинам.
Например, идет fakedsplit около конца полного пакета и используется fooling=md5sig.  md5sig добавляет tcp option, итоговый пакет не влезает в MTU. дурение отменяется, идет выплевывание оригинала.
Большой seqovl тоже может привести к этому. Так же как и ipv6 specific хедеры

**Comment by nikrays** [comment]
> Сделал установку setsockopt NETLINK_NO_ENOBUFS. Попробуйте текущий вариант Возможен такой эффект, что вместо ошибок начнется зависание инета. Дроп пакетов

Спустя сутки тестов на более чем 30 роутеров, жалоб не возникло. Этот фикс решает проблему, в выводе консоли теперь нет сообщений о буфере, а также процесс перестал падать.
Что касается "эффекта зависания интернета или дропа пакетов" то также пользователями замечено не было, вероятно если делать ежесекундный точный анализ, то может быть и получится что-то найти, но пользовательский опыт в целом положительный. Спасибо большое!
Этот фикс будет в составе следующих ваших релизов? Он не конфликтует с вашим основным направлением под openwrt?

**Comment by bol-van** [comment]
Не конфликтует.
Скорее всего дропы изредка случаются в те моменты, которые иначе бы вылились в завершение процесса.
Но они редки и легко выправляются ретрансмиссиями

**Comment by nikrays** [comment]
> Не конфликтует. Скорее всего дропы изредка случаются в те моменты, которые иначе бы вылились в завершение процесса. Но они редки и легко выправляются ретрансмиссиями

То есть скорее всего обычный человек в использовании интернета дискомфорта не почувствует, верно?

**Comment by bol-van** [comment]
Если еще не почувствовали за сутки на 30 роутерах, то вряд ли

**Comment by bol-van** [comment]
Проверяйте v69.6

**Comment by nikrays** [comment]
Я также хотел бы узнать, можно ли использовать коммиты для себя как ориентир? Если нельзя, то смогли бы реализовать возможность?

```
NFQWS_OPT="
# tcp *.googlevideo.com
--filter-tcp=80,443 --dpi-desync=fake,fakedsplit --dpi-desync-fooling=md5sig,badsum,badseq --dpi-desync-split-pos=midsld --dpi-desync-fake-tls=$FAKES_TCP --hostlist=/opt/zapret/ipset/list-googlevideo.txt --new
# tcp antifilter
--filter-tcp=80,443 --dpi-desync=fake,fakedsplit --dpi-desync-fooling=md5sig,badsum,badseq --dpi-desync-split-pos=midsld --dpi-desync-fake-tls=$FAKES_TCP --hostlist=/opt/zapret/ipset/list-antifilter.txt --hostlist=/opt/zapret/ipset/list-rkn.txt --hostlist-auto=/opt/zapret/ipset/list-auto.txt --new
# udp *.googlevideo.com
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=20 --dpi-desync-fake-quic=$FAKES_UDP --hostlist=/opt/zapret/ipset/list-googlevideo.txt --new
# udp all
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=20 --hostlist=/opt/zapret/ipset/list-antifilter.txt --hostlist=/opt/zapret/ipset/list-rkn.txt --hostlist-auto=/opt/zapret/ipset/list-auto.txt --new
# udp discord
--filter-udp=50000-50100 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol=1 --dpi-desync-cutoff=d4
"
```

**Comment by nikrays** [comment]
> Но можно сделать игнорируемые опции --comment "blablabla"

Это уже можно попробовать прямо сейчас?

**Comment by bol-van** [comment]
Пока нет

**Comment by bol-van** [comment]
Собственно поддержка комментариев и не очень нужна.
Все уже сделал стандартный парсер getopt.

Его схема такова : --опция1 параметр1 --опция2 параметр2
Если написать так : --опция1 параметр1 я пришел к тебе --опция2 параметр2  с приветом
"я пришел к тебе" и "с приветом" будут проигнорированы

nfqws --qnum 22 aa aa --debug aa --dpi-desync split a --dpi-desync disorder

спокойно запускается и как надо принимает параметры

**Comment by bol-van** [comment]
да, можно

**Comment by nikrays** [comment]
Понял, спасибо, кстати при сборке ошибка BSD

![image](https://github.com/user-attachments/assets/3c9e9130-72c3-40cc-9eff-5a6089ea56a2)

**Comment by nikrays** [comment]
Я так понимаю, что теперь можно использовать оба варианта, например так:
```
NFQWS_OPT="
# tcp *.googlevideo.com
--filter-tcp=80,443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig,badsum --hostlist=/opt/zapret/ipset/list-googlevideo.txt --new
# tcp all
--filter-tcp=80,443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig,badsum  --hostlist=/opt/zapret/ipset/list-antifilter.txt --hostlist=/opt/zapret/ipset/list-rkn.txt --hostlist-auto=/opt/zapret/ipset/list-auto.txt --new
# udp *.googlevideo.com
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=50 --dpi-desync-fake-quic=$FAKES_UDP --hostlist=/opt/zapret/ipset/list-googlevideo.txt --new
# udp all
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=50 --hostlist=/opt/zapret/ipset/list-antifilter.txt --hostlist=/opt/zapret/ipset/list-rkn.txt --hostlist-auto=/opt/zapret/ipset/list-auto.txt --new
# udp discord
--filter-udp=50000-50100 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol=1 --dpi-desync-cutoff=d4
"
```

И так
```
NFQWS_OPT="
--comment tcp *.googlevideo.com
--filter-tcp=80,443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig,badsum --hostlist=/opt/zapret/ipset/list-googlevideo.txt --new

--comment tcp all
--filter-tcp=80,443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig,badsum --hostlist=/opt/zapret/ipset/list-antifilter.txt --hostlist=/opt/zapret/ipset/list-rkn.txt --hostlist-auto=/opt/zapret/ipset/list-auto.txt --new

--comment udp *.googlevideo.com
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=50 --dpi-desync-fake-quic=$FAKES_UDP --hostlist=/opt/zapret/ipset/list-googlevideo.txt --new

--comment udp all
--filter-udp=443 --dpi-desync=fake --dpi-desync-repeats=50 --hostlist=/opt/zapret/ipset/list-antifilter.txt --hostlist=/opt/zapret/ipset/list-rkn.txt --hostlist-auto=/opt/zapret/ipset/list-auto.txt --new

--comment udp discord
--filter-udp=50000-50100 --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-any-protocol=1 --dpi-desync-cutoff=d4
"
```

Ошибок не будет?

**Comment by nikrays** [comment]
> Любой вариант без слов, начинающихся с "-", сработает --comment пока не доступен

Исходя из нового релиза

**Comment by bol-van** [comment]
Можно использовать comment, но в конфигах, основанных на присвоении shell переменных, он не очень полезен.
Туда нельзя встроить пробел. Так что лучше старой методикой

**Comment by nikrays** [comment]
> Можно использовать comment, но в конфигах, основанных на присвоении shell переменных, он не очень полезен. Туда нельзя встроить пробел. Так что лучше старой методикой

Ну то есть через #
Понял, всеравно спасибо за все.
По поводу того бага, пока на множествах устройств все стабильно, процесс не падает.
