### ISSUE TITLE
Странное поведение с загрузкой в Steam

### ISSUE THREAD

**Issue by MrTold11** [bol-van/zapret#934]
1. Имеется набор стратегий в виде службы под windows:
```
set ARGS=--wf-tcp=80,443 --wf-udp=443,50000-50099 ^
--filter-udp=443 --hostlist=%HOSTLIST% --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"%BIN%quic_initial_www_google_com.bin\" --new ^
--filter-udp=50000-50099 --dpi-desync=fake --dpi-desync-any-protocol --dpi-desync-cutoff=n4 --new ^
--filter-tcp=80 --hostlist-auto=%HOSTLIST% --dpi-desync=split2 --new ^
--filter-tcp=443 --hostlist-auto=%HOSTLIST% --dpi-desync=fake,split2 --dpi-desync-ttl=1 --dpi-desync-split-seqovl=9 --dpi-desync-split-pos=10 --wssize 1:6 --wssize-cutoff=n5 --dpi-desync-fake-tls=\"%BIN%tls_clienthello_www_google_com.bin\"
```
В целом ничего необычного (самое панацейное решение из опыта).
2. Со временем заметил нездоровые симптомы: скачивание и обновление игр в Steam происходит /медленно/. Практикой и wireshark'ом было выяснено, что загрузка идет по 443 порту по tcp, соответственно начались поиски решения с последней стратегией. Debug стратегии ничего необычного не выдает.
3. Спустя тысячу попыток (в тч использование ipset-exclude по диапазонам Steam) было выяснено следующее:
- Если запустить службу, а затем запустить Steam, скачивание происходит с максимальной скоростью.
- Если запустить службу после запуска Steam, либо перезапустить ее с теми же или измененными параметрами, когда Steam уже работает, скорость загрузки драматично падает. А winws.exe в это время кушает полностью ядро процессора. Перезагрузка Steam возвращает все в норму.
- Поведение не зависит от ipset-exclude. В целом мало от чего зависит. При детальном наблюдении даже скорость не всегда падает, но проблема присутствует и выражается в нездоровом потреблении CPU. Если выпилить стратегию tcp 80 либо tcp 443, потребление CPU остается высоким, но недостаточно высоким чтобы влиять на скорость (тариф на треть гигабита, многого ожидать не стоит). Под "выпиливанием" подразумевается также удаление wf-tcp/udp фильтра в самом начале аргументов запуска. А вот если выпилить обе стратегии на tcp, то нагрузка на CPU падает до нуля (соответственно скорость также максимальная).
- Значит, дело никак не касается UDP, а только TCP. Причем не в стратегиях как таковых, а в фильтрах. И даже не в фильтрах как таковых, а только после перезагрузки во время работы Steam, но даже без изменения параметров.
- Если в аргументах оставить исключительно "--wf-tcp=80,443" (больше вообще ничего), нагрузка на CPU при активном скачивании в Steam после перезапуска службы в районе 3-6%. Если к этому добавить фильтры для UDP (!), причем с хостлистом, процесс полностью грузит ядро (11-12%), скорость скачивания значительно падает. Если подождать несколько минут, либо перезапустить Steam, все ок. Без хостлиста CPU нагружен на 3-6%.
4. Перезагрузка и запуск службы происходили так:
```
net stop %SNAME%
sc delete %SNAME%
sc create %SNAME% binPath= "\"%BIN%winws.exe\" %ARGS%" DisplayName= "zapret DPI bypass: %SNAME%" start= auto
sc description %SNAME% "zapret DPI bypass software"
sc start %SNAME%
```
Удаление драйвера WinDivert после каждой остановки сервиса плодов не дало:
```
sc delete windivert
sc stop windivert
```
5. Пытаюсь разобраться в таком ненормальном поведении скорее из принципа. Давайте думать...

P.S. Может примеры с CPU без указания модели относительно глупые, однако весьма наглядно демонстрируют поведение.

**Comment by icynstant** [comment]
Пробовали поставить регион загрузки в стиме Германия Франкфурт? Мне помогло.

**Comment by MrTold11** [comment]
От региона не зависит. Расписал весьма подробно, стратегии работают идеально до тех пор, пока не пересоздать службу и не перезапускать стим после этого. Можно даже не перезапускать, а подождать несколько минут, тогда все снова будет хорошо. И нагрузка на CPU не выше 3%. Перезапуск службы - и ядро забито, скорость падает (по-разному, то на 100 мбит/с, то и вовсе в 10 раз).

**Comment by eastone11** [comment]
попробуй избавиться от wssize 
+ это нулевая фаза. она не работает с hostlist

**Comment by bol-van** [comment]
> --filter-udp=50000-50099 --dpi-desync=fake --dpi-desync-any-protocol --new ^

ТРЭШ ФЛУД опять появляется. Это не панацея, за это надо по башке давать

**Comment by bol-van** [comment]
> При детальном наблюдении даже скорость не всегда падает, но проблема присутствует и выражается в нездоровом потреблении CPU. Если выпилить стратегию tcp 80 либо tcp 443, потребление CPU остается высоким,

Первым дело ТРЭШ флуд отправить в помойку. Без этого даже нечего рассматривать.
Затем надо смотреть --debug что выдается при нагрузке.
Включить в диспетчере показ времени ядра и смотреть где жрется в ядре или в user mode.

**Comment by MrTold11** [comment]
> попробуй избавиться от wssize
> 
> * это нулевая фаза. она не работает с hostlist

Приводил пример, даже без профилей с фильтрами по tcp после перезапуска идет нагрузка на ядро. Чисто из-за wf-tcp=80,443. 



> > --filter-udp=50000-50099 --dpi-desync=fake --dpi-desync-any-protocol --new ^
> 
> ТРЭШ ФЛУД опять появляется. Это не панацея, за это надо по башке давать

Каюсь, это не "продакшн" конфиг, поправил. Никак не влияет на описанное поведение. По остальному посмотрю еще раз

**Comment by eastone11** [comment]
> Каюсь, это не "продакшн" конфиг, поправил.

если тебе он для дискорда, то замени его скриптом

**Comment by bol-van** [comment]
> Приводил пример, даже без профилей с фильтрами по tcp после перезапуска идет нагрузка на ядро. Чисто из-за wf-tcp=80,443.

В целом это нормально, тк каждый исходящий пакет перенаправляется через windivert.
На массивных аплоадах увеличивается нагрузка. Входящие он цепляет по минимуму. Там payload based filter стоит в варианте --wf-tcp/--wf-udp.
Вопрос только в степени нагрузки.
На 12700K мне даже на 1% его не удается грузануть на спидтесте

**Comment by MrTold11** [comment]
> Если у вас не древность, замучанная десяткой, и не гигабитный аплоад, то выше нескольких процентов не должно подниматься.

В том и дело, проца с головой хватает, а канал 350 мбит. На спидтесте сомнительно сравнивать - там у меня даже 0,1% не набирается нагрузки на CPU. Проблема конкретно со стимом и его перезапуском. В один момент проблема есть, через 5 минут - все летает.

**Comment by bol-van** [comment]
Ускорители могут пытаться сократить путь пакета в ядре как это сделано в flow offloading в линухе.
И тем самым обходить некоторые хуки, которые использует windivert.

**Comment by MrTold11** [comment]
> действительно 350 может грузануть целый поток

Но грузит только при определенных условиях и непродолжительное время. Профили одинаковые.

> winws пакеты не изобретает

Может иначе обрабатывает из-за чего-то внутри? Стим их как отправлял, так и отправляет, как принимал, так и принимает, до и после запуска и остановки службы...

> Это все издержки отсутствия connbytes фильтра в windivert. Он есть только в linux.

Если фильтра нет, но в какие-то моменты все работает и загружает без лишних нагрузок на проц, это также может сюда относиться?

**Comment by bol-van** [comment]
Надо смотреть трафик выгрузки в  момент загруза. Действительно ли там мощный аплоад ?
Tmeter поставить какой-нибудь и смотреть сколько туда сколько сюда идет

**Comment by MrTold11** [comment]
Дак вот, вроде бы ничего не выгружает, а оно не идет... Буду проверять трафик сейчас

**Comment by MrTold11** [comment]
![image](https://github.com/user-attachments/assets/e946056b-ec3a-4dde-a2e1-6beaf3a055a1)
Начну с трафика... Справа налево: служба активна, начинается загрузка стим, с момент просадки и увеличения (в 2 раза?) я перезапускаю службу. То есть после перезапуска идет в два раза больше трафика (???). Все само собой нормализуется через время (около минуты), трафик падает. Затем еще раз перезапускаю службу, на этот раз секунд через 15 все снова стало в норме.

Непонятно, почему вдруг трафик вырос в два раза, когда фактическая скорость была ниже.

**Comment by MrTold11** [comment]
[debug1.log](https://github.com/user-attachments/files/18127454/debug1.log) - логи, когда "все было плохо". В целом не так уж и плохо, все уперлось в запись логов.
[debug2.log](https://github.com/user-attachments/files/18127464/debug2.log) - логи, какими должны быть.

Пути вырезаны

**Comment by MrTold11** [comment]
Нет, система без примесей. Все еще не понял, почему в одном случае все работает хорошо, а в другом ломается...

**Comment by MrTold11** [comment]
Проблема решена, после перезапуска службы никаких проблем не наблюдаю, нагрузка на CPU снизилась в несколько раз. Кайф! Большое спасибо

**Comment by bol-van** [comment]
Обход все еще работает ?

**Comment by MrTold11** [comment]
По общим проверкам да, все работает. TLS, QUIC, Discord UDP

**Comment by MrTold11** [comment]
> Внесен фильтр для исключения пустых исходящих ACK

Это в целом все правки, или будет еще что-то чего ждать в бандле? Поддерживаю свое окружение обновленным, так сказать

**Comment by bol-van** [comment]
См релиз нотес 69.7.
bundle вылит с 69.7
