### ISSUE TITLE
udp; fake,ipfrag2; dpi-desync-repeats=20.   Разрезанный фрагмент улетает внутри fake последовательности

### ISSUE THREAD

**Issue by AlexeiGHub** [bol-van/zapret#935]
Позиция отправки разрезанного пакета плавает.
Возможен сценарий даже fake между кусками.
OWRT 23.05
Уточню детали если сценарий будет неясен.

Это баг или фича?

**Comment by bol-van** [comment]
Скрипты запуска используются или руками поднимаются таблес и nfqws ?

**Comment by AlexeiGHub** [comment]
```
        local f
        local first_packet_only="$nft_connbytes 1"
	local desync="mark and $DESYNC_MARK == 0"
        
	f="udp length 156 @th,64,32 0x01000000  counter"

        nft_fw_nfqws_post "$f $desync $first_packet_only" "$f $desync $first_packet_only" $QNUM_WG
```
`
Inserting nftables ipv4 rule for nfqws postrouting (qnum 65403) : udp length 156 @th,64,32 0x01000000  counter mark and 0x40000000 == 0 ct original packets 1
`
Что не учел?

**Comment by bol-van** [comment]
По крайней мере в последней версии марк не нужен в хелперах. Там сама схема nftables исключает рекурсию по марку.
Если готовый скрипт 50-wg4all. connbytes здесь тоже не особо нужен, поскольку есть payload фильтр

```
        chain postnat {
                oifname @wanif udp length 156 @th,64,32 0x1000000 ip daddr != @nozapret meta mark set meta mark | 0x20000000 queue flags bypass to 65400
        }

        chain postnat_hook {
                type filter hook postrouting priority srcnat + 1; policy accept;
                meta mark & 0x40000000 == 0x00000000 jump postnat
        }

```

Еще раз проверил с wg4all и вашими параметрами. Все нормально у меня

**Comment by AlexeiGHub** [comment]
У меня еще старые скрипты, от 1.11.2024.
Спасибо, покопаюсь еще.

**Comment by AlexeiGHub** [comment]
> Фрагменты уходят фрагментами или обьединяются , как будто не было фрагментации ?

Нет,  все режет корректно, но очередность перемешана.

**Comment by bol-van** [comment]
nfqws дропает оригинальный пакет в очереди.
Но перед дропом, когда он еще на этапе вынесения вердикта, то есть не может уйти никуда, отсылает 22 пакета.
20 фейков и 2 фрагмента порезанного. Важно, чтобы они опять не попали в nfqueue, иначе может быть перемешана очередность и возникнуть дедлоки. Эту задачу решает desync mark bit.

Система получает 22 отсыла через raw сокеты. Дальше уже она решает как и когда они будут отосланы.
Если написать правила tc, кидать их в разные ведра с разными приоритетами по неким признакам, то можно изменить порядок отсылки.

**Comment by AlexeiGHub** [comment]
![изображение](https://github.com/user-attachments/assets/1a85f20e-f0e5-4e8d-9cea-0d8493a69aa5)

**Comment by AlexeiGHub** [comment]
> Нет ли sqm scripts или чего-то подобного ? 

Есть.




> В tc qdisc стандартный fq_codel на выходном интерфейсе ?

Нет.  CAKE, peace_of_cacke

**Comment by bol-van** [comment]
Попробуйте вырубить

**Comment by AlexeiGHub** [comment]
Это оно. Уже выключил.

**Comment by bol-van** [comment]
Тогда тут nfqws ни при делах. Сама система это делает по алгоритму qdisc

**Comment by AlexeiGHub** [comment]
Как решить эту фичу,  чтоб сохранить SQM?

**Comment by bol-van** [comment]
Разные qdisc попробовать.
У меня простой tbf проблем не вызывает

**Comment by AlexeiGHub** [comment]
Спасибо за помощь в решении вопроса.  Ваши опыт на высоте!

**Comment by AlexeiGHub** [comment]
Интересный нюанс проявился. Возможно Вам стоит подумать о мерах по недопущению этого перемешивания(если такое возможно)?  Как минимум отразить в доке.

**Comment by bol-van** [comment]
А что с этим сделаешь ? Бороться против себя самого ? Если юзер сам включил перемешивание, зачем nfqws будет с этим бороться ? Он ничего не знает об этом и не лезет в шейпер

**Comment by bol-van** [comment]
Кое-что уже сделано, но это не будет работать на всех дисциплинах.
На fifo должно по идее
```
		int pri=6;
		if (setsockopt(*sock, SOL_SOCKET, SO_PRIORITY, &pri, sizeof(pri)) == -1)
		{
			DLOG_PERROR("rawsend: setsockopt(SO_PRIORITY)");
			goto exiterr;
		}

```

**Comment by AlexeiGHub** [comment]
Мои соображения чтоб жестче закрепить реализацию логики  отсылки пакетов.
Не многие проверяют статистически результат работы программы. Думаю в основной массе мы все исходим из того что все происходит так как написано в документации. Я однозначно признаю что это в наименьшей степени зависит от вашей программы.  Но вы нередко компенсировали особенности работы среды.

**Comment by bol-van** [comment]
Если есть какие-то идеи как это можно рулить , через какие API в linux, скажите. Может я не знаю чего.
Конечно, кроме того, чтобы искуственно лезть и вырубать в tc все дисциплины

**Comment by bol-van** [comment]
Вот это можно попробовать.
Проверите ? Могу собрать под нужную архитектуру, скажите только какую
```
       PACKET_QDISC_BYPASS (since Linux 3.14)
              By default, packets sent through packet sockets pass
              through the kernel's qdisc (traffic control) layer, which
              is fine for the vast majority of use cases.  For traffic
              generator appliances using packet sockets that intend to
              brute-force flood the network—for example, to test devices
              under load in a similar fashion to pktgen—this layer can
              be bypassed by setting this integer option to 1.  A side
              effect is that packet buffering in the qdisc layer is
              avoided, which will lead to increased drops when network
              device transmit queues are busy; therefore, use at your
              own risk.
```

**Comment by AlexeiGHub** [comment]
К сожалению я слаб в понимании, пока вот изучаю ваши наработки. 
Мое сообщение пока больше как призыв подумать над этим моментом.

**Comment by AlexeiGHub** [comment]
> Могу собрать под нужную архитектуру, скажите только какую

Собрать тестовую версию nfqws?

**Comment by AlexeiGHub** [comment]
У меня aarch64.

**Comment by AlexeiGHub** [comment]
Параллельная мысль.

Как вы оцениваете вероятность перемешивания на транзитных узлах в сети?
При каскадировании SOHO роутеров например?

**Comment by bol-van** [comment]
Если на них нет перемешивающих qdisc и нет забитого под завязку внешнего канала, то маловероятно

**Comment by bol-van** [comment]
Увы, означенная опция работает только с AF_PACKET. raw пакеты на уровне сетевого интерфейса L2.
На такой уровень nfqws не спускается, он работает с L3

**Comment by bol-van** [comment]
Если используется классовая дисциплина с приоритетами, можно сделать фильтр по desync марк и вывести в отдельную приоритетную ветку пакеты от nfqws. Но здесь нужны знания, мозги, вмешиваться в sqm скрипты. Не для юзера это вообщем

**Comment by AlexeiGHub** [comment]
> Если используется классовая дисциплина с приоритетами, можно сделать фильтр по desync марк и вывести в отдельную приоритетную ветку пакеты от nfqws. Но здесь нужны знания, мозги, вмешиваться в sqm скрипты. Не для юзера это вообщем

По изучаю.

**Comment by AlexeiGHub** [comment]
А может это быть как-то связано с разгрузкой адаптера?
У меня проблемы чередования наблюдаются в wwan.

**Comment by AlexeiGHub** [comment]
FQ_CODEL + TBF проблему можно воспроизвести если немного пропатчить количество повторов до значений 35+

**Comment by bol-van** [comment]
Я не изучал настолько глубоко. Но если сильно заморочиться, всегда можно наверх повесить HTB, где выделить по марку трафик от nfqws . На другое плечо повесить текущий root в любом его варианте.

**Comment by AlexeiGHub** [comment]
> FQ_CODEL + TBF проблему можно воспроизвести если немного пропатчить количество повторов до значений 35+

Решение - увеличить burst.

**Comment by AlexeiGHub** [comment]
Какое решение можете предложить для маркирования( fwmark) fake пакетов генерируемых программой?
Спасибо.
