### ISSUE TITLE
zapret no longer works on pfsense

### ISSUE THREAD

**Issue by bdnbje** [bol-van/zapret#94]
The latest update of pfsense 2.6 doesn't work with zapret anymore. I noticed it first when i updated from 2.5. then i did a fresh install of 2.6 and got the same results. the script loads but the packages (dvtws) are not loaded.

**Comment by bol-van** [comment]
I've installed pfsense 2.6 in vmware and haven't found any problems invoking precompiled dvtws from bins/freebsd-x64 or any other binaries.
At least it works for outgoing traffic from pfsense system itself. It unblocks my ISP successfully.
To make it work its necessary to
```
kldload ipfw
kldload ipdivert

```
I noticed that this version of BSD kernel does not have sysctls required to use ipfw in earlier versions
```
sysctl net.inet.ip.pfil.outbound=ipfw,pf
sysctl net.inet.ip.pfil.inbound=ipfw,pf
sysctl net.inet6.ip6.pfil.outbound=ipfw,pf
sysctl net.inet6.ip6.pfil.inbound=ipfw,pf

```
But it works without them

Do not expect any scripts like blockcheck or install_easy to work in pfsense

**Comment by bdnbje** [comment]
I removed the sysctl lines and i still couldn't get the website to open while powertunnel can with the default settings.
I checked netstat to see what ports are listening:
```
[2.6.0-RELEASE][admin@pfSense.home.arpa]/root: netstat -na | grep "LISTEN"
tcp6       0      0 fe80::a2ce:c8ff:.988   *.*                    LISTEN
tcp4       0      0 127.0.0.1.988          *.*                    LISTEN
tcp6       0      0 *.80                   *.*                    LISTEN
tcp4       0      0 *.80                   *.*                    LISTEN
tcp6       0      0 *.443                  *.*                    LISTEN
tcp4       0      0 *.443                  *.*                    LISTEN
tcp4       0      0 127.0.0.1.953          *.*                    LISTEN
tcp4       0      0 *.53                   *.*                    LISTEN
tcp6       0      0 *.53                   *.*                    LISTEN
tcp4       0      0 *.22                   *.*                    LISTEN
tcp6       0      0 *.22                   *.*                    LISTEN
```
port 989 which is supposed to be dvtws is not listening but is running
```
[2.6.0-RELEASE][admin@pfSense.home.arpa]/root: ps -aux | grep dvtws
2147483647 33479   0.0  0.1  10836  2260  -  Is   01:50    0:00.00 dvtws --daemon --port=989 --dpi-desync=split2
root       22156   0.0  0.1  11208  2488  0  S+   01:57    0:00.00 grep dvtws
```
these are my conf files if it helps
/usr/local/etc/rc.d/zapret.sh
```
#!/bin/sh

# this file should be placed to /usr/local/etc/rc.d and chmod 755

# prepare system

kldload ipfw
kldload ipdivert

# add ipfw rules and start daemon

ipfw delete 100
ipfw add 100 divert 989 tcp from any to any 80,443 out not diverted not sockarg
pkill ^dvtws$
dvtws --daemon --port=989 --dpi-desync=split2

pfctl -a zapret -f /etc/zapret.anchor
pkill ^tpws$
tpws --daemon --port=988 --enable-pf --bind-addr=127.0.0.1 --bind-iface6=ue1 --bind-linklocal=force --split-http-req=method --split-pos=2
```

**Comment by bol-van** [comment]
Why are you starting both dvtws and tpws ? Did you just copy-paste lines from readme without understanding what they do ?
tpws is not as easy to run on pfsense as nfqws. It requires editing some pfsense files which are definitely overwritten during reinstallation or upgrade of pfsense

I suggest you first remove zapret from pfsense and run blockcheck on a client system to discover which bypass strategies are working. Ensure you are not running in a VM which is NATed. Use bridge mode in a VM.

dvtws --debug helps to discover what dvtws is doing and whether traffic is actually redirected to dvtws

**Comment by bdnbje** [comment]
I dont seem to understand why this is not working on a fresh install of pfsense. i tried running on my arch box and it worked with tpws. used the blockcheck.sh to find the strategies to use.
i edit the filter.inc and zapret.anchor files like it was mentioned in the doc files
```
[2.6.0-RELEASE][root@pfSense.home.arpa]/root: pfctl -s nat
no nat proto carp all
nat-anchor "natearly/*" all
nat-anchor "natrules/*" all
nat on ue0 inet from 127.0.0.0/8 to any port = isakmp -> 10.15.155.7 static-port
nat on ue0 inet from 10.10.10.0/24 to any port = isakmp -> 10.15.155.7 static-port
nat on ue0 inet6 from ::1 to any port = isakmp -> (ue0) round-robin static-port
nat on ue0 inet from 127.0.0.0/8 to any -> 10.15.155.7 port 1024:65535
nat on ue0 inet from 10.10.10.0/24 to any -> 10.15.155.7 port 1024:65535
nat on ue0 inet6 from ::1 to any -> (ue0) port 1024:65535 round-robin
no rdr proto carp all
rdr-anchor "tftp-proxy/*" all
rdr-anchor "miniupnpd" all
rdr-anchor "zapret/*" all
rdr-anchor "tftp-proxy/*" all
[2.6.0-RELEASE][root@pfSense.home.arpa]/root: pfctl -s nat -a zapret
rdr pass on ue1 inet proto tcp from any to any port = http -> 127.0.0.1 port 988
rdr pass on ue1 inet proto tcp from any to any port = https -> 127.0.0.1 port 988
rdr pass on ue1 inet6 proto tcp from any to any port = http -> fe80::20c:29ff:5ae3:4821 port 988
rdr pass on ue1 inet6 proto tcp from any to any port = https -> fe80::20c:29ff:5ae3:4821 port 988
```

**Comment by bol-van** [comment]
Looks like this dont work

`rdr-anchor "zapret/*" all`

and this works

`rdr-anchor "zapret" all`

The reason is unknown

**Comment by bdnbje** [comment]
> Looks like this dont work
> 
> `rdr-anchor "zapret/*" all`
> 
> and this works
> 
> `rdr-anchor "zapret" all`
> 
> The reason is unknown

okay can confirm changing zapret/* to zapret fixed it.
