### ISSUE TITLE
НЕ скачивайте здесь вирусы!!! / DO NOT download viruses here!!!

### ISSUE THREAD

**Issue by Neon228daun** [bol-van/zapret#949]
Создатель данной программы для обхода блокировок рунета сообщи мне пожалуйста почему в архиве трояны???
The creator of this program for bypassing the Runet blocking, please tell me why there are trojans in the archive???

![image](https://github.com/user-attachments/assets/e58811d0-f506-4e97-b9a1-7549882d10e1)

![image](https://github.com/user-attachments/assets/69360aa5-0098-4dd2-9607-8834d8deb800)

![image](https://github.com/user-attachments/assets/61d8d0c1-8c1a-4811-8e23-57c84df32578)

**Comment by rscx-r1** [comment]
оправдываешь ник, почитай что такое Wacatac.D!ml и не засирай ишью этим

**Comment by Neon228daun** [comment]
> оправдываешь ник, почитай что такое Wacatac.B!ml и не засирай ишью этим
я сейчас через virus total проверил мне сказали что там вирусы

**Comment by Neon228daun** [comment]
> оправдываешь ник, почитай что такое Wacatac.B!ml и не засирай ишью этим

иди нахуй

**Comment by bol-van** [comment]
Пошел к черту идиот

**Comment by plimut** [comment]
Не скачивайте эту программу она вам не нужна! Перед загрузкой вы не прошли тест на адекватноть.
