### ISSUE TITLE
cron для своего списка

### ISSUE THREAD

**Issue by Alexey71** [bol-van/zapret#95]
Здравствуйте. Можно выключить прописывание в cron `0 12 */2 * * /opt/zapret/ipset/get_config.sh`, если используется фильтрация `hostlist` с моим списком через `zapret-hosts-user.txt` ?. Смысла нету обновлять свой список через cron, почему то после обновления openwrt и запуска `install_easy.sh` прописывает правило. И выбираю не качать список `do you want to auto download ip/host list (default : N) (Y/N) ? N`, по идеи в cron не должно создавать правило.

Или как то проверку сделать. Если выбираются такие пункты при установке через` install_easy.sh`
```
select filtering :
1 : none
2 : ipset
3 : hostlist
your choice (default : hostlist) : 3
selected : hostlist

do you want to auto download ip/host list (default : N) (Y/N) ? N
```
То не добавлять в cron правило

**Comment by bol-van** [comment]
Это не ошибка. Обновляется список nozapret/nozapret6

**Comment by bol-van** [comment]
К тому же если ничего не надо больше делать, то get_config.sh ничего и не делает
Вреда никакого нет

**Comment by bol-van** [comment]
Но система не только предназначена для использования с install_easy
Можно править конфиг и перезапускать.
И если крона не будет, то часть функционала не заработает

**Comment by Alexey71** [comment]
А я всегда удалял правило). Ладно

**Comment by Alexey71** [comment]
@bol-van Привет. 
1. Эта инструкция рабочая для последних версий openwrt с nftables? https://github.com/bol-van/zapret/blob/master/docs/wireguard/wireguard_iproute_openwrt.txt
2. Сервер Wireguard не поднимал. Запущен клиент wg с конфигом на удаленном сервере. Или надо именно свой?
3. Не получается ввести команду
```
root@OpenWrt:~# . /opt/zapret/init.d/openwrt/functions
root@OpenWrt:~# network_get_device DEVICE lan
root@OpenWrt:~# ipt PREROUTING -t mangle -i $DEVICE -p tcp --dport 443 -m set --match-set zapret dst -j MARK --set-mark 0x800/0x800
iptables v1.8.7 (nf_tables): Set zapret doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
root@OpenWrt:~# ipt PREROUTING -t mangle -i $DEVICE -m set --match-set ipban dst -j MARK --set-mark 0x800/0x800
iptables v1.8.7 (nf_tables): Set ipban doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by bol-van** [comment]
На новых openwrt можно доустановить iptables и ipset.
zapret адаптирован на поддержку и nftables, и iptables. В том числе даже на системах openwrt с nftables.
Если выбран режим iptables, то ipset скрипты создают ipset-ы. Если выбран nftables, то создаются nfset.
Соответственно, бесполезно пытаться гонять zapret в режиме nftables и прикручиваться своими iptables к ipset-ам, которые не будут созданы

**Comment by bol-van** [comment]
Еще на новых openwrt можно полностью отказаться от fw4, снести его нафиг
И установить fw3. Тогда оно будет себя вести как старые версии

**Comment by Alexey71** [comment]
Сейчас у меня работает zapret для обхода ркн блока + wireguard клиент для обхода геоблок. Так вот в wireguard клиенте просто пописываю ip адреса в разрешенных адресах в пирах. Хотел через домены в zapret - zapret-hosts-user-ipban.txt, чтобы ip адреса не вводить в клиенте wireguard. Но чего-то не получается. Zapret работает через nftables - tpws - hostlist.

**Comment by bol-van** [comment]
Есть только 2 варианта
или откатываться на iptables + fw3 и следовать моей инструкции, либо переписать iptables на nftables
при этом обязательно надо использовать хуки от zapret, потому что придется вписывать правила в nftable "zapret", не в свою отдельную, потому что nfset-ы принадлежат только определенной таблице

**Comment by bol-van** [comment]
Приведу пример моих собственных хуков
это не готовое решение или рецепт, просто с чего начать

/opt/zapret/config
INIT_FW_POST_UP_HOOK="/etc/firewall.zapret.hook.post_up"

cat /etc/firewall.zapret.hook.post_up
```
#!/bin/sh

ZAPRET_NFT_TABLE=zapret

cat << EOF | nft -f - 2>/dev/null
 delete chain inet $ZAPRET_NFT_TABLE my_output
 delete chain inet $ZAPRET_NFT_TABLE my_prerouting
EOF

cat << EOF | nft -f -
 add chain inet $ZAPRET_NFT_TABLE my_output { type route hook output priority mangle; }
 flush chain inet $ZAPRET_NFT_TABLE my_output
 add rule inet $ZAPRET_NFT_TABLE my_output oifname @wanif ip daddr @ipban meta mark set mark or 0x300000

 add chain inet $ZAPRET_NFT_TABLE my_prerouting { type filter hook prerouting priority mangle; }
 flush chain inet $ZAPRET_NFT_TABLE my_prerouting
 add rule inet $ZAPRET_NFT_TABLE my_prerouting iifname @lanif ip daddr @ipban meta mark set mark or 0x100000
EOF
```
