### ISSUE TITLE
Debian 11 ошибка установки insatll_easy.sh: required utilities exist : curl ip6tables ipset iptables

### ISSUE THREAD

**Issue by plimut** [bol-van/zapret#950]
ОС Debian 11 zapret v69.8

Невозможно начать процедуру инициализации по причине отсутствия пакета ip6tables, он уже является частью iptables,
как быть?

root@GATEWAY:/opt/zapret# ./install_prereq.sh
* checking system
system is based on systemd
* checking privileges

select firewall type :
1 : iptables
2 : nftables
your choice (default : iptables) : 1
selected : iptables
* checking prerequisites
required utilities exist : curl ip6tables ipset iptables

press enter to continue

root@GATEWAY:/opt/zapret# ip6tables
ip6tables v1.8.7 (legacy): no command specified
Try `ip6tables -h' or 'ip6tables --help' for more information.

======================================================

root@GATEWAY:/opt/zapret# apt list | grep iptables

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

arno-iptables-firewall/oldstable 2.1.1-2 all
golang-github-coreos-go-iptables-dev/oldstable 0.5.0-1 all
iptables-converter-doc/oldstable 0.9.8-1.2 all
iptables-converter/oldstable 0.9.8-1.2 all
iptables-netflow-dkms/oldstable 2.5.1-2 amd64
iptables-persistent/oldstable 1.0.15 all
**iptables/oldstable,now 1.8.7-1 amd64 [установлен]**
libiptables-chainmgr-perl/oldstable 1.6-2 all
libiptables-parse-perl/oldstable 1.6-2 all
miniupnpd-iptables/oldstable 2.2.1-1 amd64
python-iptables-doc/oldstable 1.0.0-1 all
python3-iptables/oldstable 1.0.0-1+b2 amd64
root@GATEWAY:/opt/zapret#

**Comment by bol-van** [comment]
Вряд ли проблема в том, о чем вы подумали.
Пакет ip6tables не ставится.
Сам сообщение "required utilities exist" уже означает успешный проход проверки реквизитов.
на этом функция завершается
почему дальше происходит выход это вопрос.
но на debian 12 у меня такого нет

**Comment by plimut** [comment]
Прошу прощения, видимо кофе с утра не попил, действительно, перезапустил терминал и все пошло, тикет закрываем.
