### ISSUE TITLE
Спидтест для методов из blockcheck.sh

### ISSUE THREAD

**Issue by KatouMegumi-osu** [bol-van/zapret#96]
Некоторые методы очень сильно замедляют трафик, использовать их неприятно. Хотя, может и РКН что-то надурил.

**Comment by bol-van** [comment]
wssize и должен замедлять, особенно на соединениях с большим пингом
если мы тут собираемся что-то обсуждать, то больше конкретики

**Comment by KatouMegumi-osu** [comment]
Хорошо, понял.
