### ISSUE TITLE
(Android) nfqws: Не работает в других приложениях

### ISSUE THREAD

**Issue by sevcator** [bol-van/zapret#976]
Здравствуйте! Использую модуль от [ImMALWARE](https://github.com/ImMALWARE/zapret-magisk), сделал некоторые изменения которые не должны тронуть тот же функционал модуля. Android 13, Magisk Kitsune, iptables v1.8.7 (legacy), busybox имеется. Скрипт запускается /data/adb/service.d/zapret.sh, nfqws в /data/adb/modules/zapret. nfqws запущен и правила iptables установлены. Все сайты и все приложения работают на Wi-Fi (Ростелеком), на мобильном интернете (МТС) работает Discord и Chrome, в Chrome редко показывает ERR_CONNECTION_RESET. В приложениях по типу YTDLnis не работают заблокированные сайты в моем случае soundcloud.com, пишет: Connection reset by peer. Установил модуль dnscrypt-proxy, использовал iptables для перенаправления DNS, никакого результата кроме улучшенной работы nfqws. Пробывал для DNS правила с lineageos-clean-browsing, с модуля, с другого модуля. Ничего не помогает, однако dnsleaktest.com проходит и показывает другие DNS сервера (не моего провайдера). Отключал Android System WebView который был установлен в AOSP, держал установленный только из Play Market. Прикрепляю скриншоты (использовал браузер из другого приложения)

![photo_2024-12-21_16-31-03](https://github.com/user-attachments/assets/b9466504-a9e1-4276-8bf4-215354da79b4)
![photo_2024-12-21_16-31-11](https://github.com/user-attachments/assets/27a66256-9b1d-46da-b1d8-4985d6106b5c)
![photo_2024-12-21_16-31-08](https://github.com/user-attachments/assets/c6c516bc-352f-43e8-aa61-61d8e3db8e0d)
![photo_2024-12-21_16-36-29](https://github.com/user-attachments/assets/84cf74b6-4ce5-4591-bcc0-53df68e8c785)
![photo_2024-12-21_16-37-56](https://github.com/user-attachments/assets/ae559541-0dbc-4ed6-8a82-2a340ff272cc)

**Comment by Fenrir-0xFF** [comment]
[ImMALWARE](https://github.com/ImMALWARE/zapret-magisk), скомуниздил скрипт у меня, искромсал добавил непроверенные на множестре прошивок коды, после чего везде повыкладывал свой Magisk модуль на основе этого скрипта. Естественно повылазили у него повылазили баги которые он без понятия как исправлять. 

Поэтому поддержку Magisk пришлось делать мне. 
Оригинальный скрипт под андроид тут https://github.com/bol-van/zapret/discussions/872

**Comment by bol-van** [comment]
Да, это надо авторам писать, тк сборка
