### ISSUE TITLE
Обновление версии zapret на 1.69.8 Keenetic. nfq_create_queue(): Operation not permitted

### ISSUE THREAD

**Issue by Xeej** [bol-van/zapret#983]
хотел обновить версию запрета до последней, но при настройке ловлю ошибку, busybox entware, ставлю на роутер keenetic
Запуск с ошибкой на версии 1.69.8
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/c20577f9-a976-4eb9-b419-a5f226e59d72" />
nfq_create_queue(): Operation not permitted
Предварительно конечно же сохранил старую сборку, версию на которой пробовал уже не помню, но попробую на более старых и отпишусь в теме.

ни какие стратегии не прописывал, пытался копировать config и сам скрипт zapret(но он не именялся) из старой версии в новую.
пробовал убивать все процессы `killall -HUP nfqws` далее по новой ./install_easy.sh

Запуск старой установленной версии
<img width="1759" alt="image" src="https://github.com/user-attachments/assets/187c7652-5673-4658-83c8-1494d7d5e112" />

**Comment by Xeej** [comment]
только что заменил, что я использую `WS_USER=nobody` и ошибка возникает только при этой переменной. в старой версии таких проблем нет. если подскажете в каком файле лежит версия, я обязательно отпишусь, какая версия рабочаяя)

**Comment by Xeej** [comment]
Скрин с ошибкой, где я всего лишь разкоментировал WS_USER
1 запуск успешный, 2 запуск вываливается с ошибкой
<img width="1789" alt="image" src="https://github.com/user-attachments/assets/f19cdd86-34de-4f46-badf-6b012a852c73" />

**Comment by Xeej** [comment]
методом недолгого перебора, я определил, что для меня на текущий момент рабочая версия v68, все версии начиная с v69 возвращают ошибку `nfq_create_queue(): Operation not permitted` Поскольку запуск возможен только с закоментированной `#WS_USER=nobody`, а с такой конфигурацией ничего не работает на keenetic.

**Comment by lunedzy** [comment]
легче всего будет просто переустановить zapret с нуля, на новую версию.
сделать это крайне просто, тогда и проблем не будет

**Comment by Xeej** [comment]
я это и сделал, предварительно переложил в папочку старый запрет, версии начиная с v69 не запускаются

**Comment by bol-van** [comment]
такая ошибка обычно когда уже есть процесс на той же очереди
посмотрите pidof nfqws
попробуйте nfqws --qnum 111

**Comment by Xeej** [comment]
это правда два процесса была 814 и 823. почему то я думал что killall должен был все процессы прибить, и не проверел
