### ISSUE TITLE
Fedora Linux не поддерживает rc-update

### ISSUE THREAD

**Issue by desiregn** [bol-van/zapret#99]
Я попробовал вместо rc-update

```sh
rc-update add zapret
```
использовать chkconfig 

```sh
$ chkconfig --add zapret
service zapret does not support chkconfig
```

>**update-rc.d doesn't exist on Red Hat distros such as Fedora/CentOS/etc**. The equivalent would be to use chkconfig, eg.
https://unix.stackexchange.com/questions/282713/convert-update-rc-d-command-into-chkconfig

**Comment by bol-van** [comment]
Fedora давно использует systemd. О какой версии идет речь ?

**Comment by desiregn** [comment]
> Fedora давно использует systemd. О какой версии идет речь ?
Fedora 34 (Workstation Edition)

**Comment by bol-van** [comment]
Systemd с fedora 15
chkconfig и прочая обвязка от sysvinit - это все только для совместимости
install_easy должен работать

**Comment by bol-van** [comment]
Если речь идет о silverblue (read only root), то там придется ручками кое-что сделать

**Comment by desiregn** [comment]
> install_easy должен работать

Я думал что получу тоже самое. Попробую попозже и отпишусь.

**Comment by desiregn** [comment]
@bol-van закрывай issue. Поставилось. Правда не работает и были ошибки (но это уже другой вопрос - мб в моей системе бардак).

**Comment by bol-van** [comment]
Оно и не заработает с одного тычка
Необходимо исследование и настройка
