### ISSUE TITLE
Winws multidisorder - нет разбиения по маркерам при ретрансмиссии

### ISSUE THREAD

**Issue by Pavel4e5** [bol-van/zapret#992]
Иногда при использовании multidisorder сервер присылает в ответ 3 SACK подряд, что приводит к ретрансмиссии частей обработанного multidisorder-ом пакета, при этом передаваемый снова пакет по абсолютным числовым маркерам разбивается, а по относительным (host, midsld) - нет. 
Обратил на это внимание, когда заметил что иногда (редко) при обращении к youtube.com срабатывает блокировка, причем всегда срабатывает только если есть ретрансмиссия и срабатывает после ретрансмиссии - т.е. сервер успевает прислать SACK и ACK, затем идет ретрансмиссия и стоп.
Возможно лучшим решением будет как-нибудь избавиться от ретрансмиссии в этом случае.
Проверялось на Windows 10, winws 69.8 , Firefox 133.0.3 параметры запуска: `winws --wf-tcp=443 --filter-tcp=443 --dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=tls_clienthello_www_google_com.bin --dpi-desync-split-pos=1,midsld`
Файл захвата такого случая приложен.
[mdis_block_retrans.zip](https://github.com/user-attachments/files/18245521/mdis_block_retrans.zip)

**Comment by bol-van** [comment]
Да, если TLS hello многопакетное, выполняется реассемблинг. Процедура выполняется только 1 раз на соединение, при повторах - нет.
В следующий раз реассемблинг не выполняется, поэтому маркеры применяются только к первому пакету.
Проблему понял. Буду смотреть что можно сделать

**Comment by bol-van** [comment]
Вы можете в броузере отключить КИБЕР, чтобы не было мультипакетного отсыла TLS hello.

**Comment by Pavel4e5** [comment]
У меня при тестировании были отключены Cyber и QUIC. И если ретрансмиссия, то всегда все содержимое пакета передавалось повторно. Но да это не всегда может быть.
А если делать вариант с удалением ретрансмиссии, то можно например при разбивке client hello запоминать номера получившихся сегментов и потом смотреть, если повторно идет пакет с тем же номером, то его отбрасывать, мониторинг прекратить когда пойдут пакеты за пределами client hello. Можно сделать опцией по ключу в командной строке, на случай, если действительно пакеты у кого-то теряются.
Если с повторной реконструкцией, да наверно это сложнее.
Но основная идея в том, что если мы например распилили SNI, то его в целом виде уже быть не должно )

**Comment by bol-van** [comment]
В cap файле кибер
TLS Record length 2467

**Comment by Pavel4e5** [comment]
Да, действительно, я как-то пропустил что со 132 версии Firefox они включили его по умолчанию. Проверю без него. Так же интересно использует ли kyber Android TV. Хотя при ретрансмиссии проблема все равно остается. Но если это пока не очень актуально для большинства то наверно можно закрыть issue.

**Comment by Pavel4e5** [comment]
Да, действительно, я как-то пропустил что со 132 версии Firefox они включили его по умолчанию. Проверю без него. Так же интересно использует ли kyber Android TV. Хотя при ретрансмиссии проблема все равно остается. Но если это пока не очень актуально для большинства то наверно можно закрыть issue.

**Comment by Pavel4e5** [comment]
Да, вы правы, без kyber все нормально, так же клиенты для Android и Android  TV (в Nox player) тоже пока не используют kyber. Наверно в будущем, когда kyber нельзя будет отключить, это будет иметь смысл, а пока тему можно закрыть наверно.
[retrans_no_kyber.zip](https://github.com/user-attachments/files/18247064/retrans_no_kyber.zip) (`--dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=tls_clienthello_www_google_com.bin --dpi-desync-split-pos=1,midsld,endhost,1000`)

**Comment by bol-van** [comment]
Проверил у себя.
SACK и ACK приходят пачкой, так что ось не начинает ретрансмиссии
У вас там явно задержка идет. Пакеты в обратном порядке отправляются пачкой и приходить тоже должны пачкой, но возвращается лишь SACK, а значит часть пакетов вероятно задерживается DPI. Должно быть пытается реконструировать.
Может другой вид DPI стоит с несколько иным алгоритмом реконструкции.
Такое стабильно каждый раз случается или только иногда ? Какая частота ?

**Comment by bol-van** [comment]
Под cygwin собрать несложно. docs/compile/build_howto_windows.txt

Можете поправить protocol.c и собрать ?

```
size_t TLSPos(uint8_t posmarker, int16_t pos, const uint8_t *data, size_t sz)
{
	size_t elen;
	const uint8_t *ext, *p;
	size_t offset_host,len_host;
	ssize_t offset;

	switch(posmarker)
	{
		case PM_HOST:
		case PM_HOST_END:
		case PM_HOST_SLD:
		case PM_HOST_MIDSLD:
		case PM_HOST_ENDSLD:
		case PM_SNI_EXT:
			if (TLSFindExt(data,sz,0,&ext,&elen,false))

```

в последней строчке в TlsFindExt последний аргумент заменить на true (TLS Partial OK)

тогда должен работать с частичным TLS Hello. Если вдруг полностью SNI extension попадет в первый пакет, то будет применена разбивка по sld, если во второй - нет. Во втором случае может сработать DPI, который ищет тупо подстроку, но тут уже описанная в начале проблема повторной реконструкции на базе непонятно каких кусков

**Comment by Pavel4e5** [comment]
У меня если приходят подряд 3 или больше SACK, то всегда есть ретрансмиссия, но без kyber все фрагменты повторяются один к одному, и все проходит ок, см. предыдущий файл. Другого пока не увидел вчера, может нужно еще тестирование. 3 или больше SACK можно вызвать если только нарезать на достаточное количество кусков. 
С kyber, даже если стоит только `--dpi-desync-split-pos=1,midsld` где-то 50% может быть ретрансмиссия, и где-то 15% из этого блокировка.
Ниже 2 примера, обращение к одному и тому же ресурсу, с разницей в полсекунды, и тайминги вроде не особо отличаются, но в одном случае сервер отправил 2 SACK и 2 ACK а в другом случае 3 SACK и 1 ACK и вызвал ретрансмиссию без нарезки по SNI.
Параметры в этих примерах: kyber вкл., `--dpi-desync=fake,multidisorder --dpi-desync-autottl=1:2-10 --dpi-desync-fake-tls=tls_clienthello_www_google_com.bin --dpi-desync-split-pos=1,midsld`  
[mdis_kyber.zip](https://github.com/user-attachments/files/18251173/mdis_kyber.zip)

Собрать с изменениями попробую вечером.

**Comment by bol-van** [comment]
Можно попробовать зафлудить его фейками в начале с --dpi-desync-repeats=11
количество регулируется
они могут сечь только в X начальных пакетах

**Comment by Pavel4e5** [comment]
Windows 10 Pro 22H2 19045.5247
Да с добавочными фейками ретрансмиссий пока не увидел. 
[11_fake_kyber.zip](https://github.com/user-attachments/files/18251546/11_fake_kyber.zip)
В принципе заставить работать так или иначе пока не очень сложно, но я стремлюсь к минимализму ) . Особенно видя те конструкции, что пишут на форумах.

**Comment by Pavel4e5** [comment]
Windows 10 Pro 22H2 19045.5247
Результат с 11 фейками - ретрансмиссии с целым SNI есть, блокировок не заметил пока.
[11_fake_kyber.zip](https://github.com/user-attachments/files/18251794/11_fake_kyber.zip)
В принципе так или иначе работать заставить пока не сложно, но я стремлюсь к минимализму) , особенно видя те конструкции, что пишут на форумах.

**Comment by bol-van** [comment]
А на других сайтах, кроме ютуба есть блокировки от ретрансов ? Если без фейк репитов и с кибером
Подозреваю, что там просто стоит правило для X начальных пакетов если подстрока "googlevideo" или "youtube" => block

**Comment by bol-van** [comment]
А еще если есть возможность  неплохо было бы на linux попробовать
Или из виртуалки с bridge, или с флэшки. Как угодно

**Comment by bol-van** [comment]
В 11_fake_kyber нет ретрансмиссий
Погоняйте еще в таком режиме и посмотрите случаются ли они
У меня большое подозрение, что они вызваны задержками пакетов на DPI. А когда интервал X пакетов превышен, то пропускают молча

**Comment by Pavel4e5** [comment]
11_fake_kyber  - у вас файл размером 37760 ? просто сначала я выложил не тот файл, потом пересоздал сообщение

**Comment by bol-van** [comment]
Да, смотрел старый. В новом есть ретрансмиссия.

**Comment by Pavel4e5** [comment]
На других сайтах кроме youtube.com и сопутствующих не видел пока, но например на play.google.com встречается. Также интересно что на *.googlevideo.com нет ретрансмиссий. Стратегия для всех одна.
На других системах да, надо будет попробовать. У меня сейчас на роутере стоит youtubeunblock, и там вроде затупов не было, tcpdump-ом не смотрел пока.

**Comment by Pavel4e5** [comment]
Насчет *.googlevideo.com - возможно дело в том что большинство запросов идет к локальному кэшу, который у меня стоит до коробки.

**Comment by bol-van** [comment]
Удалось мне на другом подключении воспроизвести.
Сделал патч как описал выше, вылил исходники

Вот готовый exe
[winws.zip](https://github.com/user-attachments/files/18252157/winws.zip)

**Comment by bol-van** [comment]
> на play.google.com встречается.

Вот о чем и речь. Они закатали особые правила для подсетей google.
Тк они не могут рубануть целую АСку пока, они решили выделять оттуда трафик ютубе.
После того, как провайдеры стали сами обходить эту блокировку, ввели дополнительное правило искать подстроку в первых X пакетах

**Comment by Pavel4e5** [comment]
Быстро проверил - при ретрансмиссии все вроде разбивается корректно, Более подробно смогу потестировать наверно часов через 5.
[kyber_new_version.zip](https://github.com/user-attachments/files/18252267/kyber_new_version.zip)

**Comment by bol-van** [comment]
Еще важен броузер . Лиса или хромиум
Лиса не рандомизирует tls hello. У нее всегда SNI в первом пакете, потому должно всегда резаться по хосту.
В хрома рандом. Может через раз во 2-й попадать, и там не будет разрезано

**Comment by Pavel4e5** [comment]
Еще потестировал новую версию - если SNI в первом пакете, то все всегда как в примере выше. Если chromium based browser, и SNI во втором пакете, то при ретрансмиссии обратно собирается первый пакет и предается повторно, даже если маркеры там абсолютные. Второй же пакет или его фрагменты не передаются повторно вообще. Другого поведения в этом случае пока не заметил.
[kyber_chrome_new.zip](https://github.com/user-attachments/files/18253534/kyber_chrome_new.zip)
Параметры при тестировании: `--dpi-desync=fake,multidisorder --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=tls_clienthello_www_google_com.bin --dpi-desync-split-pos=1,30,sniext,midsld`

**Comment by bol-van** [comment]
Передается только то, на что не пришло SACK.
Подробнее см --debug лог

**Comment by Pavel4e5** [comment]
Ясно, как бы то ни было, сейчас проблем с блокировкой вроде нет, спасибо.
