### ISSUE TITLE
Перестало работать на Wifire (Санкт-Петербург)?

### ISSUE THREAD

**Issue by popov654** [bol-van/zapret#993]
Возможно, я что-то делаю неправильно, но скрипт отказывается открывать не только youtube, но и вообще любой сайт. Да, у меня действительно сборка, но эта же сборка прекрасно открывала и сайты, и видео на YouTube на Windows 10 ещё неделю назад. Скажите пожалуйста, в чём может быть дело?

Параметры запуска скину вечером, сейчас к сожалению нет доступа к компьютеру.

**Comment by ivdeveloper86** [comment]
Сейчас все экстрасенсы к сожалению в отпуске, подождем более подробной инфы от вас.

**Comment by electrifying** [comment]
да, у меня действительно сборка

Но тут не репозиторий сборки

**Comment by popov654** [comment]
Прошу прощения, оно заработало, видимо, требовался рестарт ОС (хотя раньше работало сразу без него, странно).
